(*
   $Id: mim.exp,v 1.3 2002/12/05 14:44:19 mikeward Exp $
   N1650 - ISO/CD-TS - 10303-1214 system_breakdown - EXPRESS MIM
*)

(* UNDER DEVELOPMENT *)

SCHEMA System_breakdown_mim;

USE FROM Product_breakdown_mim;    -- ISO/CD-TS 10303-1248

ENTITY system_breakdown_context
  SUBTYPE OF (breakdown_context);
END_ENTITY;

ENTITY system_element_usage
  SUBTYPE OF (breakdown_element_usage);
END_ENTITY;

END_SCHEMA;  -- System_breakdown_mim
