(*
   $Id: mim.exp,v 1.7 2005/02/28 13:42:07 liutkus Exp $
   ISO TC184/SC4/WG12 N3397 - ISO/CD-TS 10303-1664 Device marking - EXPRESS MIM
*)


SCHEMA Device_marking_mim;

	USE FROM Approval_mim;	-- ISO/TS 10303-1012
	USE FROM Characteristic_mim;	-- ISO/TS 10303-1654
	USE FROM Conductivity_material_aspects_mim;	-- ISO/TS 10303-1756
	USE FROM Part_template_2d_shape_mim;	-- ISO/TS 10303-1716
	USE FROM Part_template_3d_shape_mim;	-- ISO/TS 10303-1717
	USE FROM Part_template_non_planar_shape_mim;	-- ISO/TS 10303-1719
	USE FROM Person_organization_mim;	-- ISO/TS 10303-1011
	USE FROM Physical_unit_2d_shape_mim;	-- ISO/TS 10303-1726
	USE FROM Physical_unit_3d_shape_mim;	-- ISO/TS 10303-1727
	USE FROM Product_version_mim;	-- ISO/TS 10303-1018
	USE FROM Specification_document_mim;	-- ISO/TS 10303-1747
	USE FROM Styled_text_mim;	-- ISO/TS 10303-1750
	
	USE FROM Presentation_definition_schema(annotation_text_occurrence);

TYPE dm_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH 
     (representation);
END_TYPE;

TYPE dm_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH 
     (representation);
END_TYPE;

RULE marking_constraint FOR ( representation );
WHERE
  WR1: SIZEOF(QUERY(rep <* representation |
       ((rep\representation.name = 'marking')
       AND (SIZEOF(QUERY(pdr <* USEDIN(rep,
       'DEVICE_MARKING_MIM.'
        + 'PROPERTY_DEFINITION_REPRESENTATION.USED_REPRESENTATION') |
       ('DEVICE_MARKING_MIM.'
        + 'SHAPE_ASPECT' IN TYPEOF(pdr.definition)))) > 0))
       AND NOT (SIZEOF(QUERY(place <* rep.items |
       (('DEVICE_MARKING_MIM.'
        + 'PLACEMENT' IN TYPEOF (place))
       AND (place\representation_item.name = 'marking location'))
       )) = 1)
       )) = 0;
END_RULE;
	
END_SCHEMA;

