(*
   $Id: arm.exp,v 1.10 2005/11/08 11:03:00 thomasrthurman Exp $
   ISO TC184/SC4/WG3 N1641 - ISO/CD-TS 10303-1614 AP210 functional decomposition - EXPRESS ARM
*)

SCHEMA Ap210_functional_decomposition_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Electrical_network_definition_arm;	-- ISO/TS 10303-1665
	USE FROM Thermal_network_definition_arm;	-- ISO/TS 10303-1752
END_SCHEMA;

