(*
   $Id: mim.exp,v 1.5 2005/02/04 17:01:45 budreckytej Exp $
   ISO TC184/SC4/WG12 N1642 - ISO/CD-TS 10303-1614 Ap210 functional decomposition - EXPRESS MIM
*)


SCHEMA Ap210_functional_decomposition_mim;
	USE FROM Ap210_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Electrical_network_definition_mim;	-- ISO/TS 10303-1665
	USE FROM Thermal_network_definition_mim;	-- ISO/TS 10303-1752
END_SCHEMA;

