(*
   $Id: mim.exp,v 1.8 2005/11/08 11:03:00 thomasrthurman Exp $
   ISO TC184/SC4/WG3 N1642 - ISO/CD-TS 10303-1614 AP210 functional decomposition - EXPRESS MIM
*)


SCHEMA Ap210_functional_decomposition_mim;
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Electrical_network_definition_mim;	-- ISO/TS 10303-1665
	USE FROM Thermal_network_definition_mim;	-- ISO/TS 10303-1752
END_SCHEMA;

