(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 functional decomposition - EXPRESS MIM
*)


SCHEMA Ap210_functional_decomposition_mim;
	USE FROM AP210_product_data_management_mim;
	USE FROM Functional_decomposition_to_assembly_design_mim;
	USE FROM Functional_decomposition_to_design_mim;
	USE FROM Functional_decomposition_to_interconnect_design_mim;
	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_mim;
	USE FROM Network_functional_design_view_mim;
END_SCHEMA;

