(*
   $Id: arm.exp,v 1.6 2004/12/16 15:38:33 liutkus Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 assembly physical design - EXPRESS ARM
*)

SCHEMA Ap210_assembly_physical_design_arm;
   USE FROM AP210_product_data_management_arm;
   USE FROM Altered_part_arm;
   USE FROM Assembly_functional_interface_requirement_arm;
   USE FROM Assembly_module_macro_definition_arm;
   USE FROM Assembly_module_with_macro_component_arm;
   USE FROM Assembly_module_with_cable_component_2d_arm;   
   USE FROM Assembly_module_with_cable_component_3d_arm;
   USE FROM Assembly_module_with_subassembly_arm;
   USE FROM Assembly_shape_arm;
   USE FROM Assembly_2d_shape_arm;
   USE FROM Assembly_3d_shape_arm;
   USE FROM Characteristic_arm;
   USE FROM Chemical_substance_arm;
   USE FROM Cable_arm;
   USE FROM Design_specific_assignment_to_assembly_usage_view_arm;
   USE FROM Device_marking_arm;
   USE FROM Fill_area_arm;
   USE FROM Physical_unit_interconnect_definition_arm;

	TYPE assembly_module_or_assembly_group_component = 
		EXTENSIBLE GENERIC_ENTITY SELECT 
		(Assembly_module,
		Assembly_group_component);
	END_TYPE;

(** Assembly_module_with_packaged_connector_component_arm and 
Assembly_module_with_interconnect_component_arm  - most likely in some Assembly CC *)
	SUBTYPE_CONSTRAINT component_interface_terminal_subtypes FOR Component_interface_terminal;     
		(ONEOF (Packaged_connector_component_interface_terminal,
		 Interconnect_component_interface_terminal));
	END_SUBTYPE_CONSTRAINT;

(** most likely some Assembly_module CC *)
	SUBTYPE_CONSTRAINT packaged_part_subtypes FOR Packaged_part; 
	    (ONEOF (Minimally_defined_connector, -- Assembly_functional_interface_requirement_arm
	 	Packaged_connector) ANDOR -- Packaged_connector_model_arm
	 	Altered_packaged_part); -- Altered_part_arm
	END_SUBTYPE_CONSTRAINT;
	
	(** It most likely should be in Assembly_module CC *)
	SUBTYPE_CONSTRAINT physical_component_subtypes FOR Physical_component;  
		(ONEOF (Assembly_module_component, --Assembly_module_with_subassembly_arm
		Bare_die_component, -- Assembly_module_design_arm
		Cable_component, -- Assembly_module_with_cable_component_arm
		Interconnect_module_component, -- Assembly_module_with_interconnect_component_arm
		Packaged_component, -- Assembly_module_design_arm
		Routed_interconnect_component, -- Assembly_module_design_arm
		Routed_physical_component)); -- Assembly_module_design_arm 
	END_SUBTYPE_CONSTRAINT;
	
	(** It most likely should be in Assembly_module CC *)
	SUBTYPE_CONSTRAINT part_usage_view_subtypes FOR Part_usage_view;  
	    ONEOF (Package,
		 Bare_die,
		 Cable_usage_view,
		 Packaged_part,
		 Assembly_module_usage_view,
		 Interconnect_module_usage_view);
	END_SUBTYPE_CONSTRAINT;

   
END_SCHEMA;

