(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 assembly physical design - EXPRESS MIM
*)


SCHEMA Ap210_assembly_physical_design_mim;
	USE FROM AP210_product_data_management_mim;
	USE FROM Assembly_2d_shape_mim;
	USE FROM Assembly_3d_shape_mim;
	USE FROM Assembly_module_design_mim;
	USE FROM Assembly_shape_mim;
END_SCHEMA;

