(*
   $Id: mim.exp,v 1.2 2004/12/13 15:27:05 budreckytej Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 assembly physical design - EXPRESS MIM
*)


SCHEMA Ap210_assembly_physical_design_mim;
   USE FROM AP210_product_data_management_mim;
   USE FROM Altered_part_mim;
   USE FROM Assembly_functional_interface_requirement_mim;
   USE FROM Assembly_module_macro_definition_mim;
   USE FROM Assembly_module_with_macro_component_mim;
   USE FROM Assembly_module_with_cable_component_2d_arm;   
   USE FROM Assembly_module_with_cable_component_3d_mim;
   USE FROM Assembly_module_with_subassembly_mim;
   USE FROM Assembly_shape_mim;
   USE FROM Assembly_2d_shape_mim;
   USE FROM Assembly_3d_shape_mim;
   USE FROM Characteristic_mim;
   USE FROM Chemical_substance_mim;
   USE FROM Cable_mim;
   USE FROM Design_specific_assignment_to_assembly_usage_view_mim;
   USE FROM Device_marking_mim;
   USE FROM Fill_area_mim;
   USE FROM Physical_unit_interconnect_definition_mim;
END_SCHEMA;

