(*
 $Id: arm.exp,v 1.1 2002/03/22 10:24:08 robbod Exp $
*)

{ iso standard 10303 part (11) version (4) }

SCHEMA Activity_method_arm;

USE FROM Document_assignment_arm;

TYPE activity_method_documented_element_select = SELECT BASED_ON documented_element_select WITH
  (Activity_method);
END_TYPE;

ENTITY Activity_method;
  consequence : OPTIONAL STRING;
  
  description : OPTIONAL STRING;
  name : STRING;
  purpose : STRING;
END_ENTITY;

END_SCHEMA;
