(* $Id: arm.exp,v 1.3 2002/06/17 23:01:27 thendrix Exp $   
N1260 ISO/TS 10303-1068 Constructive solid geometry 3d *)
SCHEMA Constructive_solid_geometry_3d_arm;

USE FROM Constructive_solid_geometry_arm;

TYPE boolean_operand_3d = SELECT BASED_ON boolean_operand WITH
  (Half_space_solid);
END_TYPE;

TYPE csg_primitive_3d = SELECT BASED_ON csg_primitive WITH
  (Block,
   Cyclide_segment_solid,
   Eccentric_cone,
   Ellipsoid,
   Faceted_primitive,
   Rectangular_pyramid,
   Right_angular_wedge,
   Right_circular_cone,
   Right_circular_cylinder,
   Sphere,
   Torus);
END_TYPE;

ENTITY Block
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Convex_hexahedron
SUBTYPE OF (Faceted_primitive);
END_ENTITY;

ENTITY Csg_shape_representation_3d
SUBTYPE OF (Csg_shape_representation);
END_ENTITY;

ENTITY Cyclide_segment_solid
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Eccentric_cone
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Ellipsoid
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Faceted_primitive
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Half_space_solid
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Rectangular_pyramid
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Right_angular_wedge
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Right_circular_cone
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Right_circular_cylinder
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Sphere
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Tetrahedron
SUBTYPE OF (Faceted_primitive);
END_ENTITY;

ENTITY Torus
SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

END_SCHEMA;
