(*
 $Id: arm.exp,v 1.17 2009/12/12 13:13:23 lothartklein Exp $
ISO TC184/SC4/WG12 N6878 - ISO/TS 10303-1068 Constructive solid geometry 3d - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N6228
*) 


SCHEMA Constructive_solid_geometry_3d_arm;

USE FROM Elemental_geometric_shape_arm;    -- ISO/TS 10303-1004
USE FROM Primitive_solids_arm; -- ISO/TS 10303-1801

ENTITY Csg_model
  SUBTYPE OF (Geometric_model);
END_ENTITY;

END_SCHEMA;  -- Constructive_solid_geometry_3d_arm
