(*
 $Id: mim.exp,v 1.15 2009/12/21 15:14:00 liutkuviene Exp $
ISO TC184/SC4/WG12 N7823 - ISO/TS 10303-1068 Constructive solid geometry 3d - EXPRESS MIM
Supersedes ISO TC184/SC4/WG12 N6879
*) 


SCHEMA Constructive_solid_geometry_3d_mim;

USE FROM aic_csg;    -- ISO 10303-515
USE FROM Elemental_geometric_shape_mim;    -- ISO/TS 10303-1004
USE FROM Primitive_solids_mim; -- ISO/TS 10303-1801

END_SCHEMA;  -- Constructive_solid_geometry_3d_mim
