(*
$Id: arm.exp,v 1.32 2012/10/12 16:18:31 lothartklein Exp $
ISO TC184/SC4/WG12 N7729 - ISO/TS 10303-1026 Assembly structure - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N6111
*) 


SCHEMA Assembly_structure_arm;

USE FROM Product_view_definition_arm;    -- ISO/TS 10303-1019
USE FROM Product_view_definition_reference_arm; -- ISO/TS 10303-1738

USE FROM Value_with_unit_arm;    -- ISO/TS 10303-1054

TYPE product_view_definition_or_reference = SELECT (
    Product_view_definition, 
    Generic_product_view_definition_reference);
END_TYPE;

ENTITY Assembly_component_relationship
  ABSTRACT SUPERTYPE OF (ONEOF (Multi_level_reference_designator,
  								Next_assembly_usage,
                                Promissory_usage,
                                Component_upper_level_identification))
  SUBTYPE OF (Product_occurrence_definition_relationship);
  location_indicator : OPTIONAL STRING;
  quantity : OPTIONAL Value_with_unit;
WHERE
  WR1: NOT(EXISTS(quantity)) OR ((NOT ('NUMBER' IN TYPEOF(quantity.value_component))) XOR (quantity.value_component > 0));
END_ENTITY;

ENTITY Component_upper_level_identification
  SUBTYPE OF (Assembly_component_relationship);
  upper_assembly_relationship : Assembly_component_relationship;
  sub_assembly_relationship : Next_assembly_usage;
UNIQUE
  UR1: upper_assembly_relationship, sub_assembly_relationship;
WHERE
  WR1: SELF :<>: upper_assembly_relationship;
  WR2: SELF\Product_occurrence_definition_relationship.relating_view :=: upper_assembly_relationship\Product_occurrence_definition_relationship.relating_view;
  WR3: SELF\Product_occurrence_definition_relationship.related_view :=: sub_assembly_relationship\Product_occurrence_definition_relationship.related_view;
  WR4: (upper_assembly_relationship\Product_occurrence_definition_relationship.related_view :=: sub_assembly_relationship\Product_occurrence_definition_relationship.relating_view) OR (SIZEOF (QUERY (pdr <* USEDIN (upper_assembly_relationship\Product_occurrence_definition_relationship.related_view , 'ASSEMBLY_STRUCTURE_ARM.PRODUCT_OCCURRENCE_DEFINITION_RELATIONSHIP.RELATED_VIEW') | pdr.relating_view :=: sub_assembly_relationship\Product_occurrence_definition_relationship.relating_view)) = 1);
  WR5: SIZEOF (['ASSEMBLY_STRUCTURE_ARM.NEXT_ASSEMBLY_USAGE', 'ASSEMBLY_STRUCTURE_ARM.COMPONENT_UPPER_LEVEL_IDENTIFICATION'] * TYPEOF(upper_assembly_relationship)) = 1;
END_ENTITY;

ENTITY Multi_level_reference_designator
  SUBTYPE OF (Assembly_component_relationship);
  location : LIST[1:?] OF UNIQUE Next_assembly_usage;
DERIVE
  SELF\Product_occurrence_definition_relationship.relating_view RENAMED root_node 
     : Product_view_definition := location[1]\Product_occurrence_definition_relationship.relating_view;
  SELF\Product_occurrence_definition_relationship.related_view RENAMED leaf_node 
    : product_view_definition_or_reference := location[HIINDEX(location)]\Product_occurrence_definition_relationship.related_view;
UNIQUE
  UR1 : location;
END_ENTITY;

ENTITY Next_assembly_usage
  SUBTYPE OF (Assembly_component_relationship);
END_ENTITY;

ENTITY Product_occurrence_definition_relationship
  ABSTRACT SUPERTYPE;
  relating_view : product_view_definition_or_reference;
  related_view : product_view_definition_or_reference;
END_ENTITY;

ENTITY Promissory_usage
  SUBTYPE OF (Assembly_component_relationship);
END_ENTITY;

SUBTYPE_CONSTRAINT assembly_component_relationship_constraint FOR Assembly_component_relationship;
  ABSTRACT SUPERTYPE;
  TOTAL_OVER (Component_upper_level_identification, 
  			  Multi_level_reference_designator,
              Next_assembly_usage, 
              Promissory_usage);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;  -- Assembly_structure_arm
(*
   $Id: arm.exp,v 1.25 2012/10/11 05:49:08 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7825 - ISO/TS 10303-1651 Basic curve - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N77388
*)

SCHEMA Basic_curve_arm;

USE FROM Basic_geometry_arm;-- ISO/TS 10303-1652
USE FROM External_item_identification_assignment_arm;-- ISO/TS 10303-1128

SUBTYPE_CONSTRAINT curve_subtypes FOR Bounded_curve;         
  ONEOF (Composite_curve, Trimmed_curve);    
END_SUBTYPE_CONSTRAINT;

TYPE curve_transition_code = ENUMERATION OF
  (discontinuous,
   continuous,
   cont_same_gradient,
   cont_same_gradient_same_curvature);
END_TYPE;  

TYPE closed_curve = EXTENSIBLE GENERIC_ENTITY SELECT
  (Circle,
   Closed_composite_curve);
END_TYPE;

ENTITY Closed_composite_curve
  SUBTYPE OF (Composite_curve);
END_ENTITY;
  
ENTITY Composite_curve
  SUBTYPE OF (Bounded_curve);
  curve_segment : LIST[1:?] OF UNIQUE Composite_curve_segment;
END_ENTITY;

ENTITY Composite_curve_segment;
  transition   : curve_transition_code;
  same_sense   : BOOLEAN;
  segment_curve : Bounded_curve;
INVERSE
  using_curves : SET[1:?] OF Composite_curve FOR curve_segment;
END_ENTITY;

ENTITY Trimmed_curve
  SUBTYPE OF (Bounded_curve);
  basis_curve : Curve;
  start_point : Cartesian_point;
  end_point : Cartesian_point;
END_ENTITY;

END_SCHEMA;

(*
   $Id: arm.exp,v 1.7 2012/10/11 05:49:04 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7951 - ISO/TS 10303-1773 Basic data representation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N6216
*)
SCHEMA Basic_data_representation_arm;

USE FROM Extended_date_arm; -- ISO/TS 10303-1776

USE FROM Foundation_representation_arm; -- ISO/TS 10303-1006

  ENTITY Boolean_representation_item
    SUBTYPE OF (Representation_item);
      the_value : BOOLEAN;
  END_ENTITY;

  ENTITY Compound_representation_item 
    ABSTRACT SUPERTYPE OF (ONEOF (Sequence_representation_item, Set_representation_item)) 
    SUBTYPE OF (Representation_item); 
  END_ENTITY; 

  ENTITY Date_time_representation_item
    SUBTYPE OF (Representation_item);
      the_value : date_or_date_time_select;
  END_ENTITY; 

  ENTITY Integer_representation_item
    SUBTYPE OF (Representation_item);
      the_value : INTEGER;
  END_ENTITY;

  ENTITY Logical_representation_item
    SUBTYPE OF (Representation_item);
      the_value : LOGICAL;
  END_ENTITY;

  ENTITY Rational_representation_item
    SUBTYPE OF (Representation_item);
      numerator   : INTEGER;
      denominator : INTEGER;
  END_ENTITY;

  ENTITY Real_representation_item
    SUBTYPE OF (Representation_item);
      the_value   : REAL;
  END_ENTITY;

  ENTITY Sequence_representation_item
    SUBTYPE OF (Compound_representation_item);
      the_value   : LIST OF Representation_item;
  END_ENTITY;

  ENTITY Set_representation_item
    SUBTYPE OF (Compound_representation_item);
      the_value   : SET OF Representation_item;
  END_ENTITY;

  SUBTYPE_CONSTRAINT representation_item_subtypes FOR Representation_item; 
	(ONEOF (Boolean_representation_item,
	  Compound_representation_item,
      Date_time_representation_item,
      Integer_representation_item,
      Logical_representation_item,
      Rational_representation_item,
      Real_representation_item));
  END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(*
$Id: arm.exp,v 1.25 2012/10/11 05:49:04 liutkuviene Exp $
ISO TC184/SC4/WG12 N7828 - ISO/TS 10303-1652 Basic geometry - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N7193
*) 

SCHEMA Basic_geometry_arm;

USE FROM Elemental_geometric_shape_arm;    -- ISO/TS 10303-1004

ENTITY Bounded_curve
   ABSTRACT SUPERTYPE
   SUBTYPE OF (Curve);
END_ENTITY;

ENTITY Bounded_surface
   ABSTRACT SUPERTYPE
   SUBTYPE OF (Surface);
END_ENTITY;

ENTITY Circle
   SUBTYPE OF (Conic);
   radius   : length_measure;
WHERE
   WR1: radius > 0.0;
END_ENTITY;

ENTITY Conic
   SUPERTYPE OF (ONEOF(Circle, Ellipse, Hyperbola, Parabola))
   SUBTYPE OF (Curve);
   position: Axis_placement;
END_ENTITY;

 ENTITY  Conical_surface
   SUBTYPE OF (Surface);
   position : Axis_placement_3d;
   radius     : length_measure;
   semi_angle : plane_angle_measure;
WHERE
   WR1: radius >= 0.0;
END_ENTITY;


ENTITY Curve
  SUPERTYPE OF (ONEOF(Conic, Line))
  SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Cylindrical_surface
   SUBTYPE OF (Surface);
    position : Axis_placement_3d;
   radius : length_measure;
WHERE
   WR1: radius > 0.0;
END_ENTITY;

ENTITY Ellipse
   SUBTYPE OF(Conic);
   first_semi_axis: length_measure;
   second_semi_axis: length_measure;
WHERE
   WR1: first_semi_axis > 0.0;
   WR2: first_semi_axis > 0.0;
END_ENTITY;
 
ENTITY Extruded_surface
   SUBTYPE OF (Swept_surface);
   extrusion_axis      : Direction;
END_ENTITY;

ENTITY Hyperbola
   SUBTYPE OF(Conic);
   semi_axis: length_measure;
   imaginary_semi_axis: length_measure;
WHERE
   WR1: semi_axis > 0.0;
   WR2: imaginary_semi_axis > 0.0;
END_ENTITY;


ENTITY Line
  SUBTYPE OF (Curve);
   point: Cartesian_point;
   line_direction: Direction;
END_ENTITY;

ENTITY Parabola
   SUBTYPE OF(Conic);
   focal_distance: length_measure;
WHERE
   WR1: focal_distance <> 0.0;
END_ENTITY;

ENTITY Plane
  SUBTYPE OF (Surface);
  position: Axis_placement_3d;
END_ENTITY;

ENTITY Point_on_curve
  SUBTYPE OF (Point);
  supporting_curve : Curve;
END_ENTITY;

ENTITY Point_on_surface
  SUBTYPE OF (Point);
  supporting_surface : Surface;
END_ENTITY;

ENTITY Spherical_surface
   SUBTYPE OF (Surface);
   position : Axis_placement_3d;
   radius   : length_measure;
WHERE
    WR1: radius > 0.0;
END_ENTITY;
 
 
ENTITY Surface
  SUPERTYPE OF (ONEOF(Conical_surface, Cylindrical_surface, Plane, Spherical_surface, Swept_surface, Toroidal_surface))
  SUBTYPE OF (Detailed_geometric_model_element);
END_ENTITY;

ENTITY Surface_of_revolution
  SUBTYPE OF (Swept_surface);
      axis_direction : Direction;
      axis_point :     Cartesian_point;
END_ENTITY;

ENTITY Swept_surface
   SUPERTYPE OF (ONEOF(Extruded_surface, Surface_of_revolution))
   SUBTYPE OF (Surface);
   swept_curve : Curve;
END_ENTITY;


ENTITY Toroidal_surface
   SUBTYPE OF (Surface);
   position : Axis_placement_3d;
   radius : length_measure;
   minor_radius : length_measure;
WHERE
    WR1: radius > 0.0;
    WR2: minor_radius > 0.0;
END_ENTITY;
 
SUBTYPE_CONSTRAINT alternate_geometry_items FOR Detailed_geometric_model_element;
  ONEOF (Direction,
         Axis_placement,
         Cartesian_transformation_2d,
         Cartesian_transformation_3d,
         Curve,
         Surface);
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT point_subtypes FOR Point;
  ONEOF (Cartesian_point,
         Point_on_curve,
         Point_on_surface);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;  -- Basic_geometry_arm
(*
   $Id: arm.exp,v 1.67 2012/10/11 05:49:06 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7957 - ISO/TS 10303-1654 Characteristic - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7394
*)

SCHEMA Characteristic_arm;
  USE FROM Basic_data_representation_arm;  -- ISO/TS 10303-1773
  USE FROM Document_assignment_arm;	-- ISO/TS 10303-1122
  USE FROM Extended_measure_representation_arm;	-- ISO/TS 10303-1106
  USE FROM External_library_arm; -- ISO/TS 10303-1778
  USE FROM Value_with_unit_extension_arm;	-- ISO/TS 10303-1753
  USE FROM External_properties_arm;  -- ISO/TS 10303-1129 LK
  USE FROM Property_assignment_arm; -- ISO/TS 10303-1030
  REFERENCE FROM Support_resource_arm(bag_to_set); 
  
  REFERENCE FROM Qualified_measure_arm(pre_defined_type_qualifiers); -- ISO/CD-TS 10303-1782  	
  
  TYPE characteristic = SELECT
    (String_representation_item,
    Numerical_item_with_unit,
    Value_list,
    Value_set);
  END_TYPE;

  TYPE characteristic_data_table_cell = SELECT ( 
    Null_representation_item, 
    String_representation_item, 
    Numerical_item_with_global_unit,
    Numerical_item_with_unit, 
    Value_list, 
    Value_set); 
  END_TYPE; 

  TYPE c_documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON documented_element_select WITH 
    (Property_value_representation);
  END_TYPE; 
  
  TYPE range_class = ENUMERATION OF
    (closed,
     lower_open,
     upper_open,
     open);
  END_TYPE;

  TYPE scalar_or_coordinated_characteristics = SELECT
    (Property_value_representation,
     characteristic);
  END_TYPE;

  ENTITY Characteristic_data_table_header_usage 
    SUBTYPE OF (Property_definition_representation);
    SELF\Property_definition_representation.definition : Characteristic_data_table_header;
    SELF\Property_definition_representation.used_representation : Characteristic_data_table_representation;
  END_ENTITY;

  ENTITY Characteristic_data_table
    SUBTYPE OF (Representation_item);
      property_value : LIST[1:?] OF Characteristic_data_table_row;
    WHERE
      WR1: SIZEOF(QUERY( pv <* property_value |
                  NOT (SIZEOF(pv.cell) = SIZEOF(property_value[1].cell))
                  )) = 0;
  END_ENTITY;

  ENTITY Characteristic_data_table_representation
    SUBTYPE OF (Property_value_representation);
      SELF\Representation.items : SET[1:1] OF Characteristic_data_table;
  INVERSE
    header : Characteristic_data_table_header_usage FOR used_representation;      
  END_ENTITY;

  ENTITY Characteristic_data_table_row
    SUBTYPE OF (Representation_item);
      cell : LIST [1:?] OF characteristic_data_table_cell;
  END_ENTITY;

  ENTITY Characteristic_data_column_header 
    SUBTYPE OF (Independent_property);
    INVERSE
      table_header_usage : Characteristic_data_table_header_decomposition FOR related;  
  END_ENTITY;

  ENTITY Characteristic_data_table_header 
    SUBTYPE OF (Independent_property);
    INVERSE
      column : SET [2:?] OF Characteristic_data_table_header_decomposition FOR relating;    
  END_ENTITY;

  ENTITY Characteristic_data_column_header_link
    SUBTYPE OF (Independent_property_relationship);
      SELF\Independent_property_relationship.relating RENAMED precedent : Characteristic_data_column_header;
      SELF\Independent_property_relationship.related RENAMED subsequent : Characteristic_data_column_header;
    DERIVE
      SELF\Independent_property_relationship.relation_type : STRING := 'sequence'; 
    UNIQUE
      UR1 : precedent, subsequent;
    WHERE
      WR1: subsequent <> precedent;
  END_ENTITY; 

  ENTITY Characteristic_data_table_header_decomposition
    SUBTYPE OF (Independent_property_relationship);
      SELF\Independent_property_relationship.relating : Characteristic_data_table_header;
      SELF\Independent_property_relationship.related : Characteristic_data_column_header;
    DERIVE
      SELF\Independent_property_relationship.relation_type : STRING := 'decomposition';
  END_ENTITY;

  ENTITY Externally_defined_type_qualifier
    SUBTYPE OF (Type_qualifier);
      external_source : External_source;
    WHERE
      WR1: NOT(name IN pre_defined_type_qualifiers);
  END_ENTITY;

  ENTITY Length_tolerance_characteristic
    SUBTYPE OF(Tolerance_characteristic);
    WHERE
      WR1 : ('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
            ('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
            ('CHARACTERISTIC_ARM.PLUS_MINUS_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
        (SIZEOF(QUERY(it <* SELF\Representation.items |
          NOT('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(it))
         )) = 0);
      WR2 : NOT('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
        (SIZEOF(QUERY(it <* SELF\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(it))
           )) = 1);
      WR3 : NOT('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
        (SIZEOF(QUERY(it <* SELF\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(it))
           )) = 1);
      WR4 : NOT EXISTS(SELF\Representation.description);
      WR5 : NOT('CHARACTERISTIC_ARM.PLUS_MINUS_TOLERANCE_CHARACTERISTIC' IN TYPEOF(SELF)) OR
        (SIZEOF(QUERY(it <* SELF\Representation.items |
          NOT(('EXTENDED_MEASURE_REPRESENTATION_ARM.VALUE_WITH_TOLERANCES' IN TYPEOF(it)) AND
             ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(it\Value_with_tolerances.item_value)))
         )) = 0);
  END_ENTITY;

  ENTITY Maximum_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET [1:1] OF Value_limit;
    WHERE
      WR1: SELF\Representation.items[1]\Value_limit.qualifiers[1]\Type_qualifier.name = 'maximum';      
  END_ENTITY;

  ENTITY Minimum_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET [1:1] OF Value_limit;
    WHERE
      WR1: SELF\Representation.items[1]\Value_limit.qualifiers[1]\Type_qualifier.name = 'minimum';      
  END_ENTITY;

  ENTITY Nominal_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET[1:1] OF Qualified_numerical_item_with_unit;
    WHERE
      WR1: SELF\Representation.items[1]\Qualified_representation_item.qualifiers[1]\Type_qualifier.name = 'nominal';
  END_ENTITY;

  ENTITY Null_representation_item 
    SUBTYPE OF (Representation_item); 
  END_ENTITY; 

  ENTITY Plus_minus_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET [1:1] OF Value_with_tolerances;
  END_ENTITY;

  ENTITY Qualified_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET[1:4] OF Qualified_numerical_item_with_unit;
    WHERE
      WR1: valid_qualified_tolerance_characteristic(SELF);
  END_ENTITY;

  ENTITY Range_characteristic
    SUBTYPE OF (Property_value_representation);
      SELF\Representation.items : SET[2:2] OF Numerical_item_with_unit;
      range_type				: range_class;
    WHERE
      WR1 : TYPEOF(SELF\Representation.items[1]) =
          TYPEOF(SELF\Representation.items[2]);
      WR2 : TYPEOF(SELF\Representation.items[1]\Value_with_unit.unit) =
          TYPEOF(SELF\Representation.items[2]\Value_with_unit.unit);
      WR3 : valid_range(SELF\Representation.items[1],
                      SELF\Representation.items[2]);          
  END_ENTITY;

  ENTITY Statistical_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET [2:?] OF Numerical_item_with_unit;
  END_ENTITY;

  ENTITY Symmetrical_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET[2:2] OF Numerical_item_with_unit;
    WHERE
      WR1: SIZEOF(QUERY( ri <* 
         SELF\representation.items |
        'VALUE_WITH_UNIT_EXTENSION_ARM.RATIO_DATA_ELEMENT' IN TYPEOF(ri))) = 1;
  END_ENTITY;

  ENTITY Text_representation_item
  	SUBTYPE OF (String_representation_item);
  END_ENTITY;

  ENTITY Tolerance_characteristic
    ABSTRACT SUPERTYPE OF ((ONEOF (
      Maximum_tolerance_characteristic,
      Minimum_tolerance_characteristic,
      Nominal_tolerance_characteristic,
      Plus_minus_tolerance_characteristic,
      Qualified_tolerance_characteristic,
      Statistical_tolerance_characteristic,
      Symmetrical_tolerance_characteristic,
      Typical_tolerance_characteristic
      )) ANDOR Length_tolerance_characteristic)
    SUBTYPE OF (Property_value_representation);
    WHERE
      WR1: SELF\Representation.context_of_items\Representation_context.id = 'tolerance values';
      WR2 : NOT EXISTS(SELF\Representation.name);
  END_ENTITY;

  ENTITY Typical_tolerance_characteristic
    SUBTYPE OF (Tolerance_characteristic);
      SELF\Representation.items : SET [1:1] OF Value_limit;
    WHERE
      WR1: SELF\Representation.items[1]\Value_limit.qualifiers[1]\Type_qualifier.name = 'typical';      
  END_ENTITY;

  FUNCTION valid_qualified_tolerance_characteristic (input : Qualified_tolerance_characteristic) : BOOLEAN;
 --no more than one of the Type_qualifier.name shall be 'nominal'
 --no more than one of the Type_qualifier.name shall be 'typical'
 --no more than one of the Type_qualifier.name shall be 'maximium'
 --no more than one of the Type_qualifier.name shall be 'minimum'
 --Type_qualifier.name shall be drawn only from 'nominal', 'typical' , 'maximium', 'minimum'
  LOCAL
     bag_data : BAG OF STRING := [];
     valid_set : SET OF STRING := ['nominal', 'typical' , 'maximium', 'minimum'];
  END_LOCAL;
  REPEAT i := 1 TO SIZEOF(input\Qualified_tolerance_characteristic.items);
    REPEAT j := 1 TO SIZEOF(input\Qualified_tolerance_characteristic.items[i]\Qualified_representation_item.qualifiers);
     IF 'QUALIFIED_MEASURE_ARM.TYPE_QUALIFIER' IN TYPEOF(input\Qualified_tolerance_characteristic.items[i]\Qualified_representation_item.qualifiers[j])
      THEN
        bag_data := bag_data + input\Qualified_tolerance_characteristic.items[i]\Qualified_representation_item.qualifiers[j]\Type_qualifier.name;
     END_IF;
    END_REPEAT;
  END_REPEAT;

  IF (SIZEOF(bag_to_set(bag_data)) = SIZEOF(bag_data)) AND
     (VALUE_UNIQUE(bag_data)) AND 
     (SIZEOF(valid_set * bag_data) = SIZEOF(bag_data)) 
  THEN RETURN(TRUE);
  END_IF;
    
   RETURN(FALSE);
  END_FUNCTION; 

  FUNCTION valid_range(input1 : Numerical_item_with_unit;
                       input2 : Numerical_item_with_unit) : BOOLEAN;
    RETURN(TRUE);
  END_FUNCTION; 

  SUBTYPE_CONSTRAINT exclusive_property_value_representation_characteristic FOR Property_value_representation;
    ONEOF (Range_characteristic, Tolerance_characteristic);
  END_SUBTYPE_CONSTRAINT;

  SUBTYPE_CONSTRAINT type_qualifier_subtypes FOR Type_qualifier;
    ONEOF(Externally_defined_type_qualifier, Pre_defined_type_qualifier);
  END_SUBTYPE_CONSTRAINT;
  
  SUBTYPE_CONSTRAINT independent_property_subtypes FOR Independent_property;
    ONEOF (Characteristic_data_table_header, Characteristic_data_column_header);
  END_SUBTYPE_CONSTRAINT;
  
  SUBTYPE_CONSTRAINT c_representation_item_subtypes FOR Representation_item; 
	(ONEOF (Characteristic_data_table,
	  Characteristic_data_table_row));
  END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.8 2009/12/21 15:19:48 liutkuviene Exp $
   ISO TC184/SC4/WG12 N6884 - ISO/TS 10303-1765 Characterizable object - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4296
*)

SCHEMA Characterizable_object_arm;

USE FROM Support_resource_arm;

ENTITY Characterizable_object;
  name : label;
  description : OPTIONAL text;
END_ENTITY;

END_SCHEMA;
(*
 $Id: arm.exp,v 1.8 2004/11/19 21:37:34 robbod Exp $
 ISO TC184/SC4/WG12 N3022 - ISO/TS 10303-1070 Class - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2258
*) 


SCHEMA Class_arm;


ENTITY Class
  SUPERTYPE OF (ONEOF (Class_by_extension,
                       Class_by_intension));
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

ENTITY Class_by_extension
  SUBTYPE OF (Class);
END_ENTITY;

ENTITY Class_by_intension
  SUBTYPE OF (Class);
END_ENTITY;

END_SCHEMA;  -- Class_arm

(*
 $Id: arm.exp,v 1.12 2009/08/11 07:45:42 robbod Exp $
 ISO TC184/SC4/WG12 N6031 - ISO/TS 10303-1056 Configuration item - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2532
*) 


SCHEMA Configuration_item_arm;

USE FROM Product_concept_identification_arm;    -- ISO/TS 10303-1060

USE FROM Product_version_arm;    -- ISO/TS 10303-1018

USE FROM Product_view_definition_arm;    -- ISO/TS 10303-1019


TYPE version_or_definition = SELECT
   (Product_version, 
    Product_view_definition);
END_TYPE; 

ENTITY Item_design_association;
  configuration : Product_configuration;
  design : version_or_definition;
UNIQUE
  UR1: configuration, design;
END_ENTITY;

ENTITY Product_configuration;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
  item_context : Product_concept;
INVERSE
  corresponding_design : SET[0:1] OF Item_design_association FOR configuration;
END_ENTITY;

ENTITY Product_configuration_hierarchical_relationship
  SUBTYPE OF (Product_configuration_relationship);
  SELF\Product_configuration_relationship.related_product_configuration RENAMED child : Product_configuration;
  SELF\Product_configuration_relationship.relating_product_configuration RENAMED parent : Product_configuration;
END_ENTITY;

ENTITY Product_configuration_relationship
  SUPERTYPE OF (ONEOF (Product_configuration_hierarchical_relationship,
                       Product_configuration_revision_sequence));
  relating_product_configuration : Product_configuration;
  related_product_configuration : Product_configuration;
END_ENTITY;

ENTITY Product_configuration_revision_sequence
  SUBTYPE OF (Product_configuration_relationship);
  SELF\Product_configuration_relationship.relating_product_configuration RENAMED predecessor : Product_configuration;
  SELF\Product_configuration_relationship.related_product_configuration RENAMED successor : Product_configuration;
END_ENTITY;

END_SCHEMA;  -- Configuration_item_arm

(*
	$Id: arm.exp,v 1.20 2012/10/06 20:09:56 liutkuviene Exp $
	ISO TC184/SC4/WG12 N7771 - ISO/TS 10303-1131 Construction geometry - EXPRESS ARM
	Supersedes ISO TC184/SC4/WG12 N5329
*) 

SCHEMA Construction_geometry_arm;

USE FROM Basic_curve_arm;    -- ISO/TS 10303-1651

  TYPE constructive_element_select = EXTENSIBLE GENERIC_ENTITY SELECT 
    (Axis_placement,  
     Curve,  
     Point,  
     Surface); 
  END_TYPE; 

  TYPE constructive_geometry_select = SELECT
    (Constructive_geometry, 
     Geometric_model);
  END_TYPE; 

  ENTITY Constructive_geometry
    SUBTYPE OF (Representation);
      SELF\Representation.context_of_items : Geometric_coordinate_space;
      SELF\Representation.items : SET [1:?] OF constructive_element_select;
  END_ENTITY;

  ENTITY Constructive_geometry_association;
      auxiliary_geometry : Constructive_geometry;
      base_geometry      : constructive_geometry_select;
      description        : STRING;
    WHERE
      WR1: auxiliary_geometry\Representation.context_of_items :=: base_geometry\Representation.context_of_items;
  END_ENTITY;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.18 2012/10/11 05:49:06 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7975 - ISO/TS 10303-1027 Contextual shape positioning - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7412
*) 

SCHEMA Contextual_shape_positioning_arm;

USE FROM Geometric_model_relationship_arm;
USE FROM Shape_property_assignment_arm;    --  ISO/TS 10303-1032


  TYPE template_instance = SELECT
    (Geometric_placement_operation, 
     Geometric_model_relationship_with_transformation);
  END_TYPE; 

  ENTITY Contextual_shape_representation;
      contextual_shape          : Contextual_item_shape;
      representing_relationship : Geometric_model_relationship;
    DERIVE
      context_representation    : geometric_representation_select := representing_relationship.rep_2 ;
      positioned_representation : geometric_representation_select := representing_relationship.rep_1 ;
  END_ENTITY;

  ENTITY Geometric_composition_with_operator_transformation
    SUBTYPE OF (Geometric_relationship_with_operator_transformation,
      Definitional_representation_relationship);
  END_ENTITY;

  ENTITY Geometric_composition_with_placement_transformation
    SUBTYPE OF (Geometric_relationship_with_placement_transformation,
      Definitional_representation_relationship);
  END_ENTITY; 

  ENTITY Geometric_placement_model
    SUBTYPE OF (Geometric_model);
      SELF\Representation.items : SET[1:1] OF Geometric_placement_operation;
  END_ENTITY;

  ENTITY Geometric_model_relationship_with_transformation
    ABSTRACT SUPERTYPE OF (ONEOF (Geometric_relationship_with_placement_transformation,
      Geometric_relationship_with_operator_transformation))
    SUBTYPE OF (Geometric_model_relationship);
    WHERE  
      WR1: rep_1.context_of_items :<>: rep_2.context_of_items;
  END_ENTITY;

  ENTITY Geometric_relationship_with_operator_transformation
    SUBTYPE OF (Geometric_model_relationship_with_transformation);
      transformation: cartesian_transformation;
    WHERE
      WR1:  rep_1.context_of_items\Geometric_coordinate_space.dimension_count :=:
        rep_2.context_of_items\Geometric_coordinate_space.dimension_count;
  END_ENTITY;

  ENTITY Geometric_relationship_with_placement_transformation
    SUBTYPE OF (Geometric_model_relationship_with_transformation);
      transformation: Axis_placement_mapping;
    WHERE
      WR1:  rep_1.context_of_items\Geometric_coordinate_space.dimension_count :=:
        rep_2.context_of_items\Geometric_coordinate_space.dimension_count;
  END_ENTITY;

  ENTITY Shape_placement_association
    SUBTYPE OF (Shape_description_association);
      SELF\Shape_description_association.used_representation : Geometric_placement_model;
      SELF\Shape_description_association.definition : Associated_contextual_item_shape;
  END_ENTITY;
  
  ENTITY Associated_contextual_item_shape
    SUBTYPE OF (Associated_item_shape, Contextual_item_shape);
  END_ENTITY;

END_SCHEMA;

(*
 $Id: arm.exp,v 1.16 2013/11/20 21:01:45 darla Exp $
 ISO TC184/SC4/WG12 N8379 - ISO/TS 10303-1010 Date time - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N7978
*) 


SCHEMA Date_time_arm;

TYPE day_in_month_number = INTEGER;
WHERE
  WR1: {1 <= SELF <= 31};
END_TYPE; 

TYPE hour_in_day = INTEGER;
WHERE
  WR1: { 0 <= SELF < 24 };
END_TYPE; 

TYPE minute_in_hour = INTEGER;
WHERE
  WR1: { 0 <= SELF <= 59 };
END_TYPE; 

TYPE month_in_year_number = INTEGER;
WHERE
  WR1: { 1 <= SELF <= 12 };
END_TYPE; 

TYPE offset_orientation = ENUMERATION OF 
   (ahead,
    exact,
    behind);
END_TYPE; 

TYPE second_in_minute = REAL;
WHERE
  WR1: { 0 <= SELF <= 60.0 };
END_TYPE; 

TYPE year_number = INTEGER;
END_TYPE; 

ENTITY Calendar_date;
  year_component : year_number;
  month_component : month_in_year_number;
  day_component : day_in_month_number;
END_ENTITY;

ENTITY Date_time;
  date_component : Calendar_date;
  time_component : Local_time;
END_ENTITY;

ENTITY Local_time;
  hour_component : hour_in_day;
  minute_component : OPTIONAL minute_in_hour;
  second_component : OPTIONAL second_in_minute;
  zone : Time_offset;
END_ENTITY;

ENTITY Time_offset;
  hour_offset : INTEGER;
  minute_offset : OPTIONAL INTEGER;
  sense : offset_orientation;
DERIVE
  actual_minute_offset : INTEGER := NVL(minute_offset,0);
WHERE
  WR1: { 0 <= hour_offset < 24 };
  WR2: { 0 <= actual_minute_offset <= 59 };
  WR3: NOT (((hour_offset <> 0) OR (actual_minute_offset <>0)) AND (sense = exact));
END_ENTITY;

END_SCHEMA;  -- Date_time_arm
(* 
$Id: arm.exp,v 1.19 2012/10/11 05:49:04 liutkuviene Exp $  
ISO TC184/SC4/WG12 N7984 - ISO/TS 10303-1130 Derived shape element - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N7418
*) 


SCHEMA Derived_shape_element_arm;

USE FROM Construction_geometry_arm;  -- ISO/TS 10303-1131
USE FROM Shape_property_assignment_arm; -- ISO/TS 10303-1032
USE FROM Value_with_unit_arm;    -- ISO/TS 10303-1054

TYPE dse_shape_model = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON shape_model WITH (
   Constructive_geometry);
END_TYPE;

ENTITY Apex
  SUBTYPE OF (Derived_shape_element);
END_ENTITY;

ENTITY Centre_axis
  SUBTYPE OF (Centre_of_symmetry);
WHERE
  WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;

ENTITY Centre_of_symmetry
  SUPERTYPE OF (ONEOF (
    Centre_axis,
    Centre_plane,
    Centre_point,
    Median_curve,
    Median_surface))
  SUBTYPE OF (Derived_shape_element);
END_ENTITY;

ENTITY Centre_plane
  SUBTYPE OF (Centre_of_symmetry);
WHERE
  WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;

ENTITY Centre_point
  SUBTYPE OF (Centre_of_symmetry);
WHERE
  WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;
  
ENTITY Derived_shape_element
  ABSTRACT SUPERTYPE OF (ONEOF (
    Apex,
    Centre_of_symmetry,
    Geometric_contact,    
    Extension,
    Geometric_intersection,
    Geometric_alignment,
    Parallel_offset,
    Perpendicular_to,
    Tangent))
  SUBTYPE OF (Shape_element);
  derived_from : SET[1:?] OF Shape_element;
END_ENTITY;

ENTITY Geometric_alignment
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[2:?] OF Shape_element;
END_ENTITY;

ENTITY Geometric_contact
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[2:2] OF Shape_element;
END_ENTITY;

ENTITY Geometric_intersection
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[2:?] OF Shape_element;
END_ENTITY;

ENTITY Extension
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[1:1] OF Shape_element;
END_ENTITY;

ENTITY Median_curve
  SUBTYPE OF (Centre_of_symmetry);
WHERE
  WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;

ENTITY Median_surface
  SUBTYPE OF (Centre_of_symmetry);
WHERE
  WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;

ENTITY Parallel_offset
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[1:1] OF Shape_element;
END_ENTITY;

ENTITY Perpendicular_to
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[1:1] OF Shape_element;
END_ENTITY;

ENTITY Tangent_plane
  SUBTYPE OF (Tangent);
  WHERE
    WR1 : NOT EXISTS(SELF\Shape_element.description);
END_ENTITY;

ENTITY Tangent
  SUPERTYPE OF (Tangent_plane)
  SUBTYPE OF (Derived_shape_element);
  SELF\Derived_shape_element.derived_from : SET[1:1] OF Shape_element;
END_ENTITY;

ENTITY Offset_shape_element
  SUBTYPE OF (Derived_shape_element);
  offset : Value_with_unit;
END_ENTITY;

END_SCHEMA;
(*
$Id: arm.exp,v 1.43 2012/10/11 05:49:08 liutkuviene Exp $
ISO TC184/SC4/WG12 N7993 - ISO/TS 10303-1050 Dimension tolerance - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N7427
*) 


SCHEMA Dimension_tolerance_arm;

USE FROM Derived_shape_element_arm;    -- ISO/TS 10303-1130
USE FROM Document_assignment_arm;    -- ISO/TS 10303-1122
USE FROM Extended_measure_representation_arm;    -- ISO/TS 10303-1106
USE FROM Value_with_unit_extension_arm;  -- ISO/TS 10303-1753

TYPE adjoining_or_centred = ENUMERATION OF ( 
  adjoining,
  centred);
END_TYPE;

TYPE angle_relator = ENUMERATION OF 
   (equal,
    large,
    small);
END_TYPE; 

TYPE dimension_value_select = SELECT
   (Dimension_value_with_limitation, 
    Numerical_item_with_unit, 
    Tolerance_range, 
    Value_limit);
END_TYPE; 

TYPE diameter_qualifier_enumeration = ENUMERATION OF (
  centre_outer,
  centre_inner,
  outer_centre,
  outer_outer,
  outer_inner,
  inner_centre,
  inner_outer,
  inner_inner);
END_TYPE;

TYPE diameter_type = ENUMERATION OF (
   circular_or_cylindrical_diameter,
   spherical_diameter,
   toroidal_minor_diameter,
   toroidal_major_diameter,
   toroidal_high_major_diameter,
   toroidal_low_major_diameter);
END_TYPE;

TYPE dimension_target = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE;

TYPE edge_of_undefined_shape_size_element = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE;

TYPE geometric_dimension_modifier = EXTENSIBLE ENUMERATION OF (
  two_point_size, -- (LP) 
  local_size_defined_by_a_sphere, -- (LS)
  least_square_association_criteria, -- (GG) 
  maximum_inscribed_association_criteria, -- (GX) 
  minimum_circumscribed_association_criteria, -- (GN) 
  circumference_diameter_calculated_size, -- (CC) 
  area_diameter_calculated_size, -- (CA) 
  volume_diameter_calculated_size, -- (CV) 
  maximum_rank_order_size, -- (SX) 
  minimum_rank_order_size, -- (SN)
  average_rank_order_size, -- (SA) 
  median_rank_order_size, -- (SM) 
  mid_range_rank_order_size, -- (SD) 
  range_rank_order_size, -- (SR) 
  any_part_of_the_feature, -- 'APF' 
  any_cross_section, -- '/0'
  specific_fixed_cross_section, -- SCS
  common_tolerance, -- 'CT'
  free_state_condition, -- (F)
  statistical, -- ASME only
  continuous_feature, -- ASME only
  square, -- ASME only
  controlled_radius); -- ASME only
END_TYPE;

TYPE limitation_definition_select = SELECT
   (Limits_and_fits, 
    Plus_minus_bounds);
END_TYPE; 

TYPE radial_type = ENUMERATION OF (
   circular_or_cylindrical_radius,
   spherical_radius,
   toroidal_minor_radius,
   toroidal_major_radius,
   toroidal_high_major_radius,
   toroidal_low_major_radius);
END_TYPE;

TYPE tolerance_principle_type = ENUMERATION OF (
  envelope_requirement, 
  independency, 
  default);
END_TYPE;

TYPE undefined_edge_shape_enumeration_direction = ENUMERATION OF ( 
  true_neighbor,               
  false_neighbor,
  both_neighbors);
END_TYPE;

ENTITY Angular_location
  SUBTYPE OF (Dimensional_location);
  angle_selection : angle_relator;
  orientation : OPTIONAL Axis_placement;
END_ENTITY;

ENTITY Angular_size
  SUBTYPE OF (Dimensional_size);
  full : BOOLEAN;
  angle_selection : angle_relator;
END_ENTITY;

ENTITY Curved_distance
  SUBTYPE OF (Dimensional_location);
  used_path : Measurement_path;
END_ENTITY;

ENTITY Curved_size
  SUBTYPE OF (Dimensional_size);
END_ENTITY;

ENTITY Diameter_size
   SUBTYPE OF (Dimensional_size);
   geometry_type : diameter_type;
END_ENTITY;

ENTITY Dimensional_size
  ABSTRACT SUPERTYPE OF (ONEOF (Angular_size,
                                Curved_size,
                                Diameter_size,
                                Edge_of_undefined_shape_size,
                                Machining_feature_size,
                                Radial_size,
                                Thickness_size))
  SUBTYPE OF (Geometric_dimension);
  is_applied_to : dimension_target;
END_ENTITY;

ENTITY Dimension_value_with_limitation;
  defined_by : limitation_definition_select;
  limited_value : Numerical_item_with_unit;
END_ENTITY;

ENTITY Geometric_dimension
  ABSTRACT SUPERTYPE OF (ONEOF (Dimensional_location,
                                Dimensional_size));
  id : STRING;
  dimension_value : dimension_value_select;
  notes : SET[0:?] OF STRING;
  theoretical_exact : BOOLEAN;
  auxiliary : BOOLEAN;
  tolerance_principle : tolerance_principle_type;
  modifiers : LIST [0:?] of geometric_dimension_modifier;
  unit_length : OPTIONAL Length_data_element;
END_ENTITY;

ENTITY Limits_and_fits;
  deviation : STRING;
  fitting_type : OPTIONAL STRING;
  grade : STRING;
END_ENTITY;

ENTITY Linear_distance
  SUBTYPE OF (Dimensional_location);
  orientation : OPTIONAL Axis_placement;
  diameter_qualifier : OPTIONAL diameter_qualifier_enumeration;
END_ENTITY;

ENTITY Dimensional_location
  ABSTRACT SUPERTYPE OF (ONEOF (Angular_location,
                                Curved_distance,
                                Linear_distance))
  SUBTYPE OF (Geometric_dimension);
  description : OPTIONAL STRING;
  directed : OPTIONAL BOOLEAN;
  origin : dimension_target;
  target : dimension_target;
END_ENTITY;

ENTITY Edge_of_undefined_shape_size
  SUBTYPE OF (Dimensional_size);
  orientation : undefined_edge_shape_enumeration_direction;
  SELF\Dimensional_size.is_applied_to : edge_of_undefined_shape_size_element;
  SELF\Geometric_dimension.dimension_value : Tolerance_range;
UNIQUE
  UR1 : is_applied_to, orientation;
END_ENTITY;

ENTITY Machining_feature_size
  SUBTYPE OF (Dimensional_size);
  considered_attribute: STRING;
END_ENTITY;

ENTITY Measurement_path;
  defined_by : Curve;
  defined_in : Geometric_coordinate_space;
END_ENTITY;

ENTITY Plus_minus_bounds;
  lower_bound : Value_with_unit;
  upper_bound         : Value_with_unit;
END_ENTITY;

ENTITY Radial_size
   SUBTYPE OF (Dimensional_size);
   radius_type : OPTIONAL adjoining_or_centred;
   geometry_type : radial_type;
END_ENTITY;

ENTITY Thickness_size
  SUBTYPE OF (Dimensional_size);
  used_path : OPTIONAL Measurement_path;
END_ENTITY;

ENTITY Tolerance_range;
  lower_range : Numerical_item_with_unit;
  upper_range : Numerical_item_with_unit;
END_ENTITY;

END_SCHEMA;  -- Dimension_tolerance_arm
(*
$Id: arm.exp,v 1.16 2012/10/06 20:09:56 liutkuviene Exp $
ISO TC184/SC4/WG12 N7708 - ISO/TS 10303-1121 Document and version identification - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N2957
*)


SCHEMA Document_and_version_identification_arm;

USE FROM Product_identification_arm;    -- ISO/TS 10303-1017

USE FROM Product_version_arm;    -- ISO/TS 10303-1018


ENTITY Document
  SUBTYPE OF (Product);
END_ENTITY;

ENTITY Document_version
  SUBTYPE OF (Product_version);
  SELF\Product_version.of_product : Document;
END_ENTITY;

RULE document_version_constraint FOR 
(Product_version);
WHERE
  WR1: SIZEOF ( QUERY ( pv <* Product_version | ( NOT ( 'DOCUMENT_AND_VERSION_IDENTIFICATION_ARM.' + 'DOCUMENT_VERSION' IN TYPEOF ( pv) ) ) AND ( 'DOCUMENT_AND_VERSION_IDENTIFICATION_ARM.' + 'DOCUMENT' IN TYPEOF ( pv.of_product) ) ) ) = 0 ;
END_RULE; 

END_SCHEMA;  -- Document_and_version_identification_arm
(*
$Id: arm.exp,v 1.14 2012/10/06 20:09:56 liutkuviene Exp $
ISO TC184/SC4/WG12 N7714 - ISO/TS 10303-1122 Document assignment - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N7106
*)


SCHEMA Document_assignment_arm;

USE FROM Document_and_version_identification_arm;    -- ISO/TS 10303-1121

USE FROM Document_definition_arm;    -- ISO/TS 10303-1123

USE FROM File_identification_arm;    -- ISO/TS 10303-1127


TYPE assigned_document_select = SELECT
   (Document, 
    Document_definition, 
    Document_version, 
    File);
END_TYPE; 

TYPE documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT
  (Product_view_definition);
END_TYPE; 

ENTITY Document_assignment;
  assigned_document : assigned_document_select;
  is_assigned_to : SET[1:?] OF documented_element_select;
  role : STRING;
END_ENTITY;

ENTITY Partial_document_assignment
  SUBTYPE OF (Document_assignment);
  document_portion : STRING;
END_ENTITY;

END_SCHEMA;  -- Document_assignment_arm
(*
 $Id: arm.exp,v 1.18 2004/11/15 21:22:46 thendrix Exp $
ISO TC184/SC4/WG12 N3225 - ISO/TS 10303-1123 Document definition - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N1192
*) 


SCHEMA Document_definition_arm;

USE FROM Document_and_version_identification_arm;    -- ISO/TS 10303-1121

USE FROM External_item_identification_assignment_arm;    -- ISO/TS 10303-1128

USE FROM File_identification_arm;    -- ISO/TS 10303-1127

USE FROM Product_view_definition_arm;    -- ISO/TS 10303-1019


TYPE document_location_select = SELECT BASED_ON external_identification_item WITH 
   (Document_definition);
END_TYPE; 

ENTITY Digital_document_definition
  SUBTYPE OF (Document_definition);
  files : SET[0:?] OF Digital_file;
END_ENTITY;

ENTITY Document_definition
  SUPERTYPE OF (ONEOF (Digital_document_definition,
                       Physical_document_definition))
  SUBTYPE OF (Product_view_definition);
  SELF\Product_view_definition.name RENAMED description : OPTIONAL STRING;
  SELF\Product_view_definition.defined_version RENAMED associated_document_version : Document_version;
END_ENTITY;

ENTITY Document_location_identification
  SUBTYPE OF (External_source_identification);
WHERE
  WR1: 'DOCUMENT_DEFINITION_ARM.DOCUMENT_DEFINITION' IN TYPEOF(SELF\External_source_identification.item);
END_ENTITY;

ENTITY Physical_document_definition
  SUBTYPE OF (Document_definition);
  components : SET[0:?] OF Hardcopy;
END_ENTITY;

RULE document_definition_constraint FOR 
(Product_view_definition);
WHERE
  WR1: SIZEOF ( QUERY ( dd <* Product_view_definition | ( NOT ( 'DOCUMENT_DEFINITION_ARM.' + 'DOCUMENT_DEFINITION' IN TYPEOF (dd) ) ) AND ( 'DOCUMENT_DEFINITION_ARM.' + 'DOCUMENT_VERSION' IN TYPEOF ( dd.defined_version) ) ) ) =0;
END_RULE; 

END_SCHEMA;  -- Document_definition_arm
(* 
	$Id: arm.exp,v 1.30 2013/11/24 15:22:30 thomasrthurman Exp $
	ISO TC184/SC4/WG12 N8005 - ISO/TS 10303-1004 Elemental geometric shape - EXPRESS ARM
	Supersedes ISO TC184/SC4/WG12 N7089
*)
   
SCHEMA Elemental_geometric_shape_arm;
 
USE FROM Foundation_representation_arm; -- ISO/TS 10303-1006
USE FROM Elemental_topology_arm; -- ISO/TS 10303-1005

USE FROM Identification_assignment_arm; -- ISO/TS 10303-1021

  TYPE cartesian_transformation = SELECT (
    Cartesian_transformation_2d, 
	Cartesian_transformation_3d);
  END_TYPE;

  TYPE egs_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
     (Geometric_model);
  END_TYPE;

  TYPE geometric_model_item = SELECT 
    (Detailed_geometric_model_element,
     Detailed_topological_model_element);
  END_TYPE;

  TYPE template_definition_select = EXTENSIBLE SELECT (Geometric_model);
  END_TYPE; 

  ENTITY Axis_placement
    SUPERTYPE OF (ONEOF (Axis_placement_2d,
      Axis_placement_3d))
    SUBTYPE OF (Detailed_geometric_model_element);
      location      : Cartesian_point;
      axis          : OPTIONAL Direction;
      ref_direction : OPTIONAL Direction;
    DERIVE
      dim: INTEGER := SIZEOF(location\Cartesian_point.coordinates);
    WHERE
      WR1: dim >1;
      WR2: dim = SIZEOF(axis\Direction.direction_ratios);
      WR3: dim = SIZEOF(ref_direction\Direction.direction_ratios);
  END_ENTITY;

  ENTITY Axis_placement_2d
    SUBTYPE OF ( Axis_placement );
    WHERE
      WR1: NOT EXISTS(axis);
      WR2: SELF\Axis_placement.dim = 2;
  END_ENTITY;

  ENTITY Axis_placement_3d
    SUBTYPE OF ( Axis_placement );
    WHERE
      WR1: SELF\Axis_placement.dim = 3;
-- convert to IP
--     wr4: NOT EXISTS( axis ) OR NOT EXISTS( ref_direction ) OR ( cross_product( axis, ref_direction ).magnitude > 0 );
  END_ENTITY;

  ENTITY Axis_placement_mapping;
      source : Axis_placement;
      target : Axis_placement;
    WHERE
      WR1: source\Axis_placement.dim = target\Axis_placement.dim;
  END_ENTITY;

  ENTITY Point
    ABSTRACT SUPERTYPE
    SUBTYPE OF (Detailed_geometric_model_element);
  END_ENTITY;

  ENTITY Cartesian_point
    SUBTYPE OF (Point);
      coordinates : LIST[1:3] OF length_measure;
  END_ENTITY;

  ENTITY Cartesian_transformation_2d
    SUBTYPE OF (Detailed_geometric_model_element);
      multiplication_matrix : ARRAY[1:2] OF Direction;
      translation           : Cartesian_point;
    WHERE
      WR1: SIZEOF(multiplication_matrix[1]\Direction.direction_ratios)=2;
      WR2: SIZEOF(multiplication_matrix[2]\Direction.direction_ratios)=2;
      WR3: SIZEOF(translation.coordinates)=2;
  END_ENTITY;

  ENTITY Cartesian_transformation_3d
    SUBTYPE OF (Detailed_geometric_model_element);
      multiplication_matrix : ARRAY[1:3] OF Direction;
      translation           : Cartesian_point;
    WHERE
      WR1: SIZEOF(multiplication_matrix[1]\Direction.direction_ratios)=3;
      WR2: SIZEOF(multiplication_matrix[2]\Direction.direction_ratios)=3;
      WR3: SIZEOF(multiplication_matrix[3]\Direction.direction_ratios)=3;
      WR4: SIZEOF(translation.coordinates)=3;
  END_ENTITY;

  ENTITY Detailed_geometric_model_element
    ABSTRACT SUPERTYPE OF (ONEOF(
      Direction, 
      Axis_placement, 
      Cartesian_transformation_2d,
	  Cartesian_transformation_3d,
	  Geometric_placement_operation))
    SUBTYPE OF (Representation_item);
  END_ENTITY;

  ENTITY Direction
    SUBTYPE OF (Detailed_geometric_model_element);
      direction_ratios : LIST[2:3] OF REAL;  
  END_ENTITY;

  ENTITY Geometric_coordinate_space
    SUBTYPE OF (Numerical_representation_context);
      dimension_count : INTEGER;
    WHERE
      WR1: dimension_count >0;
  END_ENTITY;

  ENTITY Geometric_model
    SUBTYPE OF (Representation);
      version_id                           : OPTIONAL STRING;
      model_extent                         : OPTIONAL length_measure;
      SELF\Representation.context_of_items : Geometric_coordinate_space;
      SELF\Representation.items            : SET[1:?] OF geometric_model_item;
  END_ENTITY;
  
  ENTITY Geometric_placement
    SUBTYPE OF (Geometric_placement_operation);
      target : Axis_placement;
  END_ENTITY; 

  ENTITY Geometric_placement_operation
    ABSTRACT SUPERTYPE OF ( ONEOF (Geometric_placement,
      Geometric_operator_transformation))
    SUBTYPE OF (Detailed_geometric_model_element);
      source : Axis_placement;  
      template_definition : template_definition_select;
  END_ENTITY; 

  ENTITY Geometric_operator_transformation
    SUBTYPE OF (Geometric_placement_operation);
      target : cartesian_transformation;
  END_ENTITY; 

END_SCHEMA;












(*
$Id: arm.exp,v 1.10 2012/10/11 05:49:05 liutkuviene Exp $
ISO TC184/SC4/WG12 N8008 - ISO/TS 10303-1005 Elemental topology - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N6896
*)
   
SCHEMA Elemental_topology_arm;

   
USE FROM Foundation_representation_arm;

   
ENTITY Connected_edge_set
   SUBTYPE OF (Detailed_topological_model_element);
   connected_edges : SET [1:?] OF Edge;
 END_ENTITY;

 ENTITY Connected_face_set
   SUBTYPE OF (Detailed_topological_model_element);
   connected_faces : SET [1:?] OF Face;
 END_ENTITY;

ENTITY Connected_face_sub_set
  SUBTYPE OF (Connected_face_set);
  parent_face_set : Connected_face_set;
END_ENTITY; 

ENTITY Detailed_topological_model_element
  ABSTRACT SUPERTYPE OF (ONEOF(Connected_edge_set, Connected_face_set,
             Edge, Face, Face_bound, Vertex, (Loop ANDOR Path)))
  SUBTYPE OF (Representation_item);
END_ENTITY;

   
ENTITY Edge
   SUBTYPE OF (Detailed_topological_model_element);
   edge_start : Vertex;
   edge_end   : Vertex;
 END_ENTITY;


ENTITY Edge_loop
   SUBTYPE OF (Loop,Path);
 DERIVE
   ne : INTEGER := SIZEOF(SELF\Path.edge_list);
 WHERE
   WR1: (SELF\Path.edge_list[1].edge_start) :=:
        (SELF\Path.edge_list[ne].edge_end);
 END_ENTITY;

ENTITY Face
   SUBTYPE OF (Detailed_topological_model_element);
   bounds : SET[1:?] OF face_bound;
 WHERE
     WR1: SIZEOF(QUERY(temp <* bounds | 'ELEMENTAL_TOPOLOGY_ARM.FACE_OUTER_BOUND' IN
                                               TYPEOF(temp))) <= 1;
 END_ENTITY;

 ENTITY Face_bound
   SUBTYPE OF(Detailed_topological_model_element);
   bound       :  Loop;
   orientation :  BOOLEAN;
 END_ENTITY;

  ENTITY Face_outer_bound
    SUBTYPE OF (Face_bound);
  END_ENTITY;

ENTITY Loop
   SUPERTYPE OF (ONEOF(Vertex_loop, Edge_loop))
   SUBTYPE OF (Detailed_topological_model_element);
 END_ENTITY;

ENTITY Oriented_edge
   SUBTYPE OF (Edge);
   edge_definition : Edge;
   orientation  : BOOLEAN;
 DERIVE
   SELF\Edge.edge_start : Vertex := boolean_choice (SELF.orientation,
                                            SELF.edge_definition.edge_start,
                                            SELF.edge_definition.edge_end);
   SELF\Edge.edge_end   : Vertex := boolean_choice (SELF.orientation,
                                            SELF.edge_definition.edge_end,
                                            SELF.edge_definition.edge_start);
 WHERE
   WR1: NOT ('TOPOLOGY_SCHEMA.ORIENTED_EDGE' IN TYPEOF (SELF.edge_definition));
 END_ENTITY;

ENTITY Path
   SUBTYPE OF (Detailed_topological_model_element);
   edge_list  : LIST [1:?] OF UNIQUE Oriented_edge;
 WHERE
   WR1: path_aligned(SELF);
 END_ENTITY;

ENTITY Vertex
   SUBTYPE OF (Detailed_topological_model_element);
 END_ENTITY;


ENTITY Vertex_loop
   SUBTYPE OF (Loop);
   loop_vertex : vertex;
END_ENTITY;




FUNCTION boolean_choice (b : boolean;
            choice1, choice2 : generic : item)  : generic : item;
 
     IF b THEN
       RETURN (choice1);
     ELSE
       RETURN (choice2);
     END_IF;
   END_FUNCTION;

FUNCTION path_aligned(a_path : Path) : LOGICAL;
   LOCAL
     n : INTEGER;
     p : LOGICAL := TRUE;
   END_LOCAL;
     
     n := SIZEOF (a_path.edge_list);
     REPEAT i := 2 TO n;
       p := p AND (a_path.edge_list[i-1].edge_end :=:
                   a_path.edge_list[i].edge_start);
     END_REPEAT;
     
     RETURN (p);
 END_FUNCTION;

END_SCHEMA;

(* Last update -  24 Aug 2009 *)
(*
   $Id: arm.exp,v 1.9 2013/10/29 22:07:40 thomasrthurman Exp $
   ISO TC184/SC4/WG12 N8011 - ISO/TS 10303-1776 Extended date - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5368
*)
SCHEMA Extended_date_arm; 

USE FROM Date_time_arm; 

  TYPE date_select = SELECT ( 
    Calendar_date, 
    Year_month, 
    Date,
    Ordinal_date, 
    Week_of_year_and_day_date);
  END_TYPE; 

  TYPE date_or_date_time_select = EXTENSIBLE GENERIC_ENTITY SELECT
    (Calendar_date, 
     Date_time,
     Year_month, 
     Date,
     Ordinal_date, 
     Week_of_year_and_day_date);
  END_TYPE;


  TYPE day_in_year_number = INTEGER;
    WHERE
      WR1: {1 <= SELF <= 366};
  END_TYPE; 

  TYPE day_in_week_number = INTEGER;
    WHERE
      WR1: { 1 <= SELF <= 7 };
  END_TYPE; 
    
  TYPE week_in_year_number = INTEGER;
    WHERE
      WR1: { 1 <= SELF <= 53 };
  END_TYPE; 
   
  ENTITY Year_month;
    month_component : month_in_year_number; 
    year_component  : year_number; 
  END_ENTITY;  

  ENTITY Date;
    year_component  : year_number; 
  END_ENTITY;  
 
  ENTITY Ordinal_date;
      day_component  : day_in_year_number;   
      year_component : year_number; 
    WHERE 
      WR1:  ( NOT leap_year ( SELF  . year_component ) AND  { 1 <= day_component <= 365 } ) OR 
        ( leap_year ( SELF . year_component ) AND { 1 <= day_component <= 366 } ) ;  
  END_ENTITY; 
 
  ENTITY Week_of_year_and_day_date;
    day_component  : OPTIONAL day_in_week_number;   
    year_component : year_number; 
    week_component : week_in_year_number; 
  END_ENTITY; 

  FUNCTION leap_year
    (year : year_number) : BOOLEAN;
      IF ( ( ( ( year MOD  4 ) = 0 ) AND 
        ( ( year MOD  100 ) <> 0 ) ) OR ( ( year MOD 400 ) = 0 ) ) 
        THEN 
          RETURN  ( TRUE ) ; 
        ELSE 
          RETURN ( FALSE ) ; 
      END_IF ; 
  END_FUNCTION;

END_SCHEMA; 
(*
$Id: arm.exp,v 1.27 2012/11/09 21:40:58 thomasrthurman Exp $
ISO TC184/SC4/WG12 N8265 - ISO/TS 10303-1106 Extended measure representation - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N5371
*) 


SCHEMA Extended_measure_representation_arm;

USE FROM Qualified_measure_arm; -- ISO/CD-TS 10303-1782

  ENTITY Measure_item_with_precision
    SUBTYPE OF (Measure_item);
      significant_digits : INTEGER;
  END_ENTITY;

  ENTITY Value_limit
    SUBTYPE OF (Numerical_item_with_unit, Qualified_representation_item);
      SELF\Qualified_representation_item.qualifiers : SET[1:1] OF Pre_defined_type_qualifier;
    WHERE
      WR1:SELF\Qualified_representation_item.qualifiers[1]\Type_qualifier.name in ['minimum', 'maximum'];
  END_ENTITY;   

  ENTITY Value_list
    SUBTYPE OF (Measure_item);
      values : LIST[1:?] OF Measure_item;
  END_ENTITY;

  ENTITY Value_range
    SUBTYPE OF (Measure_item);
      lower_limit : Numerical_item_with_unit;
      upper_limit : Numerical_item_with_unit;
  END_ENTITY;

  ENTITY Value_range_with_global_unit
    SUBTYPE OF (Measure_item);
      lower_limit : Numerical_item_with_global_unit;
      upper_limit : Numerical_item_with_global_unit;
  END_ENTITY;

  ENTITY Value_set
    SUBTYPE OF (Measure_item);
      values : SET[1:?] OF Measure_item;
  END_ENTITY;

  ENTITY Value_with_tolerances
    SUBTYPE OF (Measure_item);
      item_value : Numerical_item_with_unit;
      lower_limit : REAL;
      upper_limit : REAL;
  END_ENTITY;

  SUBTYPE_CONSTRAINT alternate_measure_items FOR Measure_item;
    ABSTRACT SUPERTYPE;
    ONEOF (Measure_item_with_precision,
           Numerical_item_with_global_unit,
           Numerical_item_with_unit,
           Value_list,
           Value_range,
           Value_range_with_global_unit,
           Value_set,
           Value_with_tolerances);
  END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(*
 $Id: arm.exp,v 1.12 2008/09/12 12:13:34 liutkuviene Exp $
 ISO TC184/SC4/WG12 N5374 - ISO/TS 10303-1275 External class - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N4732
*) 

SCHEMA External_class_arm;

USE FROM Class_arm;    -- ISO/TS 10303-1070

USE FROM External_source_arm; -- ISO/CD-TS 10303-1331

USE FROM Name_assignment_arm; -- ISO/TS 10303-1340


  TYPE external_class_assigned_name_select = SELECT BASED_ON assigned_name_select WITH 
    (External_class_library);
  END_TYPE; 

  ENTITY External_class
    SUBTYPE OF (Class);
      external_source : External_class_library;
  END_ENTITY;

  ENTITY External_class_library
    SUBTYPE OF (External_source);
  END_ENTITY;

END_SCHEMA;


(*
 $Id: arm.exp,v 1.12 2004/10/21 17:59:15 darla Exp $
 ISO TC184/SC4/WG12 N1207 - ISO/TS 10303-1128 External item identification assignment - EXPRESS ARM
*)

 
SCHEMA External_item_identification_assignment_arm;

TYPE external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE;

ENTITY External_item_identification
SUBTYPE OF (External_source_identification);
  external_id : STRING;
END_ENTITY;

ENTITY External_source_identification;
  source_id	  : STRING;
  source_type : STRING;
  item 	  : external_identification_item;
  description : OPTIONAL STRING;
END_ENTITY;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.6 2009/04/22 20:07:49 liutkuviene Exp $
   ISO TC184/SC4/WG12 N6234 - ISO/TS 10303-1778 External library - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5380
*)

SCHEMA External_library_arm;

USE FROM External_source_arm;  -- ISO/TS 10303-1331

USE FROM Plib_class_reference_arm; -- ISO/TS 10303-1291

  TYPE el_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH  
    (User_defined_library_or_dictionary);
  END_TYPE;

  ENTITY Iso15926_4_rdl
    SUBTYPE OF (Known_source); 
  END_ENTITY; 

  ENTITY Known_source 
    ABSTRACT SUPERTYPE OF (ONEOF(Iso15926_4_rdl,
      Otd_catalogue,
      Otd_dictionary,
      Plib_dictionary,
      Plib_library))
    SUBTYPE OF (External_source); 
  END_ENTITY; 

  ENTITY Otd_catalogue 
    SUBTYPE OF (Known_source); 
  END_ENTITY; 

  ENTITY Otd_dictionary 
    SUBTYPE OF (Known_source); 
  END_ENTITY; 

  ENTITY Plib_dictionary 
    SUBTYPE OF (Known_source); 
  END_ENTITY; 
 
  ENTITY Plib_library 
    SUBTYPE OF (Known_source); 
  END_ENTITY; 
  
  ENTITY User_defined_library_or_dictionary 
    SUBTYPE OF (External_source); 
    INVERSE
      source : External_source_identification FOR item;
  END_ENTITY;

  SUBTYPE_CONSTRAINT external_source_subtypes FOR External_source; 
	(ONEOF (Known_source,
	  User_defined_library_or_dictionary));
  END_SUBTYPE_CONSTRAINT;
  
END_SCHEMA;
(*
 $Id: arm.exp,v 1.5 2012/10/06 20:09:56 liutkuviene Exp $
 ISO TC184/SC4/WG12 N7678 - ISO/TS 10303-1033 External model - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1228
*)

SCHEMA External_model_arm;

USE FROM Elemental_geometric_shape_arm;

USE FROM File_identification_arm;

ENTITY External_geometric_model
SUBTYPE OF (Geometric_model);
   SELF\Representation.items: SET[1:1] OF Axis_placement;
   external_file: Digital_file;
WHERE
WR1: SELF\Representation.context_of_items\Geometric_coordinate_space.dimension_count = 3;
WR2: SELF\Representation.context_of_items.kind = 'external';
END_ENTITY;

END_SCHEMA;

(*
 $Id: arm.exp,v 1.14 2012/10/11 19:02:51 thomasrthurman Exp $
 ISO TC184/SC4/WG12 N8014 - ISO/TS 10303-1129 External properties - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N7439
*)

SCHEMA External_properties_arm;

USE FROM External_library_arm; -- ISO/TS 10303-1778

USE FROM Identification_assignment_arm; -- ISO/TS 10303-1021

USE FROM Independent_property_arm; -- ISO/TS 10303-1036

USE FROM Plib_class_reference_arm; -- ISO/TS 10303-1291


  TYPE external_property_select = SELECT (Plib_property_reference, External_library_property);
  END_TYPE;

  ENTITY External_library_property
    SUBTYPE OF (Independent_property);
      external_id  : STRING;    
      source       : External_source;
    DERIVE
      library_type : STRING := source.id;
  END_ENTITY;

  ENTITY Plib_property_reference
    SUBTYPE OF (Independent_property);
      code       : STRING;
      version    : STRING;
      name_scope : Plib_class_reference;
  END_ENTITY;

  SUBTYPE_CONSTRAINT plib_or_external FOR Independent_property;
    ONEOF(Plib_property_reference, External_library_property);
  END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.4 2008/09/12 12:28:23 liutkuviene Exp $
   ISO TC184/SC4/WG12 N5386 - ISO/TS 10303-1331 External source - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5075
 *)

SCHEMA External_source_arm;

  ENTITY External_source; 
    id          : STRING;
    description : OPTIONAL STRING;
  END_ENTITY;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.40 2012/10/11 05:49:23 liutkuviene Exp $
   ISO TC184/SC4/WG12 N8017 - ISO/TS 10303-1671 Feature and connection zone - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7442
*)

SCHEMA Feature_and_connection_zone_arm; 

	USE FROM Shape_feature_arm; 
	USE FROM Surface_conditions_arm;
    REFERENCE FROM Support_resource_arm(bag_to_set); 

ENTITY Connection_zone
  SUBTYPE OF (Shape_element);
INVERSE
  surface_conditions : SET OF Surface_condition FOR described_element; 		
WHERE
  WR1 : NOT EXISTS (SELF\Shape_element.description);
  WR2 : NOT EXISTS (SELF\Shape_element.element_name);
END_ENTITY;

ENTITY Definitional_shape_element
  ABSTRACT SUPERTYPE
  SUBTYPE OF (Shape_element);
  connection_area : OPTIONAL SET[1:?] OF Connection_zone;
INVERSE
  surface_conditions : SET OF Surface_condition FOR described_element; 		
UNIQUE
  UR1 : SELF\Shape_element.element_name, 
        SELF\shape_element.containing_shape;
END_ENTITY;

ENTITY Feature_definition_with_connection_area
  SUBTYPE OF (Shape_feature_definition);
  connection_area : OPTIONAL SET [1:?] OF Connection_zone;
END_ENTITY;

ENTITY Non_definitional_shape_element 	 
  SUBTYPE OF (Shape_element); 	 
END_ENTITY;

SUBTYPE_CONSTRAINT fac_shape_element FOR Shape_element;
  ONEOF (Instanced_feature, Placed_feature) ANDOR
  ONEOF (Definitional_shape_element, Non_definitional_shape_element);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(*
 $Id: arm.exp,v 1.16 2010/06/02 13:17:19 philsp Exp $
 ISO TC184/SC4/WG12 N2123 - ISO/TS 10303-1127 File identification - EXPRESS ARM
*)

SCHEMA File_identification_arm;

USE FROM External_item_identification_assignment_arm;    -- ISO/TS 10303-1128


TYPE located_select = SELECT BASED_ON external_identification_item WITH 
   (File);
END_TYPE; 

ENTITY Digital_file
  SUBTYPE OF (File);
END_ENTITY;

ENTITY File
  ABSTRACT SUPERTYPE OF (ONEOF (Digital_file,
                                Hardcopy));
  id : STRING;
  version : OPTIONAL STRING;
  contained_data_type : OPTIONAL STRING;
END_ENTITY;

ENTITY File_location_identification
  SUBTYPE OF (External_item_identification);
WHERE
  WR1: 'FILE_IDENTIFICATION_ARM.FILE' IN TYPEOF(SELF\External_source_identification.item);
END_ENTITY;

ENTITY Hardcopy
  SUBTYPE OF (File);
END_ENTITY;

END_SCHEMA;  -- File_identification_arm
(*
$Id: arm.exp,v 1.20 2009/12/21 09:20:21 liutkuviene Exp $
ISO TC184/SC4/WG12 N6902 - ISO/TS 10303-1006 Foundation representation - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N4348
*) 


SCHEMA Foundation_representation_arm; 

USE FROM Support_resource_arm;
REFERENCE FROM Support_resource_arm (bag_to_set);
USE FROM Value_with_unit_arm;    -- ISO/TS 10303-1054


ENTITY Numerical_representation_context
  SUBTYPE OF (Representation_context);
  units : OPTIONAL SET[1:?] OF Unit;
  accuracies : OPTIONAL SET[1:?] OF Uncertainty_with_unit;
END_ENTITY;

ENTITY Representation;
  id : OPTIONAL identifier;
  name : OPTIONAL label;
  description : OPTIONAL text;
  context_of_items : Representation_context;
  items : SET[1:?] OF Representation_item;
WHERE
  WR1 : EXISTS(name) OR (TYPEOF(SELF\Representation) <> TYPEOF(SELF));
END_ENTITY;

ENTITY Representation_context;
  id : identifier;
  kind : text;
INVERSE
  representations_in_context : SET[1:?] OF Representation FOR context_of_items;
END_ENTITY;

ENTITY Representation_item
  ABSTRACT SUPERTYPE ;
  name : OPTIONAL label;
END_ENTITY;

ENTITY Representation_relationship;
  relation_type : OPTIONAL label;
  description : OPTIONAL text;
  rep_1 : Representation;
  rep_2 : Representation;
WHERE
  WR1 : EXISTS(relation_type) OR (TYPEOF(SELF\Representation_relationship) <> TYPEOF(SELF));
  WR2 : EXISTS(description) OR (TYPEOF(SELF\Representation_relationship) <> TYPEOF(SELF));
END_ENTITY;

ENTITY String_representation_item
  SUBTYPE OF (Representation_item);
  string_value : STRING;
END_ENTITY;

  FUNCTION using_representations (item : Representation_item): SET OF Representation;
    LOCAL
      results            : SET OF Representation;
      result_bag         : BAG OF Representation;
      intermediate_items : SET OF Representation_item;
    END_LOCAL;
    -- Find the representations in which the item is used and add to the
    -- results set.
    results := [];
    result_bag := USEDIN(item,'FOUNDATION_REPRESENTATION_ARM.REPRESENTATION.ITEMS');
    IF SIZEOF(result_bag) > 0 THEN
      REPEAT i := 1 TO HIINDEX(result_bag);
        results := results + result_bag[i];
      END_REPEAT;
    END_IF;
    -- Find all representation_items or founded_items
    -- by which item is referenced directly or indirectly.
    intermediate_items := using_items(item,[]);
    -- If the set of intermediate items is not empty;
    IF SIZEOF(intermediate_items) > 0 THEN
      -- For each element in the set, add the
      -- representations of that element.
      REPEAT i := 1 TO HIINDEX(intermediate_items);
        result_bag := USEDIN(intermediate_items[i],
                      'FOUNDATION_REPRESENTATION_ARM.REPRESENTATION.ITEMS');
        IF SIZEOF(result_bag) > 0 THEN
          REPEAT j := 1 TO HIINDEX(result_bag);
            results := results + result_bag[j];
          END_REPEAT;
        END_IF;
      END_REPEAT;
    END_IF;
    -- Return the set of representation in which the input item is
    -- used directly and indirectly (through intervening
    -- representation_items or founded items).
    RETURN (results);
  END_FUNCTION;

  FUNCTION using_items (item : Representation_item;
                        checked_items: SET OF Representation_item)
                      : SET OF Representation_item;
    LOCAL
      new_check_items    : SET OF Representation_item;
      result_items       : SET OF Representation_item;
      next_items         : SET OF Representation_item;
    END_LOCAL;
    result_items := [];
    new_check_items := checked_items + item;
    -- Find the set of representation_items or founded_items
    -- in which item is used directly.
    next_items := QUERY(z <* bag_to_set( USEDIN(item , '')) |
      ('FOUNDATION_REPRESENTATION_ARM.REPRESENTATION_ITEM' IN TYPEOF(z)));
    -- If the set of next_items is not empty;
    IF SIZEOF(next_items) > 0 THEN
      -- For each element in the set, find the using_items recursively
      REPEAT i := 1 TO HIINDEX(next_items);
        -- Check for loop in data model, i.e. one of the next_items
        -- occurred earlier in the set of check_items;
        IF NOT(next_items[i] IN new_check_items) THEN
          result_items := result_items + next_items[i] +
                          using_items(next_items[i],new_check_items);
        END_IF;
      END_REPEAT;
    END_IF;
    -- return the set of representation_items or founded_items
    -- in which the input item is used directly and indirectly.
    RETURN (result_items);
  END_FUNCTION;

END_SCHEMA;  -- Foundation_representation_arm
(*
   $Id: arm.exp,v 1.20 2012/10/06 20:09:56 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7720 - ISO/TS 10303-1681 Generic material aspects - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5401
*)

SCHEMA Generic_material_aspects_arm;

USE FROM Independent_property_representation_arm;	-- ISO/TS 10303-1038

  TYPE material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE material_property_select = SELECT (Material_property, General_material_property);
  END_TYPE;

  TYPE dependent_or_independent_property_representation = SELECT(
    Independent_property_representation,
    Property_representation);
  END_TYPE;

 ENTITY Applied_independent_material_property SUBTYPE OF
    (Material_property, Applied_independent_property);
     SELF\Applied_independent_property.base_independent_property: General_material_property;
  END_ENTITY;

 ENTITY Data_environment;
  environment_name : STRING;
  description : OPTIONAL STRING;
  environment_characterization: SET[1:?] OF dependent_or_independent_property_representation;
 END_ENTITY;

 ENTITY Material_identification;
  material_name : STRING;
  items : SET[1:?] OF material_item_select;
 END_ENTITY;

 ENTITY Material_property
  SUBTYPE OF (Assigned_property);
 END_ENTITY;

 ENTITY Material_property_association;
  described_material : Material_identification;
  associated_property_value : Material_property_value_representation;
  definitional : OPTIONAL BOOLEAN;
 END_ENTITY;

 ENTITY Material_property_value_representation
  SUBTYPE OF (Property_definition_representation);
    environment_condition                                               : Data_environment;
    SELF\Property_definition_representation.definition RENAMED property : material_property_select;
 END_ENTITY;

 ENTITY General_material_property
  SUBTYPE OF (Independent_property);
  WHERE
    WR1:  SIZEOF(QUERY( aip <* USEDIN(SELF,'PROPERTY_ASSIGNMENT_ARM.APPLIED_INDEPENDENT_PROPERTY.'+
                     'BASE_INDEPENDENT_PROPERTY') |
               NOT
			('GENERIC_MATERIAL_ASPECTS_ARM.APPLIED_INDEPENDENT_MATERIAL_PROPERTY' IN
                    TYPEOF(aip)))) = 0;
 END_ENTITY;


END_SCHEMA;
(*
   $Id: arm.exp,v 1.8 2012/10/11 05:49:26 liutkuviene Exp $
   ISO TC184/SC4/WG12 N8023 - ISO/TS 10303-1403 Geometric model relationship - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N6905
*)
   
SCHEMA Geometric_model_relationship_arm;

USE FROM Elemental_geometric_shape_arm;    -- ISO/TS 10303-1004
REFERENCE FROM Support_resource_arm (bag_to_set);  

TYPE geometric_representation_select = EXTENSIBLE GENERIC_ENTITY SELECT (
  Geometric_model);
END_TYPE;  

ENTITY Definitional_representation_relationship
  SUBTYPE OF (Representation_relationship);
    WHERE
      WR1: acyclic_representation_relationship(SELF,
        [SELF\representation_relationship.rep_2],
        'FOUNDATION_REPRESENTATION_ARM.'+
        'REPRESENTATION');
END_ENTITY;  

ENTITY Geometric_model_relationship
 SUBTYPE OF (Representation_relationship);
    SELF\Representation_relationship.rep_1 : geometric_representation_select;
    SELF\Representation_relationship.rep_2 : geometric_representation_select;
  WHERE
    WR1 : rep_1 <> rep_2;
END_ENTITY;

FUNCTION acyclic_representation_relationship
  (relation : representation_relationship; relatives : SET[1:?] OF representation; specific_relation : STRING) : BOOLEAN; 
  LOCAL
    x : SET OF representation_relationship;
  END_LOCAL;

  IF relation.rep_1 IN relatives THEN
    RETURN (FALSE);
  END_IF;
  x := QUERY(r <* bag_to_set(USEDIN(relation.rep_1, 'FOUNDATION_REPRESENTATION_ARM.' + 'REPRESENTATION_RELATIONSHIP.' + 'REP_2')) | specific_relation IN TYPEOF(r));
  REPEAT i := 1 TO HIINDEX(x);
    IF NOT acyclic_representation_relationship(x[i], relatives + relation.rep_1, specific_relation) THEN
      RETURN (FALSE);
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_FUNCTION; 

END_SCHEMA;
(*
$Id: arm.exp,v 1.11 2010/06/09 22:02:45 philsp Exp $
ISO TC184/SC4/WG12 N7114 - ISO/TS 10303-1021 Identification assignment - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N1111
*)
  
SCHEMA Identification_assignment_arm;


TYPE identification_item = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

ENTITY Identification_assignment;
  identifier : STRING;
  role : STRING;
  description : OPTIONAL STRING;
  items : SET[1:?] OF identification_item;
END_ENTITY;

END_SCHEMA;  -- Identification_assignment_arm
(*
 $Id: arm.exp,v 1.11 2004/10/28 19:05:37 darla Exp $
 ISO TC184/SC4/WG12 N2964 - ISO/TS 10303-1036 Independent property - EXPRESS ARM
*) 


SCHEMA Independent_property_arm; 


ENTITY Independent_property;
  id : STRING;
  property_type : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

ENTITY Independent_property_relationship;
  relation_type : STRING;
  description : OPTIONAL STRING;
  relating : Independent_property;
  related : Independent_property;
END_ENTITY;

END_SCHEMA;  -- Independent_property_arm
(*
 $Id: arm.exp,v 1.10 2006/03/24 18:37:02 thendrix Exp $
 ISO TC184/SC4/WG12 N4371 - ISO/TS 10303-1038 Independent property representation - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2966
*) 


SCHEMA Independent_property_representation_arm; 

USE FROM Property_assignment_arm;    -- ISO/TS 10303-1030 

ENTITY Independent_property_representation
  SUBTYPE OF (Property_definition_representation);
    SELF\Property_definition_representation.definition RENAMED property : Independent_property;
END_ENTITY;

END_SCHEMA;  -- Independent_property_representation_arm
(*
 $Id: arm.exp,v 1.11 2004/10/28 19:08:56 darla Exp $
 ISO TC184/SC4/WG12 N2968 - ISO/TS 10303-1118 Measure representation - EXPRESS ARM
*) 


SCHEMA Measure_representation_arm;

USE FROM Foundation_representation_arm;    -- ISO/TS 10303-1006

USE FROM Value_with_unit_arm;    -- ISO/TS 10303-1054


ENTITY Measure_item
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (Representation_item);
WHERE
  WR1: SIZEOF(USEDIN(SELF, 'FOUNDATION_REPRESENTATION_ARM.REPRESENTATION.ITEMS'))>0;
END_ENTITY;

ENTITY Numerical_item_with_global_unit
  SUBTYPE OF (Measure_item);
  value_component : measure_value;
WHERE
  WR1: SIZEOF(QUERY(pvr <* QUERY ( r <* USEDIN(SELF, 'FOUNDATION_REPRESENTATION_ARM.REPRESENTATION.ITEMS')| 'MEASURE_REPRESENTATION_ARM.PROPERTY_VALUE_REPRESENTATION' IN TYPEOF(r)) | EXISTS(pvr.context_of_items.units) )) > 0;
END_ENTITY;

ENTITY Numerical_item_with_unit
  SUBTYPE OF (Measure_item, Value_with_unit);
END_ENTITY;

ENTITY Property_value_representation
  SUBTYPE OF (Representation);
  SELF\Representation.context_of_items : Numerical_representation_context;
END_ENTITY;

END_SCHEMA;  -- Measure_representation_arm
(*
 $Id: arm.exp,v 1.4 2004/11/19 21:37:37 robbod Exp $
 ISO TC184/SC4/WG12 N3085 - ISO/TS 10303-1340 Name assignment - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2282
*) 


SCHEMA Name_assignment_arm;


TYPE assigned_name_select = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

ENTITY Name_assignment;
  name : STRING;
  role : STRING;
  items : assigned_name_select;
END_ENTITY;

END_SCHEMA;  -- Name_assignment_arm


(*
 $Id: arm.exp,v 1.23 2012/10/06 20:09:56 liutkuviene Exp $
 ISO TC184/SC4/WG12 N7702 - ISO/TS 10303-1022 Part and version identification - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N6051
*) 


SCHEMA Part_and_version_identification_arm;

USE FROM Product_identification_arm;    -- ISO/TS 10303-1017

USE FROM Product_version_arm;    -- ISO/TS 10303-1018


ENTITY Part
  SUBTYPE OF (Product);
END_ENTITY;

ENTITY Part_version
  SUBTYPE OF (Product_version);
  SELF\Product_version.of_product : Part;
END_ENTITY;

END_SCHEMA;  -- Part_and_version_identification_arm
(*
 $Id: arm.exp,v 1.15 2012/10/11 05:49:25 liutkuviene Exp $
 ISO TC184/SC4/WG12 N8038 - ISO/TS 10303-1023 Part view definition - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N7454
*) 


SCHEMA Part_view_definition_arm;

USE FROM Part_and_version_identification_arm;    -- ISO/TS 10303-1022

USE FROM Product_view_definition_arm;    -- ISO/TS 10303-1019

ENTITY Part_view_definition
  SUBTYPE OF (Product_view_definition);
  SELF\Product_view_definition.defined_version : Part_version;
  SELF\Product_view_definition.initial_context: Part_view_definition_context;
  SELF\Product_view_definition.additional_contexts: SET [0:?] OF Part_view_definition_context;
END_ENTITY;

ENTITY Part_view_definition_context
  SUBTYPE OF (View_definition_context);
WHERE
  WR1: SIZEOF ( QUERY ( pvd <* USEDIN(SELF, 'PRODUCT_VIEW_DEFINITION_ARM.PRODUCT_VIEW_DEFINITION.INITIAL_CONTEXT')
                        |  NOT ( 'PART_VIEW_DEFINITION_ARM.PART_VIEW_DEFINITION' IN TYPEOF (pvd) ) ) ) =0 ;
  WR2: SIZEOF ( QUERY ( pvd <* USEDIN(SELF, 'PRODUCT_VIEW_DEFINITION_ARM.PRODUCT_VIEW_DEFINITION.ADDITIONAL_CONTEXTS')
                        |  NOT ( 'PART_VIEW_DEFINITION_ARM.PART_VIEW_DEFINITION' IN TYPEOF (pvd) ) ) ) =0 ;
END_ENTITY;

RULE part_view_definition_constraint FOR 
(Product_view_definition);
WHERE
  WR1: SIZEOF ( QUERY ( pvd <* Product_view_definition | ( NOT ( 'PART_VIEW_DEFINITION_ARM.PART_VIEW_DEFINITION' IN TYPEOF (pvd) ) ) AND ( 'PART_VIEW_DEFINITION_ARM.PART_VERSION' IN TYPEOF ( pvd.defined_version) ) ) ) =0 ;
END_RULE; 

END_SCHEMA;  -- Part_view_definition_arm
(*
 $Id: arm.exp,v 1.16 2004/10/28 17:08:02 darla Exp $
 ISO TC184/SC4/WG12 N2921 - ISO/TS 10303-1011 Person organization - EXPRESS ARM
*)
 


SCHEMA Person_organization_arm;


TYPE organization_or_person_in_organization_select = SELECT
   (Organization, 
    Person_in_organization);
END_TYPE; 

ENTITY Address;
  name : OPTIONAL STRING;
  street_number : OPTIONAL STRING;
  street : OPTIONAL STRING;
  postal_box : OPTIONAL STRING;
  town : OPTIONAL STRING;
  region : OPTIONAL STRING;
  postal_code : OPTIONAL STRING;
  country : OPTIONAL STRING;
  internal_location : OPTIONAL STRING;
  facsimile_number : OPTIONAL STRING;
  telephone_number : OPTIONAL STRING;
  electronic_mail_address : OPTIONAL STRING;
  telex_number : OPTIONAL STRING;
  url : OPTIONAL STRING;
WHERE
  WR1: (EXISTS (street_number) OR EXISTS (street) OR EXISTS (postal_box) OR EXISTS (town) OR EXISTS (region) OR EXISTS (postal_code) OR EXISTS (country) OR EXISTS (internal_location) OR EXISTS (facsimile_number) OR EXISTS (telephone_number) OR EXISTS (electronic_mail_address) OR EXISTS (telex_number));
END_ENTITY;

ENTITY Address_assignment;
  address_type : OPTIONAL STRING;
  assigned_address : Address;
  located_person_organizations : SET[1:?] OF organization_or_person_in_organization_select;
END_ENTITY;

ENTITY Organization;
  id : OPTIONAL STRING;
  name : STRING;
END_ENTITY;

ENTITY Organization_relationship;
  relation_type : STRING;
  description : OPTIONAL STRING;
  relating_organization : Organization;
  related_organization : Organization;
END_ENTITY;

ENTITY Person;
  last_name : STRING;
  first_name : OPTIONAL STRING;
  middle_names : OPTIONAL LIST[1:?] OF STRING;
  prefix_titles : OPTIONAL LIST[1:?] OF STRING;
  suffix_titles : OPTIONAL LIST[1:?] OF STRING;
END_ENTITY;

ENTITY Person_in_organization;
  concerned_person : Person;
  containing_organization : Organization;
  role : STRING;
END_ENTITY;

END_SCHEMA;  -- Person_organization_arm
(*
$Id: arm.exp,v 1.10 2010/06/09 21:51:47 philsp Exp $
ISO TC184/SC4/WG12 N7122 - ISO/TS 10303-1013 Person organization assignment - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N1090
*)
  
SCHEMA Person_organization_assignment_arm;

USE FROM Person_organization_arm;    -- ISO/TS 10303-1011


TYPE organization_or_person_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

ENTITY Organization_or_person_in_organization_assignment;
  assigned_entity : organization_or_person_in_organization_select;
  role : STRING;
  items : SET[1:?] OF organization_or_person_in_organization_item;
END_ENTITY;

END_SCHEMA;  -- Person_organization_assignment_arm
(*
 $Id: arm.exp,v 1.9 2008/09/13 12:26:56 liutkuviene Exp $
 ISO TC184/SC4/WG12 N5455 - ISO/TS 10303-1291 Plib class reference - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N4840
*) 


SCHEMA Plib_class_reference_arm; 

USE FROM External_class_arm;    -- ISO/TS 10303-1275

USE FROM External_item_identification_assignment_arm;    -- ISO/TS 10303-1128

USE FROM Person_organization_assignment_arm;    -- ISO/TS 10303-1013


  ENTITY Plib_class_reference;
    code         : STRING;
    supplier_bsu : STRING;
    version      : STRING;
  END_ENTITY;

END_SCHEMA; 


(*
 $Id: arm.exp,v 1.5 2004/10/22 14:44:52 darla Exp $
 ISO TC184/SC4/WG12 N1177 - ISO/TS 10303-1060 Product concept identification - EXPRESS ARM
*)
   
SCHEMA Product_concept_identification_arm;
   
ENTITY Market;
  name                      : STRING;
  market_segment_type       : OPTIONAL STRING;
END_ENTITY;

   
ENTITY Product_concept;
  id                        : STRING;
  name                      : STRING;
  description               : OPTIONAL STRING;
  target_market             : OPTIONAL Market;
UNIQUE
  UR1: id;
END_ENTITY;

   
END_SCHEMA;

(*
$Id: arm.exp,v 1.19 2009/08/11 07:57:31 robbod Exp $
ISO TC184/SC4/WG12 N6065 - ISO/TS 10303-1017 Product identification - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N2925
*) 


SCHEMA Product_identification_arm;


ENTITY Product;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

END_SCHEMA;  -- Product_identification_arm
(*
 $Id: arm.exp,v 1.6 2004/01/13 10:15:26 robbod Exp $
 ISO TC184/SC4/WG12 N2527 - ISO/TS 10303-1018 Product version - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1105
*) 


SCHEMA Product_version_arm; 

USE FROM Product_identification_arm;    -- ISO/TS 10303-1017


ENTITY Product_version;
  id : STRING;
  description : OPTIONAL STRING;
  of_product : Product;
END_ENTITY;

END_SCHEMA;  -- Product_version_arm

(*
 $Id: arm.exp,v 1.8 2006/03/24 19:03:52 thendrix Exp $
 ISO TC184/SC4/WG12 N4351 - ISO/TS 10303-1019 Product view definition - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1532
*)
   
SCHEMA Product_view_definition_arm;

USE FROM Product_version_arm;
         
ENTITY Product_view_definition;
  id              	: OPTIONAL STRING;
  name  	      	: OPTIONAL STRING;
  additional_characterization	      : OPTIONAL STRING;
  initial_context 	: View_definition_context;
  additional_contexts   : SET [0:?] OF View_definition_context;
  defined_version  	: Product_version;
WHERE
  WR1: NOT (initial_context IN additional_contexts);
  WR2: EXISTS(id) OR (TYPEOF(SELF\Product_view_definition) <> TYPEOF(SELF));
END_ENTITY;
   
ENTITY View_definition_context;
  application_domain	: STRING;
  life_cycle_stage 	: STRING;
  description	 	: OPTIONAL STRING;
WHERE
  WR1: (SIZEOF (USEDIN(SELF, 'PRODUCT_VIEW_DEFINITION_ARM.' +
    'PRODUCT_VIEW_DEFINITION.INITIAL_CONTEXT')) > 0) OR
    (SIZEOF (USEDIN(SELF, 'PRODUCT_VIEW_DEFINITION_ARM.' +
    'PRODUCT_VIEW_DEFINITION.ADDITIONAL_CONTEXTS')) > 0);
END_ENTITY;
   
END_SCHEMA;

(*
   $Id: arm.exp,v 1.2 2012/10/11 05:49:13 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7768 - ISO/TS 10303-1823 Product view definition reference - EXPRESS ARM*)

SCHEMA Product_view_definition_reference_arm;

	USE FROM Support_resource_arm; -- ISO/TS 10303-1800
	USE FROM External_item_identification_assignment_arm;	-- ISO/TS 10303-1128
	USE FROM Product_view_definition_arm;	-- ISO/TS 10303-1019

 	TYPE pie_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH  
		(Generic_product_view_definition_reference);
	END_TYPE;

  ENTITY Generic_product_view_definition_reference
    ABSTRACT SUPERTYPE OF ( ONEOF ( Product_view_definition_reference, 
                  Product_view_definition_reference_with_local_representation) );
    source : External_source_identification;
  END_ENTITY;

  ENTITY Product_view_definition_reference
    SUBTYPE OF (Generic_product_view_definition_reference);
    product_id : identifier;
    product_definition_formation_id : identifier;
    product_definition_id : identifier;
    id_owning_organization_name : OPTIONAL label;
  END_ENTITY;

  ENTITY Product_view_definition_reference_with_local_representation
    SUBTYPE OF (Generic_product_view_definition_reference, Product_view_definition);
  END_ENTITY;

END_SCHEMA;
(*
 $Id: arm.exp,v 1.14 2012/09/22 22:35:47 thomasrthurman Exp $
 ISO TC184/SC4/WG12 N2939 - ISO/TS 10303-1041 Product view definition relationship - EXPRESS ARM
*)


SCHEMA Product_view_definition_relationship_arm;

USE FROM Product_view_definition_arm;    -- ISO/TS 10303-1019
USE FROM Product_view_definition_reference_arm; -- ISO/TS 10303-1738

TYPE as_product_view_definition_or_reference = SELECT (
    Product_view_definition, 
    Generic_product_view_definition_reference);
END_TYPE;

ENTITY View_definition_relationship;
  id : OPTIONAL STRING;
  relation_type : OPTIONAL STRING;
  description : OPTIONAL STRING;
  relating_view : as_product_view_definition_or_reference;
  related_view : as_product_view_definition_or_reference;
END_ENTITY;

ENTITY View_definition_usage
  SUBTYPE OF (View_definition_relationship);
END_ENTITY;

END_SCHEMA;  -- Product_view_definition_relationship_arm
(*
 $Id: arm.exp,v 1.17 2012/10/11 05:49:17 liutkuviene Exp $
 ISO TC184/SC4/WG12 N8041 - ISO/TS 10303-1030 Property assignment - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N7457
*)


SCHEMA Property_assignment_arm; 

USE FROM Foundation_representation_arm;    -- ISO/TS 10303-1006

USE FROM Independent_property_arm;    -- ISO/TS 10303-1036


TYPE property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

TYPE represented_definition = EXTENSIBLE GENERIC_ENTITY SELECT (
    Independent_property,
    Assigned_property);
END_TYPE;

ENTITY Applied_independent_property
  SUBTYPE OF (Assigned_property);
  base_independent_property : Independent_property;
DERIVE
  SELF\Assigned_property.name : STRING := base_independent_property.property_type;
END_ENTITY;

ENTITY Assigned_property;
  id : OPTIONAL STRING;
  name : STRING;
  description : OPTIONAL STRING;
  described_element : property_assignment_select;
END_ENTITY;

ENTITY Property_definition_representation
  ABSTRACT SUPERTYPE;
    name : OPTIONAL STRING;
    description : OPTIONAL STRING;
    definition : represented_definition;
    used_representation : Representation;
END_ENTITY;

ENTITY Property_representation
  SUBTYPE OF (Property_definition_representation);
    SELF\Property_definition_representation.definition RENAMED property : Assigned_property;
END_ENTITY;

END_SCHEMA;  -- Property_assignment_arm
(*
   $Id: arm.exp,v 1.9 2012/10/06 20:09:56 liutkuviene Exp $
   ISO TC184/SC4/WG12 N7723 - ISO/TS 10303-1782 Qualified measure - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N6558
*)

SCHEMA Qualified_measure_arm;

USE FROM Measure_representation_arm; -- ISO/TS 10303-1118

  CONSTANT
    pre_defined_type_qualifiers : SET OF STRING := ['minimum', 'maximum',
    'nominal', 'specified', 'typical', 'calculated', 'designed', 'estimated',
    'measured', 'required', 'set point',
    'basic', 'lower deviation', 'upper deviation'];
  END_CONSTANT;

  TYPE value_qualifier = SELECT
    (Precision_qualifier,
     Type_qualifier,
     Uncertainty_qualifier,
     Value_format_type_qualifier);
  END_TYPE;

  ENTITY Expanded_uncertainty
    SUBTYPE OF (Standard_uncertainty);
      coverage_factor : REAL;
  END_ENTITY;

  ENTITY Measure_qualification;
      name              : STRING; 
      description       : STRING; 
      qualified_measure : Value_with_unit;
      qualifiers        : SET[1:?] OF value_qualifier;
    WHERE
      WR1 : NOT('MEASURE_REPRESENTATION_ARM.'+'NUMERICAL_ITEM_WITH_UNIT' IN TYPEOF(qualified_measure));
      WR2 : SIZEOF(QUERY(temp <* qualifiers | 
        'QUALIFIED_MEASURE_ARM.PRECISION_QUALIFIER' IN TYPEOF(temp))) < 2;      
  END_ENTITY;

  ENTITY Precision_qualifier;
     significant_digits : INTEGER;
  END_ENTITY;

  ENTITY Pre_defined_type_qualifier
    SUBTYPE OF (Type_qualifier);
    WHERE
      WR1: SELF\Type_qualifier.name IN pre_defined_type_qualifiers;
  END_ENTITY;

  ENTITY Qualified_numerical_item_with_unit 
    SUBTYPE OF (Numerical_item_with_unit, Qualified_representation_item); 
  END_ENTITY; 

  ENTITY Qualified_representation_item 
    ABSTRACT SUPERTYPE
    SUBTYPE OF (Representation_item); 
       qualifiers : SET [1:?] OF value_qualifier; 
    WHERE 
      WR1: SIZEOF(QUERY(temp <* qualifiers | 
        'QUALIFIED_MEASURE_ARM.PRECISION_QUALIFIER' 
        IN TYPEOF(temp))) < 2; 
  END_ENTITY; 

  ENTITY Qualitative_uncertainty
    SUBTYPE OF (Uncertainty_qualifier);
      uncertainty_value : STRING; 
  END_ENTITY;

  ENTITY Representation_with_uncertainty
    SUBTYPE OF (Representation);
    uncertainty : SET[1:?] OF Uncertainty_with_unit;
  END_ENTITY;

  ENTITY Standard_uncertainty
    SUPERTYPE OF (Expanded_uncertainty)
    SUBTYPE OF (Uncertainty_qualifier);
      uncertainty_value : REAL;
  END_ENTITY;

  ENTITY Type_qualifier
    ABSTRACT SUPERTYPE OF(Pre_defined_type_qualifier);
    name : STRING;
  END_ENTITY;

  ENTITY Uncertainty_qualifier
    SUPERTYPE OF (ONEOF (Standard_uncertainty,
      Qualitative_uncertainty));
      measure_name : STRING; 
      description  : STRING; 
  END_ENTITY;

  ENTITY Value_format_type_qualifier;
     value_format_type : STRING;
    WHERE
     WR1: LENGTH(value_format_type) <= 80;
  END_ENTITY;

END_SCHEMA;
(*
   $Id: arm.exp,v 1.20 2012/10/11 05:49:13 liutkuviene Exp $
   ISO TC184/SC4/WG12 N8047 - ISO/TS 10303-1764 Shape feature - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7463
*)

SCHEMA Shape_feature_arm;

USE FROM Characterizable_object_arm; -- ISO/TS 10303-1765 
USE FROM Contextual_shape_positioning_arm; -- ISO/TS 10303-1027
REFERENCE FROM Support_resource_arm(bag_to_set);  -- ISO/TS 10303-1765
USE FROM Property_assignment_arm; --  ISO/TS 10303-1030

TYPE sf_shapeable_item = SELECT BASED_ON shapeable_item WITH 
  (Characterizable_object);
END_TYPE; 

TYPE sf_property_assignment_select = SELECT BASED_ON property_assignment_select WITH ( 
  Characterizable_object);
END_TYPE; 

ENTITY Shape_feature_definition
  SUBTYPE OF (Characterizable_object);
  DERIVE
    feature_model : SET [1:?] OF Geometric_model := get_geometric_model(of_shape); 
  INVERSE
    of_shape : Item_shape FOR described_element;
  WHERE
    WR1: EXISTS(feature_model);
END_ENTITY;

ENTITY Instanced_feature  
  SUBTYPE OF (Shape_element, Shape_feature_definition);
END_ENTITY;

ENTITY Placed_feature  
  SUBTYPE OF (Shape_element);
   definition : Shape_feature_definition;
END_ENTITY;

ENTITY General_feature
  SUBTYPE OF (Shape_feature_definition);
END_ENTITY; 

FUNCTION get_geometric_model(input : Item_shape) : SET OF Geometric_model;
  LOCAL
    sda : SET OF Shape_description_association := [];
    gm : SET OF Geometric_model := [];
  END_LOCAL;
 
  sda := bag_to_set(USEDIN(input,
	 	'PROPERTY_ASSIGNMENT_ARM.PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'));
 
  REPEAT i := 1 to SIZEOF(sda) BY 1;
    IF 'SHAPE_PROPERTY_ASSIGNMENT_ARM.SHAPE_DESCRIPTION_ASSOCIATION' IN TYPEOF (sda[i]) THEN
      gm := gm + sda[i]\Property_definition_representation.used_representation;
    END_IF;
  END_REPEAT;
  RETURN(gm);
END_FUNCTION;

SUBTYPE_CONSTRAINT sf_shape_element FOR Shape_element;
  ONEOF (Instanced_feature, Placed_feature);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
(* 
	$Id: arm.exp,v 1.51 2012/10/11 05:49:03 liutkuviene Exp $
	ISO TC184/SC4/WG12 N8050 - ISO/TS 10303-1032 Shape property assignment - EXPRESS ARM
	Supersedes ISO TC184/SC4/WG12 N7466
*)


SCHEMA Shape_property_assignment_arm; 

USE FROM Property_assignment_arm;
(*REFERENCE FROM*) USE FROM Assembly_structure_arm; -- ISO/TS 10303-1026

(*REFERENCE FROM*) USE FROM External_model_arm; -- ISO/TS 10303-1033

USE FROM Geometric_model_relationship_arm; -- ISO/TS 10303-1403 
USE FROM Product_view_definition_relationship_arm; -- ISO/TS 10303-1041

TYPE spa_property_assignment_select = SELECT BASED_ON property_assignment_select WITH ( 
  Item_shape,
  Shape_element, 
  Shape_element_relationship);
END_TYPE; 

TYPE chained_geometric_model_link = SELECT (
    Geometric_placement_operation,
    Geometric_coordinate_space,
    Geometric_model_relationship);
END_TYPE;

TYPE described_element_select = SELECT (
  View_definition_relationship,
  Product_occurrence_definition_relationship);
END_TYPE;  

TYPE shape_element_or_relationship_select = SELECT (
  Shape_element,
  Shape_element_relationship);
END_TYPE;  

TYPE geometric_item_specific_usage_select = SELECT (
  Shape_element, 
  Shape_element_relationship);
END_TYPE; 

TYPE spa_represented_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON represented_definition WITH (
    Item_shape,
    Shape_element,
    Shape_element_relationship);
END_TYPE;

TYPE assigned_shape_property_select = EXTENSIBLE GENERIC_ENTITY SELECT (
    Item_shape,
    Shape_element,
    Shape_element_relationship);
END_TYPE;

TYPE shape_model = EXTENSIBLE GENERIC_ENTITY SELECT
  (External_geometric_model, 
   Geometric_model);
END_TYPE; 

TYPE shapeable_item = EXTENSIBLE GENERIC_ENTITY SELECT
  (Product_occurrence_definition_relationship, 
   Product_view_definition, 
   View_definition_relationship);
END_TYPE; 

ENTITY Associated_item_shape
  SUBTYPE OF (Item_shape);
DERIVE
  associated_model : shape_model := association\Property_definition_representation.used_representation;
INVERSE  
  association : Shape_description_association FOR definition;
END_ENTITY;  

ENTITY Associated_shape_element 
  SUBTYPE OF (Shape_element);
  SELF\Shape_element.containing_shape : Associated_item_shape;
DERIVE
  associated_item : geometric_model_item := association\Geometric_item_specific_usage.identified_item;
INVERSE 
  association : Geometric_item_specific_usage FOR definition;
WHERE
  WR1: EXISTS(associated_item);
  WR2: association\Geometric_item_specific_usage.used_model\Geometric_model.context_of_items = 
  SELF\Shape_element.containing_shape\Associated_item_shape.association\Property_definition_representation.used_representation\Geometric_model.context_of_items;
END_ENTITY;

ENTITY Contextual_item_shape
  SUBTYPE OF (Item_shape);
    SELF\Item_shape.described_element : described_element_select;
  DERIVE
    shaped_product : Product_view_definition := spa_get_definition(SELF);
END_ENTITY;

ENTITY Geometric_item_specific_usage;
    name            : STRING;
    description     : OPTIONAL STRING;
    definition      : geometric_item_specific_usage_select;
    identified_item : geometric_model_item;
    used_model      : shape_model;      
END_ENTITY;

ENTITY Chain_based_geometric_item_specific_usage
    SUBTYPE OF (Geometric_item_specific_usage);
    nodes : LIST [2:?] OF UNIQUE Geometric_model;
    undirected_link : LIST [1:?] OF UNIQUE chained_geometric_model_link;
END_ENTITY;

ENTITY Item_shape;
  id                : OPTIONAL STRING;
  description       : OPTIONAL STRING;
  described_element : shapeable_item;
UNIQUE
  UR1: described_element;
END_ENTITY;

ENTITY Assigned_shape_property
  SUBTYPE OF (Assigned_property);
  SELF\Assigned_property.described_element : assigned_shape_property_select;
END_ENTITY; 

ENTITY Shape_dependent_property_representation -- maps to property_def_rep
  SUBTYPE OF (Property_definition_representation);
  SELF\Property_definition_representation.definition : Assigned_shape_property;
END_ENTITY;

ENTITY Shape_description_association -- maps to shape_def_rep
  SUBTYPE OF (Property_definition_representation);
  SELF\Property_definition_representation.definition : Associated_item_shape;
  SELF\Property_definition_representation.used_representation : shape_model;
END_ENTITY;

ENTITY Shape_element_description_association -- maps to shape_def_rep
  SUBTYPE OF (Property_definition_representation);
  SELF\Property_definition_representation.definition : shape_element_or_relationship_select;
  SELF\Property_definition_representation.used_representation : shape_model;
END_ENTITY;

ENTITY Shape_element;
    id               : OPTIONAL STRING;
    element_name     : STRING;
    description      : OPTIONAL STRING;
    containing_shape : Item_shape;
UNIQUE
    UR1: id, containing_shape;    
WHERE
    WR1: EXISTS(element_name) OR (TYPEOF(SELF\Shape_element) <> TYPEOF(SELF));
END_ENTITY;

ENTITY Shape_element_relationship;
    relation_type : OPTIONAL STRING;
    description   : OPTIONAL STRING;
    relating      : Shape_element;
    related       : Shape_element;
  WHERE
    WR1: EXISTS(relation_type) OR (TYPEOF(SELF\Shape_element_relationship) <> TYPEOF(SELF));
END_ENTITY;

SUBTYPE_CONSTRAINT property_definition_representation_subtype FOR Property_definition_representation;
  ONEOF (Shape_description_association, Shape_dependent_property_representation, Shape_element_description_association);
END_SUBTYPE_CONSTRAINT;

FUNCTION spa_get_definition ( input : Contextual_item_shape ): Product_view_definition;
  IF ('PRODUCT_VIEW_DEFINITION_RELATIONSHIP_ARM.VIEW_DEFINITION_USAGE'
    IN TYPEOF(input\Item_shape.described_element))
    THEN
      RETURN(input\Item_shape.described_element\View_definition_relationship.related_view);
  END_IF;
  IF ('ASSEMBLY_STRUCTURE_ARM.PRODUCT_OCCURRENCE_DEFINITION_RELATIONSHIP' IN
      TYPEOF(input\Item_shape.described_element))
    THEN
      RETURN(input\Item_shape.described_element\Product_occurrence_definition_relationship.related_view);
  END_IF;    
  RETURN(?);
END_FUNCTION;

END_SCHEMA;  
(*
   $Id: arm.exp,v 1.42 2009/12/23 13:29:05 liutkuviene Exp $
   ISO TC184/SC4/WG12 N6935 - ISO/TS 10303-1747 Specification document - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5503
*)

SCHEMA Specification_document_arm;

USE FROM Characteristic_arm;	-- ISO/TS 10303-1654
USE FROM Configuration_item_arm;	-- ISO/TS 10303-1056
USE FROM Tagged_text_representation_arm; -- ISO/TS 10303-1366

REFERENCE FROM Support_resource_arm(bag_to_set);

  TYPE sd_documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON documented_element_select WITH (
    Product_configuration,
    Product_view_definition,
    Product_version,
    Product);
  END_TYPE;

  TYPE sd_organization_or_person_in_organization_item = EXTENSIBLE  GENERIC_ENTITY SELECT BASED_ON organization_or_person_in_organization_item WITH  (
    Specification_definition);
  END_TYPE;
  
  ENTITY Design_specification
    SUPERTYPE OF (Interface_specification_document_definition)
    SUBTYPE OF (Specification_definition);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.additional_characterization);
  END_ENTITY;

  ENTITY Fabrication_technology_specification
    SUBTYPE OF (Process_specification);
  END_ENTITY;

  ENTITY Interface_specification_document_definition
    SUBTYPE OF (Design_specification);
  END_ENTITY;

  ENTITY Language_reference_manual
    SUBTYPE OF (Specification_definition);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.additional_characterization);
  END_ENTITY;

  ENTITY Material_specification
    SUBTYPE OF (Specification_definition);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.additional_characterization);
  END_ENTITY;

  ENTITY Partial_document_with_structured_text_representation_assignment
    SUBTYPE OF(Partial_document_assignment);
      structured_portion : string_representation_item_select;
    UNIQUE
      UR1: SELF\Partial_document_assignment.document_portion,
      SELF\Document_assignment.assigned_document;
  END_ENTITY;

  ENTITY Process_specification
    SUBTYPE OF (Specification_definition);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.additional_characterization);
  END_ENTITY;

  ENTITY Specification_allocation
  	SUBTYPE OF (Document_assignment);
      SELF\Document_assignment.assigned_document RENAMED allocated_specification : Specification_definition;
  END_ENTITY;

  ENTITY Specification_definition
  	SUPERTYPE OF(ONEOF (Design_specification,
	 Process_specification,
	 Material_specification,
	 Test_specification,
	 Language_reference_manual))
    SUBTYPE OF (Document_definition);
	DERIVE
  		source: SET[0:?] OF Organization_or_person_in_organization_assignment :=
         bag_to_set(QUERY(temp <* USEDIN(SELF,'PERSON_ORGANIZATION_ASSIGNMENT_ARM.'+
         'ORGANIZATION_OR_PERSON_IN_ORGANIZATION_ASSIGNMENT.ITEMS') |
                         (temp.role = 'document source') ));
	WHERE
      WR1: EXISTS (source) AND (SIZEOF(source) = 1);
  END_ENTITY;

  ENTITY Surface_finish_specification
    SUBTYPE OF (Material_specification);
  END_ENTITY;

  ENTITY Test_specification
    SUBTYPE OF (Specification_definition);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.additional_characterization);
  END_ENTITY;

  FUNCTION get_document_definition(
      input : documented_element_select;
      role : STRING;
      type_name : STRING) : SET OF Document_definition; 
    LOCAL
      dd : SET[0:?] OF Document_definition := [];  --this gives us access to the information base
      da : SET[0:?] OF Document_assignment :=[];
    END_LOCAL;
    da := bag_to_set(QUERY(dr <* USEDIN (input, 'DOCUMENT_ASSIGNMENT_ARM.'+
	  'DOCUMENT_ASSIGNMENT.IS_ASSIGNED_TO') | (dr.role = role)));
    -- iterate over da
    REPEAT i := 1 to SIZEOF(da) by 1;
      IF(type_name IN TYPEOF (da[i].assigned_document))THEN
        dd := dd + da[i].assigned_document;
      END_IF;
    END_REPEAT;
    RETURN(dd);
  END_FUNCTION;
	
END_SCHEMA;
(*
   $Id: arm.exp,v 1.4 2012/10/11 05:49:06 liutkuviene Exp $
   ISO TC184/SC4/WG12 N8059 - ISO/TS 10303-1800 Support resource - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7472
*)
SCHEMA Support_resource_arm;

TYPE identifier = STRING;
END_TYPE;

TYPE label = STRING;
END_TYPE;

TYPE text = STRING;
END_TYPE; 


FUNCTION bag_to_set
   (the_bag : BAG [0:?] OF GENERIC:intype) : SET [0:?] OF GENERIC:intype;

LOCAL the_set : SET OF GENERIC : intype := [];
  i : INTEGER;
END_LOCAL;
  IF SIZEOF(the_bag)> 0 THEN 
  	REPEAT i := 1 TO HIINDEX(the_bag);
      the_set := the_set + the_bag[i];
    END_REPEAT;
  END_IF;
  RETURN(the_set);
END_FUNCTION;


FUNCTION type_check_function
  (the_type : GENERIC; sub_names : SET [0:?] OF STRING; criterion : INTEGER) : LOGICAL;

  IF((NOT EXISTS(the_type)) OR (SIZEOF(sub_names)= 0))
  THEN 
    RETURN (UNKNOWN);
  ELSE 
    CASE criterion OF 
      0: RETURN (SIZEOF(sub_names * TYPEOF(the_type))> 0);
      1: RETURN (SIZEOF(sub_names * TYPEOF(the_type))= 0);
      2: RETURN (SIZEOF(sub_names * TYPEOF(the_type))= 1);
      3: RETURN(SIZEOF(sub_names * TYPEOF(the_type))<= 1); 
      OTHERWISE : RETURN (UNKNOWN);
    END_CASE;
  END_IF;
END_FUNCTION; 

END_SCHEMA;
(*
 $Id: arm.exp,v 1.35 2013/10/10 19:01:09 thomasrthurman Exp $
 ISO TC184/SC4/WG12 N8062 - ISO/TS 10303-1110 Surface conditions - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N7475
*)

SCHEMA Surface_conditions_arm;

USE FROM Dimension_tolerance_arm;

USE FROM Generic_material_aspects_arm;

USE FROM Part_view_definition_arm;

USE FROM Value_with_unit_extension_arm;

TYPE sc_dimension_target = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON dimension_target WITH (
   Coating_layer);
END_TYPE; 

  TYPE measure_qualification_or_value_with_unit = SELECT (Measure_qualification, Value_with_unit); 
  END_TYPE;

  TYPE measuring_gauge_select = EXTENSIBLE GENERIC_ENTITY SELECT (
    Part_view_definition);
  END_TYPE;

  TYPE sf_material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON material_item_select WITH
	(Coating_layer);
  END_TYPE;

  TYPE shaped_element_select = SELECT
    (Shape_element, Item_shape);
  END_TYPE;

  ENTITY Coating_layer
    SUBTYPE OF (Shape_element);
    INVERSE
      thickness : SET[0:1] OF Thickness_size FOR is_applied_to;
    WHERE
      WR1: SIZEOF(USEDIN(SELF, 'GENERIC_MATERIAL_ASPECTS_ARM.MATERIAL_IDENTIFICATION.ITEMS'))=1;
  END_ENTITY;

  ENTITY Contact_ratio
   SUBTYPE OF (Surface_condition);
     ratio_value     : Measure_item;
     measuring_gauge : measuring_gauge_select;
  DERIVE
    SELF\Assigned_property.name : STRING := 'contact ratio';
  END_ENTITY;

  ENTITY Extended_visual_appearance
    SUBTYPE OF (Visual_appearance);
      opacity          : OPTIONAL Measure_item;
      orientation      : OPTIONAL Angle_data_element;
      refraction_index : OPTIONAL Measure_item;  
      texture_map      : Digital_file;  
  END_ENTITY;

  ENTITY Hardness
    SUBTYPE OF (Surface_condition);
      depth                 : OPTIONAL Measure_item;      
      environment_condition : SET[0:?] OF STRING;
      hardness_value        : Measure_item;
      measuring_method      : STRING;      
      measuring_position    : OPTIONAL STRING;
  DERIVE
    SELF\Assigned_property.name : STRING := 'hardness';
  END_ENTITY;

  ENTITY Surface_condition
    ABSTRACT SUPERTYPE OF ( ONEOF(
      Contact_ratio,
      Hardness,
      Tactile_appearance,
      Treatment_result,
      Visual_appearance,
      Surface_texture))
    SUBTYPE OF (Assigned_shape_property);
    value_determination : OPTIONAL STRING;
    SELF\Assigned_property.described_element : shaped_element_select;
  INVERSE
    generic_representation : SET[0:0] OF Property_definition_representation FOR definition; 
  END_ENTITY;

  ENTITY Surface_texture
    SUBTYPE OF (Surface_condition);
      measuring_method    : STRING;
      measuring_direction : OPTIONAL Measurement_path;
      parameters : SET[0:?] OF Surface_texture_parameter;
  DERIVE
    SELF\Assigned_property.name : STRING := 'surface texture';
  END_ENTITY;
  
  ENTITY Surface_texture_parameter;
    parameter_value : measure_qualification_or_value_with_unit;
    parameter_name : STRING;
  END_ENTITY;

  ENTITY Tactile_appearance
    SUBTYPE OF (Surface_condition);
      depth       : OPTIONAL Measure_item;
  DERIVE
    SELF\Assigned_property.name : STRING := 'tactile appearance';
  END_ENTITY;

  ENTITY Treatment_result
    SUBTYPE OF (Surface_condition);
      purpose     : OPTIONAL STRING;
  DERIVE
    SELF\Assigned_property.name : STRING := 'treatment result';
  END_ENTITY;

  ENTITY Visual_appearance
    SUBTYPE OF (Surface_condition);
      colour_id    : STRING;
      colour_name  : OPTIONAL STRING;
      lustre       : STRING;
      transparency : OPTIONAL STRING;
      pattern      : OPTIONAL STRING;
  DERIVE
    SELF\Assigned_property.name : STRING := 'visual appearance';
  END_ENTITY;
 
END_SCHEMA;
(*
   $Id: arm.exp,v 1.23 2008/09/13 12:26:51 liutkuviene Exp $
   ISO TC184/SC4/WG12 N5521 - ISO/TS 10303-1366 Tagged text representation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5009
*)

SCHEMA Tagged_text_representation_arm;

USE FROM Foundation_representation_arm;    --  ISO/TS 10303-1006

TYPE string_representation_item_select = SELECT(
    String_representation_item, 
    Included_text_block,
    Structured_text_composition);
END_TYPE; 

TYPE string_representation_item_list = LIST[1:?] OF
string_representation_item_select;
END_TYPE;

TYPE string_representation_item_set = SET[1:?] OF string_representation_item_select;
END_TYPE;

TYPE string_representation_item_list_or_set =
 SELECT(string_representation_item_list, string_representation_item_set); 
END_TYPE;

SUBTYPE_CONSTRAINT ttr_string_representation_item_subtypes FOR String_representation_item;
  ONEOF (Tagged_text_item,
         Uniform_resource_identifier);
END_SUBTYPE_CONSTRAINT;

ENTITY Included_text_block
  SUBTYPE OF (Representation_item);
  source : Structured_text_representation;
END_ENTITY;

 ENTITY Structured_text_composition
   SUBTYPE OF (Representation_item);
  content: string_representation_item_list_or_set;
 END_ENTITY;

ENTITY Structured_text_representation
  SUBTYPE OF (Representation);
  SELF\Representation.items : SET [1:1] OF string_representation_item_select; 
END_ENTITY;

ENTITY Tagged_text_item
  SUBTYPE OF (String_representation_item);
WHERE
  WR1: SIZEOF (QUERY (using_rep <* USEDIN(SELF,
       'FOUNDATION_REPRESENTATION_ARM.REPRESENTATION.ITEMS') |
  NOT ('TAGGED_TEXT_REPRESENTATION_ARM.TAGGED_TEXT_FORMAT' IN
  TYPEOF (using_rep.context_of_items))
       )) = 0;
END_ENTITY;

ENTITY Tagged_text_format
  SUBTYPE OF (Representation_context);
END_ENTITY;

ENTITY Uniform_resource_identifier
  SUBTYPE OF (String_representation_item);
END_ENTITY;

END_SCHEMA;
(*
   $Id$
   N - ISO/CD-TS - 10303- mechanical_design_features - EXPRESS ARM
*)
(* UNDER DEVELOPMENT *)
SCHEMA Mechanical_design_features_arm;

   USE FROM Characterizable_object_arm
    (Characterizable_object);

   USE FROM Document_assignment_arm
    (Document_assignment,
     documented_element_select);

  USE FROM ELEMENTAL_GEOMETRIC_SHAPE_ARM
   (Axis_placement);

  USE FROM FEATURE_AND_CONNECTION_ZONE_ARM
   (Definitional_shape_element);

  USE FROM MEASURE_REPRESENTATION_ARM
   (Numerical_item_with_unit);

  USE FROM Part_view_definition_arm
   (Part_view_definition_context);

  USE FROM Product_view_definition_arm
   (View_definition_context);
   
  USE FROM SPECIFICATION_DOCUMENT_ARM
   (Specification_definition);

   USE FROM Support_resource_arm
   (identifier,
    text,
    label);

   USE FROM Surface_conditions_arm
    (Coating_layer,
     Surface_texture);

  USE FROM Value_with_unit_extension_arm
    (Length_data_element,
     Angle_data_element);

   USE FROM Value_with_unit_arm
    (count_measure);

  TYPE mdf_documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON documented_element_select WITH
    (Thread_feature_definition);
  END_TYPE;

  TYPE thread_hand = ENUMERATION OF
    (left,
     right);
  END_TYPE;

  TYPE thread_side = ENUMERATION OF
    (internal,
     external);
  END_TYPE;

  TYPE thread_runout_length_quantification = ENUMERATION OF
    (pitch,
    dimension);
  END_TYPE;

  TYPE thread_effective_length_modification = ENUMERATION OF
    (no_length_modification,
     additional_length);
  END_TYPE;

ENTITY Length_numerical_item_with_unit
  SUBTYPE OF (Length_data_element, Numerical_item_with_unit);
--wr??
END_ENTITY;

ENTITY Angle_numerical_item_with_unit
  SUBTYPE OF (Angle_data_element, Numerical_item_with_unit);
--wr??
END_ENTITY;

ENTITY Catalogue_thread_feature_definition
  SUBTYPE OF (Thread_feature_definition);
  documentation : Specification_definition;
  major_diameter : OPTIONAL Length_numerical_item_with_unit;
END_ENTITY;

ENTITY Defined_thread_feature_definition
  SUBTYPE OF (Thread_feature_definition);
  crest : OPTIONAL Length_numerical_item_with_unit;
  minor_diameter : OPTIONAL Length_numerical_item_with_unit;
  pitch_diameter : OPTIONAL Length_numerical_item_with_unit;
  major_diameter : Length_numerical_item_with_unit;
END_ENTITY;

ENTITY Thread_context
  SUBTYPE OF (Part_view_definition_context);
DERIVE
  SELF\View_definition_context.application_domain : STRING := 'thread';
  SELF\View_definition_context.life_cycle_stage : STRING := 'design';
WHERE
  WR1: SIZEOF ( USEDIN(SELF, 'PRODUCT_VIEW_DEFINITION_ARM.PRODUCT_VIEW_DEFINITION.ADDITIONAL_CONTEXTS') ) =0 ; -- there shall be no users in the role PRODUCT_VIEW_DEFINITION.ADDITIONAL_CONTEXT;
END_ENTITY;

ENTITY Thread_feature
  SUBTYPE OF (Definitional_shape_element);
  effective_length : Length_numerical_item_with_unit;
  definition : Thread_feature_definition;
  maximum_length : OPTIONAL Length_numerical_item_with_unit;
  placement : Axis_placement;
END_ENTITY;

ENTITY Thread_feature_definition
  ABSTRACT SUPERTYPE OF (ONEOF (Catalogue_thread_feature_definition, Defined_thread_feature_definition))
  SUBTYPE OF (Characterizable_object);
  coating : OPTIONAL Coating_layer;
  fit_class : text;
  fit_class_2 : OPTIONAL text;
  form : text;
  hand : thread_hand;
  nominal_size : OPTIONAL Length_numerical_item_with_unit;
  number_of_threads : OPTIONAL count_measure;
  qualifier : text;
  root_radius : OPTIONAL Length_numerical_item_with_unit;
  runout : OPTIONAL Thread_runout;
  series : text;
  side : thread_side;
  significant_digits : OPTIONAL INTEGER;
  surface_roughness : OPTIONAL Surface_texture;
  INVERSE
  reference_documents : SET [1:?] OF Document_assignment FOR is_assigned_to;
END_ENTITY;

ENTITY Thread_runout;
  length_of_runout : Length_numerical_item_with_unit;
  length_quantification : thread_runout_length_quantification;
  effective_length_modification : thread_effective_length_modification;
END_ENTITY;

END_SCHEMA;
(*
 $Id: arm.exp,v 1.20 2012/10/11 05:49:06 liutkuviene Exp $
ISO TC184/SC4/WG12 N7843 - ISO/TS 10303-1054 Value with unit - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N7238
*) 


SCHEMA Value_with_unit_arm;


TYPE any_number_value = NUMBER;
END_TYPE; 

TYPE any_string_value = STRING;
END_TYPE; 

TYPE length_measure = REAL;
END_TYPE; 

TYPE measure_value = EXTENSIBLE SELECT
   (any_number_value, 
    any_string_value, 
    length_measure, 
    plane_angle_measure,
    area_measure,
    count_measure,
   ratio_measure,
   volume_measure);
END_TYPE; 

TYPE plane_angle_measure = REAL;
END_TYPE; 

TYPE ratio_measure = REAL;
END_TYPE;

TYPE area_measure = REAL;
END_TYPE;

TYPE volume_measure = REAL;
END_TYPE;

TYPE count_measure = NUMBER;
END_TYPE;

ENTITY Area_unit
  SUBTYPE OF (Derived_unit);
END_ENTITY;

ENTITY Amount_of_substance_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Context_dependent_unit
  SUBTYPE OF (Unit);
WHERE
  WR1: EXISTS(SELF\Unit.name);
END_ENTITY;

ENTITY Conversion_based_unit
  SUBTYPE OF (Unit);
  conversion_factor : Value_with_unit;
WHERE
  WR1: EXISTS(SELF\Unit.name);
END_ENTITY;

ENTITY Derived_unit
 SUPERTYPE OF (ONEOF (Area_unit,
                       Volume_unit))
 SUBTYPE OF (Unit);
  elements : SET[1:?] OF Derived_unit_element;
END_ENTITY;


ENTITY Derived_unit_element;
  base_unit : Unit;
  exponent : REAL;
END_ENTITY;

ENTITY Duration
  SUBTYPE OF (Value_with_unit);
WHERE
  WR1: 'VALUE_WITH_UNIT_ARM.' + 'TIME_UNIT' IN TYPEOF(SELF\Value_with_unit.unit);
END_ENTITY;

ENTITY Electric_current_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Length_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Luminous_intensity_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Mass_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Plane_angle_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Ratio_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Solid_angle_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Thermodynamic_temperature_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Time_unit
  SUBTYPE OF (Unit);
END_ENTITY;

ENTITY Uncertainty_with_unit
  SUBTYPE OF (Value_with_unit);
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

ENTITY Unit
  SUPERTYPE OF (ONEOF (Amount_of_substance_unit,
                       Electric_current_unit,
                       Length_unit,
                       Luminous_intensity_unit,
                       Mass_unit,
                       Plane_angle_unit,
                       Ratio_unit,
                       Solid_angle_unit,
                       Thermodynamic_temperature_unit,
                       Time_unit));
  name : STRING;
  si_unit : BOOLEAN;
END_ENTITY;

ENTITY Value_with_unit;
  unit : Unit;
  value_component : measure_value;
END_ENTITY;

ENTITY Volume_unit
  SUBTYPE OF (Derived_unit);
END_ENTITY;

END_SCHEMA;  -- Value_with_unit_arm
(*
   $Id: arm.exp,v 1.26 2013/02/11 18:46:02 thomasrthurman Exp $
   ISO TC184/SC4/WG12 N8244 - ISO/TS 10303-1753 Value with unit extension - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5533
*)

SCHEMA Value_with_unit_extension_arm;

	USE FROM Value_with_unit_arm;	-- ISO/TS 10303-1054
	
ENTITY Absorbed_dose_data_element
  SUBTYPE OF (Value_with_unit);
END_ENTITY;

  ENTITY Radioactivity_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Acceleration_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Amount_of_substance_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.AMOUNT_OF_SUBSTANCE_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Angle_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.PLANE_ANGLE_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Area_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Capacitance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Celsius_temperature_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Conductance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Dielectric_constant_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Dose_equivalent_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Electric_charge_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Electric_current_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.ELECTRIC_CURRENT_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Electric_potential_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Energy_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Force_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Frequency_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Illuminance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Inductance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Length_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
      WR1 : SELF\Value_with_unit.value_component >= 0.0;
	  WR2 : 'VALUE_WITH_UNIT_ARM.LENGTH_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Loss_tangent_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Luminous_flux_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Luminous_intensity_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.LUMINOUS_INTENSITY_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Magnetic_flux_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Magnetic_flux_density_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Mass_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.MASS_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Power_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Pressure_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Ratio_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.RATIO_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Resistance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Solid_angle_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.SOLID_ANGLE_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Thermal_resistance_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Thermodynamic_temperature_data_element
    SUBTYPE OF (Value_with_unit);
    WHERE
		WR1 : 'VALUE_WITH_UNIT_ARM.THERMODYNAMIC_TEMPERATURE_UNIT' IN TYPEOF(SELF\Value_with_unit.Unit);
  END_ENTITY;

  ENTITY Velocity_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

  ENTITY Volume_data_element
    SUBTYPE OF (Value_with_unit);
  END_ENTITY;

SUBTYPE_CONSTRAINT value_with_unit_subtypes FOR Value_with_unit; 
  ONEOF (Acceleration_data_element,
 Absorbed_dose_data_element,
 Radioactivity_data_element,
 Amount_of_substance_data_element,
 Angle_data_element,
 Area_data_element,
 Capacitance_data_element,
 Celsius_temperature_data_element,
 Conductance_data_element,
 Dielectric_constant_data_element,
 Dose_equivalent_data_element,
 Electric_charge_data_element,
 Electric_current_data_element,
 Electric_potential_data_element,
 Energy_data_element,
 Force_data_element,
 Frequency_data_element,
 Illuminance_data_element,
 Inductance_data_element,
 Length_data_element,
 Loss_tangent_data_element,
 Luminous_flux_data_element,
 Luminous_intensity_data_element,
 Magnetic_flux_data_element,
 Magnetic_flux_density_data_element,
 Mass_data_element,
 Power_data_element,
 Pressure_data_element,
 Ratio_data_element,
 Resistance_data_element,
 Solid_angle_data_element,
 Thermal_resistance_data_element,
 Thermodynamic_temperature_data_element,
 Velocity_data_element,
 Volume_data_element); 
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
