(*
   $Id: mim.exp,v 1.2 2002/12/05 12:00:21 mikeward Exp $
   N1653 - ISO/CD-TS - 10303-1215 physical_breakdown - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Physical_breakdown_mim;

USE FROM Product_breakdown_mim;

	USE FROM Product_breakdown_mim;

	ENTITY physical_breakdown_context
	SUBTYPE OF (breakdown_context);
	END_ENTITY;

	ENTITY physical_element_usage
	SUBTYPE OF (breakdown_element_usage);
	END_ENTITY;

END_SCHEMA;
