(*
   $Id: mim.exp,v 1.20 2017/03/23 13:49:42 kevletu Exp $
   ISO TC184/SC4/WG12 N9416 - ISO/TS 10303-1645 Assembly module with packaged connector component - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N8105
*)
SCHEMA Assembly_module_with_packaged_connector_component_mim;

USE FROM Altered_package_mim;	-- ISO/TS 10303-1601
USE FROM Assembly_module_with_packaged_component_mim;	-- ISO/TS 10303-1829
USE FROM Interface_component_mim;	-- ISO/TS 10303-1691
USE FROM Packaged_connector_model_mim;	-- ISO/TS 10303-1708

ENTITY interface_mounted_join
 SUBTYPE OF (shape_aspect_relationship,shape_aspect);
END_ENTITY;

ENTITY packaged_connector_component
    SUBTYPE OF (interface_component, packaged_component);
END_ENTITY;

END_SCHEMA;

