(*
$Id: arm.exp,v 1.2 2005/06/01 21:11:59 thendrix Exp $
ISO TC184/SC4/WG12 N6561 - ISO/TS 10303-1005 Elemental topology - EXPRESS ARM
Supersedes ISO TC184/SC4/WG12 N674
*)
   
SCHEMA Elemental_topology_arm;

   
USE FROM Foundation_representation_arm;

   
ENTITY Detailed_topological_model_element
  ABSTRACT SUPERTYPE
  SUBTYPE OF (Representation_item);
END_ENTITY;

   
END_SCHEMA;

(* Last update -  15 Aug 2001 *)
