(*
   $Id: mim.exp,v 1.18 2009/06/21 12:13:05 abhpf Exp $
   ISO TC184/SC4/WG3 N2497 - ISO/TS 10303-1433 Project management - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N2312
*)

SCHEMA Project_management_mim;
USE FROM Organization_structure_mim;
USE FROM Project_breakdown_mim;
USE FROM Work_structure_mim;
USE FROM date_time_schema   
(local_time); 
USE FROM state_type_schema
(state_type_role);



TYPE prjm_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(action_directive,
	action_method,
	action_resource_requirement,
	applied_event_occurrence_assignment,
	approval,
	ascribable_state,
	certification,
	configuration_item,
	contract_relationship,
	document_file,
	effectivity,
	event_occurrence,
	organization,
	organizational_project,
	person,
	person_and_organization,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_group_membership,
	versioned_action_request);
END_TYPE;

TYPE prjm_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action,
	action_actual,
	action_directive,
	action_method,
	action_method_assignment,
	action_method_relationship,
	action_property,
	action_relationship,
	action_request_solution,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_action_request_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_event_occurrence_assignment,
	applied_organizational_project_assignment,
	applied_position_in_organization_group_assignment,
	applied_security_classification_assignment,
	ascribable_state,
	certification,
	condition,
	configuration_item,
	contract,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	directed_action,
	event_occurrence,
	observation,
	observation_consequence,
	organization,
	organizational_project,
	person_and_organization,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_group_membership,
	representation,
	representation_item,
	resource_property,
	security_classification,
	state_observed,
	state_observed_relationship,
	state_observed_role,
	state_type,
	state_type_relationship,
	task_objective,
	task_step);
END_TYPE;

TYPE prjm_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(applied_approval_assignment,
	applied_certification_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_event_occurrence_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	configuration_item,
	contract_relationship,
	executed_action,
	information_usage_right,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	product_definition_relationship,
	state_observed,
	state_type,
	versioned_action_request);
END_TYPE;

TYPE prjm_aliasable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON aliasable_item WITH
	(address,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_security_classification_assignment,
	approval,
	approval_status,
	certification,
	configuration_item,
	event_occurrence,
	external_class_library,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization,
	organizational_project,
	person,
	person_and_organization,
	product,
	product_as_individual,
	product_as_individual_view,
	product_as_planned,
	product_as_realized,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	security_classification);
END_TYPE;

TYPE prjm_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(action_actual,
	action_method,
	action_method_assignment,
	applied_action_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_location_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	applied_security_classification_assignment,
	ascribable_state,
	assumption,
	assumption_assignment,
	assumption_relationship,
	configuration_item,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	executed_action,
	identification_assignment_relationship,
	item_assumed,
	organization_relationship,
	organizational_project,
	person_and_organization,
	person_and_organization_address, organizational_address,
	position_in_organization,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	security_classification,
	state_observed_relationship,
	state_type,
	state_type_relationship);
END_TYPE;

TYPE prjm_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(information_right,
	information_usage_right,
	product_concept,
	product_concept_context,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship,
	usage_association);
END_TYPE;

TYPE prjm_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(action_method,
	action_relationship,
	applied_action_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_external_identification_assignment,
	configuration_item,
	contract_relationship,
	document_relationship,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	information_right,
	information_usage_right,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	representation_item,
	state_observed,
	state_observed_relationship,
	state_type,
	state_type_relationship);
END_TYPE;

TYPE prjm_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(action_method,
	approval_person_organization,
	configuration_item,
	executed_action,
	product,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	property_definition,
	state_type);
END_TYPE;

TYPE prjm_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(action_property,
	action_status,
	address,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_document_reference,
	applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	applied_security_classification_assignment,
	applied_usage_right,
	approval,
	approval_person_organization,
	approval_relationship,
	approval_status,
	assumption,
	assumption_assignment,
	assumption_relationship,
	attribute_language_assignment,
	calendar_date,
	certification,
	class,
	configuration_design,
	configuration_item,
	context_dependent_unit,
	contract,
	contract_relationship,
	date_and_time,
	date_assignment, date_and_time_assignment,
	descriptive_representation_item,
	document_file,
	document_relationship,
	effectivity,
	effectivity_relationship,
	event_occurrence,
	event_occurrence_relationship,
	identification_assignment_relationship,
	information_right,
	information_usage_right,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	language,
	local_time,
	multi_language_attribute_assignment,
	organization,
	organization_relationship,
	organizational_project,
	organizational_project_relationship,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_concept,
	product_concept_context,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_group_membership,
	product_relationship,
	representation,
	representation_context,
	representation_item,
	representation_relationship,
	resource_property,
	resource_property_representation,
	security_classification,
	state_observed_role,
	time_interval_relationship,
	usage_association);
END_TYPE;

TYPE prjm_collection_assignment_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON collection_assignment_groupable_item WITH
	(action_directive,
	configuration_item,
	contract,
	organization,
	organizational_project,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	versioned_action_request);
END_TYPE;

TYPE prjm_collection_membership_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON collection_membership_groupable_item WITH
	(action,
	action_directive,
	action_method,
	action_method_assignment,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_relationship,
	action_request_solution,
	action_request_status,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	action_status,
	address,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_action_request_assignment,
	applied_approval_assignment,
	applied_attribute_classification_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_experience_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	applied_location_assignment,
	applied_location_representation_assignment,
	applied_name_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organization_type_assignment,
	applied_organizational_project_assignment,
	applied_person_type_assignment,
	applied_person_type_definition_assignment,
	applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	applied_qualification_type_assignment,
	applied_security_classification_assignment,
	applied_usage_right,
	approval,
	approval_person_organization,
	approval_relationship,
	approval_status,
	ascribable_state,
	ascribable_state_relationship,
	assumption,
	assumption_assignment,
	assumption_relationship,
	attribute_language_assignment,
	breakdown_context,
	breakdown_of,
	calendar_date,
	certification,
	class,
	collection_assignment,
	collection_membership,
	condition,
	configuration_design,
	configuration_item,
	configuration_item_relationship,
	contract,
	contract_relationship,
	coordinated_universal_time_offset,
	date_and_time,
	date_assignment, date_and_time_assignment,
	derived_unit_element,
	document_file,
	document_relationship,
	effectivity,
	effectivity_relationship,
	event_occurrence,
	event_occurrence_relationship,
	experience,
	experience_type,
	experience_type_relationship,
	external_source,
	general_property,
	general_property_relationship,
	group,
	identification_assignment_relationship,
	information_right,
	information_usage_right,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	language,
	local_time,
	location,
	location_relationship,
	measure_representation_item,
	measure_with_unit,
	multi_language_attribute_assignment,
	named_unit, derived_unit,
	observation,
	observation_consequence,
	observation_relationship,
	organization,
	organization_relationship,
	organization_type,
	organizational_project,
	organizational_project_relationship,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	person_type,
	person_type_definition,
	person_type_definition_relationship,
	position_in_organization,
	position_in_organization_assignment,
	position_in_organization_relationship,
	position_in_organization_type,
	position_in_organization_type_assignment,
	product,
	product_concept,
	product_concept_context,
	product_definition,
	product_definition_context,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_group_assignment, breakdown_element_group_assignment, product_definition_usage,
	product_definition_relationship,
	product_design_to_individual,
	product_design_version_to_individual,
	product_design_view_to_individual,
	product_group,
	product_group_membership,
	product_group_relationship,
	product_planned_to_realized,
	product_relationship,
	property_definition,
	property_definition_representation,
	qualification_type,
	qualification_type_relationship,
	representation,
	representation_context,
	representation_item,
	representation_relationship,
	resource_property,
	resource_property_representation,
	same_as_external_item_assignment,
	security_classification,
	selected_item_assignment,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_observed_role,
	state_type,
	state_type_assignment,
	state_type_relationship,
	state_type_role,
	task_objective,
	time_interval,
	time_interval_relationship,
	usage_association,
	versioned_action_request);
END_TYPE;

TYPE prjm_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(action_method,
	action_method_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_location_assignment,
	applied_organizational_project_assignment,
	applied_qualification_type_assignment,
	applied_security_classification_assignment,
	configuration_item,
	date_assignment, date_and_time_assignment,
	general_property,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	organization,
	organization_type,
	product_concept,
	product_definition_relationship,
	state_type_relationship,
	task_element_relationship,
	versioned_action_request);
END_TYPE;

TYPE prjm_condition_evaluation_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_evaluation_action_items WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	ascribable_state,
	executed_action,
	group,
	product,
	product_concept,
	product_definition_relationship,
	product_group,
	product_group_membership,
	product_group_relationship,
	resource_property,
	resource_property_representation,
	state_type);
END_TYPE;

TYPE prjm_contract_item = EXTENSIBLE SELECT BASED_ON contract_item WITH
	(action_method,
	applied_action_assignment,
	configuration_item,
	executed_action,
	externally_defined_class,
	organization,
	organizational_project,
	person_and_organization,
	product,
	product_definition_formation,
	product_definition_formation_relationship,
	security_classification);
END_TYPE;

TYPE prjm_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(action_method,
	action_relationship,
	applied_action_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_organizational_project_assignment,
	applied_position_in_organization_assignment,
	applied_usage_right,
	approval,
	approval_person_organization,
	ascribable_state,
	assumption,
	assumption_assignment,
	assumption_relationship,
	configuration_item,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	document_file,
	effectivity,
	executed_action,
	identification_assignment_relationship,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization_relationship,
	organizational_project,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	security_classification,
	selected_item_assignment,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship);
END_TYPE;

TYPE prjm_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(action_method,
	action_relationship,
	applied_action_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_organizational_project_assignment,
	applied_position_in_organization_assignment,
	applied_usage_right,
	approval,
	approval_person_organization,
	ascribable_state,
	assumption,
	assumption_assignment,
	assumption_relationship,
	configuration_item,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	document_file,
	effectivity,
	executed_action,
	identification_assignment_relationship,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization_relationship,
	organizational_project,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	security_classification,
	selected_item_assignment,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship);
END_TYPE;

TYPE prjm_experience_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_item WITH
	(action_method,
	applied_event_occurrence_assignment,
	observation_consequence,
	organizational_project,
	product);
END_TYPE;

TYPE prjm_experience_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_type_item WITH
	(action_method_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_position_in_organization_assignment,
	event_occurrence,
	group,
	observation_consequence,
	person_type,
	person_type_definition_relationship,
	product,
	product_group);
END_TYPE;

TYPE prjm_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(action_method,
	action_relationship,
	address,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_location_representation_assignment, 
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	applied_qualification_type_assignment,
	applied_security_classification_assignment,
	applied_usage_right,
	approval,
	assumption,
	assumption_assignment,
	assumption_relationship,
	certification,
	class,
	condition,
	configuration_item,
	contract,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	document_file,
	effectivity,
	executed_action,
	general_property,
	general_property_relationship,
	information_right,
	information_usage_right,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization,
	organization_relationship,
	organizational_project,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_concept,
	product_concept_context,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	representation_item,
	security_classification,
	state_type_relationship,
	usage_association);
END_TYPE;

TYPE prjm_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(action_method,
	action_method_relationship,
	action_property_representation,
	action_request_solution,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	applied_qualification_type_assignment,
	applied_security_classification_assignment,
	applied_usage_right,
	assumption,
	assumption_assignment,
	assumption_relationship,
	configuration_item,
	date_assignment, date_and_time_assignment,
	document_file,
	event_occurrence,
	executed_action,
	identification_assignment_relationship,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	multi_language_attribute_assignment,
	organization_relationship,
	person_and_organization,
	person_and_organization_address, organizational_address,
	person_type_definition_relationship,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_definition_usage,
	product_relationship,
	property_definition,
	resource_property_representation,
	state_observed_assignment);
END_TYPE;

TYPE prjm_event_occurrence_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON event_occurrence_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_relationship,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_contract_assignment,
	applied_organizational_project_assignment,
	approval,
	certification,
	condition,
	contract,
	contract_relationship,
	executed_action,
	general_property,
	general_property_relationship,
	observation,
	organizational_project,
	product,
	product_concept_context,
	product_definition,
	product_definition_formation,
	product_definition_relationship,
	representation,
	representation_item,
	resource_property,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_relationship,
	task_objective,
	versioned_action_request);
END_TYPE;

TYPE prjm_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH
	(action_method,
	action_resource_requirement,
	organization,
	organizational_project,
	person_and_organization,
	product);
END_TYPE;

TYPE prjm_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH
	(action_method,
	task_element);
END_TYPE;

TYPE prjm_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(action_relationship,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	ascribable_state,
	ascribable_state_relationship,
	assumption,
	assumption_relationship,
	class,
	condition,
	configuration_item,
	contract_relationship,
	document_file,
	effectivity,
	executed_action,
	experience,
	identification_assignment_relationship,
	information_right,
	information_usage_right,
	person_type_definition,
	position_in_organization,
	product,
	product_concept,
	product_concept_context,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_definition_usage,
	product_relationship,
	property_definition,
	representation_item,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type_assignment,
	state_type_relationship,
	task_step,
	usage_association);
END_TYPE;

TYPE prjm_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(action_directive,
	action_method,
	action_property,
	action_resource,
	action_resource_requirement,
	applied_action_method_assignment,
	applied_certification_assignment,
	applied_external_identification_assignment,
	applied_security_classification_assignment,
	applied_usage_right,
	certification,
	configuration_item,
	contract,
	contract_relationship,
	document_file,
	document_relationship,
	information_right,
	information_usage_right,
	organization,
	organizational_project,
	person_and_organization,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	property_definition,
	representation_item,
	security_classification,
	usage_association);
END_TYPE;

TYPE prjm_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(action_method,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_classification_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_organizational_project_assignment,
	applied_usage_right,
	approval,
	breakdown_of,
	certification,
	condition,
	contract,
	contract_relationship,
	effectivity,
	executed_action,
	general_property,
	general_property_relationship,
	information_usage_right,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	property_definition,
	qualification_type,
	security_classification,
	state_observed_assignment,
	state_type_assignment);
END_TYPE;

TYPE prjm_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(action_directive,
	action_method,
	applied_action_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	approval,
	certification,
	contract,
	contract_relationship,
	effectivity,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	organizational_project,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	property_definition,
	state_type_relationship);
END_TYPE;

TYPE prjm_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(event_occurrence,
	product,
	product_definition,
	product_definition_formation, 
	product_definition_relationship);
END_TYPE;

TYPE prjm_location_representation_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_representation_item WITH
	(action,
	action_method,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	attribute_language_assignment,
	breakdown_of,
	event_occurrence,
	executed_action,
	observation,
	organization,
	organization_type,
	organizational_project,
	person_and_organization,
	product,
	product_concept,
	product_concept_context,
	product_definition_relationship,
	representation,
	resource_property,
	state_observed,
	state_observed_relationship,
	state_type,
	versioned_action_request);
END_TYPE;

TYPE prjm_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(action_method,
	action_relationship,
	applied_action_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_external_identification_assignment,
	configuration_item,
	contract_relationship,
	document_relationship,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	information_right,
	information_usage_right,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	representation_item,
	state_observed,
	state_observed_relationship,
	state_type,
	state_type_relationship);
END_TYPE;

TYPE prjm_name_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON name_item WITH
	(product_definition_group_assignment, breakdown_element_group_assignment, breakdown_element_realization, product_definition_usage,
	event_occurrence,
	observation,
	product,
	product_definition);
END_TYPE;

TYPE prjm_observed_context_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON observed_context_item WITH
	(action,
	action_method,
	action_property,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_organizational_project_assignment,
	applied_security_classification_assignment,
	approval,
	ascribable_state,
	configuration_item,
	executed_action,
	group,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	observation_consequence,
	organizational_project,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_design_to_individual,
	product_group,
	product_planned_to_realized,
	property_definition,
	property_definition_representation,
	representation,
	representation_item,
	resource_property,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_observed_role,
	state_type,
	state_type_assignment,
	state_type_relationship,
	task_element,
	task_method,
	task_objective);
END_TYPE;

TYPE prjm_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(action_method,
	action_relationship,
	address,
	applied_action_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	approval,
	approval_status,
	ascribable_state,
	assumption,
	assumption_assignment,
	assumption_relationship,
	certification,
	class,
	configuration_item,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	document_file,
	effectivity,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	identification_assignment_relationship,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization,
	organizational_project,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_as_individual_version,
	product_as_individual_view,
	product_definition,
	product_definition_context,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	resource_property,
	security_classification,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship,
	task_method);
END_TYPE;

TYPE prjm_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(action_method,
	action_relationship,
	address,
	applied_action_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_identification_assignment,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organizational_project_assignment,
	approval,
	approval_status,
	ascribable_state,
	assumption,
	assumption_assignment,
	assumption_relationship,
	certification,
	class,
	configuration_item,
	contract_relationship,
	date_assignment, date_and_time_assignment,
	document_file,
	effectivity,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	identification_assignment_relationship,
	item_assumed,
	justification_group_assignment, justification_item_group_assignment, justification_assignment,
	justification_support_item_group_assignment, justification_support_assignment,
	organization,
	organizational_project,
	person,
	person_and_organization,
	person_and_organization_address, organizational_address,
	product,
	product_as_individual_version,
	product_as_individual_view,
	product_definition,
	product_definition_context,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	resource_property,
	security_classification,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship,
	task_method);
END_TYPE;

TYPE prjm_person_definition_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_definition_item WITH
	(action_method_assignment,
	applied_person_type_assignment,
	applied_position_in_organization_group_assignment,
	group,
	organization,
	person_and_organization,
	position_in_organization_assignment,
	position_in_organization_type_assignment);
END_TYPE;

TYPE prjm_person_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_type_item WITH
	(action_directive,
	action_method,
	action_method_assignment,
	action_request_solution,
	applied_document_reference, applied_document_usage_constraint_assignment,
	applied_experience_assignment,
	applied_organizational_project_assignment,
	executed_action,
	experience,
	experience_type,
	observation_consequence,
	organizational_project,
	product,
	product_definition_formation,
	product_definition_relationship,
	versioned_action_request);
END_TYPE;

TYPE prjm_position_in_organization_group_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_group_item WITH
	(action,
	action_directive,
	action_method,
	action_method_assignment,
	action_resource_requirement,
	configuration_item,
	event_occurrence,
	executed_action,
	location,
	organizational_project,
	product_concept,
	product_group,
	state_observed,
	versioned_action_request);
END_TYPE;

TYPE prjm_position_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_item WITH
	(action,
	action_directive,
	action_method,
	action_method_assignment,
	action_resource_requirement,
	configuration_item,
	event_occurrence,
	executed_action,
	location,
	organizational_project,
	product_concept,
	product_group,
	state_observed,
	versioned_action_request);
END_TYPE;

TYPE prjm_position_in_organization_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_type_item WITH
	(action,
	action_directive,
	action_method,
	action_method_assignment,
	action_resource_requirement,
	configuration_item,
	event_occurrence,
	executed_action,
	location,
	organizational_project,
	product_concept,
	product_group,
	state_observed,
	versioned_action_request);
END_TYPE;

TYPE prjm_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(configuration_item,
	executed_action,
	organization,
	person_and_organization,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_relationship,
	representation);
END_TYPE;

TYPE prjm_same_as_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON same_as_item WITH
	(action,
	action_method_relationship,
	action_property,
	action_request_status,
	action_resource,
	action_resource_requirement,
	action_status,
	address,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_experience_assignment,
	applied_external_identification_assignment,
	applied_location_representation_assignment,
	applied_position_in_organization_group_assignment,
	approval,
	approval_status,
	ascribable_state,
	assumption,
	attribute_language_assignment,
	breakdown_context,
	calendar_date,
	certification,
	condition,
	contract,
	coordinated_universal_time_offset,
	date_and_time,
	derived_unit_element,
	event_occurrence,
	experience,
	experience_type,
	external_source,
	general_property,
	group,
	information_right,
	information_usage_right,
	item_assumed,
	language,
	local_time,
	location,
	measure_representation_item,
	measure_with_unit,
	named_unit, derived_unit,
	observation,
	observation_consequence,
	organization,
	organization_type,
	person,
	person_type,
	person_type_definition,
	position_in_organization,
	position_in_organization_assignment,
	position_in_organization_type,
	position_in_organization_type_assignment,
	product,
	product_concept,
	product_concept_context,
	product_definition,
	product_definition_context,
	product_definition_formation,
	qualification_type,
	representation, 
	representation_context,
	resource_property,
	security_classification,
	state_observed,
	state_observed_role,
	state_type,
	state_type_role,
	task_objective,
	time_interval);
END_TYPE;

TYPE prjm_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(action_method,
	action_property,
	action_resource,
	applied_action_assignment,
	applied_document_reference, applied_document_usage_constraint_assignment,
	configuration_item,
	document_file,
	event_occurrence,
	executed_action,
	product,
	product_as_individual_version,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_relationship,
	property_definition);
END_TYPE;

TYPE prjm_selected_item_context_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_context_items WITH
	(configuration_item,
	product_concept);
END_TYPE;

TYPE prjm_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(applied_action_method_assignment,
	applied_external_identification_assignment,
	approval,
	ascribable_state,
	configuration_item,
	document_file,
	event_occurrence,
	information_usage_right,
	observation,
	observation_consequence,
	organizational_project,
	person_type,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_relationship,
	state_observed,
	state_observed_relationship,
	state_observed_role,
	state_type,
	state_type_assignment,
	state_type_relationship);
END_TYPE;

TYPE prjm_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(applied_external_identification_assignment,
	approval,
	configuration_item,
	document_file,
	event_occurrence,
	observation_consequence,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_group_assignment, breakdown_element_group_assignment, breakdown_element_realization, 
	product_definition_relationship,
	product_definition_usage,
	state_observed);
END_TYPE;

TYPE prjm_time_interval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON time_interval_item WITH
	(executed_action);
END_TYPE;

(*TYPE prjm_characterized_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_definition WITH
	(action,
	action_directive,
	action_method,
	action_method_relationship,
	action_property,
	action_relationship,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	ascribable_state,
	configuration_item,
	document_file,
	event_occurrence,
	executed_action,
	general_property,
	general_property_relationship,
	group,
	information_usage_right,
	observation,
	observation_consequence,
	product,
	product_concept,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_relationship,
	product_group,
	property_definition,
	property_definition_representation,
	representation,
	representation_context,
	representation_item,
	resource_property,
	security_classification,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship,
	task_objective,
	versioned_action_request);
END_TYPE;*)

ENTITY prjm_characterizable_action
SUBTYPE OF (action, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_directive
SUBTYPE OF (action_directive, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_method
SUBTYPE OF (action_method, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_method_relationship
SUBTYPE OF (action_method_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_property
SUBTYPE OF (action_property, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_relationship
SUBTYPE OF (action_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_resource
SUBTYPE OF (action_resource, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_action_resource_requirement
SUBTYPE OF (action_resource_requirement, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_applied_action_assignment
SUBTYPE OF (applied_action_assignment, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_applied_action_method_assignment
SUBTYPE OF (applied_action_method_assignment, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_ascribable_state
SUBTYPE OF (ascribable_state, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_configuration_item
SUBTYPE OF (configuration_item, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_document_file
SUBTYPE OF (document_file, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_event_occurrence
SUBTYPE OF (event_occurrence, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_executed_action
SUBTYPE OF (executed_action, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_general_property
SUBTYPE OF (general_property, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_general_property_relationship
SUBTYPE OF (general_property_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_group
SUBTYPE OF (group, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_information_usage_right
SUBTYPE OF (information_usage_right, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_observation
SUBTYPE OF (observation, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_observation_consequence
SUBTYPE OF (observation_consequence, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product
SUBTYPE OF (product, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_concept
SUBTYPE OF (product_concept, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_definition
SUBTYPE OF (product_definition, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_definition_formation
SUBTYPE OF (product_definition_formation, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_definition_formation_relationship
SUBTYPE OF (product_definition_formation_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_definition_relationship
SUBTYPE OF (product_definition_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_product_group
SUBTYPE OF (product_group, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_property_definition
SUBTYPE OF (property_definition, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_property_definition_representation
SUBTYPE OF (property_definition_representation, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_representation
SUBTYPE OF (representation, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_representation_context
SUBTYPE OF (representation_context, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_representation_item
SUBTYPE OF (representation_item, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_resource_property
SUBTYPE OF (resource_property, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_security_classification
SUBTYPE OF (security_classification, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_observed
SUBTYPE OF (state_observed, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_observed_assignment
SUBTYPE OF (state_observed_assignment, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_observed_relationship
SUBTYPE OF (state_observed_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_type
SUBTYPE OF (state_type, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_type_assignment
SUBTYPE OF (state_type_assignment, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_state_type_relationship
SUBTYPE OF (state_type_relationship, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_task_objective
SUBTYPE OF (task_objective, characterized_object);
END_ENTITY;

ENTITY prjm_characterizable_versioned_action_request
SUBTYPE OF (versioned_action_request, characterized_object);
END_ENTITY;

END_SCHEMA;

