(*
 $Id: checkModuleMain.js,v 1.16 2005/03/09 01:07:43 thendrix Exp $
 ISO TC184/SC4/WG12 N - ISO/WD 10303-1433 Project management - EXPRESS MIM
*)
(* UNDER DEVELOPMENT *)
SCHEMA Project_management_mim;
  USE FROM Organization_structure_mim;
  USE FROM Project_breakdown_mim;
  USE FROM Schedule_mim;
  USE FROM Work_structure_mim;
  USE FROM Project_management_resource_information_mim;
  USE FROM Management_resource_information_mim;
  USE FROM Project_management_project_management_resource_information_connector_mim;
  USE FROM Project_management_organization_structure_connector_mim;
  USE FROM Project_management_project_breakdown_connector_mim;
  USE FROM Project_management_schedule_connector_mim;
  USE FROM Project_management_work_structure_connector_mim;
END_SCHEMA;
