(*
   $Id: mim.exp,v 1.1 2004/10/21 20:36:12 abhpf Exp $
   N - ISO/CD-TS - 10303- project_management - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Project_management_mim;
  USE FROM Organization_structure_mim;
  USE FROM Project_breakdown_mim;
  USE FROM Schedule_mim;
  USE FROM Work_structure_mim;
  USE FROM Project_management_resource_information_mim;
  USE FROM Management_resource_information_mim;
  USE FROM Project_management_project_management_resource_information_connector_mim;
  USE FROM Project_management_organization_structure_connector_mim;
  USE FROM Project_management_project_breakdown_connector_mim;
  USE FROM Project_management_schedule_connector_mim;
  USE FROM Project_management_work_structure_connector_mim;
END_SCHEMA;
