(*
 $Id: mim.exp,v 1.11 2006/03/24 19:08:22 thendrix Exp $
 ISO TC184/SC4/WG12 N4285 - ISO/TS 10303-1141 Requirement view definition - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N3134
*) 


SCHEMA Requirement_view_definition_mim;

USE FROM Product_view_definition_mim;    -- ISO/TS 10303-1019

USE FROM Requirement_identification_and_version_mim;    -- ISO/TS 10303-1140


END_SCHEMA;  -- Requirement_view_definition_mim
