(*
   $Id: arm.exp,v 1.5 2005/01/17 23:42:18 thomasrthurman Exp $
   ISO TC184/SC4/WG12 N1653 - ISO/CD-TS 10303-1618 Ap210 interconnect design for microwave - EXPRESS ARM
*)

SCHEMA Ap210_interconnect_design_for_microwave_arm;
	USE FROM Ap210_interconnect_design_arm;	-- ISO/TS 10303-1617
(**   (+ spline curves ...)
   + edge terminal, cross-section_terminals !!
   GL: is it guided_wave_terminal or something else?
*)   
END_SCHEMA;

