{ iso standard 10303 part (11) version (4) }
(*  $Id: $ *) 

SCHEMA Property_assignment_arm;

USE FROM Independent_property_arm;

TYPE property_assignment_select = EXTENSIBLE SELECT ;
END_TYPE;

ENTITY Applied_independent_element_property
SUBTYPE OF (Element_property);
  base_element_property : Independent_property;
END_ENTITY;

ENTITY Element_property;
  described_element : property_assignment_select;
  description : OPTIONAL STRING;
  name : OPTIONAL STRING;
END_ENTITY;

END_SCHEMA;

