(*
   $Id: mim.exp,v 1.1 2009/03/17 18:05:16 dmprice Exp $
   N - ISO/CD-TS - 10303- same_as_external_item - EXPRESS MIM*)

SCHEMA Same_as_external_item_mim;

USE FROM External_source_mim;    -- ISO/TS 10303-1331

USE FROM management_resources_schema   -- ISO 10303-41
  (external_identification_assignment); 


ENTITY same_as_external_item_assignment
  SUBTYPE OF (external_identification_assignment);
END_ENTITY;

END_SCHEMA;  -- Same_as_external_item_mim


