(*
$Id: arm.exp,v 1.7 2003/02/07 11:14:18 robbod Exp $
ISO TC184/SC4/WG12 N1475 - ISO/CD-TS 10303-1270 Message - EXPRESS ARM
*) 

SCHEMA Message_arm; 

USE FROM Approval_arm;    -- ISO/TS 10303-1012

USE FROM Date_time_assignment_arm;    -- ISO/TS 10303-1014

USE FROM Person_organization_arm;    -- ISO/TS 10303-1011

USE FROM Security_classification_arm;    -- ISO/TS 10303-1015

USE FROM State_observed_arm;    -- ISO/CD-TS 10303-1256


TYPE message_approval_select = SELECT BASED_ON approval_item WITH 
   (Message);
END_TYPE; 

TYPE message_date_time_select = SELECT BASED_ON date_or_date_time_item WITH 
   (Message);
END_TYPE; 

TYPE message_definer_select = EXTENSIBLE SELECT
   (Organization, 
    Person_in_organization);
END_TYPE; 

TYPE message_security_classification_select = SELECT BASED_ON security_classification_item WITH 
   (Message);
END_TYPE; 

TYPE message_state_select = SELECT BASED_ON state_of_item WITH 
   (Message);
END_TYPE; 

ENTITY Content_item;
  item_identifier : STRING;
  item_type : STRING;
  access_comment : OPTIONAL STRING;
END_ENTITY;

ENTITY Message;
  contains : SET[0:?] OF Content_item;
  defined_by : OPTIONAL SET[0:?] OF message_definer_select;
  id : STRING;
  message_type : STRING;
  purpose : OPTIONAL STRING;
END_ENTITY;

ENTITY Message_association;
  related : Message;
  relating : Message;
  role : STRING;
END_ENTITY;

END_SCHEMA;  -- Message_arm
