(*
ISO TC184/SC4/WG12 Nnew number - ISO/TS 10303-1121 Document and version identification - EXPRESS MIM
Supersedes ISO TC184/SC4/WG12 N1187
*) 


SCHEMA Document_and_version_identification_mim;

USE FROM product_definition_schema   -- ISO 10303-41
  (product_category,
   product_related_product_category); 

USE FROM Product_identification_mim;    -- ISO/WD 10303-1017

USE FROM Product_version_mim;    -- ISO/TS 10303-1018


END_SCHEMA;  -- Document_and_version_identification_mim

