(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Layered interconnect module design - EXPRESS MIM
*)


SCHEMA Layered_interconnect_module_design_mim;
	USE FROM Basic_curve_mim;
	USE FROM Component_feature_mim;
	USE FROM Component_grouping_mim;
	USE FROM Extended_geometric_tolerance_mim;
	USE FROM Form_features_mim;
	USE FROM Functional_design_elaboration_mim;
	USE FROM Interconnect_module_usage_view_mim;
	USE FROM Interconnect_physical_requirement_allocation_mim;
	USE FROM Layered_shape_mim;
	USE FROM Manufacturing_technology_mim;
	USE FROM Part_template_2d_shape_mim;
	USE FROM Part_template_extension_mim;
	USE FROM Physical_unit_design_view_mim;
	USE FROM Printed_physical_layout_template_mim;
	USE FROM Requirement_assignment_mim;
END_SCHEMA;

