<?xml version="1.0" encoding="utf-8"?>
<!--
$ Id: build_script.xsl,v 1.9 2003/02/26 02:12:17 thendrix Exp $
   Author:  Rob Bodington, Eurostep Limited
   Owner:   Developed by Eurostep Limited http://www.eurostep.com
   Purpose: To build the initial ANT build package. 
-->

<xsl:stylesheet 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0">
  
  <xsl:import href="../../xsl/common.xsl"/>

  <xsl:output 
    method="xml"
    indent="yes"
    />
        
  <xsl:template match="ballot_index">
    <xsl:text>
    </xsl:text>
    <xsl:comment>
      This file has been auto generated by:
      ant -buildfile buildscript.xml
      
      Usage:
      ant -buildfile script.xml checks
         Generates the HTML for the modules listed in ballot_index.xml
      Errors are reported an stored in 
      <xsl:value-of select="concat('stepmod/',@name,'_ant_check_[yyyymmdd].txt')"/>

    </xsl:comment>

    <project name="ballotchecks" default="all" basedir="../../..">
      <xsl:text>
      </xsl:text>
        <xsl:element name="property">
          <xsl:attribute name="name">MODULESDIR</xsl:attribute>
          <xsl:attribute name="value">
              <xsl:value-of select="'data/modules/'"/>
          </xsl:attribute>
        </xsl:element>

        <xsl:element name="property">
          <xsl:attribute name="name">UTILSDIR</xsl:attribute>
          <xsl:attribute name="value">
              <xsl:value-of select="'utils/'"/>
          </xsl:attribute>
        </xsl:element>

        <xsl:variable name="outfile" select="concat(@name,'_ant_check_${DSTAMP}.txt')"/>
        <target name="checks">
          <tstamp/>
          <echo>
            Outputting to: <xsl:value-of select="concat('stepmod/',$outfile)"/>
          </echo>
          <xsl:apply-templates select="ballot_package/module">
            <xsl:with-param name="outfile" select="$outfile" />
            </xsl:apply-templates>
      </target>


    <xsl:text>
    </xsl:text>

    <xsl:text>
    </xsl:text>

  </project>

  </xsl:template>

  <xsl:template match="module">
    <xsl:param name="outfile"/>

    <xsl:element name="exec">
        <xsl:attribute name="executable">
          <xsl:value-of select="'bash'"/>
        </xsl:attribute>
        <xsl:attribute name="failifexecutionfails">
          <xsl:value-of select="'false'"/>
        </xsl:attribute>
        <xsl:attribute name="output">
          <xsl:value-of select="$outfile"/>
        </xsl:attribute>
        <xsl:attribute name="append">
          <xsl:value-of select="'true'"/>
        </xsl:attribute>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'ant'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-emacs'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-q'"/>
          </xsl:attribute>
        </xsl:element>
        <!--        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-v'"/>
          </xsl:attribute>
        </xsl:element> -->
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-buildfile'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('${UTILSDIR}','build.xml')"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('-DMODULES=','${MODULESDIR}',@name)"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'clean_module'"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:element>

      <xsl:element name="exec">
        <xsl:attribute name="executable">
          <xsl:value-of select="'bash'"/>
        </xsl:attribute>
        <xsl:attribute name="failifexecutionfails">
          <xsl:value-of select="'false'"/>
        </xsl:attribute>
        <xsl:attribute name="output">
          <xsl:value-of select="$outfile"/>
        </xsl:attribute>
        <xsl:attribute name="append">
          <xsl:value-of select="'true'"/>
        </xsl:attribute>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'ant'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-emacs'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-q'"/>
          </xsl:attribute>
        </xsl:element>
        <!--        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-v'"/>
          </xsl:attribute>
        </xsl:element> -->
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-buildfile'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('${UTILSDIR}','build.xml')"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('-DMODULES=','${MODULESDIR}',@name)"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'modules'"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:element>

      <xsl:element name="exec">
        <xsl:attribute name="executable">
          <xsl:value-of select="'bash'"/>
        </xsl:attribute>
        <xsl:attribute name="failifexecutionfails">
          <xsl:value-of select="'false'"/>
        </xsl:attribute>
        <xsl:attribute name="output">
          <xsl:value-of select="$outfile"/>
        </xsl:attribute>
        <xsl:attribute name="append">
          <xsl:value-of select="'true'"/>
        </xsl:attribute>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'ant'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-emacs'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-q'"/>
          </xsl:attribute>
        </xsl:element>
        <!--        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-v'"/>
          </xsl:attribute>
        </xsl:element> -->
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-buildfile'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('${UTILSDIR}','build.xml')"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('-DMODULES=','${MODULESDIR}',@name)"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'mapping'"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:element>

      <xsl:element name="exec">
        <xsl:attribute name="executable">
          <xsl:value-of select="'bash'"/>
        </xsl:attribute>
        <xsl:attribute name="failifexecutionfails">
          <xsl:value-of select="'false'"/>
        </xsl:attribute>
        <xsl:attribute name="output">
          <xsl:value-of select="$outfile"/>
        </xsl:attribute>
        <xsl:attribute name="append">
          <xsl:value-of select="'true'"/>
        </xsl:attribute>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'ant'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-emacs'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-q'"/>
          </xsl:attribute>
        </xsl:element>
        <!--        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-v'"/>
          </xsl:attribute>
        </xsl:element> -->
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'-buildfile'"/>
          </xsl:attribute>
        </xsl:element>
        <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('${UTILSDIR}','build.xml')"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="concat('-DMODULESDIR=','${MODULESDIR}',@name)"/>
          </xsl:attribute>
        </xsl:element>
       <xsl:element name="arg">
          <xsl:attribute name="value">            
          <xsl:value-of select="'valid_modules'"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:element>

  </xsl:template>


</xsl:stylesheet>












