(*
 $Id: mim.exp,v 1.6 2002/06/06 17:02:20 robbod Exp $
 N1154 - ISO/CD TS - 10303-1043 Work order - EXPRESS MIM 
*)

SCHEMA Work_order_mim;

USE FROM action_schema
(action_directive);

USE FROM action_schema
(action_directive);

USE FROM Activity_as_directed_mim;

USE FROM Activity_method_mim;

USE FROM Approval_mim;

USE FROM Contract_mim;

USE FROM Date_time_assignment_mim;

USE FROM Person_organization_assignment_mim;

USE FROM Work_request_mim;

END_SCHEMA;
