(*
   $Id: arm.exp,v 1.2 2003/04/22 09:46:15 rugarcia Exp $
   ISO/TC184/SC4 WG12N1338 - ISO/CD-TS 10303-436 ap236_furniture_catalog_and_interior_design - EXPRESS ARM
*)

SCHEMA Ap236_furniture_catalog_and_interior_design_arm;

	USE FROM Parametric_catalog_data_and_shape_representation_arm; --
	USE FROM Furniture_interior_decoration_arm;

CONSTANT 
  schema_name : STRING := 'AP236_FURNITURE_CATALOG_AND_INTERIOR_DESIGN_ARM';
END_CONSTANT;

END_SCHEMA;
