(*  
 $Id: mim_lf.exp,v 1.8 2005/04/27 12:42:24 rocc Exp $
 ISO TC184/SC4/WG3 N1859 - ISO/CD-TS 10303-436 ap236 furniture catalog and interior design - EXPRESS MIM Long form
*)
SCHEMA Ap236_furniture_catalog_and_interior_design_mim_lf;

  TYPE ahead_or_behind = ENUMERATION OF
    (AHEAD,
     EXACT,
     BEHIND);
  END_TYPE;

  TYPE aliasable_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE amount_of_substance_measure = REAL;
  END_TYPE;

  TYPE angle_relator = ENUMERATION OF
    (EQUAL,
     LARGE,
     SMALL);
  END_TYPE;

  TYPE approval_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE area_measure = REAL;
  END_TYPE;

  TYPE attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT
    (multi_language_attribute_assignment);
  END_TYPE;

  TYPE attribute_type = SELECT
    (label,
     text);
  END_TYPE;

  TYPE axis2_placement = SELECT
    (axis2_placement_2d,
     axis2_placement_3d);
  END_TYPE;

  TYPE b_spline_curve_form = ENUMERATION OF
    (POLYLINE_FORM,
     CIRCULAR_ARC,
     ELLIPTIC_ARC,
     PARABOLIC_ARC,
     HYPERBOLIC_ARC,
     UNSPECIFIED);
  END_TYPE;

  TYPE b_spline_surface_form = ENUMERATION OF
    (PLANE_SURF,
     CYLINDRICAL_SURF,
     CONICAL_SURF,
     SPHERICAL_SURF,
     TOROIDAL_SURF,
     SURF_OF_REVOLUTION,
     RULED_SURF,
     GENERALISED_CONE,
     QUADRIC_SURF,
     SURF_OF_LINEAR_EXTRUSION,
     UNSPECIFIED);
  END_TYPE;

  TYPE boolean_operand = SELECT
    (solid_model,
     half_space_solid,
     csg_primitive,
     boolean_result,
     half_space_2d);
  END_TYPE;

  TYPE boolean_operator = ENUMERATION OF
    (UNION,
     INTERSECTION,
     DIFFERENCE);
  END_TYPE;

  TYPE category_usage_item = SELECT
    (product_class);
  END_TYPE;

  TYPE celsius_temperature_measure = REAL;
  END_TYPE;

  TYPE certification_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE characterized_action_definition = SELECT
    (action,
     action_method,
     action_method_relationship,
     action_relationship);
  END_TYPE;

  TYPE characterized_definition = SELECT
    (characterized_object,
     characterized_product_definition,
     shape_definition);
  END_TYPE;

  TYPE characterized_material_property = SELECT
    (product_material_composition_relationship);
  END_TYPE;

  TYPE characterized_product_definition = SELECT
    (product_definition,
     product_definition_relationship);
  END_TYPE;

  TYPE characterized_resource_definition = SELECT
    (action_resource_requirement,
     action_resource_requirement_relationship);
  END_TYPE;

  TYPE class_system_item = EXTENSIBLE GENERIC_ENTITY SELECT
    (characterized_class);
  END_TYPE;

  TYPE class_usage_effectivity_context_item = SELECT
    (product_definition);
  END_TYPE;

  TYPE classification_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE classification_item_extended = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
    (characterized_class);
  END_TYPE;

  TYPE classification_select = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE classified_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE complete_membership_select = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE compound_item_definition = SELECT
    (list_representation_item,
     set_representation_item);
  END_TYPE;

  TYPE configuration_design_item = SELECT
    (product_definition,
     product_definition_formation);
  END_TYPE;

  TYPE configured_effectivity_context_item = SELECT
    (product_concept_feature_association);
  END_TYPE;

  TYPE configured_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE context_dependent_measure = REAL;
  END_TYPE;

  TYPE contract_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE count_measure = NUMBER;
  END_TYPE;

  TYPE csg_primitive = SELECT
    (sphere,
     ellipsoid,
     block,
     right_angular_wedge,
     faceted_primitive,
     rectangular_pyramid,
     torus,
     right_circular_cone,
     eccentric_cone,
     right_circular_cylinder,
     cyclide_segment_solid,
     primitive_2d);
  END_TYPE;

  TYPE csg_select = SELECT
    (boolean_result,
     csg_primitive);
  END_TYPE;

  TYPE curve_on_surface = SELECT
    (pcurve,
     surface_curve,
     composite_curve_on_surface);
  END_TYPE;

  TYPE date_and_time_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE date_and_time_item_approval = SELECT BASED_ON date_and_time_item;
  END_TYPE;

  TYPE date_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE date_item_approval = SELECT BASED_ON date_item;
  END_TYPE;

  TYPE date_time_or_event_occurrence = SELECT
    (date_time_select,
     event_occurrence);
  END_TYPE;

  TYPE date_time_select = SELECT
    (date,
     date_and_time,
     local_time);
  END_TYPE;

  TYPE day_in_month_number = INTEGER;
  END_TYPE;

  TYPE day_in_week_number = INTEGER;
  END_TYPE;

  TYPE day_in_year_number = INTEGER;
  END_TYPE;

  TYPE derived_property_select = SELECT
    (property_definition);
  END_TYPE;

  TYPE description_attribute_select = SELECT
    (action_request_solution,
     application_context,
     approval_role,
     configuration_design,
     context_dependent_shape_representation,
     date_role,
     date_time_role,
     effectivity,
     external_source,
     organization_role,
     person_and_organization,
     person_and_organization_role,
     person_role,
     property_definition_representation,
     representation,
     time_role);
  END_TYPE;

  TYPE descriptive_measure = STRING;
  END_TYPE;

  TYPE dimension_count = INTEGER;
  END_TYPE;

  TYPE dimension_identification_item = SELECT BASED_ON identification_item;
  END_TYPE;

  TYPE dimension_tolerance_document_reference_item = SELECT BASED_ON document_reference_item WITH
    (externally_defined_dimension_definition);
  END_TYPE;

  TYPE dimensional_characteristic = SELECT
    (dimensional_location,
     dimensional_size);
  END_TYPE;

  TYPE document_location_select = SELECT BASED_ON external_identification_item;
  END_TYPE;

  TYPE document_reference_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE effectivity_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE effectivity_item_for_replacement = SELECT BASED_ON effectivity_item;
  END_TYPE;

  TYPE effectivity_specification_for_replacement = SELECT BASED_ON effectivity_item;
  END_TYPE;

  TYPE electric_current_measure = REAL;
  END_TYPE;

  TYPE event_occurrence_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item;
  END_TYPE;

  TYPE event_occurrence_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item;
  END_TYPE;

  TYPE event_occurrence_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE extent_enumeration = ENUMERATION OF
    (INVALID,
     ZERO,
     FINITE_NON_ZERO,
     INFINITE);
  END_TYPE;

  TYPE external_class_name_item = SELECT BASED_ON name_item WITH
    (external_class_library);
  END_TYPE;

  TYPE external_identification_for_plib_property = SELECT BASED_ON external_identification_item WITH
    (externally_defined_general_property);
  END_TYPE;

  TYPE external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE externally_versioned_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE file_identification_item = SELECT BASED_ON identification_item WITH
    (document_file);
  END_TYPE;

  TYPE file_location_select = SELECT BASED_ON external_identification_item WITH
    (document_file);
  END_TYPE;

  TYPE file_version_item = SELECT BASED_ON versionable_item WITH
    (document_file);
  END_TYPE;

  TYPE founded_item_select = SELECT
    (founded_item,
     representation_item);
  END_TYPE;

  TYPE geometric_set_select = SELECT
    (point,
     curve,
     surface);
  END_TYPE;

  TYPE groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE hour_in_day = INTEGER;
  END_TYPE;

  TYPE id_attribute_select = SELECT
    (action,
     address,
     application_context,
     group,
     organizational_project,
     product_category,
     property_definition,
     representation,
     shape_aspect,
     shape_aspect_relationship);
  END_TYPE;

  TYPE id_for_class = SELECT BASED_ON identification_item WITH
    (characterized_class);
  END_TYPE;

  TYPE id_for_product_identification = SELECT BASED_ON identification_item WITH
    (product_identification);
  END_TYPE;

  TYPE identification_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE identifier = STRING;
  END_TYPE;

  TYPE idrm_marked_item = EXTENSIBLE SELECT BASED_ON classification_item;
  END_TYPE;

  TYPE instance_usage_context_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE knot_type = ENUMERATION OF
    (UNIFORM_KNOTS,
     QUASI_UNIFORM_KNOTS,
     PIECEWISE_BEZIER_KNOTS,
     UNSPECIFIED);
  END_TYPE;

  TYPE label = STRING;
  END_TYPE;

  TYPE length_measure = REAL;
  END_TYPE;

  TYPE limit_condition = ENUMERATION OF
    (MAXIMUM_MATERIAL_CONDITION,
     LEAST_MATERIAL_CONDITION,
     REGARDLESS_OF_FEATURE_SIZE);
  END_TYPE;

  TYPE list_of_reversible_topology_item = LIST OF reversible_topology_item;
  END_TYPE;

  TYPE list_representation_item = LIST [1:?] OF representation_item;
  END_TYPE;

  TYPE luminous_intensity_measure = REAL;
  END_TYPE;

  TYPE mass_measure = REAL;
  END_TYPE;

  TYPE mce_organization_item = SELECT BASED_ON organization_item;
  END_TYPE;

  TYPE measure_value = SELECT
    (amount_of_substance_measure,
     area_measure,
     celsius_temperature_measure,
     context_dependent_measure,
     count_measure,
     descriptive_measure,
     electric_current_measure,
     length_measure,
     luminous_intensity_measure,
     mass_measure,
     numeric_measure,
     parameter_value,
     plane_angle_measure,
     positive_length_measure,
     positive_plane_angle_measure,
     positive_ratio_measure,
     ratio_measure,
     solid_angle_measure,
     thermodynamic_temperature_measure,
     time_measure,
     volume_measure);
  END_TYPE;

  TYPE message = STRING;
  END_TYPE;

  TYPE minute_in_hour = INTEGER;
  END_TYPE;

  TYPE month_in_year_number = INTEGER;
  END_TYPE;

  TYPE mri_aliasable_item = EXTENSIBLE SELECT BASED_ON aliasable_item;
  END_TYPE;

  TYPE mri_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item;
  END_TYPE;

  TYPE mri_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item;
  END_TYPE;

  TYPE mri_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item;
  END_TYPE;

  TYPE mri_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item;
  END_TYPE;

  TYPE mri_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item;
  END_TYPE;

  TYPE mri_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item;
  END_TYPE;

  TYPE mri_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item;
  END_TYPE;

  TYPE mri_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item;
  END_TYPE;

  TYPE multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE name_attribute_select = SELECT
    (action_request_solution,
     address,
     configuration_design,
     context_dependent_shape_representation,
     derived_unit,
     effectivity,
     person_and_organization,
     product_definition,
     product_definition_substitute,
     property_definition_representation);
  END_TYPE;

  TYPE name_item = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE numeric_measure = NUMBER;
  END_TYPE;

  TYPE organization_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE organization_item_solution = SELECT BASED_ON organization_item;
  END_TYPE;

  TYPE parameter_value = REAL;
  END_TYPE;

  TYPE pcurve_or_surface = SELECT
    (pcurve,
     surface);
  END_TYPE;

  TYPE person_and_organization_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE person_organization_select = SELECT
    (organization,
     person,
     person_and_organization);
  END_TYPE;

  TYPE plane_angle_measure = REAL;
  END_TYPE;

  TYPE plib_class_identification_item = SELECT BASED_ON external_identification_item;
  END_TYPE;

  TYPE plib_class_organization_item = SELECT BASED_ON organization_item;
  END_TYPE;

  TYPE positive_length_measure = length_measure;
  END_TYPE;

  TYPE positive_plane_angle_measure = plane_angle_measure;
  END_TYPE;

  TYPE positive_ratio_measure = ratio_measure;
  END_TYPE;

  TYPE preferred_surface_curve_representation = ENUMERATION OF
    (CURVE_3D,
     PCURVE_S1,
     PCURVE_S2);
  END_TYPE;

  TYPE product_as_individual_identification_item = SELECT BASED_ON identification_item WITH
    (product_as_individual,
     product_as_individual_version,
     product_as_individual_view);
  END_TYPE;

  TYPE product_definition_or_assembly_relationship = SELECT
    (assembly_component_usage,
     product_definition);
  END_TYPE;

  TYPE product_definition_or_breakdown_element_usage = EXTENSIBLE GENERIC_ENTITY SELECT
    (breakdown_element_usage);
  END_TYPE;

  TYPE product_definition_or_product_definition_relationship = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  TYPE product_or_formation_or_definition = SELECT
    (product,
     product_definition_formation,
     product_definition);
  END_TYPE;

  TYPE project_as_date_and_time_item = SELECT BASED_ON date_and_time_item;
  END_TYPE;

  TYPE project_as_date_item = SELECT BASED_ON date_item;
  END_TYPE;

  TYPE project_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE property_or_shape_select = SELECT
    (property_definition,
     shape_definition);
  END_TYPE;

  TYPE ratio_measure = REAL;
  END_TYPE;

  TYPE representation_identification_item = SELECT BASED_ON identification_item;
  END_TYPE;

  TYPE representation_version_item = SELECT BASED_ON versionable_item;
  END_TYPE;

  TYPE represented_definition = SELECT
    (general_property,
     property_definition,
     property_definition_relationship,
     shape_aspect,
     shape_aspect_relationship);
  END_TYPE;

  TYPE requirement_identification_and_version_mri_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON mri_identification_item;
  END_TYPE;

  TYPE reversible_topology = SELECT
    (reversible_topology_item,
     list_of_reversible_topology_item,
     set_of_reversible_topology_item);
  END_TYPE;

  TYPE reversible_topology_item = SELECT
    (edge,
     path,
     face,
     face_bound,
     closed_shell,
     open_shell);
  END_TYPE;

  TYPE role_select = SELECT
    (action_assignment,
     action_request_assignment,
     approval_assignment,
     approval_date_time,
     certification_assignment,
     contract_assignment,
     document_reference,
     effectivity_assignment,
     external_referent_assignment,
     group_assignment,
     name_assignment,
     security_classification_assignment);
  END_TYPE;

  TYPE second_in_minute = REAL;
  END_TYPE;

  TYPE security_classification_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE set_of_reversible_topology_item = SET OF reversible_topology_item;
  END_TYPE;

  TYPE set_representation_item = SET [1:?] OF representation_item;
  END_TYPE;

  TYPE shape_definition = SELECT
    (product_definition_shape,
     shape_aspect,
     shape_aspect_relationship);
  END_TYPE;

  TYPE shape_tolerance_select = SELECT
    (geometric_tolerance,
     plus_minus_tolerance);
  END_TYPE;

  TYPE shell = SELECT
    (vertex_shell,
     wire_shell,
     open_shell,
     closed_shell);
  END_TYPE;

  TYPE si_prefix = ENUMERATION OF
    (EXA,
     PETA,
     TERA,
     GIGA,
     MEGA,
     KILO,
     HECTO,
     DECA,
     DECI,
     CENTI,
     MILLI,
     MICRO,
     NANO,
     PICO,
     FEMTO,
     ATTO);
  END_TYPE;

  TYPE si_unit_name = ENUMERATION OF
    (METRE,
     GRAM,
     SECOND,
     AMPERE,
     KELVIN,
     MOLE,
     CANDELA,
     RADIAN,
     STERADIAN,
     HERTZ,
     NEWTON,
     PASCAL,
     JOULE,
     WATT,
     COULOMB,
     VOLT,
     FARAD,
     OHM,
     SIEMENS,
     WEBER,
     TESLA,
     HENRY,
     DEGREE_CELSIUS,
     LUMEN,
     LUX,
     BECQUEREL,
     GRAY,
     SIEVERT);
  END_TYPE;

  TYPE solid_angle_measure = REAL;
  END_TYPE;

  TYPE source = ENUMERATION OF
    (MADE,
     BOUGHT,
     NOT_KNOWN);
  END_TYPE;

  TYPE source_item = SELECT
    (message);
  END_TYPE;

  TYPE specification_for_category = SELECT BASED_ON groupable_item WITH
    (package_product_concept_feature);
  END_TYPE;

  TYPE spr_document_reference_item = SELECT BASED_ON document_reference_item;
  END_TYPE;

  TYPE spr_organization_item = EXTENSIBLE SELECT BASED_ON organization_item;
  END_TYPE;

  TYPE spr_person_and_organization_item = EXTENSIBLE SELECT BASED_ON person_and_organization_item;
  END_TYPE;

  TYPE supported_item = SELECT
    (action,
     action_directive,
     action_method);
  END_TYPE;

  TYPE surface_boundary = SELECT
    (boundary_curve,
     degenerate_pcurve);
  END_TYPE;

  TYPE surface_model = SELECT
    (shell_based_surface_model,
     face_based_surface_model);
  END_TYPE;

  TYPE text = STRING;
  END_TYPE;

  TYPE thermodynamic_temperature_measure = REAL;
  END_TYPE;

  TYPE time_measure = REAL;
  END_TYPE;

  TYPE tolerance_method_definition = SELECT
    (tolerance_value,
     limits_and_fits);
  END_TYPE;

  TYPE transformation = SELECT
    (item_defined_transformation,
     functionally_defined_transformation);
  END_TYPE;

  TYPE transition_code = ENUMERATION OF
    (DISCONTINUOUS,
     CONTINUOUS,
     CONT_SAME_GRADIENT,
     CONT_SAME_GRADIENT_SAME_CURVATURE);
  END_TYPE;

  TYPE trimming_preference = ENUMERATION OF
    (CARTESIAN,
     PARAMETER,
     UNSPECIFIED);
  END_TYPE;

  TYPE trimming_select = SELECT
    (cartesian_point);
  END_TYPE;

  TYPE unit = SELECT
    (derived_unit,
     named_unit);
  END_TYPE;

  TYPE value_qualifier = SELECT
    (precision_qualifier,
     type_qualifier,
     uncertainty_qualifier);
  END_TYPE;

  TYPE vector_or_direction = SELECT
    (vector,
     direction);
  END_TYPE;

  TYPE version_for_class = SELECT BASED_ON versionable_item WITH
    (characterized_class);
  END_TYPE;

  TYPE version_for_plib_property = SELECT BASED_ON externally_versioned_item WITH
    (externally_defined_general_property);
  END_TYPE;

  TYPE version_for_product_identification = SELECT BASED_ON versionable_item WITH
    (product_identification);
  END_TYPE;

  TYPE versionable_item = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE volume_measure = REAL;
  END_TYPE;

  TYPE week_in_year_number = INTEGER;
  END_TYPE;

  TYPE wireframe_model = SELECT
    (shell_based_wireframe_model,
     edge_based_wireframe_model);
  END_TYPE;

  TYPE year_number = INTEGER;
  END_TYPE;

  ENTITY action;
      name          : label;
      description   : OPTIONAL text;
      chosen_method : action_method;
    DERIVE
      id            : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY action_assignment
    ABSTRACT;
      assigned_action : action;
    DERIVE
      role            : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY action_directive;
      name        : label;
      description : OPTIONAL text;
      analysis    : text;
      comment     : text;
      requests    : SET [1:?] OF versioned_action_request;
  END_ENTITY;

  ENTITY action_method;
      name        : label;
      description : OPTIONAL text;
      consequence : text;
      purpose     : text;
  END_ENTITY;

  ENTITY action_method_assignment
    ABSTRACT;
      assigned_action_method : action_method;
      role                   : action_method_role;
  END_ENTITY;

  ENTITY action_method_relationship;
      name            : label;
      description     : OPTIONAL text;
      relating_method : action_method;
      related_method  : action_method;
  END_ENTITY;

  ENTITY action_method_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY action_property;
      name        : label;
      description : text;
      definition  : characterized_action_definition;
  END_ENTITY;

  ENTITY action_property_relationship;
      name                     : label;
      description              : text;
      relating_action_property : action_property;
      related_action_property  : action_property;
  END_ENTITY;

  ENTITY action_relationship;
      name            : label;
      description     : OPTIONAL text;
      relating_action : action;
      related_action  : action;
  END_ENTITY;

  ENTITY action_request_assignment
    ABSTRACT;
      assigned_action_request : versioned_action_request;
    DERIVE
      role                    : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY action_request_solution;
      method      : action_method;
      request     : versioned_action_request;
    DERIVE
      description : text := get_description_value (SELF);
      name        : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY action_request_status;
      status           : label;
      assigned_request : versioned_action_request;
  END_ENTITY;

  ENTITY action_resource;
      name        : label;
      description : OPTIONAL text;
      usage       : SET [1:?] OF supported_item;
      kind        : action_resource_type;
  END_ENTITY;

  ENTITY action_resource_relationship;
      name              : label;
      description       : OPTIONAL text;
      relating_resource : action_resource;
      related_resource  : action_resource;
  END_ENTITY;

  ENTITY action_resource_requirement;
      name        : label;
      description : text;
      kind        : resource_requirement_type;
      operations  : SET [1:?] OF characterized_action_definition;
  END_ENTITY;

  ENTITY action_resource_requirement_relationship;
      name                                 : label;
      description                          : text;
      relating_action_resource_requirement : action_resource_requirement;
      related_action_resource_requirement  : action_resource_requirement;
  END_ENTITY;

  ENTITY action_resource_type;
      name : label;
  END_ENTITY;

  ENTITY action_status;
      status          : label;
      assigned_action : executed_action;
  END_ENTITY;

  ENTITY address;
      internal_location       : OPTIONAL label;
      street_number           : OPTIONAL label;
      street                  : OPTIONAL label;
      postal_box              : OPTIONAL label;
      town                    : OPTIONAL label;
      region                  : OPTIONAL label;
      postal_code             : OPTIONAL label;
      country                 : OPTIONAL label;
      facsimile_number        : OPTIONAL label;
      telephone_number        : OPTIONAL label;
      electronic_mail_address : OPTIONAL label;
      telex_number            : OPTIONAL label;
    DERIVE
      name                    : label := get_name_value(SELF);
      url                     : identifier := get_id_value(SELF);
  END_ENTITY;

  ENTITY advanced_face
    SUBTYPE OF(face_surface);
  END_ENTITY;

  ENTITY alternate_product_relationship;
      name       : label;
      definition : OPTIONAL text;
      alternate  : product;
      base       : product;
      basis      : text;
    UNIQUE
      UR1 : alternate, base;
  END_ENTITY;

  ENTITY amount_of_substance_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY amount_of_substance_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY angular_location
    SUBTYPE OF(dimensional_location);
      angle_selection : angle_relator;
  END_ENTITY;

  ENTITY angular_size
    SUBTYPE OF(dimensional_size);
      angle_selection : angle_relator;
  END_ENTITY;

  ENTITY apex
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY application_context;
      application      : label;
    DERIVE
      description      : text := get_description_value (SELF);
      id               : identifier := get_id_value (SELF);
    INVERSE
      context_elements : SET [1:?] OF application_context_element FOR frame_of_reference;
  END_ENTITY;

  ENTITY application_context_element
    SUPERTYPE OF (ONEOF(library_context, product_concept_context, product_context, product_definition_context));
      name               : label;
      frame_of_reference : application_context;
  END_ENTITY;

  ENTITY application_context_relationship;
      name             : label;
      description      : OPTIONAL text;
      relating_context : application_context;
      related_context  : application_context;
  END_ENTITY;

  ENTITY application_protocol_definition;
      status                                    : label;
      application_interpreted_model_schema_name : label;
      application_protocol_year                 : year_number;
      application                               : application_context;
  END_ENTITY;

  ENTITY applied_approval_assignment
    SUBTYPE OF(approval_assignment);
      items : SET [1:?] OF approval_item;
  END_ENTITY;

  ENTITY applied_certification_assignment
    SUBTYPE OF(certification_assignment);
      items : SET [1:?] OF certification_item;
  END_ENTITY;

  ENTITY applied_classification_assignment
    SUBTYPE OF(classification_assignment);
      items : SET [1:?] OF classification_item;
  END_ENTITY;

  ENTITY applied_contract_assignment
    SUBTYPE OF(contract_assignment);
      items : SET [1:?] OF contract_item;
  END_ENTITY;

  ENTITY applied_date_and_time_assignment
    SUBTYPE OF(date_and_time_assignment);
      items : SET [1:?] OF date_and_time_item;
  END_ENTITY;

  ENTITY applied_date_assignment
    SUBTYPE OF(date_assignment);
      items : SET [1:?] OF date_item;
  END_ENTITY;

  ENTITY applied_document_reference
    SUBTYPE OF(document_reference);
      items : SET [1:?] OF document_reference_item;
  END_ENTITY;

  ENTITY applied_document_usage_constraint_assignment
    SUBTYPE OF(document_usage_constraint_assignment);
      items : SET [1:?] OF document_reference_item;
  END_ENTITY;

  ENTITY applied_effectivity_assignment
    SUBTYPE OF(effectivity_assignment);
      items : SET [1:?] OF effectivity_item;
  END_ENTITY;

  ENTITY applied_event_occurrence_assignment
    SUBTYPE OF(event_occurrence_assignment);
      items : SET [1:?] OF event_occurrence_item;
  END_ENTITY;

  ENTITY applied_external_identification_assignment
    SUBTYPE OF(external_identification_assignment);
      items : SET [1:?] OF external_identification_item;
  END_ENTITY;

  ENTITY applied_group_assignment
    SUBTYPE OF(group_assignment);
      items : SET [1:?] OF groupable_item;
  END_ENTITY;

  ENTITY applied_identification_assignment
    SUBTYPE OF(identification_assignment);
      items : SET [1:?] OF identification_item;
  END_ENTITY;

  ENTITY applied_name_assignment
    SUBTYPE OF(name_assignment);
      item : name_item;
  END_ENTITY;

  ENTITY applied_organization_assignment
    SUBTYPE OF(organization_assignment);
      items : SET [1:?] OF organization_item;
  END_ENTITY;

  ENTITY applied_organizational_project_assignment
    SUBTYPE OF(organizational_project_assignment);
      items : SET [1:?] OF project_item;
  END_ENTITY;

  ENTITY applied_person_and_organization_assignment
    SUBTYPE OF(person_and_organization_assignment);
      items : SET [1:?] OF person_and_organization_item;
  END_ENTITY;

  ENTITY applied_security_classification_assignment
    SUBTYPE OF(security_classification_assignment);
      items : SET [1:?] OF security_classification_item;
  END_ENTITY;

  ENTITY approval;
      status : approval_status;
      level  : label;
  END_ENTITY;

  ENTITY approval_assignment
    ABSTRACT;
      assigned_approval : approval;
    DERIVE
      role              : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY approval_date_time;
      date_time      : date_time_select;
      dated_approval : approval;
    DERIVE
      role           : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY approval_person_organization;
      person_organization : person_organization_select;
      authorized_approval : approval;
      role                : approval_role;
  END_ENTITY;

  ENTITY approval_relationship;
      name              : label;
      description       : OPTIONAL text;
      relating_approval : approval;
      related_approval  : approval;
  END_ENTITY;

  ENTITY approval_role;
      role        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY approval_status;
      name : label;
  END_ENTITY;

  ENTITY area_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY area_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY assembly_component_usage
    SUPERTYPE OF (ONEOF(next_assembly_usage_occurrence, specified_higher_usage_occurrence, promissory_usage_occurrence) ANDOR quantified_assembly_component_usage)
    SUBTYPE OF(product_definition_usage);
      reference_designator : OPTIONAL identifier;
  END_ENTITY;

  ENTITY assembly_component_usage_substitute;
      name       : label;
      definition : OPTIONAL text;
      base       : assembly_component_usage;
      substitute : assembly_component_usage;
    UNIQUE
      UR1 : base, substitute;
  END_ENTITY;

  ENTITY assembly_component_usage_substitute_with_ranking
    SUBTYPE OF(assembly_component_usage_substitute);
      ranking           : INTEGER;
      ranking_rationale : text;
  END_ENTITY;

  ENTITY attribute_classification_assignment
    ABSTRACT;
      assigned_class : group;
      attribute_name : label;
      role           : classification_role;
  END_ENTITY;

  ENTITY attribute_language_assignment
    SUBTYPE OF(attribute_classification_assignment);
      SELF\attribute_classification_assignment.assigned_class : language;
      items                                                   : SET [1:?] OF attribute_language_item;
  END_ENTITY;

  ENTITY attribute_value_assignment
    ABSTRACT;
      attribute_name  : label;
      attribute_value : attribute_type;
      role            : attribute_value_role;
  END_ENTITY;

  ENTITY attribute_value_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY axis1_placement
    SUBTYPE OF(placement);
      axis : OPTIONAL direction;
    DERIVE
      z    : direction := NVL(normalise(axis), dummy_gri ||
             direction([0.0,0.0,1.0]));
  END_ENTITY;

  ENTITY axis2_placement_2d
    SUBTYPE OF(placement);
      ref_direction : OPTIONAL direction;
    DERIVE
      p             : LIST [2:2] OF direction := build_2axes(ref_direction);
  END_ENTITY;

  ENTITY axis2_placement_3d
    SUBTYPE OF(placement);
      axis          : OPTIONAL direction;
      ref_direction : OPTIONAL direction;
    DERIVE
      p             : LIST [3:3] OF direction := build_axes(axis,ref_direction);
  END_ENTITY;

  ENTITY b_spline_curve
    SUPERTYPE OF (ONEOF(uniform_curve, b_spline_curve_with_knots, quasi_uniform_curve, bezier_curve) ANDOR rational_b_spline_curve)
    SUBTYPE OF(bounded_curve);
      degree                        : INTEGER;
      control_points_list           : LIST [2:?] OF cartesian_point;
      curve_form                    : b_spline_curve_form;
      closed_curve                  : LOGICAL;
      self_intersect                : LOGICAL;
    DERIVE
      upper_index_on_control_points : INTEGER := (SIZEOF(control_points_list) - 1);
      control_points                : ARRAY [0:100] OF cartesian_point := list_to_array(control_points_list,0,
                                      upper_index_on_control_points);
  END_ENTITY;

  ENTITY b_spline_curve_with_knots
    SUBTYPE OF(b_spline_curve);
      knot_multiplicities  : LIST [2:?] OF INTEGER;
      knots                : LIST [2:?] OF parameter_value;
      knot_spec            : knot_type;
    DERIVE
      upper_index_on_knots : INTEGER := SIZEOF(knots);
  END_ENTITY;

  ENTITY b_spline_surface
    SUPERTYPE OF (ONEOF(b_spline_surface_with_knots, uniform_surface, quasi_uniform_surface, bezier_surface) ANDOR rational_b_spline_surface)
    SUBTYPE OF(bounded_surface);
      u_degree            : INTEGER;
      v_degree            : INTEGER;
      control_points_list : LIST [2:?] OF LIST [2:?] OF cartesian_point;
      surface_form        : b_spline_surface_form;
      u_closed            : LOGICAL;
      v_closed            : LOGICAL;
      self_intersect      : LOGICAL;
    DERIVE
      u_upper             : INTEGER := SIZEOF(control_points_list) - 1;
      v_upper             : INTEGER := SIZEOF(control_points_list[1]) - 1;
      control_points      : ARRAY [0:100] OF ARRAY [0:100] OF cartesian_point := make_array_of_array(control_points_list,
                            0,u_upper,0,v_upper);
  END_ENTITY;

  ENTITY b_spline_surface_with_knots
    SUBTYPE OF(b_spline_surface);
      u_multiplicities : LIST [2:?] OF INTEGER;
      v_multiplicities : LIST [2:?] OF INTEGER;
      u_knots          : LIST [2:?] OF parameter_value;
      v_knots          : LIST [2:?] OF parameter_value;
      knot_spec        : knot_type;
    DERIVE
      knot_u_upper     : INTEGER := SIZEOF(u_knots);
      knot_v_upper     : INTEGER := SIZEOF(v_knots);
  END_ENTITY;

  ENTITY b_spline_volume
    SUPERTYPE OF (ONEOF(b_spline_volume_with_knots, uniform_volume, quasi_uniform_volume, bezier_volume) ANDOR rational_b_spline_volume)
    SUBTYPE OF(volume);
      u_degree            : INTEGER;
      v_degree            : INTEGER;
      w_degree            : INTEGER;
      control_points_list : LIST [2:?] OF LIST [2:?] OF LIST [2:?] OF cartesian_point;
    DERIVE
      u_upper             : INTEGER := SIZEOF(control_points_list) - 1;
      v_upper             : INTEGER := SIZEOF(control_points_list[1]) - 1;
      w_upper             : INTEGER := SIZEOF(control_points_list[1][1]) - 1;
      control_points      : ARRAY [0:100] OF ARRAY [0:100] OF ARRAY [0:100] OF cartesian_point := make_array_of_array_of_array (control_points_list,
                            0,u_upper,0,v_upper,
                            0,w_upper );
  END_ENTITY;

  ENTITY b_spline_volume_with_knots
    SUBTYPE OF(b_spline_volume);
      u_multiplicities : LIST [2:?] OF INTEGER;
      v_multiplicities : LIST [2:?] OF INTEGER;
      w_multiplicities : LIST [2:?] OF INTEGER;
      u_knots          : LIST [2:?] OF parameter_value;
      v_knots          : LIST [2:?] OF parameter_value;
      w_knots          : LIST [2:?] OF parameter_value;
    DERIVE
      knot_u_upper     : INTEGER := SIZEOF(u_knots);
      knot_v_upper     : INTEGER := SIZEOF(v_knots);
      knot_w_upper     : INTEGER := SIZEOF(w_knots);
  END_ENTITY;

  ENTITY bezier_curve
    SUBTYPE OF(b_spline_curve);
  END_ENTITY;

  ENTITY bezier_surface
    SUBTYPE OF(b_spline_surface);
  END_ENTITY;

  ENTITY bezier_volume
    SUBTYPE OF(b_spline_volume);
  END_ENTITY;

  ENTITY block
    SUBTYPE OF(geometric_representation_item);
      position : axis2_placement_3d;
      x        : positive_length_measure;
      y        : positive_length_measure;
      z        : positive_length_measure;
  END_ENTITY;

  ENTITY block_volume
    SUBTYPE OF(volume);
      position : axis2_placement_3d;
      x        : positive_length_measure;
      y        : positive_length_measure;
      z        : positive_length_measure;
  END_ENTITY;

  ENTITY boolean_result
    SUBTYPE OF(geometric_representation_item);
      operator       : boolean_operator;
      first_operand  : boolean_operand;
      second_operand : boolean_operand;
  END_ENTITY;

  ENTITY boundary_curve
    SUBTYPE OF(composite_curve_on_surface);
  END_ENTITY;

  ENTITY bounded_curve
    SUPERTYPE OF (ONEOF(polyline, b_spline_curve, trimmed_curve, bounded_pcurve, bounded_surface_curve, composite_curve))
    SUBTYPE OF(curve);
  END_ENTITY;

  ENTITY bounded_pcurve
    SUBTYPE OF(pcurve, bounded_curve);
  END_ENTITY;

  ENTITY bounded_surface
    SUPERTYPE OF (ONEOF(b_spline_surface, rectangular_trimmed_surface, curve_bounded_surface, rectangular_composite_surface))
    SUBTYPE OF(surface);
  END_ENTITY;

  ENTITY bounded_surface_curve
    SUBTYPE OF(surface_curve, bounded_curve);
  END_ENTITY;

  ENTITY box_domain
    SUBTYPE OF(founded_item);
      corner  : cartesian_point;
      xlength : positive_length_measure;
      ylength : positive_length_measure;
      zlength : positive_length_measure;
  END_ENTITY;

  ENTITY boxed_half_space
    SUBTYPE OF(half_space_solid);
      enclosure : box_domain;
  END_ENTITY;

  ENTITY breakdown_context
    SUBTYPE OF(product_definition_relationship);
  END_ENTITY;

  ENTITY breakdown_element_group_assignment
    SUBTYPE OF(group_assignment);
      SELF\group_assignment.assigned_group : product_definition_element_relationship;
      items                                : SET [1:1] OF product_definition_or_breakdown_element_usage;
  END_ENTITY;

  ENTITY breakdown_element_realization
    SUBTYPE OF(characterized_object, product_definition_element_relationship);
  END_ENTITY;

  ENTITY breakdown_element_usage
    SUBTYPE OF(product_definition_relationship);
  END_ENTITY;

  ENTITY breakdown_of
    SUBTYPE OF(product_definition_relationship);
  END_ENTITY;

  ENTITY brep_2d
    SUBTYPE OF(solid_model);
      extent : face;
  END_ENTITY;

  ENTITY brep_with_voids
    SUBTYPE OF(manifold_solid_brep);
      voids : SET [1:?] OF oriented_closed_shell;
  END_ENTITY;

  ENTITY calendar_date
    SUBTYPE OF(date);
      day_component   : day_in_month_number;
      month_component : month_in_year_number;
  END_ENTITY;

  ENTITY cartesian_point
    SUPERTYPE OF (ONEOF(cylindrical_point, polar_point, spherical_point))
    SUBTYPE OF(point);
      coordinates : LIST [1:3] OF length_measure;
  END_ENTITY;

  ENTITY cartesian_transformation_operator
    SUPERTYPE OF (ONEOF(cartesian_transformation_operator_2d, cartesian_transformation_operator_3d))
    SUBTYPE OF(geometric_representation_item, functionally_defined_transformation);
      axis1        : OPTIONAL direction;
      axis2        : OPTIONAL direction;
      local_origin : cartesian_point;
      scale        : OPTIONAL REAL;
    DERIVE
      scl          : REAL := NVL(scale, 1.0);
  END_ENTITY;

  ENTITY cartesian_transformation_operator_2d
    SUBTYPE OF(cartesian_transformation_operator);
    DERIVE
      u : LIST [2:2] OF direction := 
          base_axis(2,SELF\cartesian_transformation_operator.axis1,
          SELF\cartesian_transformation_operator.axis2,?);
  END_ENTITY;

  ENTITY cartesian_transformation_operator_3d
    SUBTYPE OF(cartesian_transformation_operator);
      axis3 : OPTIONAL direction;
    DERIVE
      u     : LIST [3:3] OF direction := base_axis(3,SELF\cartesian_transformation_operator.axis1,
              SELF\cartesian_transformation_operator.axis2,axis3);
  END_ENTITY;

  ENTITY celsius_temperature_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY centre_of_symmetry
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY certification;
      name    : label;
      purpose : text;
      kind    : certification_type;
  END_ENTITY;

  ENTITY certification_assignment
    ABSTRACT;
      assigned_certification : certification;
    DERIVE
      role                   : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY certification_type;
      description : label;
  END_ENTITY;

  ENTITY characterized_class
    SUBTYPE OF(characterized_object, class);
  END_ENTITY;

  ENTITY characterized_object;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY characterized_object_relationship;
      name            : label;
      description     : OPTIONAL text;
      relating_object : characterized_object;
      related_object  : characterized_object;
  END_ENTITY;

  ENTITY circle
    SUBTYPE OF(conic);
      radius : positive_length_measure;
  END_ENTITY;

  ENTITY circular_area
    SUBTYPE OF(primitive_2d);
      centre : cartesian_point;
      radius : positive_length_measure;
  END_ENTITY;

  ENTITY circular_involute
    SUBTYPE OF(curve);
      position    : axis2_placement;
      base_radius : positive_length_measure;
  END_ENTITY;

  ENTITY class
    SUBTYPE OF(group);
  END_ENTITY;

  ENTITY class_by_extension
    SUBTYPE OF(class);
  END_ENTITY;

  ENTITY class_by_intension
    SUBTYPE OF(class);
  END_ENTITY;

  ENTITY class_system
    SUBTYPE OF(group);
  END_ENTITY;

  ENTITY class_usage_effectivity_context_assignment
    SUBTYPE OF(effectivity_context_assignment);
      items : SET [1:?] OF class_usage_effectivity_context_item;
  END_ENTITY;

  ENTITY classification
    SUBTYPE OF(classification_assignment);
      classified : classification_select;
    DERIVE
      classifier : class := SELF\classification_assignment.assigned_class;
  END_ENTITY;

  ENTITY classification_assignment
    ABSTRACT;
      assigned_class : group;
      role           : classification_role;
  END_ENTITY;

  ENTITY classification_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY closed_shell
    SUBTYPE OF(connected_face_set);
  END_ENTITY;

  ENTITY clothoid
    SUBTYPE OF(curve);
      position          : axis2_placement;
      clothoid_constant : length_measure;
  END_ENTITY;

  ENTITY complete_membership
    SUBTYPE OF(classification_assignment);
    DERIVE
      containing_set : class := SELF\classification_assignment.assigned_class;
  END_ENTITY;

  ENTITY complete_membership_of_empty_set
    SUBTYPE OF(complete_membership);
  END_ENTITY;

  ENTITY complete_membership_of_non_empty_set
    SUBTYPE OF(complete_membership);
      members : SET [1:?] OF complete_membership_select;
  END_ENTITY;

  ENTITY composite_curve
    SUBTYPE OF(bounded_curve);
      segments       : LIST [1:?] OF composite_curve_segment;
      self_intersect : LOGICAL;
    DERIVE
      n_segments     : INTEGER := SIZEOF(segments);
      closed_curve   : LOGICAL := segments[n_segments].transition <> discontinuous;
  END_ENTITY;

  ENTITY composite_curve_on_surface
    SUBTYPE OF(composite_curve);
    DERIVE
      basis_surface : SET [0:2] OF surface := 
                      get_basis_surface(SELF);
  END_ENTITY;

  ENTITY composite_curve_segment
    SUBTYPE OF(founded_item);
      transition   : transition_code;
      same_sense   : BOOLEAN;
      parent_curve : curve;
    INVERSE
      using_curves : BAG [1:?] OF composite_curve FOR segments;
  END_ENTITY;

  ENTITY composite_shape_aspect
    SUBTYPE OF(shape_aspect);
    INVERSE
      component_relationships : SET [2:?] OF shape_aspect_relationship FOR relating_shape_aspect;
  END_ENTITY;

  ENTITY compound_representation_item
    SUBTYPE OF(representation_item);
      item_element : compound_item_definition;
  END_ENTITY;

  ENTITY concept_feature_operator;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY concept_feature_relationship;
      name                             : label;
      description                      : OPTIONAL text;
      relating_product_concept_feature : product_concept_feature;
      related_product_concept_feature  : product_concept_feature;
  END_ENTITY;

  ENTITY concept_feature_relationship_with_condition
    SUBTYPE OF(concept_feature_relationship);
      conditional_operator : concept_feature_operator;
  END_ENTITY;

  ENTITY conditional_concept_feature
    SUBTYPE OF(product_concept_feature);
      condition : concept_feature_relationship_with_condition;
  END_ENTITY;

  ENTITY configurable_item
    SUBTYPE OF(configuration_item);
      item_concept_feature : SET [1:?] OF product_concept_feature_association;
  END_ENTITY;

  ENTITY configuration_design;
      configuration : configuration_item;
      design        : configuration_design_item;
    DERIVE
      name          : label := get_name_value (SELF);
      description   : text := get_description_value (SELF);
    UNIQUE
      UR1 : configuration, design;
  END_ENTITY;

  ENTITY configuration_effectivity
    SUBTYPE OF(product_definition_effectivity);
      configuration : configuration_design;
  END_ENTITY;

  ENTITY configuration_item;
      id           : identifier;
      name         : label;
      description  : OPTIONAL text;
      item_concept : product_concept;
      purpose      : OPTIONAL label;
  END_ENTITY;

  ENTITY configuration_item_relationship;
      name                        : label;
      description                 : OPTIONAL text;
      relating_configuration_item : configuration_item;
      related_configuration_item  : configuration_item;
  END_ENTITY;

  ENTITY configured_effectivity_assignment
    SUBTYPE OF(effectivity_assignment);
      items : SET [1:?] OF configured_effectivity_item;
  END_ENTITY;

  ENTITY configured_effectivity_context_assignment
    SUBTYPE OF(effectivity_context_assignment);
      SELF\effectivity_context_assignment.assigned_effectivity_assignment : configured_effectivity_assignment;
      items                                                               : SET [1:?] OF configured_effectivity_context_item;
  END_ENTITY;

  ENTITY conic
    SUPERTYPE OF (ONEOF(circle, ellipse, hyperbola, parabola))
    SUBTYPE OF(curve);
      position : axis2_placement;
  END_ENTITY;

  ENTITY conical_surface
    SUBTYPE OF(elementary_surface);
      radius     : length_measure;
      semi_angle : plane_angle_measure;
  END_ENTITY;

  ENTITY connected_edge_set
    SUBTYPE OF(topological_representation_item);
      ces_edges : SET [1:?] OF edge;
  END_ENTITY;

  ENTITY connected_face_set
    SUPERTYPE OF (ONEOF(closed_shell, open_shell) ANDOR connected_face_sub_set)
    SUBTYPE OF(topological_representation_item);
      cfs_faces : SET [1:?] OF face;
  END_ENTITY;

  ENTITY connected_face_sub_set
    SUBTYPE OF(connected_face_set);
      parent_face_set : connected_face_set;
  END_ENTITY;

  ENTITY constructive_geometry_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY constructive_geometry_representation_relationship
    SUBTYPE OF(representation_relationship);
  END_ENTITY;

  ENTITY contact_ratio_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY context_dependent_shape_representation;
      representation_relation      : shape_representation_relationship;
      represented_product_relation : product_definition_shape;
    DERIVE
      description                  : text := get_description_value (SELF);
      name                         : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY context_dependent_unit
    SUBTYPE OF(named_unit);
      name : label;
  END_ENTITY;

  ENTITY contract;
      name    : label;
      purpose : text;
      kind    : contract_type;
  END_ENTITY;

  ENTITY contract_assignment
    ABSTRACT;
      assigned_contract : contract;
    DERIVE
      role              : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY contract_relationship;
      id                : identifier;
      name              : label;
      description       : OPTIONAL text;
      relating_contract : contract;
      related_contract  : contract;
  END_ENTITY;

  ENTITY contract_type;
      description : label;
  END_ENTITY;

  ENTITY conversion_based_unit
    SUBTYPE OF(named_unit);
      name              : label;
      conversion_factor : measure_with_unit;
  END_ENTITY;

  ENTITY convex_hexahedron
    SUBTYPE OF(faceted_primitive);
  END_ENTITY;

  ENTITY coordinated_universal_time_offset;
      hour_offset          : INTEGER;
      minute_offset        : OPTIONAL INTEGER;
      sense                : ahead_or_behind;
    DERIVE
      actual_minute_offset : INTEGER := NVL(minute_offset,0);
  END_ENTITY;

  ENTITY csg_solid
    SUBTYPE OF(solid_model);
      tree_root_expression : csg_select;
  END_ENTITY;

  ENTITY curve
    SUPERTYPE OF (ONEOF(line, conic, clothoid, circular_involute, pcurve, surface_curve, offset_curve_2d, offset_curve_3d, curve_replica) ANDOR bounded_curve)
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY curve_bounded_surface
    SUBTYPE OF(bounded_surface);
      basis_surface  : surface;
      boundaries     : SET [1:?] OF boundary_curve;
      implicit_outer : BOOLEAN;
  END_ENTITY;

  ENTITY curve_replica
    SUBTYPE OF(curve);
      parent_curve   : curve;
      transformation : cartesian_transformation_operator;
  END_ENTITY;

  ENTITY cyclide_segment_solid
    SUBTYPE OF(geometric_representation_item);
      position    : axis2_placement_3d;
      radius1     : positive_length_measure;
      radius2     : positive_length_measure;
      cone_angle1 : plane_angle_measure;
      cone_angle2 : plane_angle_measure;
      turn_angle  : plane_angle_measure;
  END_ENTITY;

  ENTITY cylindrical_point
    SUBTYPE OF(cartesian_point);
      r                                : length_measure;
      theta                            : plane_angle_measure;
      z                                : length_measure;
    DERIVE
      SELF\cartesian_point.coordinates : LIST [1:3] OF length_measure := 
                                         [r*cos(theta), r*sin(theta), z];
  END_ENTITY;

  ENTITY cylindrical_surface
    SUBTYPE OF(elementary_surface);
      radius : positive_length_measure;
  END_ENTITY;

  ENTITY cylindrical_volume
    SUBTYPE OF(volume);
      position : axis2_placement_3d;
      radius   : positive_length_measure;
      height   : positive_length_measure;
  END_ENTITY;

  ENTITY data_environment;
      name        : label;
      description : text;
      elements    : SET [1:?] OF property_definition_representation;
  END_ENTITY;

  ENTITY data_environment_relationship;
      name                      : label;
      description               : text;
      relating_data_environment : data_environment;
      related_data_environment  : data_environment;
  END_ENTITY;

  ENTITY date
    SUPERTYPE OF (ONEOF(calendar_date, ordinal_date, week_of_year_and_day_date));
      year_component : year_number;
  END_ENTITY;

  ENTITY date_and_time;
      date_component : date;
      time_component : local_time;
  END_ENTITY;

  ENTITY date_and_time_assignment
    ABSTRACT;
      assigned_date_and_time : date_and_time;
      role                   : date_time_role;
  END_ENTITY;

  ENTITY date_assignment
    ABSTRACT;
      assigned_date : date;
      role          : date_role;
  END_ENTITY;

  ENTITY date_role;
      name        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY date_time_role;
      name        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY dated_effectivity
    SUBTYPE OF(effectivity);
      effectivity_end_date   : OPTIONAL date_time_or_event_occurrence;
      effectivity_start_date : date_time_or_event_occurrence;
  END_ENTITY;

  ENTITY datum
    SUBTYPE OF(shape_aspect);
      identification               : identifier;
    INVERSE
      established_by_relationships : SET [1:?] OF shape_aspect_relationship FOR related_shape_aspect;
  END_ENTITY;

  ENTITY datum_feature
    SUBTYPE OF(shape_aspect);
    INVERSE
      feature_basis_relationship : shape_aspect_relationship FOR relating_shape_aspect;
  END_ENTITY;

  ENTITY datum_reference;
      precedence       : INTEGER;
      referenced_datum : datum;
  END_ENTITY;

  ENTITY datum_target
    SUBTYPE OF(shape_aspect);
      target_id                 : identifier;
    INVERSE
      target_basis_relationship : shape_aspect_relationship FOR relating_shape_aspect;
  END_ENTITY;

  ENTITY definitional_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY degenerate_pcurve
    SUBTYPE OF(point);
      basis_surface      : surface;
      reference_to_curve : definitional_representation;
  END_ENTITY;

  ENTITY degenerate_toroidal_surface
    SUBTYPE OF(toroidal_surface);
      select_outer : BOOLEAN;
  END_ENTITY;

  ENTITY derived_shape_aspect
    SUPERTYPE OF (ONEOF(apex, centre_of_symmetry, geometric_alignment, geometric_intersection, parallel_offset, perpendicular_to, extension, tangent))
    SUBTYPE OF(shape_aspect);
    INVERSE
      deriving_relationships : SET [1:?] OF shape_aspect_relationship FOR relating_shape_aspect;
  END_ENTITY;

  ENTITY derived_unit;
      elements : SET [1:?] OF derived_unit_element;
    DERIVE
      name     : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY derived_unit_element;
      unit     : named_unit;
      exponent : REAL;
  END_ENTITY;

  ENTITY description_attribute;
      attribute_value : text;
      described_item  : description_attribute_select;
  END_ENTITY;

  ENTITY descriptive_representation_item
    SUBTYPE OF(representation_item);
      description : text;
  END_ENTITY;

  ENTITY dimension_related_tolerance_zone_element;
      related_dimension : dimensional_location;
      related_element   : tolerance_zone_definition;
  END_ENTITY;

  ENTITY dimensional_characteristic_representation;
      dimension      : dimensional_characteristic;
      representation : shape_dimension_representation;
  END_ENTITY;

  ENTITY dimensional_exponents;
      length_exponent                    : REAL;
      mass_exponent                      : REAL;
      time_exponent                      : REAL;
      electric_current_exponent          : REAL;
      thermodynamic_temperature_exponent : REAL;
      amount_of_substance_exponent       : REAL;
      luminous_intensity_exponent        : REAL;
  END_ENTITY;

  ENTITY dimensional_location
    SUPERTYPE OF (ONEOF(angular_location, dimensional_location_with_path) ANDOR directed_dimensional_location)
    SUBTYPE OF(shape_aspect_relationship);
  END_ENTITY;

  ENTITY dimensional_location_with_path
    SUBTYPE OF(dimensional_location);
      path : shape_aspect;
  END_ENTITY;

  ENTITY dimensional_size
    SUPERTYPE OF (ONEOF(angular_size, dimensional_size_with_path) ANDOR externally_defined_dimension_definition);
      applies_to : shape_aspect;
      name       : label;
  END_ENTITY;

  ENTITY dimensional_size_with_path
    SUBTYPE OF(dimensional_size);
      path : shape_aspect;
  END_ENTITY;

  ENTITY directed_action
    SUBTYPE OF(executed_action);
      directive : action_directive;
  END_ENTITY;

  ENTITY directed_dimensional_location
    SUBTYPE OF(dimensional_location);
  END_ENTITY;

  ENTITY direction
    SUBTYPE OF(geometric_representation_item);
      direction_ratios : LIST [2:3] OF REAL;
  END_ENTITY;

  ENTITY document;
      id                   : identifier;
      name                 : label;
      description          : OPTIONAL text;
      kind                 : document_type;
    INVERSE
      representation_types : SET OF document_representation_type FOR represented_document;
  END_ENTITY;

  ENTITY document_file
    SUBTYPE OF(document, characterized_object);
  END_ENTITY;

  ENTITY document_product_association;
      name              : label;
      description       : OPTIONAL text;
      relating_document : document;
      related_product   : product_or_formation_or_definition;
  END_ENTITY;

  ENTITY document_product_equivalence
    SUBTYPE OF(document_product_association);
  END_ENTITY;

  ENTITY document_reference
    ABSTRACT;
      assigned_document : document;
      source            : label;
    DERIVE
      role              : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY document_relationship;
      name              : label;
      description       : OPTIONAL text;
      relating_document : document;
      related_document  : document;
  END_ENTITY;

  ENTITY document_representation_type;
      name                 : label;
      represented_document : document;
  END_ENTITY;

  ENTITY document_type;
      product_data_type : label;
  END_ENTITY;

  ENTITY document_usage_constraint;
      source                : document;
      subject_element       : label;
      subject_element_value : text;
  END_ENTITY;

  ENTITY document_usage_constraint_assignment
    ABSTRACT;
      assigned_document_usage : document_usage_constraint;
      role                    : document_usage_role;
  END_ENTITY;

  ENTITY document_usage_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY document_with_class
    SUBTYPE OF(document);
      class : identifier;
  END_ENTITY;

  ENTITY dupin_cyclide_surface
    SUBTYPE OF(elementary_surface);
      generalised_major_radius : positive_length_measure;
      generalised_minor_radius : positive_length_measure;
      skewness                 : length_measure;
  END_ENTITY;

  ENTITY eccentric_cone
    SUBTYPE OF(geometric_representation_item);
      position    : axis2_placement_3d;
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
      height      : positive_length_measure;
      x_offset    : length_measure;
      y_offset    : length_measure;
      ratio       : REAL;
  END_ENTITY;

  ENTITY eccentric_conical_volume
    SUBTYPE OF(volume);
      position    : axis2_placement_3d;
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
      height      : positive_length_measure;
      x_offset    : length_measure;
      y_offset    : length_measure;
      ratio       : REAL;
  END_ENTITY;

  ENTITY edge
    SUPERTYPE OF (ONEOF(edge_curve, oriented_edge, subedge))
    SUBTYPE OF(topological_representation_item);
      edge_start : vertex;
      edge_end   : vertex;
  END_ENTITY;

  ENTITY edge_based_wireframe_model
    SUBTYPE OF(geometric_representation_item);
      ebwm_boundary : SET [1:?] OF connected_edge_set;
  END_ENTITY;

  ENTITY edge_curve
    SUBTYPE OF(edge, geometric_representation_item);
      edge_geometry : curve;
      same_sense    : BOOLEAN;
  END_ENTITY;

  ENTITY edge_loop
    SUBTYPE OF(loop, path);
    DERIVE
      ne : INTEGER := SIZEOF(SELF\path.edge_list);
  END_ENTITY;

  ENTITY effectivity
    SUPERTYPE OF (ONEOF(serial_numbered_effectivity, dated_effectivity, lot_effectivity, time_interval_based_effectivity) ANDOR product_definition_effectivity);
      id          : identifier;
    DERIVE
      name        : label := get_name_value(SELF);
      description : text := get_description_value(SELF);
  END_ENTITY;

  ENTITY effectivity_assignment
    ABSTRACT;
      assigned_effectivity : effectivity;
    DERIVE
      role                 : object_role := get_role(SELF);
  END_ENTITY;

  ENTITY effectivity_context_assignment
    ABSTRACT;
      assigned_effectivity_assignment : effectivity_assignment;
      role                            : effectivity_context_role;
  END_ENTITY;

  ENTITY effectivity_context_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY effectivity_relationship;
      name                 : label;
      description          : OPTIONAL text;
      related_effectivity  : effectivity;
      relating_effectivity : effectivity;
  END_ENTITY;

  ENTITY electric_current_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY electric_current_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY elementary_surface
    SUPERTYPE OF (ONEOF(plane, cylindrical_surface, conical_surface, spherical_surface, toroidal_surface) ANDOR dupin_cyclide_surface)
    SUBTYPE OF(surface);
      position : axis2_placement_3d;
  END_ENTITY;

  ENTITY ellipse
    SUBTYPE OF(conic);
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
  END_ENTITY;

  ENTITY ellipsoid
    SUBTYPE OF(geometric_representation_item);
      position    : axis2_placement_3d;
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
      semi_axis_3 : positive_length_measure;
  END_ENTITY;

  ENTITY ellipsoid_volume
    SUBTYPE OF(volume);
      position    : axis2_placement_3d;
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
      semi_axis_3 : positive_length_measure;
  END_ENTITY;

  ENTITY elliptic_area
    SUBTYPE OF(primitive_2d);
      position    : axis2_placement_2d;
      semi_axis_1 : positive_length_measure;
      semi_axis_2 : positive_length_measure;
  END_ENTITY;

  ENTITY evaluated_degenerate_pcurve
    SUBTYPE OF(degenerate_pcurve);
      equivalent_point : cartesian_point;
  END_ENTITY;

  ENTITY event_occurrence;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY event_occurrence_assignment
    ABSTRACT;
      assigned_event_occurrence : event_occurrence;
      role                      : event_occurrence_role;
  END_ENTITY;

  ENTITY event_occurrence_context_assignment
    ABSTRACT;
      assigned_event_occurrence_assignment : event_occurrence_assignment;
      role                                 : event_occurrence_context_role;
  END_ENTITY;

  ENTITY event_occurrence_context_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY event_occurrence_relationship;
      name           : label;
      description    : OPTIONAL text;
      relating_event : event_occurrence;
      related_event  : event_occurrence;
  END_ENTITY;

  ENTITY event_occurrence_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY exclusive_product_concept_feature_category
    SUBTYPE OF(product_concept_feature_category);
  END_ENTITY;

  ENTITY executed_action
    SUBTYPE OF(action);
  END_ENTITY;

  ENTITY expanded_uncertainty
    SUBTYPE OF(standard_uncertainty);
      coverage_factor : REAL;
  END_ENTITY;

  ENTITY experience;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY experience_assignment
    ABSTRACT;
      id                  : identifier;
      name                : label;
      description         : OPTIONAL text;
      assigned_experience : experience;
      role                : experience_role;
  END_ENTITY;

  ENTITY experience_relationship;
      id                  : identifier;
      name                : label;
      description         : OPTIONAL text;
      relating_experience : experience;
      related_experience  : experience;
  END_ENTITY;

  ENTITY experience_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY experience_type;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY experience_type_assignment
    ABSTRACT;
      id                       : identifier;
      name                     : label;
      description              : OPTIONAL text;
      assigned_experience_type : experience_type;
      role                     : experience_type_role;
  END_ENTITY;

  ENTITY experience_type_relationship;
      id                       : identifier;
      name                     : label;
      description              : OPTIONAL text;
      relating_experience_type : experience_type;
      related_experience_type  : experience_type;
  END_ENTITY;

  ENTITY experience_type_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY extension
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY external_class_library
    SUBTYPE OF(external_source);
  END_ENTITY;

  ENTITY external_identification_assignment
    ABSTRACT
    SUBTYPE OF(identification_assignment);
      source : external_source;
  END_ENTITY;

  ENTITY external_referent_assignment
    ABSTRACT;
      assigned_name : label;
    DERIVE
      role          : object_role := get_role(SELF);
    UNIQUE
      UR1 : assigned_name;
  END_ENTITY;

  ENTITY external_source;
      source_id   : source_item;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY external_source_relationship;
      name            : label;
      description     : OPTIONAL text;
      relating_source : external_source;
      related_source  : external_source;
  END_ENTITY;

  ENTITY externally_defined_class
    SUBTYPE OF(class, externally_defined_item);
  END_ENTITY;

  ENTITY externally_defined_dimension_definition
    SUBTYPE OF(dimensional_size, externally_defined_item);
  END_ENTITY;

  ENTITY externally_defined_general_property
    SUBTYPE OF(general_property, externally_defined_item);
  END_ENTITY;

  ENTITY externally_defined_item;
      item_id : source_item;
      source  : external_source;
  END_ENTITY;

  ENTITY externally_defined_item_relationship;
      name          : label;
      description   : OPTIONAL text;
      relating_item : externally_defined_item;
      related_item  : externally_defined_item;
  END_ENTITY;

  ENTITY extruded_area_solid
    SUBTYPE OF(swept_area_solid);
      extruded_direction : direction;
      depth              : positive_length_measure;
  END_ENTITY;

  ENTITY extruded_face_solid
    SUBTYPE OF(swept_face_solid);
      extruded_direction : direction;
      depth              : positive_length_measure;
  END_ENTITY;

  ENTITY face
    SUPERTYPE OF (ONEOF(face_surface, subface, oriented_face))
    SUBTYPE OF(topological_representation_item);
      bounds : SET [1:?] OF face_bound;
  END_ENTITY;

  ENTITY face_based_surface_model
    SUBTYPE OF(geometric_representation_item);
      fbsm_faces : SET [1:?] OF connected_face_set;
  END_ENTITY;

  ENTITY face_bound
    SUBTYPE OF(topological_representation_item);
      bound       : loop;
      orientation : BOOLEAN;
  END_ENTITY;

  ENTITY face_outer_bound
    SUBTYPE OF(face_bound);
  END_ENTITY;

  ENTITY face_surface
    SUBTYPE OF(face, geometric_representation_item);
      face_geometry : surface;
      same_sense    : BOOLEAN;
  END_ENTITY;

  ENTITY faceted_brep
    SUBTYPE OF(manifold_solid_brep);
  END_ENTITY;

  ENTITY faceted_primitive
    SUPERTYPE OF (ONEOF(tetrahedron, convex_hexahedron))
    SUBTYPE OF(geometric_representation_item);
      points : LIST [4:?] OF cartesian_point;
  END_ENTITY;

  ENTITY fixed_reference_swept_surface
    SUBTYPE OF(swept_surface);
      directrix       : curve;
      fixed_reference : direction;
  END_ENTITY;

  ENTITY founded_item;
  END_ENTITY;

  ENTITY functional_breakdown_context
    SUBTYPE OF(breakdown_context);
  END_ENTITY;

  ENTITY functional_element_usage
    SUBTYPE OF(breakdown_element_usage);
  END_ENTITY;

  ENTITY functionally_defined_transformation;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY general_material_property
    SUBTYPE OF(general_property);
  END_ENTITY;

  ENTITY general_property;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY general_property_association;
      name               : label;
      description        : OPTIONAL text;
      base_definition    : general_property;
      derived_definition : derived_property_select;
  END_ENTITY;

  ENTITY general_property_relationship;
      name              : label;
      description       : OPTIONAL text;
      relating_property : general_property;
      related_property  : general_property;
  END_ENTITY;

  ENTITY geometric_alignment
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY geometric_curve_set
    SUBTYPE OF(geometric_set);
  END_ENTITY;

  ENTITY geometric_intersection
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY geometric_representation_context
    SUBTYPE OF(representation_context);
      coordinate_space_dimension : dimension_count;
  END_ENTITY;

  ENTITY geometric_representation_item
    SUPERTYPE OF (ONEOF(point, direction, vector, placement, cartesian_transformation_operator, curve, surface, edge_curve, face_surface, poly_loop, vertex_point, solid_model, boolean_result, sphere, right_circular_cone, right_circular_cylinder, torus, block, primitive_2d, right_angular_wedge, ellipsoid, faceted_primitive, rectangular_pyramid, cyclide_segment_solid, volume, half_space_solid, half_space_2d, shell_based_surface_model, face_based_surface_model, shell_based_wireframe_model, edge_based_wireframe_model, geometric_set) ANDOR eccentric_cone)
    SUBTYPE OF(representation_item);
    DERIVE
      dim : dimension_count := dimension_of(SELF);
  END_ENTITY;

  ENTITY geometric_set
    SUPERTYPE OF (ONEOF(geometric_curve_set, geometric_set_replica))
    SUBTYPE OF(geometric_representation_item);
      elements : SET [1:?] OF geometric_set_select;
  END_ENTITY;

  ENTITY geometric_set_replica
    SUBTYPE OF(geometric_set);
      parent_set                  : geometric_set;
      transformation              : cartesian_transformation_operator;
    DERIVE
      SELF\geometric_set.elements : SET [1:?] OF geometric_set_select := 
                                    build_transformed_set(transformation, parent_set);
  END_ENTITY;

  ENTITY geometric_tolerance;
      name                    : label;
      description             : text;
      magnitude               : measure_with_unit;
      toleranced_shape_aspect : shape_aspect;
  END_ENTITY;

  ENTITY geometric_tolerance_relationship;
      name                         : label;
      description                  : text;
      relating_geometric_tolerance : geometric_tolerance;
      related_geometric_tolerance  : geometric_tolerance;
  END_ENTITY;

  ENTITY geometric_tolerance_with_datum_reference
    SUBTYPE OF(geometric_tolerance);
      datum_system : SET [1:?] OF datum_reference;
  END_ENTITY;

  ENTITY geometric_tolerance_with_defined_unit
    SUBTYPE OF(geometric_tolerance);
      unit_size : measure_with_unit;
  END_ENTITY;

  ENTITY geometrically_bounded_2d_wireframe_representation
    SUBTYPE OF(shape_representation);
  END_ENTITY;

  ENTITY global_uncertainty_assigned_context
    SUBTYPE OF(representation_context);
      uncertainty : SET [1:?] OF uncertainty_measure_with_unit;
  END_ENTITY;

  ENTITY global_unit_assigned_context
    SUBTYPE OF(representation_context);
      units : SET [1:?] OF unit;
  END_ENTITY;

  ENTITY group;
      name        : label;
      description : OPTIONAL text;
    DERIVE
      id          : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY group_assignment
    ABSTRACT;
      assigned_group : group;
    DERIVE
      role           : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY group_relationship;
      name           : label;
      description    : OPTIONAL text;
      relating_group : group;
      related_group  : group;
  END_ENTITY;

  ENTITY half_space_2d
    SUBTYPE OF(geometric_representation_item);
      base_curve     : curve;
      agreement_flag : BOOLEAN;
  END_ENTITY;

  ENTITY half_space_solid
    SUBTYPE OF(geometric_representation_item);
      base_surface   : surface;
      agreement_flag : BOOLEAN;
  END_ENTITY;

  ENTITY hardness_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY hexahedron_volume
    SUBTYPE OF(volume);
      points : LIST [8:8] OF cartesian_point;
  END_ENTITY;

  ENTITY hyperbola
    SUBTYPE OF(conic);
      semi_axis      : positive_length_measure;
      semi_imag_axis : positive_length_measure;
  END_ENTITY;

  ENTITY id_attribute;
      attribute_value : identifier;
      identified_item : id_attribute_select;
  END_ENTITY;

  ENTITY identification_assignment
    ABSTRACT;
      assigned_id : identifier;
      role        : identification_role;
  END_ENTITY;

  ENTITY identification_assignment_relationship;
      name                               : label;
      description                        : OPTIONAL text;
      relating_identification_assignment : identification_assignment;
      related_identification_assignment  : identification_assignment;
  END_ENTITY;

  ENTITY identification_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY inclusion_product_concept_feature
    SUBTYPE OF(conditional_concept_feature);
  END_ENTITY;

  ENTITY instance_usage_context_assignment
    SUBTYPE OF(product_definition_context);
      items : SET [1:?] OF instance_usage_context_select;
  END_ENTITY;

  ENTITY intersection_curve
    SUBTYPE OF(surface_curve);
  END_ENTITY;

  ENTITY item_defined_transformation;
      name             : label;
      description      : OPTIONAL text;
      transform_item_1 : representation_item;
      transform_item_2 : representation_item;
  END_ENTITY;

  ENTITY item_identified_representation_usage;
      name                : label;
      description         : OPTIONAL text;
      definition          : represented_definition;
      used_representation : representation;
      identified_item     : representation_item;
  END_ENTITY;

  ENTITY known_source
    SUBTYPE OF(external_source, pre_defined_item);
  END_ENTITY;

  ENTITY language
    SUBTYPE OF(group);
  END_ENTITY;

  ENTITY length_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY length_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY library_assignment
    ABSTRACT
    SUBTYPE OF(external_referent_assignment);
      frame_of_reference : library_context;
    UNIQUE
      UR1 : frame_of_reference;
  END_ENTITY;

  ENTITY library_context
    SUBTYPE OF(application_context_element);
      library_reference : label;
  END_ENTITY;

  ENTITY limits_and_fits;
      form_variance : label;
      zone_variance : label;
      grade         : label;
      source        : text;
  END_ENTITY;

  ENTITY line
    SUBTYPE OF(curve);
      pnt : cartesian_point;
      dir : vector;
  END_ENTITY;

  ENTITY local_time;
      hour_component   : hour_in_day;
      minute_component : OPTIONAL minute_in_hour;
      second_component : OPTIONAL second_in_minute;
      zone             : coordinated_universal_time_offset;
  END_ENTITY;

  ENTITY location;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY location_assignment
    ABSTRACT;
      id                : identifier;
      name              : label;
      description       : OPTIONAL text;
      assigned_location : location;
      role              : location_role;
  END_ENTITY;

  ENTITY location_relationship;
      id                : identifier;
      name              : label;
      description       : OPTIONAL text;
      relating_location : location;
      related_location  : location;
  END_ENTITY;

  ENTITY location_representation_assignment
    ABSTRACT;
      id                   : identifier;
      name                 : label;
      description          : OPTIONAL text;
      represented_location : location;
      role                 : location_representation_role;
  END_ENTITY;

  ENTITY location_representation_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY location_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY loop
    SUPERTYPE OF (ONEOF(vertex_loop, edge_loop, poly_loop))
    SUBTYPE OF(topological_representation_item);
  END_ENTITY;

  ENTITY lot_effectivity
    SUBTYPE OF(effectivity);
      effectivity_lot_id   : identifier;
      effectivity_lot_size : measure_with_unit;
  END_ENTITY;

  ENTITY luminous_intensity_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY luminous_intensity_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY make_from_usage_option
    SUBTYPE OF(product_definition_usage);
      ranking           : INTEGER;
      ranking_rationale : text;
      quantity          : measure_with_unit;
  END_ENTITY;

  ENTITY make_from_usage_option_group;
      members : SET [2:?] OF make_from_usage_option;
  END_ENTITY;

  ENTITY manifold_solid_brep
    SUBTYPE OF(solid_model);
      outer : closed_shell;
  END_ENTITY;

  ENTITY mapped_item
    SUBTYPE OF(representation_item);
      mapping_source : representation_map;
      mapping_target : representation_item;
  END_ENTITY;

  ENTITY mass_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY mass_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY material_designation;
      name        : label;
      definitions : SET [1:?] OF characterized_definition;
  END_ENTITY;

  ENTITY material_designation_characterization;
      name        : label;
      description : text;
      designation : material_designation;
      property    : characterized_material_property;
  END_ENTITY;

  ENTITY material_property
    SUBTYPE OF(property_definition);
  END_ENTITY;

  ENTITY material_property_representation
    SUBTYPE OF(property_definition_representation);
      dependent_environment : data_environment;
  END_ENTITY;

  ENTITY measure_qualification;
      name              : label;
      description       : text;
      qualified_measure : measure_with_unit;
      qualifiers        : SET [1:?] OF value_qualifier;
  END_ENTITY;

  ENTITY measure_representation_item
    SUBTYPE OF(representation_item, measure_with_unit);
  END_ENTITY;

  ENTITY measure_with_unit
    SUPERTYPE OF (ONEOF(length_measure_with_unit, mass_measure_with_unit, time_measure_with_unit, electric_current_measure_with_unit, thermodynamic_temperature_measure_with_unit, celsius_temperature_measure_with_unit, amount_of_substance_measure_with_unit, luminous_intensity_measure_with_unit, plane_angle_measure_with_unit, solid_angle_measure_with_unit, area_measure_with_unit, volume_measure_with_unit, ratio_measure_with_unit) ANDOR uncertainty_measure_with_unit ANDOR measure_representation_item);
      value_component : measure_value;
      unit_component  : unit;
  END_ENTITY;

  ENTITY modified_geometric_tolerance
    SUBTYPE OF(geometric_tolerance);
      modifier : limit_condition;
  END_ENTITY;

  ENTITY moments_of_inertia_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY multi_language_attribute_assignment
    SUBTYPE OF(attribute_value_assignment);
      items                : SET [1:?] OF multi_language_attribute_item;
    DERIVE
      translation_language : language := language_indication[1]\attribute_classification_assignment.assigned_class;
    INVERSE
      language_indication  : SET [1:1] OF attribute_language_assignment FOR items;
  END_ENTITY;

  ENTITY name_assignment
    ABSTRACT;
      assigned_name : label;
    DERIVE
      role          : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY name_attribute;
      attribute_value : label;
      named_item      : name_attribute_select;
  END_ENTITY;

  ENTITY named_unit
    SUPERTYPE OF (ONEOF(si_unit, conversion_based_unit, context_dependent_unit) ANDOR ONEOF(length_unit, mass_unit, time_unit, electric_current_unit, thermodynamic_temperature_unit, amount_of_substance_unit, luminous_intensity_unit, plane_angle_unit, solid_angle_unit, area_unit, volume_unit, ratio_unit));
      dimensions : dimensional_exponents;
  END_ENTITY;

  ENTITY next_assembly_usage_occurrence
    SUBTYPE OF(assembly_component_usage);
  END_ENTITY;

  ENTITY object_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY offset_curve_2d
    SUBTYPE OF(curve);
      basis_curve    : curve;
      distance       : length_measure;
      self_intersect : LOGICAL;
  END_ENTITY;

  ENTITY offset_curve_3d
    SUBTYPE OF(curve);
      basis_curve    : curve;
      distance       : length_measure;
      self_intersect : LOGICAL;
      ref_direction  : direction;
  END_ENTITY;

  ENTITY offset_surface
    SUBTYPE OF(surface);
      basis_surface  : surface;
      distance       : length_measure;
      self_intersect : LOGICAL;
  END_ENTITY;

  ENTITY open_path
    SUBTYPE OF(path);
    DERIVE
      ne : INTEGER := SIZEOF(SELF\path.edge_list);
  END_ENTITY;

  ENTITY open_shell
    SUBTYPE OF(connected_face_set);
  END_ENTITY;

  ENTITY ordinal_date
    SUBTYPE OF(date);
      day_component : day_in_year_number;
  END_ENTITY;

  ENTITY organization;
      id          : OPTIONAL identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY organization_assignment
    ABSTRACT;
      assigned_organization : organization;
      role                  : organization_role;
  END_ENTITY;

  ENTITY organization_relationship;
      name                  : label;
      description           : OPTIONAL text;
      relating_organization : organization;
      related_organization  : organization;
  END_ENTITY;

  ENTITY organization_role;
      name        : label;
    DERIVE
      description : text := get_description_value(SELF);
  END_ENTITY;

  ENTITY organization_type;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY organization_type_assignment
    ABSTRACT;
      id                         : identifier;
      name                       : label;
      description                : OPTIONAL text;
      assigned_organization_type : organization_type;
      role                       : organization_type_role;
  END_ENTITY;

  ENTITY organization_type_relationship;
      id                         : identifier;
      name                       : label;
      description                : OPTIONAL text;
      relating_organization_type : organization_type;
      related_organization_type  : organization_type;
  END_ENTITY;

  ENTITY organization_type_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY organizational_address
    SUBTYPE OF(address);
      organizations : SET [1:?] OF organization;
      description   : OPTIONAL text;
  END_ENTITY;

  ENTITY organizational_project;
      name                      : label;
      description               : OPTIONAL text;
      responsible_organizations : SET [1:?] OF organization;
    DERIVE
      id                        : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY organizational_project_assignment
    ABSTRACT;
      assigned_organizational_project : organizational_project;
      role                            : organizational_project_role;
  END_ENTITY;

  ENTITY organizational_project_relationship;
      name                            : label;
      description                     : OPTIONAL text;
      relating_organizational_project : organizational_project;
      related_organizational_project  : organizational_project;
  END_ENTITY;

  ENTITY organizational_project_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY oriented_closed_shell
    SUBTYPE OF(closed_shell);
      closed_shell_element              : closed_shell;
      orientation                       : BOOLEAN;
    DERIVE
      SELF\connected_face_set.cfs_faces : SET [1:?] OF face := conditional_reverse(SELF.orientation,
                                          SELF.closed_shell_element.cfs_faces);
  END_ENTITY;

  ENTITY oriented_edge
    SUBTYPE OF(edge);
      edge_element         : edge;
      orientation          : BOOLEAN;
    DERIVE
      SELF\edge.edge_start : vertex := boolean_choose (SELF.orientation,
                             SELF.edge_element.edge_start,
                             SELF.edge_element.edge_end);
      SELF\edge.edge_end   : vertex := boolean_choose (SELF.orientation,
                             SELF.edge_element.edge_end,
                             SELF.edge_element.edge_start);
  END_ENTITY;

  ENTITY oriented_face
    SUBTYPE OF(face);
      face_element     : face;
      orientation      : BOOLEAN;
    DERIVE
      SELF\face.bounds : SET [1:?] OF face_bound := conditional_reverse(SELF.orientation,SELF.face_element.bounds);
  END_ENTITY;

  ENTITY oriented_open_shell
    SUBTYPE OF(open_shell);
      open_shell_element                : open_shell;
      orientation                       : BOOLEAN;
    DERIVE
      SELF\connected_face_set.cfs_faces : SET [1:?] OF face := conditional_reverse(SELF.orientation,
                                          SELF.open_shell_element.cfs_faces);
  END_ENTITY;

  ENTITY oriented_path
    SUBTYPE OF(path);
      path_element        : path;
      orientation         : BOOLEAN;
    DERIVE
      SELF\path.edge_list : LIST [1:?] OF oriented_edge := conditional_reverse(SELF.orientation,
                            SELF.path_element.edge_list);
  END_ENTITY;

  ENTITY oriented_surface
    SUBTYPE OF(surface);
      orientation : BOOLEAN;
  END_ENTITY;

  ENTITY outer_boundary_curve
    SUBTYPE OF(boundary_curve);
  END_ENTITY;

  ENTITY package_product_concept_feature
    SUBTYPE OF(product_concept_feature);
  END_ENTITY;

  ENTITY parabola
    SUBTYPE OF(conic);
      focal_dist : length_measure;
  END_ENTITY;

  ENTITY parallel_offset
    SUBTYPE OF(derived_shape_aspect);
      offset : measure_with_unit;
  END_ENTITY;

  ENTITY parametric_representation_context
    SUBTYPE OF(representation_context);
  END_ENTITY;

  ENTITY path
    SUPERTYPE OF (ONEOF(open_path, edge_loop, oriented_path))
    SUBTYPE OF(topological_representation_item);
      edge_list : LIST [1:?] OF oriented_edge;
  END_ENTITY;

  ENTITY pcurve
    SUBTYPE OF(curve);
      basis_surface      : surface;
      reference_to_curve : definitional_representation;
  END_ENTITY;

  ENTITY perpendicular_to
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY person;
      id            : identifier;
      last_name     : OPTIONAL label;
      first_name    : OPTIONAL label;
      middle_names  : OPTIONAL LIST [1:?] OF label;
      prefix_titles : OPTIONAL LIST [1:?] OF label;
      suffix_titles : OPTIONAL LIST [1:?] OF label;
  END_ENTITY;

  ENTITY person_and_organization;
      the_person       : person;
      the_organization : organization;
    DERIVE
      name             : label := get_name_value (SELF);
      description      : text := get_description_value(SELF);
  END_ENTITY;

  ENTITY person_and_organization_address
    SUBTYPE OF(organizational_address, personal_address);
      SELF\organizational_address.organizations : SET [1:1] OF organization;
      SELF\personal_address.people              : SET [1:1] OF person;
  END_ENTITY;

  ENTITY person_and_organization_assignment
    ABSTRACT;
      assigned_person_and_organization : person_and_organization;
      role                             : person_and_organization_role;
  END_ENTITY;

  ENTITY person_and_organization_role;
      name        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY person_assignment
    ABSTRACT;
      assigned_person : person;
      role            : person_role;
  END_ENTITY;

  ENTITY person_role;
      name        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY person_type;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY person_type_assignment
    ABSTRACT;
      id                   : identifier;
      name                 : label;
      description          : OPTIONAL text;
      assigned_person_type : person_type;
      role                 : person_type_role;
  END_ENTITY;

  ENTITY person_type_definition;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
      formation   : person_type_definition_formation;
  END_ENTITY;

  ENTITY person_type_definition_assignment
    ABSTRACT;
      id                              : identifier;
      name                            : label;
      description                     : OPTIONAL text;
      assigned_person_type_definition : person_type_definition;
      role                            : person_type_definition_role;
  END_ENTITY;

  ENTITY person_type_definition_formation;
      id             : identifier;
      name           : label;
      description    : OPTIONAL text;
      of_person_type : person_type;
  END_ENTITY;

  ENTITY person_type_definition_relationship;
      id                              : identifier;
      name                            : label;
      description                     : OPTIONAL text;
      relating_person_type_definition : person_type_definition;
      related_person_type_definition  : person_type_definition;
  END_ENTITY;

  ENTITY person_type_definition_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY person_type_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY personal_address
    SUBTYPE OF(address);
      people      : SET [1:?] OF person;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY physical_breakdown_context
    SUBTYPE OF(breakdown_context);
  END_ENTITY;

  ENTITY physical_element_usage
    SUBTYPE OF(breakdown_element_usage);
  END_ENTITY;

  ENTITY physically_modelled_product_definition
    SUBTYPE OF(product_definition);
  END_ENTITY;

  ENTITY placement
    SUPERTYPE OF (ONEOF(axis1_placement, axis2_placement_2d, axis2_placement_3d))
    SUBTYPE OF(geometric_representation_item);
      location : cartesian_point;
  END_ENTITY;

  ENTITY plane
    SUBTYPE OF(elementary_surface);
  END_ENTITY;

  ENTITY plane_angle_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY plane_angle_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY plus_minus_tolerance;
      range                : tolerance_method_definition;
      toleranced_dimension : dimensional_characteristic;
    UNIQUE
      UR1 : toleranced_dimension;
  END_ENTITY;

  ENTITY point
    SUPERTYPE OF (ONEOF(cartesian_point, point_on_curve, point_on_surface, point_in_volume, point_replica, degenerate_pcurve))
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY point_in_volume
    SUBTYPE OF(point);
      basis_volume      : volume;
      point_parameter_u : parameter_value;
      point_parameter_v : parameter_value;
      point_parameter_w : parameter_value;
  END_ENTITY;

  ENTITY point_on_curve
    SUBTYPE OF(point);
      basis_curve     : curve;
      point_parameter : parameter_value;
  END_ENTITY;

  ENTITY point_on_surface
    SUBTYPE OF(point);
      basis_surface     : surface;
      point_parameter_u : parameter_value;
      point_parameter_v : parameter_value;
  END_ENTITY;

  ENTITY point_replica
    SUBTYPE OF(point);
      parent_pt      : point;
      transformation : cartesian_transformation_operator;
  END_ENTITY;

  ENTITY polar_point
    SUBTYPE OF(cartesian_point);
      r                                : length_measure;
      theta                            : plane_angle_measure;
    DERIVE
      SELF\cartesian_point.coordinates : LIST [1:3] OF length_measure := 
                                         [r*cos(theta), r*sin(theta)];
  END_ENTITY;

  ENTITY poly_loop
    SUBTYPE OF(loop, geometric_representation_item);
      polygon : LIST [3:?] OF cartesian_point;
  END_ENTITY;

  ENTITY polygonal_area
    SUBTYPE OF(primitive_2d);
      bounds : LIST [3:?] OF cartesian_point;
  END_ENTITY;

  ENTITY polyline
    SUBTYPE OF(bounded_curve);
      points : LIST [2:?] OF cartesian_point;
  END_ENTITY;

  ENTITY position_in_organization;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY position_in_organization_assignment
    ABSTRACT;
      id                                : identifier;
      name                              : label;
      description                       : OPTIONAL text;
      assigned_position_in_organization : position_in_organization;
      role                              : position_in_organization_role;
  END_ENTITY;

  ENTITY position_in_organization_relationship;
      id                                : identifier;
      name                              : label;
      description                       : OPTIONAL text;
      relating_position_in_organization : position_in_organization;
      related_position_in_organization  : position_in_organization;
  END_ENTITY;

  ENTITY position_in_organization_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY position_in_organization_type;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY position_in_organization_type_assignment
    ABSTRACT;
      id                                     : identifier;
      name                                   : label;
      description                            : OPTIONAL text;
      assigned_position_in_organization_type : position_in_organization_type;
      role                                   : position_in_organization_type_role;
  END_ENTITY;

  ENTITY position_in_organization_type_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY pre_defined_item;
      name : label;
  END_ENTITY;

  ENTITY precision_qualifier;
      precision_value : INTEGER;
  END_ENTITY;

  ENTITY primitive_2d
    SUPERTYPE OF (ONEOF(circular_area, elliptic_area, rectangular_area, polygonal_area))
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY process_product_association;
      name            : label;
      description     : text;
      defined_product : characterized_product_definition;
      process         : product_definition_process;
  END_ENTITY;

  ENTITY process_property_association;
      name              : label;
      description       : text;
      process           : property_process;
      property_or_shape : property_or_shape_select;
  END_ENTITY;

  ENTITY product;
      id                 : identifier;
      name               : label;
      description        : OPTIONAL text;
      frame_of_reference : SET [1:?] OF product_context;
  END_ENTITY;

  ENTITY product_as_individual
    SUBTYPE OF(product);
  END_ENTITY;

  ENTITY product_as_individual_version
    ABSTRACT
    SUPERTYPE OF (ONEOF(product_as_planned, product_as_realized))
    SUBTYPE OF(product_definition_formation);
      SELF\product_definition_formation.of_product : product_as_individual;
  END_ENTITY;

  ENTITY product_as_individual_view
    SUBTYPE OF(product_definition);
      SELF\product_definition.defined_version : product_as_individual_version;
  END_ENTITY;

  ENTITY product_as_planned
    SUBTYPE OF(product_as_individual_version);
  END_ENTITY;

  ENTITY product_as_realized
    SUBTYPE OF(product_as_individual_version);
  END_ENTITY;

  ENTITY product_category;
      name        : label;
      description : OPTIONAL text;
    DERIVE
      id          : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY product_category_relationship;
      name         : label;
      description  : OPTIONAL text;
      category     : product_category;
      sub_category : product_category;
  END_ENTITY;

  ENTITY product_class
    SUBTYPE OF(product_concept, characterized_object);
  END_ENTITY;

  ENTITY product_concept;
      id             : identifier;
      name           : label;
      description    : OPTIONAL text;
      market_context : product_concept_context;
    UNIQUE
      UR1 : id;
  END_ENTITY;

  ENTITY product_concept_context
    SUBTYPE OF(application_context_element);
      market_segment_type : label;
  END_ENTITY;

  ENTITY product_concept_feature;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY product_concept_feature_association;
      name        : label;
      description : OPTIONAL text;
      concept     : product_concept;
      feature     : product_concept_feature;
  END_ENTITY;

  ENTITY product_concept_feature_category
    SUBTYPE OF(group);
  END_ENTITY;

  ENTITY product_concept_feature_category_usage
    SUBTYPE OF(group_assignment);
      SELF\group_assignment.assigned_group : product_concept_feature_category;
      items                                : SET [1:?] OF category_usage_item;
  END_ENTITY;

  ENTITY product_concept_relationship;
      name                     : label;
      description              : OPTIONAL text;
      relating_product_concept : product_concept;
      related_product_concept  : product_concept;
  END_ENTITY;

  ENTITY product_context
    SUBTYPE OF(application_context_element);
      discipline_type : label;
  END_ENTITY;

  ENTITY product_definition;
      id                 : identifier;
      description        : OPTIONAL text;
      formation          : product_definition_formation;
      frame_of_reference : product_definition_context;
    DERIVE
      name               : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY product_definition_context
    SUBTYPE OF(application_context_element);
      life_cycle_stage : label;
  END_ENTITY;

  ENTITY product_definition_context_association;
      definition         : product_definition;
      frame_of_reference : product_definition_context;
      role               : product_definition_context_role;
  END_ENTITY;

  ENTITY product_definition_context_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY product_definition_effectivity
    SUBTYPE OF(effectivity);
      usage : product_definition_relationship;
  END_ENTITY;

  ENTITY product_definition_element_relationship
    SUBTYPE OF(group);
  END_ENTITY;

  ENTITY product_definition_formation;
      id          : identifier;
      description : OPTIONAL text;
      of_product  : product;
    UNIQUE
      UR1 : id, of_product;
  END_ENTITY;

  ENTITY product_definition_formation_relationship;
      id                                    : identifier;
      name                                  : label;
      description                           : OPTIONAL text;
      relating_product_definition_formation : product_definition_formation;
      related_product_definition_formation  : product_definition_formation;
  END_ENTITY;

  ENTITY product_definition_formation_with_specified_source
    SUBTYPE OF(product_definition_formation);
      make_or_buy : source;
  END_ENTITY;

  ENTITY product_definition_group_assignment
    SUBTYPE OF(group_assignment);
      SELF\group_assignment.assigned_group : product_definition_element_relationship;
      items                                : SET [1:1] OF product_definition_or_product_definition_relationship;
  END_ENTITY;

  ENTITY product_definition_occurrence_relationship;
      name             : label;
      description      : OPTIONAL text;
      occurrence       : product_definition;
      occurrence_usage : assembly_component_usage;
  END_ENTITY;

  ENTITY product_definition_process
    SUBTYPE OF(action);
      identification      : identifier;
    INVERSE
      product_definitions : SET [1:?] OF process_product_association FOR process;
  END_ENTITY;

  ENTITY product_definition_relationship;
      id                          : identifier;
      name                        : label;
      description                 : OPTIONAL text;
      relating_product_definition : product_definition;
      related_product_definition  : product_definition;
  END_ENTITY;

  ENTITY product_definition_shape
    SUBTYPE OF(property_definition);
    UNIQUE
      UR1 : definition;
  END_ENTITY;

  ENTITY product_definition_substitute;
      description           : OPTIONAL text;
      context_relationship  : product_definition_relationship;
      substitute_definition : product_definition;
    DERIVE
      name                  : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY product_definition_usage
    SUPERTYPE OF (ONEOF(make_from_usage_option, assembly_component_usage))
    SUBTYPE OF(product_definition_relationship);
  END_ENTITY;

  ENTITY product_definition_with_associated_documents
    SUBTYPE OF(product_definition);
      documentation_ids : SET [1:?] OF document;
  END_ENTITY;

  ENTITY product_design_to_individual
    SUBTYPE OF(product_relationship);
      SELF\product_relationship.individual_product : product_as_individual;
      SELF\product_relationship.product_design     : product;
  END_ENTITY;

  ENTITY product_design_version_to_individual
    SUBTYPE OF(product_definition_formation_relationship);
      SELF\product_definition_formation_relationship.individual_product     : product_as_individual_version;
      SELF\product_definition_formation_relationship.product_design_version : product_definition_formation;
  END_ENTITY;

  ENTITY product_identification
    SUBTYPE OF(configuration_item, characterized_object);
      SELF\configuration_item.item_concept : product_class;
  END_ENTITY;

  ENTITY product_material_composition_relationship
    SUBTYPE OF(product_definition_relationship);
      class                : label;
      constituent_amount   : SET [1:?] OF measure_with_unit;
      composition_basis    : label;
      determination_method : text;
  END_ENTITY;

  ENTITY product_planned_to_realized
    SUBTYPE OF(product_definition_formation_relationship);
      SELF\product_definition_formation_relationship.planned_product  : product_as_planned;
      SELF\product_definition_formation_relationship.realized_product : product_as_realized;
  END_ENTITY;

  ENTITY product_related_product_category
    SUBTYPE OF(product_category);
      products : SET [1:?] OF product;
  END_ENTITY;

  ENTITY product_relationship;
      id               : identifier;
      name             : label;
      description      : OPTIONAL text;
      relating_product : product;
      related_product  : product;
  END_ENTITY;

  ENTITY product_specification
    SUBTYPE OF(product_identification, configurable_item);
  END_ENTITY;

  ENTITY projected_zone_definition
    SUBTYPE OF(tolerance_zone_definition);
      projection_end   : shape_aspect;
      projected_length : measure_with_unit;
  END_ENTITY;

  ENTITY promissory_usage_occurrence
    SUBTYPE OF(assembly_component_usage);
  END_ENTITY;

  ENTITY property_definition;
      name        : label;
      description : OPTIONAL text;
      definition  : characterized_definition;
    DERIVE
      id          : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY property_definition_relationship;
      name                         : label;
      description                  : text;
      relating_property_definition : property_definition;
      related_property_definition  : property_definition;
  END_ENTITY;

  ENTITY property_definition_representation;
      definition          : represented_definition;
      used_representation : representation;
    DERIVE
      description         : text := get_description_value (SELF);
      name                : label := get_name_value (SELF);
  END_ENTITY;

  ENTITY property_process
    SUBTYPE OF(action);
      identification : identifier;
    INVERSE
      properties     : SET [1:?] OF process_property_association FOR process;
  END_ENTITY;

  ENTITY pyramid_volume
    SUBTYPE OF(volume);
      position : axis2_placement_3d;
      xlength  : positive_length_measure;
      ylength  : positive_length_measure;
      height   : positive_length_measure;
  END_ENTITY;

  ENTITY qualification;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY qualification_assignment
    ABSTRACT;
      id                     : identifier;
      name                   : label;
      description            : OPTIONAL text;
      assigned_qualification : qualification;
      role                   : qualification_role;
  END_ENTITY;

  ENTITY qualification_relationship;
      id                     : identifier;
      name                   : label;
      description            : OPTIONAL text;
      relating_qualification : qualification;
      related_qualification  : qualification;
  END_ENTITY;

  ENTITY qualification_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY qualification_type;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY qualification_type_assignment
    ABSTRACT;
      id                          : identifier;
      name                        : label;
      description                 : OPTIONAL text;
      assigned_qualification_type : qualification_type;
      role                        : qualification_type_role;
  END_ENTITY;

  ENTITY qualification_type_relationship;
      id                          : identifier;
      name                        : label;
      description                 : OPTIONAL text;
      relating_qualification_type : qualification_type;
      related_qualification_type  : qualification_type;
  END_ENTITY;

  ENTITY qualification_type_role;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY qualified_representation_item
    SUBTYPE OF(representation_item);
      qualifiers : SET [1:?] OF value_qualifier;
  END_ENTITY;

  ENTITY qualitative_uncertainty
    SUBTYPE OF(uncertainty_qualifier);
      uncertainty_value : text;
  END_ENTITY;

  ENTITY quantified_assembly_component_usage
    SUBTYPE OF(assembly_component_usage);
      quantity : measure_with_unit;
  END_ENTITY;

  ENTITY quasi_uniform_curve
    SUBTYPE OF(b_spline_curve);
  END_ENTITY;

  ENTITY quasi_uniform_surface
    SUBTYPE OF(b_spline_surface);
  END_ENTITY;

  ENTITY quasi_uniform_volume
    SUBTYPE OF(b_spline_volume);
  END_ENTITY;

  ENTITY ratio_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY ratio_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY rational_b_spline_curve
    SUBTYPE OF(b_spline_curve);
      weights_data : LIST [2:?] OF REAL;
    DERIVE
      weights      : ARRAY [0:100] OF REAL := list_to_array(weights_data,0,
                     upper_index_on_control_points);
  END_ENTITY;

  ENTITY rational_b_spline_surface
    SUBTYPE OF(b_spline_surface);
      weights_data : LIST [2:?] OF LIST [2:?] OF REAL;
    DERIVE
      weights      : ARRAY [0:100] OF ARRAY [0:100] OF REAL := make_array_of_array(weights_data,0,u_upper,0,v_upper);
  END_ENTITY;

  ENTITY rational_b_spline_volume
    SUBTYPE OF(b_spline_volume);
      weights_data : LIST [2:?] OF LIST [2:?] OF LIST [2:?] OF REAL;
    DERIVE
      weights      : ARRAY [0:100] OF ARRAY [0:100] OF ARRAY [0:100] OF REAL := make_array_of_array_of_array
                     (weights_data,0,u_upper,0,v_upper,0,w_upper);
  END_ENTITY;

  ENTITY rectangle_domain
    SUBTYPE OF(founded_item);
      corner  : cartesian_point;
      xlength : positive_length_measure;
      ylength : positive_length_measure;
  END_ENTITY;

  ENTITY rectangled_half_space
    SUBTYPE OF(half_space_2d);
      enclosure : rectangle_domain;
  END_ENTITY;

  ENTITY rectangular_area
    SUBTYPE OF(primitive_2d);
      position : axis2_placement_2d;
      x        : positive_length_measure;
      y        : positive_length_measure;
  END_ENTITY;

  ENTITY rectangular_composite_surface
    SUBTYPE OF(bounded_surface);
      segments : LIST [1:?] OF LIST [1:?] OF surface_patch;
    DERIVE
      n_u      : INTEGER := SIZEOF(segments);
      n_v      : INTEGER := SIZEOF(segments[1]);
  END_ENTITY;

  ENTITY rectangular_pyramid
    SUBTYPE OF(geometric_representation_item);
      position : axis2_placement_3d;
      xlength  : positive_length_measure;
      ylength  : positive_length_measure;
      height   : positive_length_measure;
  END_ENTITY;

  ENTITY rectangular_trimmed_surface
    SUBTYPE OF(bounded_surface);
      basis_surface : surface;
      u1            : parameter_value;
      u2            : parameter_value;
      v1            : parameter_value;
      v2            : parameter_value;
      usense        : BOOLEAN;
      vsense        : BOOLEAN;
  END_ENTITY;

  ENTITY referenced_modified_datum
    SUBTYPE OF(datum_reference);
      modifier : limit_condition;
  END_ENTITY;

  ENTITY relative_event_occurrence
    SUBTYPE OF(event_occurrence);
      base_event : event_occurrence;
      offset     : time_measure_with_unit;
  END_ENTITY;

  ENTITY reparametrised_composite_curve_segment
    SUBTYPE OF(composite_curve_segment);
      param_length : parameter_value;
  END_ENTITY;

  ENTITY replacement_relationship
    SUBTYPE OF(action_relationship);
  END_ENTITY;

  ENTITY representation;
      name             : label;
      items            : SET [1:?] OF representation_item;
      context_of_items : representation_context;
    DERIVE
      id               : identifier := get_id_value (SELF);
      description      : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY representation_context;
      context_identifier         : identifier;
      context_type               : text;
    INVERSE
      representations_in_context : SET [1:?] OF representation FOR context_of_items;
  END_ENTITY;

  ENTITY representation_item;
      name : label;
  END_ENTITY;

  ENTITY representation_item_relationship;
      name                         : label;
      description                  : OPTIONAL text;
      relating_representation_item : representation_item;
      related_representation_item  : representation_item;
  END_ENTITY;

  ENTITY representation_map;
      mapping_origin        : representation_item;
      mapped_representation : representation;
    INVERSE
      map_usage             : SET [1:?] OF mapped_item FOR mapping_source;
  END_ENTITY;

  ENTITY representation_relationship;
      name        : label;
      description : OPTIONAL text;
      rep_1       : representation;
      rep_2       : representation;
  END_ENTITY;

  ENTITY representation_relationship_with_transformation
    SUBTYPE OF(representation_relationship);
      transformation_operator : transformation;
  END_ENTITY;

  ENTITY requirement_for_action_resource
    SUBTYPE OF(action_resource_requirement);
      resources : SET [1:?] OF action_resource;
  END_ENTITY;

  ENTITY resource_property;
      name        : label;
      description : text;
      resource    : characterized_resource_definition;
  END_ENTITY;

  ENTITY resource_property_relationship;
      name                       : label;
      description                : text;
      relating_resource_property : resource_property;
      related_resource_property  : resource_property;
  END_ENTITY;

  ENTITY resource_requirement_type;
      name        : label;
      description : text;
  END_ENTITY;

  ENTITY resource_requirement_type_relationship;
      name                      : label;
      description               : text;
      relating_requirement_type : resource_requirement_type;
      related_requirement_type  : resource_requirement_type;
  END_ENTITY;

  ENTITY revolved_area_solid
    SUBTYPE OF(swept_area_solid);
      axis      : axis1_placement;
      angle     : plane_angle_measure;
    DERIVE
      axis_line : line := representation_item('')||
                  geometric_representation_item()|| curve()||
                  line(axis.location, representation_item('')||
                  geometric_representation_item()||
                  vector(axis.z, 1.0));
  END_ENTITY;

  ENTITY revolved_face_solid
    SUBTYPE OF(swept_face_solid);
      axis      : axis1_placement;
      angle     : plane_angle_measure;
    DERIVE
      axis_line : line := representation_item('')||
                  geometric_representation_item()|| curve()||
                  line(axis.location, representation_item('')||
                  geometric_representation_item()||
                  vector(axis.z, 1.0));
  END_ENTITY;

  ENTITY right_angular_wedge
    SUBTYPE OF(geometric_representation_item);
      position : axis2_placement_3d;
      x        : positive_length_measure;
      y        : positive_length_measure;
      z        : positive_length_measure;
      ltx      : length_measure;
  END_ENTITY;

  ENTITY right_circular_cone
    SUBTYPE OF(geometric_representation_item);
      position   : axis1_placement;
      height     : positive_length_measure;
      radius     : length_measure;
      semi_angle : plane_angle_measure;
  END_ENTITY;

  ENTITY right_circular_cylinder
    SUBTYPE OF(geometric_representation_item);
      position : axis1_placement;
      height   : positive_length_measure;
      radius   : positive_length_measure;
  END_ENTITY;

  ENTITY role_association;
      role           : object_role;
      item_with_role : role_select;
  END_ENTITY;

  ENTITY runout_zone_definition
    SUBTYPE OF(tolerance_zone_definition);
      orientation : runout_zone_orientation;
  END_ENTITY;

  ENTITY runout_zone_orientation;
      angle : measure_with_unit;
  END_ENTITY;

  ENTITY runout_zone_orientation_reference_direction
    SUBTYPE OF(runout_zone_orientation);
      orientation_defining_relationship : shape_aspect_relationship;
  END_ENTITY;

  ENTITY seam_curve
    SUBTYPE OF(surface_curve);
  END_ENTITY;

  ENTITY seam_edge
    SUBTYPE OF(oriented_edge);
      pcurve_reference : pcurve;
  END_ENTITY;

  ENTITY sectioned_spine
    SUBTYPE OF(geometric_curve_set);
      cross_sections : LIST [2:?] OF curve;
      spine_points   : LIST [2:?] OF point;
  END_ENTITY;

  ENTITY security_classification;
      name           : label;
      purpose        : text;
      security_level : security_classification_level;
  END_ENTITY;

  ENTITY security_classification_assignment
    ABSTRACT;
      assigned_security_classification : security_classification;
    DERIVE
      role                             : object_role := get_role (SELF);
  END_ENTITY;

  ENTITY security_classification_level;
      name : label;
  END_ENTITY;

  ENTITY serial_numbered_effectivity
    SUBTYPE OF(effectivity);
      effectivity_start_id : identifier;
      effectivity_end_id   : OPTIONAL identifier;
  END_ENTITY;

  ENTITY shape_aspect;
      name                 : label;
      description          : OPTIONAL text;
      of_shape             : product_definition_shape;
      product_definitional : LOGICAL;
    DERIVE
      id                   : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY shape_aspect_deriving_relationship
    SUBTYPE OF(shape_aspect_relationship);
  END_ENTITY;

  ENTITY shape_aspect_relationship;
      name                  : label;
      description           : OPTIONAL text;
      relating_shape_aspect : shape_aspect;
      related_shape_aspect  : shape_aspect;
    DERIVE
      id                    : identifier := get_id_value (SELF);
  END_ENTITY;

  ENTITY shape_definition_representation
    SUBTYPE OF(property_definition_representation);
  END_ENTITY;

  ENTITY shape_dimension_representation
    SUBTYPE OF(shape_representation);
  END_ENTITY;

  ENTITY shape_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY shape_representation_relationship
    SUBTYPE OF(representation_relationship);
  END_ENTITY;

  ENTITY shell_based_surface_model
    SUBTYPE OF(geometric_representation_item);
      sbsm_boundary : SET [1:?] OF shell;
  END_ENTITY;

  ENTITY shell_based_wireframe_model
    SUBTYPE OF(geometric_representation_item);
      sbwm_boundary : SET [1:?] OF shell;
  END_ENTITY;

  ENTITY si_unit
    SUBTYPE OF(named_unit);
      prefix                     : OPTIONAL si_prefix;
      name                       : si_unit_name;
    DERIVE
      SELF\named_unit.dimensions : dimensional_exponents := dimensions_for_si_unit (name);
  END_ENTITY;

  ENTITY solid_angle_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY solid_angle_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY solid_model
    SUPERTYPE OF (ONEOF(csg_solid, manifold_solid_brep, swept_face_solid, swept_area_solid, swept_disk_solid, solid_replica, brep_2d, trimmed_volume))
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY solid_replica
    SUBTYPE OF(solid_model);
      parent_solid   : solid_model;
      transformation : cartesian_transformation_operator_3d;
  END_ENTITY;

  ENTITY specified_higher_usage_occurrence
    SUBTYPE OF(assembly_component_usage);
      upper_usage : assembly_component_usage;
      next_usage  : next_assembly_usage_occurrence;
    UNIQUE
      UR1 : upper_usage, next_usage;
  END_ENTITY;

  ENTITY sphere
    SUBTYPE OF(geometric_representation_item);
      radius : positive_length_measure;
      centre : point;
  END_ENTITY;

  ENTITY spherical_point
    SUBTYPE OF(cartesian_point);
      r                                : length_measure;
      theta                            : plane_angle_measure;
      phi                              : plane_angle_measure;
    DERIVE
      SELF\cartesian_point.coordinates : LIST [1:3] OF length_measure := 
                                         [r*sin(theta)*cos(phi), r*sin(theta)*sin(phi), r*cos(theta)];
  END_ENTITY;

  ENTITY spherical_surface
    SUBTYPE OF(elementary_surface);
      radius : positive_length_measure;
  END_ENTITY;

  ENTITY spherical_volume
    SUBTYPE OF(volume);
      position : axis2_placement_3d;
      radius   : positive_length_measure;
  END_ENTITY;

  ENTITY standard_uncertainty
    SUBTYPE OF(uncertainty_qualifier);
      uncertainty_value : REAL;
  END_ENTITY;

  ENTITY statistical_distribution_for_tolerance
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY subedge
    SUBTYPE OF(edge);
      parent_edge : edge;
  END_ENTITY;

  ENTITY subface
    SUBTYPE OF(face);
      parent_face : face;
  END_ENTITY;

  ENTITY surface
    SUPERTYPE OF (ONEOF(elementary_surface, swept_surface, bounded_surface, offset_surface, surface_replica) ANDOR oriented_surface)
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY surface_curve
    SUPERTYPE OF (ONEOF(intersection_curve, seam_curve) ANDOR bounded_surface_curve)
    SUBTYPE OF(curve);
      curve_3d              : curve;
      associated_geometry   : LIST [1:2] OF pcurve_or_surface;
      master_representation : preferred_surface_curve_representation;
    DERIVE
      basis_surface         : SET [1:2] OF surface := get_basis_surface(SELF);
  END_ENTITY;

  ENTITY surface_curve_swept_area_solid
    SUBTYPE OF(swept_area_solid);
      directrix         : curve;
      start_param       : REAL;
      end_param         : REAL;
      reference_surface : surface;
  END_ENTITY;

  ENTITY surface_curve_swept_face_solid
    SUBTYPE OF(swept_face_solid);
      directrix         : curve;
      start_param       : REAL;
      end_param         : REAL;
      reference_surface : surface;
  END_ENTITY;

  ENTITY surface_curve_swept_surface
    SUBTYPE OF(swept_surface);
      directrix         : curve;
      reference_surface : surface;
  END_ENTITY;

  ENTITY surface_of_linear_extrusion
    SUBTYPE OF(swept_surface);
      extrusion_axis : vector;
  END_ENTITY;

  ENTITY surface_of_revolution
    SUBTYPE OF(swept_surface);
      axis_position : axis1_placement;
    DERIVE
      axis_line     : line := representation_item('')||
                      geometric_representation_item()|| curve()||
                      line(axis_position.location, representation_item('')||
                      geometric_representation_item()||
                      vector(axis_position.z, 1.0));
  END_ENTITY;

  ENTITY surface_patch
    SUBTYPE OF(founded_item);
      parent_surface : bounded_surface;
      u_transition   : transition_code;
      v_transition   : transition_code;
      u_sense        : BOOLEAN;
      v_sense        : BOOLEAN;
    INVERSE
      using_surfaces : BAG [1:?] OF rectangular_composite_surface FOR segments;
  END_ENTITY;

  ENTITY surface_replica
    SUBTYPE OF(surface);
      parent_surface : surface;
      transformation : cartesian_transformation_operator_3d;
  END_ENTITY;

  ENTITY surface_texture_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY swept_area_solid
    SUPERTYPE OF (ONEOF(revolved_area_solid, extruded_area_solid, surface_curve_swept_area_solid))
    SUBTYPE OF(solid_model);
      swept_area : curve_bounded_surface;
  END_ENTITY;

  ENTITY swept_disk_solid
    SUBTYPE OF(solid_model);
      directrix    : curve;
      radius       : positive_length_measure;
      inner_radius : OPTIONAL positive_length_measure;
      start_param  : REAL;
      end_param    : REAL;
  END_ENTITY;

  ENTITY swept_face_solid
    SUPERTYPE OF (ONEOF(extruded_face_solid, revolved_face_solid, surface_curve_swept_face_solid))
    SUBTYPE OF(solid_model);
      swept_face : face_surface;
  END_ENTITY;

  ENTITY swept_surface
    SUPERTYPE OF (ONEOF(surface_of_linear_extrusion, surface_of_revolution, surface_curve_swept_surface, fixed_reference_swept_surface))
    SUBTYPE OF(surface);
      swept_curve : curve;
  END_ENTITY;

  ENTITY symmetric_shape_aspect
    SUBTYPE OF(shape_aspect);
    INVERSE
      basis_relationships : SET [1:?] OF shape_aspect_relationship FOR relating_shape_aspect;
  END_ENTITY;

  ENTITY tactile_appearance_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY tangent
    SUBTYPE OF(derived_shape_aspect);
  END_ENTITY;

  ENTITY tetrahedron
    SUBTYPE OF(faceted_primitive);
  END_ENTITY;

  ENTITY tetrahedron_volume
    SUBTYPE OF(volume);
      point_1 : cartesian_point;
      point_2 : cartesian_point;
      point_3 : cartesian_point;
      point_4 : cartesian_point;
  END_ENTITY;

  ENTITY thermodynamic_temperature_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY thermodynamic_temperature_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY time_assignment
    ABSTRACT;
      assigned_time : local_time;
      role          : time_role;
  END_ENTITY;

  ENTITY time_interval;
      id          : identifier;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY time_interval_assignment
    ABSTRACT;
      assigned_time_interval : time_interval;
      role                   : time_interval_role;
  END_ENTITY;

  ENTITY time_interval_based_effectivity
    SUBTYPE OF(effectivity);
      effectivity_period : time_interval;
  END_ENTITY;

  ENTITY time_interval_relationship;
      name                   : label;
      description            : OPTIONAL text;
      relating_time_interval : time_interval;
      related_time_interval  : time_interval;
  END_ENTITY;

  ENTITY time_interval_role;
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY time_interval_with_bounds
    SUBTYPE OF(time_interval);
      primary_bound   : OPTIONAL date_time_or_event_occurrence;
      secondary_bound : OPTIONAL date_time_or_event_occurrence;
      duration        : OPTIONAL time_measure_with_unit;
  END_ENTITY;

  ENTITY time_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY time_role;
      name        : label;
    DERIVE
      description : text := get_description_value (SELF);
  END_ENTITY;

  ENTITY time_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY tolerance_value;
      lower_bound : measure_with_unit;
      upper_bound : measure_with_unit;
  END_ENTITY;

  ENTITY tolerance_with_statistical_distribution;
      associated_tolerance : shape_tolerance_select;
      tolerance_allocation : statistical_distribution_for_tolerance;
  END_ENTITY;

  ENTITY tolerance_zone
    SUBTYPE OF(shape_aspect);
      defining_tolerance : SET [1:?] OF geometric_tolerance;
      form               : tolerance_zone_form;
  END_ENTITY;

  ENTITY tolerance_zone_definition
    SUPERTYPE OF (ONEOF(projected_zone_definition, runout_zone_definition));
      zone       : tolerance_zone;
      boundaries : SET [1:?] OF shape_aspect;
  END_ENTITY;

  ENTITY tolerance_zone_form;
      name : label;
  END_ENTITY;

  ENTITY topological_representation_item
    SUPERTYPE OF (ONEOF(vertex, edge, face_bound, face, vertex_shell, wire_shell, connected_edge_set, connected_face_set, loop ANDOR path))
    SUBTYPE OF(representation_item);
  END_ENTITY;

  ENTITY toroidal_surface
    SUBTYPE OF(elementary_surface);
      major_radius : positive_length_measure;
      minor_radius : positive_length_measure;
  END_ENTITY;

  ENTITY toroidal_volume
    SUBTYPE OF(volume);
      position     : axis2_placement_3d;
      major_radius : positive_length_measure;
      minor_radius : positive_length_measure;
  END_ENTITY;

  ENTITY torus
    SUBTYPE OF(geometric_representation_item);
      position     : axis1_placement;
      major_radius : positive_length_measure;
      minor_radius : positive_length_measure;
  END_ENTITY;

  ENTITY trimmed_curve
    SUBTYPE OF(bounded_curve);
      basis_curve           : curve;
      trim_1                : SET [1:2] OF trimming_select;
      trim_2                : SET [1:2] OF trimming_select;
      sense_agreement       : BOOLEAN;
      master_representation : trimming_preference;
  END_ENTITY;

  ENTITY trimmed_volume
    SUBTYPE OF(solid_model);
      basis_volume : volume;
      u1           : parameter_value;
      u2           : parameter_value;
      v1           : parameter_value;
      v2           : parameter_value;
      w1           : parameter_value;
      w2           : parameter_value;
  END_ENTITY;

  ENTITY type_qualifier;
      name : label;
  END_ENTITY;

  ENTITY uncertainty_assigned_representation
    SUBTYPE OF(representation);
      uncertainty : SET [1:?] OF uncertainty_measure_with_unit;
  END_ENTITY;

  ENTITY uncertainty_measure_with_unit
    SUBTYPE OF(measure_with_unit);
      name        : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY uncertainty_qualifier
    SUPERTYPE OF (ONEOF(standard_uncertainty, qualitative_uncertainty));
      measure_name : label;
      description  : text;
  END_ENTITY;

  ENTITY uniform_curve
    SUBTYPE OF(b_spline_curve);
  END_ENTITY;

  ENTITY uniform_surface
    SUBTYPE OF(b_spline_surface);
  END_ENTITY;

  ENTITY uniform_volume
    SUBTYPE OF(b_spline_volume);
  END_ENTITY;

  ENTITY value_range
    SUBTYPE OF(compound_representation_item);
  END_ENTITY;

  ENTITY value_representation_item
    SUBTYPE OF(representation_item);
      value_component : measure_value;
  END_ENTITY;

  ENTITY vector
    SUBTYPE OF(geometric_representation_item);
      orientation : direction;
      magnitude   : length_measure;
  END_ENTITY;

  ENTITY versioned_action_request;
      id          : identifier;
      version     : label;
      purpose     : text;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY versioned_action_request_relationship;
      id                                : identifier;
      name                              : label;
      description                       : OPTIONAL text;
      relating_versioned_action_request : versioned_action_request;
      related_versioned_action_request  : versioned_action_request;
  END_ENTITY;

  ENTITY vertex
    SUBTYPE OF(topological_representation_item);
  END_ENTITY;

  ENTITY vertex_loop
    SUBTYPE OF(loop);
      loop_vertex : vertex;
  END_ENTITY;

  ENTITY vertex_point
    SUBTYPE OF(vertex, geometric_representation_item);
      vertex_geometry : point;
  END_ENTITY;

  ENTITY vertex_shell
    SUBTYPE OF(topological_representation_item);
      vertex_shell_extent : vertex_loop;
  END_ENTITY;

  ENTITY visual_appearance_representation
    SUBTYPE OF(representation);
  END_ENTITY;

  ENTITY volume
    SUPERTYPE OF (ONEOF(block_volume, wedge_volume, spherical_volume, cylindrical_volume, eccentric_conical_volume, toroidal_volume, pyramid_volume, b_spline_volume, ellipsoid_volume, tetrahedron_volume, hexahedron_volume))
    SUBTYPE OF(geometric_representation_item);
  END_ENTITY;

  ENTITY volume_measure_with_unit
    SUBTYPE OF(measure_with_unit);
  END_ENTITY;

  ENTITY volume_unit
    SUBTYPE OF(named_unit);
  END_ENTITY;

  ENTITY wedge_volume
    SUBTYPE OF(volume);
      position : axis2_placement_3d;
      x        : positive_length_measure;
      y        : positive_length_measure;
      z        : positive_length_measure;
      ltx      : length_measure;
  END_ENTITY;

  ENTITY week_of_year_and_day_date
    SUBTYPE OF(date);
      week_component : week_in_year_number;
      day_component  : OPTIONAL day_in_week_number;
  END_ENTITY;

  ENTITY wire_shell
    SUBTYPE OF(topological_representation_item);
      wire_shell_extent : SET [1:?] OF loop;
  END_ENTITY;

  SUBTYPE_CONSTRAINT classification_or_complete_membership FOR classification_assignment;
    ONEOF(classification, complete_membership);
  END_SUBTYPE_CONSTRAINT;


END_SCHEMA;

