(*
   $Id: arm.exp,v 1.4 2004/12/16 12:55:49 liutkus Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 assembly functional interface requirements - EXPRESS ARM
*)

SCHEMA Ap210_assembly_functional_interface_requirements_arm;
   USE FROM Assembly_module_usage_view_arm;
   USE FROM Network_functional_usage_view_arm;
   USE FROM Functional_assignment_to_part_arm;   
   USE FROM Characteristic_arm;
END_SCHEMA;

