(*
   $Id: mim.exp,v 1.10 2005/11/10 17:20:48 lothartklein Exp $
   ISO TC184/SC4/WG3 N1947 - ISO/CD-TS 10303-1604 AP210 assembly functional interface requirements - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG3 N1612
*)


SCHEMA Ap210_assembly_functional_interface_requirements_mim;
	USE FROM Assembly_module_usage_view_mim;	-- ISO/TS 10303-1642
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Functional_usage_view_mim;	-- ISO/TS 10303-1705
END_SCHEMA;

