(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Functional decomposition to assembly design - EXPRESS ARM
*)

SCHEMA Functional_decomposition_to_assembly_design_arm;

USE FROM Functional_decomposition_to_design_arm;

USE FROM Assembly_technology_arm;

  ENTITY Design_functional_unit_allocation_to_assembly_joint;
      functional_design_definition_path : Design_composition_path;
      implementation                    : Assembly_joint;
    UNIQUE
      UR1 : functional_design_definition_path;
  END_ENTITY;

END_SCHEMA;
