(*
   $Id: arm.exp,v 1.5 2005/01/04 07:11:00 kovaliovas Exp $
   ISO TC184/SC4/WG12 N3417 - ISO/CD-TS 10303-1675 Functional decomposition to assembly design - EXPRESS ARM
*)

SCHEMA Functional_decomposition_to_assembly_design_arm;

USE FROM Functional_decomposition_to_design_arm;

USE FROM Assembly_technology_arm;

  ENTITY Design_functional_unit_allocation_to_assembly_joint;
      functional_design_definition_path : Design_composition_path;
      implementation                    : Assembly_joint;
    UNIQUE
      UR1 : functional_design_definition_path;
  END_ENTITY;

END_SCHEMA;
