(*
   $Id: mim.exp,v 1.3 2005/02/02 14:45:24 budreckytej Exp $
   ISO TC184/SC4/WG12 N3559 - ISO/CD-TS 10303-1726 Physical unit 2d shape - EXPRESS MIM
*)


SCHEMA Physical_unit_2d_shape_mim;
	USE FROM Non_feature_shape_element_mim;	-- ISO/TS 10303-1706
	USE FROM Physical_unit_shape_with_parameters_mim;	-- ISO/TS 10303-1730
	USE FROM Value_with_unit_extension_mim;	-- ISO/TS 10303-1753
	USE FROM Layered_2d_shape_mim; -- ISO/TS 10303-1693
END_SCHEMA;

