(*
   $Id: arm.exp,v 1.7 2008/10/10 15:10:05 abhpf Exp $
   ISO TC184/SC4/WG12 N5860 - ISO/DIS 10303-1784 External analysis representation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4574
*) 

SCHEMA External_analysis_representation_arm;

USE FROM Analysis_representation_arm;

USE FROM File_identification_arm;

ENTITY External_analysis_model
SUBTYPE OF (Analysis_model);
  external_file : Digital_file;
END_ENTITY;

END_SCHEMA;

