(*
   $Id: mim.exp,v 1.4 2007/03/21 01:11:56 abhpf Exp $
  ISO TC184/SC4/WG12 N4575 - ISO/WD 10303-1784 external_analysis_representation - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA External_analysis_representation_mim;

USE FROM Analysis_representation_mim;    -- ISO/CD-TS 10303-1785

USE FROM File_identification_mim;    -- ISO/TS 10303-1127

USE FROM product_property_definition_schema   -- ISO 10303-41
  (property_definition); 

USE FROM product_property_representation_schema   -- ISO 10303-41
  (property_definition_representation); 


END_SCHEMA;  -- External_analysis_representation_mim

