(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Shield - EXPRESS ARM
*)

SCHEMA Shield_arm;

USE FROM Physical_unit_design_view_arm;

	TYPE shieldable_item = EXTENSIBLE GENERIC_ENTITY SELECT
    (assembly_component);
	END_TYPE;

  ENTITY Shield
    SUBTYPE OF (Assembly_component);
      shielded_item : SET[1:?] OF shieldable_item;
  END_ENTITY; -- shield

END_SCHEMA;
