(*
   $Id: arm.exp,v 1.6 2005/01/06 14:04:48 liutkus Exp $
   ISO TC184/SC4/WG12 N1665 - ISO/CD-TS 10303-1622 Ap210 interconnect technology constraints - EXPRESS ARM
*)

SCHEMA Ap210_interconnect_technology_constraints_arm;
	USE FROM Ap210_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Characteristic_arm;	-- ISO/TS 10303-1654
	USE FROM Fabrication_technology_arm;	-- ISO/TS 10303-1670
END_SCHEMA;

