(*  ISO/TC184/SC4 WG3N1211 - ISO/CD-TS - 10303-1151 functional_data - EXPRESS ARM  *)

SCHEMA Functional_data_arm;

USE FROM Activity_structure_and_classification_arm;    --  ISO/CD-TS 10303-1169
USE FROM Organization_type_arm;    --  ISO/CD-TS 10303-1240
USE FROM Type_of_person_arm;    --  ISO/CD-TS 10303-1245
USE FROM Person_organization_arm;    --  ISO/TS 10303-1011
USE FROM Product_structure_and_classification_arm;    --  ISO/CD-TS 10303-1156
USE FROM Property_and_property_assignment_arm;    --  ISO/CD-TS 10303-1198

TYPE functional_involved_class_select = SELECT BASED_ON involved_class_select WITH 
   (Class_of_activity, 
    Class_of_composition_of_activity, 
    Class_of_connection_of_activity, 
    Class_of_involvement_in_activity, 
    Class_of_product, 
    Class_of_composition_of_product, 
    Class_of_connection_of_product, 
    Class_of_containment_of_product, 
    Class_of_involvement_of_product_in_connection, 
    Organization_type, 
    Type_of_person, 
    Property_condition);
END_TYPE; 

TYPE functional_involved_item_select = SELECT BASED_ON involved_select WITH 
   (Class_of_activity, 
    Class_of_composition_of_activity, 
    Class_of_connection_of_activity, 
    Class_of_involvement_in_activity, 
    Class_of_product, 
    Class_of_composition_of_product, 
    Class_of_connection_of_product, 
    Class_of_containment_of_product, 
    Class_of_involvement_of_product_in_connection, 
    Organization_type, 
    Type_of_person, 
    Property_condition, 
    Individual_activity, 
    Composition_of_individual_activity, 
    Connection_of_individual_activity, 
    Individual_involvement_in_activity, 
    Product_as_individual, 
    Composition_of_individual_product, 
    Connection_of_individual_product, 
    Containment_of_individual_product, 
    Involvement_of_individual_product_in_connection, 
    Organization, 
    Person, 
    Person_in_organization, 
    Possession_of_property);
END_TYPE; 

END_SCHEMA;  -- Functional_data_arm

