(*  ISO/TC184/SC4/WG3 N1215 - ISO/CD-TS - 10303-1151 functional_data - EXPRESS MIM  *)

SCHEMA Functional_data_mim;

USE FROM Reference_data_library_mim;    --  ISO/CD-TS 10303-1213
USE FROM Activity_structure_and_classification_mim;    --  ISO/CD-TS 10303-1169
USE FROM Person_organization_mim;    --  ISO/TS 10303-1011
USE FROM Product_structure_and_classification_mim;    --  ISO/CD-TS 10303-1156
USE FROM Property_and_property_assignment_mim;    --  ISO/CD-TS 10303-1198

TYPE functional_involved_class_select = SELECT BASED_ON involved_class_select WITH 
   (class_of_activity, 
    class_of_composition_of_activity, 
    class_of_connection_of_activity, 
    class_of_involvement_in_activity, 
    class_of_product, 
    class_of_composition_of_product, 
    class_of_connection_of_product, 
    class_of_containment_of_product, 
    class_of_involvement_of_product_in_connection, 
    organization_type, 
    class_of_person, 
    property_condition_for_activity, 
    property_condition_for_product);
END_TYPE; 

TYPE functional_involved_item_select = SELECT BASED_ON involved_select WITH 
   (class_of_activity, 
    class_of_composition_of_activity, 
    class_of_connection_of_activity, 
    class_of_involvement_in_activity, 
    class_of_product, 
    class_of_composition_of_product, 
    class_of_connection_of_product, 
    class_of_containment_of_product, 
    class_of_involvement_of_product_in_connection, 
    organization_type, 
    class_of_person, 
    property_condition_for_activity, 
    property_condition_for_product, 
    individual_activity, 
    composition_of_individual_activity, 
    connection_of_individual_activity, 
    individual_involvement_in_activity, 
    product_as_individual, 
    composition_of_individual_product, 
    connection_of_individual_product, 
    containment_of_individual_product, 
    involvement_of_individual_product_in_connection, 
    organization, 
    person, 
    person_and_organization, 
    possession_of_property_by_activity, 
    possession_of_property_by_product);
END_TYPE; 

END_SCHEMA;  -- Functional_data_mim
