(*
   $Id: mkmodule.js,v 1.46 2010/02/04 16:48:02 robbod Exp $
   N - ISO/CD-TS - 10303- wiring_harness_assembly_design - EXPRESS ARM*)

SCHEMA Wiring_harness_assembly_design_arm;

USE FROM Harness_assembly_electrical_design_arm; -- ISO/TS 10303-1636
USE FROM Extruded_structure_cross_section_arm; --
USE FROM Edge_based_topological_representation_with_length_arm; --

USE FROM Cable_arm; -- ISO/TS 10303-1653


ENTITY Wiring_harness_assembly_design
  SUBTYPE OF (Assembly_module_design_view);
  topology : Connected_edge_with_length_set_representation;
END_ENTITY;

END_SCHEMA;
