(*
   $Id: mim.exp,v 1.4 2015/08/14 10:22:51 lothartklein Exp $
   N - ISO/TS 10303-1828 wiring_harness_assembly_design - EXPRESS MIM*)

SCHEMA Wiring_harness_assembly_design_mim;

USE FROM Assembly_module_design_mim;
USE FROM Cable_mim;
USE FROM Extruded_structure_cross_section_mim; 
USE FROM Edge_based_topological_representation_with_length_mim; 

ENTITY harness_node
	SUBTYPE OF (shape_aspect);
END_ENTITY;

ENTITY harness_segment
	SUBTYPE OF (shape_aspect);
END_ENTITY;

END_SCHEMA;
