(* topology_based_identification_schema -- an extension of ISO 10303-55*)

SCHEMA topology_based_identification_schema;

REFERENCE FROM geometry_schema					-- ISO 10303-42
	(cartesian_point,
	geometric_representation_item);
	
REFERENCE FROM topology_schema					-- ISO 10303-42
	(edge_curve,
	face,
	face_surface,
	list_shell_faces,
	shell);
	
REFERENCE FROM geometric_model_schema				-- ISO 10303-42
	(extruded_face_solid,
	manifold_solid_brep,
	msb_shells,
	revolved_face_solid,
	solid_model);
	
REFERENCE FROM sketch_schema					-- ISO 10303-108
	(positioned_sketch);
	
REFERENCE FROM solid_shape_element_schema			-- ISO 10303-111
	(edge_blended_solid,
	extruded_face_solid_with_trim_conditions,
	offset_face_solid,
	revolved_face_solid_with_trim_conditions,
	sculptured_solid,
	shelled_solid,
	solid_with_chamfered_edges,
	solid_with_circular_pattern,
	solid_with_groove,
	solid_with_hole,
	solid_with_pocket,
	solid_with_protrusion,
	solid_with_rectangular_pattern,
	solid_with_slot,
	solid_with_through_depression,
	solid_with_trapezoidal_section_slot,
	thickened_face_solid);

TYPE face_type_to_be_created = ENUMERATION OF
	(initial, lateral, terminal);
END_TYPE;

TYPE profile_type_select = SELECT
	(face_surface, positioned_sketch);
END_TYPE;

ENTITY basic_face_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(imported_face_identification,
		profile_based_feature_identification,
		transition_feature_identification,
		shell_feature_identification,
		offset_feature_identification,
		draft_feature_identification,
		pattern_feature_identification,
		face_surface_based_feature_identification))
	SUBTYPE OF (geometric_representation_item);
	containing_model : solid_model;
END_ENTITY;

ENTITY imported_face_identification
	SUBTYPE OF (basic_face_identification);
	SELF\basic_face_identification.containing_model : manifold_solid_brep;
   	imported_face : face_surface;
WHERE
	WR1: face_in_brep(imported_face, SELF\basic_face_identification.containing_model);
END_ENTITY;

ENTITY profile_based_feature_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(extrude_feature_identification,
		revolve_feature_identification,
		revolved_hole_feature_identification))
	SUBTYPE OF (basic_face_identification);
	surface_instance	: OPTIONAL profile_type_select;
	edge_segment		: OPTIONAL edge_curve;
	face_creation_type	: face_type_to_be_created;
WHERE
	WR1: NOT (('SKETCH_SCHEMA.POSITIONED_SKETCH' IN	TYPEOF(surface_instance)) 
	AND NOT ('TOPOLOGY_SCHEMA.FACE_SURFACE' IN TYPEOF(surface_instance.sketch_basis)));
END_ENTITY;

ENTITY extrude_feature_identification
	SUBTYPE OF (profile_based_feature_identification);
WHERE
	WR1: SIZEOF(TYPEOF(SELF\basic_face_identification.containing_model) *
	['GEOMETRIC_MODEL_SCHEMA.EXTRUDED_FACE_SOLID',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_THROUGH_DEPRESSION',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_POCKET',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_SLOT',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_PROTRUSION']) = 1;
END_ENTITY;

ENTITY revolve_feature_identification
	SUBTYPE OF (profile_based_feature_identification);
WHERE
	WR1: SIZEOF(TYPEOF(SELF\basic_face_identification.containing_model) *
	['GEOMETRIC_MODEL_SCHEMA.REVOLVED_FACE_SOLID',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_GROOVE']) = 1;
END_ENTITY;

ENTITY revolved_hole_feature_identification
	SUBTYPE OF (profile_based_feature_identification);
	SELF\basic_face_identification.containing_model : solid_with_hole;
END_ENTITY;

ENTITY transition_feature_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(edge_blend_feature_identification,
		chamfer_feature_identification))
	SUBTYPE OF (basic_face_identification);
	adjacent_face_identifications : LIST[2:?] OF UNIQUE basic_face_identification;
END_ENTITY; 

ENTITY edge_blend_feature_identification
	SUBTYPE OF (transition_feature_identification);
WHERE
	WR1: SIZEOF(TYPEOF(SELF\basic_face_identification.containing_model) *
	['SOLID_SHAPE_ELEMENT_SCHEMA.EDGE_BLENDED_SOLID',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_POCKET',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_TRAPEZOIDAL_SECTION_SLOT',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_GROOVE']) = 1;
END_ENTITY; 

ENTITY chamfer_feature_identification
	SUBTYPE OF (transition_feature_identification);
	SELF\basic_face_identification.containing_model : solid_with_chamfered_edges;
END_ENTITY; 

ENTITY shell_feature_identification
	SUBTYPE OF (basic_face_identification);
	SELF\basic_face_identification.containing_model : shelled_solid;
	corresponding_face_identification : basic_face_identification;
END_ENTITY;

ENTITY offset_feature_identification
	SUBTYPE OF (basic_face_identification);
	SELF\basic_face_identification.containing_model : offset_face_solid;
	offset_face_identification : basic_face_identification;
END_ENTITY;

ENTITY draft_feature_identification
	SUBTYPE OF (basic_face_identification);
	drafted_face_identification : basic_face_identification;
WHERE
	WR1: SIZEOF(TYPEOF(SELF\basic_face_identification.containing_model) *
	['SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_POCKET',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_TRAPEZOIDAL_SECTION_SLOT',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_GROOVE',
	'SOLID_SHAPE_ELEMENT_SCHEMA.SOLID_WITH_PROTRUSION',
	'SOLID_SHAPE_ELEMENT_SCHEMA.EXTRUDED_FACE_SOLID_WITH_TRIM_CONDITIONS',
	'SOLID_SHAPE_ELEMENT_SCHEMA.REVOLVED_FACE_SOLID_WITH_TRIM_CONDITIONS']) = 1;
END_ENTITY;

ENTITY face_surface_based_feature_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(sculpture_feature_identification,
		thicken_feature_identification))
	SUBTYPE OF (basic_face_identification);
	target_face : face_surface;
END_ENTITY;

ENTITY sculpture_feature_identification
	SUBTYPE OF (face_surface_based_feature_identification);
	SELF\basic_face_identification.containing_model : sculptured_solid;
END_ENTITY;

ENTITY thicken_feature_identification 
	SUBTYPE OF (face_surface_based_feature_identification); 
	SELF\basic_face_identification.containing_model : thickened_face_solid;
	edge_segment : OPTIONAL edge_curve;
	face_creation_type : face_type_to_be_created;
END_ENTITY;

ENTITY pattern_feature_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(rectangular_pattern_feature_identification,
		circular_pattern_feature_identification))
	SUBTYPE OF (basic_face_identification);
	target_face_identification : basic_face_identification;
END_ENTITY;

ENTITY rectangular_pattern_feature_identification
	SUBTYPE OF (pattern_feature_identification);
	SELF\basic_face_identification.containing_model : solid_with_rectangular_pattern;
	total_row_inst_num : INTEGER;
	total_col_inst_num : INTEGER;
	row_inst_order : INTEGER;
	col_inst_order : INTEGER;
WHERE
	WR1: (row_inst_order > 0) AND (row_inst_order <= total_row_inst_num);
	WR2: (col_inst_order > 0) AND (col_inst_order <= total_col_inst_num);
END_ENTITY;

ENTITY circular_pattern_feature_identification
	SUBTYPE OF (pattern_feature_identification);
	SELF\basic_face_identification.containing_model : solid_with_circular_pattern;
	total_rad_inst_num : INTEGER;
	total_ang_inst_num : INTEGER;
	rad_inst_order : INTEGER;
	ang_inst_order : INTEGER;
WHERE
	WR1: (rad_inst_order > 0) AND (rad_inst_order <= total_rad_inst_num);
	WR2: (ang_inst_order > 0) AND (ang_inst_order <= total_ang_inst_num);
END_ENTITY;

ENTITY ambiguity_resolution
	ABSTRACT SUPERTYPE OF (
		ONEOF(split_element_information, 
		merged_element_information));
END_ENTITY;

ENTITY split_element_information
	SUBTYPE OF (ambiguity_resolution, geometric_representation_item);
	split_elements_number : INTEGER;
	element_order : INTEGER;
	reference_point : cartesian_point;
WHERE
	WR1: split_elements_number >= 2;
	WR2: (element_order > 0) AND (element_order <= split_elements_number);
END_ENTITY;

ENTITY merged_element_information
	SUBTYPE OF (ambiguity_resolution, geometric_representation_item);
	merged_elements_number : INTEGER;
	merged_element_identifications : LIST[1:?] OF UNIQUE basic_face_identification;
END_ENTITY;

ENTITY topology_based_element_identification
	ABSTRACT SUPERTYPE OF (
		ONEOF(topology_based_face_identification,
		topology_based_edge_identification,
		topology_based_vertex_identification))
	SUBTYPE OF (geometric_representation_item);
END_ENTITY;

ENTITY topology_based_face_identification
	SUBTYPE OF (topology_based_element_identification);
	face_basic_identification : basic_face_identification;
	face_SEI : OPTIONAL split_element_information;
	face_MEI : OPTIONAL merged_element_information;
END_ENTITY;

ENTITY topology_based_edge_identification
	SUBTYPE OF (topology_based_element_identification);
	left_adjacent_face : topology_based_face_identification;
	right_adjacent_face : topology_based_face_identification;
	edge_SEI : OPTIONAL split_element_information;
END_ENTITY;

ENTITY topology_based_vertex_identification
	SUBTYPE OF (topology_based_element_identification);
	adjacent_faces : LIST[1:?] OF topology_based_face_identification;
	vertex_SEI : OPTIONAL split_element_information;
END_ENTITY;

ENTITY user_selected_topology_element
	SUBTYPE OF (geometric_representation_item);
	querying_topology_identification : topology_based_element_identification;
END_ENTITY;

FUNCTION face_in_brep (test_face : face; brep : manifold_solid_brep) 
: BOOLEAN;
LOCAL
  shells : SET[1 : ?] OF shell := msb_shells(brep);
  faces : LIST[0 : ?] OF face := [];
  i, j : INTEGER;
  result : BOOLEAN := FALSE;
END_LOCAL;
REPEAT i := 1 TO SIZEOF(shells);
  faces := list_shell_faces(shells[i]);
  REPEAT j := 1 TO SIZEOF(faces); 
    IF (test_face :=: faces[j]) THEN
      result := TRUE;
    END_IF;
  END_REPEAT;
END_REPEAT;
RETURN(result);
END_FUNCTION;

END_SCHEMA;