(*
   $Id: arm.exp,v 1.23 2005/12/02 13:56:12 liutkus Exp $
   ISO TC184/SC4/WG12 N3435 - ISO/CD-TS 10303-1682 Interconnect 2d shape - EXPRESS ARM
*)

SCHEMA Interconnect_2d_shape_arm;

	USE FROM Fabrication_joint_arm;	-- ISO/TS 10303-1668
	USE FROM Layered_interconnect_module_with_design_intent_modifications_arm;	-- ISO/TS 10303-1699
	USE FROM Physical_unit_2d_design_view_arm;	-- ISO/TS 10303-1724

  TYPE design_intent_modification_planar_shape_select = SELECT
    (Design_intent_modification_styled_area_representation,
     Design_intent_modification_planar_shape_model);
  END_TYPE;

  ENTITY Component_2d_embedded_location
    SUBTYPE OF (Component_2d_location);
      precedent_surface  : Adjacent_stratum_surface_embedded_physical_component_surface_definition;
      subsequent_surface : Adjacent_stratum_surface_embedded_physical_component_surface_definition;
      reference_terminal : Fabrication_joint;
    UNIQUE
      UR1 : precedent_surface,
 reference_terminal,
 subsequent_surface;
    WHERE
      WR1 : precedent_surface <> subsequent_surface;
      WR2 : SELF\Component_2d_location.substrate_location = FALSE;
      WR3 : NOT EXISTS(SELF\Representation_relationship.description);
  END_ENTITY;

  ENTITY Continuous_assembly_component_2d_shape_model
   SUBTYPE OF (Assembly_component_2d_shape_model);
      SELF\Assembly_component_2d_shape_model.shape_characterized_component : SET[1:?] OF Connected_area_component;
  END_ENTITY;

  ENTITY Design_intent_modification_planar_position;
      design_shape   : Physical_unit_planar_shape_model;
      transformation : Axis_placement_2d;
      feature_shape  : design_intent_modification_planar_shape_select;
  END_ENTITY;

  ENTITY Design_intent_modification_planar_shape_model
    SUBTYPE OF (Planar_projected_shape_model);
      represented_design_intent_modification : Design_intent_modification;
    WHERE
      WR1 : NOT EXISTS(SELF\Representation.description);
  END_ENTITY;

  ENTITY Design_intent_modification_styled_area_representation;
      derived_planar_shape                   : OPTIONAL SET[1:?] OF Design_intent_modification_planar_shape_model;
      represented_design_intent_modification : Design_intent_modification;
      shape_styled_area_representation       : fill_area_style_select;
  END_ENTITY;

  ENTITY Discontinuous_assembly_component_2d_shape_model
   SUBTYPE OF (Assembly_component_2d_shape_model);
     SELF\Assembly_component_2d_shape_model.shape_characterized_component : SET[1:?] OF Disconnected_area_component;
  END_ENTITY;

  ENTITY Disconnected_area_component
    SUBTYPE OF (Laminate_component);
      SELF\Definition_based_product_occurrence.derived_from : Fill_area_template;
      stratum_feature_implementation           : SET[1:?] OF Stratum_feature;
  END_ENTITY; -- disconnected_area_component

END_SCHEMA;
