(*
   $Id: mim.exp,v 1.12 2005/12/28 22:19:30 liutkus Exp $
   ISO TC184/SC4/WG12 N3994 - ISO/TS 10303-1682 Interconnect 2d shape - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3436
*)


SCHEMA Interconnect_2d_shape_mim;
	USE FROM Fabrication_joint_mim;	-- ISO/TS 10303-1668
	USE FROM Layered_interconnect_module_with_design_intent_modifications_mim;	-- ISO/TS 10303-1699
	USE FROM Physical_unit_2d_design_view_mim;	-- ISO/TS 10303-1724

END_SCHEMA;


