(******************************************************************************)
(*                                                                            *)
(*        This file was produced by Eurostep GraphicalEXPRESS V1.3.20         *)
(*                                                                            *)
(******************************************************************************)

(* Original model: ap233 wd2.vsd *)
(* Title:  *)
(* Author: Phil Spiby *)
(* Comments:  *)

(*"Function_based_behaviour_arm"  $Id: arm.exp,v 1.2 2005/05/13 18:07:10 abhpf Exp $
ISO TC184/SC4/WG12 N3713 - ISO/WD 10303-1453 Function based behaviour - EXPRESS ARM
* *)
SCHEMA Function_based_behaviour_arm;

USE FROM Behaviour_description_assignment_arm;

USE FROM Extended_task_element_arm;

USE FROM Foundation_representation_arm;

USE FROM Required_resource_arm;

USE FROM Resource_property_assignment_arm;

TYPE fbb_condition_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_item WITH
  (Required_resource_assignment,
   Resource_item_assignment,
   Resource_property);
END_TYPE;

TYPE fbb_required_resource_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON required_resource_item WITH
  (Task_step);
END_TYPE;

TYPE fbb_resource_assignment_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON resource_assignment_item WITH
  (Product,
   Product_version,
   Product_view_definition);
END_TYPE;

TYPE fbb_resource_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON resource_item_select WITH
  (Product,
   Product_version,
   Product_view_definition);
END_TYPE;

TYPE fbb_task_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON task_item WITH
  (Product,
   Product_version,
   Product_view_definition);
END_TYPE;

TYPE functional_behaviour_model = SELECT BASED_ON behaviour_model WITH
  (Functional_model);
END_TYPE;

ENTITY Functional_model
SUBTYPE OF (Representation);
  SELF\Representation.context_of_items : Functional_representation_context;
  SELF\Representation.items : SET [1 : ?] OF Functional_representation_item;
END_ENTITY;

ENTITY Functional_representation_context
SUBTYPE OF (Representation_context);
END_ENTITY;

ENTITY Functional_representation_item
SUBTYPE OF (Representation_item);
  item : Task_element;
END_ENTITY;

END_SCHEMA;

