(*
   $Id: mim.exp,v 1.11 2008/04/06 19:47:17 abhpf Exp $ 
   ISO TC184/SC4/WG3 N2288 - ISO/CD-TS 10303-1453 Function based behaviour - EXPRESS MIM
*)

SCHEMA Function_based_behaviour_mim;

USE FROM Behaviour_description_assignment_mim;

USE FROM Expression_assignment_mim;

USE FROM External_functional_model_mim;

USE FROM General_model_parameter_mim;

USE FROM Required_resource_mim;

USE FROM Resource_property_assignment_mim;

USE FROM Textual_expression_representation_mim;

USE FROM Function_based_behaviour_representation_mim;

USE FROM Condition_mim  
  (condition); 
  
USE FROM External_item_identification_assignment_mim  
  (applied_external_identification_assignment); 

USE FROM File_identification_mim  
  (document_file); 
  
USE FROM Task_element_mim  
  (task_element,
  task_element_relationship,
  task_step); 

TYPE fbb_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_method,
	action_method_relationship,			-- joined from fbb_condition_action_method_items
	action_method_assignment_relationship,
	action_resource,
	action_resource_relationship,			-- joined from fbb_condition_action_method_items
	action_resource_requirement,
	action_resource_requirement_relationship,	-- joined from fbb_condition_action_method_items
	applied_action_method_assignment,
	applied_classification_assignment,
	applied_identification_assignment,
	condition,
	document_file,
	group,
	parameter_value_select,
	product,
	product_definition,
	product_definition_formation,
	product_definition_formation_relationship,
	product_related_product_category,
	property_definition,
	property_definition_representation,
	representation,
	resource_property,
	resource_property_representation,
	task_element,
	task_element_relationship,			-- joined from fbb_condition_action_method_items
	task_step);
END_TYPE;

(* joined with "BASED_ON action_method_items"
TYPE fbb_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(action_method,
	action_method_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	property_definition,
	resource_property,
	task_element_relationship);
END_TYPE;
*)

TYPE fbb_assignment_target_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON assignment_target_select WITH
	(condition);
END_TYPE;

TYPE fbb_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(action_method,
	action_method_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	class,
	context_dependent_unit,
	conversion_based_unit,
	derived_unit,
	document_file,
	external_class_library,
	general_property,
	general_property_relationship,
	measure_with_unit,
	named_unit,
	product,
	product_category,
	product_definition,
	product_definition_context,
	product_definition_formation,
	product_definition_formation_relationship,
	representation,
	representation_context,
	representation_item,
	resource_property,
	resource_property_representation,
	uncertainty_measure_with_unit);
END_TYPE;

TYPE fbb_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(action_method,
	action_method_relationship,
	action_resource,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	applied_external_identification_assignment,
	condition,
	document_file,
	external_class_library,
	general_property,
	general_property_relationship,
	product,
	product_category,
	product_definition,
	product_definition_formation,
	representation,
	resource_property,
	task_element,
	task_element_relationship,
	task_step);
END_TYPE;

--??
(*TYPE fbb_characterized_resource_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_resource_select WITH
	(action_resource_requirement,
	action_resource,
	action_method,			-- Error, not in in the characterized_resource_definition list of process_property_schema
	action_resource_relationship);
END_TYPE;

is captured by:*)

(* HPF - It appears that these ENITIY's are not needed.  Mapping should be totally in mapping table. 
	For template example see the 3 resource_xxxx_characterized modules.
	Also see SCHEMA process_property_schema;
		TYPE characterized_resource_definition = SELECT
		   (action_resource,
		    action_resource_relationship,
		    action_resource_requirement,
		    action_resource_requirement_relationship);
		END_TYPE;
		
		ENTITY resource_property;
		  name : label;
		  description : text;
		  resource : characterized_resource_definition;
		END_ENTITY;
	All but Resource_item_assignment which maps to action_method can be covered in mappng table.
	Since characterized_object not in characterized_resource_definition list 
	ENTITY fbb_characterized_action_method is not a valid.usage of characterized_object.

ENTITY fbb_characterized_action_method
  SUBTYPE OF (action_method, characterized_object);
END_ENTITY;

ENTITY fbb_characterized_action_resource
  SUBTYPE OF (action_resource, characterized_object);
END_ENTITY;

ENTITY fbb_characterized_action_resource_relationship
  SUBTYPE OF (action_resource_relationship, characterized_object);
END_ENTITY;

ENTITY fbb_characterized_action_resource_requirement
  SUBTYPE OF (action_resource_requirement, characterized_object);
END_ENTITY;
*)

(*TYPE fbb_ap233_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(applied_action_method_assignment,
	generic_expression,
	general_property,
	general_property_relationship,
	product,
	product_category,
	product_definition_formation,
	product_definition_formation_relationship,
	property_definition,
	property_definition_representation,
	representation,
	representation_context,
	representation_item);
END_TYPE;

is captured by:*)

ENTITY fbb_characterized_applied_action_method_assignment
  SUBTYPE OF (characterized_object, applied_action_method_assignment);
END_ENTITY;

ENTITY fbb_characterized_generic_expression	
  SUBTYPE OF (characterized_object, generic_expression);
END_ENTITY;

ENTITY fbb_characterized_general_property
  SUBTYPE OF (characterized_object, general_property);
END_ENTITY;

ENTITY fbb_characterized_general_property_relationship
  SUBTYPE OF (characterized_object, general_property_relationship);
END_ENTITY;

ENTITY fbb_characterized_product
  SUBTYPE OF (characterized_object, product);
END_ENTITY;

ENTITY fbb_characterized_product_category
  SUBTYPE OF (characterized_object, product_category);
END_ENTITY;

ENTITY fbb_characterized_product_definition_formation
  SUBTYPE OF (characterized_object, product_definition_formation);
END_ENTITY;

ENTITY fbb_characterized_product_definition_formation_relationship
  SUBTYPE OF (characterized_object, product_definition_formation_relationship);
END_ENTITY;

ENTITY fbb_characterized_property_definition
  SUBTYPE OF (characterized_object, property_definition);
END_ENTITY;

ENTITY fbb_characterized_property_definition_representation
  SUBTYPE OF (characterized_object, property_definition_representation);
END_ENTITY;

ENTITY fbb_characterized_representation
  SUBTYPE OF (characterized_object, representation);
END_ENTITY;

ENTITY fbb_characterized_representation_context
  SUBTYPE OF (characterized_object, representation_context);
END_ENTITY;

ENTITY fbb_characterized_representation_item
  SUBTYPE OF (characterized_object, representation_item);
END_ENTITY;

TYPE functional_groupable_item = SELECT BASED_ON groupable_item WITH
  (functional_model);
END_TYPE;

  
END_SCHEMA;

