(*
 $Id: checkModuleMain.js,v 1.16 2005/03/09 01:07:43 thendrix Exp $
 ISO TC184/SC4/WG12 N6040 - ISO/CD-TS 10303-1398 Identification relationship - EXPRESS MIM
*) 


SCHEMA Identification_relationship_mim;

USE FROM Identification_assignment_mim;    -- ISO/TS 10303-1021

USE FROM management_resources_schema   -- ISO 10303-41
  (identification_assignment_relationship); 


END_SCHEMA;  -- Identification_relationship_mim
