(*

  WG12N9999 - ISO 10303-41ed3 qualification_schema: 3rd Edition

*)


SCHEMA qualifications_schema; 


ENTITY qualification_type;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

ENTITY qualification_type_relationship;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
  related_qualification_type : qualification_type;
  relating_qualification_type : qualification_type;
END_ENTITY;

END_SCHEMA;  -- qualifications_schema
