(*
   $Id: arm.exp,v 1.9 2007/11/28 12:58:17 liutkus Exp $
   ISO TC184/SC4/WG12 N4230 - ISO/TS 10303-1762 Generic product occurrence - EXPRESS ARM
*)

SCHEMA Generic_product_occurrence_arm;

	USE FROM Product_view_definition_arm;	-- ISO/TS 10303-1019
	USE FROM Value_with_unit_arm;	-- ISO/TS 10303-1054	
	USE FROM Extended_measure_representation_arm;	-- ISO/TS 10303-1106	
	USE FROM Specified_product_arm;	-- ISO/TS 10303-1104	

TYPE extended_value_with_unit = EXTENSIBLE SELECT (
     Value_with_unit, 
     Value_limit, 
     Value_range);
END_TYPE;

END_SCHEMA;
