(*
   $Id: arm.exp,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   N - ISO/CD-TS - 10303- Generic product occurrence - EXPRESS ARM
*)

SCHEMA Generic_product_occurrence_arm;

	USE FROM Assembly_structure_arm;	-- ISO/TS 10303-1026
	USE FROM Extended_measure_representation_arm;	-- ISO/TS 10303-1106
	USE FROM Measure_representation_arm;	-- ISO/TS 10303-1118
	USE FROM Product_view_definition_relationship_arm;	-- ISO/TS 10303-1041
	USE FROM Value_with_unit_arm;	-- ISO/TS 10303-1054
	USE FROM Specified_product_arm;	-- ISO/TS 10303-1104


SUBTYPE_CONSTRAINT alternate_product_instance FOR Product_occurrence;
  ONEOF (Single_instance,
         Quantified_instance,
         Selected_instance) 
  AND
  ONEOF (Definition_based_product_occurrence,
         Specification_based_product_occurrence);
END_SUBTYPE_CONSTRAINT;

TYPE extended_value_with_unit = SELECT (
     Value_with_unit, 
     Value_limit, 
     Value_range);
END_TYPE;

	ENTITY Definition_based_product_occurrence
		ABSTRACT SUPERTYPE
		SUBTYPE OF (Product_occurrence);
  		derived_from: Product_view_definition;
  	WHERE
			WR1: SELF\Product_view_definition.defined_version = derived_from.defined_version;
	END_ENTITY;

ENTITY Product_occurrence
ABSTRACT SUPERTYPE OF (ONEOF (Single_instance, Quantified_instance))
SUBTYPE OF (Product_view_definition);
INVERSE
  occurrence_contexts: SET[1:?] OF View_definition_relationship FOR related_view;
END_ENTITY;

ENTITY Product_occurrence_with_quantity
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (Product_occurrence);
  occurrence_quantity : OPTIONAL extended_value_with_unit;
END_ENTITY;

ENTITY Quantified_instance
  SUBTYPE OF (Product_occurrence_with_quantity);
  SELF\Product_occurrence_with_quantity.occurrence_quantity : Value_with_unit;
END_ENTITY;

ENTITY Selected_instance
  SUBTYPE OF (Product_occurrence_with_quantity);
  quantity_criterion : OPTIONAL STRING;
END_ENTITY;

ENTITY Single_instance
  SUBTYPE OF (Product_occurrence);
END_ENTITY;

ENTITY Specification_based_product_occurrence
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (Product_occurrence);
  SELF\Product_view_definition.defined_version : Specification_based_product_version;
END_ENTITY;
-- IP1: further specializations of this entity have to ensure that:

END_SCHEMA;
