(*
 $Id: arm.exp,v 1.7 2004/11/19 21:37:40 robbod Exp $
 ISO TC184/SC4/WG12 N???? - ISO/TS 10303-1142 Requirement view definition relationship - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N3136
*) 


SCHEMA Requirement_view_definition_relationship_arm;

USE FROM Product_view_definition_relationship_arm;    -- ISO/TS 10303-1041

USE FROM Requirement_view_definition_arm;    -- ISO/TS 10303-1141

ENTITY Requirement_collection_relationship
SUBTYPE OF (Requirement_view_definition_relationship);
  SELF\Requirement_view_definition_relationship.primary RENAMED collection : Requirement_view_definition;
  SELF\Requirement_view_definition_relationship.secondary RENAMED member : Requirement_view_definition;
END_ENTITY;

ENTITY Requirement_view_definition_relationship
SUBTYPE OF (View_definition_relationship);
  SELF\View_definition_relationship.relating_view RENAMED primary : Requirement_view_definition;
  SELF\View_definition_relationship.related_view RENAMED secondary : Requirement_view_definition;
WHERE
    WR1: primary :<>: secondary;
END_ENTITY;

ENTITY Tracing_relationship
SUBTYPE OF (Requirement_view_definition_relationship);
  SELF\Requirement_view_definition_relationship.primary RENAMED traces_from : Requirement_view_definition;
  SELF\Requirement_view_definition_relationship.secondary RENAMED traces_to : Requirement_view_definition;
END_ENTITY;

END_SCHEMA;  -- Requirement_view_definition_relationship_arm

