(*
 $Id: mim.exp,v 1.11 2011/08/13 13:23:18 lothartklein Exp $
 ISO TC184/SC4/WG12 N6133 - ISO/TS 10303-1142 Requirement view definition relationship - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N6133
*) 


SCHEMA Requirement_view_definition_relationship_mim;

USE FROM Product_view_definition_relationship_mim;    -- ISO/TS 10303-1041
USE FROM Requirement_view_definition_mim;    -- ISO/TS 10303-1141

END_SCHEMA;  -- Requirement_view_definition_relationship_mim

