(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Interconnect module connection routing - EXPRESS MIM
*)


SCHEMA Interconnect_module_connection_routing_mim;
	USE FROM Fabrication_joint_mim;
	USE FROM Functional_design_elaboration_mim;
	USE FROM Layered_interconnect_module_with_design_intend_modifications_mim;
END_SCHEMA;

