(*
  $Id:$
*) 
{ iso standard 10303 part (11) version (4) }

SCHEMA Independent_property_arm;

   ENTITY Independent_property;
      description : OPTIONAL STRING;
      id : STRING;
      property_type : STRING;
   END_ENTITY;

   ENTITY Independent_property_relationship;
      description : OPTIONAL STRING;
      related : Independent_property;
      relating : Independent_property;
      relation_type : STRING;
   END_ENTITY;

END_SCHEMA;

