(*
   $Id: mim.exp,v 1.20 2006/01/20 08:43:42 liutkuviene Exp $
   ISO TC184/SC4/WG12 N4123 - ISO/TS 10303-1725 Physical unit 3d design view - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3562
*)


SCHEMA Physical_unit_3d_design_view_mim;

	USE FROM Layered_3d_shape_mim;	-- ISO/TS 10303-1694
	USE FROM Part_template_shape_with_parameters_mim;  -- ISO/TS 10303-1720	
	USE FROM Physical_unit_design_view_mim;	-- ISO/TS 10303-1728	
	-- Needed by the mapping
	USE FROM aic_manifold_surface (manifold_surface_shape_representation); -- ISO 10303-511 
	
ENTITY component_3d_location
  SUBTYPE OF (context_dependent_shape_representation, shape_representation_relationship, representation_relationship_with_transformation, definitional_representation_relationship);
END_ENTITY;

END_SCHEMA;


