./checkUsingAnt.sh activity_as_realized
./checkUsingAnt.sh analysis_assignment
./checkUsingAnt.sh analysis_identification
./checkUsingAnt.sh ap239_document_management
./checkUsingAnt.sh ap239_management_resource_information
./checkUsingAnt.sh ap239_part_definition_information
./checkUsingAnt.sh ap239_product_definition_information
./checkUsingAnt.sh ap239_product_life_cycle_support
./checkUsingAnt.sh ap239_task_specification_resourced
./checkUsingAnt.sh ap239_work_definition
./checkUsingAnt.sh approval
./checkUsingAnt.sh assembly_structure
./checkUsingAnt.sh basic_geometry
./checkUsingAnt.sh collection_identification_and_version
./checkUsingAnt.sh conditional_effectivity
./checkUsingAnt.sh configuration_effectivity
./checkUsingAnt.sh configuration_item
./checkUsingAnt.sh contract
./checkUsingAnt.sh document_and_version_identification
./checkUsingAnt.sh document_management
./checkUsingAnt.sh document_properties
./checkUsingAnt.sh identification_relationship
./checkUsingAnt.sh information_rights
./checkUsingAnt.sh interface
./checkUsingAnt.sh justification
./checkUsingAnt.sh message
./checkUsingAnt.sh observation
./checkUsingAnt.sh part_and_version_identification
./checkUsingAnt.sh product_as_individual
./checkUsingAnt.sh product_categorization
./checkUsingAnt.sh product_environment_definition
./checkUsingAnt.sh product_environment_observed
./checkUsingAnt.sh product_identification
./checkUsingAnt.sh required_resource
./checkUsingAnt.sh required_resource_characterized
./checkUsingAnt.sh requirement_assignment
./checkUsingAnt.sh requirement_identification_and_version
./checkUsingAnt.sh requirement_management
./checkUsingAnt.sh requirement_view_definition_relationship
./checkUsingAnt.sh resource_as_realized
./checkUsingAnt.sh resource_as_realized_characterized
./checkUsingAnt.sh resource_item
./checkUsingAnt.sh resource_item_characterized
./checkUsingAnt.sh resource_management
./checkUsingAnt.sh resource_management_characterized
./checkUsingAnt.sh same_as_external_item
./checkUsingAnt.sh single_part_representation
./checkUsingAnt.sh state_characterized
./checkUsingAnt.sh system_identification_and_version
./checkUsingAnt.sh task_specification
./checkUsingAnt.sh verification_and_validation

