./checkNumber.sh activity_as_realized
./checkNumber.sh analysis_assignment
./checkNumber.sh analysis_identification
./checkNumber.sh ap239_document_management
./checkNumber.sh ap239_management_resource_information
./checkNumber.sh ap239_part_definition_information
./checkNumber.sh ap239_product_definition_information
./checkNumber.sh ap239_product_life_cycle_support
./checkNumber.sh ap239_task_specification_resourced
./checkNumber.sh ap239_work_definition
./checkNumber.sh approval
./checkNumber.sh assembly_structure
./checkNumber.sh basic_geometry
./checkNumber.sh collection_identification_and_version
./checkNumber.sh conditional_effectivity
./checkNumber.sh configuration_effectivity
./checkNumber.sh configuration_item
./checkNumber.sh contract
./checkNumber.sh document_and_version_identification
./checkNumber.sh document_management
./checkNumber.sh document_properties
./checkNumber.sh identification_relationship
./checkNumber.sh information_rights
./checkNumber.sh interface
./checkNumber.sh justification
./checkNumber.sh message
./checkNumber.sh observation
./checkNumber.sh part_and_version_identification
./checkNumber.sh product_as_individual
./checkNumber.sh product_categorization
./checkNumber.sh product_environment_definition
./checkNumber.sh product_environment_observed
./checkNumber.sh product_identification
./checkNumber.sh required_resource
./checkNumber.sh required_resource_characterized
./checkNumber.sh requirement_assignment
./checkNumber.sh requirement_identification_and_version
./checkNumber.sh requirement_management
./checkNumber.sh requirement_view_definition_relationship
./checkNumber.sh resource_as_realized
./checkNumber.sh resource_as_realized_characterized
./checkNumber.sh resource_item
./checkNumber.sh resource_item_characterized
./checkNumber.sh resource_management
./checkNumber.sh resource_management_characterized
./checkNumber.sh same_as_external_item
./checkNumber.sh single_part_representation
./checkNumber.sh state_characterized
./checkNumber.sh system_identification_and_version
./checkNumber.sh task_specification
./checkNumber.sh verification_and_validation

