
SCHEMA Ap203e2_config_control_3d_design_module_arm;

USE FROM Advanced_boundary_representation_arm ;
USE FROM Ap203e2_configuration_management_arm;
USE FROM Associative_text_arm ;
USE FROM Construction_geometry_arm;
USE FROM Constructive_solid_geometry_3d_arm;
USE FROM Default_tolerance_arm ;
USE FROM Derived_shape_element_arm ;
USE FROM Dimension_tolerance_arm ;
USE FROM Document_management_arm;
USE FROM Edge_based_wireframe_arm;
USE FROM Faceted_boundary_representation_arm;
USE FROM Geometric_tolerance_arm ;
USE FROM Geometric_validation_property_representation_arm ;
USE FROM Geometrically_bounded_surface_arm;
USE FROM Geometrically_bounded_wireframe_arm;
USE FROM Incomplete_data_reference_mechanism_arm;
USE FROM Manifold_surface_arm;
USE FROM Product_structure_arm ;
USE FROM Shape_appearance_layers_arm;
USE FROM Shell_based_wireframe_arm;
USE FROM Work_management_arm;

END_SCHEMA; -- Ap203e2_config_control_3d_design_module_arm
