SCHEMA nut_and_bolt_2_schema; 

USE FROM nut_and_bolt_1_schema;    -- ISO 10303-88


TYPE applied_symmetry_select = SELECT BASED_ON select_space_or_element WITH 
   (gift, 
    grift, 
    sift);
END_TYPE; 

ENTITY gift
  SUBTYPE OF (generic_symmetry);
END_ENTITY;

--test
ENTITY grift
  SUBTYPE OF (generic_symmetry);
END_ENTITY;

ENTITY sift
  SUBTYPE OF (generic_symmetry);
END_ENTITY;

END_SCHEMA;  -- nut_and_bolt_2_schema
