(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 package functional and physical characterization - EXPRESS ARM
*)

SCHEMA Ap210_package_functional_and_physical_characterization_arm;
   USE FROM AP210_product_data_management_arm;
   USE FROM Characteristic_arm;   
   USE FROM Chemical_substance_arm;   
   USE FROM Package_arm;
   USE FROM Part_feature_grouping_arm;   
END_SCHEMA;

