(*
   $Id: arm.exp,v 1.8 2005/06/07 12:55:21 budreckytej Exp $
   ISO TC184/SC4/WG3 N1677 - ISO/CD-TS 10303-1626 Ap210 physical unit physical characterization - EXPRESS ARM
*)

SCHEMA Ap210_physical_unit_physical_characterization_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Part_feature_grouping_arm;	-- ISO/TS 10303-1713
   -- look to IS what to add further
END_SCHEMA;

