(*
 $Id: mim.exp,v 1.9 2003/10/13 10:58:38 leifgyllstrom Exp $
 ISO TC184/SC4/WG12 N2415 - ISO/TS 10303-1267 Required resource - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N1467
*) 


SCHEMA Required_resource_mim; 

USE FROM action_schema   -- ISO 10303-41
  (action_method); 

USE FROM Activity_method_assignment_mim   -- ISO/TS 10303-1249
  (applied_action_method_assignment); 

USE FROM Classification_assignment_mim;    -- ISO/TS 10303-1114

USE FROM management_resources_schema   -- ISO 10303-41
  (action_method_assignment,
   action_method_role); 

USE FROM Measure_representation_mim;    -- ISO/TS 10303-1118

USE FROM process_property_schema   -- ISO 10303-49
  (action_resource_requirement,
   action_resource_requirement_relationship,
   characterized_action_definition,
   characterized_resource_definition,
   requirement_for_action_resource,
   resource_property,
   resource_requirement_type); 

USE FROM Resource_item_mim;    -- ISO/TS 10303-1268


TYPE required_resource_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH 
   (action_method, 
    action_resource_requirement, 
    action_resource_requirement_relationship);
END_TYPE; 

END_SCHEMA;  -- Required_resource_mim

