(*
 $Id: arm.exp,v 1.2 2002/10/02 13:12:22 robbod Exp $
 ISO TC184/SC4/WG12 N2282 - ISO/TS 10303-1340 Name assignment - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1405
*) 


SCHEMA Name_assignment_arm; 


TYPE assigned_name_select = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

ENTITY Name_assignment;
  name : STRING;
  role : STRING;
  items : assigned_name_select;
END_ENTITY;

END_SCHEMA;  -- Name_assignment_arm

