(*
 $Id: mim.exp,v 1.2 2002/10/02 12:18:39 robbod Exp $
 ISO TC184/SC4/WG12 N1406 - ISO/CD-TS 10303-1340 Name assignment - EXPRESS MIM
*) 


SCHEMA Name_assignment_mim; 

USE FROM management_resources_schema   -- ISO 10303-41
  (name_assignment); 

TYPE name_item = EXTENSIBLE SELECT;
END_TYPE; 

ENTITY applied_name_assignment
  SUBTYPE OF (name_assignment);
  items : name_item;
END_ENTITY;

END_SCHEMA;  -- Name_assignment_mim
