-- Generated on 01/10/2012 15:36:23 by ExpressPrettyPrint version: 4.0.0.47, PDTec AG
-- From: Harmonized AP242 BO Model.exp

SCHEMA AP242_BusinessObjectModel;


CONSTANT
  SCHEMA_NAME : STRING := 'AP242_BUSINESSOBJECTMODEL.';
END_CONSTANT;


TYPE ActivityAssignmentSelect = SELECT(
  Activity,
  ActivityMethod,
  ActivityRelationship,
  AlternatePartRelationship,
  AlternativeSolution,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownVersion,
  ClassCategoryAssociation,
  ClassConditionAssociation,
  ClassInclusionAssociation,
  ClassSelect,
  ClassSpecificationAssociation,
  Configuration,
  Document,
  DocumentDefinition,
  DocumentVersion,
  Effectivity,
  Event,
  File,
  GeometricModel,
  IndividualAssemblyRelationship,
  IndividualPartView,
  ManufacturingConfiguration,
  MaterialIdentification,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartVersion,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  ProjectAssignment,
  ProjectRelationship,
  PropertyDefinitionAssignment,
  PropertyValue,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  RequirementView,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  StyledModel
);
END_TYPE;

TYPE ActivityMethodAssignmentSelect = SELECT(
  Activity,
  ActivityAssignment,
  ActivityMethod,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionRelationship,
  Contract,
  Document,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  File,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  Organization,
  Part,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  PropertyValueAssignment,
  PropertyValueAssignmentRelationship,
  PropertyValueRelationship,
  Requirement,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  WorkRequest
);
END_TYPE;

TYPE AngleSelect = SELECT(
  CoordinateSystem,
  Direction,
  ExternalCurve,
  ExternalPointPath
);
END_TYPE;

TYPE ApplicationDomainSelect = SELECT(
  ApplicationDomain,
  ProxySelect
);
END_TYPE;

TYPE ApprovalAssignmentSelect = SELECT(
  Activity,
  ActivityAssignment,
  ActivityMethodAssignment,
  AlternatePartRelationship,
  AlternativeSolution,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownVersion,
  Certification,
  ClassCategoryAssociation,
  ClassConditionAssociation,
  ClassInclusionAssociation,
  ClassSelect,
  ClassSpecificationAssociation,
  Classification,
  Configuration,
  Contract,
  Document,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  Effectivity,
  ExternalClassSystem,
  File,
  GeometricModel,
  IndividualAssemblyRelationship,
  IndividualPartTestResult,
  IndividualPartView,
  InformationUsageRight,
  InformationUsageRightAssignment,
  ManufacturingConfiguration,
  MaterialIdentification,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  PropertyDefinitionSelect,
  PropertyValue,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  RequirementAssignment,
  RequirementView,
  SecurityClassification,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  StyledModel,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE AssignedDocumentSelect = SELECT(
  Document,
  DocumentDefinition,
  DocumentVersion,
  File
);
END_TYPE;

TYPE BoundaryClassZoneSelect = SELECT(
  ExternalLoop,
  GeometricBoundingCurveSelect
);
END_TYPE;

TYPE BreakdownAssignmentSelect = SELECT(
  DocumentDefinition,
  IndividualPartView,
  PartOccurrence,
  PartView,
  ProductClass,
  ProductConfiguration,
  RequirementView
);
END_TYPE;

TYPE BreakdownElementOrAlternativeSolutionSelect = SELECT(
  AlternativeSolution,
  BreakdownElement
);
END_TYPE;

TYPE BreakdownElementOrPartOccurrenceSelect = SELECT(
  BreakdownElement,
  PartOccurrence
);
END_TYPE;

TYPE CertificationAssignmentSelect = SELECT(
  AlternatePartRelationship,
  PartOccurrence,
  PartVersion,
  PartVersionRelationship,
  SupplierSolution
);
END_TYPE;

TYPE CharacterString = STRING;
END_TYPE;

TYPE ClassSelect = SELECT(
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass
);
END_TYPE;

TYPE ClassString = STRING;
END_TYPE;

TYPE ComponentClassForAssemblySelect = SELECT(
  CompositeAssembly,
  FilamentLaminate,
  Ply,
  PlyLaminate,
  ProcessedCore
);
END_TYPE;

TYPE CompositeAssemblyShapeSelect = SELECT(
  ExternalAdvancedBrepShapeRepresentation,
  ExternalEdgeBasedWireframeShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation,
  ExternalGeometricallyBoundedSurfaceShapeRepresentation,
  ExternalGeometricallyBoundedWireframeShapeRepresentation,
  ExternalManifoldSurfaceShapeRepresentation,
  ExternalShellBasedWireframeShapeRepresentation,
  ThreeDGeometrySet
);
END_TYPE;

TYPE ConfiguredItemSelect = SELECT(
  AlternativeSolution,
  BreakdownElement,
  PartOccurrence,
  ProcessOperationOccurrence,
  ProcessPlan
);
END_TYPE;

TYPE ConfiguredSpecificationSelect = SELECT(
  ClassConditionAssociation,
  ClassSpecificationAssociation
);
END_TYPE;

TYPE ContractAssignmentSelect = SELECT(
  Activity,
  AlternativeSolution,
  BreakdownElement,
  DocumentVersion,
  InformationUsageRight,
  Organization,
  PartVersion,
  PersonInOrganization,
  ProductConfiguration,
  WorkOrder
);
END_TYPE;

TYPE coordinateTypeEnum = ENUMERATION OF(
  cartesian,
  cylindrical,
  spherical,
  polar,
  linear
);
END_TYPE;

TYPE CoreShapeSelect = SELECT(
  BeveledSheetRepresentation,
  ExternalAdvancedBrepShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation
);
END_TYPE;

TYPE DateTimeAssignmentSelect = SELECT(
  Event,
  GeneralOrganizationalDataSelect
);
END_TYPE;

TYPE DateTimePersonOrganizationElementSelect = SELECT(
  Event,
  GeneralOrganizationalDataSelect
);
END_TYPE;

TYPE DateTimeString = STRING;
END_TYPE;

TYPE DeltaChangeManagementObjectSelect = SELECT(
  ActivityAssignmentSelect,
  EventAssignment
);
END_TYPE;

TYPE DeltaChangeRelationshipSelect = SELECT(
  AlternativeSolutionRelationship,
  BreakdownElementVersionRelationship,
  DocumentVersionRelationship,
  PartVersionRelationship,
  ProcessOperationOccurrenceRelationship,
  ProcessPlanRelationship,
  ReplacedPartViewRelationship,
  ReplacedUsageRelationship,
  RequirementVersionRelationship,
  ShapeElementRelationship
);
END_TYPE;

TYPE DescriptorSelect = SELECT(
  Descriptor,
  DescriptorSet,
  MultiLingualStringSelect
);
END_TYPE;

TYPE DescriptorSet = SET[2:?] OF Descriptor;
END_TYPE;

TYPE DocumentAssignmentSelect = SELECT(
  Activity,
  ActivityAssignment,
  ActivityMethod,
  AlternativeSolution,
  Approval,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Certification,
  ClassAttribute,
  ClassSelect,
  Contract,
  DeltaChange,
  ExternalClassSystem,
  ExternalItem,
  IndividualAssemblyRelationship,
  IndividualPartTestResult,
  IndividualPartView,
  InformationRight,
  InformationUsageRight,
  InformationUsageRightRelationship,
  MaterialIdentification,
  Organization,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartShape,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  Person,
  ProcessOperationOccurrence,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionSelect,
  PropertyValue,
  RealizationOrOccurrenceRelationship,
  RequirementView,
  RetentionPeriod,
  SecurityClassification,
  ShapeElement,
  ShapeElementRelationship,
  Specification,
  SpecificationCategory,
  SurfaceCondition,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE EffectivityAssignmentSelect = SELECT(
  AlternativeSolution,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersionRelationship,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  ClassCategoryAssociation,
  ClassConditionAssociation,
  ClassInclusionAssociation,
  ClassSelect,
  ClassSpecificationAssociation,
  Configuration,
  Document,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  ExternalClassSystem,
  File,
  GeometricModel,
  IdentifierSelect,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartVersion,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  ProcessOperationDefinition,
  ProcessOperationDefinitionRelationship,
  ProcessOperationOccurrence,
  ProcessOperationOccurrenceRelationship,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  PropertyDefinitionAssignment,
  PropertyDefinitionSelect,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  SecurityClassification,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  StyledModel
);
END_TYPE;

TYPE EvaluationResultEnum = ENUMERATION OF(
  fail,
  pass,
  undefined
);
END_TYPE;

TYPE EvaluationStatusEnum = ENUMERATION OF(
  invalid,
  not_evaluatable,
  to_be_evaluated,
  valid
);
END_TYPE;

TYPE EventOrDateSelect = SELECT(
  DateTimeString,
  EVENT
);
END_TYPE;

TYPE ExplicitTransformationSelect = SELECT(
  ExplicitTransformation2d,
  ExplicitTransformation3d
);
END_TYPE;

TYPE ExternalSourceSelect = SELECT(
  DigitalFile,
  Document,
  IdentifierSelect
);
END_TYPE;

TYPE FinalDefinitionSelect = SELECT(
  IndividualPartView,
  PartView,
  RequirementView
);
END_TYPE;

TYPE GeneralOrganizationalDataSelect = SELECT(
  Activity,
  ActivityAssignment,
  ActivityMethodWorkRequestAssociation,
  AlternatePartRelationship,
  AlternativeSolution,
  AlternativeSolutionRelationship,
  Approval,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersionRelationship,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  Certification,
  ClassCategoryAssociation,
  ClassConditionAssociation,
  ClassInclusionAssociation,
  ClassSelect,
  ClassSpecificationAssociation,
  Classification,
  Configuration,
  Contract,
  Document,
  DocumentDefinition,
  DocumentVersion,
  ExternalClassSystem,
  File,
  GeometricModel,
  IdentifierSelect,
  IndividualAssemblyRelationship,
  IndividualPartTestResult,
  IndividualPartView,
  InformationUsageRight,
  ManufacturingConfiguration,
  MaterialIdentification,
  Organization,
  OrganizationRelationship,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  PersonInOrganization,
  PersonInOrganizationRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  PropertyDefinitionSelect,
  PropertyValue,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  RequirementView,
  SecurityClassification,
  SecurityClassificationAssignment,
  SetMembership,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  StyledModel,
  SubSetMember,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE GeometricBoundingCurveSelect = SELECT(
  ExternalCompositeCurveOnSurface,
  ExternalPcurve,
  ExternalSurfaceCurve
);
END_TYPE;

TYPE GeometricModelOrExternalRepresentationSelect = SELECT(
  ExternalRepresentation,
  GeometricModel
);
END_TYPE;

TYPE IdentificationContextSelect = SELECT(
  Identifier,
  Organization
);
END_TYPE;

TYPE IdentifierSelect = SELECT(
  IdentifierSet,
  SingleIdentifierSelect
);
END_TYPE;

TYPE IdentifierSet = SET[2:?] OF Identifier;
END_TYPE;

TYPE IdentifierString = STRING;
END_TYPE;

TYPE IndividualAssemblyRelationshipRealizationContextSelect = SELECT(
  AssemblyViewRelationship,
  PartOccurrence
);
END_TYPE;

TYPE InformationUsageRightAssignmentSelect = SELECT(
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodWorkRequestAssociation,
  AlternatePartRelationship,
  AlternativeSolution,
  AlternativeSolutionRelationship,
  Approval,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  Certification,
  ClassConditionAssociation,
  ClassInclusionAssociation,
  ClassSelect,
  ClassSpecificationAssociation,
  Classification,
  Configuration,
  Contract,
  DeltaChange,
  Document,
  DocumentDefinition,
  DocumentVersion,
  ExternalClassSystem,
  ExternalItem,
  File,
  GeometricModel,
  IdentifierSelect,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartView,
  InformationRight,
  InformationUsageRight,
  InformationUsageRightRelationship,
  ManufacturingConfiguration,
  MaterialIdentification,
  Organization,
  OrganizationRelationship,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartShape,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  PersonInOrganizationRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  PropertyDefinitionSelect,
  PropertyValue,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  Requirement,
  RequirementVersion,
  RequirementView,
  RetentionPeriod,
  SecurityClassification,
  SecurityClassificationAssignment,
  ShapeElement,
  ShapeElementRelationship,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  StyledModel,
  SurfaceCondition,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE InZoneSelect = SELECT(
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodWorkRequestAssociation,
  BreakdownElementView,
  DocumentDefinition,
  IndividualPartView,
  PartView,
  RequirementView
);
END_TYPE;

TYPE Language = ProxySelect;
END_TYPE;

TYPE LengthMeasure = REAL;
END_TYPE;

TYPE LifeCycleStageSelect = SELECT(
  LifeCycleStage,
  ProxySelect
);
END_TYPE;

TYPE MatingTypeEnum = ENUMERATION OF(
  bolted_joint,
  brazing,
  clasping,
  clinching,
  clipping,
  doweling,
  flanging,
  foam_injection,
  gluing,
  laser_welding,
  press_fit,
  riveting,
  sewing,
  spot_welding,
  stapling,
  welding,
  soldering,
  friction_welding
);
END_TYPE;

TYPE MeasureActivitySelect = SELECT(
  Activity,
  ProcessOperationOccurrence
);
END_TYPE;

TYPE ModelPropertyValueSelect = SELECT(
  GeometricModel,
  StyledModel
);
END_TYPE;

TYPE MultiLingualStringSelect = SELECT(
  CharacterString,
  LocalizedString,
  TranslatedStringSet
);
END_TYPE;

TYPE OrientedSurfaceSelect = SELECT(
  ExternalOrientedSurface,
  ExternalSurface
);
END_TYPE;

TYPE PartInformationSelect = SELECT(
  BreakdownElement,
  IndividualPartView,
  PartOccurrence,
  PartView
);
END_TYPE;

TYPE PartOccurrenceDefinitionSelect = SELECT(
  PartView,
  ProductConfiguration
);
END_TYPE;

TYPE PartOccurrenceUsageContextSelect = SELECT(
  PartViewOccurrenceRelationship,
  ProcessOperationInputOrOutput,
  RealizationOrOccurrenceRelationship
);
END_TYPE;

TYPE PartVersionOrProductConfgurationSelect = SELECT(
  PartVersion,
  ProductConfiguration
);
END_TYPE;

TYPE PartViewOrProductConfgurationSelect = SELECT(
  PartView,
  ProductConfiguration
);
END_TYPE;

TYPE PeriodOrDateSelect = SELECT(
  DateTimeString,
  Duration,
  EVENT
);
END_TYPE;

TYPE PersonOrganizationSelect = SELECT(
  Organization,
  PersonInOrganization
);
END_TYPE;

TYPE PersonOrOrganizationSelect = SELECT(
  Organization,
  PersonInOrganization
);
END_TYPE;

TYPE PhysicalElementSelect = SELECT(
  AlternativeSolution,
  BreakdownElement,
  PartView
);
END_TYPE;

TYPE PlyLaminateShapeSelect = SELECT(
  CompositeSheetRepresentation,
  ExternalAdvancedBrepShapeRepresentation,
  ExternalCsgShapeRepresentation,
  ExternalCurveSweptSolidShapeRepresentation,
  ExternalElementaryBrepShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation,
  ExternalTessellatedShapeRepresentation,
  ThreeDGeometrySet
);
END_TYPE;

TYPE PointSelect = SELECT(
  CartesianPoint,
  ExternalDegeneratePcurve,
  ExternalPointOnCurve,
  ExternalPointOnSurface
);
END_TYPE;

TYPE ProcessOperationInputOrOutputSelect = SELECT(
  AssemblyOccurrenceRelationship,
  AssemblyViewRelationship,
  PartOccurrence,
  PartVersion
);
END_TYPE;

TYPE ProcessOperationResourceAssignmentSelect = SELECT(
  BreakdownElement,
  IndividualPartView,
  PartOccurrence,
  PartVersion,
  RequirementView
);
END_TYPE;

TYPE ProjectAssignmentSelect = SELECT(
  Activity,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownVersion,
  Document,
  DocumentVersion,
  IndividualPartView,
  Part,
  PartOccurrence,
  PartVersion,
  ProductClass,
  ProductConfiguration
);
END_TYPE;

TYPE PropertyAssignmentSelect = SELECT(
  Activity,
  ActivityMethod,
  ActivityMethodAssignment,
  BreakdownElementView,
  BreakdownVersion,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  File,
  IndividualPartView,
  Part,
  PartOccurrence,
  PartOccurrenceRelationship,
  PartShape,
  PartVersion,
  PartView,
  PartViewOccurrenceRelationship,
  PartViewRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  RealizationOrOccurrenceRelationship,
  ShapeElement,
  ShapeElementRelationship,
  Specification
);
END_TYPE;

TYPE PropertyDefinitionSelect = SELECT(
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString
);
END_TYPE;

TYPE PropertyDefinitionString = STRING;
END_TYPE;

TYPE PropertyValueSelect = SELECT(
  CartesianPoint,
  NumericalValue
);
END_TYPE;

TYPE ProxyItemSelect = SELECT(
  ExternalItem,
  ExternalOwlObject,
  ProxyString
);
END_TYPE;

TYPE ProxySelect = SELECT(
  Proxy,
  ProxyItemSelect
);
END_TYPE;

TYPE ProxyString = STRING;
END_TYPE;

TYPE RequirementAssignmentSelect = SELECT(
  AlternatePartRelationship,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Document,
  DocumentDefinition,
  DocumentVersion,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  Part,
  PartVersion,
  PartView,
  Requirement,
  RequirementVersion,
  RequirementView
);
END_TYPE;

TYPE RequirementSourceSelect = SELECT(
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Document,
  DocumentDefinition,
  DocumentVersion,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  Part,
  PartVersion,
  PartView,
  Requirement,
  RequirementVersion,
  RequirementView
);
END_TYPE;

TYPE RequirementVersionOrViewSelect = SELECT(
  RequirementVersion,
  RequirementView
);
END_TYPE;

TYPE SecurityClassificationSelect = SELECT(
  Activity,
  ActivityAssignment,
  AlternativeSolution,
  AssemblyOccurrenceRelationship,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownVersion,
  Configuration,
  Document,
  DocumentDefinition,
  DocumentVersion,
  ExternalClassSystem,
  File,
  GeometricModel,
  IndividualAssemblyRelationship,
  IndividualPartTestResult,
  IndividualPartView,
  ManufacturingConfiguration,
  MaterialIdentification,
  Part,
  PartVersion,
  PartView,
  PartViewRelationship,
  ProcessPlan,
  ProductClass,
  Project,
  PropertyDefinitionAssignment,
  PropertyDefinitionSelect,
  PropertyValueAssignment,
  RealizationOrOccurrenceRelationship,
  RequirementView,
  Specification,
  SpecificationCategory,
  StyledModel,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE ShapedElementSelect = SELECT(
  PartShape,
  ShapeElement
);
END_TYPE;

TYPE ShapeInformationSelect = SELECT(
  ShapeElementRelationship,
  ShapedElementSelect
);
END_TYPE;

TYPE ShapeModelSelect = SELECT(
  ExternalGeometricModel
);
END_TYPE;

TYPE SingleIdentifierSelect = SELECT(
  Identifier,
  IdentifierString
);
END_TYPE;

TYPE SpecificationExpressionOperationEnum = ENUMERATION OF(
  and_operation,
  or_operation,
  oneof_operation,
  not_operation
);
END_TYPE;

TYPE SpecificationOperandSelect = SELECT(
  Specification,
  SpecificationExpression
);
END_TYPE;

TYPE StockCategoryEnum = ENUMERATION OF(
  ANISOTROPIC_MATERIAL,
  BRAIDED_ASSEMBLY,
  DISCONTINUOUS_FIBER_ASSEMBLY,
  FILAMENT_ASSEMBLY,
  ISOTROPIC_MATERIAL,
  STOCK_CORE,
  WOVEN_ASSEMBLY
);
END_TYPE;

TYPE SuppliedObjectSelect = SELECT(
  Activity,
  ActivityMethod,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  ClassAttribute,
  ClassSelect,
  Configuration,
  Contract,
  Document,
  DocumentDefinition,
  DocumentVersion,
  Effectivity,
  Event,
  ExternalClassSystem,
  File,
  FormatProperty,
  GeometricModel,
  IndividualPartTestResult,
  IndividualPartView,
  InformationRight,
  InformationUsageRight,
  ManufacturingConfiguration,
  MaterialIdentification,
  Organization,
  Part,
  PartOccurrence,
  PartVersion,
  PartView,
  PersonInOrganization,
  ProcessOperationDefinition,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  Requirement,
  RequirementSatisfactionAssertion,
  RequirementVersion,
  RequirementView,
  SecurityClassification,
  Specification,
  SpecificationCategory,
  SpecificationExpression,
  SpecificationInclusion,
  TemplateInstance,
  WorkOrder,
  WorkRequest
);
END_TYPE;

TYPE ThicknessLaminateTableComponentSelect = SELECT(
  FilamentLaminate,
  Ply,
  ProcessedCore
);
END_TYPE;

TYPE TransformationSelect = SELECT(
  GeometricModelRelationship,
  TemplateInstance
);
END_TYPE;

TYPE TransitionCodeEnum = ENUMERATION OF(
  cont_same_gradient,
  cont_same_gradient_same_curvature,
  continuous,
  discontinuous
);
END_TYPE;

TYPE TranslatedStringSet = SET[1:?] OF LocalizedString;
END_TYPE;

TYPE TypeQualifierSelect = SELECT(
  ExternalTypeQualifier,
  PreDefinedTypeQualifier
);
END_TYPE;

TYPE UnitSelect = SELECT(
  ExternalUnit,
  Unit
);
END_TYPE;

TYPE Uri = IdentifierString;
END_TYPE;

TYPE ValidityContextSelect = SELECT(
  Organization,
  ProductClass,
  ProductConfiguration
);
END_TYPE;

TYPE ValueQualifierSelect = SELECT(
  PrecisionQualifier,
  TypeQualifierSelect,
  UncertaintyQualifier
);
END_TYPE;

ENTITY Activity;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  activityType : ClassSelect;
  actualEndDate : OPTIONAL DateTimeString;
  actualStartDate : OPTIONAL DateTimeString;
  chosenMethod : OPTIONAL ActivityMethod;
  concernedOrganizations : OPTIONAL SET[1:?] OF Organization;
  plannedEndDate : OPTIONAL PeriodOrDateSelect;
  plannedStartDate : OPTIONAL EventOrDateSelect;
  requestor : OPTIONAL DateAndPersonOrganization;
  resolvedRequests : OPTIONAL SET[1:?] OF WorkRequest;
  status : OPTIONAL ClassSelect;
  supplyingOrganizations : OPTIONAL SET[1:?] OF Organization;
INVERSE
  authorization : SET[0:1] OF WorkOrder FOR isControlling;
END_ENTITY;

ENTITY ActivityAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedActivity : Activity;
  assignedTo : SET[1:?] OF ActivityAssignmentSelect;
END_ENTITY;

ENTITY ActivityMethod;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  consequence : OPTIONAL MultiLingualStringSelect;
  purpose : MultiLingualStringSelect;
END_ENTITY;

ENTITY ActivityMethodAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedActivityMethod : ActivityMethod;
  assignedTo : SET[1:?] OF ActivityMethodAssignmentSelect;
END_ENTITY;

ENTITY ActivityMethodRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ActivityMethod;
  related : ActivityMethod;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ActivityMethodWorkRequestAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associationType : ClassSelect;
  associatedActivityMethod : ActivityMethod;
  associatedWorkRequest : WorkRequest;
END_ENTITY;

ENTITY ActivityRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Activity;
  related : Activity;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AddElement
  SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY Address;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL CharacterString;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  country : OPTIONAL CharacterString;
  electronicMailAddress : OPTIONAL CharacterString;
  facsimileNumber : OPTIONAL CharacterString;
  internalLocation : OPTIONAL CharacterString;
  postalBox : OPTIONAL CharacterString;
  postalCode : OPTIONAL CharacterString;
  region : OPTIONAL CharacterString;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  street : OPTIONAL CharacterString;
  streetNumber : OPTIONAL CharacterString;
  telephoneNumber : OPTIONAL CharacterString;
  telexNumber : OPTIONAL CharacterString;
  town : OPTIONAL CharacterString;
  url : OPTIONAL CharacterString;
END_ENTITY;

ENTITY AlternatePartRelationship
  SUBTYPE OF(PartRelationship);
  criteria : OPTIONAL MultiLingualStringSelect;
DERIVE
  SELF\PartRelationship.relationType : ClassString := 'alternate';
UNIQUE
  UR1: relating, related;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AlternativeSolution
  SUPERTYPE OF(ONEOF(FinalSolution, SupplierSolution, TechnicalSolution));
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  baseElement : BreakdownElementOrAlternativeSolutionSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY AlternativeSolutionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : AlternativeSolution;
  related : AlternativeSolution;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ApplicationDomain;
  sameAs : SET[1:?] OF ProxySelect;
UNIQUE
  UR1: sameAs;
END_ENTITY;

ENTITY Approval;
  id : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  actualDate : OPTIONAL DateTimeString;
  approvedBy : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  plannedDate : OPTIONAL DateTimeString;
  purpose : MultiLingualStringSelect;
  scopes : OPTIONAL SET[1:?] OF Organization;
  status : ClassSelect;
END_ENTITY;

ENTITY ApprovalAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedApproval : Approval;
  assignedTo : SET[1:?] OF ApprovalAssignmentSelect;
END_ENTITY;

ENTITY ApprovalRelationship;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Approval;
  related : Approval;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AssemblyDefinition
  SUPERTYPE OF(ONEOF(MatingDefinition))
  SUBTYPE OF(PartView);
  assemblyType : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY AssemblyJoint;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assemblyShape : PartShape;
  shapeElement1 : ShapeElement;
  shapeElement2 : ShapeElement;
END_ENTITY;

ENTITY AssemblyOccurrenceRelationship
  ABSTRACT
  SUPERTYPE OF(ONEOF(NextAssemblyOccurrenceUsage, PromissoryAssemblyOccurrenceUsage))
  SUBTYPE OF(PartViewOccurrenceRelationship);
  SELF\PartViewOccurrenceRelationship.relating : AssemblyDefinition;
  placement : OPTIONAL TransformationSelect;
END_ENTITY;

ENTITY AssemblyOccurrenceRelationshipSubstitution;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : AssemblyOccurrenceRelationship;
  related : AssemblyOccurrenceRelationship;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AssemblyRealizationContextAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : IndividualAssemblyRelationship;
  related : IndividualAssemblyRelationshipRealizationContextSelect;
END_ENTITY;

ENTITY AssemblyViewRelationship
  ABSTRACT
  SUPERTYPE OF(ONEOF(NextAssemblyViewUsage, PromissoryAssemblyViewUsage))
  SUBTYPE OF(PartViewRelationship);
  SELF\PartViewRelationship.relating : AssemblyDefinition;
  locationIndicator : OPTIONAL IdentifierSelect;
  quantity : OPTIONAL ValueWithUnit;
END_ENTITY;

ENTITY AssemblyViewRelationshipSubstitution;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : AssemblyViewRelationship;
  related : AssemblyViewRelationship;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BeveledSheetRepresentation
  SUBTYPE OF(ConstituentShapeRepresentation);
  bevelAngle : NumericalValue;
  boundarySurface : CompositeSheetRepresentation;
  verticalProfileHeight : NumericalValue;
WHERE
  WR1 : TRUE;
END_ENTITY;

ENTITY BoundaryCurveRepresentation;
  name : OPTIONAL DescriptorSelect;
  bounds : SET[1:?] OF GeometricBoundingCurveSelect;
END_ENTITY;

ENTITY Breakdown
  SUPERTYPE OF(ONEOF(FunctionalBreakdown, PhysicalBreakdown, SystemBreakdown, ZonalBreakdown));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  breakdownType : ClassSelect;
  versions : SET[1:?] OF BreakdownVersion;
WHERE
  wr1: NOT(TYPEOF(SELF) = [SCHEMA_NAME + 'BREAKDOWN']) OR ((SELF.breakdownType <> 'physical') AND (SELF.breakdownType <> 'functional') AND (SELF.breakdownType <> 'zonal') AND (SELF.breakdownType <> 'system'));
END_ENTITY;

ENTITY BreakdownAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedBreakdownVersion : BreakdownVersion;
  assignedTo : SET[1:?] OF BreakdownAssignmentSelect;
END_ENTITY;

ENTITY BreakdownElement;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : OPTIONAL SET[1:?] OF BreakdownElementVersion;
END_ENTITY;

ENTITY BreakdownElementAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  associatedBreakdown : BreakdownVersion;
  associatedElemenent : BreakdownElement;
END_ENTITY;

ENTITY BreakdownElementVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF BreakdownElementView;
INVERSE
  versionOf : BreakdownElement FOR versions;
END_ENTITY;

ENTITY BreakdownElementVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementVersion;
  related : BreakdownElementVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownElementView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
INVERSE
  viewOf : BreakdownElementVersion FOR views;
END_ENTITY;

ENTITY BreakdownElementViewRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementView;
  related : BreakdownElementView;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Breakdown;
  related : Breakdown;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
INVERSE
  versionOf : Breakdown FOR versions;
END_ENTITY;

ENTITY BreakdownVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownVersion;
  related : BreakdownVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY CartesianPoint
  SUBTYPE OF(Point);
  coordinates : LIST[1:3] OF LengthMeasure;
END_ENTITY;

ENTITY CentreOfMass
  SUBTYPE OF(ShapeDependentProperty);
  centrePoint : CartesianPoint;
  SELF\ShapeDependentProperty.definedIn : GeometricCoordinateSpace;
END_ENTITY;

ENTITY Certification;
  id : OPTIONAL IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  certificationType : ClassSelect;
END_ENTITY;

ENTITY CertificationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedCertification : Certification;
  assignedTo : SET[1:?] OF CertificationAssignmentSelect;
END_ENTITY;

ENTITY ChangeElementSequence;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : DeltaChangeActivity;
  related : DeltaChangeActivity;
END_ENTITY;

ENTITY CircularPath
  SUBTYPE OF(PathSegment);
  viaPoint : CartesianPoint;
END_ENTITY;

ENTITY Class;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  definedIn : OPTIONAL ExternalClassSystem;
UNIQUE
  ur1: id;
END_ENTITY;

ENTITY ClassAttribute;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  AttributeDefinition : PropertyDefinition;
  allowedValues : OPTIONAL SET[1:?] OF PropertyValue;
  definedFor : Class;
END_ENTITY;

ENTITY ClassCategoryAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedCategory : SpecificationCategory;
  associatedProductClass : ProductClass;
  mandatory : BOOLEAN;
END_ENTITY;

ENTITY ClassConditionAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  conditionType : ClassSelect;
  associatedCondition : SpecificationExpression;
  associatedProductClass : ProductClass;
END_ENTITY;

ENTITY Classification;
  role : OPTIONAL ClassString;
  class : ClassSelect;
END_ENTITY;

ENTITY ClassificationRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Classification;
  related : Classification;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ClassInclusionAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedInclusion : SpecificationInclusion;
  associatedProductClass : ProductClass;
END_ENTITY;

ENTITY ClassSpecificationAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associationType : ClassSelect;
  associatedProductClass : ProductClass;
  associatedSpecification : Specification;
END_ENTITY;

ENTITY CoatingLayer
  SUBTYPE OF(ShapeElement);
INVERSE
  thickness : SET[0:1] OF ThicknessSizeDimension FOR appliedTo;
END_ENTITY;

ENTITY CollectedPartRelationship
  SUBTYPE OF(PartViewOccurrenceRelationship);
  SELF\PartViewOccurrenceRelationship.relating : CollectionDefinition;
DERIVE
  SELF\PartViewOccurrenceRelationship.relationType : ClassString := 'collected part view';
END_ENTITY;

ENTITY CollectionDefinition
  SUBTYPE OF(PartView);
  purpose : OPTIONAL MultiLingualStringSelect;
INVERSE
  collectedParts : SET[2:?] OF CollectedPartRelationship FOR relating;
END_ENTITY;

ENTITY ComponentPlacement;
  placedComponent : BreakdownElementView;
  placement : TransformationSelect;
  referenceComponent : BreakdownElementView;
END_ENTITY;

ENTITY CompositeAssembly
  SUBTYPE OF(ConstituentPart);
  layupPart : CompositeAssemblyTable;
  shape : OPTIONAL CompositeAssemblyShapeSelect;
END_ENTITY;

ENTITY CompositeAssemblySequenceDefinition;
  componentsInSequence : OPTIONAL BAG[1:?] OF ComponentClassForAssemblySelect;
END_ENTITY;

ENTITY CompositeAssemblyTable
  SUBTYPE OF(LaminateTable);
  sequenceGroups : LIST[2:?] OF CompositeAssemblySequenceDefinition;
END_ENTITY;

ENTITY CompositeSheetRepresentation
  SUPERTYPE OF(ONEOF(FaceBasedSheetRepresentation, GeometricSheetRepresentation))
  SUBTYPE OF(ConstituentShapeRepresentation);
  threeDGeometry : ExternalGeometricModel;
END_ENTITY;

ENTITY Configuration;
  id : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  configurationType : ClassSelect;
  inheritanceType : ClassSelect;
  configuredElement : ConfiguredItemSelect;
  isSolutionFor : ConfiguredSpecificationSelect;
END_ENTITY;

ENTITY ConstituentPart
  SUBTYPE OF(PartView);
  weight : OPTIONAL NumericalValue;
WHERE
  WR1 : TRUE;
END_ENTITY;

ENTITY ConstituentShapeRepresentation
  ABSTRACT
  SUPERTYPE OF(ONEOF(BeveledSheetRepresentation, CompositeSheetRepresentation, ThreeDGeometrySet));
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  coordinateSpace : GeometricCoordinateSpace;
  isAppliedTo : SET[1:?] OF DetailedGeometricModelElement;
END_ENTITY;

ENTITY ContentProperty;
  description : OPTIONAL DescriptorSelect;
  detailLevel : OPTIONAL DescriptorSelect;
  geometryTypes : OPTIONAL SET[1:?] OF Classification;
  languages : OPTIONAL SET[1:?] OF Language;
  realWorldScale : OPTIONAL NumericalValue;
END_ENTITY;

ENTITY Contract;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  contractType : ClassSelect;
INVERSE
  releases : SET[0:?] OF OrganizationInContract FOR signedContracts;
END_ENTITY;

ENTITY ContractAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedContract : Contract;
  assignedTo : SET[1:?] OF ContractAssignmentSelect;
END_ENTITY;

ENTITY CoordinateSystem
  SUBTYPE OF(DetailedGeometricModelElement);
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  coordinateType : coordinateTypeEnum;
  axis : OPTIONAL Direction;
  dimensionality : INTEGER;
  origin : Point;
  refDirection : OPTIONAL Direction;
WHERE
  wr1: dimensionality > 0;
END_ENTITY;

ENTITY Copyright
  SUBTYPE OF(InformationRight);
END_ENTITY;

ENTITY CreationProperty;
  description : OPTIONAL DescriptorSelect;
  creatingInterface : OPTIONAL CharacterString;
  creatingSystem : CharacterString;
  operatingSystem : OPTIONAL CharacterString;
END_ENTITY;

ENTITY DataEnvironment;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  characterization : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY DataValidityPeriod
  SUBTYPE OF(DatedEffectivity);
END_ENTITY;

ENTITY DateAndPersonAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDateAndPerson : DateAndPersonOrganization;
  assignedTo : SET[1:?] OF DateTimePersonOrganizationElementSelect;
END_ENTITY;

ENTITY DateAndPersonOrganization;
  date : DateTimeString;
  personOrOrganization : PersonOrOrganizationSelect;
END_ENTITY;

ENTITY DatedConfiguration
  SUBTYPE OF(ManufacturingConfiguration);
  endDefinition : OPTIONAL EventOrDateSelect;
  startDefinition : EventOrDateSelect;
END_ENTITY;

ENTITY DatedEffectivity
  SUPERTYPE OF(ONEOF(DataValidityPeriod))
  SUBTYPE OF(Effectivity);
  endDefinition : OPTIONAL EventOrDateSelect;
  startDefinition : OPTIONAL EventOrDateSelect;
END_ENTITY;

ENTITY DateTimeAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDate : DateTimeString;
  assignedTo : SET[1:?] OF DateTimeAssignmentSelect;
END_ENTITY;

ENTITY DeleteElement
  SUBTYPE OF(DeltaChangeActivity);
  previousDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY DeltaChange;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  changeAcitvities : OPTIONAL SET[1:?] OF DeltaChangeActivity;
  describedChange : OPTIONAL DeltaChangeRelationshipSelect;
END_ENTITY;

ENTITY DeltaChangeActivity
  ABSTRACT
  SUPERTYPE OF(ONEOF(AddElement, DeleteElement, ModifyElement, ModifySingleElement));
  attributeName : OPTIONAL CharacterString;
  changeLocationInAggregateAttribute : OPTIONAL LIST[1:?] OF INTEGER;
INVERSE
  changeSet : DeltaChange FOR changeAcitvities;
END_ENTITY;

ENTITY Descriptor;
  id : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  descriptionContext : OPTIONAL SET[1:?] OF IdentificationContextSelect;
  text : MultiLingualStringSelect;
WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

ENTITY DescriptorRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Descriptor;
  related : Descriptor;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DetailedGeometricModelElement
  ABSTRACT
  SUPERTYPE OF(ONEOF(CoordinateSystem, Direction, ExternalPointOnCurve, ExternalPointOnsurface, Point, TemplateInstance, Transformation));
END_ENTITY;

ENTITY DigitalDocumentDefinition
  SUBTYPE OF(DocumentDefinition);
  files : OPTIONAL SET[1:?] OF DigitalFile;
END_ENTITY;

ENTITY DigitalFile
  SUBTYPE OF(File);
INVERSE
  associatedModelSpace : ExternalGeometricModel FOR DefinedAs;
END_ENTITY;

ENTITY Direction
  SUBTYPE OF(DetailedGeometricModelElement);
  name : OPTIONAL DescriptorSelect;
  directionRatios : LIST[2:3] OF LengthMeasure;
END_ENTITY;

ENTITY DirectionOfFiberOrientationWithinAPly;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  angleReferences : SET[1:?] OF AngleSelect;
  basis : ReinforcementOrientationBasis;
INVERSE
  orientations : PlyOrientationAngle FOR fiberDirection;
END_ENTITY;

ENTITY Document;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  documentTypes : SET[1:?] OF ClassSelect;
  versions : SET[1:?] OF DocumentVersion;
END_ENTITY;

ENTITY DocumentAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDocument : AssignedDocumentSelect;
  assignedTo : SET[1:?] OF DocumentAssignmentSelect;
  documentPortion : OPTIONAL MultiLingualStringSelect;
END_ENTITY;

ENTITY DocumentDefinition
  ABSTRACT
  SUPERTYPE OF(ONEOF(DigitalDocumentDefinition, PhysicalDocumentDefinition));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  documentContent : OPTIONAL ContentProperty;
  documentCreation : OPTIONAL CreationProperty;
  documentFormat : OPTIONAL SET[1:?] OF FormatProperty;
  documentSize : OPTIONAL SizeProperty;
INVERSE
  viewOf : DocumentVersion FOR views;
END_ENTITY;

ENTITY DocumentDefinitionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : DocumentDefinition;
  related : DocumentDefinition;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DocumentRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Document;
  related : Document;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DocumentVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  views : OPTIONAL SET[1:?] OF DocumentDefinition;
INVERSE
  versionOf : Document FOR versions;
END_ENTITY;

ENTITY DocumentVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : DocumentVersion;
  related : DocumentVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DrapedOrientationAngle
  SUBTYPE OF(PlyOrientationAngle);
END_ENTITY;

ENTITY Duration;
  time : STRING;
  unit : STRING;
END_ENTITY;

ENTITY EdgeZoneShape
  SUBTYPE OF(ZoneStructuralMakeupShapeRepresentation);
  boundary : BoundaryClassZoneSelect;
END_ENTITY;

ENTITY Effectivity
  SUPERTYPE OF(ONEOF(DatedEffectivity, LotEffectivity, SerialEffectivity, TimeIntervalEffectivity));
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  concernedOrganizations : OPTIONAL SET[1:?] OF Organization;
  effectivityContext : OPTIONAL LifeCycleStageSelect;
END_ENTITY;

ENTITY EffectivityAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedEffectivity : Effectivity;
  assignedTo : SET[1:?] OF EffectivityAssignmentSelect;
  effectivityIndication : BOOLEAN;
END_ENTITY;

ENTITY EffectivityRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Effectivity;
  related : Effectivity;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ElementDelivery;
  role : ClassSelect;
  associatedActivity : Activity;
  deliverableElements : SET[1:?] OF ActivityAssignmentSelect;
  destination : Organization;
  quantity : ValueWithUnit;
END_ENTITY;

ENTITY EvaluatedCharacteristic;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  actualCharacteristics : SET[1:?] OF PropertyValue;
  evaluationResult : EvaluationResultEnum;
  evaluationStatus : EvaluationStatusEnum;
  plannedCharacteristics : SET[1:?] OF PlannedCharacteristic;
END_ENTITY;

ENTITY Event;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  eventType : ClassSelect;
  actualStartDate : OPTIONAL DateTimeString;
  offset : OPTIONAL Duration;
  plannedStartDate : OPTIONAL DateTimeString;
END_ENTITY;

ENTITY EventAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedEvent : Event;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
END_ENTITY;

ENTITY EventRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Event;
  related : Event;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ExchangeContext;
  description : OPTIONAL DescriptorSelect;
  identificationContext : OPTIONAL IdentificationContextSelect;
  language : OPTIONAL Language;
WHERE
  wr1: EXISTS(language) OR EXISTS (identificationContext);
END_ENTITY;

ENTITY ExchangeContextClassLibrary;
  id : Uri;
UNIQUE
  UR1: id;
END_ENTITY;

ENTITY ExpandedUncertainty
  SUBTYPE OF(StandardUncertainty);
  coverageFactor : REAL;
END_ENTITY;

ENTITY ExplicitTransformation2d
  SUBTYPE OF(Transformation2d);
  axis1 : OPTIONAL Direction;
  axis2 : OPTIONAL Direction;
  localOrigin : CartesianPoint;
END_ENTITY;

ENTITY ExplicitTransformation3d
  SUBTYPE OF(Transformation3d);
  axis1 : OPTIONAL Direction;
  axis2 : OPTIONAL Direction;
  axis3 : OPTIONAL Direction;
  localOrigin : CartesianPoint;
END_ENTITY;

ENTITY ExternalAdvancedBrepShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
WHERE
  WR1 : TRUE;
END_ENTITY;

ENTITY ExternalClass;
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
UNIQUE
  ur1: id, source;
END_ENTITY;

ENTITY ExternalClassSystem;
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
INVERSE
  allowedClasses : SET[1:?] OF Class FOR definedIn;
UNIQUE
  ur1: id, source;
END_ENTITY;

ENTITY ExternalCompositeCurveOnSurface
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalCsgShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalCurve
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalCurveSweptSolidShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalDegeneratePcurve
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalEdgeBasedWireframeShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalElementaryBrepShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalFacetedBrepShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalGeometricallyBoundedSurfaceShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalGeometricallyBoundedWireframeShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalGeometricModel
  SUBTYPE OF(GeometricModel);
  accuracyType : OPTIONAL ClassSelect;
  accuracyValue : OPTIONAL REAL;
  definedAs : DigitalFile;
  SELF\GeometricModel.modelElements : SET[1:1] OF CoordinateSystem;
  parameterValues : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY ExternalItem
  SUPERTYPE OF(ONEOF(ExternalRepresentationItem));
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
UNIQUE
  ur1: id, source;
END_ENTITY;

ENTITY ExternalLoop
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalManifoldSurfaceShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalOrientedSurface
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalOwlClass;
  class : Uri;
UNIQUE
  ur1: class;
END_ENTITY;

ENTITY ExternalOwlObject;
  individual : Uri;
UNIQUE
  ur1: individual;
END_ENTITY;

ENTITY ExternalPcurve
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalPointOnCurve
  SUBTYPE OF(DetailedGeometricModelElement);
  supportingCurve : ExternalCurve;
  threeDGeometry : ExternalRepresentationItem;
END_ENTITY;

ENTITY ExternalPointOnSurface
  SUBTYPE OF(DetailedGeometricModelElement);
  threeDGeometry : ExternalRepresentationItem;
END_ENTITY;

ENTITY ExternalPointPath
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalPropertyDefinition;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
  sameAs : SET[1:?] OF ProxySelect;
UNIQUE
  UR1: sameAs;
END_ENTITY;

ENTITY ExternalRepresentation
  SUPERTYPE OF(ONEOF(ExternalAdvancedBrepShapeRepresentation, ExternalCsgShapeRepresentation, ExternalCurveSweptSolidShapeRepresentation, ExternalEdgeBasedWireframeShapeRepresentation, ExternalElementaryBrepShapeRepresentation, ExternalFacetedBrepShapeRepresentation, ExternalGeometricallyBoundedSurfaceShapeRepresentation, ExternalGeometricallyBoundedWireframeShapeRepresentation, ExternalManifoldSurfaceShapeRepresentation, ExternalShellBasedWireframeShapeRepresentation, ExternalTessellatedShapeRepresentation));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  definedAs : DigitalFile;
  modelElement : ExternalRepresentationItem;
END_ENTITY;

ENTITY ExternalRepresentationItem
  SUPERTYPE OF(ONEOF(ExternalCompositeCurveOnSurface, ExternalCurve, ExternalDegeneratePcurve, ExternalLoop, ExternalOrientedSurface, ExternalPcurve, ExternalPointPath, ExternalSurface, ExternalSurfaceCurve))
  SUBTYPE OF(ExternalItem);
  name : DescriptorSelect;
DERIVE
  SELF\ExternalItem.source : DigitalFile := definedIn.definedAs;
INVERSE
  definedIn : ExternalRepresentation FOR modelElement;
END_ENTITY;

ENTITY ExternalShellBasedWireframeShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalSurface
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalSurfaceCurve
  SUBTYPE OF(ExternalRepresentationItem);
END_ENTITY;

ENTITY ExternalTessellatedShapeRepresentation
  SUBTYPE OF(ExternalRepresentation);
END_ENTITY;

ENTITY ExternalTypeQualifier;
  sameAs : OPTIONAL ProxySelect;
END_ENTITY;

ENTITY ExternalUnit;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : SET[1:?] OF ProxySelect;
UNIQUE
  UR1: sameAs;
END_ENTITY;

ENTITY FaceBasedSheetRepresentation
  SUBTYPE OF(CompositeSheetRepresentation);
  faceSurface : ExternalSurface;
  innerBounds : OPTIONAL SET[1:?] OF ExternalLoop;
  outerBound : ExternalLoop;
END_ENTITY;

ENTITY FilamentLaminate
  SUBTYPE OF(ConstituentPart);
  madeFrom : StockMaterial;
  shapeCrossSection : OPTIONAL ShapeDescriptionAssociation;
WHERE
  WR1 : SELF.madeFrom.stockMaterialType = FILAMENT_ASSEMBLY;
END_ENTITY;

ENTITY File
  ABSTRACT
  SUPERTYPE OF(ONEOF(DigitalFile, Hardcopy));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  fileType : OPTIONAL ClassSelect;
  fileContent : OPTIONAL ContentProperty;
  fileCreation : OPTIONAL CreationProperty;
  fileFormat : OPTIONAL FormatProperty;
  fileSize : OPTIONAL SizeProperty;
  locations : OPTIONAL SET[1:?] OF ExternalItem;
END_ENTITY;

ENTITY FinalSolution
  SUBTYPE OF(AlternativeSolution);
  specifications : SET[1:?] OF FinalDefinitionSelect;
  status : ClassSelect;
END_ENTITY;

ENTITY FormatProperty;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  characterCode : OPTIONAL ClassSelect;
  dataFormat : OPTIONAL ClassSelect;
  sizeFormat : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY FrozenAssignment;
  frozenObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY FunctionalBreakdown
  SUBTYPE OF(Breakdown);
DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'functional';
END_ENTITY;

ENTITY FunctionalBreakdownElementViewAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  associatedFunctionalElement : BreakdownElementView;
  associatedPhysicalElement : PhysicalElementSelect;
END_ENTITY;

ENTITY GeneralShapeDependentProperty
  SUBTYPE OF(ShapeDependentProperty);
  propertyType : PropertyDefinitionSelect;
  propertyValue : PropertyValueSelect;
  unit : OPTIONAL Unit;
END_ENTITY;

ENTITY GeometricalRelationship
  SUBTYPE OF(PartViewRelationship);
  placement : TransformationSelect;
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'geometrically related part view';
END_ENTITY;

ENTITY GeometricCoordinateSpace;
  id : IdentifierSelect;
  coordinateType : ClassSelect;
  accuracies : OPTIONAL SET[1:?] OF MeasureQualification;
  dimensionality : INTEGER;
  units : OPTIONAL SET[1:?] OF Unit;
WHERE
  wr1: dimensionality > 0;
END_ENTITY;

ENTITY GeometricModel
  SUPERTYPE OF(ONEOF(ExternalGeometricModel))
  SUBTYPE OF(TemplateDefinition);
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  geometryType : OPTIONAL SET[1:?] OF ClassSelect;
  definedIn : GeometricCoordinateSpace;
  modelElements : SET[1:?] OF DetailedGeometricModelElement;
  modelExtent : OPTIONAL LengthMeasure;
END_ENTITY;

ENTITY GeometricModelRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : GeometricModel;
  related : GeometricModel;
  placement : OPTIONAL Transformation;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY GeometricSheetRepresentation
  SUBTYPE OF(CompositeSheetRepresentation);
  basisSurface : ExternalSurface;
  cutouts : OPTIONAL SET[1:?] OF BoundaryCurveRepresentation;
  outerEdge : BoundaryCurveRepresentation;
END_ENTITY;

ENTITY Hardcopy
  SUBTYPE OF(File);
END_ENTITY;

ENTITY Identifier;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  idString : IdentifierString;
  identificationContext : OPTIONAL IdentificationContextSelect;
UNIQUE
  UR1: idString, role, identificationContext;
WHERE
  ContextlessForOrganizationOnly: NOT (NOT EXISTS(identificationContext) AND (SIZEOF(USEDIN(SELF, SCHEMA_NAME + 'ORGANIZATION.ID'))=0));
END_ENTITY;

ENTITY IdentifierRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Identifier;
  related : Identifier;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ImplicitTransformation2d
  SUBTYPE OF(Transformation2d);
  origin : CoordinateSystem;
  target : CoordinateSystem;
END_ENTITY;

ENTITY ImplicitTransformation3d
  SUBTYPE OF(Transformation3d);
  origin : CoordinateSystem;
  target : CoordinateSystem;
END_ENTITY;

ENTITY IndividualAssemblyRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : IndividualPartView;
  related : IndividualPartView;
DERIVE
  relationType : ClassString := 'next assembly view';
INVERSE
  isRealizationOf : AssemblyRealizationContextAssociation FOR relating;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY IndividualPart;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : SET[1:?] OF IndividualPartVersion;
END_ENTITY;

ENTITY IndividualPartTestResult
  SUBTYPE OF(MeasuredCharacteristic);
  testedPart : IndividualPartView;
END_ENTITY;

ENTITY IndividualPartVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF IndividualPartView;
INVERSE
  versionOf : IndividualPart FOR versions;
END_ENTITY;

ENTITY IndividualPartVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : IndividualPartVersion;
  related : IndividualPartVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY IndividualPartView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
INVERSE
  viewOf : IndividualPartVersion FOR views;
END_ENTITY;

ENTITY IndividualPartViewRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : IndividualPartView;
  related : IndividualPartView;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY InformationRight
  SUPERTYPE OF(ONEOF(Copyright));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  owners : SET[1:?] OF PersonOrganizationSelect;
  restriction : OPTIONAL MultiLingualStringSelect;
END_ENTITY;

ENTITY InformationUsageRight;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  grantsRight : SET[1:?] OF InformationRight;
  owners : SET[1:?] OF PersonOrganizationSelect;
END_ENTITY;

ENTITY InformationUsageRightAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedRight : InformationUsageRight;
  isAssignedTo : SET[1:?] OF InformationUsageRightAssignmentSelect;
END_ENTITY;

ENTITY InformationUsageRightRelationship;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : InformationUsageRight;
  related : InformationUsageRight;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY InstancePlacement;
  placedInstance : SinglePartOccurrence;
  placement : TransformationSelect;
  referenceComponent : BreakdownElementView;
END_ENTITY;

ENTITY InZoneAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  locatedItem : InZoneSelect;
  zone : BreakdownElementView;
END_ENTITY;

ENTITY KinematicPathDefinedByNodes;
  name : OPTIONAL DescriptorSelect;
  placementStart : CoordinateSystem;
  representationContext : GeometricCoordinateSpace;
  segments : LIST[1:?] OF PathSegment;
  tStart : REAL;
END_ENTITY;

ENTITY LaidOrientationAngle
  SUBTYPE OF(PlyOrientationAngle);
END_ENTITY;

ENTITY LaminateTable
  SUPERTYPE OF(ONEOF(CompositeAssemblyTable, PlyLaminateTable, ZoneStructuralMakeup))
  SUBTYPE OF(PartView);
  baseSurface : SurfaceWithDirection;
  basis : ReinforcementOrientationBasis;
  resultingSurface : OrientedSurfaceSelect;
WHERE
  WR1 : TRUE;
END_ENTITY;

ENTITY LifeCycleStage;
  sameAs : SET[1:?] OF ProxySelect;
UNIQUE
  UR1: sameAs;
END_ENTITY;

ENTITY LinearPath
  SUBTYPE OF(PathSegment);
END_ENTITY;

ENTITY LinkMotionAlongPath;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  items : SET[1:?] OF KinematicPathDefinedByNodes;
  representationContext : GeometricCoordinateSpace;
  timeUnit : OPTIONAL Unit;
END_ENTITY;

ENTITY LinkMotionDecompositionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : LinkMotionAlongPath;
  related : LinkMotionAlongPath;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY LinkMotionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : LinkMotionAlongPath;
  related : GeometricModelOrExternalRepresentationSelect;
  tranformationOperator : LinkMotionTransformation;
END_ENTITY;

ENTITY LinkMotionTransformation;
  transformItem1 : CoordinateSystem;
  transformItem2 : KinematicPathDefinedByNodes;
END_ENTITY;

ENTITY LocalizedString;
  language : OPTIONAL Language;
  text : CharacterString;
WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

ENTITY LotConfiguration
  SUBTYPE OF(ManufacturingConfiguration);
  SELF\ManufacturingConfiguration.id : IdentifierSelect;
  lotSize : ValueWithUnit;
END_ENTITY;

ENTITY LotEffectivity
  SUBTYPE OF(Effectivity);
  lotSize : ValueWithUnit;
END_ENTITY;

ENTITY MakeFromRelationship
  SUBTYPE OF(PartViewRelationship);
  priority : OPTIONAL INTEGER;
  quantity : OPTIONAL ValueWithUnit;
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'make from';
END_ENTITY;

ENTITY ManufacturingConfiguration
  ABSTRACT
  SUPERTYPE OF(ONEOF(DatedConfiguration, LotConfiguration, SerialConfiguration, TimeIntervalConfiguration));
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  concernedOrganizations : OPTIONAL SET[1:?] OF Organization;
  configuredElement : PartOccurrence;
  isSolutionFor : ProductPartEquivalence;
END_ENTITY;

ENTITY MatedPartAssociation
  SUBTYPE OF(NextAssemblyOccurrenceUsage);
  SELF\AssemblyOccurrenceRelationship.relating : MatingDefinition;
END_ENTITY;

ENTITY MatedPartRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  matingType : MatingTypeEnum;
  relating : MatedPartAssociation;
  related : MatedPartAssociation;
  matedShapes : OPTIONAL SET[1:?] OF AssemblyJoint;
  matingMaterials : OPTIONAL SET[1:?] OF QuantifiedPartOccurrence;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY MaterialIdentification;
  id : IdentifierSelect;
  assignedTo : SET[1:?] OF PropertyAssignmentSelect;
END_ENTITY;

ENTITY MaterialPropertyAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedProperty : MaterialPropertyValue;
  assignedTo : MaterialIdentification;
  definitional : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY MaterialPropertyDefinition
  SUBTYPE OF(PropertyDefinition);
  name : DescriptorSelect;
END_ENTITY;

ENTITY MaterialPropertyValue
  SUBTYPE OF(PropertyValue);
  SELF\PropertyValue.definition : MaterialPropertyDefinition;
  environmentCondition : DataEnvironment;
END_ENTITY;

ENTITY MatingDefinition
  SUBTYPE OF(AssemblyDefinition);
  matingType : OPTIONAL ClassSelect;
INVERSE
  matedParts : SET[2:?] OF MatedPartAssociation FOR relating;
END_ENTITY;

ENTITY MeasuredCharacteristic
  ABSTRACT
  SUPERTYPE OF(ONEOF(IndividualPartTestResult));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  measureActivity : OPTIONAL MeasureActivitySelect;
  measuredCharacteristics : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY MeasureQualification;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  qualifiers : SET[1:?] OF ValueQualifierSelect;
WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

ENTITY ModelProperty;
  definition : PropertyDefinitionSelect;
  specifiedValue : ModelPropertyValueSelect;
END_ENTITY;

ENTITY ModelPropertyAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedProperty : ModelProperty;
  assignedTo : SET[1:?] OF PropertyAssignmentSelect;
  validityContext : OPTIONAL ValidityContextSelect;
END_ENTITY;

ENTITY ModifyElement
  SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY ModifySingleElement
  SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : DeltaChangeManagementObjectSelect;
  previousDesignObject : DeltaChangeManagementObjectSelect;
WHERE
  WR1: currentDesignObject :<>: previousDesignObject;
END_ENTITY;

ENTITY MomentsOfInertia
  SUBTYPE OF(ShapeDependentProperty);
  SELF\ShapeDependentProperty.definedIn : GeometricCoordinateSpace;
  inertiaValue : ARRAY[1:3] OF ARRAY[1:3] OF NumericalValue;
  referenceAxisPlacement : CoordinateSystem;
END_ENTITY;

ENTITY NamedSize
  SUBTYPE OF(RectangularSize);
  size : ClassSelect;
END_ENTITY;

ENTITY NextAssemblyOccurrenceUsage
  SUPERTYPE OF(ONEOF(MatedPartAssociation))
  SUBTYPE OF(AssemblyOccurrenceRelationship);
DERIVE
  SELF\PartViewOccurrenceRelationship.relationType : ClassString := 'next assembly occurrence';
END_ENTITY;

ENTITY NextAssemblyViewUsage
  SUBTYPE OF(AssemblyViewRelationship);
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'next assembly view';
END_ENTITY;

ENTITY NumericalContext;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  accuracy : REAL;
  significantDigits : OPTIONAL INTEGER;
END_ENTITY;

ENTITY NumericalValue
  SUPERTYPE OF(ONEOF(ValueLimit))
  SUBTYPE OF(ValueWithUnit);
  valueComponent : REAL;
  valueContext : OPTIONAL NumericalContext;
END_ENTITY;

ENTITY Organization;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  deliveryAdddress : OPTIONAL Address;
  organizationTypes : OPTIONAL ClassSelect;
  postalAddress : OPTIONAL Address;
  visitorAddress : OPTIONAL Address;
END_ENTITY;

ENTITY OrganizationInContract;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  contractedOrganization : Organization;
  organizationRole : ClassSelect;
  signedBy : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  signedContracts : SET[1:?] OF Contract;
END_ENTITY;

ENTITY OrganizationOrPersonInOrganizationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedPersonOrOrganization : PersonOrOrganizationSelect;
  assignedTo : SET[1:?] OF DateTimePersonOrganizationElementSelect;
END_ENTITY;

ENTITY OrganizationRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Organization;
  related : Organization;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY Part;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  partTypes : SET[1:?] OF ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : SET[1:?] OF PartVersion;
END_ENTITY;

ENTITY PartOccurrence
  ABSTRACT
  SUPERTYPE OF(ONEOF(QuantifiedPartOccurrence, SelectedPartOccurrence, SinglePartOccurrence, SpecifiedPartOccurrence));
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definition : PartOccurrenceDefinitionSelect;
END_ENTITY;

ENTITY PartOccurrenceRelationship
  SUPERTYPE OF(ONEOF(ReplacedUsageRelationship, SameTimeMachiningRelationship));
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartOccurrence;
  related : PartOccurrence;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PartRelationship
  SUPERTYPE OF(ONEOF(AlternatePartRelationship));
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Part;
  related : Part;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PartShape;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  describedObject : PartInformationSelect;
  elements : OPTIONAL SET[1:?] OF ShapeElement;
END_ENTITY;

ENTITY PartToIndividualPartAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPart;
  associatedPart : Part;
END_ENTITY;

ENTITY PartVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF PartView;
INVERSE
  correspondingProductConfiguration : SET[0:1] OF ProductPartEquivalence FOR associatedPartVersion;
  versionOf : Part FOR versions;
END_ENTITY;

ENTITY PartVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartVersion;
  related : PartVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PartVersionToIndividualPartVersionAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPartVersion;
  associatedPart : PartVersionOrProductConfgurationSelect;
END_ENTITY;

ENTITY PartView
  SUPERTYPE OF(ONEOF(AssemblyDefinition, CollectionDefinition, ConstituentPart, LaminateTable));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
INVERSE
  viewOf : PartVersion FOR views;
END_ENTITY;

ENTITY PartViewOccurrenceRelationship
  SUPERTYPE OF(ONEOF(AssemblyOccurrenceRelationship, AssemblyOccurrenceRelationship, CollectedPartRelationship));
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartView;
  related : PartOccurrence;
END_ENTITY;

ENTITY PartViewRelationship
  SUPERTYPE OF(ONEOF(AssemblyViewRelationship, GeometricalRelationship, MakeFromRelationship, ProcessStateRelationship, ReplacedPartViewRelationship, ToolPartRelationship));
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartView;
  related : PartView;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PartViewToIndividualPartViewAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPartView;
  associatedPart : PartViewOrProductConfgurationSelect;
END_ENTITY;

ENTITY PathSegment
  ABSTRACT
  SUPERTYPE OF(ONEOF(CircularPath, LinearPath, PointToPointPath));
  placementEnd : CoordinateSystem;
  tEnd : REAL;
  transition : TransitionCodeEnum;
END_ENTITY;

ENTITY PercentageLaminateTable
  SUBTYPE OF(ZoneStructuralMakeup);
  tableComponents : SET[1:?] OF PercentagePly;
  totalThickness : NumericalValue;
END_ENTITY;

ENTITY PercentagePly;
  makeupAndProperties : OPTIONAL ZoneStructuralMakeup;
  material : StockMaterial;
  strengthOrientation : OPTIONAL PlyOrientationAngle;
  volumePercent : NumericalValue;
END_ENTITY;

ENTITY Person;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  businessAddress : OPTIONAL Address;
  firstName : OPTIONAL STRING;
  lastName : STRING;
  middleNames : OPTIONAL LIST[1:?] OF STRING;
  prefixTitles : OPTIONAL LIST[1:?] OF STRING;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  suffixTitles : OPTIONAL LIST[1:?] OF STRING;
INVERSE
  associatedOrganizations : SET[1:?] OF PersonInOrganization FOR associatedPerson;
END_ENTITY;

ENTITY PersonInOrganization;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedOrganization : Organization;
  associatedPerson : Person;
  location : OPTIONAL Address;
  personRole : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY PersonInOrganizationRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PersonInOrganization;
  related : PersonInOrganization;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PhysicalBreakdown
  SUBTYPE OF(Breakdown);
DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'physical';
END_ENTITY;

ENTITY PhysicalDocumentDefinition
  SUBTYPE OF(DocumentDefinition);
  components : OPTIONAL SET[1:?] OF Hardcopy;
END_ENTITY;

ENTITY PlannedCharacteristic;
  name : OPTIONAL DescriptorSelect;
  definedFor : RequirementAssignment;
  plannedCharacteristics : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY Ply
  SUBTYPE OF(ConstituentPart);
  materialType : StockMaterial;
  constituents : OPTIONAL LIST[1:?] OF PlyPiece;
  materialOrientation : DirectionOfFiberOrientationWithinAPly;
  plyThickness : NumericalValue;
  shape : OPTIONAL PlyShape;
WHERE
  WR1 : SELF.plyThickness.valueComponent >= 0.0;
  WR2 : TRUE;
END_ENTITY;

ENTITY PlyLaminate
  SUBTYPE OF(ConstituentPart);
  plyTable : PlyLaminateTable;
  shape : OPTIONAL PlyLaminateShapeSelect;
END_ENTITY;

ENTITY PlyLaminateSequenceDefinition
  SUBTYPE OF(ConstituentPart);
  pliesInSequence : SET[1:?] OF Ply;
END_ENTITY;

ENTITY PlyLaminateTable
  SUBTYPE OF(LaminateTable);
  sequence : LIST[2:?] OF PlyLaminateSequenceDefinition;
END_ENTITY;

ENTITY PlyOrientationAngle
  ABSTRACT
  SUPERTYPE OF(ONEOF(DrapedOrientationAngle, LaidOrientationAngle));
  description : OPTIONAL DescriptorSelect;
  relationType : OPTIONAL ClassSelect;
  angleReference : AngleSelect;
  fiberDirection : DirectionOfFiberOrientationWithinAPly;
  reinforcementDirection : ReinforcementOrientationBasis;
END_ENTITY;

ENTITY PlyPiece
  SUBTYPE OF(ConstituentPart);
  shape : OPTIONAL PlyShape;
  warp_surface : logical;
END_ENTITY;

ENTITY PlyShape;
  basis : OPTIONAL PlyShape;
  definingModel : PlyLaminateShapeSelect;
END_ENTITY;

ENTITY Point
  SUPERTYPE OF(ONEOF(CartesianPoint))
  SUBTYPE OF(DetailedGeometricModelElement);
END_ENTITY;

ENTITY PointToPointPath
  SUBTYPE OF(PathSegment);
END_ENTITY;

ENTITY PointZoneShape
  SUBTYPE OF(ZoneStructuralMakeupShapeRepresentation);
  location : PointSelect;
END_ENTITY;

ENTITY PrecisionQualifier;
  sameAs : OPTIONAL ProxySelect;
  significantDigits : INTEGER;
END_ENTITY;

ENTITY PreDefinedTypeQualifier;
  name : ClassSelect;
END_ENTITY;

ENTITY ProcessedCore
  SUBTYPE OF(ConstituentPart);
  addedMaterial : OPTIONAL LIST[1:?] OF Ply;
  cellDirection : DirectionOfFiberOrientationWithinAPly;
  madeFromProcessedCore : OPTIONAL SET[1:?] OF ProcessedCore;
  madeFromStock : StockMaterial;
  shape : OPTIONAL CoreShapeSelect;
WHERE
  WR1 : TRUE;
END_ENTITY;

ENTITY ProcessOperationDefinition;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  processType : ClassSelect;
END_ENTITY;

ENTITY ProcessOperationDefinitionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessOperationDefinition;
  related : ProcessOperationDefinition;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProcessOperationInputOrOutput;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  concernedShapes : OPTIONAL SET[1:?] OF ShapeElement;
  element : ProcessOperationInputOrOutputSelect;
  operation : ProcessOperationOccurrence;
  placement : OPTIONAL Transformation;
END_ENTITY;

ENTITY ProcessOperationOccurrence;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  definedIn : OPTIONAL GeometricCoordinateSpace;
  definition : ProcessOperationDefinition;
  plan : ProcessPlan;
END_ENTITY;

ENTITY ProcessOperationOccurrenceRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessOperationOccurrence;
  related : ProcessOperationOccurrence;
  cycleTime : OPTIONAL Duration;
  waitingTime : OPTIONAL PropertyValue;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProcessOperationResourceAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedResource : ProcessOperationResourceAssignmentSelect;
  assignedTo : ProcessOperationOccurrence;
  placement : OPTIONAL Transformation;
  reason : OPTIONAL MultiLingualStringSelect;
  referenceTool : BOOLEAN;
END_ENTITY;

ENTITY ProcessPlan;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  producedOutputs : OPTIONAL SET[1:?] OF PartVersion;
END_ENTITY;

ENTITY ProcessPlanRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessPlan;
  related : ProcessPlan;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProcessStateRelationship
  SUBTYPE OF(PartViewRelationship);
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'process state';
END_ENTITY;

ENTITY ProductClass;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  levelType : OPTIONAL ClassSelect;
  marketSegmentType : OPTIONAL ClassSelect;
  marketName : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY ProductClassRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProductClass;
  related : ProductClass;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProductConfiguration;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definingSpecifications : OPTIONAL SET[1:?] OF Specification;
  memberOf : ProductClass;
INVERSE
  correspondingPartVersion : SET[0:1] OF ProductPartEquivalence FOR associatedProductConfiguration;
END_ENTITY;

ENTITY ProductConfigurationRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProductConfiguration;
  related : ProductConfiguration;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProductPartEquivalence;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedPartVersion : PartVersion;
  associatedProductConfiguration : ProductConfiguration;
END_ENTITY;

ENTITY Project;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  actualEndDate : OPTIONAL DateTimeString;
  actualStartDate : OPTIONAL DateTimeString;
  plannedEndDate : OPTIONAL PeriodOrDateSelect;
  plannedStartDate : OPTIONAL EventOrDateSelect;
  responsibleOrganizations : OPTIONAL SET[1:?] OF Organization;
END_ENTITY;

ENTITY ProjectAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedProject : Project;
  assignedTo : SET[1:?] OF ProjectAssignmentSelect;
END_ENTITY;

ENTITY ProjectRelationship;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Project;
  related : Project;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PromissoryAssemblyOccurrenceUsage
  SUBTYPE OF(AssemblyOccurrenceRelationship);
DERIVE
  SELF\PartViewOccurrenceRelationship.relationType : ClassString := 'promissory assembly occurrence';
END_ENTITY;

ENTITY PromissoryAssemblyViewUsage
  SUBTYPE OF(AssemblyViewRelationship);
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'promissory assembly view';
END_ENTITY;

ENTITY PropertyDefinition;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  propertyType : ClassSelect;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
END_ENTITY;

ENTITY PropertyDefinitionAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedPropertyDefinition : PropertyDefinitionSelect;
  assignedTo : PropertyAssignmentSelect;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
UNIQUE
  UR1: assignedTo, assignedPropertyDefinition;
END_ENTITY;

ENTITY PropertyDefinitionAssignmentRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyDefinitionAssignment;
  related : PropertyDefinitionAssignment;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyDefinitionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyDefinitionSelect;
  related : PropertyDefinitionSelect;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyValue
  ABSTRACT
  SUPERTYPE OF(ONEOF(MaterialPropertyValue, StringValue, ValueList, ValueSet, ValueWithUnit));
  name : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definition : PropertyDefinitionSelect;
  determinationMethod : OPTIONAL ClassSelect;
  qualifications : OPTIONAL SET[1:?] OF MeasureQualification;
WHERE
  encapsulated: SIZEOF(USEDIN(SELF,'')-
 (USEDIN(SELF, SCHEMA_NAME + 'PROPERTYVALUERELATIONSHIP.RELATING')+
 USEDIN(SELF, SCHEMA_NAME + 'PROPERTYVALUERELATIONSHIP.RELATED')))=1;
END_ENTITY;

ENTITY PropertyValueAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedPropertyValues : SET[1:?] OF PropertyValue;
  assignedTo : PropertyAssignmentSelect;
  valueAssignmentContext : OPTIONAL PropertyDefinitionAssignment;
END_ENTITY;

ENTITY PropertyValueAssignmentRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyValueAssignment;
  related : PropertyValueAssignment;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyValueRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyValue;
  related : PropertyValue;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY Proxy;
  individual : ProxyItemSelect;
END_ENTITY;

ENTITY ProxyRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Proxy;
  related : Proxy;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY QualitativeUncertainty
  SUBTYPE OF(UncertaintyQualifier);
  uncertaintyValue : MultiLingualStringSelect;
END_ENTITY;

ENTITY QuantifiedPartOccurrence
  SUBTYPE OF(PartOccurrence);
  quantity : NumericalValue;
END_ENTITY;

ENTITY RealizationOrOccurrenceRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementOrAlternativeSolutionSelect;
  related : BreakdownElementOrPartOccurrenceSelect;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY RectangularSize
  SUPERTYPE OF(ONEOF(NamedSize));
  density : OPTIONAL ValueWithUnit;
  height : OPTIONAL ValueWithUnit;
  width : OPTIONAL ValueWithUnit;
END_ENTITY;

ENTITY ReinforcementOrientationBasis;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  coordinateSpace : GeometricCoordinateSpace;
  placement : CoordinateSystem;
INVERSE
  tables : SET[1:?] OF LaminateTable FOR basis;
END_ENTITY;

ENTITY ReplacedPartViewRelationship
  SUBTYPE OF(PartViewRelationship);
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'replaced part view';
END_ENTITY;

ENTITY ReplacedUsageRelationship
  SUBTYPE OF(PartOccurrenceRelationship);
  usageContext : PartOccurrenceUsageContextSelect;
DERIVE
  SELF\PartOccurrenceRelationship.relationType : ClassString := 'replaced usage';
END_ENTITY;

ENTITY Requirement;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : OPTIONAL SET[1:?] OF RequirementVersion;
END_ENTITY;

ENTITY RequirementAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedRequirement : RequirementVersionOrViewSelect;
  assignedTo : RequirementAssignmentSelect;
END_ENTITY;

ENTITY RequirementCollectionRelationship
  SUBTYPE OF(RequirementViewRelationship);
DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'collection';
END_ENTITY;

ENTITY RequirementDecompositionRelationship
  SUBTYPE OF(RequirementCollectionRelationship);
DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'decomposition';
END_ENTITY;

ENTITY RequirementSatisfactionAssertion;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assertedBy : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  relatedAssignment : OPTIONAL RequirementAssignment;
  satisfiedBy : RequirementAssignmentSelect;
  satisfiedRequirement : RequirementVersionOrViewSelect;
END_ENTITY;

ENTITY RequirementSequenceRelationship
  SUBTYPE OF(RequirementVersionRelationship);
DERIVE
  SELF\RequirementVersionRelationship.relationType : ClassString := 'sequence';
END_ENTITY;

ENTITY RequirementSourceAssociation;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  source : RequirementSourceSelect;
  sourcedRequirement : RequirementVersionOrViewSelect;
END_ENTITY;

ENTITY RequirementTracingRelationship
  SUBTYPE OF(RequirementViewRelationship);
DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'tracing';
END_ENTITY;

ENTITY RequirementVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF RequirementView;
INVERSE
  versionOf : Requirement FOR versions;
END_ENTITY;

ENTITY RequirementVersionRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : RequirementVersion;
  related : RequirementVersion;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY RequirementView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  definitionalRepresentations : SET[1:?] OF PropertyValue;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
INVERSE
  viewOf : RequirementVersion FOR views;
END_ENTITY;

ENTITY RequirementViewRelationship
  SUPERTYPE OF(ONEOF(RequirementCollectionRelationship, RequirementTracingRelationship));
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : RequirementView;
  related : RequirementView;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY RetentionPeriod;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
  earliestEnd : PeriodOrDateSelect;
  latestEnd : PeriodOrDateSelect;
  start : EventOrDateSelect;
END_ENTITY;

ENTITY SameTimeMachiningRelationship
  SUBTYPE OF(PartOccurrenceRelationship);
  placement : OPTIONAL TransformationSelect;
DERIVE
  SELF\PartOccurrenceRelationship.relationType : ClassString := 'same time machining';
END_ENTITY;

ENTITY SecurityClassification;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  level : ClassSelect;
END_ENTITY;

ENTITY SecurityClassificationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedSecurityClassification : SecurityClassification;
  assignedTo : SET[1:?] OF SecurityClassificationSelect;
END_ENTITY;

ENTITY SelectedPartOccurrence
  SUBTYPE OF(PartOccurrence);
  criterion : MultiLingualStringSelect;
  quantity : ValueWithUnit;
END_ENTITY;

ENTITY SerialConfiguration
  SUBTYPE OF(ManufacturingConfiguration);
  endNumber : OPTIONAL IdentifierSelect;
  startNumber : IdentifierSelect;
END_ENTITY;

ENTITY SerialEffectivity
  SUBTYPE OF(Effectivity);
  endNumber : OPTIONAL IdentifierSelect;
  startNumber : IdentifierSelect;
END_ENTITY;

ENTITY SetMembership;
  member : ProxyItemSelect;
  ofSet : ClassSelect;
END_ENTITY;

ENTITY ShapeDependentProperty
  ABSTRACT
  SUPERTYPE OF(ONEOF(CentreOfMass, GeneralShapeDependentProperty, MomentsOfInertia));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedTo : ShapedElementSelect;
  definedIn : OPTIONAL GeometricCoordinateSpace;
  valueDetermination : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY ShapeDescriptionAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  definingGeometry : GeometricModel;
  isDefiningShapeFor : ShapeInformationSelect;
END_ENTITY;

ENTITY ShapeElement
  SUPERTYPE OF(ONEOF(CoatingLayer));
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
INVERSE
  containingShape : PartShape FOR elements;
END_ENTITY;

ENTITY ShapeElementRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ShapeElement;
  related : ShapeElement;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY SinglePartOccurrence
  SUBTYPE OF(PartOccurrence);
END_ENTITY;

ENTITY SizeProperty;
  description : OPTIONAL DescriptorSelect;
  fileSize : OPTIONAL ValueWithUnit;
  pageCount : OPTIONAL ValueWithUnit;
END_ENTITY;

ENTITY SmearedMaterial
  SUBTYPE OF(ZoneStructuralMakeup);
  totalThickness : NumericalValue;
END_ENTITY;

ENTITY Specification;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  category : SpecificationCategory;
  package : BOOLEAN;
END_ENTITY;

ENTITY SpecificationCategory;
  id : IdentifierSelect;
  description : DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  implicitExclusiveCondition : BOOLEAN;
END_ENTITY;

ENTITY SpecificationCategoryHierarchy;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  subCategory : SpecificationCategory;
  superCategory : SpecificationCategory;
END_ENTITY;

ENTITY SpecificationExpression;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  operands : SET[1:?] OF SpecificationOperandSelect;
  theOperation : SpecificationExpressionOperationEnum;
END_ENTITY;

ENTITY SpecificationInclusion;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  ifCondition : SpecificationOperandSelect;
  includedSpecification : SpecificationOperandSelect;
END_ENTITY;

ENTITY SpecifiedPartOccurrence
  SUBTYPE OF(PartOccurrence);
  assemblyContext : AssemblyDefinition;
  subAssemblyRelationship : PartOccurrence;
  upperAssemblyRelationship : PartOccurrence;
END_ENTITY;

ENTITY StandardUncertainty
  SUPERTYPE OF(ONEOF(ExpandedUncertainty))
  SUBTYPE OF(UncertaintyQualifier);
  uncertaintyValue : REAL;
END_ENTITY;

ENTITY StockMaterial;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  stockMaterialType : StockCategoryEnum;
  propertyValues : SET[1:?] OF MaterialPropertyValue;
  referenceDirection : OPTIONAL Direction;
END_ENTITY;

ENTITY StringValue
  SUBTYPE OF(PropertyValue);
  valueComponent : MultiLingualStringSelect;
END_ENTITY;

ENTITY StyledModel
  SUBTYPE OF(TemplateDefinition);
  id : IdentifierSelect;
  modelType : ClassSelect;
  definedIn : DigitalFile;
END_ENTITY;

ENTITY SubsetMember;
  subset : ClassSelect;
  superset : ClassSelect;
END_ENTITY;

ENTITY SuppliedObjectRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : SuppliedObjectSelect;
  related : SuppliedObjectSelect;
END_ENTITY;

ENTITY SupplierSolution
  SUBTYPE OF(AlternativeSolution);
  probabilityRate : OPTIONAL REAL;
  supplier : Organization;
END_ENTITY;

ENTITY SurfaceCondition;
  id : IdentifierSelect;
  conditionType : ClassString;
  definedIn : DigitalFile;
END_ENTITY;

ENTITY SurfaceWithDirection;
  definingSurface : OrientedSurfaceSelect;
  materialDirection : Direction;
END_ENTITY;

ENTITY SystemBreakdown
  SUBTYPE OF(Breakdown);
DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'system';
END_ENTITY;

ENTITY TechnicalSolution
  SUBTYPE OF(AlternativeSolution);
END_ENTITY;

ENTITY TemplateDefinition
  ABSTRACT
  SUPERTYPE OF(ONEOF(GeometricModel, StyledModel));
INVERSE
  templateInstances : SET[0:?] OF TemplateInstance FOR definition;
END_ENTITY;

ENTITY TemplateInstance
  SUBTYPE OF(DetailedGeometricModelElement);
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  definition : TemplateDefinition;
  origin : CoordinateSystem;
  scale : OPTIONAL REAL;
  target : ExplicitTransformationSelect;
END_ENTITY;

ENTITY ThicknessLaminateTable
  SUBTYPE OF(ZoneStructuralMakeup);
  tableComponents : LIST[2:?] OF ThicknessLaminateTableComponentSelect;
END_ENTITY;

ENTITY ThicknessSizeDimension;
  id : IdentifierSelect;
  appliedTo : ShapeElement;
  thickness : NumericalValue;
END_ENTITY;

ENTITY ThreeDGeometrySet
  SUBTYPE OF(ConstituentShapeRepresentation);
  basisRole : ClassSelect;
  basisSurface : ExternalSurface;
  definingBoundary : SET[1:?] OF GeometricBoundingCurveSelect;
  threeDGeometry : ExternalGeometricModel;
END_ENTITY;

ENTITY TimeInterval;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  endDefinition : PeriodOrDateSelect;
  startDefinition : EventOrDateSelect;
END_ENTITY;

ENTITY TimeIntervalAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedTimeInterval : TimeInterval;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
END_ENTITY;

ENTITY TimeIntervalConfiguration
  SUBTYPE OF(ManufacturingConfiguration);
  configurationPeriod : TimeInterval;
END_ENTITY;

ENTITY TimeIntervalEffectivity
  SUBTYPE OF(Effectivity);
  effectivityPeriod : TimeInterval;
END_ENTITY;

ENTITY ToolPartRelationship
  SUBTYPE OF(PartViewRelationship);
  placement : OPTIONAL TransformationSelect;
DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'tool part';
END_ENTITY;

ENTITY Transformation
  ABSTRACT
  SUPERTYPE OF(ONEOF(Transformation2d, Transformation3d))
  SUBTYPE OF(DetailedGeometricModelElement);
  name : OPTIONAL DescriptorSelect;
END_ENTITY;

ENTITY Transformation2d
  SUPERTYPE OF(ONEOF(ExplicitTransformation2d, ImplicitTransformation2d))
  SUBTYPE OF(Transformation);
END_ENTITY;

ENTITY Transformation3d
  SUPERTYPE OF(ONEOF(ExplicitTransformation3d, ImplicitTransformation3d))
  SUBTYPE OF(Transformation);
END_ENTITY;

ENTITY UncertaintyQualifier
  SUPERTYPE OF(ONEOF(QualitativeUncertainty, StandardUncertainty));
  description : OPTIONAL DescriptorSelect;
  measureName : MultiLingualStringSelect;
  sameAs : OPTIONAL ProxySelect;
END_ENTITY;

ENTITY Unit;
  name : ClassSelect;
  kind : OPTIONAL ClassSelect;
  prefix : OPTIONAL ClassSelect;
  quantity : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY ValueLimit
  SUBTYPE OF(NumericalValue);
  qualifier : TypeQualifierSelect;
END_ENTITY;

ENTITY ValueList
  SUBTYPE OF(PropertyValue);
  values : LIST[1:?] OF PropertyValue;
END_ENTITY;

ENTITY ValueRange
  SUBTYPE OF(ValueWithUnit);
  lowerLimit : REAL;
  upperLimit : REAL;
END_ENTITY;

ENTITY ValueSet
  SUBTYPE OF(PropertyValue);
  values : SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY ValueWithTolerances
  SUBTYPE OF(ValueWithUnit);
  lowerLimit : REAL;
  tolerancedValue : REAL;
  upperLimit : REAL;
END_ENTITY;

ENTITY ValueWithUnit
  ABSTRACT
  SUPERTYPE OF(ONEOF(NumericalValue, ValueRange, ValueWithTolerances))
  SUBTYPE OF(PropertyValue);
  significantDigits : OPTIONAL INTEGER;
  unit : UnitSelect;
END_ENTITY;

ENTITY ViewContext;
  description : OPTIONAL DescriptorSelect;
  applicationDomain : ApplicationDomainSelect;
  lifeCycleStage : LifeCycleStageSelect;
UNIQUE
  UR1: applicationDomain, lifeCycleStage;
END_ENTITY;

ENTITY WorkOrder;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  orderType : ClassSelect;
  inResponseTo : OPTIONAL SET[1:?] OF WorkRequest;
  isControlling : SET[1:?] OF Activity;
END_ENTITY;

ENTITY WorkRequest;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  requestType : ClassSelect;
  notifiedPersons : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  requestor : DateAndPersonOrganization;
  scopes : OPTIONAL SET[1:?] OF ActivityAssignmentSelect;
  status : ClassSelect;
END_ENTITY;

ENTITY WorkRequestRelationship;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : WorkRequest;
  related : WorkRequest;
WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ZonalBreakdown
  SUBTYPE OF(Breakdown);
DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'zonal';
END_ENTITY;

ENTITY ZoneStructuralMakeup
  ABSTRACT
  SUPERTYPE OF(ONEOF(PercentageLaminateTable, SmearedMaterial, ThicknessLaminateTable))
  SUBTYPE OF(LaminateTable);
  boundary : ZoneStructuralMakeupShapeRepresentation;
END_ENTITY;

ENTITY ZoneStructuralMakeupShapeRepresentation
  SUPERTYPE OF(ONEOF(EdgeZoneShape, PointZoneShape));
END_ENTITY;

END_SCHEMA;