(*
   $Id: mim.exp,v 1.5 2005/04/04 10:08:35 liutkus Exp $
   ISO TC184/SC4/WG12 N3433 - ISO/CD-TS 10303-1680 Functional unit requirement allocation - EXPRESS MIM
*)


SCHEMA Functional_unit_requirement_allocation_mim;
	USE FROM Network_functional_design_view_mim;	-- ISO/TS 10303-1704
	
TYPE fura_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH 
     (component_functional_unit);
END_TYPE; 
	
END_SCHEMA;

