SCHEMA managed_model_based_3d_engineering_bom;

-- Release candidate 10 for SMRLv6
(*
Changes against RC9:
- Bugzilla #5000: TYPE TransformationSelect = SELECT (
  GeometricRepresentationRelationshipWithPlacementTransformation,
  CartesianTransformation
); ==>
TYPE TransformationSelect = SELECT (
  GeometricRepresentationRelationship
  CartesianTransformation
);
- Bugzilla #5001: in ExternalGeometricModel, ComposedGeometricModel:
  SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacement; ==> SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacementOrTransformationSelect;
- Bugzilla #4957: AlternativeSolution added to EffectivityAssignmentSelect
- Bugzilla #4956: ENTITY Effectivity SUPERTYPE OF(ONEOF(DataValidityEffectivity, LotEffectivity, SerialEffectivity, TimeIntervalEffectivity));
   ==>            ENTITY Effectivity SUPERTYPE OF(ONEOF(ConditionalEffectivity, DataValidityEffectivity, LotEffectivity, SerialEffectivity, TimeIntervalEffectivity));
- Bugzilla #4956: ENTITY KinematicLinkToOccurrenceAssociation;
  associatedLink : KinematicLink;
  associatedTo : AssemblyOccurrenceRelationship;	
END_ENTITY;
==>
ENTITY KinematicLinkToOccurrenceAssociation;
  associatedLink : KinematicLink;
  associatedTo : Occurrence;	
END_ENTITY;

*)


CONSTANT
 SCHEMA_NAME : STRING := 'MANAGED_MODEL_BASED_3D_ENGINEERING_BOM.';
END_CONSTANT;


(*:PI1
 ------------------------------------------------------------
  Part and Version Identification
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Part;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  partTypes : SET[1:?] OF ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : SET[1:?] OF PartVersion;
END_ENTITY;

ENTITY PartVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF PartView;
 INVERSE
  correspondingProductConfiguration : SET[0:1] OF ProductDesignAssociation FOR associatedDesign;
  versionOf : Part FOR versions;
END_ENTITY;

ENTITY PartRelationship
 SUPERTYPE OF(ONEOF(AlternatePartRelationship));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Part;
  related : Part;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AlternatePartRelationship
 SUBTYPE OF(PartRelationship);
  criteria : OPTIONAL MultiLingualStringSelect;
 DERIVE
  SELF\PartRelationship.relationType : ClassString := 'alternate';
 UNIQUE
  UR1: relating, related;
END_ENTITY;

ENTITY PartVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartVersion;
  related : PartVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


(*:PI2
 ------------------------------------------------------------
  Part View
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY PartView
 SUPERTYPE OF(ONEOF(AssemblyDefinition, CollectionDefinition, ConstituentPart, LaminateTable));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  definingGeometry : OPTIONAL GeometricModel;
 INVERSE
  viewOf : PartVersion FOR views;
END_ENTITY;

ENTITY PartViewRelationship
 SUPERTYPE OF(ONEOF(AssemblyViewRelationship, GeometricalRelationship, MakeFromRelationship, ProcessStateRelationship, ReplacedPartViewRelationship, ToolPartRelationship));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartView;
  related : PartView;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ViewContext;
  description : OPTIONAL DescriptorSelect;
  applicationDomain : ApplicationDomainSelect;
  lifeCycleStage : LifeCycleStageSelect;
 UNIQUE
  UR1: applicationDomain, lifeCycleStage;
END_ENTITY;

TYPE ApplicationDomainSelect = SELECT (
  ApplicationDomain,
  ProxySelect
);
END_TYPE;

TYPE LifeCycleStageSelect = SELECT (
  LifeCycleStage,
  ProxySelect
);
END_TYPE;

ENTITY ApplicationDomain;
  sameAs : SET[1:?] OF ProxySelect;
 UNIQUE
  UR1: sameAs;
END_ENTITY;

ENTITY LifeCycleStage;
  sameAs : SET[1:?] OF ProxySelect;
 UNIQUE
  UR1: sameAs;
END_ENTITY;


(*:SBC1
 ------------------------------------------------------------
  Product Specification
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Market;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  marketSegmentType : OPTIONAL ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

 ENTITY ProductConcept
 SUPERTYPE OF(ONEOF(ProductClass));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  targetMarket : OPTIONAL Market;
END_ENTITY;

ENTITY ProductClass
 SUBTYPE OF (ProductConcept); 
  versionId : OPTIONAL IdentifierSelect;
  levelType : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY ProductClassRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProductClass;
  related : ProductClass;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

-- specifications

ENTITY Specification;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  category : SpecificationCategory;
  package : BOOLEAN;
END_ENTITY;

ENTITY SpecificationCategory;
  id : IdentifierSelect;
  description : DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  implicitExclusiveCondition : BOOLEAN;
END_ENTITY;

ENTITY SpecificationCategoryHierarchy;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  subCategory : SpecificationCategory;
  superCategory : SpecificationCategory;
END_ENTITY;

ENTITY SpecificationInclusion;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  ifCondition : ConditionParameterSelect;
  includedSpecification : ConditionParameterSelect;
END_ENTITY;

ENTITY SpecificationCategoryAssignment;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedCategory : SpecificationCategory;
  assignedTo : ProductClass;
  mandatory : BOOLEAN;
END_ENTITY;

ENTITY SpecificationConditionAssignment;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  conditionType : ClassSelect;
  assignedCondition : Condition;
  assignedTo : ProductClass;
END_ENTITY;

ENTITY SpecificationInclusionAssignment;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedInclusion : SpecificationInclusion;
  assignedTo : ProductClass;
END_ENTITY;

ENTITY SpecificationAssignment;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associationType : ClassSelect;
  assignedTo : ProductClass;
  assignedSpecification : Specification;
END_ENTITY;

-- conditions

ENTITY Condition
 SUPERTYPE OF (ONEOF (AndCondition, OrCondition, NotCondition, OneOfCondition, EqualsCondition, NotEqualsCondition));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  conditionType : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  parameters : SET[1:?] OF ParameterSelect;
END_ENTITY;

ENTITY ConditionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Condition;
  related : Condition;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

TYPE ParameterSelect = SELECT (
  ConditionParameter, 
  ConditionParameterSelect
);
END_TYPE;

ENTITY ConditionParameter;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  parameter : OPTIONAL ConditionParameterSelect;
END_ENTITY;

TYPE ConditionParameterSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  AddressAssignment,
  Approval,
  ApprovalAssignment,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionAssignment,
  CertificationAssignment,
  Classification,
  Condition,
  ConditionAssignment,
  ConditionRelationship,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  DateTimeString,
  Descriptor,
  Document,
  DocumentAssignment,
  DocumentDefinitionRelationship,
  DocumentDefinition,
  DocumentVersion,
  EffectivityAssignment,
  EventAssignment,
  FrozenAssignment,
  Identifier,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Organization,
  OrganizationOrPersonInOrganizationAssignment,
  Part,
  PartVersion,
  PartView,
  PartViewRelationship,
  ProcessOperationResourceAssignment,
  ProductConcept,
  ProductConfiguration,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueRelationship,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementVersion,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassificationAssignment,
  Specification,
  SpecificationAssignment,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  TimeIntervalAssignment,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment
);
END_TYPE;

ENTITY AndCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'and';
END_ENTITY;

ENTITY OrCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'or';
END_ENTITY;

ENTITY NotCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'not';
END_ENTITY;

ENTITY OneOfCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'one of';
END_ENTITY;

ENTITY EqualsCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'equals';
END_ENTITY;

ENTITY NotEqualsCondition
 SUBTYPE OF (Condition);
 DERIVE
  SELF\Condition.conditionType : ClassSelect := 'not equals';
END_ENTITY;

ENTITY ConditionAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedCondition : Condition;
  assignedTo : ConditionAssignmentSelect;
END_ENTITY;

TYPE ConditionAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  AddressAssignment,
  Approval,
  ApprovalAssignment,
  BreakdownElementViewRelationship,
  BreakdownVersionAssignment,
  CertificationAssignment,
  ConditionAssignment,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  DocumentAssignment,
  DocumentDefinitionRelationship,
  Effectivity,
  EffectivityAssignment,
  EventAssignment,
  FrozenAssignment,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  OrganizationOrPersonInOrganizationAssignment,
  PartViewRelationship,
  ProcessOperationResourceAssignment,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyValueAssignment,
  RequirementAssignment,
  RequirementViewRelationship,
  SecurityClassificationAssignment,
  SpecificationAssignment,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  TimeIntervalAssignment,
  WorkOrderAssignment,
  WorkRequestAssignment
);
END_TYPE;


(*:SBC2
 ------------------------------------------------------------
  Breakdown
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Breakdown
 SUPERTYPE OF(ONEOF(FunctionalBreakdown, PhysicalBreakdown, SystemBreakdown, ZonalBreakdown));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  breakdownType : ClassSelect;
  versions : SET[1:?] OF BreakdownVersion;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 WHERE
  WR1: NOT(TYPEOF(SELF) = [SCHEMA_NAME + 'BREAKDOWN']) OR ((SELF.breakdownType <> 'physical') AND (SELF.breakdownType <> 'functional') AND (SELF.breakdownType <> 'zonal') AND (SELF.breakdownType <> 'system'));
END_ENTITY;

ENTITY BreakdownRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Breakdown;
  related : Breakdown;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 INVERSE
  versionOf : Breakdown FOR versions;
END_ENTITY;

ENTITY BreakdownVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownVersion;
  related : BreakdownVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownVersionAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedBreakdownVersion : BreakdownVersion;
  assignedTo : SET[1:?] OF BreakdownVersionAssignmentSelect;
END_ENTITY;

TYPE BreakdownVersionAssignmentSelect = SELECT (
  DocumentDefinition,
  IndividualPartView,
  Occurrence,
  PartView,
  ProductClass,
  ProductConfiguration,
  RequirementView
);
END_TYPE;

ENTITY BreakdownElement;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : OPTIONAL SET[1:?] OF BreakdownElementVersion;
END_ENTITY;

ENTITY BreakdownElementRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElement;
  related : BreakdownElement;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


ENTITY BreakdownContext;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  breakdownContext : BreakdownVersion;
  breakdownElement : BreakdownElement;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;
(*
ENTITY BreakdownElementAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedBreakdown : BreakdownVersion;
  associatedElement : BreakdownElement;
END_ENTITY;
*)
ENTITY BreakdownElementVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF BreakdownElementView;
 INVERSE
  versionOf : BreakdownElement FOR versions;
END_ENTITY;

ENTITY BreakdownElementVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementVersion;
  related : BreakdownElementVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY BreakdownElementView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  definingGeometry : OPTIONAL GeometricModel;
 INVERSE
  viewOf : BreakdownElementVersion FOR views;
END_ENTITY;

ENTITY BreakdownElementViewRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementView;
  related : BreakdownElementView;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY FunctionalBreakdown
 SUBTYPE OF(Breakdown);
 DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'functional';
END_ENTITY;

ENTITY FunctionalBreakdownElementViewAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  associatedFunctionalElement : BreakdownElementView;
  associatedPhysicalElement : PhysicalElementSelect;
END_ENTITY;

TYPE PhysicalElementSelect = SELECT (
  AlternativeSolution,
  BreakdownElement,
  PartView
);
END_TYPE;

ENTITY PhysicalBreakdown
 SUBTYPE OF(Breakdown);
 DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'physical';
END_ENTITY;

ENTITY SystemBreakdown
 SUBTYPE OF(Breakdown);
 DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'system';
END_ENTITY;

ENTITY ZonalBreakdown
 SUBTYPE OF(Breakdown);
 DERIVE
  SELF\Breakdown.breakdownType : ClassString := 'zonal';
END_ENTITY;

ENTITY InZone;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  locatedItem : InZoneSelect;
  zone : BreakdownElementView;
END_ENTITY;

TYPE InZoneSelect = SELECT (
  ActivityMethod,
  ActivityMethodAssignment,
  BreakdownElementView,
  DocumentDefinition,
  IndividualPartView,
  PartView,
  RequirementView
);
END_TYPE;

ENTITY BreakdownElementRealization;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : BreakdownElementOrAlternativeSolutionSelect;
  related : BreakdownElementOrOccurrenceSelect;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

TYPE BreakdownElementOrAlternativeSolutionSelect = SELECT (
  AlternativeSolution,
  BreakdownElement
);
END_TYPE;

TYPE BreakdownElementOrOccurrenceSelect = SELECT (
  BreakdownElement,
  Occurrence
);
END_TYPE;

ENTITY AlternativeSolution
 SUPERTYPE OF(ONEOF(FinalSolution, SupplierSolution, TechnicalSolution));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  baseElement : BreakdownElementOrAlternativeSolutionSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY AlternativeSolutionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : AlternativeSolution;
  related : AlternativeSolution;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY FinalSolution
 SUBTYPE OF(AlternativeSolution);
  specifications : SET[1:?] OF FinalDefinitionSelect;
  status : ClassSelect;
END_ENTITY;

TYPE FinalDefinitionSelect = SELECT (
  IndividualPartView,
  PartView,
  RequirementView
);
END_TYPE;

ENTITY SupplierSolution
 SUBTYPE OF(AlternativeSolution);
  probabilityRate : OPTIONAL REAL;
  supplier : Organization;
END_ENTITY;

ENTITY TechnicalSolution
 SUBTYPE OF(AlternativeSolution);
END_ENTITY;

ENTITY ComponentPlacement;
  placedComponent : BreakdownElementView;
  placement : TransformationSelect;
  referenceComponent : BreakdownElementView;
 WHERE
  WR1: NOT ('GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(placement)) OR (placement.definitional = TRUE);
END_ENTITY;

ENTITY OccurrencePlacement;
  placedInstance : SingleOccurrence;
  placement : TransformationSelect;
  referenceComponent : BreakdownElementView;
 WHERE
  WR1: NOT ('GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(placement)) OR (placement.definitional = TRUE);
END_ENTITY;


(*:SBC3
 ------------------------------------------------------------
  Assembly Structure
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE TransformationSelect = SELECT (
  GeometricRepresentationRelationship,
  CartesianTransformation
);
END_TYPE;

ENTITY AssemblyOccurrenceRelationship
 ABSTRACT
 SUPERTYPE OF(ONEOF(NextAssemblyOccurrenceUsage, PromissoryAssemblyOccurrenceUsage))
 SUBTYPE OF(ViewOccurrenceRelationship);
  SELF\ViewOccurrenceRelationship.relating : AssemblyDefinition;
  placement : OPTIONAL TransformationSelect;
 WHERE
  WR1: NOT ('GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(placement)) OR (placement.definitional = TRUE);
END_ENTITY;

ENTITY AssemblyOccurrenceRelationshipSubstitution;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : AssemblyOccurrenceRelationship;
  related : AssemblyOccurrenceRelationship;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY AssemblyViewRelationship
 ABSTRACT
 SUPERTYPE OF(ONEOF(NextAssemblyViewUsage, PromissoryAssemblyViewUsage))
 SUBTYPE OF(PartViewRelationship);
  SELF\PartViewRelationship.relating : AssemblyDefinition;
  locationIndicator : OPTIONAL IdentifierSelect;
  quantity : OPTIONAL ValueWithUnit;
  definingGeometry : OPTIONAL GeometricModel;
END_ENTITY;

ENTITY AssemblyViewRelationshipSubstitution;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : AssemblyViewRelationship;
  related : AssemblyViewRelationship;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY GeometricalRelationship
 SUBTYPE OF(PartViewRelationship);
  placement : GeometricRepresentationRelationshipWithPlacementTransformation;
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'geometrically related part view';
END_ENTITY;

ENTITY NextAssemblyOccurrenceUsage
 SUPERTYPE OF(ONEOF(MatedPartAssociation))
 SUBTYPE OF(AssemblyOccurrenceRelationship);
 DERIVE
  SELF\ViewOccurrenceRelationship.relationType : ClassString := 'next assembly occurrence';
END_ENTITY;

ENTITY NextAssemblyViewUsage
 SUBTYPE OF(AssemblyViewRelationship);
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'next assembly view';
END_ENTITY;

ENTITY PromissoryAssemblyOccurrenceUsage
 SUBTYPE OF(AssemblyOccurrenceRelationship);
 DERIVE
  SELF\ViewOccurrenceRelationship.relationType : ClassString := 'promissory assembly occurrence';
END_ENTITY;

ENTITY PromissoryAssemblyViewUsage
 SUBTYPE OF(AssemblyViewRelationship);
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'promissory assembly view';
END_ENTITY;

ENTITY ReplacedPartViewRelationship
 SUBTYPE OF(PartViewRelationship);
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'replaced part view';
END_ENTITY;

ENTITY AssemblyDefinition
 SUPERTYPE OF(ONEOF(MatingDefinition))
 SUBTYPE OF(PartView);
  assemblyType : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY CollectionDefinition
 SUBTYPE OF(PartView);
  purpose : OPTIONAL MultiLingualStringSelect;
 INVERSE
  collectedParts : SET[2:?] OF CollectedPartRelationship FOR relating;
END_ENTITY;

ENTITY CollectedPartRelationship
 SUBTYPE OF(ViewOccurrenceRelationship);
  SELF\ViewOccurrenceRelationship.relating : CollectionDefinition;
 DERIVE
  SELF\ViewOccurrenceRelationship.relationType : ClassString := 'collected part view';
END_ENTITY;


(*:SBC4
 ------------------------------------------------------------
  Configuration
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY ConditionalEffectivity
  SUPERTYPE OF(ONEOF(ConditionalConfiguration))
  SUBTYPE OF (Effectivity);
  condition : Condition;
END_ENTITY;


ENTITY ConditionalConfiguration
 SUBTYPE OF(ConditionalEffectivity);
  configurationType : ClassSelect;
  inheritanceType : ClassSelect;
  configuredElement : ConfiguredItemSelect;
  resolvedConfiguration : ConfiguredSpecificationSelect;
END_ENTITY;

TYPE ConfiguredItemSelect = SELECT (
  AlternativeSolution,
  BreakdownElement,
  Occurrence,
  AssemblyViewRelationship,
  ProcessOperationOccurrence,
  ProcessPlan
);
END_TYPE;

TYPE ConfiguredSpecificationSelect = SELECT (
  SpecificationConditionAssignment,
  SpecificationAssignment
);
END_TYPE;

ENTITY ConfiguredAssemblyEffectivity;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  configuredElement : AssemblyDesignSelect;
  resolvedConfiguration : ProductDesignAssociation;
  effectivityDomain : Effectivity;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY ProductConfiguration;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  definingSpecifications : OPTIONAL SET[1:?] OF Specification;
  memberOf : ProductClass;
INVERSE
  correspondingPartVersion : SET[0:1] OF ProductDesignAssociation FOR associatedConfiguration;
END_ENTITY;

ENTITY ProductConfigurationRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProductConfiguration;
  related : ProductConfiguration;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProductDesignAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  associatedDesign : PartVersion;
  associatedConfiguration : ProductConfiguration;
END_ENTITY;

(*:SBC5
 ------------------------------------------------------------
  Part Occurrence
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Occurrence
 ABSTRACT
 SUPERTYPE OF(ONEOF(QuantifiedOccurrence, SelectedOccurrence, SingleOccurrence, SpecifiedOccurrence));
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definition : OccurrenceDefinitionSelect;
  definingGeometry : OPTIONAL GeometricModel;
END_ENTITY;

TYPE OccurrenceDefinitionSelect = SELECT (
  PartView,
  ProductConfiguration
);
END_TYPE;

ENTITY OccurrenceRelationship
 SUPERTYPE OF(ONEOF(ReplacedUsageRelationship, SameTimeMachiningRelationship));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Occurrence;
  related : Occurrence;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ViewOccurrenceRelationship
 SUPERTYPE OF(ONEOF(AssemblyOccurrenceRelationship, CollectedPartRelationship));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PartView;
  related : Occurrence;
END_ENTITY;

ENTITY QuantifiedOccurrence
 SUBTYPE OF(Occurrence);
  quantity : NumericalValue;
END_ENTITY;

ENTITY ReplacedUsageRelationship
 SUBTYPE OF(OccurrenceRelationship);
  usageContext : OccurrenceUsageContextSelect;
 DERIVE
  SELF\OccurrenceRelationship.relationType : ClassString := 'replaced usage';
END_ENTITY;

TYPE OccurrenceUsageContextSelect = SELECT (
  ViewOccurrenceRelationship,
  ProcessOperationInputOrOutput,
  BreakdownElementRealization
);
END_TYPE;

ENTITY SelectedOccurrence
 SUBTYPE OF(Occurrence);
  criterion : MultiLingualStringSelect;
  quantity : ValueWithUnit;
END_ENTITY;

ENTITY SingleOccurrence
 SUBTYPE OF(Occurrence);
END_ENTITY;

ENTITY SpecifiedOccurrence
 SUBTYPE OF(Occurrence);
  assemblyContext : AssemblyDefinition;
  subAssemblyRelationship : Occurrence;
  upperAssemblyRelationship : Occurrence;
END_ENTITY;


(*:SBC6
 ------------------------------------------------------------
  Transformation, Geometric Coordinate Space, and Coordinate System
 ------------------------------------------------------------
*)

-- partially harmonized with PLCS

ENTITY RepresentationItem
 ABSTRACT
 SUPERTYPE OF(ONEOF(DetailedGeometricModelItem, ExternalRepresentationItem, KinematicPair, KinematicPairValue, InterpolatedConfigurationSequence));
  external : OPTIONAL ExternalItem;
  name : OPTIONAL DescriptorSelect;
END_ENTITY;

ENTITY ExternalRepresentationItem
 SUBTYPE OF (RepresentationItem);
  SELF\RepresentationItem.external : ExternalItem;
END_ENTITY;

ENTITY ExternalItem;
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
 UNIQUE
  UR1: id, source;
END_ENTITY;

ENTITY DetailedGeometricModelItem
 ABSTRACT
 SUPERTYPE OF(ONEOF(RotationAboutDirection, AxisPlacement, Direction, Point, CartesianTransformation, Loop, Surface, Curve, PointPath))
 SUBTYPE OF (RepresentationItem);
END_ENTITY;

ENTITY AxisPlacement
 SUBTYPE OF(DetailedGeometricModelItem);
  position : LIST [2:3] OF LengthMeasure;
  refDirection : OPTIONAL LIST [2:3] OF LengthMeasure;
  axis : OPTIONAL LIST [2:3] OF LengthMeasure;
 DERIVE
  dim : INTEGER := SIZEOF(position);
WHERE
  WR1: SIZEOF(refDirection) = SIZEOF(position);
  WR2: NOT(EXISTS(axis)) OR (SIZEOF(axis) = SIZEOF(position));
END_ENTITY;

ENTITY Direction
 SUBTYPE OF(DetailedGeometricModelItem);
  directionRatios : LIST [2:3] OF LengthMeasure;
DERIVE
  dim : INTEGER := SIZEOF(directionRatios);
END_ENTITY;

TYPE LengthMeasure = REAL;
END_TYPE;

ENTITY Point
 ABSTRACT
 SUPERTYPE OF(ONEOF(CartesianPoint, PointOnCurve, PointOnSurface))
 SUBTYPE OF(DetailedGeometricModelItem);
END_ENTITY;

ENTITY CartesianPoint
 SUBTYPE OF(Point);
  coordinates : LIST [2:3] OF LengthMeasure;
DERIVE
  dim : INTEGER := SIZEOF(coordinates);
END_ENTITY;

ENTITY CartesianTransformation
 SUBTYPE OF(DetailedGeometricModelItem);
  rotationMatrix : LIST [2:3] OF LIST [2:3] OF LengthMeasure;
  translationVector : LIST [2:3] OF LengthMeasure;
  scale : OPTIONAL REAL;
DERIVE
  dim : INTEGER := SIZEOF(translationVector);
  scl : REAL := NVL(scale, 1.0);
WHERE
  WR1: scl > 0.0;
  WR2: SIZEOF(translationVector) = SIZEOF(rotationMatrix);
END_ENTITY;

ENTITY GeometricCoordinateSpace;
  id : IdentifierSelect;
  accuracies : OPTIONAL SET[1:?] OF MeasureQualification;
  dimensionCount : INTEGER;
  units : OPTIONAL SET[1:?] OF Unit;
 WHERE
  WR1: dimensionCount > 0;
END_ENTITY;


(*:PPP1
 ------------------------------------------------------------
  Individual Part
 ------------------------------------------------------------
*)

-- partially harmonized with PLCS

ENTITY AssemblyRealizationContext;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : IndividualAssemblyRelationship;
  related : AssemblyDesignSelect;
END_ENTITY;

TYPE AssemblyDesignSelect = SELECT (
  AssemblyViewRelationship,
  Occurrence
);
END_TYPE;

ENTITY IndividualAssemblyRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : IndividualPartView;
  related : IndividualPartView;
 DERIVE
  relationType : ClassString := 'next assembly view';
 INVERSE
  isRealizationOf : AssemblyRealizationContext FOR relating;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY IndividualPart;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : SET[1:?] OF IndividualPartVersion;
END_ENTITY;

ENTITY IndividualPartRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : IndividualPart;
  related : IndividualPart;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY IndividualPartVersion
 SUPERTYPE OF(ONEOF(PlannedIndividualPart, RealizedIndividualPart));
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF IndividualPartView;
 INVERSE
  versionOf : IndividualPart FOR versions;
END_ENTITY;

ENTITY IndividualPartVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : IndividualPartVersion;
  related : IndividualPartVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY IndividualPartView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  definingGeometry : OPTIONAL GeometricModel;
 INVERSE
  viewOf : IndividualPartVersion FOR views;
END_ENTITY;

ENTITY IndividualPartViewRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : IndividualPartView;
  related : IndividualPartView;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PartToIndividualPartAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPart;
  associatedPart : Part;
END_ENTITY;

ENTITY PartVersionToIndividualPartVersionAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPartVersion;
  associatedPart : PartVersionOrProductConfigurationSelect;
END_ENTITY;

TYPE PartVersionOrProductConfigurationSelect = SELECT (
  PartVersion,
  ProductConfiguration
);
END_TYPE;

ENTITY PartViewToIndividualPartViewAssociation;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  associatedInduvidualPart : IndividualPartView;
  associatedPart : PartViewOrProductConfigurationSelect;
END_ENTITY;

TYPE PartViewOrProductConfigurationSelect = SELECT (
  PartView,
  ProductConfiguration
);
END_TYPE;

ENTITY PlannedIndividualPart
 SUBTYPE OF (IndividualPartVersion);
END_ENTITY;

ENTITY RealizedIndividualPart
 SUBTYPE OF (IndividualPartVersion);
END_ENTITY;

ENTITY ProductPlannedToRealized
 SUBTYPE OF (IndividualPartVersionRelationship);
  SELF\IndividualPartVersionRelationship.relating : PlannedIndividualPart;
  SELF\IndividualPartVersionRelationship.related : RealizedIndividualPart;
END_ENTITY;

(*:E1
 ------------------------------------------------------------
  Effectivity
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Effectivity
 SUPERTYPE OF(ONEOF(ConditionalEffectivity, DataValidityEffectivity, LotEffectivity, SerialEffectivity, TimeIntervalEffectivity));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  concernedOrganizations : OPTIONAL SET[1:?] OF Organization;
  effectivityContext : OPTIONAL EffectivityContextSelect;
  endDefinition : OPTIONAL EventOrDateSelect;
  startDefinition : OPTIONAL EventOrDateSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

TYPE EffectivityContextSelect = SELECT ( 
  Activity,  
  Contract, 
  Project,
  Organization, 
  PersonInOrganization,
  ProductClass,
  ProductConfiguration);
END_TYPE;

ENTITY EffectivityAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedEffectivity : Effectivity;
  assignedTo : SET[1:?] OF EffectivityAssignmentSelect;
  effectivityIndication : BOOLEAN;
END_ENTITY;

TYPE EffectivityAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  ActivityRelationship,
  AddressAssignment,
  AlternativeSolution,
  AlternativeSolutionRelationship,
  ApprovalAssignment,
  ApprovalRelationship,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  AssignmentObjectRelationship,
  Breakdown,
  BreakdownElement,
  BreakdownElementRelationship,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownRelationship,
  BreakdownVersion,
  BreakdownVersionAssignment,
  BreakdownVersionRelationship,
  CertificationAssignment,
  ClassificationRelationship,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  ConditionalConfiguration,
  ConditionAssignment,
  ConditionRelationship,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  Descriptor,
  DescriptorRelationship,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  EffectivityAssignment,
  EffectivityRelationship,
  EventAssignment,
  EventRelationship,
  ExternalClassSystem,
  File,
  FileRelationship,
  FrozenAssignment,
  GeometricRepresentation,
  IdentifierRelationship,
  Identifier,
  IdentifierString,
  IdentifierSet,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartRelationship,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  InformationUsageRightRelationship,
  InZone,
  LinkMotionDecompositionRelationship,
  LinkMotionRelationship,
  MatedPartRelationship,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  OrganizationOrPersonInOrganizationAssignment,
  OrganizationRelationship,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartRelationship,
  PartToIndividualPartAssociation,
  PartVersion,
  PartVersionRelationship,
  PartVersionToIndividualPartVersionAssociation,
  PartView,
  PartViewRelationship,
  PartViewToIndividualPartViewAssociation,
  PersonInOrganization,
  PersonInOrganizationRelationship,
  ProcessOperationDefinition,
  ProcessOperationDefinitionRelationship,
  ProcessOperationOccurrence,
  ProcessOperationOccurrenceRelationship,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProcessPlanRelationship,
  ProductClass,
  ProductClassRelationship,
  ProductConfiguration,
  ProductConfigurationRelationship,
  ProductDesignAssociation,
  ProjectAssignment,
  ProjectRelationship,
  PropertyDefinitionAssignment,
  PropertyDefinitionAssignmentRelationship,
  PropertyDefinitionRelationship,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueAssignmentRelationship,
  PropertyValueRelationship,
  ProxyRelationship,
  ProxySelect,
  Requirement,
  RequirementAssignment,
  RequirementRelationship,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassification,
  SecurityClassificationAssignment,
  ShapeElementRelationship,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationConditionAssignment,
  Condition,
  SpecificationInclusion,
  SpecificationInclusionAssignment,
  StyledModel,
  SuppliedObjectRelationship,
  TimeIntervalAssignment,
  TimeIntervalRelationship,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkOrderAssignment,
  WorkOrderRelationship,
  WorkRequestAssignment,
  WorkRequestRelationship
);
END_TYPE;

ENTITY EffectivityRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Effectivity;
  related : Effectivity;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DataValidityEffectivity
 SUBTYPE OF(Effectivity);
 WHERE
  wr1: EXISTS(SELF\Effectivity.startDefinition) OR EXISTS(SELF\Effectivity.endDefinition);
END_ENTITY;

ENTITY LotEffectivity
 SUBTYPE OF(Effectivity);
  lotSize : ValueWithUnit;
END_ENTITY;

ENTITY SerialEffectivity
 SUBTYPE OF(Effectivity);
  endNumber : OPTIONAL IdentifierSelect;
  startNumber : IdentifierSelect;
END_ENTITY;

ENTITY TimeIntervalEffectivity
 SUBTYPE OF(Effectivity);
  effectivityPeriod : Duration;
 WHERE
  wr1: EXISTS(SELF\Effectivity.startDefinition) OR EXISTS(SELF\Effectivity.endDefinition);
END_ENTITY;


(*:C1
 ------------------------------------------------------------
  Property
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE PropertyAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  ActivityRelationship,
  Address,
  AddressAssignment,
  AlternativeSolution,
  Approval,
  ApprovalAssignment,
  BreakdownElementRealization,
  BreakdownElementRelationship,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownRelationship,
  BreakdownVersion,
  BreakdownVersionAssignment,
  BreakdownVersionRelationship,
  CertificationAssignment,
  Condition,
  ConditionAssignment,
  ConditionRelationship,
  Contract,
  ContractAssignment,
  ContractRelationship,
  DateAndPersonAssignment,
  DateTimeAssignment,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentRelationship,
  DocumentVersionRelationship,
  EffectivityAssignment,
  EventAssignment,
  File,
  FileRelationship,
  FrozenAssignment,
  IndividualPartRelationship,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  InZone,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Occurrence,
  OccurrenceRelationship,
  OrganizationOrPersonInOrganizationAssignment,
  OrganizationRelationship,
  Part,
  PartRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductConcept,
  ProductConfiguration,
  ProductConfigurationRelationship,
  Project,
  ProjectAssignment,
  ProjectRelationship,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  PropertyValueAssignment,
  PropertyValueRelationship,
  RequirementAssignment,
  RequirementRelationship,
  RequirementSource,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassificationAssignment,
  ShapeElement,
  ShapeElementRelationship,
  Specification,
  SpecificationAssignment,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  TimeIntervalAssignment,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment,
  WorkRequestRelationship
);
END_TYPE;

TYPE PropertyDefinitionSelect = SELECT (
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString
);
END_TYPE;

TYPE PropertyDefinitionString = STRING;
END_TYPE;

TYPE PropertyValueSelect = SELECT (
  CartesianPoint,
  NumericalValue
);
END_TYPE;

ENTITY ExternalPropertyDefinition;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
  sameAs : SET[1:?] OF ProxySelect;
  definition : ProxyItemSelect;
 UNIQUE
  UR1: sameAs;
END_ENTITY;

TYPE UnitSelect = SELECT (
  ExternalUnit,
  Unit
);
END_TYPE;

ENTITY PropertyDefinition;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  propertyType : ClassSelect;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
END_ENTITY;

ENTITY PropertyDefinitionAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedPropertyDefinition : PropertyDefinitionSelect;
  assignedTo : PropertyAssignmentSelect;
  allowedUnits : OPTIONAL SET[1:?] OF UnitSelect;
 UNIQUE
  UR1: assignedTo, assignedPropertyDefinition;
END_ENTITY;

ENTITY PropertyDefinitionAssignmentRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyDefinitionAssignment;
  related : PropertyDefinitionAssignment;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyDefinitionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyDefinitionSelect;
  related : PropertyDefinitionSelect;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyValue
 ABSTRACT
 SUPERTYPE OF(ONEOF(StringValue, ValueList, ValueSet, ValueWithUnit));
  name : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definition : PropertyDefinitionSelect;
  determinationMethod : OPTIONAL ClassSelect;
  qualifications : OPTIONAL SET[1:?] OF MeasureQualification;
 WHERE
  encapsulated: SIZEOF(USEDIN(SELF,'')-(USEDIN(SELF, SCHEMA_NAME + 'PROPERTYVALUERELATIONSHIP.RELATING')+USEDIN(SELF, SCHEMA_NAME + 'PROPERTYVALUERELATIONSHIP.RELATED')))=1;
END_ENTITY;

ENTITY PropertyValueAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedPropertyValues : SET[1:?] OF PropertyValue;
  assignedTo : PropertyAssignmentSelect;
  valueAssignmentContext : OPTIONAL PropertyDefinitionAssignment;
END_ENTITY;

ENTITY PropertyValueAssignmentRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyValueAssignment;
  related : PropertyValueAssignment;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY PropertyValueRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PropertyValue;
  related : PropertyValue;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ValueLimit
 SUBTYPE OF(NumericalValue);
  qualifier : TypeQualifierSelect;
END_ENTITY;

TYPE TypeQualifierSelect = SELECT (
  ExternalTypeQualifier,
  PreDefinedTypeQualifier
);
END_TYPE;

ENTITY ValueList
 SUBTYPE OF(PropertyValue);
  values : LIST[1:?] OF PropertyValue;
END_ENTITY;

ENTITY ValueRange
 SUBTYPE OF(ValueWithUnit);
  lowerLimit : REAL;
  upperLimit : REAL;
END_ENTITY;

ENTITY ValueSet
 SUBTYPE OF(PropertyValue);
  values : SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY StringValue
 SUBTYPE OF(PropertyValue);
  valueComponent : MultiLingualStringSelect;
END_ENTITY;

ENTITY ValueWithTolerances
 SUBTYPE OF(ValueWithUnit);
  lowerLimit : REAL;
  tolerancedValue : REAL;
  upperLimit : REAL;
END_ENTITY;

ENTITY ValueWithUnit
 ABSTRACT
 SUPERTYPE OF(ONEOF(NumericalValue, ValueRange, ValueWithTolerances))
 SUBTYPE OF(PropertyValue);
  significantDigits : OPTIONAL INTEGER;
  unit : UnitSelect;
END_ENTITY;

ENTITY NumericalValue
 SUPERTYPE OF(ONEOF(ValueLimit))
 SUBTYPE OF(ValueWithUnit);
  valueComponent : REAL;
  valueContext : OPTIONAL NumericalContext;
END_ENTITY;

ENTITY NumericalContext;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  accuracy : REAL;
  significantDigits : OPTIONAL INTEGER;
END_ENTITY;

-- Shape Dependent Properties / Validation Properties

ENTITY ShapeDependentProperty
 ABSTRACT
 SUPERTYPE OF(ONEOF(CentreOfMass, GeneralShapeDependentProperty, MomentsOfInertia));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedTo : ShapedElementSelect;
  definedIn : OPTIONAL GeometricCoordinateSpace;
  valueDetermination : OPTIONAL ClassSelect;
END_ENTITY;

TYPE ShapedElementSelect = SELECT (
  PartInformationSelect,
  ShapeElement
);
END_TYPE;

ENTITY CentreOfMass
 SUBTYPE OF(ShapeDependentProperty);
  centrePoint : CartesianPoint;
  SELF\ShapeDependentProperty.definedIn : GeometricCoordinateSpace;
END_ENTITY;

ENTITY GeneralShapeDependentProperty
 SUBTYPE OF(ShapeDependentProperty);
  propertyType : PropertyDefinitionSelect;
  propertyValue : PropertyValueSelect;
  unit : OPTIONAL Unit;
END_ENTITY;

ENTITY MomentsOfInertia
 SUBTYPE OF(ShapeDependentProperty);
  SELF\ShapeDependentProperty.definedIn : GeometricCoordinateSpace;
  inertiaValue : ARRAY[1:3] OF ARRAY[1:3] OF NumericalValue;
  referenceAxisPlacement : AxisPlacement;
END_ENTITY;

-- Qualifieres

ENTITY UncertaintyQualifier
 SUPERTYPE OF(ONEOF(QualitativeUncertainty, StandardUncertainty));
  description : OPTIONAL DescriptorSelect;
  measureName : MultiLingualStringSelect;
  sameAs : OPTIONAL ProxySelect;
END_ENTITY;

ENTITY QualitativeUncertainty
 SUBTYPE OF(UncertaintyQualifier);
  uncertaintyValue : MultiLingualStringSelect;
END_ENTITY;

ENTITY StandardUncertainty
 SUPERTYPE OF(ONEOF(ExpandedUncertainty))
 SUBTYPE OF(UncertaintyQualifier);
  uncertaintyValue : REAL;
END_ENTITY;

ENTITY ExpandedUncertainty
 SUBTYPE OF(StandardUncertainty);
  coverageFactor : REAL;
END_ENTITY;

ENTITY MeasureQualification;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  qualifiers : SET[1:?] OF ValueQualifierSelect;
 WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

TYPE ValueQualifierSelect = SELECT (
  PrecisionQualifier,
  TypeQualifierSelect,
  UncertaintyQualifier
);
END_TYPE;

ENTITY ExternalTypeQualifier;
  sameAs : OPTIONAL ProxySelect;
END_ENTITY;

ENTITY PrecisionQualifier;
  sameAs : OPTIONAL ProxySelect;
  significantDigits : INTEGER;
END_ENTITY;

ENTITY PreDefinedTypeQualifier;
  name : ClassSelect;
END_ENTITY;


-- Model Properties

ENTITY ModelProperty;
  definition : PropertyDefinitionSelect;
  specifiedValue : ModelPropertyValueSelect;
END_ENTITY;

TYPE ModelPropertyValueSelect = SELECT (
  GeometricModel,
  StyledModel
);
END_TYPE;

ENTITY ModelPropertyAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedProperty : ModelProperty;
  assignedTo : SET[1:?] OF PropertyAssignmentSelect;
  validityContext : OPTIONAL ValidityContextSelect;
END_ENTITY;

TYPE ValidityContextSelect = SELECT (
  Organization,
  ProductClass,
  ProductConfiguration
);
END_TYPE;

-- Units

ENTITY Unit;
  name : ClassSelect;
  kind : OPTIONAL ClassSelect;
  prefix : OPTIONAL ClassSelect;
  quantity : OPTIONAL ClassSelect;
END_ENTITY;

ENTITY ExternalUnit;
  definition : ProxyItemSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : SET[1:?] OF ProxySelect;
 UNIQUE
  UR1: sameAs;
END_ENTITY;


(*:C2
 ------------------------------------------------------------
  Material
 ------------------------------------------------------------
*)

-- not harmonized with PLCS yet

ENTITY MaterialIdentification;
  id : IdentifierSelect;
  assignedTo : SET[1:?] OF MaterialIdentificationAssignmentSelect;
END_ENTITY;

TYPE MaterialIdentificationAssignmentSelect = SELECT (
  BreakdownElementView,
  AlternativeSolution,
  PartView,
  Hardcopy,
  ViewOccurrenceRelationship,
  PartViewRelationship,
  Occurrence,
  IndividualPartView,
  ProductConcept,
  ProductConfiguration,
  ShapeElement,
  ShapeElementRelationship,
  RequirementView
);
END_TYPE;

ENTITY MaterialPropertyAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedProperty : MaterialPropertyValue;
  assignedTo : MaterialIdentification;
  definitional : OPTIONAL BOOLEAN;
END_ENTITY;

ENTITY MaterialPropertyDefinition
 SUBTYPE OF(PropertyDefinition);
  name : DescriptorSelect;
END_ENTITY;

ENTITY MaterialPropertyValue;
  definition : MaterialPropertyDefinition;
  environmentCondition : DataEnvironment;
  materialValue : PropertyValue;
END_ENTITY;

ENTITY DataEnvironment;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  characterization : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;


(*:C3
 ------------------------------------------------------------
  Shape Association and Structure
 ------------------------------------------------------------
*)

-- not harmonized with PLCS yet

TYPE PartInformationSelect = SELECT (
  BreakdownElementView,
  IndividualPartView,
  PartView,
  Occurrence,
  AssemblyViewRelationship
);
END_TYPE;

ENTITY ShapeElement
 SUPERTYPE OF(ONEOF(CoatingLayer));
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  representedGeometry : OPTIONAL RepresentationItem;
  elementOf : PartInformationSelect;
END_ENTITY;

ENTITY ShapeElementRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ShapeElement;
  related : ShapeElement;
  representedGeometry : OPTIONAL RepresentationItem;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


(*:K1
 ------------------------------------------------------------
  Kinematic Structure and Link
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

TYPE ActuatedDirectionEnum = ENUMERATION OF (
  bidirectional,
  positive_only,
  negative_only,
  not_actuated
);
END_TYPE; 

TYPE ExternalCurveOrSurfaceSelect = SELECT (
  Curve,
  Surface
);
END_TYPE;	

TYPE ExternalTrimmedCurveOrSurfaceSelect = SELECT (
  TrimmedCurve,
  RectangularTrimmedSurface
);
END_TYPE;

TYPE HighOrderKinematicPairTypeEnum = ENUMERATION OF (
  linear_flexible_and_planar_curve_pair,
  point_on_surface_pair,
  point_on_planar_curve_pair,
  planar_curve_pair,
  rolling_curve_pair,
  sliding_curve_pair,
  rolling_surface_pair,
  sliding_surface_pair
);
END_TYPE;

TYPE InterpolationTypeEnum = ENUMERATION OF (
  undefined_interpolation_type,
  discontinuous_interpolation_type,
  synchronous_interpolation_type,
  linear_interpolation_type
);
END_TYPE; 

TYPE LowOrderKinematicPairTypeEnum = ENUMERATION OF (
  cylindrical_pair,
  fully_constrained_pair,
  planar_pair,
  prismatic_pair,
  revolute_pair,
  spherical_pair,
  spherical_pair_with_pin,
  unconstrained_pair,
  universal_pair
);
END_TYPE;

TYPE LowOrderKinematicPairWithMotionCouplingTypeEnum = ENUMERATION OF (
	gear_pair,
	linear_flexible_and_pinion_pair,
	rack_and_pinion_pair,
	screw_pair
);
END_TYPE;

TYPE MotionModelSelect = SELECT (
  LinkMotionAlongPath,
  InterpolatedConfigurationModel);
END_TYPE;	

TYPE ParameterValue = REAL;
END_TYPE; 

TYPE PlaneAngleMeasure = REAL;
END_TYPE; 

TYPE RotationAboutAxes = LIST[1:3] OF PlaneAngleMeasure;
END_TYPE; 

TYPE SimpleOrSpatialRotationSelect = SELECT (
  RotationAboutAxes,
  RotationAboutDirection
); 
END_TYPE;

TYPE TranslationAlongAxes = LIST[1:3] OF LengthMeasure;
END_TYPE; 

ENTITY ActuatedPair;
  tx : OPTIONAL ActuatedDirectionEnum;
  ty : OPTIONAL ActuatedDirectionEnum;
  tz : OPTIONAL ActuatedDirectionEnum;
  rx : OPTIONAL ActuatedDirectionEnum;
  ry : OPTIONAL ActuatedDirectionEnum;
  rz : OPTIONAL ActuatedDirectionEnum;
END_ENTITY;

ENTITY RectangularTrimmedSurface
 SUBTYPE OF (Surface);
END_ENTITY;

ENTITY TrimmedCurve
 SUBTYPE OF (Curve);
END_ENTITY;	

ENTITY HighOrderKinematicPair
 SUBTYPE OF (KinematicPair);
  kind : HighOrderKinematicPairTypeEnum;
  model1 : ExternalGeometricModel; 
  model2 : OPTIONAL ExternalGeometricModel; 
  curveOrSurface1 : ExternalCurveOrSurfaceSelect;
  curveOrSurface2 : OPTIONAL ExternalCurveOrSurfaceSelect;
  orientation : OPTIONAL BOOLEAN;
  range1 : OPTIONAL ExternalTrimmedCurveOrSurfaceSelect;
  range2 : OPTIONAL ExternalTrimmedCurveOrSurfaceSelect;
  lowerLimitYaw : OPTIONAL PlaneAngleMeasure;
  upperLimitYaw : OPTIONAL PlaneAngleMeasure;
  lowerLimitPitch : OPTIONAL PlaneAngleMeasure;
  upperLimitPitch : OPTIONAL PlaneAngleMeasure;
  lowerLimitRoll : OPTIONAL PlaneAngleMeasure;
  upperLimitRoll : OPTIONAL PlaneAngleMeasure;
END_ENTITY;

ENTITY InterpolatedConfigurationModel
 SUBTYPE OF (GeometricRepresentation);
  parameterUnit : Unit;
  SELF\GeometricRepresentation.items : SET [1:?] OF InterpolatedConfigurationSequence;
END_ENTITY;

ENTITY InterpolatedConfigurationSegment;
  state : MechanismState;
  tParameter : ParameterValue;
  interpolation : InterpolationTypeEnum;
END_ENTITY;

ENTITY InterpolatedConfigurationSequence
 SUBTYPE OF (RepresentationItem);
  segments : LIST[2:?] OF InterpolatedConfigurationSegment;
END_ENTITY;

ENTITY KinematicLink
 SUBTYPE OF (GeometricRepresentation);
  ofModel : OPTIONAL ExternalGeometricModel;
  SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacement; -- == pairFrames
END_ENTITY;

ENTITY KinematicLinkToOccurrenceAssociation;
  associatedLink : KinematicLink;
  associatedTo : Occurrence;	
END_ENTITY;

ENTITY KinematicMechanismAssociation;
  associatedMechanism : Mechanism;
  associatedTo : AssemblyDefinition;
  baseLink : KinematicLink;
 UNIQUE
  ur1 : associatedTo;  
END_ENTITY;

ENTITY KinematicPair
 ABSTRACT
 SUPERTYPE OF(ONEOF(LowOrderKinematicPair, LowOrderKinematicPairWithMotionCoupling, HighOrderKinematicPair))
 SUBTYPE OF (RepresentationItem);
  link1 : KinematicLink;
  link2 : KinematicLink;
  pairFrame1 : AxisPlacement;
  pairFrame2 : AxisPlacement;
  actuation : OPTIONAL ActuatedPair;
END_ENTITY;

ENTITY KinematicPairValue
 SUBTYPE OF (RepresentationItem);
  appliesToPair : KinematicPair;
  actualTranslation : OPTIONAL TranslationAlongAxes;
  actualRotation : OPTIONAL SimpleOrSpatialRotationSelect;
  actualPointOnCurve1 : OPTIONAL PointOnCurve;
  actualPointOnCurve2 : OPTIONAL PointOnCurve;
  actualPointOnSurface1 : OPTIONAL PointOnSurface;
  actualPointOnSurface2 : OPTIONAL PointOnSurface;
END_ENTITY;

ENTITY LowOrderKinematicPair
 SUBTYPE OF (KinematicPair);
  kind : LowOrderKinematicPairTypeEnum;
  lowerLimitActualTranslationX : OPTIONAL LengthMeasure;
  upperLimitActualTranslationX : OPTIONAL LengthMeasure;
  lowerLimitActualTranslationY : OPTIONAL LengthMeasure;
  upperLimitActualTranslationY : OPTIONAL LengthMeasure;
  lowerLimitActualTranslationZ : OPTIONAL LengthMeasure;
  upperLimitActualTranslationZ : OPTIONAL LengthMeasure;
  lowerLimitActualRotationX : OPTIONAL PlaneAngleMeasure;
  upperLimitActualRotationX : OPTIONAL PlaneAngleMeasure;
  lowerLimitActualRotationY : OPTIONAL PlaneAngleMeasure;
  upperLimitActualRotationY : OPTIONAL PlaneAngleMeasure;
  lowerLimitActualRotationZ : OPTIONAL PlaneAngleMeasure;
  upperLimitActualRotationZ : OPTIONAL PlaneAngleMeasure;
END_ENTITY;

ENTITY LowOrderKinematicPairWithMotionCoupling
 SUBTYPE OF (KinematicPair);
  kind : LowOrderKinematicPairWithMotionCouplingTypeEnum;
  pitch : OPTIONAL LengthMeasure;
  radius1 : OPTIONAL LengthMeasure;
  radius2 : OPTIONAL LengthMeasure;
  lowerLimitRackDisplacement : OPTIONAL LengthMeasure;
  upperLimitRackDisplacement : OPTIONAL LengthMeasure;
  lowerLimitActualRotation : OPTIONAL PlaneAngleMeasure;
  upperLimitActualRotation : OPTIONAL PlaneAngleMeasure;
  bevel : OPTIONAL PlaneAngleMeasure;
  helicalAngle : OPTIONAL PlaneAngleMeasure;
  gearRatio : OPTIONAL REAL;
END_ENTITY;

ENTITY Mechanism
 SUBTYPE OF (GeometricRepresentation);
  SELF\GeometricRepresentation.items : SET[1:?] OF KinematicPair;
END_ENTITY;

ENTITY MechanismState
 SUBTYPE OF (GeometricRepresentation);
  representedMechanism : Mechanism;
  SELF\GeometricRepresentation.items : SET[1:?] OF KinematicPairValue;
END_ENTITY;

ENTITY MotionModelAssociation; 
  associatedModel : MotionModelSelect;
  associatedTo : AssemblyDefinition;
END_ENTITY;

ENTITY RotationAboutDirection
 SUBTYPE OF (DetailedGeometricModelItem);
  directionOfAxis : Direction;
  rotationAngle : PlaneAngleMeasure;
END_ENTITY;

ENTITY ToolAttachmentPointFrame
 SUBTYPE OF (AxisPlacement);
END_ENTITY;	
	
ENTITY ToolCentrePointFrame
 SUBTYPE OF (AxisPlacement);
END_ENTITY;	


(*:K2
 ------------------------------------------------------------
  Kinematic Motion
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY KinematicPathDefinedByNodes
 SUBTYPE OF (RepresentationItem);
  placementStart : AxisPlacement;
  segments : LIST[1:?] OF PathSegment;
  tStart : REAL;
END_ENTITY;

ENTITY LinkMotionAlongPath
 SUBTYPE OF (GeometricRepresentation);
  SELF\GeometricRepresentation.items : SET[1:?] OF KinematicPathDefinedByNodes;
  timeUnit : OPTIONAL Unit;
END_ENTITY;

ENTITY LinkMotionDecompositionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : LinkMotionAlongPath;
  related : LinkMotionAlongPath;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY LinkMotionRelationship;
-- SUBTYPE OF (GeometricRepresentation);
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : LinkMotionAlongPath;
  related : ExternalGeometricModel;
  tranformationOperator : LinkMotionTransformation;
END_ENTITY;

ENTITY LinkMotionTransformation;
  transformItem1 : AxisPlacement;
  transformItem2 : KinematicPathDefinedByNodes;
END_ENTITY;

ENTITY PathSegment
 ABSTRACT
 SUPERTYPE OF(ONEOF(CircularPath, LinearPath, PointToPointPath));
  placementEnd : AxisPlacement;
  tEnd : REAL;
  transition : TransitionCodeEnum;
END_ENTITY;

TYPE TransitionCodeEnum = ENUMERATION OF(
  cont_same_gradient,
  cont_same_gradient_same_curvature,
  continuous,
  discontinuous
);
END_TYPE;

ENTITY CircularPath
 SUBTYPE OF(PathSegment);
  viaPoint : CartesianPoint;
END_ENTITY;

ENTITY LinearPath
 SUBTYPE OF(PathSegment);
END_ENTITY;

ENTITY PointToPointPath
 SUBTYPE OF(PathSegment);
END_ENTITY;


(*:PP1
 ------------------------------------------------------------
  Process Plan
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

TYPE ProcessOperationInputOrOutputSelect = SELECT (
  AssemblyOccurrenceRelationship,
  AssemblyViewRelationship,
  Occurrence,
  PartVersion
);
END_TYPE;

TYPE ProcessOperationResourceAssignmentSelect = SELECT (
  BreakdownElement,
  IndividualPartView,
  Occurrence,
  PartVersion,
  RequirementView
);
END_TYPE;

ENTITY ProcessOperationDefinition;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  versionId : OPTIONAL IdentifierSelect;
  processType : ClassSelect;
END_ENTITY;

ENTITY ProcessOperationDefinitionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessOperationDefinition;
  related : ProcessOperationDefinition;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProcessOperationInputOrOutput;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  concernedShapes : OPTIONAL SET[1:?] OF ShapeElement;
  element : ProcessOperationInputOrOutputSelect;
  operation : ProcessOperationOccurrence;
  placement : OPTIONAL GeometricRepresentationRelationshipWithPlacementTransformation;
END_ENTITY;

ENTITY ProcessOperationOccurrence;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definedIn : OPTIONAL GeometricCoordinateSpace;
  definition : ProcessOperationDefinition;
  plan : ProcessPlan;
END_ENTITY;

ENTITY ProcessOperationOccurrenceRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessOperationOccurrence;
  related : ProcessOperationOccurrence;
  cycleTime : OPTIONAL Duration;
  waitingTime : OPTIONAL PropertyValue;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProcessOperationResourceAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedResource : ProcessOperationResourceAssignmentSelect;
  assignedTo : ProcessOperationOccurrence;
  placement : OPTIONAL GeometricRepresentationRelationshipWithPlacementTransformation;
  reason : OPTIONAL MultiLingualStringSelect;
  referenceTool : BOOLEAN;
END_ENTITY;

ENTITY ProcessPlan;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  versionId : OPTIONAL IdentifierSelect;
  producedOutputs : OPTIONAL SET[1:?] OF PartVersion;
END_ENTITY;

ENTITY ProcessPlanRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ProcessPlan;
  related : ProcessPlan;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


(*:PP2
 ------------------------------------------------------------
  Mating
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY AssemblyJoint;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assemblyShape : AssemblyDefinition; -- was ItemShape;
  shapeElement1 : ShapeElement;
  shapeElement2 : ShapeElement;
END_ENTITY;

ENTITY MakeFromRelationship
 SUBTYPE OF(PartViewRelationship);
  priority : OPTIONAL INTEGER;
  quantity : OPTIONAL ValueWithUnit;
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'make from';
END_ENTITY;

ENTITY MatedPartAssociation
 SUBTYPE OF(NextAssemblyOccurrenceUsage);
  SELF\AssemblyOccurrenceRelationship.relating : MatingDefinition;
END_ENTITY;

ENTITY MatedPartRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  matingType : MatingTypeEnum;
  relating : MatedPartAssociation;
  related : MatedPartAssociation;
  matedShapes : OPTIONAL SET[1:?] OF AssemblyJoint;
  matingMaterials : OPTIONAL SET[1:?] OF QuantifiedOccurrence;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

TYPE MatingTypeEnum = ENUMERATION OF(
  bolted_joint,
  brazing,
  clasping,
  clinching,
  clipping,
  doweling,
  flanging,
  foam_injection,
  gluing,
  laser_welding,
  press_fit,
  riveting,
  sewing,
  spot_welding,
  stapling,
  welding,
  soldering,
  friction_welding
);
END_TYPE;

ENTITY MatingDefinition
 SUBTYPE OF(AssemblyDefinition);
  matingType : OPTIONAL ClassSelect;
 INVERSE
  matedParts : SET[2:?] OF MatedPartAssociation FOR relating;
END_ENTITY;

ENTITY ProcessStateRelationship
 SUBTYPE OF(PartViewRelationship);
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'process state';
END_ENTITY;

ENTITY SameTimeMachiningRelationship
 SUBTYPE OF(OccurrenceRelationship);
  placement : OPTIONAL TransformationSelect;
 DERIVE
  SELF\OccurrenceRelationship.relationType : ClassString := 'same time machining';
 WHERE
  WR1: NOT ('GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(placement)) OR (placement.definitional = FALSE);
END_ENTITY;

ENTITY ToolPartRelationship
 SUBTYPE OF(PartViewRelationship);
  placement : OPTIONAL TransformationSelect;
 DERIVE
  SELF\PartViewRelationship.relationType : ClassString := 'tool part';
 WHERE
  WR1: NOT ('GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(placement)) OR (placement.definitional = FALSE);
END_ENTITY;


(*:RR1
 ------------------------------------------------------------
  Requirements
 ------------------------------------------------------------
*)

--  harmonized with PLCS

ENTITY Requirement;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  versions : OPTIONAL SET[1:?] OF RequirementVersion;
END_ENTITY;

ENTITY RequirementRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Requirement;
  related : Requirement;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


ENTITY RequirementAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedRequirement : RequirementView;
  assignedTo : RequirementAssignmentSelect;
END_ENTITY;

TYPE RequirementAssignmentSelect = SELECT (
  ActivityMethod,
  ActivityMethodAssignment,
  AlternatePartRelationship,
  AlternativeSolution,
  AssemblyOccurrenceRelationship,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationship,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementRelationship,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Document,
  DocumentDefinition,
  DocumentVersion,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  Part,
  PartVersion,
  PartView,
  ProductConfiguration,
  Project,
  Requirement,
  RequirementVersion,
  RequirementView,
  WorkRequest
);
END_TYPE;

ENTITY RequirementCollectionRelationship
 SUBTYPE OF(RequirementViewRelationship);
 DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'collection';
END_ENTITY;

ENTITY RequirementDecompositionRelationship
 SUBTYPE OF(RequirementCollectionRelationship);
 DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'decomposition';
END_ENTITY;

ENTITY RequirementSatisfactionAssertion;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assertedBy : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  relatedAssignment : OPTIONAL RequirementAssignment;
  satisfiedBy : RequirementAssignmentSelect;
  satisfiedRequirement : RequirementView;
END_ENTITY;

ENTITY RequirementSequenceRelationship
 SUBTYPE OF(RequirementVersionRelationship);
 DERIVE
  SELF\RequirementVersionRelationship.relationType : ClassString := 'sequence';
END_ENTITY;

ENTITY RequirementSource;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  source : RequirementSourceSelect;
  sourcedRequirement : RequirementView;
END_ENTITY;

TYPE RequirementSourceSelect = SELECT (
  Activity ,
  ActivityMethod,
  ActivityMethodAssignment,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Contract ,
  Document,
  DocumentDefinition,
  DocumentVersion,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  Organization ,
  Part,
  PartVersion,
  PartView,
  PersonInOrganization ,
  Project,
  Requirement,
  RequirementVersion,
  RequirementView
);
END_TYPE;

ENTITY RequirementTracingRelationship
 SUBTYPE OF(RequirementViewRelationship);
 DERIVE
  SELF\RequirementViewRelationship.relationType : ClassString := 'tracing';
END_ENTITY;

ENTITY RequirementVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  views : OPTIONAL SET[1:?] OF RequirementView;
 INVERSE
  versionOf : Requirement FOR versions;
END_ENTITY;

ENTITY RequirementVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : RequirementVersion;
  related : RequirementVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY RequirementView;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  additionalContexts : OPTIONAL SET[1:?] OF ViewContext;
  definitionalRepresentations : SET[1:?] OF PropertyValue;
  initialContext : ViewContext;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 INVERSE
  viewOf : RequirementVersion FOR views;
END_ENTITY;

ENTITY RequirementViewRelationship
 SUPERTYPE OF(ONEOF(RequirementCollectionRelationship, RequirementTracingRelationship));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : RequirementView;
  related : RequirementView;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


(*:RR2
 ------------------------------------------------------------
  Rule Specification and Management
 ------------------------------------------------------------
*)

-- not part if DIS version of edition 1


(*:RR3
 ------------------------------------------------------------
  Planned and Evaluated Characteristics
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY PlannedCharacteristic;
  name : OPTIONAL DescriptorSelect;
  definedFor : RequirementAssignment;
  plannedCharacteristics : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

ENTITY EvaluatedCharacteristic;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  actualCharacteristics : SET[1:?] OF PropertyValue;
  evaluationResult : EvaluationResultEnum;
  evaluationStatus : EvaluationStatusEnum;
  plannedCharacteristics : SET[1:?] OF PlannedCharacteristic;
END_ENTITY;

TYPE EvaluationResultEnum = ENUMERATION OF(
  fail,
  pass,
  undefined
);
END_TYPE;

TYPE EvaluationStatusEnum = ENUMERATION OF(
  invalid,
  not_evaluatable,
  to_be_evaluated,
  valid
);
END_TYPE;

ENTITY MeasuredCharacteristic
 ABSTRACT
 SUPERTYPE OF(ONEOF(IndividualPartTestResult));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  measureActivity : OPTIONAL MeasureActivitySelect;
  measuredCharacteristics : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;

TYPE MeasureActivitySelect = SELECT (
  Activity,
  ProcessOperationOccurrence
);
END_TYPE;

ENTITY IndividualPartTestResult
 SUBTYPE OF(MeasuredCharacteristic);
  testedPart : IndividualPartView;
END_ENTITY;

(*
 ------------------------------------------------------------
  Geometry
 ------------------------------------------------------------
*)


(*:GMI1
 ------------------------------------------------------------
  Person, Organization and Address
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Address;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL CharacterString;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  country : OPTIONAL CharacterString;
  electronicMailAddress : OPTIONAL CharacterString;
  facsimileNumber : OPTIONAL CharacterString;
  internalLocation : OPTIONAL CharacterString;
  postalBox : OPTIONAL CharacterString;
  postalCode : OPTIONAL CharacterString;
  region : OPTIONAL CharacterString;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  street : OPTIONAL CharacterString;
  streetNumber : OPTIONAL CharacterString;
  telephoneNumber : OPTIONAL CharacterString;
  telexNumber : OPTIONAL CharacterString;
  town : OPTIONAL CharacterString;
  url : OPTIONAL CharacterString;
END_ENTITY;

ENTITY AddressAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedAddress : Address;
  assignedTo : OrganizationOrPersonInOrganizationSelect;
END_ENTITY;

ENTITY Organization;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  organizationTypes : OPTIONAL SET[1:?] OF ClassSelect;
END_ENTITY;

ENTITY OrganizationRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Organization;
  related : Organization;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY OrganizationOrPersonInOrganizationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedPersonOrOrganization : OrganizationOrPersonInOrganizationSelect;
  assignedTo : SET[1:?] OF DateTimePersonOrganizationElementSelect;
END_ENTITY;

ENTITY Person;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  lastName : STRING;
  firstName : OPTIONAL STRING;
  middleNames : OPTIONAL LIST[1:?] OF STRING;
  prefixTitles : OPTIONAL LIST[1:?] OF STRING;
  suffixTitles : OPTIONAL LIST[1:?] OF STRING;
 INVERSE
  associatedOrganizations : SET[1:?] OF PersonInOrganization FOR associatedPerson;
END_ENTITY;

ENTITY PersonInOrganization;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  personRole : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  associatedPerson : Person;
  associatedOrganization : Organization;
END_ENTITY;

ENTITY PersonInOrganizationRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : PersonInOrganization;
  related : PersonInOrganization;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY SuppliedObjectRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : SuppliedObjectSelect;
  related : SuppliedObjectSelect;
 WHERE
  WR1: TYPEOF(relating) = TYPEOF(related);
END_ENTITY;

TYPE SuppliedObjectSelect = SELECT (
  Activity,
  ActivityMethod,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  ClassAttribute,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  ConditionalConfiguration,
  Contract,
  Document,
  DocumentDefinition,
  DocumentVersion,
  Effectivity,
  Event,
  ExternalClassSystem,
  File,
  FormatProperty,
  GeometricRepresentation,
  IndividualPartTestResult,
  IndividualPartView,
  InformationRight,
  InformationUsageRight,
  ConfiguredAssemblyEffectivity,
  MaterialIdentification,
  Organization,
  Part,
  Occurrence,
  PartVersion,
  PartView,
  PersonInOrganization,
  ProcessOperationDefinition,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  Requirement,
  RequirementSatisfactionAssertion,
  RequirementVersion,
  RequirementView,
  SecurityClassification,
  Specification,
  SpecificationCategory,
  Condition,
  SpecificationInclusion,
  WorkOrder,
  WorkRequest
);
END_TYPE;

ENTITY AssignmentObjectRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : Classification;
  relating : AssignmentObjectSelect;
  related : AssignmentObjectSelect;
 WHERE
  WR1: TYPEOF(relating) = TYPEOF(related);
END_ENTITY;

TYPE AssignmentObjectSelect = SELECT (
  ActivityAssignment,
  ActivityMethodAssignment,
  AddressAssignment,
  ApprovalAssignment,
  BreakdownVersionAssignment,
  CertificationAssignment,
  ConditionAssignment,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  DocumentAssignment,
  EffectivityAssignment,
  EventAssignment,
  FrozenAssignment,
  InformationUsageRightAssignment,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  OrganizationOrPersonInOrganizationAssignment,
  ProcessOperationResourceAssignment,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyValueAssignment,
  RequirementAssignment,
  SecurityClassificationAssignment,
  SpecificationAssignment,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  TimeIntervalAssignment,
  WorkOrderAssignment,
  WorkRequestAssignment
);
END_TYPE;


(*:GMI2
 ------------------------------------------------------------
  Approval, Contract and Project
 ------------------------------------------------------------
*)

-- partially harmonized with PLCS (only Approval)

ENTITY Approval;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  status : ClassSelect;
  validDate : OPTIONAL DateTimeString;
  approvedBy : OPTIONAL SET[1:?] OF ApprovingPersonOrganization;
  approvalScope : OPTIONAL SET[1:?] OF ApprovalScopeSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

TYPE ApprovalScopeSelect = SELECT (
  Activity,  
  Contract, 
  Project,
  Organization, 
  PersonInOrganization,
  ProductClass,
  ProductConfiguration
);
END_TYPE;

ENTITY ApprovingPersonOrganization;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  approver : OrganizationOrPersonInOrganizationSelect;
  dateApproved : OPTIONAL DateTimeString;
INVERSE
  authorizedApproval : Approval FOR approvedBy;
END_ENTITY;

TYPE OrganizationOrPersonInOrganizationSelect = SELECT (
  Organization,
  PersonInOrganization
);
END_TYPE;

ENTITY ApprovalRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Approval;
  related : Approval;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ApprovalAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedApproval : Approval;
  assignedTo : SET[1:?] OF ApprovalAssignmentSelect;
END_ENTITY;

TYPE ApprovalAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  AddressAssignment,
  AlternatePartRelationship,
  AlternativeSolution,
  ApprovalAssignment,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownVersionAssignment,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionRelationship,
  Certification,
  CertificationAssignment,
  Classification,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  Condition,
  ConditionalConfiguration,
  ConditionAssignment,
  ConfiguredAssemblyEffectivity,
  Contract,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  Descriptor,
  DescriptorRelationship,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  Effectivity,
  EffectivityAssignment,
  EventAssignment,
  ExternalClassSystem,
  File,
  FrozenAssignment,
  GeometricRepresentation,
  Identifier,
  IdentifierRelationship,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRight,
  InformationUsageRightAssignment,
  InZone,
  MaterialIdentification,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  OrganizationOrPersonInOrganizationAssignment,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  PersonInOrganization,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  PartRelationship,
  Project,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueRelationship,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassification,
  SecurityClassificationAssignment,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusion,
  SpecificationInclusionAssignment,
  StyledModel,
  TimeIntervalAssignment,
  ViewContext,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment
);
END_TYPE;

-- certification

TYPE CertificationAssignmentSelect = SELECT (
  Activity,
  ActivityMethod,
  ActivityMethodAssignment,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionRelationship,
  Document,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartViewRelationship,
  Part,
  Occurrence,
  PartRelationship,
  PartVersion,
  PartVersionRelationship,
  PartViewRelationship,
  ProductConfiguration,
  Project,
  Requirement,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementViewRelationship,
  SupplierSolution
);
END_TYPE;

ENTITY Certification;
  id : OPTIONAL IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  certificationType : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY CertificationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedCertification : Certification;
  assignedTo : SET[1:?] OF CertificationAssignmentSelect;
END_ENTITY;

-- contract

TYPE ContractAssignmentSelect = SELECT (
  Activity,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownVersion,
  Classification,
  Descriptor,
  Document,
  DocumentVersion,
  ExchangeContextClassLibrary,
  Identifier,
  IndividualPart,
  IndividualPartVersion,
  InformationUsageRight,
  Organization,
  Part,
  PartVersion,
  PersonInOrganization,
  ProductConfiguration,
  Project,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementCollectionRelationship,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  WorkOrder,
  WorkRequest
);
END_TYPE;

ENTITY Contract;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  contractType : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 INVERSE
  releases : SET[0:?] OF OrganizationInContract FOR signedContracts;
END_ENTITY;

ENTITY ContractRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Contract;
  related : Contract;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ContractAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedContract : Contract;
  assignedTo : SET[1:?] OF ContractAssignmentSelect;
END_ENTITY;

ENTITY OrganizationInContract;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  contractedOrganization : Organization;
  organizationRole : ClassSelect;
  signedBy : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
  signedContracts : SET[1:?] OF Contract;
END_ENTITY;

-- project

ENTITY Project;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  actualEndDate : OPTIONAL DateTimeString;
  actualStartDate : OPTIONAL DateTimeString;
  plannedEndDate : OPTIONAL PeriodOrDateSelect;
  plannedStartDate : OPTIONAL EventOrDateSelect;
  responsibleOrganizations : OPTIONAL SET[1:?] OF Organization;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY ProjectRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Project;
  related : Project;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ProjectAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedProject : Project;
  assignedTo : SET[1:?] OF ProjectAssignmentSelect;
END_ENTITY;

TYPE ProjectAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  AlternativeSolution,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownVersion,
  Document,
  DocumentVersion,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  Occurrence,
  Part,
  PartVersion,
  ProductConcept,
  ProductConfiguration,
  PropertyValue,
  Requirement,
  RequirementVersion
);
END_TYPE;


(*:GMI3
 ------------------------------------------------------------
  Information Right
 ------------------------------------------------------------
*)

-- not harmonized with PLCS yet

ENTITY InformationRight
 SUPERTYPE OF(ONEOF(Copyright));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  owners : SET[1:?] OF OrganizationOrPersonInOrganizationSelect;
  restriction : OPTIONAL MultiLingualStringSelect;
END_ENTITY;

ENTITY InformationUsageRight;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  grantsRight : SET[1:?] OF InformationRight;
  owners : SET[1:?] OF OrganizationOrPersonInOrganizationSelect;
END_ENTITY;

ENTITY InformationUsageRightRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL SET[1:?] OF DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : InformationUsageRight;
  related : InformationUsageRight;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY InformationUsageRightAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedRight : InformationUsageRight;
  isAssignedTo : SET[1:?] OF InformationUsageRightAssignmentSelect;
END_ENTITY;

TYPE InformationUsageRightAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  AlternativeSolution,
  AlternativeSolutionRelationship,
  Approval,
  AssemblyOccurrenceRelationship,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationship,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  Certification,
  Classification,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  ConditionalConfiguration,
  ConfiguredAssemblyEffectivity,
  Contract,
  DeltaChange,
  Descriptor,
  DescriptorRelationship,
  DigitalFile,
  Document,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  ExternalClassSystem,
  ExternalItem,
  File,
  FileRelationship,
  GeometricRepresentation,
  IdentifierRelationship,
  Identifier,
  IdentifierString,
  IdentifierSet,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartView,
  InformationRight,
  InformationUsageRight,
  InformationUsageRightRelationship,
  MaterialIdentification,
  Organization,
  OrganizationRelationship,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  PersonInOrganizationRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementVersion,
  RequirementView,
  RetentionPeriod,
  SecurityClassification,
  SecurityClassificationAssignment,
  ShapeElement,
  ShapeElementRelationship,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationConditionAssignment,
  Condition,
  SpecificationInclusion,
  SpecificationInclusionAssignment,
  StyledModel,
  SuppliedObjectRelationship,
  SurfaceCondition,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkRequest
);
END_TYPE;

ENTITY Copyright
 SUBTYPE OF(InformationRight);
END_ENTITY;


(*:GMI4
 ------------------------------------------------------------
  Multi Linguism
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE Language = LIST[1:2] OF STRING; -- format: language code (according ISO 639-1 or 639-2) + an optional country code (ISO 3166-1)
END_TYPE;

TYPE CharacterString = STRING;
END_TYPE;

TYPE MultiLingualStringSelect = SELECT (
  CharacterString,
  LocalizedString,
  TranslatedStringSet
);
END_TYPE;

TYPE TranslatedStringSet = SET[1:?] OF LocalizedString;
END_TYPE;

ENTITY LocalizedString;
  language : OPTIONAL Language;
  text : CharacterString;
 WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

(*:GMI5
 ------------------------------------------------------------
  Classification
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE ClassSelect = SELECT (
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass
);
END_TYPE;

TYPE ClassString = STRING;
END_TYPE;

ENTITY Class;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  definedIn : OPTIONAL ExternalClassSystem;
 INVERSE
  classAttributes : SET[0:?] OF ClassAttribute FOR definedFor;
 UNIQUE
  UR1: id;
END_ENTITY;

ENTITY ClassAttribute;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  allowedValues : OPTIONAL SET[1:?] OF PropertyValue;
  attributeDefinition : PropertyDefinition;
  definedFor : Class;
END_ENTITY;

ENTITY Classification;
  role : OPTIONAL ClassString;
  class : ClassSelect;
END_ENTITY;

ENTITY ClassificationRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Classification;
  related : Classification;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ExternalClass;
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
 UNIQUE
  UR1: id, source;
END_ENTITY;

ENTITY ExternalClassSystem;
  id : SingleIdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  source : OPTIONAL ExternalSourceSelect;
 INVERSE
  allowedClasses : SET[1:?] OF Class FOR definedIn;
 UNIQUE
  UR1: id, source;
END_ENTITY;

TYPE ExternalSourceSelect = SELECT (
  DigitalFile,
  Document,
  IdentifierSelect
);
END_TYPE;

TYPE Uri = IdentifierString;
END_TYPE;

ENTITY ExternalOwlClass;
  class : Uri;
 UNIQUE
  UR1: class;
END_ENTITY;

ENTITY ExternalOwlObject;
  individual : Uri;
 UNIQUE
  UR1: individual;
END_ENTITY;

ENTITY ExchangeContextClassLibrary;
  id : Uri;
 UNIQUE
  UR1: id;
END_ENTITY;

-- Proxy

TYPE ProxyItemSelect = SELECT (
  ExternalItem,
  ExternalOwlObject,
  ProxyString
);
END_TYPE;

TYPE ProxySelect = SELECT (
  Proxy,
  ProxyItemSelect
);
END_TYPE;

TYPE ProxyString = STRING;
END_TYPE;

ENTITY Proxy;
  individual : ProxyItemSelect;
END_ENTITY;

ENTITY ProxyRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Proxy;
  related : Proxy;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY SetMembership;
  member : ProxyItemSelect;
  ofSet : ClassSelect;
END_ENTITY;

ENTITY SubsetMember;
  subset : ClassSelect;
  superset : ClassSelect;
END_ENTITY;

-- Security Classification

TYPE SecurityClassificationAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  AlternativeSolution,
  AssemblyOccurrenceRelationship,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationship,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementRelationship,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownVersion,
  Classification,
  ConditionalConfiguration,
  ConfiguredAssemblyEffectivity,
  Descriptor,
  DescriptorRelationship,
  DigitalFile,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentVersion,
  ExternalClassSystem,
  File,
  GeometricRepresentation,
  Hardcopy,
  Identifier,
  IdentifierRelationship,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartView,
  MaterialIdentification,
  Part,
  PartToIndividualPartAssociation,
  PartVersion,
  PartVersionToIndividualPartVersionAssociation,
  PartView,
  PartViewRelationship,
  PartViewToIndividualPartViewAssociation,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  PropertyDefinitionAssignment,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValueAssignment,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementCollectionRelationship,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  Specification,
  SpecificationCategory,
  StyledModel,
  WorkOrder,
  WorkRequest
);
END_TYPE;

ENTITY SecurityClassification;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  level : ClassSelect;
END_ENTITY;

ENTITY SecurityClassificationAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : OPTIONAL ClassSelect;
  assignedSecurityClassification : SecurityClassification;
  assignedTo : SET[1:?] OF SecurityClassificationAssignmentSelect;
END_ENTITY;

(*:GMI6
 ------------------------------------------------------------
  Identification
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE IdentifierSelect = SELECT (
  IdentifierSet,
  SingleIdentifierSelect
);
END_TYPE;

TYPE IdentifierSet = SET[2:?] OF Identifier;
END_TYPE;

TYPE IdentifierString = STRING;
END_TYPE;

TYPE SingleIdentifierSelect = SELECT (
  Identifier,
  IdentifierString
);
END_TYPE;

TYPE IdentificationContextSelect = SELECT (
  Identifier,
  Organization
);
END_TYPE;

ENTITY Identifier;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  id : IdentifierString;
  identificationContext : OPTIONAL IdentificationContextSelect;
 UNIQUE
  UR1: id, role, identificationContext;
 WHERE
  ContextlessForOrganizationOnly: NOT (NOT EXISTS(identificationContext) AND (SIZEOF(USEDIN(SELF, SCHEMA_NAME + 'ORGANIZATION.ID'))=0));
END_ENTITY;

ENTITY IdentifierRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Identifier;
  related : Identifier;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

-- Exchange context
(* 
 The Exchange context provides the default lagnguage and/or context used for 
 identifications and descriptions where the strings are used as opposed
 to the explcit entities, 
*)

ENTITY ExchangeContext;
  description : OPTIONAL DescriptorSelect;
  identificationContext : OPTIONAL IdentificationContextSelect;
  defaultLanguage : OPTIONAL Language;
  defaultUnit : OPTIONAL Unit;
 WHERE
  WR1: EXISTS(defaultLanguage) OR EXISTS (identificationContext);
END_ENTITY;


(*:GMI7
 ------------------------------------------------------------
  Name and Description
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE DescriptorSelect = SELECT (
  Descriptor,
  DescriptorSet,
  MultiLingualStringSelect
);
END_TYPE;

TYPE DescriptorSet = SET[2:?] OF Descriptor;
END_TYPE;

ENTITY Descriptor;
  id : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  descriptionContext : OPTIONAL SET[1:?] OF IdentificationContextSelect;
  text : MultiLingualStringSelect;
 WHERE
  encapsulated: SIZEOF(USEDIN(SELF,''))=1;
END_ENTITY;

ENTITY DescriptorRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Descriptor;
  related : Descriptor;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;




(*:GMI8
 ------------------------------------------------------------
  Date and Time
 ------------------------------------------------------------
*)

-- harmonized with PLCS

TYPE DateTimeString = STRING;
END_TYPE;

ENTITY DateAndPersonAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDateAndPerson : DateAndPersonOrganization;
  assignedTo : SET[1:?] OF DateTimePersonOrganizationElementSelect;
END_ENTITY;

TYPE DateTimePersonOrganizationElementSelect = SELECT (
  Event,
  GeneralOrganizationalDataSelect
);
END_TYPE;

TYPE GeneralOrganizationalDataSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  ActivityRelationship,
  AddressAssignment,
  AlternativeSolution,
  AlternativeSolutionRelationship,
  Approval,
  ApprovalAssignment,
  ApprovalRelationship,
  ApprovingPersonOrganization,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionAssignment,
  BreakdownVersionRelationship,
  Certification,
  CertificationAssignment,
  Classification,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  Condition,
  ConditionalConfiguration,
  ConditionAssignment,
  ConfiguredAssemblyEffectivity,
  Contract,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  Descriptor,
  DescriptorRelationship,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  Effectivity,
  EffectivityAssignment,
  EventAssignment,
  ExternalClassSystem,
  File,
  FrozenAssignment,
  GeometricRepresentation,
  IdentifierRelationship,
  Identifier,
  IdentifierString,
  IdentifierSet,
  IndividualAssemblyRelationship,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRight,
  InformationUsageRightAssignment,
  MaterialIdentification,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Organization,
  OrganizationOrPersonInOrganizationAssignment,
  OrganizationRelationship,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartRelationship,
  PartToIndividualPartAssociation,
  PartVersion,
  PartVersionRelationship,
  PartVersionToIndividualPartVersionAssociation,
  PartView,
  PartViewRelationship,
  PartViewToIndividualPartViewAssociation,
  Person,
  PersonInOrganization,
  PersonInOrganizationRelationship,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductConcept,
  ProductConfiguration,
  Project,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueRelationship,
  Proxy,
  RequirementAssignment,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassification,
  SecurityClassificationAssignment,
  SetMembership,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusion,
  SpecificationInclusionAssignment,
  StyledModel,
  SubsetMember,
  TimeIntervalAssignment,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment
);
END_TYPE;

ENTITY DateAndPersonOrganization;
  date : DateTimeString;
  personOrOrganization : OrganizationOrPersonInOrganizationSelect;
END_ENTITY;

ENTITY DateTimeAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDate : DateTimeString;
  assignedTo : SET[1:?] OF DateTimeAssignmentSelect;
END_ENTITY;

TYPE DateTimeAssignmentSelect = SELECT (
  Event,
  GeneralOrganizationalDataSelect
);
END_TYPE;

ENTITY Duration;
  time : STRING;
  unit : STRING;
END_ENTITY;

ENTITY Event;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  eventType : ClassSelect;
  actualStartDate : OPTIONAL DateTimeString;
  offset : OPTIONAL Duration;
  plannedStartDate : OPTIONAL DateTimeString;
END_ENTITY;

ENTITY EventAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedEvent : Event;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
END_ENTITY;

ENTITY EventRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Event;
  related : Event;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY RetentionPeriod;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
  earliestEnd : PeriodOrDateSelect;
  latestEnd : PeriodOrDateSelect;
  start : EventOrDateSelect;
END_ENTITY;

TYPE PeriodOrDateSelect = SELECT (
  DateTimeString,
  Duration,
  Event
);
END_TYPE;

TYPE EventOrDateSelect = SELECT (
  DateTimeString,
  Event
);
END_TYPE;

ENTITY TimeInterval
 SUPERTYPE OF (ONEOF (TimeIntervalWithId, TimeIntervalWithBounds));  
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY TimeIntervalRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : TimeInterval;
  related : TimeInterval;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY TimeIntervalWithId
 SUBTYPE OF (TimeInterval);
  SELF\TimeInterval.id : IdentifierSelect;
END_ENTITY;

ENTITY TimeIntervalWithBounds
 SUBTYPE OF (TimeInterval);
  primaryBound : OPTIONAL EventOrDateSelect;
  secondaryBound : OPTIONAL EventOrDateSelect;
  duration : OPTIONAL Duration;
WHERE
  WR1: NOT (EXISTS (secondaryBound) AND EXISTS (duration));
  WR2: EXISTS (primaryBound) OR EXISTS (secondaryBound);
END_ENTITY;

ENTITY TimeIntervalAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedTimeInterval : TimeInterval;
  assignedTo : SET[1:?] OF GeneralOrganizationalDataSelect;
END_ENTITY;


(*:AMW1
 ------------------------------------------------------------
  Activity
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Activity
 ABSTRACT
 SUPERTYPE OF (ONEOF (ActualActivity, PlannedActivity));
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  activityType : ClassSelect;
  status : OPTIONAL ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  possibleMethods : OPTIONAL SET[1:?] OF ActivityMethod; -- a relationship?
  chosenMethod : OPTIONAL ActivityMethod;
  requestor : OPTIONAL DateAndPersonOrganization;
  supplyingOrganizations : OPTIONAL SET[1:?] OF Organization;
  concernedOrganizations : OPTIONAL SET[1:?] OF Organization;
END_ENTITY;

ENTITY ActualActivity
  SUPERTYPE OF (DirectedActualActivity)
  SUBTYPE OF (Activity);
  actualStartDate : OPTIONAL DateTimeString;
  actualEndDate : OPTIONAL DateTimeString;
END_ENTITY;

ENTITY PlannedActivity
  SUPERTYPE OF (DirectedPlannedActivity)
  SUBTYPE OF (Activity);
  versionId : OPTIONAL IdentifierSelect;
  plannedStartDate : OPTIONAL EventOrDateSelect;
  plannedEndDate : OPTIONAL PeriodOrDateSelect;
END_ENTITY;

ENTITY DirectedActualActivity
  SUBTYPE OF (ActualActivity);
  directive : WorkOrder;
END_ENTITY;

ENTITY DirectedPlannedActivity
  SUBTYPE OF (PlannedActivity);
  directive : WorkOrder;
END_ENTITY;

ENTITY ActivityRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Activity;
  related : Activity;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ActivityHappeningRelationship
 SUBTYPE OF (ActivityRelationship);
  SELF\ActivityRelationship.relating : PlannedActivity;
  SELF\ActivityRelationship.related :  ActualActivity;
 DERIVE
  SELF\ActivityRelationship.relationType : ClassSelect := 'happening';
END_ENTITY;


ENTITY ActivityAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedActivity : Activity;
  assignedTo : SET[1:?] OF ActivityAssignmentSelect;
END_ENTITY;

TYPE ActivityAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityRelationship,
  AddressAssignment,
  AlternatePartRelationship,
  AlternativeSolution,
  ApprovalAssignment,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  AssignmentObjectRelationship,
  Breakdown,
  BreakdownVersionAssignment,
  BreakdownElement,
  BreakdownElementRealization,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionRelationship,
  CertificationAssignment,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  ConditionalConfiguration,
  ConditionAssignment,
  ConfiguredAssemblyEffectivity,
  Contract,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  Effectivity,
  EffectivityAssignment,
  Event,
  EventAssignment,
  File,
  FrozenAssignment,
  GeometricRepresentation,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  MaterialIdentification,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Organization,
  OrganizationOrPersonInOrganizationAssignment,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  ProcessOperationDefinition,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductClass,
  ProductConfiguration,
  Project,
  ProjectAssignment,
  ProjectRelationship,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueRelationship,
  Requirement,
  RequirementAssignment,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassificationAssignment,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  Condition,
  SpecificationInclusion,
  SpecificationInclusionAssignment,
  StyledModel,
  TimeIntervalAssignment,
  ViewOccurrenceRelationship,
  WorkOrderAssignment,
  WorkRequestAssignment
);
END_TYPE;

ENTITY ActivityMethod;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  consequence : OPTIONAL MultiLingualStringSelect;
  purpose : MultiLingualStringSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY ActivityMethodAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedActivityMethod : ActivityMethod;
  assignedTo : SET[1:?] OF ActivityMethodAssignmentSelect;
END_ENTITY;

TYPE ActivityMethodAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  AddressAssignment,
  AlternativeSolution,
  ApprovalAssignment,
  Breakdown,
  BreakdownVersionAssignment,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionRelationship,
  CertificationAssignment,
  ConditionAssignment,
  Contract,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  EffectivityAssignment,
  EventAssignment,
  File,
  FrozenAssignment,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationUsageRightAssignment,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Organization,
  OrganizationOrPersonInOrganizationAssignment,
  Part,
  PartVersion,
  PartVersionRelationship,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  ProcessOperationResourceAssignment,
  ProductClass,
  ProductConfiguration,
  Project,
  ProjectAssignment,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  PropertyValueAssignment,
  PropertyValueAssignmentRelationship,
  PropertyValueRelationship,
  Requirement,
  RequirementAssignment,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  SecurityClassificationAssignment,
  SpecificationAssignment,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  TimeIntervalAssignment,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment
);
END_TYPE;

ENTITY ActivityMethodRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : ActivityMethod;
  related : ActivityMethod;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY ElementDelivery;
  role : ClassSelect;
  associatedActivity : Activity;
  deliverableElements : SET[1:?] OF ActivityAssignmentSelect;
  destination : Organization;
  quantity : ValueWithUnit;
END_ENTITY;


(*:AMW2
 ------------------------------------------------------------
  Work Management
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY WorkOrder;
  id : IdentifierSelect;
  versionId : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  orderType : ClassSelect;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  inResponseTo : OPTIONAL SET[1:?] OF WorkRequest;
END_ENTITY;

ENTITY WorkOrderRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : WorkOrder;
  related : WorkOrder;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY WorkOrderAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedWorkOrder : WorkOrder;
  assignedTo : SET[1:?] OF WorkOrderAssignmentSelect;
END_ENTITY;

TYPE WorkOrderAssignmentSelect = SELECT (
  Activity,
  ActivityMethod
);
END_TYPE;

ENTITY WorkRequest;
  id : IdentifierSelect;
  versionId : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs: OPTIONAL SET[1:?] OF Classification;
  requestType : ClassSelect;
  status : OPTIONAL ClassSelect;
  requestor : DateAndPersonOrganization;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
  scope : OPTIONAL SET[1:?] OF ActivityAssignmentSelect;
  notifiedPersons : OPTIONAL SET[1:?] OF DateAndPersonOrganization;
END_ENTITY;

ENTITY WorkRequestRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : WorkRequest;
  related : WorkRequest;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY WorkRequestAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedWorkRequest : WorkRequest;
  assignedTo : SET[1:?] OF WorkRequestAssignmentSelect;
END_ENTITY;

TYPE WorkRequestAssignmentSelect = SELECT (
  Activity,
  ActivityMethod,
  Breakdown,
  BreakdownElement,
  BreakdownElementVersion,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  Contract,
  Document,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  File,
  IndividualPart,
  IndividualPartVersion,
  IndividualPartView,
  IndividualPartViewRelationship,
  Organization,
  Part,
  PartVersion,
  PartView,
  PartViewRelationship,
  Person,
  PersonInOrganization,
  ProductConfiguration,
  Project,
  Requirement,
  RequirementVersion,
  RequirementView,
  RequirementViewRelationship
);
END_TYPE;


(*:AMW3
 ------------------------------------------------------------
  Delta Change
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY DeltaChange;
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  changeActivities : OPTIONAL SET[1:?] OF DeltaChangeActivity;
  describedChange : OPTIONAL DeltaChangeRelationshipSelect;
END_ENTITY;

TYPE DeltaChangeRelationshipSelect = SELECT (
  AlternativeSolutionRelationship,
  BreakdownElementVersionRelationship,
  DocumentVersionRelationship,
  PartVersionRelationship,
  ProcessOperationOccurrenceRelationship,
  ProcessPlanRelationship,
  ReplacedPartViewRelationship,
  ReplacedUsageRelationship,
  RequirementVersionRelationship,
  ShapeElementRelationship
);
END_TYPE;

ENTITY ChangeElementSequence;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relating : DeltaChangeActivity;
  related : DeltaChangeActivity;
END_ENTITY;

ENTITY DeltaChangeActivity
 ABSTRACT
 SUPERTYPE OF(ONEOF(AddElement, DeleteElement, ModifyElement, ModifySingleElement));
  attributeName : OPTIONAL CharacterString;
  changeLocationInAggregateAttribute : OPTIONAL LIST[1:?] OF INTEGER;
 INVERSE
  changeSet : DeltaChange FOR changeActivities;
END_ENTITY;

ENTITY AddElement
 SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY DeleteElement
 SUBTYPE OF(DeltaChangeActivity);
  previousDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY ModifyElement
 SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

ENTITY ModifySingleElement
 SUBTYPE OF(DeltaChangeActivity);
  currentDesignObject : DeltaChangeManagementObjectSelect;
  previousDesignObject : DeltaChangeManagementObjectSelect;
 WHERE
  WR1: currentDesignObject :<>: previousDesignObject;
END_ENTITY;

ENTITY FrozenAssignment;
  frozenObject : SET[1:?] OF DeltaChangeManagementObjectSelect;
END_ENTITY;

TYPE DeltaChangeManagementObjectSelect = ActivityAssignmentSelect;
END_TYPE;


(*:DM1
 ------------------------------------------------------------
  Document Identification
 ------------------------------------------------------------
*)

-- harmonized with PLCS

ENTITY Document;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  documentTypes : SET[1:?] OF ClassSelect;
  versions : SET[1:?] OF DocumentVersion;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
END_ENTITY;

ENTITY DocumentAssignment;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  role : ClassSelect;
  assignedDocument : AssignedDocumentSelect;
  assignedTo : SET[1:?] OF DocumentAssignmentSelect;
  documentPortion : OPTIONAL MultiLingualStringSelect;
END_ENTITY;

TYPE AssignedDocumentSelect = SELECT (
  Document,
  DocumentVersion,
  DocumentDefinition,
  File
);
END_TYPE;

TYPE DocumentAssignmentSelect = SELECT (
  Activity,
  ActivityAssignment,
  ActivityMethod,
  ActivityMethodAssignment,
  ActivityMethodRelationship,
  ActivityRelationship,
  AddressAssignment,
  AlternativeSolution,
  Approval,
  ApprovalAssignment,
  ApprovalRelationship,
  ApprovingPersonOrganization,
  AssemblyOccurrenceRelationshipSubstitution,
  AssemblyViewRelationshipSubstitution,
  Breakdown,
  BreakdownElement,
  BreakdownContext, --BreakdownElementAssociation,
  BreakdownElementRealization,
  BreakdownElementVersion,
  BreakdownElementVersionRelationship,
  BreakdownElementView,
  BreakdownElementViewRelationship,
  BreakdownVersion,
  BreakdownVersionAssignment,
  BreakdownVersionRelationship,
  Certification,
  CertificationAssignment,
  ClassAttribute,
  Classification,
  Class,
  ClassString,
  ExternalClass,
  ExternalOwlClass,
  Condition,
  ConditionAssignment,
  ConditionRelationship,
  Contract,
  ContractAssignment,
  DateAndPersonAssignment,
  DateTimeAssignment,
  DeltaChange,
  Descriptor,
  DescriptorRelationship,
  Document,
  DocumentAssignment,
  DocumentDefinition,
  DocumentDefinitionRelationship,
  DocumentVersion,
  DocumentVersionRelationship,
  Effectivity,
  EffectivityAssignment,
  EffectivityRelationship,
  EventAssignment,
  ExternalItem,
  FileRelationship,
  FrozenAssignment,
  Identifier,
  IdentifierRelationship,
  IndividualAssemblyRelationship,
  IndividualPart,
  IndividualPartTestResult,
  IndividualPartVersion,
  IndividualPartVersionRelationship,
  IndividualPartView,
  IndividualPartViewRelationship,
  InformationRight,
  InformationUsageRight,
  InformationUsageRightAssignment,
  InformationUsageRightRelationship,
  InZone,
  MaterialIdentification,
  MaterialPropertyAssignment,
  ModelPropertyAssignment,
  Organization,
  OrganizationOrPersonInOrganizationAssignment,
  OrganizationRelationship,
  Part,
  Occurrence,
  OccurrenceRelationship,
  PartRelationship,
  PartToIndividualPartAssociation,
  PartVersion,
  PartVersionRelationship,
  PartVersionToIndividualPartVersionAssociation,
  PartView,
  PartViewRelationship,
  PartViewToIndividualPartViewAssociation,
  Person,
  PersonInOrganization,
  ProcessOperationOccurrence,
  ProcessOperationResourceAssignment,
  ProcessPlan,
  ProductConcept,
  ProductConfiguration,
  Project,
  ProjectAssignment,
  ProjectRelationship,
  PropertyDefinitionAssignment,
  PropertyDefinitionRelationship,
  ExternalPropertyDefinition,
  PropertyDefinition,
  PropertyDefinitionString,
  PropertyValue,
  PropertyValueAssignment,
  PropertyValueRelationship,
  Proxy,
  Requirement,
  RequirementAssignment,
  RequirementSource,
  RequirementVersion,
  RequirementVersionRelationship,
  RequirementView,
  RequirementViewRelationship,
  RetentionPeriod,
  SecurityClassification,
  SecurityClassificationAssignment,
  ShapeElement,
  ShapeElementRelationship,
  Specification,
  SpecificationAssignment,
  SpecificationCategory,
  SpecificationCategoryAssignment,
  SpecificationConditionAssignment,
  SpecificationInclusionAssignment,
  SurfaceCondition,
  TimeInterval,
  TimeIntervalAssignment,
  TimeIntervalRelationship,
  ViewContext,
  ViewOccurrenceRelationship,
  WorkOrder,
  WorkOrderAssignment,
  WorkRequest,
  WorkRequestAssignment
);
END_TYPE;

ENTITY DocumentRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : Document;
  related : Document;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DocumentVersion;
  id : IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  views : OPTIONAL SET[1:?] OF DocumentDefinition;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 INVERSE
  versionOf : Document FOR versions;
END_ENTITY;

ENTITY DocumentVersionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : DocumentVersion;
  related : DocumentVersion;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;


(*:DM2
 ------------------------------------------------------------
  Document Structure and Property
 ------------------------------------------------------------
*)

-- partially harmonized with PLCS

ENTITY DocumentDefinition
 SUPERTYPE OF(ONEOF(DigitalDocumentDefinition, PhysicalDocumentDefinition));
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  documentContent : OPTIONAL ContentProperty;
  documentCreation : OPTIONAL CreationProperty;
  documentFormat : OPTIONAL SET[1:?] OF FormatProperty;
  documentSize : OPTIONAL SizeProperty;
  sameAs : OPTIONAL SET[1:?] OF ProxySelect;
 INVERSE
  viewOf : DocumentVersion FOR views;
END_ENTITY;

ENTITY DocumentDefinitionRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : DocumentDefinition;
  related : DocumentDefinition;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY DigitalDocumentDefinition
 SUBTYPE OF(DocumentDefinition);
  files : OPTIONAL SET[1:?] OF DigitalFile;
END_ENTITY;

ENTITY PhysicalDocumentDefinition
 SUBTYPE OF(DocumentDefinition);
  components : OPTIONAL SET[1:?] OF Hardcopy;
END_ENTITY;

ENTITY File
 ABSTRACT
 SUPERTYPE OF(ONEOF(DigitalFile, Hardcopy));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  fileType : OPTIONAL ClassSelect;
  fileContent : OPTIONAL ContentProperty;
  fileCreation : OPTIONAL CreationProperty;
  fileFormat : OPTIONAL FormatProperty;
  fileSize : OPTIONAL SizeProperty;
  locations : OPTIONAL SET[1:?] OF ExternalItem;
END_ENTITY;

ENTITY FileRelationship;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  relationType : ClassSelect;
  relating : File;
  related : File;
 WHERE
  WR1: relating :<>: related;
END_ENTITY;

ENTITY Hardcopy
 SUBTYPE OF(File);
END_ENTITY;

ENTITY DigitalFile
 SUBTYPE OF(File);
 INVERSE
  associatedModelSpace : SET[0:?] OF ExternalGeometricModel FOR externalFile;
END_ENTITY;

ENTITY ContentProperty;
  description : OPTIONAL DescriptorSelect;
  detailLevel : OPTIONAL DescriptorSelect;
  geometryTypes : OPTIONAL SET[1:?] OF Classification;
  languages : OPTIONAL SET[1:?] OF Language;
  realWorldScale : OPTIONAL NumericalValue;
END_ENTITY;

ENTITY CreationProperty;
  description : OPTIONAL DescriptorSelect;
  creatingInterface : OPTIONAL CharacterString;
  creatingSystem : CharacterString;
  operatingSystem : OPTIONAL CharacterString;
END_ENTITY;

ENTITY FormatProperty;
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  characterCode : OPTIONAL ClassSelect;
  dataFormat : OPTIONAL ClassSelect;
  sizeFormat : OPTIONAL RectangularSize;
END_ENTITY;

ENTITY SizeProperty;
  description : OPTIONAL DescriptorSelect;
  fileSize : OPTIONAL ValueWithUnit;
  pageCount : OPTIONAL ValueWithUnit;
END_ENTITY;

ENTITY NamedSize
 SUBTYPE OF(RectangularSize);
  size : ClassSelect;
END_ENTITY;

ENTITY RectangularSize
 SUPERTYPE OF(ONEOF(NamedSize));
  density : OPTIONAL ValueWithUnit;
  height : OPTIONAL ValueWithUnit;
  width : OPTIONAL ValueWithUnit;
END_ENTITY;


(*:DM3
 ------------------------------------------------------------
  External References
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY ExternalGeometricModel
 SUPERTYPE OF(ONEOF(ExternalAdvancedBrepShapeRepresentation, ExternalCsgShapeRepresentation, ExternalCurveSweptSolidShapeRepresentation, ExternalEdgeBasedWireframeShapeRepresentation, ExternalElementaryBrepShapeRepresentation, ExternalFacetedBrepShapeRepresentation, ExternalGeometricallyBoundedSurfaceShapeRepresentation, ExternalGeometricallyBoundedWireframeShapeRepresentation, ExternalManifoldSurfaceShapeRepresentation, ExternalShellBasedWireframeShapeRepresentation, ExternalTessellatedShapeRepresentation))
 SUBTYPE OF(GeometricModel);
  externalFile : DigitalFile;
  SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacementOrTransformationSelect;
  parameterValues : OPTIONAL SET[1:?] OF PropertyValue;
END_ENTITY;


(*:CSS
 ------------------------------------------------------------
  Composite Structural Shape and Structure
 ------------------------------------------------------------
*)

-- not harmonized with PLCS yet

ENTITY BeveledSheetRepresentation
 SUBTYPE OF(ConstituentShapeRepresentation);
  bevelAngle : NumericalValue;
  boundarySurface : CompositeSheetRepresentation;
  verticalProfileHeight : NumericalValue;
 WHERE
  WR1: (SELF.verticalProfileHeight.unit.name='length') AND (SELF.bevelAngle.unit.name='angle');
END_ENTITY;

ENTITY BoundaryCurveRepresentation;
  name : OPTIONAL DescriptorSelect;
  bounds : SET[1:?] OF GeometricBoundingCurveSelect;
END_ENTITY;

TYPE GeometricBoundingCurveSelect = SELECT (
  CompositeCurveOnSurface,
  Pcurve,
  SurfaceCurve
);
END_TYPE;

ENTITY CompositeAssembly
 SUBTYPE OF(ConstituentPart);
  layupPart : CompositeAssemblyTable;
  shape : OPTIONAL CompositeAssemblyShapeSelect;
END_ENTITY;

TYPE CompositeAssemblyShapeSelect = SELECT (
  ExternalAdvancedBrepShapeRepresentation,
  ExternalEdgeBasedWireframeShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation,
  ExternalGeometricallyBoundedSurfaceShapeRepresentation,
  ExternalGeometricallyBoundedWireframeShapeRepresentation,
  ExternalManifoldSurfaceShapeRepresentation,
  ExternalShellBasedWireframeShapeRepresentation,
  ThreeDGeometrySet
);
END_TYPE;

ENTITY CompositeAssemblySequenceDefinition;
  componentsInSequence : OPTIONAL BAG[1:?] OF ComponentClassForAssemblySelect;
END_ENTITY;

TYPE ComponentClassForAssemblySelect = SELECT (
  CompositeAssembly,
  FilamentLaminate,
  Ply,
  PlyLaminate,
  ProcessedCore
);
END_TYPE;

ENTITY CompositeAssemblyTable
 SUBTYPE OF(LaminateTable);
  sequenceGroups : LIST[2:?] OF CompositeAssemblySequenceDefinition;
END_ENTITY;

ENTITY CompositeSheetRepresentation
 SUPERTYPE OF(ONEOF(FaceBasedSheetRepresentation, GeometricSheetRepresentation))
 SUBTYPE OF(ConstituentShapeRepresentation);
  threeDGeometry : ExternalGeometricModel;
END_ENTITY;

ENTITY ConstituentPart
 SUBTYPE OF(PartView);
  weight : OPTIONAL NumericalValue;
 WHERE
  WR1: ((NOT(EXISTS(SELF.weight))) OR ((EXISTS(SELF.weight)) AND (SELF.weight.unit.name='mass')));
END_ENTITY;

ENTITY ConstituentShapeRepresentation
 ABSTRACT
 SUPERTYPE OF(ONEOF(BeveledSheetRepresentation, CompositeSheetRepresentation, ThreeDGeometrySet))
 SUBTYPE OF (GeometricRepresentation);
END_ENTITY;

ENTITY DirectionOfFiberOrientationWithinAPly;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  angleReferences : SET[1:?] OF AngleSelect;
  basis : ReinforcementOrientationBasis;
 INVERSE
  orientations : PlyOrientationAngle FOR fiberDirection;
END_ENTITY;

TYPE AngleSelect = SELECT (
  AxisPlacement,
  Direction,
  Curve,
  PointPath
);
END_TYPE;

ENTITY DrapedOrientationAngle
 SUBTYPE OF(PlyOrientationAngle);
END_ENTITY;

ENTITY EdgeZoneShape
 SUBTYPE OF(ZoneStructuralMakeupShapeRepresentation);
  boundary : BoundaryClassZoneSelect;
END_ENTITY;

TYPE BoundaryClassZoneSelect = SELECT (
  Loop,
  GeometricBoundingCurveSelect
);
END_TYPE;

ENTITY ExternalAdvancedBrepShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY CompositeCurveOnSurface
 SUBTYPE OF(Curve);
END_ENTITY;

ENTITY ExternalCsgShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY Curve
 SUPERTYPE OF (ONEOF (Pcurve, SurfaceCurve, TrimmedCurve, CompositeCurveOnSurface))
 SUBTYPE OF(DetailedGeometricModelItem);
  SELF\RepresentationItem.external : ExternalItem; 
END_ENTITY;

ENTITY ExternalCurveSweptSolidShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY DegeneratePcurve
 SUBTYPE OF(Pcurve);
END_ENTITY;

ENTITY ExternalEdgeBasedWireframeShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY ExternalElementaryBrepShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY ExternalFacetedBrepShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY ExternalGeometricallyBoundedSurfaceShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY ExternalGeometricallyBoundedWireframeShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY Loop
 SUBTYPE OF(DetailedGeometricModelItem);
  SELF\RepresentationItem.external : ExternalItem;  
END_ENTITY;

ENTITY ExternalManifoldSurfaceShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY OrientedSurface
 SUBTYPE OF(Surface);
END_ENTITY;

ENTITY Pcurve
 SUBTYPE OF(Curve);
END_ENTITY;

ENTITY PointOnCurve
 SUBTYPE OF(Point);
  basicCurve : Curve;
  parameter : ExternalRepresentationItem;
  SELF\RepresentationItem.external : ExternalItem;
END_ENTITY;

ENTITY PointOnSurface
 SUBTYPE OF(Point);
  basicSurface : Surface;
  parameter : ExternalRepresentationItem;
  SELF\RepresentationItem.external : ExternalItem;
END_ENTITY;

ENTITY PointPath
 SUBTYPE OF(DetailedGeometricModelItem);
  SELF\RepresentationItem.external : ExternalItem;  
END_ENTITY;

ENTITY ExternalShellBasedWireframeShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY Surface
 SUPERTYPE OF (ONEOF (OrientedSurface, RectangularTrimmedSurface))
 SUBTYPE OF(DetailedGeometricModelItem);
  SELF\RepresentationItem.external : ExternalItem;
END_ENTITY;

ENTITY SurfaceCurve
 SUBTYPE OF(Curve);
END_ENTITY;

ENTITY ExternalTessellatedShapeRepresentation
 SUBTYPE OF(ExternalGeometricModel);
END_ENTITY;

ENTITY FaceBasedSheetRepresentation
 SUBTYPE OF(CompositeSheetRepresentation);
  faceSurface : Surface;
  innerBounds : OPTIONAL SET[1:?] OF Loop;
  outerBound : Loop;
END_ENTITY;

ENTITY FilamentLaminate
 SUBTYPE OF(ConstituentPart);
  madeFrom : StockMaterial;
  shapeCrossSection : OPTIONAL GeometricModel;
 WHERE
  WR1 : SELF.madeFrom.stockMaterialType = filament_assembly;
END_ENTITY;

ENTITY GeometricSheetRepresentation
 SUBTYPE OF(CompositeSheetRepresentation);
  basisSurface : Surface;
  cutouts : OPTIONAL SET[1:?] OF BoundaryCurveRepresentation;
  outerEdge : BoundaryCurveRepresentation;
END_ENTITY;

ENTITY LaidOrientationAngle
 SUBTYPE OF(PlyOrientationAngle);
END_ENTITY;

ENTITY LaminateTable
 SUPERTYPE OF(ONEOF(CompositeAssemblyTable, PlyLaminateTable, ZoneStructuralMakeup))
 SUBTYPE OF(PartView);
  baseSurface : SurfaceWithDirection;
  basis : ReinforcementOrientationBasis;
  resultingSurface : Surface;
 WHERE
  WR1: SELF.initialContext.applicationdomain = 'composites';
END_ENTITY;

ENTITY PercentageLaminateTable
 SUBTYPE OF(ZoneStructuralMakeup);
  tableComponents : SET[1:?] OF PercentagePly;
  totalThickness : NumericalValue;
END_ENTITY;

ENTITY PercentagePly;
  makeupAndProperties : OPTIONAL ZoneStructuralMakeup;
  material : StockMaterial;
  strengthOrientation : OPTIONAL PlyOrientationAngle;
  volumePercent : NumericalValue;
END_ENTITY;

ENTITY Ply
 SUBTYPE OF(ConstituentPart);
  materialType : StockMaterial;
  constituents : OPTIONAL LIST[1:?] OF PlyPiece;
  materialOrientation : DirectionOfFiberOrientationWithinAPly;
  plyThickness : NumericalValue;
  shape : OPTIONAL PlyShape;
 WHERE
  WR1 : SELF.plyThickness.valueComponent >= 0.0;
  WR2 : SELF.plyThickness.unit.name='length';
END_ENTITY;

ENTITY PlyLaminate
 SUBTYPE OF(ConstituentPart);
  plyTable : PlyLaminateTable;
  shape : OPTIONAL PlyLaminateShapeSelect;
END_ENTITY;

TYPE PlyLaminateShapeSelect = SELECT (
  CompositeSheetRepresentation,
  ExternalAdvancedBrepShapeRepresentation,
  ExternalCsgShapeRepresentation,
  ExternalCurveSweptSolidShapeRepresentation,
  ExternalElementaryBrepShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation,
  ExternalTessellatedShapeRepresentation,
  ThreeDGeometrySet
);
END_TYPE;

ENTITY PlyLaminateSequenceDefinition
 SUBTYPE OF(ConstituentPart);
  pliesInSequence : SET[1:?] OF Ply;
END_ENTITY;

ENTITY PlyLaminateTable
 SUBTYPE OF(LaminateTable);
  sequence : LIST[2:?] OF PlyLaminateSequenceDefinition;
END_ENTITY;

ENTITY PlyOrientationAngle
 ABSTRACT
 SUPERTYPE OF(ONEOF(DrapedOrientationAngle, LaidOrientationAngle));
  description : OPTIONAL DescriptorSelect;
  angleReference : AngleSelect;
  fiberDirection : DirectionOfFiberOrientationWithinAPly;
  reinforcementDirection : ReinforcementOrientationBasis;
END_ENTITY;

ENTITY PlyPiece
 SUBTYPE OF(ConstituentPart);
  shape : OPTIONAL PlyShape;
  warpSurface : LOGICAL;
END_ENTITY;

ENTITY PlyShape;
  basis : OPTIONAL PlyShape;
  definingModel : PlyLaminateShapeSelect;
END_ENTITY;

ENTITY PointZoneShape
 SUBTYPE OF(ZoneStructuralMakeupShapeRepresentation);
  location : PointSelect;
END_ENTITY;

TYPE PointSelect = SELECT (
  CartesianPoint,
  DegeneratePcurve,
  PointOnCurve,
  PointOnSurface
);
END_TYPE;

ENTITY ProcessedCore
 SUBTYPE OF(ConstituentPart);
  addedMaterial : OPTIONAL LIST[1:?] OF Ply;
  cellDirection : DirectionOfFiberOrientationWithinAPly;
  madeFromProcessedCore : OPTIONAL SET[1:?] OF ProcessedCore;
  madeFromStock : StockMaterial;
  shape : OPTIONAL CoreShapeSelect;
 WHERE
  WR1: SELF.madeFromStock.stockMaterialType = stock_core;
END_ENTITY;

TYPE CoreShapeSelect = SELECT (
  BeveledSheetRepresentation,
  ExternalAdvancedBrepShapeRepresentation,
  ExternalFacetedBrepShapeRepresentation
);
END_TYPE;

ENTITY ReinforcementOrientationBasis;
  id : OPTIONAL IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  coordinateSpace : GeometricCoordinateSpace;
  placement : AxisPlacement;
 INVERSE
  tables : SET[1:?] OF LaminateTable FOR basis;
END_ENTITY;

ENTITY SmearedMaterial
 SUBTYPE OF(ZoneStructuralMakeup);
  totalThickness : NumericalValue;
END_ENTITY;

ENTITY StockMaterial;
  id : IdentifierSelect;
  name : DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  stockMaterialType : StockCategoryEnum;
  propertyValues : SET[1:?] OF MaterialPropertyValue;
  referenceDirection : OPTIONAL Direction;
END_ENTITY;

TYPE StockCategoryEnum = ENUMERATION OF(
  anisotropic_material,
  braided_assembly,
  discontinuous_fiber_assembly,
  filament_assembly,
  isotropic_material,
  stock_core,
  woven_assembly
);
END_TYPE;

ENTITY SurfaceWithDirection;
  definingSurface : Surface;
  materialDirection : Direction;
END_ENTITY;

ENTITY ThicknessLaminateTable
 SUBTYPE OF(ZoneStructuralMakeup);
  tableComponents : LIST[2:?] OF ThicknessLaminateTableComponentSelect;
END_ENTITY;

TYPE ThicknessLaminateTableComponentSelect = SELECT (
  FilamentLaminate,
  Ply,
  ProcessedCore
);
END_TYPE;

ENTITY ThicknessSizeDimension;
  id : IdentifierSelect;
  appliedTo : ShapeElement;
  thickness : NumericalValue;
END_ENTITY;

ENTITY ThreeDGeometrySet
 SUBTYPE OF(ConstituentShapeRepresentation);
  basisRole : ClassSelect;
  basisSurface : Surface;
  definingBoundary : SET[1:?] OF GeometricBoundingCurveSelect;
  threeDGeometry : ExternalGeometricModel;
END_ENTITY;

ENTITY ZoneStructuralMakeup
 ABSTRACT
 SUPERTYPE OF(ONEOF(PercentageLaminateTable, SmearedMaterial, ThicknessLaminateTable))
 SUBTYPE OF(LaminateTable);
  boundary : ZoneStructuralMakeupShapeRepresentation;
END_ENTITY;

ENTITY ZoneStructuralMakeupShapeRepresentation
 SUPERTYPE OF(ONEOF(EdgeZoneShape, PointZoneShape));
END_ENTITY;


(*:GS
 ------------------------------------------------------------
  Geometric Shape
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY GeometricRepresentation
 ABSTRACT
 SUPERTYPE OF(ONEOF(GeometricModel, ConstituentShapeRepresentation, StyledModel, Mechanism, MechanismState, KinematicLink, LinkMotionAlongPath, InterpolatedConfigurationModel));
  id : IdentifierSelect;
  name : OPTIONAL DescriptorSelect;
  description : OPTIONAL DescriptorSelect;
  versionId : OPTIONAL IdentifierSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  representationTypes : OPTIONAL SET[1:?] OF ClassSelect;
  contextOfItems : GeometricCoordinateSpace;
  items : SET[1:?] OF RepresentationItem;
END_ENTITY;

ENTITY GeometricRepresentationRelationship
 ABSTRACT
 SUPERTYPE OF (ONEOF(
    GeometricRepresentationRelationshipWithCartesianTransformation,
    GeometricRepresentationRelationshipWithPlacementTransformation,
    GeometricRepresentationRelationshipWithSameCoordinateSpace));
  id : OPTIONAL IdentifierSelect;
  description : OPTIONAL DescriptorSelect;
  classifiedAs : OPTIONAL SET[1:?] OF Classification;
  definitional : BOOLEAN;
  relating : GeometricRepresentation;
  related : GeometricRepresentation;
END_ENTITY;

ENTITY GeometricModel
 SUPERTYPE OF(ONEOF(ComposedGeometricModel, TransformedGeometricModel, ExternalGeometricModel))
 SUBTYPE OF (GeometricRepresentation);
  modelExtent : OPTIONAL LengthMeasure;
END_ENTITY;

ENTITY GeometricRepresentationRelationshipWithPlacementTransformation
 SUBTYPE OF (GeometricRepresentationRelationship);
  origin : AxisPlacement;
  target : AxisPlacement;
 WHERE
  WR1: SELF\GeometricRepresentationRelationship.relating.contextOfItems :<>: SELF\GeometricRepresentationRelationship.related.contextOfItems;
END_ENTITY;

ENTITY GeometricRepresentationRelationshipWithSameCoordinateSpace
 SUBTYPE OF (GeometricRepresentationRelationship);
 WHERE
  WR1: SELF\GeometricRepresentationRelationship.relating.contextOfItems :=: SELF\GeometricRepresentationRelationship.related.contextOfItems;
END_ENTITY;
  
ENTITY GeometricRepresentationRelationshipWithCartesianTransformation
 SUBTYPE OF (GeometricRepresentationRelationship);
  transformation : CartesianTransformation;
 WHERE
  WR1: SELF\GeometricRepresentationRelationship.relating.contextOfItems :<>: SELF\GeometricRepresentationRelationship.related.contextOfItems;
END_ENTITY;

ENTITY ComposedGeometricModel
 SUBTYPE OF (GeometricModel);
  SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacementOrTransformationSelect;
END_ENTITY;

ENTITY TransformedGeometricModel
 SUBTYPE OF (GeometricModel);
  SELF\GeometricRepresentation.items : SET[1:?] OF AxisPlacementOrTransformationSelect;
 DERIVE
  sourceModel : GeometricModel := derivedFrom.relating;
 INVERSE
  derivedFrom : GeometricRepresentationRelationship FOR related;  
 WHERE
  WR1: (SCHEMA_NAME + 'GEOMETRICREPRESENTATIONRELATIONSHIPWITHOPERATORTRANSFORMATION' IN TYPEOF(derivedFrom)) OR
       (SCHEMA_NAME + 'GEOMETRICREPRESENTATIONRELATIONSHIPWITHPLACEMENTTRANSFORMATION' IN TYPEOF(derivedFrom));
END_ENTITY;

TYPE AxisPlacementOrTransformationSelect = SELECT (
  AxisPlacement,
  CartesianTransformation
);
END_TYPE;  



(*:PGC
 ------------------------------------------------------------
  3D Parametrics and Geometric Constraints Design
 ------------------------------------------------------------
*)

-- not harmonized with PLCS

ENTITY CoatingLayer
 SUBTYPE OF(ShapeElement);
 INVERSE
  thickness : SET[0:1] OF ThicknessSizeDimension FOR appliedTo;
END_ENTITY;

ENTITY SurfaceCondition;
  id : IdentifierSelect;
  assignedTo : ShapedElementSelect;
  conditionType : ClassString;
  definedIn : DigitalFile;
END_ENTITY;


(*:MF
 ------------------------------------------------------------
  Machining Feature
 ------------------------------------------------------------
*)

-- not part of DIS version of edition 1


(*:SDQ1
 ------------------------------------------------------------
  Shape Data Quality Criteria
 ------------------------------------------------------------
*)

-- not part of DIS version of edition 1


(*:SDQ2
 ------------------------------------------------------------
  Shape Data Quality Inspection
 ------------------------------------------------------------
*)

-- not part of DIS version of edition 1


(*:PD
 ------------------------------------------------------------
  Presentation and Draughting
 ------------------------------------------------------------
*)

ENTITY StyledModel
 SUBTYPE OF(GeometricRepresentation);
  definedIn : DigitalFile;
END_ENTITY;


(*:GDT
 ------------------------------------------------------------
  Geometric Dimensions and Tolerances
 ------------------------------------------------------------
*)

-- not part of DIS version of edition 1

END_SCHEMA;

