(*
  ISO TC184/SC4/WG12 N4xxx - ISO/TS 10303-1xxy Thickened face solid - EXPRESS MIM
*)

SCHEMA Basic_geometric_topology_mim;

USE FROM Elemental_topology_mim;

USE FROM Basic_geometry_mim; -- GL added need to access curve, which was previously defined in this module

USE FROM topology_schema  -- ISO 10303-42
      (edge,
      edge_curve,
      vertex,
      vertex_point); 
    
USE FROM geometry_schema  -- ISO 10303-42
      (curve);

END_SCHEMA;

