(*
   $Id: mim.exp,v 1.17 2007/11/15 12:37:56 liutkus Exp $
   ISO TC184/SC4/WG12 N5594 - ISO/TS 10303-1642 Assembly module usage view - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3874
*)
SCHEMA Assembly_module_usage_view_mim;

--	USE FROM Functional_assignment_to_part_mim;	-- ISO/TS 10303-1674
	USE FROM Functional_usage_view_mim;	-- ISO/TS 10303-1705
	USE FROM Packaged_connector_model_mim;	-- ISO/TS 10303-1708

ENTITY assembly_definition
 SUBTYPE OF (physical_unit);
END_ENTITY;

ENTITY assembly_module_interface_terminal
  SUBTYPE OF (assembly_module_terminal);
END_ENTITY;

ENTITY assembly_module_terminal
  SUPERTYPE OF (assembly_module_interface_terminal)
  SUBTYPE OF (shape_aspect);
END_ENTITY;

END_SCHEMA;

