(*
$Id: arm.exp,v 1.4 2009/08/11 07:58:27 robbod Exp $
ISO TC184/SC4/WG12 N6582 - ISO/TS 10303-1399 Property as definition - EXPRESS ARM
*) 


SCHEMA Property_as_definition_arm;

USE FROM Product_view_definition_properties_arm;    -- ISO/TS 10303-1034

ENTITY Single_property_is_definition
  SUBTYPE OF (Assigned_property);
  SELF\Assigned_property.described_element : Product_view_definition;
UNIQUE
  UR1: SELF\Assigned_property.described_element;
END_ENTITY;

END_SCHEMA;  -- Property_as_definition_arm

