(*
   $Id: arm.exp,v 1.11 2007/11/15 12:40:22 liutkus Exp $
   ISO TC184/SC4/WG3 N1985 - ISO/TS 10303-1759 AP210 datum difference based model definition - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1745
*)

SCHEMA Ap210_datum_difference_based_model_definition_arm;

	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Datum_difference_based_model_arm;	-- ISO/TS 10303-1660

END_SCHEMA;
