(*
   $Id: arm.exp,v 1.5 2005/01/14 09:57:47 liutkus Exp $
   ISO TC184/SC4/WG12 N1668 - ISO/CD-TS 10303-1623 Ap210 laminate assembly design - EXPRESS ARM
*)

SCHEMA Ap210_laminate_assembly_design_arm;
	USE FROM Ap210_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Characteristic_arm;	-- ISO/TS 10303-1654
	USE FROM Sequential_laminate_assembly_design_arm;	-- ISO/TS 10303-1741
   --- look IS
END_SCHEMA;

