(*
   $Id: mim.exp,v 1.4 2005/01/14 09:58:02 liutkus Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 laminate assembly design - EXPRESS MIM
*)


SCHEMA Ap210_laminate_assembly_design_mim;
	USE FROM Ap210_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Characteristic_mim;	-- ISO/TS 10303-1654
	USE FROM Sequential_laminate_assembly_design_mim;	-- ISO/TS 10303-1741
END_SCHEMA;

