SCHEMA Ap209_multidisciplinary_analysis_and_design_mim;

-- AP203 Shape, Composites, and PDM
USE FROM Ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim;

-- Analysis Identification
USE FROM Analysis_assignment_mim;
USE FROM Analysis_characterized_mim;
USE FROM Analysis_identification_mim;
USE FROM Analysis_product_relationships_mim;

-- Analysis Model
USE FROM Analysis_mim;
USE FROM Analysis_representation_mim;
USE FROM Cfd_model_mim;
USE FROM Finite_elements_mim;
USE FROM Mesh_connectivity_mim;
USE FROM Mesh_topology_mim;
USE FROM Product_analysis_mim;

-- Analysis Shape
USE FROM Analysis_shape_mim;
USE FROM Finite_element_shape_mim;

-- Fields and Properties
USE FROM Cfd_specified_general_property_mim;
USE FROM Fea_definition_relationships_mim;
USE FROM Fea_material_aspects_mim;


-- Analysis Control and Results
USE FROM Cfd_equations_mim;
USE FROM Cfd_results_mim;
USE FROM Finite_element_analysis_mim;
USE FROM Mesh_function_mim;

-- Bulk import the Part 50 and 13584 schemas
USE FROM mathematical_functions_schema;           -- ISO 10303-50
USE FROM ISO13584_generic_expressions_schema;     -- ISO 13584-20
USE FROM ISO13584_expressions_schema;             -- ISO 13584-20

USE FROM Part_view_definition_mim;


TYPE Ap209e2_analysis_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
  (control,
   fea_model,
   result,
   temporal_spatial_domain);
END_TYPE;

TYPE Ap209e2_analysed_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON analysed_item WITH
  (product_definition,
   fea_model,
   temporal_spatial_domain);
END_TYPE;

END_SCHEMA;

SCHEMA Finite_elements_mim;
   ENTITY fea_model;
   END_ENTITY;
END_SCHEMA;

SCHEMA Finite_element_analysis_mim;
   ENTITY control;
   END_ENTITY;

   ENTITY result;
   END_ENTITY;

END_SCHEMA;

SCHEMA Product_analysis_mim;
   ENTITY temporal_spatial_domain;
   END_ENTITY;

END_SCHEMA;

SCHEMA Part_view_definition_mim;
   ENTITY product_definition;
   END_ENTITY;

END_SCHEMA;


SCHEMA Ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim;
END_SCHEMA;

-- Analysis Identification
SCHEMA Analysis_assignment_mim;
END_SCHEMA;
SCHEMA Analysis_identification_mim;
END_SCHEMA;
SCHEMA Analysis_product_relationships_mim;
END_SCHEMA;

-- Analysis Model
SCHEMA Analysis_mim;
END_SCHEMA;
SCHEMA Analysis_representation_mim;
END_SCHEMA;
SCHEMA Cfd_model_mim;
END_SCHEMA;
SCHEMA Mesh_connectivity_mim;
END_SCHEMA;
SCHEMA Mesh_topology_mim;
END_SCHEMA;

-- Analysis Shape
SCHEMA Analysis_shape_mim;
END_SCHEMA;
SCHEMA Finite_element_shape_mim;
END_SCHEMA;

-- Fields and Properties
SCHEMA Cfd_specified_general_property_mim;
END_SCHEMA;
SCHEMA Fea_definition_relationships_mim;
END_SCHEMA;
SCHEMA Fea_material_aspects_mim;
END_SCHEMA;


-- Analysis Control and Results
SCHEMA Cfd_equations_mim;
END_SCHEMA;
SCHEMA Cfd_results_mim;
END_SCHEMA;
SCHEMA Mesh_function_mim;
END_SCHEMA;

-- Bulk import the Part 50 and 13584 schemas
SCHEMA mathematical_functions_schema;           -- ISO 10303-50
END_SCHEMA;
SCHEMA ISO13584_generic_expressions_schema;     -- ISO 13584-20
END_SCHEMA;
SCHEMA ISO13584_expressions_schema;             -- ISO 13584-20
END_SCHEMA;


