(*
  $Id: $
  ISO/TC184/SC4 WG12NXXXX - ISO/CD-TS - 10303-ZZZZ Classification - EXPRESS ARM
*)

SCHEMA Classification_arm;

   USE FROM Class_arm; -- ISO/CD-TS 10303-1070
  
   TYPE classified_select = EXTENSIBLE SELECT;
   END_TYPE;
   
   ENTITY Classification;      
      classified : classified_select;      
      classifier : Class;
   END_ENTITY;

   ENTITY Complete_membership;
      containing_set : Class;
      members : SET [1 : ?] OF classified_select;
   END_ENTITY;

END_SCHEMA;