(*
   $Id: mim.exp,v 1.1 2003/01/02 09:02:19 goset1 Exp $
   N - ISO/CD-TS 10303- Manufacturing_configuration_effectivity - EXPRESS MIM*)

SCHEMA Manufacturing_configuration_effectivity_mim;

USE FROM Configuration_effectivity_mim;

USE FROM Person_organization_assignment_mim;

USE FROM Product_occurrence_mim;

USE FROM Specified_product_mim;


TYPE mce_organization_item = SELCT BASED_ON organization_item WITH
	(configuration_effectivity);
END_TYPE;

END_SCHEMA;
