(*
   $Id: arm.exp,v 1.12 2005/09/27 06:22:03 kovaliovas Exp $
   ISO TC184/SC4/WG12 N3408 - ISO/CD-TS 10303-1671 Feature and connection zone - EXPRESS ARM
*)

SCHEMA Feature_and_connection_zone_arm; 

	USE FROM Shape_property_assignment_arm;	-- ISO/TS 10303-1032

	SUBTYPE_CONSTRAINT facz_shape_element_subtypes FOR Shape_element;
	  ONEOF (Shape_feature,
	  Connection_zone);
	END_SUBTYPE_CONSTRAINT;

  ENTITY Shape_feature
  	ABSTRACT SUPERTYPE
       SUBTYPE OF (Shape_element);
   		connection_area : OPTIONAL SET[1:?] OF Connection_zone;
    UNIQUE
      UR1 : SELF\Shape_element.element_name, 
      SELF\shape_element.containing_shape;
  END_ENTITY;

  ENTITY Connection_zone
  	ABSTRACT SUBTYPE OF (Shape_element);
  	DERIVE
  	  SELF\Shape_element.description : STRING := '';
    WHERE
      WR1 : SIZEOF(USEDIN(SELF, '')) > 0;
  END_ENTITY;

END_SCHEMA;
