(*
   $Id: mim.exp,v 1.8 2005/02/04 15:27:11 budreckytej Exp $
   ISO TC184/SC4/WG12 N3409 - ISO/CD-TS 10303-1671 Feature and connection zone - EXPRESS MIM
*)


SCHEMA Feature_and_connection_zone_mim;
	USE FROM Shape_property_assignment_mim;	-- ISO/TS 10303-1032
	
ENTITY connection_zone_interface_plane_relationship
  SUBTYPE OF (shape_aspect, shape_aspect_relationship);
UNIQUE
  UR1: SELF\shape_aspect_relationship.name;
END_ENTITY;
	
END_SCHEMA;


