(*
   $Id: mim.exp,v 1.20 2012/10/11 05:49:23 liutkuviene Exp $
   ISO TC184/SC4/WG12 N8018 - ISO/TS 10303-1671 Feature and connection zone - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7443
*)


SCHEMA Feature_and_connection_zone_mim;
	USE FROM Shape_feature_mim; -- ISO/TS 10303-1764
	USE FROM Surface_conditions_mim; -- ISO/TS 10303-1110
	
ENTITY feature_definition_with_connection_area
  SUBTYPE OF (shape_feature_definition);
END_ENTITY;

END_SCHEMA;


