(*

   $Id: arm.exp,v 1.10 2005/01/04 07:10:55 kovaliovas Exp $

   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Assembly module macro definition - EXPRESS ARM

*)



SCHEMA Assembly_module_macro_definition_arm;



USE FROM Interconnect_module_with_macros_arm;



USE FROM Assembly_module_design_arm;



	SUBTYPE_CONSTRAINT assembly_module_terminal_subtypes FOR Assembly_module_terminal; 

	((ONEOF (Assembly_module_interface_terminal,

	 Assembly_module_join_terminal)) ANDOR

	 (Pca_terminal));

	END_SUBTYPE_CONSTRAINT;



  ENTITY Assembly_module_join_terminal

    SUBTYPE OF (Assembly_module_terminal);

    INVERSE

      defining_terminal : component_feature_to_physical_usage_view_assignment FOR defined_part_feature;

    WHERE

      WR1 : 'ASSEMBLY_MODULE_MACRO_DEFINITION_ARM.INTERCONNECT_MODULE_JOIN_TERMINAL' IN TYPEOF(defining_terminal.assigned_terminal);

      WR2 : 'ASSEMBLY_MODULE_MACRO_DEFINITION_ARM.' + 'COMPONENT_TERMINAL_TO_ASSEMBLY_MODULE_JOIN_TERMINAL_ASSIGNMENT' IN TYPEOF(defining_terminal);

      WR3 : NOT (SIZEOF(USEDIN(SELF,

 '')) > 0) OR (SIZEOF(QUERY(ct <* USEDIN(SELF,

 '') | NOT ('ASSEMBLY_MODULE_MACRO_DEFINITION_ARM.ASSEMBLY_MODULE_MACRO_COMPONENT_JOIN_TERMINAL' IN TYPEOF(ct)))) = 0);

  END_ENTITY;



  ENTITY Component_terminal_to_assembly_module_join_terminal_assignment

    SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);

		SELF\Component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal : Assembly_module_join_terminal;

		SELF\Component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal : Interconnect_module_macro_component_join_terminal;

    UNIQUE

      UR1 : usage_view_terminal;

  END_ENTITY;





END_SCHEMA;



