(*
   $Id: arm.exp,v 1.2 2015/04/16 12:51:02 lothartklein Exp $
   N - ISO/CD-TS - 10303- extruded_structure_cross_section - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA Extruded_structure_cross_section_arm;

USE FROM Physical_unit_usage_view_arm; -- ISO/TS 10303-1732
USE FROM Component_feature_arm; -- ISO/TS 10303-1657

TYPE twist_direction_enum = ENUMERATION OF (
  clockwise, 
  counter_clockwise); 
END_TYPE;

TYPE cross_sectional_constituent_element = SELECT (
  Cross_sectional_outer_component_feature,
  Cross_sectional_group_shape_element);
END_TYPE;

ENTITY Shape_element_group
  SUBTYPE OF (Shape_element);
  items : SET [1:?] OF Shape_element;
WHERE
  WR1: TRUE;-- the of_shape of the items shall be the same as the of_shape of THIS.
  WR2: NOT (SELF IN items); -- plus acyclic 
END_ENTITY; 

--- typically for library , except for the harness
ENTITY Cross_sectional_outer_part_shape_element
  SUBTYPE OF (Part_feature); -- or General_part_feature
  max_cross_section_diameter : OPTIONAL Length_data_element;
  min_cross_section_diameter : OPTIONAL Length_data_element;
  minimum_bend_radius : OPTIONAL Length_data_element;
UNIQUE
  UR1: SELF\Shape_element.associated_definition;
END_ENTITY;
-- IP: The shape of the cross section is perpendicular to the local centre line in the geometric representation.

-- The Cross_sectional_outer_part_shape_element is a kind of Part_feature
-- that represents the outer cross section shape that is perpendicular to a given centre-line.
ENTITY Cross_sectional_outer_component_feature
  SUBTYPE OF (Component_feature);
  SELF\Component_feature.definition : Cross_sectional_outer_part_shape_element;
END_ENTITY;

-- This belongs now to the assembly, e.g. the electrical harness
--  Informal Proposition (IP): the grouping is of a physical nature, at one cross-section an element can be only in one group
-- Note: A Cross_sectional_group_shape_element is not abstract on purpose because the designer may not know how the grouping is physically realised.
ENTITY Cross_sectional_group_shape_element
  SUPERTYPE OF ( ONEOF (Cross_sectional_group_shape_element_with_tubular_cover, Cross_sectional_group_shape_element_with_lacing, Twisted_cross_sectional_group_shape_element) )
  SUBTYPE OF (Shape_element_group);  -- Lothar thinks this should be Part_shape_element
  max_cross_section_diameter : OPTIONAL Length_data_element;
  min_cross_section_diameter : OPTIONAL Length_data_element;
  minimum_bend_radius : OPTIONAL Length_data_element;
  SELF\Shape_element_group.items : SET[1:?] OF cross_sectional_constituent_element; 
END_ENTITY;
-- IP: The shape of the cross section is perpendicular to the local centre line in the geometric representation.

ENTITY Cross_sectional_group_shape_element_with_tubular_cover 
  SUBTYPE OF (Cross_sectional_group_shape_element);
  cover : Component_feature; -- of the covering component;
END_ENTITY;

ENTITY Cross_sectional_group_shape_element_with_lacing
  SUBTYPE OF (Cross_sectional_group_shape_element);
  lacing_material : OPTIONAL Product_occurrence;
END_ENTITY;

ENTITY Twisted_cross_sectional_group_shape_element
  SUBTYPE OF (Cross_sectional_group_shape_element);
  twist_period : OPTIONAL Length_data_element;
  twist_direction : OPTIONAL twist_direction_enum;
END_ENTITY;

END_SCHEMA;
