(*
   $Id: arm.exp,v 1.6 2017/04/20 22:44:44 lothartklein Exp $
   N - ISO/TS 10303-1827 extruded_structure_cross_section - EXPRESS ARM*)

SCHEMA Extruded_structure_cross_section_arm;

USE FROM General_design_connectivity_arm; -- ISO/TS 10303-1844
USE FROM Value_with_unit_extension_arm; -- ISO/TS 10303-1753

TYPE twist_direction_enum = ENUMERATION OF (
  clockwise, 
  counter_clockwise); 
END_TYPE;

TYPE cross_sectional_constituent_element = SELECT (
  Cross_sectional_part_shape_element,
  Cross_sectional_group_shape_element);
END_TYPE;

ENTITY Cross_sectional_part_shape_element
  ABSTRACT SUPERTYPE OF (Cross_sectional_outer_part_shape_element ANDOR Cross_sectional_group_shape_element)
  SUBTYPE OF (Part_shape_element); -- or General_part_feature
  max_cross_section_diameter : OPTIONAL Length_data_element;
  min_cross_section_diameter : OPTIONAL Length_data_element;
  minimum_bend_radius : OPTIONAL Length_data_element;
END_ENTITY;

ENTITY Cross_sectional_outer_part_shape_element
  SUBTYPE OF (Cross_sectional_part_shape_element, General_part_feature); 
UNIQUE
  UR1: SELF\Shape_element.associated_definition;
END_ENTITY;

ENTITY Cross_sectional_outer_occurrence_feature
  SUBTYPE OF (Occurrence_shape_feature);
  SELF\Occurrence_shape_feature.definition : Cross_sectional_outer_part_shape_element;
END_ENTITY;

ENTITY Cross_sectional_group_shape_element
  SUPERTYPE OF ( ONEOF (Cross_sectional_group_shape_element_with_tubular_cover, Cross_sectional_group_shape_element_with_lacing, Twisted_cross_sectional_group_shape_element) )
  SUBTYPE OF (Cross_sectional_part_shape_element); 
  items : SET[1:?] OF cross_sectional_constituent_element; 
END_ENTITY;

ENTITY Cross_sectional_group_shape_element_with_tubular_cover 
  SUBTYPE OF (Cross_sectional_group_shape_element);
  cover : Occurrence_shape_feature; -- of the covering component;
END_ENTITY;

ENTITY Cross_sectional_group_shape_element_with_lacing
  SUBTYPE OF (Cross_sectional_group_shape_element);
  lacing_material : OPTIONAL Product_occurrence;
END_ENTITY;

ENTITY Twisted_cross_sectional_group_shape_element
  SUBTYPE OF (Cross_sectional_group_shape_element);
  twist_period : OPTIONAL Length_data_element;
  twist_direction : OPTIONAL twist_direction_enum;
END_ENTITY;

END_SCHEMA;
