(*
   $Id: arm.exp,v 1.6 2008/10/10 12:04:42 abhpf Exp $
   ISO TC184/SC4/WG12 N5848 - ISO/DIS 10303-1473 Description assignment - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4562
*)

SCHEMA Description_assignment_arm;

TYPE description_item = EXTENSIBLE GENERIC_ENTITY SELECT ;
END_TYPE;

ENTITY Description_text;
  description : STRING;
END_ENTITY;

ENTITY Description_text_assignment;
  description : Description_text;
  items : SET [1 : ?] OF description_item;
END_ENTITY;

END_SCHEMA;
