(*
   $Id: arm.exp,v 1.1 2011/06/04 18:02:53 lothartklein Exp $
   ISO TC184/SC4/WG12 N7924 - ISO/CD-TS - 10303-1813 Parametric representation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7361
*)
(* UNDER DEVELOPMENT *)
SCHEMA Parametric_representation_arm;

USE FROM Foundation_representation_arm; --  ISO/TS 10303-1006

ENTITY Definitional_representation
  SUBTYPE OF (Representation);
  SELF\Representation.context_of_items : Parametric_representation_context;
END_ENTITY; 

ENTITY Parametric_representation_context
  SUBTYPE OF (Representation_context);
END_ENTITY;

END_SCHEMA;
