(*
   $Id: mkmodule.js,v 1.46 2010/02/04 16:48:02 robbod Exp $
   N - ISO/CD-TS - 10303- parametric_representation - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA Parametric_representation_arm;

USE FROM Foundation_representation_arm; --  ISO/TS 10303-1006

ENTITY Definitional_representation
  SUBTYPE OF (Representation);
  SELF\Representation.context_of_items : Parametric_representation_context;
END_ENTITY; 

ENTITY Parametric_representation_context
  SUBTYPE OF (Representation_context);
END_ENTITY;

END_SCHEMA;
