(*
   $Id: mim.exp,v 1.6 2005/02/02 14:43:51 budreckytej Exp $
   ISO TC184/SC4/WG12 N3478 - ISO/CD-TS 10303-1695 Layered interconnect module 2d design - EXPRESS MIM
*)


SCHEMA Layered_interconnect_module_2d_design_mim;
	USE FROM Layered_interconnect_module_design_mim;	-- ISO/TS 10303-1698
	USE FROM Physical_unit_2d_shape_mim;	-- ISO/TS 10303-1726

RULE stratum_interconnect_module_planar_position_constraint FOR 
          (mapped_item);
WHERE
  WR1: SIZEOF(QUERY(mi <* mapped_item |
       (mi\representation_item.name = 
          'planar positioned stratum shape in interconnect module')
    AND NOT('LAYERED_INTERCONNECT_MODULE_2D_DESIGN_MIM.'
       + 'AXIS2_PLACEMENT_2D' IN TYPEOF(mi.mapping_target))
       )) = 0;
END_RULE;

RULE stratum_planar_shape_constraint FOR (shape_representation);
WHERE
  WR1: SIZEOF(QUERY(sr <* shape_representation |
       NOT( NOT ((sr\representation.name = 'planar projected shape') AND 
       (SIZEOF(QUERY(pdr <* USEDIN(sr,
       'LAYERED_INTERCONNECT_MODULE_2D_DESIGN_MIM.'
       + 'PROPERTY_DEFINITION_REPRESENTATION.USED_REPRESENTATION') |
       ('LAYERED_INTERCONNECT_MODULE_2D_DESIGN_MIM.'
       + 'STRATUM' IN TYPEOF(pdr.definition.definition))
       )) = 1))
       OR (SIZEOF(QUERY(a2p2d <* sr.items |
       ('LAYERED_INTERCONNECT_MODULE_2D_DESIGN_MIM.'
       + 'AXIS2_PLACEMENT_2D' IN TYPEOF(a2p2d))
       )) >= 0)))) = 0;
END_RULE;
	
END_SCHEMA;


