(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Physical component feature - EXPRESS ARM
*)

SCHEMA Physical_component_feature_arm; 

USE FROM Component_feature_arm;

  ENTITY Physical_component_feature
    SUBTYPE OF (Component_feature);
  END_ENTITY;

  ENTITY Physical_component_terminal
    ABSTRACT SUPERTYPE
    SUBTYPE OF (Component_terminal,
 			Physical_component_feature);
  END_ENTITY;

END_SCHEMA;
