(*
   $Id: arm.exp,v 1.11 2003/02/27 14:59:14 robbod Exp $
   ISO TC184/SC4/WG3  - ISO/CD-TS 10303-1293 Ap239 part definition information - EXPRESS ARM
*) 

SCHEMA Ap239_part_definition_information_arm;


  TYPE activity_or_activity_method_select = SELECT
    (activity,
     activity_method);
  END_TYPE; -- activity_or_activity_method_select

  TYPE alias_identification_item = SELECT
    (interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     approval_status,
     organization,
     security_classification,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition,
     requirement,
     requirement_version,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version_relationship,
     tracing_relationship,
     requirement_view_definition);
  END_TYPE; -- alias_identification_item

  TYPE any_number_value = NUMBER;
  END_TYPE; -- any_number_value

  TYPE any_string_value = STRING;
  END_TYPE; -- any_string_value

  TYPE ap239_dm_approval_item = SELECT
    (document_assignment);
  END_TYPE; -- ap239_dm_approval_item

  TYPE ap239_dm_classification_item = SELECT
    (applied_information_usage_right,
     content_item,
     descriptive_document_property,
     digital_document_definition,
     digital_file,
     document,
     document_assignment,
     document_definition_relationship,
     document_location_identification,
     document_property_representation,
     document_version,
     envelope,
     envelope_association,
     external_item_identification,
     external_source_identification,
     file_location_identification,
     file_relationship,
     hardcopy,
     information_right,
     information_usage_right,
     information_usage_right_relationship,
     message,
     message_association,
     numerical_document_property,
     partial_document_assignment,
     physical_document_definition);
  END_TYPE; -- ap239_dm_classification_item

  TYPE ap239_dm_classified_attribute_select = SELECT
    (content_item,
     descriptive_document_property,
     digital_file,
     document_assignment,
     document_definition_relationship,
     document_location_identification,
     document_property_representation,
     envelope,
     envelope_association,
     external_item_identification,
     external_source_identification,
     file_location_identification,
     file_relationship,
     hardcopy,
     information_right,
     information_usage_right,
     information_usage_right_relationship,
     message,
     message_association,
     numerical_document_property,
     partial_document_assignment);
  END_TYPE; -- ap239_dm_classified_attribute_select

  TYPE ap239_dm_contract_item = SELECT
    (message);
  END_TYPE; -- ap239_dm_contract_item

  TYPE ap239_dm_date_or_date_time_item = SELECT
    (document_assignment);
  END_TYPE; -- ap239_dm_date_or_date_time_item

  TYPE ap239_dm_documented_element_select = SELECT
    (certification,
     contract,
     identification_assignment,
     organization,
     person);
  END_TYPE; -- ap239_dm_documented_element_select

  TYPE ap239_dm_information_usage_right_item = SELECT
    (digital_document_definition,
     digital_file,
     document,
     document_definition_relationship,
     document_version,
     file_relationship,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- ap239_dm_information_usage_right_item

  TYPE ap239_dm_organization_or_person_in_organization = SELECT
    (document_assignment);
  END_TYPE; -- ap239_dm_organization_or_person_in_organization

  TYPE ap239_dm_security_classification_item = SELECT
    (document_assignment);
  END_TYPE; -- ap239_dm_security_classification_item

  TYPE ap239_dm_state_definition_of_item = SELECT
    (digital_document_definition,
     document,
     document_version,
     physical_document_definition);
  END_TYPE; -- ap239_dm_state_definition_of_item

  TYPE ap239_dm_state_of_item = SELECT
    (digital_document_definition,
     document,
     document_version,
     physical_document_definition);
  END_TYPE; -- ap239_dm_state_of_item

  TYPE ap239_dm_string_select = SELECT
    (envelope,
     envelope_association,
     information_right,
     information_usage_right,
     message,
     message_association,
     connector_on,
     interface_connector,
     interface_connector_definition,
     interface_connector_version,
     part,
     part_version,
     part_view_definition);
  END_TYPE; -- ap239_dm_string_select

  TYPE ap239_mri_alias_identification_item = SELECT
    (approval_status,
     organization,
     security_classification);
  END_TYPE; -- ap239_mri_alias_identification_item

  TYPE ap239_mri_classification_item = SELECT
    (address,
     address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     attribute_translation_assignment,
     calendar_date,
     certification,
     certification_assignment,
     contract,
     contract_assignment,
     date_or_date_time_assignment,
     date_time,
     identification_assignment,
     language,
     organization,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     security_classification,
     security_classification_assignment,
     activity_property,
     assigned_property,
     independent_property,
     property_representation,
     representation,
     representation_context,
     representation_item);
  END_TYPE; -- ap239_mri_classification_item

  TYPE ap239_mri_classified_attribute_select = SELECT
    (address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     certification,
     certification_assignment,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     language,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project_assignment,
     project_relationship,
     security_classification,
     activity_property,
     assigned_property,
     independent_property,
     property_representation,
     representation,
     representation_context,
     representation_item);
  END_TYPE; -- ap239_mri_classified_attribute_select

  TYPE ap239_mri_date_or_date_time_item = SELECT
    (alias_identification,
     identification_assignment);
  END_TYPE; -- ap239_mri_date_or_date_time_item

  TYPE ap239_mri_identification_item = SELECT
    (approval_status,
     organization,
     security_classification);
  END_TYPE; -- ap239_mri_identification_item

  TYPE ap239_padi_alias_identification_item = SELECT
    (interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_alias_identification_item

  TYPE ap239_padi_approval_item = SELECT
    (interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     product_design_to_individual,
     product_planned_to_realized);
  END_TYPE; -- ap239_padi_approval_item

  TYPE ap239_padi_certification_item = SELECT
    (interface_connection,
     interface_connector_version,
     interface_specification_version,
     part_version,
     product_as_planned,
     product_as_realized,
     product_version_relationship);
  END_TYPE; -- ap239_padi_certification_item

  TYPE ap239_padi_classification_item = SELECT
    (interface_connection,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_definition_for,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     market,
     part,
     part_version,
     part_view_definition,
     product,
     product_as_planned,
     product_as_realized,
     product_category,
     product_concept,
     product_design_to_individual,
     product_planned_to_realized,
     product_version,
     product_version_relationship,
     product_view_definition,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     supplied_part_relationship,
     tracing_relationship,
     view_definition_context);
  END_TYPE; -- ap239_padi_classification_item

  TYPE ap239_padi_classified_attribute_select = SELECT
    (interface_connection,
     interface_connector_definition,
     interface_specification_definition,
     market,
     part_view_definition,
     product_category,
     product_concept,
     product_version_relationship,
     requirement_version_relationship,
     requirement_view_definition,
     view_definition_context,
     view_definition_relationship);
  END_TYPE; -- ap239_padi_classified_attribute_select

  TYPE ap239_padi_contract_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_design,
     interface_connector_version,
     interface_specification_version,
     part_version,
     product_as_planned,
     product_as_realized,
     project);
  END_TYPE; -- ap239_padi_contract_item

  TYPE ap239_padi_date_and_time_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_date_and_time_item

  TYPE ap239_padi_documented_element_select = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     product_design_to_individual,
     product_planned_to_realized,
     product_version_relationship,
     product_view_definition);
  END_TYPE; -- ap239_padi_documented_element_select

  TYPE ap239_padi_identification_item = SELECT
    (interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_identification_item

  TYPE ap239_padi_information_usage_right_item = SELECT
    (interface_connection,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_information_usage_right_item

  TYPE ap239_padi_organization_or_person_in_organization = SELECT
    (alias_identification,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_organization_or_person_in_organization

  TYPE ap239_padi_project_item = SELECT
    (product_concept);
  END_TYPE; -- ap239_padi_project_item

  TYPE ap239_padi_property_assignment_select = SELECT
    (part_view_definition);
  END_TYPE; -- ap239_padi_property_assignment_select

  TYPE ap239_padi_requirement_assignment_item = SELECT
    (document_version,
     interface_specification,
     part_version,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_requirement_assignment_item

  TYPE ap239_padi_requirement_source_item = SELECT
    (document_version);
  END_TYPE; -- ap239_padi_requirement_source_item

  TYPE ap239_padi_security_classification_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- ap239_padi_security_classification_item

  TYPE ap239_padi_state_definition_of_item = SELECT
    (certification,
     connector_on,
     contract,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     organization,
     part,
     part_version,
     part_view_definition,
     person_in_organization,
     product_as_planned,
     product_as_realized,
     product_category,
     project,
     security_classification);
  END_TYPE; -- ap239_padi_state_definition_of_item

  TYPE ap239_padi_state_of_item = SELECT
    (certification,
     connector_on,
     contract,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     organization,
     part,
     part_version,
     part_view_definition,
     person_in_organization,
     product_as_planned,
     product_as_realized,
     project,
     security_classification);
  END_TYPE; -- ap239_padi_state_of_item

  TYPE ap239_padi_string_select = SELECT
    (envelope,
     envelope_association,
     information_right,
     information_usage_right,
     message,
     message_association,
     connector_on,
     interface_connector,
     interface_connector_definition,
     interface_connector_version,
     part,
     part_version,
     part_view_definition);
  END_TYPE; -- ap239_padi_string_select

  TYPE ap239_props_ap239_mri_classification_item = SELECT
    (address,
     address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     attribute_translation_assignment,
     calendar_date,
     certification,
     certification_assignment,
     contract,
     contract_assignment,
     date_or_date_time_assignment,
     date_time,
     identification_assignment,
     language,
     organization,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     security_classification,
     security_classification_assignment,
     activity_property,
     assigned_property,
     independent_property,
     property_representation,
     representation,
     representation_context,
     representation_item);
  END_TYPE; -- ap239_props_ap239_mri_classification_item

  TYPE ap239_props_ap239_mri_classified_attribute_select = SELECT
    (address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     certification,
     certification_assignment,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     language,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project_assignment,
     project_relationship,
     security_classification,
     activity_property,
     assigned_property,
     independent_property,
     property_representation,
     representation,
     representation_context,
     representation_item);
  END_TYPE; -- ap239_props_ap239_mri_classified_attribute_select

  TYPE ap239_props_mri_approval_item = SELECT
    (certification,
     contract,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship);
  END_TYPE; -- ap239_props_mri_approval_item

  TYPE ap239_props_mri_date_or_date_time_item = SELECT
    (certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation);
  END_TYPE; -- ap239_props_mri_date_or_date_time_item

  TYPE ap239_props_mri_identification_item = SELECT
    (contract,
     organization,
     security_classification,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship);
  END_TYPE; -- ap239_props_mri_identification_item

  TYPE ap239_props_mri_organization_or_person_in_organization_item =
 SELECT
    (contract,
     identification_assignment,
     security_classification_assignment,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation);
  END_TYPE; -- ap239_props_mri_organization_or_person_in_organization_item

  TYPE ap239_props_mri_string_select = SELECT
    (approval,
     approval_relationship,
     approval_status,
     certification,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation_item);
  END_TYPE; -- ap239_props_mri_string_select

  TYPE approval_item = SELECT
    (interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     product_design_to_individual,
     product_planned_to_realized,
     document_assignment,
     certification,
     contract,
     envelope,
     message);
  END_TYPE; -- approval_item

  TYPE assigned_document_select = SELECT
    (document,
     document_definition,
     document_version,
     file);
  END_TYPE; -- assigned_document_select

  TYPE assigned_name_select = SELECT
    (external_class_library);
  END_TYPE; -- assigned_name_select

  TYPE associated_date_time = SELECT
    (condition);
  END_TYPE; -- associated_date_time

  TYPE associated_organization_or_person = SELECT
    (condition);
  END_TYPE; -- associated_organization_or_person

  TYPE certification_item = SELECT
    (interface_connection,
     interface_connector_version,
     interface_specification_version,
     part_version,
     product_as_planned,
     product_as_realized,
     product_version_relationship);
  END_TYPE; -- certification_item

  TYPE classification_item = SELECT
    (interface_connection,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_definition_for,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     market,
     part,
     part_version,
     part_view_definition,
     product,
     product_as_planned,
     product_as_realized,
     product_category,
     product_concept,
     product_design_to_individual,
     product_planned_to_realized,
     product_version,
     product_version_relationship,
     product_view_definition,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     supplied_part_relationship,
     tracing_relationship,
     view_definition_context,
     applied_information_usage_right,
     content_item,
     descriptive_document_property,
     digital_document_definition,
     digital_file,
     document,
     document_assignment,
     document_definition_relationship,
     document_location_identification,
     document_property_representation,
     document_version,
     envelope,
     envelope_association,
     external_item_identification,
     external_source_identification,
     file_location_identification,
     file_relationship,
     hardcopy,
     information_right,
     information_usage_right,
     information_usage_right_relationship,
     message,
     message_association,
     numerical_document_property,
     partial_document_assignment,
     physical_document_definition,
     address,
     address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     attribute_translation_assignment,
     calendar_date,
     certification,
     certification_assignment,
     contract,
     contract_assignment,
     date_or_date_time_assignment,
     date_time,
     identification_assignment,
     language,
     organization,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     security_classification,
     security_classification_assignment,
     applied_state_definition_assignment,
     state_definition,
     state_definition_relationship,
     applied_state_assignment,
     state,
     state_relationship);
  END_TYPE; -- classification_item

  TYPE classified_attribute_select = SELECT
    (interface_connection,
     interface_connector_definition,
     interface_specification_definition,
     market,
     part_view_definition,
     product_category,
     product_concept,
     product_version_relationship,
     requirement_version_relationship,
     requirement_view_definition,
     view_definition_context,
     view_definition_relationship,
     content_item,
     descriptive_document_property,
     digital_file,
     document_assignment,
     document_definition_relationship,
     document_location_identification,
     document_property_representation,
     envelope,
     envelope_association,
     external_item_identification,
     external_source_identification,
     file_location_identification,
     file_relationship,
     hardcopy,
     information_right,
     information_usage_right,
     information_usage_right_relationship,
     message,
     message_association,
     numerical_document_property,
     partial_document_assignment,
     address_assignment,
     approval,
     approval_assignment,
     approval_relationship,
     approval_status,
     approving_person_organization,
     certification,
     certification_assignment,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     language,
     organization_or_person_in_organization_assignment,
     organization_relationship,
     person_in_organization,
     project_assignment,
     project_relationship,
     security_classification);
  END_TYPE; -- classified_attribute_select

  TYPE component_item = SELECT
    (product_view_definition);
  END_TYPE; -- component_item

  TYPE condition_item = SELECT
    (state_definition,
     state_definition_relationship);
  END_TYPE; -- condition_item

  TYPE connector_on_item = SELECT
    (product_view_definition,
     view_definition_relationship);
  END_TYPE; -- connector_on_item

  TYPE contract_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_design,
     interface_connector_version,
     interface_specification_version,
     part_version,
     product_as_planned,
     product_as_realized,
     project,
     message,
     document_version,
     information_usage_right,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- contract_item

  TYPE date_or_date_time_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     document_assignment,
     alias_identification,
     identification_assignment,
     certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     envelope,
     message,
     condition);
  END_TYPE; -- date_or_date_time_item

  TYPE date_or_date_time_select = SELECT
    (calendar_date,
     date_time);
  END_TYPE; -- date_or_date_time_select

  TYPE date_or_event = SELECT
    (calendar_date,
     date_time,
     event);
  END_TYPE; -- date_or_event

  TYPE day_in_month_number = INTEGER;
  WHERE
    wr1: ((1 <= SELF) AND (SELF <= 31));
  END_TYPE; -- day_in_month_number

  TYPE descriptive_or_numerical = SELECT
    (descriptive_document_property,
     numerical_document_property);
  END_TYPE; -- descriptive_or_numerical

  TYPE document_location_select = SELECT
    (document_definition);
  END_TYPE; -- document_location_select

  TYPE document_management_alias_identification_item = SELECT
    (digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- document_management_alias_identification_item

  TYPE document_management_approval_item = SELECT
    (certification,
     contract,
     digital_document_definition,
     document_definition_relationship,
     document_version,
     physical_document_definition);
  END_TYPE; -- document_management_approval_item

  TYPE document_management_contract_item = SELECT
    (document_version);
  END_TYPE; -- document_management_contract_item

  TYPE document_management_date_or_date_time_item = SELECT
    (certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     digital_document_definition,
     digital_file,
     document_definition_relationship,
     document_version,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- document_management_date_or_date_time_item

  TYPE document_management_identification_item = SELECT
    (contract,
     organization,
     security_classification,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- document_management_identification_item

  TYPE document_management_person_and_organization_item = SELECT
    (contract,
     identification_assignment,
     security_classification_assignment,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- document_management_person_and_organization_item

  TYPE document_management_security_classification_item = SELECT
    (digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- document_management_security_classification_item

  TYPE document_management_string_select = SELECT
    (approval,
     approval_relationship,
     approval_status,
     certification,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     digital_document_definition,
     document,
     document_assignment,
     document_definition_relationship,
     document_version,
     external_item_identification,
     external_source_identification,
     file_relationship,
     physical_document_definition,
     product_category);
  END_TYPE; -- document_management_string_select

  TYPE document_property_item = SELECT
    (document_definition,
     file);
  END_TYPE; -- document_property_item

  TYPE documented_element_select = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_design,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_planned_to_realized,
     interface_connector_version,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     product_design_to_individual,
     product_planned_to_realized,
     product_version_relationship,
     product_view_definition,
     certification,
     contract,
     identification_assignment,
     organization,
     person);
  END_TYPE; -- documented_element_select

  TYPE envelope_approval_select = SELECT
    (envelope);
  END_TYPE; -- envelope_approval_select

  TYPE envelope_date_time_select = SELECT
    (envelope);
  END_TYPE; -- envelope_date_time_select

  TYPE envelope_person_organization_select = SELECT
    (envelope);
  END_TYPE; -- envelope_person_organization_select

  TYPE envelope_property_select = SELECT
    (envelope);
  END_TYPE; -- envelope_property_select

  TYPE external_class_assigned_name_select = SELECT
    (external_class_library);
  END_TYPE; -- external_class_assigned_name_select

  TYPE external_identification_item = SELECT
    (document_definition,
     file);
  END_TYPE; -- external_identification_item

  TYPE hour_in_day = INTEGER;
  WHERE
    wr1: ((0 <= SELF) AND (SELF < 24));
  END_TYPE; -- hour_in_day

  TYPE identification = SELECT
    (condition);
  END_TYPE; -- identification

  TYPE identification_item = SELECT
    (interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     approval_status,
     contract,
     organization,
     security_classification,
     state_definition,
     state_definition_relationship,
     product_as_individual,
     requirement,
     requirement_version,
     requirement_view_definition,
     condition);
  END_TYPE; -- identification_item

  TYPE information_usage_right_item = SELECT
    (interface_connection,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     digital_document_definition,
     digital_file,
     document,
     document_definition_relationship,
     document_version,
     file_relationship,
     hardcopy,
     physical_document_definition);
  END_TYPE; -- information_usage_right_item

  TYPE length_measure = NUMBER;
  END_TYPE; -- length_measure

  TYPE limit_qualifier_list = ENUMERATION OF
    (minimum,
     maximum);
  END_TYPE; -- limit_qualifier_list

  TYPE located_select = SELECT
    (file);
  END_TYPE; -- located_select

  TYPE measure_value = SELECT
    (any_number_value,
     any_string_value,
     length_measure);
  END_TYPE; -- measure_value

  TYPE message_approval_select = SELECT
    (message);
  END_TYPE; -- message_approval_select

  TYPE message_date_time_select = SELECT
    (message);
  END_TYPE; -- message_date_time_select

  TYPE message_definer_select = SELECT
    (organization,
     person_in_organization);
  END_TYPE; -- message_definer_select

  TYPE message_security_classification_select = SELECT
    (message);
  END_TYPE; -- message_security_classification_select

  TYPE message_state_select = SELECT
    (message);
  END_TYPE; -- message_state_select

  TYPE minute_in_hour = INTEGER;
  WHERE
    wr1: ((0 <= SELF) AND (SELF <= 59));
  END_TYPE; -- minute_in_hour

  TYPE month_in_year_number = INTEGER;
  WHERE
    wr1: ((1 <= SELF) AND (SELF <= 12));
  END_TYPE; -- month_in_year_number

  TYPE mri_approval_item = SELECT
    (certification,
     contract,
     digital_document_definition,
     document_definition_relationship,
     document_version,
     physical_document_definition,
     applied_information_usage_right,
     information_usage_right,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- mri_approval_item

  TYPE mri_date_or_date_time_item = SELECT
    (certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     digital_document_definition,
     digital_file,
     document_definition_relationship,
     document_version,
     hardcopy,
     physical_document_definition,
     information_usage_right,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- mri_date_or_date_time_item

  TYPE mri_identification_item = SELECT
    (contract,
     organization,
     security_classification,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- mri_identification_item

  TYPE mri_organization_or_person_in_organization_item = SELECT
    (contract,
     identification_assignment,
     security_classification_assignment,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition,
     information_usage_right,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- mri_organization_or_person_in_organization_item

  TYPE mri_string_select = SELECT
    (approval,
     approval_relationship,
     approval_status,
     certification,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     digital_document_definition,
     document,
     document_assignment,
     document_definition_relationship,
     document_version,
     external_item_identification,
     external_source_identification,
     file_relationship,
     physical_document_definition,
     product_category,
     activity_property,
     assigned_property,
     independent_property,
     independent_property_relationship,
     representation_item,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- mri_string_select

  TYPE offset_orientation = ENUMERATION OF
    (ahead,
     exact,
     behind);
  END_TYPE; -- offset_orientation

  TYPE organization_or_person_in_organization_item = SELECT
    (alias_identification,
     interface_connector,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     part,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     document_assignment,
     contract,
     identification_assignment,
     security_classification_assignment,
     envelope,
     condition);
  END_TYPE; -- organization_or_person_in_organization_item

  TYPE organization_or_person_in_organization_select = SELECT
    (organization,
     person_in_organization);
  END_TYPE; -- organization_or_person_in_organization_select

  TYPE product_as_individual_identification_item = SELECT
    (product_as_individual);
  END_TYPE; -- product_as_individual_identification_item

  TYPE product_property_assignment = SELECT
    (product_view_definition,
     view_definition_relationship);
  END_TYPE; -- product_property_assignment

  TYPE project_item = SELECT
    (product_concept);
  END_TYPE; -- project_item

  TYPE property_assignment_select = SELECT
    (part_view_definition,
     document_definition,
     file,
     envelope,
     state_definition,
     state_definition_relationship,
     requirement_assignment,
     product_view_definition,
     view_definition_relationship);
  END_TYPE; -- property_assignment_select

  TYPE property_value_qualifier = ENUMERATION OF
    (nominal,
     specified,
     typical);
  END_TYPE; -- property_value_qualifier

  TYPE requirement_alias_idenfication_item = SELECT
    (requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version_relationship,
     tracing_relationship);
  END_TYPE; -- requirement_alias_idenfication_item

  TYPE requirement_assignment_item = SELECT
    (document_version,
     interface_specification,
     part_version,
     product_as_planned,
     product_as_realized);
  END_TYPE; -- requirement_assignment_item

  TYPE requirement_assignment_property_assignment_select = SELECT
    (requirement_assignment);
  END_TYPE; -- requirement_assignment_property_assignment_select

  TYPE requirement_contract_item = SELECT
    (requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_contract_item

  TYPE requirement_identification_and_version_alias_identification_item =
              SELECT
    (requirement,
     requirement_version);
  END_TYPE; -- requirement_identification_and_version_alias_identification_item

  TYPE requirement_identification_and_version_identification_item =
              SELECT
    (requirement,
     requirement_version);
  END_TYPE; -- requirement_identification_and_version_identification_item

  TYPE requirement_mri_approval_item = SELECT
    (certification,
     contract,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_mri_approval_item

  TYPE requirement_mri_date_or_date_time_item = SELECT
    (certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_mri_date_or_date_time_item

  TYPE requirement_mri_identification_item = SELECT
    (contract,
     organization,
     security_classification,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_mri_identification_item

  TYPE requirement_mri_organization_or_person_in_organization_item =
              SELECT
    (contract,
     identification_assignment,
     security_classification_assignment,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_mri_organization_or_person_in_organization_item

  TYPE requirement_mri_string_select = SELECT
    (approval,
     approval_relationship,
     approval_status,
     certification,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_mri_string_select

  TYPE requirement_security_classification_item = SELECT
    (requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- requirement_security_classification_item

  TYPE requirement_source_item = SELECT
    (document_version);
  END_TYPE; -- requirement_source_item

  TYPE requirement_view_definition_alias_identification_item = SELECT
    (requirement_view_definition);
  END_TYPE; -- requirement_view_definition_alias_identification_item

  TYPE requirement_view_definition_identification_item = SELECT
    (requirement_view_definition);
  END_TYPE; -- requirement_view_definition_identification_item

  TYPE right_approval_item = SELECT
    (certification,
     contract,
     applied_information_usage_right,
     information_usage_right);
  END_TYPE; -- right_approval_item

  TYPE right_contract_item = SELECT
    (information_usage_right);
  END_TYPE; -- right_contract_item

  TYPE right_date_item = SELECT
    (certification,
     contract,
     organization_or_person_in_organization_assignment,
     security_classification_assignment,
     information_usage_right);
  END_TYPE; -- right_date_item

  TYPE right_person_organization_item = SELECT
    (contract,
     identification_assignment,
     security_classification_assignment,
     information_usage_right);
  END_TYPE; -- right_person_organization_item

  TYPE second_in_minute = REAL;
  WHERE
    wr1: ((0 <= SELF) AND (SELF <= 60));
  END_TYPE; -- second_in_minute

  TYPE security_classification_item = SELECT
    (interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification_definition,
     interface_specification_version,
     part_version,
     part_view_definition,
     product_as_planned,
     product_as_realized,
     document_assignment,
     digital_document_definition,
     digital_file,
     document,
     document_version,
     hardcopy,
     physical_document_definition,
     message,
     requirement,
     requirement_assignment,
     requirement_collection_relationship,
     requirement_source,
     requirement_version,
     requirement_version_relationship,
     requirement_view_definition,
     tracing_relationship);
  END_TYPE; -- security_classification_item

  TYPE state_classified_item = SELECT
    (applied_state_assignment,
     state,
     state_relationship);
  END_TYPE; -- state_classified_item

  TYPE state_definition_classified_select = SELECT
    (applied_state_definition_assignment,
     state_definition,
     state_definition_relationship);
  END_TYPE; -- state_definition_classified_select

  TYPE state_definition_condition = SELECT
    (state_definition,
     state_definition_relationship);
  END_TYPE; -- state_definition_condition

  TYPE state_definition_identification_item = SELECT
    (state_definition,
     state_definition_relationship);
  END_TYPE; -- state_definition_identification_item

  TYPE state_definition_of_item = SELECT
    (certification,
     connector_on,
     contract,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     organization,
     part,
     part_version,
     part_view_definition,
     person_in_organization,
     product_as_planned,
     product_as_realized,
     product_category,
     project,
     security_classification,
     digital_document_definition,
     document,
     document_version,
     physical_document_definition);
  END_TYPE; -- state_definition_of_item

  TYPE state_definition_property_assignment = SELECT
    (state_definition,
     state_definition_relationship);
  END_TYPE; -- state_definition_property_assignment

  TYPE state_of_item = SELECT
    (certification,
     connector_on,
     contract,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_version,
     interface_specification,
     interface_specification_definition,
     interface_specification_version,
     organization,
     part,
     part_version,
     part_view_definition,
     person_in_organization,
     product_as_planned,
     product_as_realized,
     project,
     security_classification,
     digital_document_definition,
     document,
     document_version,
     physical_document_definition,
     message);
  END_TYPE; -- state_of_item

  TYPE string_select = SELECT
    (envelope,
     envelope_association,
     information_right,
     information_usage_right,
     message,
     message_association,
     approval,
     approval_relationship,
     approval_status,
     certification,
     contract,
     date_or_date_time_assignment,
     identification_assignment,
     organization_relationship,
     person_in_organization,
     project,
     project_assignment,
     project_relationship);
  END_TYPE; -- string_select

  TYPE year_number = INTEGER;
  END_TYPE; -- year_number

  ENTITY activity;
      chosen_method : activity_method;
      description   : OPTIONAL STRING;
      id            : STRING;
      name          : STRING;
  END_ENTITY; -- activity

  ENTITY activity_method;
      consequence : OPTIONAL STRING;
      description : OPTIONAL STRING;
      name        : STRING;
      purpose     : STRING;
  END_ENTITY; -- activity_method

  ENTITY activity_property;
      described_element : activity_or_activity_method_select;
      name              : STRING;
      description       : STRING;
  END_ENTITY; -- activity_property

  ENTITY activity_property_representation;
      description : OPTIONAL STRING;
      property    : activity_property;
      rep         : representation;
      role        : STRING;
  END_ENTITY; -- activity_property_representation

  ENTITY activity_relationship;
      description       : OPTIONAL STRING;
      name              : STRING;
      related_activity  : activity;
      relating_activity : activity;
  END_ENTITY; -- activity_relationship

  ENTITY activity_status;
      assigned_activity : activity;
      status            : STRING;
  END_ENTITY; -- activity_status

  ENTITY address;
      street_number           : OPTIONAL STRING;
      street                  : OPTIONAL STRING;
      postal_box              : OPTIONAL STRING;
      town                    : OPTIONAL STRING;
      region                  : OPTIONAL STRING;
      postal_code             : OPTIONAL STRING;
      country                 : OPTIONAL STRING;
      internal_location       : OPTIONAL STRING;
      facsimile_number        : OPTIONAL STRING;
      telephone_number        : OPTIONAL STRING;
      electronic_mail_address : OPTIONAL STRING;
      telex_number            : OPTIONAL STRING;
      url                     : OPTIONAL STRING;
      name                    : OPTIONAL STRING;
    WHERE
      wr1: (EXISTS(street_number) OR EXISTS(street) OR EXISTS(postal_box) 
               OR EXISTS(town) OR EXISTS(region) OR EXISTS(postal_code) OR 
               EXISTS(country) OR EXISTS(internal_location) OR EXISTS(
               facsimile_number) OR EXISTS(telephone_number) OR EXISTS(
               electronic_mail_address) OR EXISTS(telex_number));
  END_ENTITY; -- address

  ENTITY address_assignment;
      assigned_address             : address;
      address_type                 : OPTIONAL STRING;
      located_person_organizations : SET [1:?] OF organization_or_person_in_organization_select;
  END_ENTITY; -- address_assignment

  ENTITY alias_identification
    SUBTYPE OF (identification_assignment);
    DERIVE
      SELF\identification_assignment.role : STRING := 'alias';
    WHERE
      wr1: (SIZEOF(QUERY ( item <* SELF\identification_assignment.items | 
               (NOT ('AP239_PART_DEFINITION_INFORMATION_ARM.ALIAS_IDENTIFICATION_ITEM' 
               IN TYPEOF(item))) )) = 0);
  END_ENTITY; -- alias_identification

  ENTITY amount_of_substance_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- amount_of_substance_unit

  ENTITY and_state_cause_effect_definition
    SUBTYPE OF (state_cause_effect_definition);
  END_ENTITY; -- and_state_cause_effect_definition

  ENTITY applied_independent_activity_property
    SUBTYPE OF (activity_property);
      base_element_property : independent_property;
    DERIVE
      SELF\activity_property.name : STRING := base_element_property.
                                       property_type;
  END_ENTITY; -- applied_independent_activity_property

  ENTITY applied_independent_property
    SUBTYPE OF (assigned_property);
      base_independent_property : independent_property;
    DERIVE
      SELF\assigned_property.name : STRING := base_independent_property.
                                       property_type;
  END_ENTITY; -- applied_independent_property

  ENTITY applied_information_usage_right;
      item          : SET [1:?] OF information_usage_right_item;
      right_applied : information_usage_right;
  END_ENTITY; -- applied_information_usage_right

  ENTITY applied_state_assignment;
      described_state : state;
      assigned_to     : state_of_item;
      role            : state_role;
  END_ENTITY; -- applied_state_assignment

  ENTITY applied_state_definition_assignment;
      described_state_definition : state_definition;
      assigned_to                : state_definition_of_item;
      role                       : state_definition_role;
  END_ENTITY; -- applied_state_definition_assignment

  ENTITY approval;
      status       : approval_status;
      purpose      : STRING;
      planned_date : OPTIONAL date_or_date_time_select;
      actual_date  : OPTIONAL date_or_date_time_select;
  END_ENTITY; -- approval

  ENTITY approval_assignment;
      assigned_approval : approval;
      items             : SET [1:?] OF approval_item;
      role              : OPTIONAL STRING;
  END_ENTITY; -- approval_assignment

  ENTITY approval_relationship;
      relation_type     : STRING;
      relating_approval : approval;
      related_approval  : approval;
      description       : OPTIONAL STRING;
  END_ENTITY; -- approval_relationship

  ENTITY approval_status;
      status_name : STRING;
  END_ENTITY; -- approval_status

  ENTITY approving_person_organization;
      person_organization : organization_or_person_in_organization_select;
      approval_date       : OPTIONAL date_or_date_time_select;
      authorized_approval : approval;
      role                : OPTIONAL STRING;
  END_ENTITY; -- approving_person_organization

  ENTITY assigned_document_property
    SUBTYPE OF (assigned_property);
    DERIVE
      SELF\assigned_property.name : STRING := 'document property';
    UNIQUE
      ur1 : described_element;
    WHERE
      wr1: (SIZEOF([
               'AP239_PART_DEFINITION_INFORMATION_ARM.DOCUMENT_DEFINITION',
               'AP239_PART_DEFINITION_INFORMATION_ARM.FILE'] * TYPEOF(SELF\
               assigned_property.described_element)) = 1);
  END_ENTITY; -- assigned_document_property

  ENTITY assigned_property;
      described_element : property_assignment_select;
      description       : OPTIONAL STRING;
      id                : OPTIONAL STRING;
      name              : STRING;
  END_ENTITY; -- assigned_property

  ENTITY attribute_classification;
      allowed_value     : class;
      attribute_name    : STRING;
      classified_entity : classified_attribute_select;
  END_ENTITY; -- attribute_classification

  ENTITY attribute_translation_assignment;
      considered_instances : SET [1:?] OF string_select;
      considered_attribute : STRING;
      translation_text     : STRING;
      translation_language : language;
    WHERE
      wr1: (SIZEOF(QUERY ( ci <* considered_instances | (SIZEOF(
               QUERY ( ata <* USEDIN(ci,'AP239_PART_DEFINITION_INFORMATION_ARM.ATTRIBUTE_TRANSLATION_ASSIGNMENT.CONSIDERED_INSTANCES')
                | ((ata.considered_attribute = considered_attribute) AND (
               ata.translation_language :=: translation_language)) )) > 1) )) 
               = 0);
  END_ENTITY; -- attribute_translation_assignment

  ENTITY binary_generic_expression
    ABSTRACT SUPERTYPE
    SUBTYPE OF (generic_expression);
      operands : LIST [2:2] OF generic_expression;
  END_ENTITY; -- binary_generic_expression

  ENTITY calendar_date;
      year_component  : year_number;
      month_component : month_in_year_number;
      day_component   : day_in_month_number;
  END_ENTITY; -- calendar_date

  ENTITY certification;
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- certification

  ENTITY certification_assignment;
      assigned_certification : certification;
      role                   : STRING;
      items                  : SET [1:?] OF certification_item;
  END_ENTITY; -- certification_assignment

  ENTITY class
    SUPERTYPE OF (ONEOF (class_by_extension,class_by_intension));
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- class

  ENTITY class_by_extension
    SUBTYPE OF (class);
  END_ENTITY; -- class_by_extension

  ENTITY class_by_intension
    SUBTYPE OF (class);
  END_ENTITY; -- class_by_intension

  ENTITY classification_assignment;
      assigned_class : class;
      items          : SET [1:?] OF classification_item;
      role           : OPTIONAL STRING;
  END_ENTITY; -- classification_assignment

  ENTITY complement;
      id          : STRING;
      name        : STRING;
      description : STRING;
      set_1       : class;
      set_2       : class;
      universe    : class;
  END_ENTITY; -- complement

  ENTITY composition_of_state
    SUBTYPE OF (state_relationship);
      SELF\state_relationship.relating : state;
      SELF\state_relationship.related  : state;
    DERIVE
      part  : state := SELF\composition_of_state.related;
      whole : state := SELF\composition_of_state.relating;
  END_ENTITY; -- composition_of_state

  ENTITY composition_of_state_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      part  : state_definition := SELF\composition_of_state_definition.
                 related;
      whole : state_definition := SELF\composition_of_state_definition.
                 relating;
  END_ENTITY; -- composition_of_state_definition

  ENTITY condition
    SUBTYPE OF (logical_expression);
      descriptive_definition : OPTIONAL STRING;
      title                  : STRING;
  END_ENTITY; -- condition

  ENTITY condition_assignment
    SUPERTYPE OF (ONEOF (condition_context,condition_scope));
      condition : condition;
      item      : condition_item;
      role      : STRING;
  END_ENTITY; -- condition_assignment

  ENTITY condition_context
    SUBTYPE OF (condition_assignment);
  END_ENTITY; -- condition_context

  ENTITY condition_scope
    SUBTYPE OF (condition_assignment);
  END_ENTITY; -- condition_scope

  ENTITY connector_on;
      connector   : interface_connector_definition;
      description : OPTIONAL STRING;
      id          : STRING;
      item        : connector_on_item;
      name        : STRING;
  END_ENTITY; -- connector_on

  ENTITY content_item;
      item_identifier : STRING;
      item_type       : STRING;
      access_comment  : OPTIONAL STRING;
  END_ENTITY; -- content_item

  ENTITY context_dependent_unit
    SUBTYPE OF (unit);
    WHERE
      wr1: EXISTS(SELF\unit.name);
  END_ENTITY; -- context_dependent_unit

  ENTITY contract;
      id      : STRING;
      purpose : STRING;
      kind    : STRING;
  END_ENTITY; -- contract

  ENTITY contract_assignment;
      assigned_contract : contract;
      items             : SET [1:?] OF contract_item;
  END_ENTITY; -- contract_assignment

  ENTITY conversion_based_unit
    SUBTYPE OF (unit);
      conversion_factor : value_with_unit;
    WHERE
      wr1: EXISTS(SELF\unit.name);
  END_ENTITY; -- conversion_based_unit

  ENTITY date_or_date_time_assignment;
      assigned_date : date_or_date_time_select;
      role          : STRING;
      items         : SET [1:?] OF date_or_date_time_item;
  END_ENTITY; -- date_or_date_time_assignment

  ENTITY date_time;
      date_component : calendar_date;
      time_component : local_time;
  END_ENTITY; -- date_time

  ENTITY defined_state_relationship;
      name             : STRING;
      description      : OPTIONAL STRING;
      definitive_state : state_assertion;
      defined_state    : state_assessment;
  END_ENTITY; -- defined_state_relationship

  ENTITY derived_unit
    SUBTYPE OF (unit);
      elements : SET [1:?] OF derived_unit_element;
  END_ENTITY; -- derived_unit

  ENTITY derived_unit_element;
      base_unit : unit;
      exponent  : REAL;
  END_ENTITY; -- derived_unit_element

  ENTITY descriptive_document_property
    SUBTYPE OF (string_representation_item);
    INVERSE
      valued_characteristic : SET [1:1] OF
                                  document_property_representation FOR 
                                 items;
  END_ENTITY; -- descriptive_document_property

  ENTITY digital_document_definition
    SUBTYPE OF (document_definition);
      files : SET [0:?] OF digital_file;
  END_ENTITY; -- digital_document_definition

  ENTITY digital_file
    SUBTYPE OF (file);
  END_ENTITY; -- digital_file

  ENTITY document
    SUBTYPE OF (product);
  END_ENTITY; -- document

  ENTITY document_assignment;
      assigned_document : assigned_document_select;
      is_assigned_to    : documented_element_select;
      role              : STRING;
  END_ENTITY; -- document_assignment

  ENTITY document_definition
    ABSTRACT SUPERTYPE OF (ONEOF (digital_document_definition,
        physical_document_definition));
      id                          : STRING;
      description                 : OPTIONAL STRING;
      associated_document_version : document_version;
  END_ENTITY; -- document_definition

  ENTITY document_definition_relationship;
      relation_type                : STRING;
      description                  : OPTIONAL STRING;
      relating_document_definition : document_definition;
      related_document_definition  : document_definition;
    WHERE
      wr1: (relating_document_definition :<>: related_document_definition);
  END_ENTITY; -- document_definition_relationship

  ENTITY document_location_identification
    SUBTYPE OF (external_source_identification);
    WHERE
      wr1: ('AP239_PART_DEFINITION_INFORMATION_ARM.DOCUMENT_DEFINITION' IN
                TYPEOF(SELF\external_source_identification.item));
  END_ENTITY; -- document_location_identification

  ENTITY document_property_representation
    SUBTYPE OF (representation);
      SELF\representation.items : SET [1:?] OF descriptive_or_numerical;
    WHERE
      wr1: (SIZEOF(QUERY ( pr <* USEDIN(SELF,'AP239_PART_DEFINITION_INFORMATION_ARM.PROPERTY_REPRESENTATION.REP')
                | (
               'AP239_PART_DEFINITION_INFORMATION_ARM.ASSIGNED_PROPERTY' IN
                TYPEOF(pr.property)) )) > 0);
      wr2: (SELF\representation.context_of_items.kind = 
               'document parameters');
      wr3: valid_document_property_representation(SELF);
      wr4: (SIZEOF(QUERY ( it1 <* SELF\representation.items | (SIZEOF(
               QUERY ( it2 <* SELF\representation.items | (it1.name = it2.
               name) )) > 1) )) = 0);
  END_ENTITY; -- document_property_representation

  ENTITY document_version
    SUBTYPE OF (product_version);
      SELF\product_version.of_product : document;
  END_ENTITY; -- document_version

  ENTITY duration
    SUBTYPE OF (value_with_unit);
    WHERE
      wr1: (('AP239_PART_DEFINITION_INFORMATION_ARM.' + 'TIME_UNIT') IN 
               TYPEOF(SELF\value_with_unit.unit));
  END_ENTITY; -- duration

  ENTITY electric_current_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- electric_current_unit

  ENTITY envelope;
      acknowledge : OPTIONAL STRING;
      id          : STRING;
      wrapping    : OPTIONAL message;
  END_ENTITY; -- envelope

  ENTITY envelope_association;
      related  : envelope;
      relating : envelope;
      role     : OPTIONAL STRING;
  END_ENTITY; -- envelope_association

  ENTITY event;
      id                 : STRING;
      name               : STRING;
      description        : OPTIONAL STRING;
      planned_start_date : OPTIONAL date_or_date_time_select;
      actual_start_date  : OPTIONAL date_or_date_time_select;
  END_ENTITY; -- event

  ENTITY event_relationship;
      relation_type : STRING;
      event1        : event;
      event2        : event;
      description   : OPTIONAL STRING;
  END_ENTITY; -- event_relationship

  ENTITY expression
    ABSTRACT SUPERTYPE
    SUBTYPE OF (generic_expression);
  END_ENTITY; -- expression

  ENTITY external_class
    SUBTYPE OF (class);
      external_source : external_class_library;
  END_ENTITY; -- external_class

  ENTITY external_class_library;
      id          : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- external_class_library

  ENTITY external_item_identification
    SUBTYPE OF (external_source_identification);
      external_id : STRING;
  END_ENTITY; -- external_item_identification

  ENTITY external_source_identification;
      source_id   : STRING;
      source_type : STRING;
      item        : external_identification_item;
      description : OPTIONAL STRING;
  END_ENTITY; -- external_source_identification

  ENTITY file
    ABSTRACT SUPERTYPE OF (ONEOF (digital_file,hardcopy));
      id                  : STRING;
      version             : OPTIONAL STRING;
      contained_data_type : OPTIONAL STRING;
  END_ENTITY; -- file

  ENTITY file_location_identification
    SUBTYPE OF (external_item_identification);
    WHERE
      wr1: ('AP239_PART_DEFINITION_INFORMATION_ARM.FILE' IN TYPEOF(SELF\
               external_source_identification.item));
  END_ENTITY; -- file_location_identification

  ENTITY file_relationship;
      relation_type          : STRING;
      description            : OPTIONAL STRING;
      relating_document_file : file;
      related_document_file  : file;
    WHERE
      wr1: (relating_document_file :<>: related_document_file);
  END_ENTITY; -- file_relationship

  ENTITY generic_expression
    ABSTRACT SUPERTYPE OF (ONEOF (unary_generic_expression,
        binary_generic_expression,multiple_arity_generic_expression));
    WHERE
      wr1: is_acyclic(SELF);
  END_ENTITY; -- generic_expression

  ENTITY hardcopy
    SUBTYPE OF (file);
  END_ENTITY; -- hardcopy

  ENTITY identification_assignment;
      identifier  : STRING;
      role        : STRING;
      description : OPTIONAL STRING;
      items       : SET [1:?] OF identification_item;
  END_ENTITY; -- identification_assignment

  ENTITY independent_property;
      id            : STRING;
      property_type : STRING;
      description   : OPTIONAL STRING;
  END_ENTITY; -- independent_property

  ENTITY independent_property_relationship;
      relation_type : STRING;
      related       : independent_property;
      relating      : independent_property;
      description   : OPTIONAL STRING;
  END_ENTITY; -- independent_property_relationship

  ENTITY independent_property_representation;
      property    : independent_property;
      rep         : representation;
      role        : OPTIONAL STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- independent_property_representation

  ENTITY information_right;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      restriction : OPTIONAL STRING;
  END_ENTITY; -- information_right

  ENTITY information_usage_right;
      id           : STRING;
      name         : STRING;
      grants_right : SET [1:?] OF information_right;
      comment      : OPTIONAL STRING;
  END_ENTITY; -- information_usage_right

  ENTITY information_usage_right_relationship;
      related  : information_usage_right;
      relating : information_usage_right;
      role     : STRING;
  END_ENTITY; -- information_usage_right_relationship

  ENTITY interface_connection
    SUBTYPE OF (view_definition_relationship);
      SELF\view_definition_relationship.related_view  : interface_connector_definition;
      SELF\view_definition_relationship.relating_view : interface_connector_definition;
    DERIVE
      connecting : interface_connector_definition := SELF\
                      interface_connection.relating_view;
      connected  : interface_connector_definition := SELF\
                      interface_connection.related_view;
  END_ENTITY; -- interface_connection

  ENTITY interface_connector
    SUBTYPE OF (product);
  END_ENTITY; -- interface_connector

  ENTITY interface_connector_as_planned
    SUBTYPE OF (interface_connector_version);
  END_ENTITY; -- interface_connector_as_planned

  ENTITY interface_connector_as_realized
    SUBTYPE OF (interface_connector_version);
  END_ENTITY; -- interface_connector_as_realized

  ENTITY interface_connector_definition
    SUBTYPE OF (product_view_definition);
      SELF\product_view_definition.defined_version : interface_connector_version;
  END_ENTITY; -- interface_connector_definition

  ENTITY interface_connector_design
    SUBTYPE OF (interface_connector_version);
  END_ENTITY; -- interface_connector_design

  ENTITY interface_connector_design_to_planned;
      description : OPTIONAL STRING;
      design      : interface_connector_design;
      id          : STRING;
      name        : STRING;
      planned     : interface_connector_as_planned;
  END_ENTITY; -- interface_connector_design_to_planned

  ENTITY interface_connector_design_to_realized;
      description : OPTIONAL STRING;
      design      : interface_connector_design;
      id          : STRING;
      name        : STRING;
      realized    : interface_connector_as_realized;
  END_ENTITY; -- interface_connector_design_to_realized

  ENTITY interface_connector_planned_to_realized;
      description : OPTIONAL STRING;
      id          : STRING;
      name        : STRING;
      planned     : interface_connector_as_planned;
      realized    : interface_connector_as_realized;
  END_ENTITY; -- interface_connector_planned_to_realized

  ENTITY interface_connector_version
    SUBTYPE OF (product_version);
      SELF\product_version.of_product : interface_connector;
  END_ENTITY; -- interface_connector_version

  ENTITY interface_definition_for;
      description         : OPTIONAL STRING;
      id                  : STRING;
      interface           : interface_specification_definition;
      interface_component : component_item;
      name                : STRING;
  END_ENTITY; -- interface_definition_for

  ENTITY interface_specification
    SUBTYPE OF (product);
  END_ENTITY; -- interface_specification

  ENTITY interface_specification_definition
    SUBTYPE OF (product_view_definition);
      SELF\product_view_definition.defined_version : interface_specification_version;
  END_ENTITY; -- interface_specification_definition

  ENTITY interface_specification_version
    SUBTYPE OF (product_version);
      SELF\product_version.of_product : interface_specification;
  END_ENTITY; -- interface_specification_version

  ENTITY intersection;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      operand     : SET [2:?] OF class;
      resultant   : class;
  END_ENTITY; -- intersection

  ENTITY language;
      language_code : STRING;
      country_code  : OPTIONAL STRING;
  END_ENTITY; -- language

  ENTITY language_indication;
      considered_instances : SET [1:?] OF string_select;
      considered_attribute : STRING;
      used_language        : language;
  END_ENTITY; -- language_indication

  ENTITY length_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- length_unit

  ENTITY local_time;
      hour_component   : hour_in_day;
      minute_component : OPTIONAL minute_in_hour;
      second_component : OPTIONAL second_in_minute;
      zone             : time_offset;
  END_ENTITY; -- local_time

  ENTITY logical_expression
    ABSTRACT SUPERTYPE
    SUBTYPE OF (expression);
  END_ENTITY; -- logical_expression

  ENTITY luminous_intensity_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- luminous_intensity_unit

  ENTITY market;
      name                : STRING;
      market_segment_type : OPTIONAL STRING;
  END_ENTITY; -- market

  ENTITY mass_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- mass_unit

  ENTITY measure_item
    ABSTRACT SUPERTYPE OF (ONEOF (numerical_item_with_unit,
        numerical_item_with_global_unit,value_limit,
        value_limit_with_global_unit,value_list,value_range,
        value_range_with_global_unit,value_with_tolerances))
    SUBTYPE OF (representation_item);
    WHERE
      wr1: (SIZEOF(USEDIN(SELF,'AP239_PART_DEFINITION_INFORMATION_ARM.PROPERTY_VALUE_REPRESENTATION.ITEMS')) 
               > 0);
  END_ENTITY; -- measure_item

  ENTITY message;
      contains     : SET [0:?] OF content_item;
      defined_by   : OPTIONAL SET [0:?] OF message_definer_select;
      id           : STRING;
      message_type : STRING;
      purpose      : OPTIONAL STRING;
  END_ENTITY; -- message

  ENTITY message_association;
      related  : message;
      relating : message;
      role     : STRING;
  END_ENTITY; -- message_association

  ENTITY multiple_arity_generic_expression
    ABSTRACT SUPERTYPE
    SUBTYPE OF (generic_expression);
      operands : LIST [2:?] OF generic_expression;
  END_ENTITY; -- multiple_arity_generic_expression

  ENTITY name_assignment;
      name  : STRING;
      role  : STRING;
      items : assigned_name_select;
  END_ENTITY; -- name_assignment

  ENTITY numerical_document_property
    SUBTYPE OF (numerical_item_with_unit);
    INVERSE
      valued_characteristic : SET [1:1] OF
                                  document_property_representation FOR 
                                 items;
  END_ENTITY; -- numerical_document_property

  ENTITY numerical_item_with_global_unit
    SUBTYPE OF (measure_item);
      value_component : measure_value;
    WHERE
      wr1: (SIZEOF(QUERY ( pvr <* USEDIN(SELF,'AP239_PART_DEFINITION_INFORMATION_ARM.PROPERTY_VALUE_REPRESENTATION.ITEMS')
                | EXISTS(pvr.units) )) > 0);
  END_ENTITY; -- numerical_item_with_global_unit

  ENTITY numerical_item_with_unit
    SUBTYPE OF (measure_item, value_with_unit);
  END_ENTITY; -- numerical_item_with_unit

  ENTITY numerical_representation_context
    SUBTYPE OF (representation_context);
      units      : OPTIONAL SET [1:?] OF unit;
      accuracies : OPTIONAL SET [1:?] OF uncertainty_with_unit;
  END_ENTITY; -- numerical_representation_context

  ENTITY or_state_cause_effect_definition
    SUBTYPE OF (state_cause_effect_definition);
  END_ENTITY; -- or_state_cause_effect_definition

  ENTITY organization;
      id   : STRING;
      name : STRING;
  END_ENTITY; -- organization

  ENTITY organization_or_person_in_organization_assignment;
      assigned_entity : organization_or_person_in_organization_select;
      role            : STRING;
      items           : SET [1:?] OF
                            organization_or_person_in_organization_item;
  END_ENTITY; -- organization_or_person_in_organization_assignment

  ENTITY organization_relationship;
      relation_type         : STRING;
      description           : OPTIONAL STRING;
      relating_organization : organization;
      related_organization  : organization;
  END_ENTITY; -- organization_relationship

  ENTITY part
    SUBTYPE OF (product);
    WHERE
      wr1: (SIZEOF(['part','raw material'] * types_of_product(SELF)) = 1);
  END_ENTITY; -- part

  ENTITY part_version
    SUBTYPE OF (product_version);
      SELF\product_version.of_product : part;
  END_ENTITY; -- part_version

  ENTITY part_view_definition
    SUBTYPE OF (product_view_definition);
      SELF\product_view_definition.defined_version : part_version;
  END_ENTITY; -- part_view_definition

  ENTITY partial_document_assignment
    SUBTYPE OF (document_assignment);
      document_portion : STRING;
  END_ENTITY; -- partial_document_assignment

  ENTITY person;
      last_name     : STRING;
      first_name    : OPTIONAL STRING;
      middle_names  : OPTIONAL LIST [1:?] OF STRING;
      prefix_titles : OPTIONAL LIST [1:?] OF STRING;
      suffix_titles : OPTIONAL LIST [1:?] OF STRING;
  END_ENTITY; -- person

  ENTITY person_in_organization;
      concerned_person        : person;
      containing_organization : organization;
      role                    : STRING;
    UNIQUE
      person_is_unique_in_organization : concerned_person, 
                                            containing_organization;
  END_ENTITY; -- person_in_organization

  ENTITY physical_document_definition
    SUBTYPE OF (document_definition);
      components : SET [0:?] OF hardcopy;
  END_ENTITY; -- physical_document_definition

  ENTITY plane_angle_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- plane_angle_unit

  ENTITY power_set;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      base        : class;
      derived     : class;
  END_ENTITY; -- power_set

  ENTITY product;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- product

  ENTITY product_as_individual
    ABSTRACT SUPERTYPE OF (ONEOF (product_as_planned,product_as_realized))
    SUBTYPE OF (product_version);
  END_ENTITY; -- product_as_individual

  ENTITY product_as_planned
    SUBTYPE OF (product_as_individual);
  END_ENTITY; -- product_as_planned

  ENTITY product_as_realized
    SUBTYPE OF (product_as_individual);
  END_ENTITY; -- product_as_realized

  ENTITY product_category;
      id          : OPTIONAL STRING;
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- product_category

  ENTITY product_category_assignment;
      category : product_category;
      products : SET [1:?] OF product;
  END_ENTITY; -- product_category_assignment

  ENTITY product_category_hierarchy;
      super_category : product_category;
      sub_category   : product_category;
  END_ENTITY; -- product_category_hierarchy

  ENTITY product_concept;
      id            : STRING;
      name          : STRING;
      description   : OPTIONAL STRING;
      target_market : OPTIONAL market;
    UNIQUE
      ur1 : id;
  END_ENTITY; -- product_concept

  ENTITY product_design_to_individual;
      individual_product : product_as_individual;
      product_version    : product_version;
  END_ENTITY; -- product_design_to_individual

  ENTITY product_planned_to_realized;
      planned_product  : product_as_planned;
      realized_product : product_as_realized;
  END_ENTITY; -- product_planned_to_realized

  ENTITY product_version;
      id          : STRING;
      description : OPTIONAL STRING;
      of_product  : product;
    UNIQUE
      ur1 : id, of_product;
  END_ENTITY; -- product_version

  ENTITY product_version_relationship;
      relating_version : product_version;
      related_version  : product_version;
      relation_type    : STRING;
      description      : OPTIONAL STRING;
    WHERE
      wr1: (relating_version :<>: related_version);
  END_ENTITY; -- product_version_relationship

  ENTITY product_view_definition;
      id                          : STRING;
      name                        : OPTIONAL STRING;
      additional_characterization : OPTIONAL STRING;
      initial_context             : view_definition_context;
      additional_contexts         : SET [0:?] OF view_definition_context;
      defined_version             : product_version;
    WHERE
      wr1: (NOT (initial_context IN additional_contexts));
  END_ENTITY; -- product_view_definition

  ENTITY project;
      id                        : STRING;
      name                      : STRING;
      description               : OPTIONAL STRING;
      responsible_organizations : SET [1:?] OF organization;
      planned_start_date        : OPTIONAL date_or_event;
      planned_end_date          : OPTIONAL date_or_event;
      actual_start_date         : OPTIONAL date_or_date_time_select;
      actual_end_date           : OPTIONAL date_or_date_time_select;
  END_ENTITY; -- project

  ENTITY project_assignment;
      assigned_project : project;
      role             : STRING;
      items            : SET [1:?] OF project_item;
  END_ENTITY; -- project_assignment

  ENTITY project_relationship;
      relation_type    : STRING;
      description      : OPTIONAL STRING;
      relating_project : project;
      related_project  : project;
  END_ENTITY; -- project_relationship

  ENTITY proper_subset;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      subset      : class;
      superset    : class;
  END_ENTITY; -- proper_subset

  ENTITY property_representation;
      description : OPTIONAL STRING;
      property    : assigned_property;
      rep         : representation;
      role        : OPTIONAL STRING;
  END_ENTITY; -- property_representation

  ENTITY property_value_representation
    SUBTYPE OF (representation);
      SELF\representation.context_of_items : numerical_representation_context;
  END_ENTITY; -- property_value_representation

  ENTITY qualified_property_value_representation
    SUBTYPE OF (property_value_representation);
      value_determination : OPTIONAL STRING;
      qualifier           : OPTIONAL property_value_qualifier;
  END_ENTITY; -- qualified_property_value_representation

  ENTITY ratio_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- ratio_unit

  ENTITY relative_event
    SUBTYPE OF (event);
      base_event : event;
      offset     : duration;
  END_ENTITY; -- relative_event

  ENTITY representation;
      name             : STRING;
      context_of_items : representation_context;
      items            : SET [1:?] OF representation_item;
      description      : OPTIONAL STRING;
      id               : OPTIONAL STRING;
  END_ENTITY; -- representation

  ENTITY representation_context;
      id   : STRING;
      kind : STRING;
    INVERSE
      representations_in_context : SET [1:?] OF representation FOR 
                                      context_of_items;
  END_ENTITY; -- representation_context

  ENTITY representation_item
    ABSTRACT SUPERTYPE;
      name : STRING;
  END_ENTITY; -- representation_item

  ENTITY representation_relationship;
      relation_type : STRING;
      description   : STRING;
      rep_1         : representation;
      rep_2         : representation;
  END_ENTITY; -- representation_relationship

  ENTITY requirement
    SUBTYPE OF (product);
  END_ENTITY; -- requirement

  ENTITY requirement_assignment;
      assigned_requirement : requirement_view_definition;
      assigned_to          : requirement_assignment_item;
      description          : OPTIONAL STRING;
      id                   : STRING;
  END_ENTITY; -- requirement_assignment

  ENTITY requirement_collection_relationship
    SUBTYPE OF (view_definition_relationship);
      SELF\view_definition_relationship.relating_view : requirement_view_definition;
      SELF\view_definition_relationship.related_view  : requirement_view_definition;
    DERIVE
      member     : requirement_view_definition := SELF\
                      requirement_collection_relationship.related_view;
      collection : requirement_view_definition := SELF\
                      requirement_collection_relationship.relating_view;
  END_ENTITY; -- requirement_collection_relationship

  ENTITY requirement_source;
      description         : OPTIONAL STRING;
      id                  : STRING;
      source              : requirement_source_item;
      sourced_requirement : requirement_view_definition;
  END_ENTITY; -- requirement_source

  ENTITY requirement_version
    SUBTYPE OF (product_version);
      SELF\product_version.of_product : requirement;
  END_ENTITY; -- requirement_version

  ENTITY requirement_version_relationship
    SUBTYPE OF (product_version_relationship);
      SELF\product_version_relationship.relating_version : requirement_version;
      SELF\product_version_relationship.related_version  : requirement_version;
    DERIVE
      successor   : requirement_version := SELF\
                       requirement_version_relationship.related_version;
      predecessor : requirement_version := SELF\
                       requirement_version_relationship.relating_version;
  END_ENTITY; -- requirement_version_relationship

  ENTITY requirement_view_definition
    SUBTYPE OF (product_view_definition);
      SELF\product_view_definition.defined_version : requirement_version;
      satisfied                                    : OPTIONAL BOOLEAN;
      tbd                                          : BOOLEAN;
  END_ENTITY; -- requirement_view_definition

  ENTITY same_membership;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      set_1       : class;
      set_2       : class;
  END_ENTITY; -- same_membership

  ENTITY security_classification;
      classification_level : STRING;
      description          : OPTIONAL STRING;
  END_ENTITY; -- security_classification

  ENTITY security_classification_assignment;
      classification : security_classification;
      items          : SET [1:?] OF security_classification_item;
  END_ENTITY; -- security_classification_assignment

  ENTITY sequence_of_state
    SUBTYPE OF (state_relationship);
      SELF\state_relationship.relating : state;
      SELF\state_relationship.related  : state;
    DERIVE
      predecessor : state := SELF\sequence_of_state.related;
      successor   : state := SELF\sequence_of_state.relating;
  END_ENTITY; -- sequence_of_state

  ENTITY sequence_of_state_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      predecessor : state_definition := SELF\sequence_of_state_definition.
                       related;
      successor   : state_definition := SELF\sequence_of_state_definition.
                       relating;
  END_ENTITY; -- sequence_of_state_definition

  ENTITY solid_angle_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- solid_angle_unit

  ENTITY state
    SUPERTYPE OF (ONEOF (state_observed,state_predicted));
      name        : STRING;
      description : STRING;
  END_ENTITY; -- state

  ENTITY state_assertion;
      name              : STRING;
      description       : STRING;
      asserted_state    : state;
      conformance_state : state_definition;
  END_ENTITY; -- state_assertion

  ENTITY state_assessment;
      name             : STRING;
      description      : STRING;
      assessed_state   : state;
      comparable_state : state_definition;
  END_ENTITY; -- state_assessment

  ENTITY state_cause_effect
    SUBTYPE OF (state_relationship);
      SELF\state_relationship.relating : state;
      SELF\state_relationship.related  : state;
    DERIVE
      cause  : state := SELF\state_cause_effect.related;
      effect : state := SELF\state_cause_effect.relating;
  END_ENTITY; -- state_cause_effect

  ENTITY state_cause_effect_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      cause  : state_definition := SELF\state_cause_effect_definition.
                  related;
      effect : state_definition := SELF\state_cause_effect_definition.
                  relating;
  END_ENTITY; -- state_cause_effect_definition

  ENTITY state_complement_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
      set_2                                       : state_definition;
    DERIVE
      set_1    : state_definition := SELF\state_complement_definition.
                    related;
      universe : state_definition := SELF\state_complement_definition.
                    relating;
  END_ENTITY; -- state_complement_definition

  ENTITY state_definition;
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- state_definition

  ENTITY state_definition_relationship;
      name        : STRING;
      description : STRING;
      relating    : state_definition;
      related     : state_definition;
  END_ENTITY; -- state_definition_relationship

  ENTITY state_definition_role;
      name        : STRING;
      description : STRING;
  END_ENTITY; -- state_definition_role

  ENTITY state_observed
    SUBTYPE OF (state);
  END_ENTITY; -- state_observed

  ENTITY state_predicted
    SUBTYPE OF (state);
  END_ENTITY; -- state_predicted

  ENTITY state_predicted_to_observed
    SUBTYPE OF (state_relationship);
      SELF\state_relationship.relating : state_observed;
      SELF\state_relationship.related  : state_predicted;
    DERIVE
      predicted_state : state_predicted := SELF\
                           state_predicted_to_observed.related;
      observed_state  : state_observed := SELF\state_predicted_to_observed
                           .relating;
  END_ENTITY; -- state_predicted_to_observed

  ENTITY state_proper_subset_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      proper_subset   : state_definition := SELF\
                           state_proper_subset_definition.related;
      proper_superset : state_definition := SELF\
                           state_proper_subset_definition.relating;
  END_ENTITY; -- state_proper_subset_definition

  ENTITY state_relationship;
      name        : STRING;
      description : OPTIONAL STRING;
      relating    : state;
      related     : state;
  END_ENTITY; -- state_relationship

  ENTITY state_role;
      name        : STRING;
      description : STRING;
  END_ENTITY; -- state_role

  ENTITY state_subset_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      subset   : state_definition := SELF\state_subset_definition.related;
      superset : state_definition := SELF\state_subset_definition.relating;
  END_ENTITY; -- state_subset_definition

  ENTITY state_symptom_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      symptom_cause  : state_definition := SELF\state_symptom_definition.
                          related;
      symptom_effect : state_definition := SELF\state_symptom_definition.
                          relating;
  END_ENTITY; -- state_symptom_definition

  ENTITY state_transition
    SUBTYPE OF (state_relationship);
      SELF\state_relationship.relating : state;
      SELF\state_relationship.related  : state;
    DERIVE
      start_state : state := SELF\state_transition.related;
      end_state   : state := SELF\state_transition.relating;
  END_ENTITY; -- state_transition

  ENTITY state_transition_definition
    SUBTYPE OF (state_definition_relationship);
      SELF\state_definition_relationship.relating : state_definition;
      SELF\state_definition_relationship.related  : state_definition;
    DERIVE
      start_state : state_definition := SELF\state_transition_definition.
                       related;
      end_state   : state_definition := SELF\state_transition_definition.
                       relating;
  END_ENTITY; -- state_transition_definition

  ENTITY string_representation_item
    SUBTYPE OF (representation_item);
      string_value : STRING;
  END_ENTITY; -- string_representation_item

  ENTITY subset;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      subset      : class;
      superset    : class;
  END_ENTITY; -- subset

  ENTITY supplied_part_relationship
    SUBTYPE OF (product_version_relationship);
    WHERE
      wr1: (SELF\product_version_relationship.relation_type IN [
               'supplied item','supplied document']);
  END_ENTITY; -- supplied_part_relationship

  ENTITY thermodynamic_temperature_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- thermodynamic_temperature_unit

  ENTITY time_offset;
      hour_offset   : INTEGER;
      minute_offset : OPTIONAL INTEGER;
      sense         : offset_orientation;
    DERIVE
      actual_minute_offset : INTEGER := NVL(minute_offset,0);
    WHERE
      wr1: ((0 <= hour_offset) AND (hour_offset < 24));
      wr2: ((0 <= minute_offset) AND (minute_offset <= 59));
      wr3: (NOT (((hour_offset <> 0) OR (actual_minute_offset <> 0)) AND (
               sense = exact)));
  END_ENTITY; -- time_offset

  ENTITY time_unit
    SUBTYPE OF (unit);
  END_ENTITY; -- time_unit

  ENTITY tracing_relationship
    SUBTYPE OF (view_definition_relationship);
      SELF\view_definition_relationship.relating_view : requirement_view_definition;
      SELF\view_definition_relationship.related_view  : requirement_view_definition;
    DERIVE
      traces_to   : requirement_view_definition := SELF\
                       tracing_relationship.related_view;
      traces_from : requirement_view_definition := SELF\
                       tracing_relationship.relating_view;
  END_ENTITY; -- tracing_relationship

  ENTITY unary_generic_expression
    ABSTRACT SUPERTYPE
    SUBTYPE OF (generic_expression);
      operand : generic_expression;
  END_ENTITY; -- unary_generic_expression

  ENTITY uncertainty_with_unit
    SUBTYPE OF (value_with_unit);
      name        : STRING;
      description : OPTIONAL STRING;
  END_ENTITY; -- uncertainty_with_unit

  ENTITY union;
      id          : STRING;
      name        : STRING;
      description : OPTIONAL STRING;
      operand     : SET [2:?] OF class;
      resultant   : class;
  END_ENTITY; -- union

  ENTITY unit
    SUPERTYPE OF (ONEOF (amount_of_substance_unit,electric_current_unit,
        length_unit,luminous_intensity_unit,mass_unit,plane_angle_unit,
        ratio_unit,solid_angle_unit,thermodynamic_temperature_unit,
        time_unit));
      name    : OPTIONAL STRING;
      si_unit : BOOLEAN;
  END_ENTITY; -- unit

  ENTITY value_limit
    SUBTYPE OF (measure_item);
      limit_qualifier : limit_qualifier_list;
      limit           : value_with_unit;
  END_ENTITY; -- value_limit

  ENTITY value_limit_with_global_unit
    SUBTYPE OF (measure_item);
      limit           : numerical_item_with_global_unit;
      limit_qualifier : limit_qualifier_list;
  END_ENTITY; -- value_limit_with_global_unit

  ENTITY value_list
    SUBTYPE OF (measure_item);
      values : LIST [1:?] OF measure_item;
  END_ENTITY; -- value_list

  ENTITY value_range
    SUBTYPE OF (measure_item);
      lower_limit : numerical_item_with_unit;
      upper_limit : numerical_item_with_unit;
  END_ENTITY; -- value_range

  ENTITY value_range_with_global_unit
    SUBTYPE OF (measure_item);
      lower_limit : numerical_item_with_global_unit;
      upper_limit : numerical_item_with_global_unit;
  END_ENTITY; -- value_range_with_global_unit

  ENTITY value_with_tolerances
    SUBTYPE OF (measure_item);
      item_value : numerical_item_with_unit;
      tolerances : value_range;
  END_ENTITY; -- value_with_tolerances

  ENTITY value_with_unit;
      unit            : unit;
      value_component : measure_value;
  END_ENTITY; -- value_with_unit

  ENTITY view_definition_context;
      application_domain : STRING;
      life_cycle_stage   : STRING;
      description        : OPTIONAL STRING;
  END_ENTITY; -- view_definition_context

  ENTITY view_definition_relationship;
      id            : STRING;
      relating_view : product_view_definition;
      related_view  : product_view_definition;
      relation_type : OPTIONAL STRING;
      description   : OPTIONAL STRING;
  END_ENTITY; -- view_definition_relationship

  ENTITY view_definition_usage
    SUBTYPE OF (view_definition_relationship);
  END_ENTITY; -- view_definition_usage

  ENTITY xor_state_cause_effect_definition
    SUBTYPE OF (state_cause_effect_definition);
  END_ENTITY; -- xor_state_cause_effect_definition

  FUNCTION acyclic(
               arg1: generic_expression;
               arg2: SET OF generic_expression
      ): BOOLEAN;

    LOCAL
      result : BOOLEAN;
    END_LOCAL;
    IF 'AP239_PART_DEFINITION_INFORMATION_ARM.SIMPLE_GENERIC_EXPRESSION' 
        IN TYPEOF(arg1) THEN
      RETURN(TRUE);
    END_IF;
    IF arg1 IN arg2 THEN
      RETURN(FALSE);
    END_IF;
    IF 'AP239_PART_DEFINITION_INFORMATION_ARM.UNARY_GENERIC_EXPRESSION' IN
         TYPEOF(arg1) THEN
      RETURN(acyclic(arg1\unary_generic_expression.operand,arg2 + [arg1]));
    END_IF;
    IF 'AP239_PART_DEFINITION_INFORMATION_ARM.BINARY_GENERIC_EXPRESSION' 
        IN TYPEOF(arg1) THEN
      RETURN(acyclic(arg1\binary_generic_expression.operands[1],arg2 + [
          arg1]) AND acyclic(arg1\binary_generic_expression.operands[2],
          arg2 + [arg1]));
    END_IF;
    IF 'AP239_PART_DEFINITION_INFORMATION_ARM.MULTIPLE_ARITY_GENERIC_EXPRESSION' 
        IN TYPEOF(arg1) THEN
      result := TRUE;
      REPEAT i := 1 TO SIZEOF(arg1\multiple_arity_generic_expression.
          operands) BY 1;
        result := result AND acyclic(arg1\
            multiple_arity_generic_expression.operands[i],arg2 + [arg1]);
      END_REPEAT;
      RETURN(result);
    END_IF;

  END_FUNCTION; -- acyclic

  FUNCTION is_acyclic(
               arg: generic_expression
      ): BOOLEAN;
    RETURN(acyclic(arg,[]));

  END_FUNCTION; -- is_acyclic

  FUNCTION types_of_product(
               obj: product
      ): SET OF STRING;

    LOCAL
      i                    : INTEGER;
      category_assignments : BAG OF product_category_assignment;
      categories           : SET OF STRING := [];
    END_LOCAL;
    category_assignments := USEDIN(obj,
        'AP239_PART_DEFINITION_INFORMATION_ARM.' + 
        'PRODUCT_CATEGORY_ASSIGNMENT.PRODUCTS');
    REPEAT i := LOINDEX(category_assignments) TO HIINDEX(
        category_assignments) BY 1;
      categories := categories + category_assignments[i].category.name;
    END_REPEAT;
    RETURN(categories);

  END_FUNCTION; -- types_of_product

  FUNCTION valid_document_property_representation(
               rep: document_property_representation
      ): LOGICAL;
    CASE rep.name OF
      'document content' :         BEGIN
          RETURN(SIZEOF(QUERY ( items <* rep\representation.items | (NOT (
              items.name IN ['detail level','geometry type',
              'real world scale'])) )) = 0);
        END;
      'document creation'  :         BEGIN
          IF NOT (SIZEOF(QUERY ( items <* rep\representation.items | (NOT 
              (items.name IN ['creating interface','creating system',
              'operating system'])) )) = 0) THEN
            RETURN(FALSE);
          END_IF;
          IF NOT (SIZEOF(QUERY ( items <* rep\representation.items | (NOT 
              (items.name IN ['creating system'])) )) = 1) THEN
            RETURN(FALSE);
          ELSE
            RETURN(TRUE);
          END_IF;
        END;
      'document format'  :         BEGIN
          RETURN(SIZEOF(QUERY ( items <* rep\representation.items | (NOT (
              items.name IN ['character code','data format','size format',
              'size format standard'])) )) = 0);
        END;
      'document size'    :         BEGIN
          RETURN(SIZEOF(QUERY ( items <* rep\representation.items | (NOT (
              items.name IN ['file size','page count'])) )) = 0);
        END;
      OTHERWISE          :         RETURN(UNKNOWN);
      END_CASE;

  END_FUNCTION; -- valid_document_property_representation

END_SCHEMA; -- ap239_part_definition_information_arm_lf
