(*

   ISO TC184/SC4/WG12 N3423 - ISO/CD-TS 10303-1677 Functional decomposition to interconnect design - EXPRESS ARM

   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Functional decomposition to interconnect design - EXPRESS ARM

*)



SCHEMA Functional_decomposition_to_interconnect_design_arm;



USE FROM Functional_decomposition_to_design_arm;



USE FROM Fabrication_joint_arm;



USE FROM Layered_interconnect_module_with_printed_component_design_arm;

	

USE FROM Network_functional_design_view_arm;

	



  ENTITY Design_functional_unit_allocation_to_fabrication_joint;

      functional_design_definition_path : Design_composition_path;

      implementation                    : Fabrication_joint;

    UNIQUE

      UR1 : functional_design_definition_path;

  END_ENTITY;



  ENTITY Transmission_line_functional_unit_terminal_allocation;

      implementation                             : Printed_component_join_terminal;

      transmission_line_functional_unit_terminal : Functional_unit_terminal;

      functional_unit_design_path                : Transmission_line_functional_unit_to_routed_printed_component_allocation;

    UNIQUE

      UR1 : implementation,

 transmission_line_functional_unit_terminal;

  END_ENTITY;



  ENTITY Transmission_line_functional_unit_to_routed_printed_component_allocation

    SUBTYPE OF (Design_functional_unit_allocation_to_assembly_component);

      SELF\Design_functional_unit_allocation_to_assembly_component.implementation : Routed_printed_component;

  END_ENTITY;



END_SCHEMA;

