(*
  $Id: mim.exp,v 1.1 2002/03/22 10:15:41 robbod Exp $
*)
{ iso standard 10303 part (11) version (4) }

SCHEMA Activity_mim;

USE FROM action_schema
(action,
 action_assignment);

USE FROM Activity_method_mim;

USE FROM Approval_mim;

USE FROM Configuration_effectivity_mim;

USE FROM configuration_management_schema
(configuration_effectivity);

USE FROM Contract_mim;

USE FROM Date_time_assignment_mim;

USE FROM Document_assignment_mim;

USE FROM Person_organization_assignment_mim;

USE FROM product_definition_schema
(product_definition,
 product_definition_formation,
 product_definition_relationship);

USE FROM Product_identification_mim;

USE FROM Product_version_mim;

USE FROM Product_view_definition_mim;

USE FROM Product_view_definition_relationship_mim;

TYPE action_approval_item = SELECT BASED_ON approval_item WITH
  (action);
END_TYPE;

TYPE action_contract_item = SELECT BASED_ON contract_item WITH
  (action);
END_TYPE;

TYPE action_date_and_time_item = SELECT BASED_ON date_and_time_item WITH
  (action);
END_TYPE;

TYPE action_date_item = SELECT BASED_ON date_item WITH
  (action);
END_TYPE;

TYPE action_items = EXTENSIBLE SELECT 
  (configuration_effectivity,
   product_definition,
   product_definition_formation,
   product_definition_relationship);
END_TYPE;

TYPE action_organization_item = SELECT BASED_ON organization_item WITH
  (action);
END_TYPE;

TYPE action_person_and_organization_item = SELECT BASED_ON person_and_organization_item WITH
  (action);
END_TYPE;

ENTITY applied_action_assignment
SUBTYPE OF (action_assignment);
  items : SET [1 : ?] OF action_items;
END_ENTITY;

END_SCHEMA;
