(*
   $Id: arm.exp,v 1.24 2015/09/25 09:01:21 lothartklein Exp $
   ISO TC184/SC4/WG12 N9291 - ISO/TS 10303-1764 Shape feature - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N8047
*)

SCHEMA Shape_feature_arm;

USE FROM Characterizable_object_arm; -- ISO/TS 10303-1765 
USE FROM Contextual_shape_positioning_arm; -- ISO/TS 10303-1027
REFERENCE FROM Support_resource_arm(bag_to_set);  -- ISO/TS 10303-1765
USE FROM Property_assignment_arm; --  ISO/TS 10303-1030

TYPE sf_shapeable_item = SELECT BASED_ON shapeable_item WITH 
  (Characterizable_object);
END_TYPE; 

TYPE sf_property_assignment_select = SELECT BASED_ON property_assignment_select WITH ( 
  Characterizable_object);
END_TYPE; 

TYPE sf_assigned_shape_property_select = SELECT BASED_ON assigned_shape_property_select WITH ( 
  Characterizable_object);
END_TYPE; 

TYPE sf_represented_definition = SELECT BASED_ON represented_definition WITH ( 
  Characterizable_object);
END_TYPE; 

ENTITY Shape_feature_definition
  SUBTYPE OF (Characterizable_object);
WHERE
  WR1: EXISTS(SELF\Characterizable_object.primary_shape_representation);
END_ENTITY;

ENTITY Instanced_feature  
  SUBTYPE OF (Shape_element, Shape_feature_definition);
END_ENTITY;

ENTITY Placed_feature  
  SUBTYPE OF (Shape_element);
   definition : Shape_feature_definition;
END_ENTITY;

ENTITY General_feature
  SUBTYPE OF (Shape_feature_definition);
END_ENTITY; 

SUBTYPE_CONSTRAINT sf_shape_element FOR Shape_element;
  ONEOF (Instanced_feature, Placed_feature);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
