(*
   $Id: mim.exp,v 1.2 2005/11/24 11:55:21 liutkus Exp $
   N - ISO/CD-TS - 10303- shape_feature - EXPRESS MIM*)

SCHEMA Shape_feature_mim;
USE FROM Contextual_shape_positioning_mim;

ENTITY feature_definition
  SUBTYPE OF (characterized_object);
END_ENTITY;

ENTITY instanced_feature
  SUBTYPE OF (shape_aspect,feature_definition);
WHERE
  WR1:  'SHAPE_FEATURE_MIM.PRODUCT_DEFINITION' IN
         TYPEOF(SELF\shape_aspect.of_shape.definition);   
  WR2:  SELF\shape_aspect.product_definitional;   
END_ENTITY;

ENTITY placed_feature
  SUBTYPE OF (shape_aspect);
END_ENTITY;

END_SCHEMA;
