(*
   $Id: mim.exp,v 1.1 2005/11/17 16:12:36 liutkuviene Exp $
   N - ISO/CD-TS - 10303- shape_feature - EXPRESS MIM*)

SCHEMA Shape_feature_mim;
USE FROM Contextual_shape_positioning_mim;

ENTITY feature_definition
  SUBTYPE OF (characterized_object);
END_ENTITY;

ENTITY instanced_feature
  SUBTYPE OF (shape_aspect,feature_definition);
END_ENTITY;

ENTITY placed_feature
  SUBTYPE OF (shape_aspect);
END_ENTITY;

END_SCHEMA;
