(*
$Id: risk_schema.exp,v 1.8 2004/12/16 10:10:56 leyson Exp $
  WG12N3267 - ISO 10303-58 risk_schema
*)

SCHEMA risk_schema;

USE FROM action_schema   -- ISO 10303-41
  (action,
   action_method,
   action_method_relationship,
   action_resource); 

USE FROM application_context_schema   -- ISO 10303-41
  (application_context,
   application_context_element); 

USE FROM basic_attribute_schema   -- ISO 10303-41
  (object_role); 

USE FROM document_schema   -- ISO 10303-41
  (document); 

USE FROM group_schema   -- ISO 10303-41
  (group); 

USE FROM management_resources_schema   -- ISO 10303-41
  (action_method_assignment,
   classification_assignment,
   classification_role,
   person_and_organization_assignment); 

USE FROM measure_schema   -- ISO 10303-41
  (measure_value); 

USE FROM person_organization_schema   -- ISO 10303-41
  (organization,
   person,
   person_and_organization,
   person_and_organization_role); 

USE FROM product_definition_schema   -- ISO 10303-41
  (product,
   product_definition,
   product_definition_formation,
   product_definition_relationship,
   product_definition_with_associated_documents,
   product_relationship); 

USE FROM representation_schema   -- ISO 10303-43
  (representation,
   representation_context,
   representation_item,
   value_representation_item); 

USE FROM state_observed_schema   -- ISO 10303-56
  (state_observed,
   state_observed_assignment,
   state_observed_role); 

USE FROM support_resource_schema   -- ISO 10303-41
  (identifier,
   label,
   text); 


TYPE mitigation_select = SELECT
   (risk, 
    risk_consequence, 
    risk_perception_relationship, 
    risk_probability_assignment, 
    risk_relationship, 
    risk_source_assignment);
END_TYPE; 

TYPE risk_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT
   (risk, 
    risk_consequence, 
    risk_perception, 
    risk_perception_relationship, 
    risk_probability, 
    risk_relationship);
END_TYPE; 

TYPE risk_communication_select = SELECT
   (applied_risk_classification_assignment, 
    lessons_learned, 
    risk, 
    risk_analysis, 
    risk_assessment, 
    risk_consequence, 
    risk_context, 
    risk_control, 
    risk_criteria, 
    risk_evaluation, 
    risk_identification, 
    risk_impact, 
    risk_owner_assignment, 
    risk_perception, 
    risk_perception_context, 
    risk_perception_relationship, 
    risk_probability, 
    risk_reduction, 
    risk_relationship, 
    risk_resource, 
    risk_status_assignment, 
    risk_treatment, 
    source_identification);
END_TYPE; 

TYPE risk_estimation_select = SELECT
   (qualitative_consequence, 
    qualitative_probability, 
    quantitative_consequence, 
    quantitative_probability, 
    quantitative_probability_distribution);
END_TYPE; 

TYPE risk_evaluation_select = SELECT
   (risk_analysis, 
    risk_consequence, 
    risk_context, 
    risk_perception, 
    risk_perception_relationship, 
    risk_probability_assignment, 
    risk_source_assignment, 
    risk_treatment);
END_TYPE; 

TYPE risk_identification_select = SELECT
   (risk_consequence, 
    risk_criteria, 
    risk_probability, 
    risk_probability_assignment);
END_TYPE; 

TYPE risk_supported_item = SELECT
   (risk_analysis, 
    risk_assessment, 
    risk_communication, 
    risk_control, 
    risk_estimation, 
    risk_identification, 
    risk_reduction, 
    risk_treatment, 
    source_identification);
END_TYPE; 

ENTITY applied_risk_classification_assignment
  SUBTYPE OF (classification_assignment);
  items : SET[1:?] OF risk_classification_item;
  SELF\classification_assignment.assigned_class : group;
  SELF\classification_assignment.role : classification_role;
END_ENTITY;

ENTITY lessons_learned
  SUBTYPE OF (risk_perception);
  document_ids : document;
  risk_source_assignment : risk_source_assignment;
END_ENTITY;

ENTITY qualitative_consequence
  SUBTYPE OF (risk_consequence);
  SELF\representation.items RENAMED estimate : SET[1:?] OF qualitative_consequence_estimate;
END_ENTITY;

ENTITY qualitative_consequence_estimate
  SUBTYPE OF (representation_item);
  SELF\representation_item.name : label;
END_ENTITY;

ENTITY qualitative_probability
  SUBTYPE OF (risk_probability);
  SELF\representation.items RENAMED estimate : SET[1:?] OF qualitative_probability_estimate;
END_ENTITY;

ENTITY qualitative_probability_estimate
  SUBTYPE OF (representation_item);
  SELF\representation_item.name : label;
END_ENTITY;

ENTITY quantitative_consequence
  SUBTYPE OF (risk_consequence);
  SELF\representation.items RENAMED estimate : SET[1:?] OF quantitative_consequence_estimate;
END_ENTITY;

ENTITY quantitative_consequence_estimate
  SUBTYPE OF (value_representation_item);
  SELF\value_representation_item.value_component : measure_value;
END_ENTITY;

ENTITY quantitative_probability
  SUBTYPE OF (risk_probability);
  SELF\representation.items RENAMED estimate : SET[1:?] OF quantitative_probability_estimate;
END_ENTITY;

ENTITY quantitative_probability_distribution
  SUBTYPE OF (quantitative_probability);
  mean : REAL;
  variance : REAL;
END_ENTITY;

ENTITY quantitative_probability_estimate
  SUBTYPE OF (value_representation_item);
  SELF\value_representation_item.value_component : measure_value;
END_ENTITY;

ENTITY risk
  SUBTYPE OF (product);
  SELF\product.id : identifier;
  SELF\product.name : label;
  SELF\product.description : OPTIONAL text;
  SELF\product.frame_of_reference RENAMED risk_context : SET[1:?] OF risk_context;
END_ENTITY;

ENTITY risk_action
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (action);
  SELF\action.name : label;
  SELF\action.description : OPTIONAL text;
  SELF\action.chosen_method RENAMED risk_treatment : risk_treatment;
END_ENTITY;

ENTITY risk_analysis
  SUBTYPE OF (risk_action);
  source_identification : source_identification;
  risk_estimates : SET[1:?] OF risk_estimation;
END_ENTITY;

ENTITY risk_application_context_element
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (application_context_element);
  SELF\application_context_element.name : label;
  SELF\application_context_element.frame_of_reference : application_context;
END_ENTITY;

ENTITY risk_assessment
  SUBTYPE OF (risk_action);
  risk_analysis : SET[1:?] OF risk_analysis;
  risk_evaluation : SET[1:?] OF risk_evaluation;
END_ENTITY;

ENTITY risk_communication
  SUBTYPE OF (risk_action);
  communicator : risk_stakeholder;
  communicatee : SET[1:?] OF risk_stakeholder;
  inputs : SET[1:?] OF risk_communication_select;
END_ENTITY;

ENTITY risk_consequence
  SUBTYPE OF (representation);
  SELF\representation.name : label;
  SELF\representation.context_of_items : representation_context;
  SELF\representation.items : SET[1:?] OF representation_item;
DERIVE
  SELF\representation.description : text := get_description_value (SELF);
  SELF\representation.id : identifier := get_id_value (SELF);
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_context
  SUBTYPE OF (risk_application_context_element);
END_ENTITY;

ENTITY risk_control
  SUBTYPE OF (risk_action);
  monitor : SET[1:?] OF risk_assessment;
END_ENTITY;

ENTITY risk_criteria
  SUBTYPE OF (action_method);
  SELF\action_method.name : label;
  SELF\action_method.description : OPTIONAL text;
  SELF\action_method.consequence : text;
  SELF\action_method.purpose RENAMED risk_stakeholder : risk_stakeholder;
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_estimation
  SUBTYPE OF (risk_action);
  inputs : SET[0:?] OF risk_evaluation;
  outputs : SET[1:?] OF risk_estimation_select;
END_ENTITY;

ENTITY risk_evaluation
  SUBTYPE OF (action);
  SELF\action.name : label;
  SELF\action.description : OPTIONAL text;
  SELF\action.chosen_method RENAMED risk_criteria : risk_criteria;
  inputs : SET[1:?] OF risk_evaluation_select;
DERIVE
  SELF\action.id : identifier := get_id_value (SELF);
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_identification
  SUBTYPE OF (risk_action);
  inputs : SET[1:?] OF risk_identification_select;
END_ENTITY;

ENTITY risk_impact
  SUBTYPE OF (risk_consequence);
  causal_consequence : OPTIONAL risk_consequence;
END_ENTITY;

ENTITY risk_impact_assignment
  ABSTRACT SUPERTYPE ;
  assigned_risk_impact : risk_impact;
DERIVE
  role : object_role := get_role (SELF);
WHERE
  : SIZEOF(USEDIN(SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ROLE_ASSOCIATION.ITEM_WITH_ROLE')) <= 1;
END_ENTITY;

ENTITY risk_organization_stakeholder
  SUBTYPE OF (organization, risk_stakeholder);
  SELF\organization.id : OPTIONAL identifier;
  SELF\organization.name : label;
  SELF\organization.description : OPTIONAL text;
END_ENTITY;

ENTITY risk_owner_assignment
  SUBTYPE OF (person_and_organization_assignment);
  SELF\person_and_organization_assignment.assigned_person_and_organization : risk_stakeholder;
  risk : SET[1:?] OF risk;
  SELF\person_and_organization_assignment.role : person_and_organization_role;
END_ENTITY;

ENTITY risk_perception
  SUBTYPE OF (product_definition);
  SELF\product_definition.id : identifier;
  SELF\product_definition.description : OPTIONAL text;
  SELF\product_definition.formation : risk_perception_formation;
  SELF\product_definition.frame_of_reference RENAMED risk_perception_context : risk_perception_context;
  risk_probability : risk_probability_assignment;
  risk_consequence : SET[1:?] OF risk_consequence;
DERIVE
  SELF\product_definition.name : label := SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'NAME_ATTRIBUTE.NAMED_ITEM')) <= 1;
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_perception_context
  SUBTYPE OF (risk_application_context_element);
END_ENTITY;

ENTITY risk_perception_formation
  SUBTYPE OF (product_definition_formation);
  SELF\product_definition_formation.id : identifier;
  SELF\product_definition_formation.description : OPTIONAL text;
  SELF\product_definition_formation.of_product RENAMED of_risk : risk;
END_ENTITY;

ENTITY risk_perception_relationship
  SUBTYPE OF (product_definition_relationship);
  SELF\product_definition_relationship.id : identifier;
  SELF\product_definition_relationship.name : label;
  SELF\product_definition_relationship.description : OPTIONAL text;
  relating_risk_perception : SET[1:?] OF risk_perception;
  related_risk_perception : SET[1:?] OF risk_perception;
  probability : OPTIONAL risk_probability_assignment;
END_ENTITY;

ENTITY risk_person_and_organization_stakeholder
  SUBTYPE OF (person_and_organization, risk_stakeholder);
  SELF\person_and_organization.the_person : risk_person_stakeholder;
  SELF\person_and_organization.the_organization : risk_organization_stakeholder;
DERIVE
  SELF\person_and_organization.description : text := get_description_value (SELF);
  SELF\person_and_organization.name : label := get_name_value (SELF);
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'NAME_ATTRIBUTE.NAMED_ITEM')) <= 1;
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_person_stakeholder
  SUBTYPE OF (person, risk_stakeholder);
  SELF\person.id : identifier;
  SELF\person.last_name : OPTIONAL label;
  SELF\person.first_name : OPTIONAL label;
  SELF\person.middle_names : OPTIONAL LIST[1:?] OF label;
  SELF\person.prefix_titles : OPTIONAL LIST[1:?] OF label;
  SELF\person.suffix_titles : OPTIONAL LIST[1:?] OF label;
WHERE
  : EXISTS(last_name) OR EXISTS(first_name);
END_ENTITY;

ENTITY risk_probability
  SUBTYPE OF (representation);
  SELF\representation.name : label;
  SELF\representation.context_of_items : representation_context;
  SELF\representation.items : SET[1:?] OF representation_item;
DERIVE
  SELF\representation.description : text := get_description_value (SELF);
  SELF\representation.id : identifier := get_id_value (SELF);
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_probability_assignment
  ABSTRACT SUPERTYPE ;
  assigned_risk_probability : risk_probability;
DERIVE
  role : object_role := get_role (SELF);
WHERE
  : SIZEOF(USEDIN(SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ROLE_ASSOCIATION.ITEM_WITH_ROLE')) <= 1;
END_ENTITY;

ENTITY risk_reduction
  SUBTYPE OF (action);
  SELF\action.name : label;
  SELF\action.description : OPTIONAL text;
  approach : risk_treatment;
  resolves : SET[1:?] OF mitigation_select;
  risk_evaluation : OPTIONAL risk_evaluation;
DERIVE
  SELF\action.id : identifier := get_id_value (SELF);
WHERE
  : SIZEOF (USEDIN (SELF, 'BASIC_ATTRIBUTE_SCHEMA.' + 'ID_ATTRIBUTE.IDENTIFIED_ITEM')) <= 1;
END_ENTITY;

ENTITY risk_relationship
  SUBTYPE OF (product_relationship);
  SELF\product_relationship.id : identifier;
  SELF\product_relationship.name : label;
  SELF\product_relationship.description : OPTIONAL text;
  SELF\product_relationship.relating_product RENAMED relating_risk : risk;
  SELF\product_relationship.related_product RENAMED related_risk : risk;
END_ENTITY;

ENTITY risk_resource
  SUBTYPE OF (action_resource);
  SELF\action_resource.name : label;
  SELF\action_resource.description : OPTIONAL text;
  SELF\action_resource.usage : SET[1:?] OF risk_supported_item;
  SELF\action_resource.kind : label;
END_ENTITY;

ENTITY risk_resource_assignment
  ABSTRACT SUPERTYPE ;
  assigned_risk_resource : risk_resource;
  role : risk_resource_role;
END_ENTITY;

ENTITY risk_resource_role;
  name : label;
  description : OPTIONAL text;
END_ENTITY;

ENTITY risk_source_assignment
  ABSTRACT SUPERTYPE ;
  assigned_risk : risk;
  risk_context : risk_context;
END_ENTITY;

ENTITY risk_stakeholder
  ABSTRACT SUPERTYPE ;
END_ENTITY;

ENTITY risk_status_assignment
  SUBTYPE OF (state_observed_assignment);
  SELF\state_observed_assignment.assigned_state_observed : state_observed;
  SELF\state_observed_assignment.role : state_observed_role;
  risk : risk;
END_ENTITY;

ENTITY risk_treatment
  SUBTYPE OF (action_method);
  SELF\action_method.name : label;
  SELF\action_method.description : OPTIONAL text;
  SELF\action_method.consequence RENAMED primary_objective : mitigation_select;
  SELF\action_method.purpose RENAMED risk_analysis : risk_analysis;
  secondary_objectives : SET[0:?] OF mitigation_select;
END_ENTITY;

ENTITY source_identification
  SUBTYPE OF (risk_identification);
  risk_source_assignment : risk_source_assignment;
END_ENTITY;

END_SCHEMA;  -- risk_schema