(* $Id: arm.exp,v 1.2 2002/08/13 09:42:43 goset1 Exp $
N	ISO/WD 10303-xxx	Alternative solution - Express ARM *)

SCHEMA Specification_control_arm;

USE FROM Alternative_solution_arm;

USE FROM Part_occurrence_arm;

USE FROM Product_class_arm;

USE FROM Specification_based_configuration_arm;

USE FROM Specified_product_arm;

TYPE configured_element = EXTENSIBLE SELECT BASED_ON configured_item_select WITH (product_function, product_component, Alternative_solution);
END_TYPE;

END_SCHEMA;

