(*
   $Id: mkmodule.js,v 1.46 2010/02/04 16:48:02 robbod Exp $
   ISO TC184/SC4/WG12 N.... - ISO/TS 10303-1738 product_view_definition_reference - EXPRESS MIM*)

SCHEMA Product_view_definition_reference_mim;

	USE FROM Support_resource_mim; -- ISO/TS 10303-1800
	USE FROM External_item_identification_assignment_mim;	-- ISO/TS 10303-1128
	USE FROM Product_view_definition_mim;	-- ISO/TS 10303-1019
	USE FROM External_reference_schema
		(externally_defined_item,
		external_source);
	USE FROM product_definition_schema (
		generic_product_definition_reference,
		product_definition_reference,
		product_definition_reference_with_local_representation);
	
TYPE pie_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH 
     (generic_product_definition_reference);
END_TYPE; 

END_SCHEMA;
