(*
   $Id: mim.exp,v 1.8 2005/01/13 21:45:56 liutkus Exp $
   ISO TC184/SC4/WG12 N3370 - ISO/CD-TS 10303-1652 Basic geometry - EXPRESS MIM
*)


SCHEMA Basic_geometry_mim;

	USE FROM Elemental_geometric_shape_mim;    -- ISO/TS 10303-1004

	USE FROM Geometry_schema(plane,
	point_on_curve,
	curve,
	point_on_surface,
	degenerate_pcurve,
	surface,
	oriented_surface); -- required by mapping

END_SCHEMA;

