(*
   $Id: mim.exp,v 1.11 2006/01/20 08:43:36 liutkuviene Exp $
   ISO TC184/SC4/WG12 N3904 - ISO/TS 10303-1652 Basic geometry - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3370
*)


SCHEMA Basic_geometry_mim;

	USE FROM Elemental_geometric_shape_mim;    -- ISO/TS 10303-1004

	USE FROM Geometry_schema(plane,
	point_on_curve,
	curve,
	line,
	point_on_surface,
	degenerate_pcurve,
	surface,
	oriented_surface);

END_SCHEMA;

