(*
   $Id: arm.exp,v 1.10 2006/01/20 08:43:41 liutkuviene Exp $
   ISO TC184/SC4/WG3 N2005 - ISO/CD-TS 10303-1615 AP210 functional requirement allocation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1644
*)

SCHEMA Ap210_functional_requirement_allocation_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Functional_unit_requirement_allocation_arm;	-- ISO/TS 10303-1680
   -- look to IS what to add further
END_SCHEMA;

