(*
 $Id: mim.exp,v 1.9 2009/05/22 10:08:12 liutkuviene Exp $
 ISO TC184/SC4/WG12 N6617 - ISO/TS 10303-1027 Contextual shape positioning - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N5333
*)
SCHEMA Contextual_shape_positioning_mim;

USE FROM Elemental_geometric_shape_mim;          -- ISO/TS 10303-1004
USE FROM Geometric_model_relationship_mim;
USE FROM Shape_property_assignment_mim; --  ISO/TS 10303-1032

USE FROM product_property_representation_schema -- ISO 10303-41
  (context_dependent_shape_representation);

USE FROM representation_schema 	-- ISO 10303-43
      (functionally_defined_transformation,
      representation_relationship_with_transformation);

END_SCHEMA;




