(*
   $Id: arm.exp,v 1.1 2005/11/25 15:24:24 dmprice Exp $
   N - ISO/CD-TS - 10303- general_model_parameter - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA General_model_parameter_arm;

USE FROM Classification_assignment_arm;

USE FROM External_class_arm;

USE FROM Independent_property_representation_arm;

USE FROM Parameter_value_specification_arm;

ENTITY General_model_parameter
SUBTYPE OF (Independent_property);
  default_value : OPTIONAL parameter_value_select;
END_ENTITY;

END_SCHEMA;