(*
   $Id$
   N - ISO/CD-TS - 10303- mechanical_design_shaded_presentation - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA Mechanical_design_shaded_presentation_arm;

 USE FROM Camera_view_3d_arm;
 
 USE FROM Appearance_assignment_arm;
 
 USE FROM Colour_arm;
 
 TYPE mdsp_presented_model_select = SELECT BASED_ON presented_model_select WITH
   (Styled_model);
 END_TYPE;
 
 ENTITY Mechanical_design_shaded_presentation_area   -- AIM is mechanical_design_shaded_presentation_area
   SUBTYPE OF (View_area);
 END_ENTITY;
 
 ENTITY Mechanical_design_shaped_styled_model  -- AIM is mechanical_design_shaded_presentation_representation
   SUBTYPE OF (Styled_model);
 END_ENTITY;

-- ToDo: need to check for light sources and more ... 

END_SCHEMA;
