(*
   $Id: mim.exp,v 1.4 2005/01/04 07:21:34 kovaliovas Exp $
   ISO TC184/SC4/WG12 N3595 - ISO/CD-TS 10303-1741 Sequential laminate assembly design - EXPRESS MIM
*)


SCHEMA Sequential_laminate_assembly_design_mim;
	USE FROM Assembly_module_with_interconnect_component_mim;
	USE FROM Component_feature_mim;
	USE FROM Layered_interconnect_module_design_mim;
	
ENTITY interconnect_module_stratum_based_terminal
  SUBTYPE OF (interconnect_module_terminal);
END_ENTITY;

ENTITY sequential_laminate_passage_based_fabrication_joint
  SUBTYPE OF (shape_aspect);
END_ENTITY;
	
END_SCHEMA;

