(*
 $Id: mim.exp,v 1.14 2012/10/11 05:49:13 liutkuviene Exp $
 ISO TC184/SC4/WG12 N7991 - ISO/TS 10303-1362 Dimension and tolerance callouts - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N5351
*) 

SCHEMA Dimension_and_tolerance_callouts_mim;

USE FROM Associative_draughting_elements_mim; -- ISO/TS 10303-1311
USE FROM Draughting_annotation_mim; -- ISO/TS 10303-1206
USE FROM Draughting_element_specialisations_mim; -- ISO/TS 10303-1312
USE FROM Geometric_tolerance_mim; -- ISO/TS 10303-1051

TYPE datc_draughting_model_item_definition = EXTENSIBLE GENERIC_ENTITY SELECT 
  BASED_ON draughting_model_item_definition WITH (
  dimensional_size,
  geometric_tolerance);
END_TYPE;

TYPE dimensioning_standard_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
  (product_definition);
END_TYPE; 

ENTITY dimension_curve_terminator_to_projection_curve_associativity
  SUBTYPE OF(annotation_occurrence_associativity);
  SELF\annotation_occurrence_relationship.relating_annotation_occurrence : dimension_curve_terminator;
  SELF\annotation_occurrence_relationship.related_annotation_occurrence  : projection_curve;
END_ENTITY;

END_SCHEMA; 
