(*
 $Id: mim.exp,v 1.21 2017/06/24 22:55:20 thomasrthurman Exp $
 ISO TC184/SC4/WG12 N7991 - ISO/TS 10303-1362 Dimension and tolerance callouts - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N5351
*) 

SCHEMA Dimension_and_tolerance_callouts_mim;

USE FROM Associative_draughting_elements_mim; -- ISO/TS 10303-1311
USE FROM Draughting_annotation_mim; -- ISO/TS 10303-1206
USE FROM Draughting_element_specialisations_mim; -- ISO/TS 10303-1312
USE FROM Geometric_tolerance_mim; -- ISO/TS 10303-1051
USE FROM draughting_element_schema (
          draughting_model_item_definition); -- ISO 10303-101
USE FROM mechanical_design_schema (
         annotation_placeholder_occurrence,
         draughting_model_item_association_with_placeholder,
         md_draughting_callout_element);
USE FROM shape_tolerance_schema (geometric_tolerance); -- ISO 10303-47
USE FROM product_property_definition_schema (
         characterized_object, ---?? 
         property_definition, 
         product_definition_shape, 
         shape_aspect,
         shape_aspect_relationship);

TYPE datc_draughting_model_item_definition = EXTENSIBLE GENERIC_ENTITY SELECT 
  BASED_ON draughting_model_item_definition WITH (
  dimensional_location,
  dimensional_size,
  angularity_tolerance,
  circular_runout_tolerance,
  coaxiality_tolerance,
  concentricity_tolerance,
  cylindricity_tolerance,
  flatness_tolerance,
  line_profile_tolerance,
  geometric_tolerance,
  geometric_tolerance_with_datum_reference, 
  geometric_tolerance_with_defined_unit,
  geometric_tolerance_with_defined_area_unit,
  geometric_tolerance_with_maximum_tolerance,
  geometric_tolerance_with_modifiers, 
  modified_geometric_tolerance,
  parallelism_tolerance,
  perpendicularity_tolerance,
  position_tolerance,
  roundness_tolerance,
  straightness_tolerance,
  surface_profile_tolerance,
  symmetry_tolerance,
  total_runout_tolerance,
  unequally_disposed_geometric_tolerance);
END_TYPE;

TYPE dimensioning_standard_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
  (product_definition);
END_TYPE; 

ENTITY dimension_curve_terminator_to_projection_curve_associativity
  SUBTYPE OF(annotation_occurrence_associativity);
  SELF\annotation_occurrence_relationship.relating_annotation_occurrence : dimension_curve_terminator;
  SELF\annotation_occurrence_relationship.related_annotation_occurrence  : projection_curve;
END_ENTITY;

END_SCHEMA; 
