(*
   $Id: mim.exp,v 1.2 2004/12/13 15:27:26 budreckytej Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 assembly physical interface requirements - EXPRESS MIM
*)


SCHEMA Ap210_assembly_physical_interface_requirements_mim;
   USE FROM AP210_product_data_management_mim;
   USE FROM Assembly_physical_requirement_allocation_mim;
   USE FROM Requirement_decomposition_mim;
   USE FROM Characteristic_mim;
END_SCHEMA;

