(*
   $Id: mim.exp,v 1.4 2012/09/15 09:15:15 lothartklein Exp $
   N - ISO/CD-TS - 10303- product_as_individual_assembly_and_test - EXPRESS MIM*)

SCHEMA Product_as_individual_assembly_and_test_mim;

USE FROM Planned_characteristic_mim; -- ISO/TS 10303-1733
USE FROM Product_as_individual_mim; -- ISO/TS 10303-1164
USE FROM Property_assignment_mim; -- ISO/TS 10303-1030
USE FROM Process_plan_mim;
USE FROM Activity_mim; -- ISO/TS 10303-1047

ENTITY evaluated_characteristic_of_product_as_individual_test_result
  SUBTYPE OF (evaluated_characteristic);
END_ENTITY;

END_SCHEMA;
