(*
   $Id: mim.exp,v 1.2 2011/07/07 10:03:16 lothartklein Exp $
   N - ISO/CD-TS - 10303- product_as_individual_assembly_and_test - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Product_as_individual_assembly_and_test_mim;
USE FROM Planned_characteristic_mim; -- ISO/TS 10303-1733
USE FROM Product_as_individual_mim; -- ISO/TS 10303-1164
USE FROM Property_assignment_mim; -- ISO/TS 10303-1030
USE FROM Process_plan_mim;
USE FROM Activity_mim; -- ISO/TS 10303-1047

END_SCHEMA;
