(*
   $Id: mim.exp,v 1.9 2005/11/24 11:55:21 liutkus Exp $
   ISO TC184/SC4/WG12 N3430 - ISO/CD-TS 10303-1678 Functional decomposition with nodal representation to packaged mapping - EXPRESS MIM
*)


SCHEMA Functional_decomposition_with_nodal_representation_to_packaged_mapping_mim;
	USE FROM Functional_decomposition_to_design_mim; -- ISO/TS 10303-1676
	USE FROM Physical_connectivity_definition_mim;	-- ISO/TS 10303-1755

END_SCHEMA;

