(*
   $Id: arm.exp,v 1.114 2006/03/22 10:07:24 liutkus Exp $
   ISO TC184/SC4/WG12 N3957 - ISO/TS 10303-1670 Fabrication technology - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3663
*)

SCHEMA Fabrication_technology_arm;
    USE FROM Constructive_solid_geometry_2d_arm; 	-- ISO/TS 10303-1731
	USE FROM Part_feature_location_arm; -- ISO/TS 10303-1714
	USE FROM Physical_layout_template_arm;	-- ISO/TS 10303-1722
	USE FROM Requirement_decomposition_arm;	-- ISO/TS 10303-1740
	USE FROM Extended_geometric_tolerance_arm;  -- ISO/TS 10303-1666
	USE FROM Part_template_shape_with_parameters_arm; -- ISO/TS 10303-1720

	REFERENCE FROM Specification_document_arm(get_document_definition);	-- ISO/TS 10303-1747

	TYPE ft_documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON documented_element_select WITH 
	   (Passage_technology,
	   Stratum_technology);
	END_TYPE; 
	
  TYPE ft_material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON material_item_select WITH
	(Filled_via_template,
	Passage_technology,
	Stratum_technology);
  END_TYPE;

	TYPE ft_requirement_assignment_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assignment_item WITH 
	   (Passage_technology,
      Stratum_technology,
      Stratum_technology_occurrence);
	END_TYPE; 

	SUBTYPE_CONSTRAINT ft_shape_feature_subtypes FOR Shape_feature; 
	    (ONEOF (Via_template_terminal,
         Component_termination_passage_template_terminal,
         Land_template_terminal));
	END_SUBTYPE_CONSTRAINT;

	SUBTYPE_CONSTRAINT ft_template_definition_subtypes FOR Template_definition; 
	    (ONEOF (Geometric_template,
	    Single_stratum_template,
		 Stratum_stack_model));
	END_SUBTYPE_CONSTRAINT;

  TYPE land_template_terminal_class = ENUMERATION OF
    (surface_point_class,
     edge_curve_class,
     edge_point_class,
     surface_area_class);
  END_TYPE;

  TYPE layer_position_type = ENUMERATION OF
    (secondary,
     all,
     external,
     primary,
     internal);
  END_TYPE;

  TYPE layer_purpose = ENUMERATION OF
    (other_signal,
     lands_only,
     power_or_ground,
     embedded_passive_capacitor_dielectric,
     embedded_passive_resistor);
  END_TYPE;

 	TYPE mt_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH  
		(Land_physical_template,
		Documentation_layer_technology);
	END_TYPE;

	TYPE mt_usage_concept = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON usage_concept WITH 
		(Land_template_terminal);
	END_TYPE;

  TYPE predefined_documentation_layer_purpose = ENUMERATION OF
    (soldermask,
     solderpaste,
     silkscreen,
     generic_layer,
     glue,
     gluemask,
     pastemask);
  END_TYPE;

  TYPE stiffness_class = ENUMERATION OF
    (fluid_like,
     conformal_coat,
     stiff_laminate);
  END_TYPE;

  ENTITY Blind_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      of_measure_orientation               : measure_orientation;
      datum_reference_layer                : Stratum_technology_occurrence;
      datum_reference_side                 : Stratum_technology_occurrence_link;
      bottom_distance_from_datum_reference : Shape_dimension_representation;
  END_ENTITY;

  ENTITY Component_termination_passage_template
    SUBTYPE OF (Continuous_template, Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_component_termination_passage_definition;
    INVERSE
      access_mechanisms : SET[2:?] OF component_termination_passage_template_terminal FOR associated_definition;
  END_ENTITY;

  ENTITY Component_termination_passage_template_interface_terminal
    SUBTYPE OF (Component_termination_passage_template_terminal);
  END_ENTITY;

  ENTITY Component_termination_passage_template_join_terminal
    SUBTYPE OF (Component_termination_passage_template_terminal);
      disallowed_inter_stratum_extent : OPTIONAL SET[1:?] OF Stratum_technology_occurrence_link;
  END_ENTITY;

  ENTITY Component_termination_passage_template_terminal
    ABSTRACT SUPERTYPE OF (ONEOF (Component_termination_passage_template_interface_terminal,
 Component_termination_passage_template_join_terminal))
    SUBTYPE OF (Shape_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition : Component_termination_passage_template;
      SELF\Shape_feature.connection_area                                : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;
  
  ENTITY Continuous_template
    SUBTYPE OF (Geometric_template);
  WHERE
    WR1 : SIZEOF(QUERY(s <* SELF\Geometric_template.shapes |
          NOT 
          (SIZEOF(['CONSTRUCTIVE_SOLID_GEOMETRY_2D_ARM.SINGLE_AREA_CSG_2D_MODEL',
                   'PART_TEMPLATE_EXTENSION_ARM.PLANAR_PATH_SHAPE_MODEL_WITH_PARAMETERS'] * TYPEOF(s))
           = 1)
          )) = 0;
  END_ENTITY;

  ENTITY Counterbore_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      smaller_passage : Unsupported_passage_template;
      larger_passage  : Blind_passage_template;
  END_ENTITY;

  ENTITY Countersunk_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      constant_diameter_passage : Unsupported_passage_template;
      tapered_passage           : Blind_passage_template;
  END_ENTITY;

  ENTITY Default_attachment_size_based_land_physical_template
    SUBTYPE OF (Land_physical_template, Shape_feature);
      SELF\Shape_feature.connection_area RENAMED minimum_attachment_region_size : OPTIONAL SET[1:1] OF Connection_zone_in_layout_template;
      maximum_attachment_region_size : OPTIONAL Connection_zone_in_layout_template;
    DERIVE
      SELF\Shape_element.containing_shape : Default_attachment_size_based_land_physical_template := SELF;
      SELF\Shape_feature.element_name : STRING := '';      
    INVERSE
      interface_access_mechanisms : SET[1:?] OF land_template_interface_terminal FOR associated_definition;
    WHERE
      WR1 : NOT (EXISTS(minimum_attachment_region_size) AND EXISTS(maximum_attachment_region_size)) OR (minimum_attachment_region_size[1] :<>: maximum_attachment_region_size);
      WR2 : NOT (EXISTS(minimum_attachment_region_size)) OR (SIZEOF(QUERY(mars <* minimum_attachment_region_size |
                 NOT(mars\Shape_element.containing_shape :=: SELF)
                 )) = 0);
      WR3 : maximum_attachment_region_size\Shape_element.containing_shape :=: SELF;
  END_ENTITY;

  ENTITY Default_component_termination_passage_definition
    SUBTYPE OF (Passage_technology);
      allowed_component_terminal_extent                        : Length_tolerance_characteristic;
      SELF\Passage_technology.as_finished_deposition_thickness : Length_tolerance_characteristic;
      SELF\Passage_technology.as_finished_passage_extent       : Length_tolerance_characteristic;
    INVERSE
      SELF\Passage_technology.deposition_material : SET [1:1] OF material_identification FOR items;
    WHERE
      WR1 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material);
  END_ENTITY;

  ENTITY Default_passage_based_land_physical_template
    ABSTRACT SUPERTYPE OF (ONEOF (Default_plated_passage_based_land_physical_template,
    Default_unsupported_passage_based_land_physical_template))
    SUBTYPE OF (Land_physical_template);
      minimum_fabrication_allowance : Length_data_element;
      of_passage_technology         : Passage_technology;
      minimum_annular_ring          : Length_data_element;
    UNIQUE
      UR1 : of_passage_technology, SELF\Stratum_feature_template.of_stratum_technology;
  END_ENTITY;

	ENTITY Default_plated_passage_based_land_physical_template
	  SUBTYPE OF (Default_passage_based_land_physical_template);
	 WHERE
	   WR1 : SELF\Default_passage_based_land_physical_template.of_passage_technology.plated_passage = TRUE;
	END_ENTITY;

  ENTITY Default_tapered_blind_via_definition
    SUBTYPE OF (Default_via_definition);
      as_finished_interior_passage_extent      : Length_tolerance_characteristic;
    WHERE
      WR1: less(as_finished_interior_passage_extent,as_finished_passage_extent);
  END_ENTITY;

  ENTITY Default_unsupported_passage_based_land_physical_template
    SUBTYPE OF (Default_passage_based_land_physical_template);
      SELF\Default_passage_based_land_physical_template.of_passage_technology : Default_unsupported_passage_definition;
  END_ENTITY;

  ENTITY Default_unsupported_passage_definition
    SUBTYPE OF (Passage_technology);
      SELF\Passage_technology.as_finished_passage_extent : Length_tolerance_characteristic;
  END_ENTITY;

  ENTITY Default_via_definition
    SUBTYPE OF (Passage_technology);
      SELF\Passage_technology.as_finished_deposition_thickness : Length_tolerance_characteristic;
      SELF\Passage_technology.as_finished_passage_extent       : Length_tolerance_characteristic;
    INVERSE
      SELF\Passage_technology.deposition_material : SET [1:1] OF material_identification FOR items;
    WHERE
      WR1 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material);
  END_ENTITY;

  ENTITY Design_layer_technology
    SUBTYPE OF (Stratum_technology);
      design_layer_purpose                                     : layer_purpose;
      SELF\Stratum_technology.minimum_finished_feature_size    : Length_data_element;
      SELF\Stratum_technology.minimum_finished_feature_spacing : Length_data_element;
   WHERE
	WR1 : (SIZEOF([SELF\Stratum_technology.stratum_material.electrical_conductivity_classification,
           SELF\Stratum_technology.stratum_material.thermal_conductivity_classification] *
           ['conductive']) >= 1) OR
       (SELF\Stratum_technology.stratum_material.magnetic_permeability_classification IN ['highly permeable']) OR
       (SELF\Stratum_technology.stratum_material.optical_insertion_loss_classification IN ['vacuum', 'very low loss', 'low loss']);
  END_ENTITY;

  ENTITY Documentation_layer_technology
    SUBTYPE OF (Stratum_technology);
      pre_defined_documentation_layer_purpose : OPTIONAL predefined_documentation_layer_purpose;
    INVERSE
	  externally_defined_documentation_layer_purpose : SET [0:1] OF External_source_identification FOR item;      
	WHERE
	  WR1: (EXISTS (pre_defined_documentation_layer_purpose)) XOR ((SIZEOF(externally_defined_documentation_layer_purpose)) = 1);
  END_ENTITY;

  ENTITY Filled_via_template
    SUBTYPE OF (Via_template);
    INVERSE
      fill_material : SET[1:1] OF Material_identification FOR items;
    WHERE
      WR1: 'CONDUCTIVITY_MATERIAL_ASPECTS_ARM.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (fill_material[1]);
  END_ENTITY;

  ENTITY Inter_stratum_feature_template
    SUPERTYPE OF (ONEOF(Component_termination_passage_template,
      Unsupported_passage_template,
      Via_template))
    SUBTYPE OF (Geometric_template);
      of_passage_technology : Passage_technology;
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
  END_ENTITY;

  ENTITY Land_physical_template
    SUPERTYPE OF (ONEOF (Default_passage_based_land_physical_template,
		 Default_attachment_size_based_land_physical_template))
    SUBTYPE OF (Stratum_feature_template);
      SELF\Single_stratum_template.of_stratum_technology : OPTIONAL SET[1:?] OF Design_layer_technology;
    INVERSE
      access_mechanisms                                   : SET[1:?] OF land_template_terminal FOR containing_shape;
      pre_defined_classification_code                     : SET[0:1] OF External_source_identification FOR item;      
    UNIQUE
      UR1 : pre_defined_classification_code;
    WHERE
      WR1 : SIZEOF(QUERY(ltjt <* access_mechanisms | NOT ('FABRICATION_TECHNOLOGY_ARM.LAND_TEMPLATE_JOIN_TERMINAL' IN TYPEOF(ltjt)))) = 0;
      WR2 : SIZEOF(QUERY(s <* SELF\Geometric_template.shapes |
             NOT ('CONSTRUCTIVE_SOLID_GEOMETRY_2D_ARM.SINGLE_BOUNDARY_CSG_2D_MODEL' IN TYPEOF(s)))) = 0;
      WR3 : SIZEOF(SELF\Geometric_template.shapes) > 0;
  END_ENTITY;

  ENTITY Land_template_interface_terminal
    SUBTYPE OF (Land_template_terminal);
      SELF\Land_template_terminal.associated_definition : Default_attachment_size_based_land_physical_template;
  END_ENTITY;

  ENTITY Land_template_join_terminal
    SUBTYPE OF (Land_template_terminal);
  END_ENTITY;

  ENTITY Land_template_terminal
    ABSTRACT SUPERTYPE OF (ONEOF (Land_template_join_terminal,
 Land_template_interface_terminal))
    SUBTYPE OF (Shape_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition : Land_physical_template;
      SELF\Shape_feature.connection_area : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;      
      connection_zone_category                                          : OPTIONAL SET[1:?] OF land_template_terminal_class;
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT (EXISTS(SELF\Shape_feature.connection_area)) OR EXISTS(connection_zone_category);
      WR2 : NOT (EXISTS(SELF\Shape_feature.connection_area)) OR (SIZEOF(SELF\Shape_feature.connection_area) = SIZEOF(connection_zone_category));
      WR3 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;

  ENTITY Material_removal_feature_template
    SUBTYPE OF (Single_stratum_continuous_template);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
      WR2 : SIZEOF(SELF\Geometric_template.shapes) > 0;
  END_ENTITY;

	ENTITY Passage_technology
		SUPERTYPE OF (ONEOF (Default_via_definition,
 			Default_component_termination_passage_definition,
 			Default_unsupported_passage_definition));
      name                              : STRING;
      as_finished_deposition_thickness  : OPTIONAL Length_tolerance_characteristic;
      as_finished_passage_extent        : OPTIONAL Length_tolerance_characteristic;      
      maximum_aspect_ratio              : OPTIONAL REAL;      
      plated_passage                    : BOOLEAN;
	 DERIVE
		specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'specification', 
  			'SPECIFICATION_DOCUMENT_ARM.PROCESS_SPECIFICATION');
     INVERSE
	  deposition_material : SET [0:1] OF material_identification FOR items;      
     UNIQUE
       UR1 : name;
	 WHERE
	  WR1 : NOT (SIZEOF(deposition_material) = 1) OR
            ('CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material[1]));
      WR2: NOT (plated_passage) OR (SIZEOF(deposition_material) = 1);
      WR3: NOT EXISTS(as_finished_deposition_thickness) OR (SIZEOF(deposition_material) = 1);
      WR4: NOT EXISTS(as_finished_deposition_thickness) OR (SIZEOF(deposition_material) = 1);
      WR5: NOT (plated_passage) OR
           (SIZEOF([deposition_material[1].electrical_conductivity_classification,
                    deposition_material[1].thermal_conductivity_classification] *
                   ['conductive']) >= 1);
	END_ENTITY;

  ENTITY Single_stratum_continuous_template
    ABSTRACT SUPERTYPE OF (ONEOF (Stratum_feature_template,
                                Material_removal_feature_template))  
    SUBTYPE OF (Continuous_template, Single_stratum_template);
  END_ENTITY;

  ENTITY Single_stratum_template
    ABSTRACT SUPERTYPE OF (Single_stratum_continuous_template)
    SUBTYPE OF (Template_definition);
      of_stratum_technology : OPTIONAL SET [1:?] OF stratum_technology;
  END_ENTITY;

  ENTITY Stratum_feature_template
    SUPERTYPE OF (Land_physical_template)
    SUBTYPE OF (Single_stratum_continuous_template);
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
  END_ENTITY;

  ENTITY Stratum_stack_model
    ABSTRACT SUPERTYPE
    SUBTYPE OF(Template_definition);
    DERIVE
      composing_occurrence : SET [1:?] OF Stratum_technology_occurrence := get_stack(composing_link);
    INVERSE
      composing_link : SET[1:?] OF Stratum_technology_occurrence_link FOR scope;
  END_ENTITY;

  ENTITY Stratum_technology
    SUPERTYPE OF (ONEOF (Design_layer_technology,
 Documentation_layer_technology));
      name                             : STRING;  
      layer_position                   : layer_position_type;
      stratum_thickness                : Length_tolerance_characteristic;
      minimum_finished_feature_size    : OPTIONAL Length_data_element;
      laminate_stiffness_class         : OPTIONAL stiffness_class;
      minimum_finished_feature_spacing : OPTIONAL Length_data_element;
      maximum_feature_size_requirement : OPTIONAL Length_data_element;
	DERIVE
		specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'specification', 
  			'SPECIFICATION_DOCUMENT_ARM.PROCESS_SPECIFICATION');
		surface_specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'surface specification', 
  			'SPECIFICATION_DOCUMENT_ARM.SURFACE_FINISH_SPECIFICATION');
   INVERSE
	  stratum_material : material_identification FOR items;      
    UNIQUE
      UR1 : name;
    WHERE
      WR1 : NOT (layer_position = layer_position_type.primary) OR ('FABRICATION_TECHNOLOGY_ARM.DESIGN_LAYER_TECHNOLOGY' IN TYPEOF(SELF));
      WR2 : NOT (layer_position = layer_position_type.secondary) OR ('FABRICATION_TECHNOLOGY_ARM.DESIGN_LAYER_TECHNOLOGY' IN TYPEOF(SELF));
	  WR3 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (stratum_material);
  END_ENTITY;

  ENTITY Stratum_technology_occurrence;
    name       : STRING; 
    definition : Stratum_technology;
  UNIQUE
    UR1: name;  
  END_ENTITY;

  ENTITY Stratum_technology_occurrence_link;
    precedent_sto  : Stratum_technology_occurrence;
    subsequent_sto : Stratum_technology_occurrence;
    scope          : Stratum_stack_model;
  WHERE
   WR1 : precedent_sto <> subsequent_sto;
  END_ENTITY;

  ENTITY Stratum_technology_occurrence_swap_relationship;
    primary_sto  : Stratum_technology_occurrence;
    secondary_sto : Stratum_technology_occurrence;
    scope : Stratum_stack_model;
   UNIQUE
    UR1 : primary_sto, scope;
    UR2 : secondary_sto, scope;
  WHERE
   WR1 : primary_sto <> secondary_sto;
   WR2 : (primary_sto IN scope\Stratum_stack_model.composing_occurrence) AND
         (secondary_sto IN scope\Stratum_stack_model.composing_occurrence);
  END_ENTITY;

  ENTITY Stratum_technology_swap_relationship;
    primary_stratum_technology   : Stratum_technology;
    secondary_stratum_technology : Stratum_technology;
   UNIQUE
    UR1: primary_stratum_technology;
    UR2: secondary_stratum_technology;
   WHERE 
    WR1 : NOT (('FABRICATION_TECHNOLOGY_ARM.DOCUMENTATION_LAYER_TECHNOLOGY' IN TYPEOF(primary_stratum_technology)) AND
              EXISTS(primary_stratum_technology\Documentation_layer_technology.pre_defined_documentation_layer_purpose))
          OR
          (primary_stratum_technology\Documentation_layer_technology.pre_defined_documentation_layer_purpose =
           secondary_stratum_technology\Documentation_layer_technology.pre_defined_documentation_layer_purpose);
    WR2: TYPEOF(primary_stratum_technology) = TYPEOF(secondary_stratum_technology);
    WR3: primary_stratum_technology\Stratum_technology.layer_position = layer_position_type.primary;
    WR4: secondary_stratum_technology\Stratum_technology.layer_position = layer_position_type.secondary;
    WR5: primary_stratum_technology <> secondary_stratum_technology;
  END_ENTITY;

  ENTITY Unsupported_passage_template
    SUPERTYPE OF (ONEOF (Counterbore_passage_template,
      Countersunk_passage_template,
      Blind_passage_template))
    SUBTYPE OF (Continuous_template, Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_unsupported_passage_definition;
  END_ENTITY;

  ENTITY Via_template
    SUBTYPE OF (Continuous_template, Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_via_definition;
    INVERSE
      access_mechanisms : SET[2:?] OF via_template_terminal FOR containing_shape;
  END_ENTITY;

  ENTITY Via_template_terminal
    SUBTYPE OF (Shape_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition : Via_template;
      disallowed_inter_stratum_extent                                   : OPTIONAL SET [1:?] OF Stratum_technology_occurrence_link;
      SELF\Shape_feature.connection_area : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;      
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;

FUNCTION get_electrical_conductivity
  (mi : SET[0:?] OF Material_identification) : BOOLEAN;
	REPEAT i := 1 to SIZEOF(mi) by 1;
	  IF ('CONDUCTIVITY_MATERIAL_ASPECT.'+'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' 
	  	IN TYPEOF (mi[i])) THEN
		  IF((EXISTS(mi[i].electrical_conductivity_classification)) AND 
		  (mi[i].electrical_conductivity_classification IN ['conductive', 'semi conductive', 'super conductive'])) THEN
	  		RETURN (TRUE);
	  	END_IF;	
	  END_IF;
	END_REPEAT;
	RETURN (FALSE);
END_FUNCTION;

 FUNCTION get_stack(input : SET OF Stratum_technology_occurrence_link) : SET OF Stratum_technology_occurrence;
  LOCAL
   sto : SET OF Stratum_technology_occurrence := [];
    i : INTEGER := 0;
  END_LOCAL;
  REPEAT  i := 1 TO SIZEOF(input) BY 1;
   sto := sto + input[i].precedent_sto + input[i].subsequent_sto;
  END_REPEAT;
  RETURN(sto);
  END_FUNCTION;

  FUNCTION less(input1 : Length_tolerance_characteristic;
              input2 : Length_tolerance_characteristic) : BOOLEAN;
    RETURN(TRUE);
  END_FUNCTION;

END_SCHEMA;
