(*
   $Id: arm.exp,v 1.60 2005/12/09 22:03:22 thomasrthurman Exp $
   ISO TC184/SC4/WG12 N3663 - ISO/CD-TS 10303-1670 Fabrication technology - EXPRESS ARM
*)

SCHEMA Fabrication_technology_arm;
	USE FROM Part_feature_location_arm; -- ISO/TS 10303-1714
	USE FROM Physical_layout_template_arm;	-- ISO/TS 10303-1722
	USE FROM Requirement_decomposition_arm;	-- ISO/TS 10303-1740
	USE FROM Extended_geometric_tolerance_arm;  -- ISO/TS 10303-1666

	REFERENCE FROM Specification_document_arm(get_document_definition);	-- ISO/TS 10303-1747

	TYPE ft_documented_element_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON documented_element_select WITH 
	   (Passage_technology,
	   Stratum_technology);
	END_TYPE; 

  TYPE ft_material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON material_item_select WITH
	(Passage_technology,
	Stratum_technology);
  END_TYPE;

	SUBTYPE_CONSTRAINT ft_placed_feature_subtypes FOR Placed_feature; 
	    (ONEOF (Via_template_terminal,
         Component_termination_passage_template_terminal,
         Land_template_terminal));
	END_SUBTYPE_CONSTRAINT;

	SUBTYPE_CONSTRAINT ft_template_definition_subtypes FOR Template_definition; 
	    (ONEOF (Material_removal_feature_template,
		 Stratum_feature_template,
		 Stratum_stack_model,
         Inter_stratum_feature_template));
	END_SUBTYPE_CONSTRAINT;

  TYPE land_template_terminal_class = ENUMERATION OF
    (surface_point_class,
     edge_curve_class,
     edge_point_class,
     surface_area_class);
  END_TYPE;

  TYPE layer_position_type = ENUMERATION OF
    (secondary,
     all,
     external,
     primary,
     internal);
  END_TYPE;

  TYPE layer_purpose = ENUMERATION OF
    (other_signal,
     lands_only,
     power_or_ground,
     embedded_passive_capacitor_dielectric,
     embedded_passive_resistor);
  END_TYPE;

 	TYPE mt_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH  
		(Land_physical_template,
		Documentation_layer_technology);
	END_TYPE;

	TYPE mt_usage_concept = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON usage_concept WITH 
		(Land_template_terminal);
	END_TYPE;

  TYPE pca_product_design_object_category = ENUMERATION OF
    (assembly_component_category,
     assembly_module_category,
     assembly_module_component_category,
     assembly_module_component_terminal_category,
     assembly_module_macro_component_category,
     assembly_module_macro_component_join_terminal_category,
     bare_die_component_category,
     bare_die_component_terminal_category,
     bonded_conductive_base_blind_via_category,
     buried_via_category,
     cable_component_category,
     component_feature_category,
     component_mounting_feature_category,
     component_termination_passage_category,
     component_termination_passage_and_contact_size_dependent_land_category,
     component_termination_passage_interface_terminal_category,
     component_termination_passage_join_terminal_category,
     conductive_interconnect_element_terminal_category,
     conductive_interconnect_element_with_pre_defined_transitions_category,
     conductive_interconnect_element_with_user_defined_single_transition_category,
     connected_area_component_category,
     contact_size_dependent_land_category,
     cutout_category,
     cutout_edge_segment_category,
     dielectric_material_passage_category,
     electrical_isolation_laminate_component_category,
     embedded_physical_component_terminal_category,
     fiducial_category,
     fill_area_category,
     filled_area_material_removal_laminate_component_category,
     inter_stratum_feature_category,
     interconnect_component_interface_terminal_category,
     interconnect_component_join_terminal_category,
     interconnect_module_component_category,
     interconnect_module_component_stratum_based_terminal_category,
     interconnect_module_component_surface_feature_category,
     interconnect_module_component_terminal_category,
     interconnect_module_edge_category,
     interconnect_module_edge_segment_category,
     interconnect_module_macro_component_category,
     interconnect_module_macro_component_join_terminal_category,
     interface_access_material_removal_laminate_component_category,
     interface_access_stratum_feature_template_component_category,
     interface_component_category,
     interfacial_connection_category,
     internal_probe_access_area_category,
     join_two_physical_connectivity_definition_supporting_inter_stratum_feature_category,
     join_two_physical_connectivity_definition_supporting_printed_component_category,
     laminate_component_category,
     laminate_text_component_category,
     laminate_text_string_component_category,
     land_category,
     land_interface_terminal_category,
     land_join_terminal_category,
     material_removal_laminate_component_category,
     minimally_defined_component_terminal_category,
     movable_packaged_component_join_terminal_category,
     multi_layer_material_removal_laminate_component_category,
     multi_layer_stratum_feature_template_component_category,
     non_conductive_base_blind_via_category,
     packaged_component_category,
     packaged_component_join_terminal_category,
     packaged_connector_component_category,
     packaged_connector_component_interface_terminal_category,
     partially_plated_cutout_category,
     partially_plated_interconnect_module_edge_category,
     physical_component_category,
     physical_connectivity_interrupting_cutout_category,
     physical_laminate_component_category,
     physical_network_supporting_inter_stratum_feature_category,
     plated_conductive_base_blind_via_category,
     plated_cutout_category,
     plated_cutout_edge_segment_category,
     plated_interconnect_module_edge_category,
     plated_interconnect_module_edge_segment_category,
     plated_passage_category,
     plated_passage_or_unsupported_passage_category,
     primary_stratum_indicator_symbol_category,
     printed_component_join_terminal_category,
     printed_connector_component_interface_terminal_category,
     probe_access_area_category,
     routed_interconnect_component_category,
     routed_physical_component_category,
     special_symbol_laminate_component_category,
     stratum_feature_category,
     stratum_feature_template_component_category,
     thermal_isolation_laminate_component_category,
     unrouted_conductive_interconnect_element_category,
     unsupported_passage_category,
     unsupported_passage_dependent_land_category,
     via_category,
     via_terminal_category);
  END_TYPE;

  TYPE predefined_documentation_layer_purpose = ENUMERATION OF
    (soldermask,
     solderpaste,
     silkscreen,
     generic_layer,
     glue,
     gluemask,
     pastemask);
  END_TYPE;

  TYPE spacing_type = ENUMERATION OF
    (nearest_boundary,
     centroid,
     furthest_boundary);
  END_TYPE;

  TYPE stiffness_class = ENUMERATION OF
    (fluid_like,
     conformal_coat,
     stiff_laminate);
  END_TYPE;

  ENTITY Blind_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      of_measure_orientation               : measure_orientation;
      datum_reference_layer                : Stratum_technology_occurrence;
      datum_reference_side                 : Stratum_technology_occurrence_link;
      bottom_distance_from_datum_reference : Shape_dimension_representation;
  END_ENTITY;

  ENTITY Component_termination_passage_template
    SUBTYPE OF (Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_component_termination_passage_definition;
    INVERSE
      access_mechanisms : SET[2:?] OF component_termination_passage_template_terminal FOR associated_definition;
  END_ENTITY;

  ENTITY Component_termination_passage_template_interface_terminal
    SUBTYPE OF (Component_termination_passage_template_terminal);
  END_ENTITY;

  ENTITY Component_termination_passage_template_join_terminal
    SUBTYPE OF (Component_termination_passage_template_terminal);
      disallowed_inter_stratum_extent : OPTIONAL SET[1:?] OF Stratum_technology_occurrence_link;
  END_ENTITY;

  ENTITY Component_termination_passage_template_terminal
    ABSTRACT SUPERTYPE OF (ONEOF (Component_termination_passage_template_interface_terminal,
 Component_termination_passage_template_join_terminal))
    SUBTYPE OF (Placed_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition    : Component_termination_passage_template;
      terminal_connection_zone : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;
    INVERSE
      terminal_shape : SET[0:1] OF geometric_model_constituent_relationship FOR constituent_element;
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;

  ENTITY Counterbore_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      smaller_passage : Unsupported_passage_template;
      larger_passage  : Blind_passage_template;
  END_ENTITY;

  ENTITY Countersunk_passage_template
    SUBTYPE OF (Unsupported_passage_template);
      constant_diameter_passage : Unsupported_passage_template;
      tapered_passage           : Blind_passage_template;
  END_ENTITY;

  ENTITY Default_attachment_size_based_land_physical_template
    SUBTYPE OF (Land_physical_template);
      minimum_attachment_region_size : OPTIONAL Connection_zone_in_layout_template;
      maximum_attachment_region_size : OPTIONAL Connection_zone_in_layout_template;
    INVERSE
      interface_access_mechanisms : SET[1:?] OF land_template_interface_terminal FOR associated_definition;
    WHERE
      WR1 : NOT (EXISTS(minimum_attachment_region_size) AND EXISTS(maximum_attachment_region_size)) OR (minimum_attachment_region_size :<>: maximum_attachment_region_size);
  END_ENTITY;

  ENTITY Default_component_termination_passage_definition
    SUBTYPE OF (Passage_technology);
      allowed_component_terminal_extent                        : Tolerance_characteristic;
      SELF\Passage_technology.as_finished_deposition_thickness : Tolerance_characteristic;
      SELF\Passage_technology.as_finished_passage_extent       : Tolerance_characteristic;
    INVERSE
      SELF\Passage_technology.deposition_material : SET [1:1] OF material_identification FOR items;
    WHERE
      WR1 : ('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(allowed_component_terminal_extent)) OR
        ('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(allowed_component_terminal_extent)) OR
        (SIZEOF(QUERY(it <* allowed_component_terminal_extent\Representation.items |
          NOT('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(allowed_component_terminal_extent\Representation.items))
         )) = 0);
      WR2 : NOT('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(allowed_component_terminal_extent)) OR
        (SIZEOF(QUERY(it <* allowed_component_terminal_extent\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(allowed_component_terminal_extent\Representation.items))
           )) = 1);
      WR3 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material);
  END_ENTITY;

  ENTITY Default_passage_based_land_physical_template
    ABSTRACT SUPERTYPE OF (ONEOF (Default_plated_passage_based_land_physical_template,
    Default_unsupported_passage_based_land_physical_template))
    SUBTYPE OF (Land_physical_template);
      minimum_fabrication_allowance : Length_data_element;
      of_passage_technology         : Passage_technology;
      of_stratum_extent             : SET [1:?] OF Stratum_technology_occurrence_link;
      minimum_annular_ring          : Length_data_element;
    UNIQUE
      UR1 : of_passage_technology, SELF\Stratum_feature_template.of_stratum_technology;
    WHERE
      WR1 : SIZEOF(of_stratum_extent * of_passage_technology.as_finished_inter_stratum_extent)
            = SIZEOF(of_stratum_extent);
  END_ENTITY;

	ENTITY Default_plated_passage_based_land_physical_template
	  SUBTYPE OF (Default_passage_based_land_physical_template);
	 WHERE
	   WR1 : SELF\Default_passage_based_land_physical_template.of_passage_technology.plated_passage = TRUE;
	END_ENTITY;

  ENTITY Default_tapered_blind_via_definition
    SUBTYPE OF (Default_via_definition);
      as_finished_interior_passage_extent      : Tolerance_characteristic;
    WHERE
      WR1: less(as_finished_interior_passage_extent,as_finished_passage_extent);
      WR2 : ('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_interior_passage_extent)) OR
        ('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_interior_passage_extent)) OR
        (SIZEOF(QUERY(it <* as_finished_interior_passage_extent\Representation.items |
          NOT('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_interior_passage_extent\Representation.items))
         )) = 0);
      WR3 : NOT('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_interior_passage_extent)) OR
        (SIZEOF(QUERY(it <* as_finished_interior_passage_extent\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_interior_passage_extent\Representation.items))
           )) = 1);
  END_ENTITY;

  ENTITY Default_unsupported_passage_based_land_physical_template
    SUBTYPE OF (Default_passage_based_land_physical_template);
      SELF\Default_passage_based_land_physical_template.of_passage_technology : Default_unsupported_passage_definition;
  END_ENTITY;

  ENTITY Default_unsupported_passage_definition
    SUBTYPE OF (Passage_technology);
      SELF\Passage_technology.as_finished_passage_extent : Tolerance_characteristic;
  END_ENTITY;

  ENTITY Default_via_definition
    SUBTYPE OF (Passage_technology);
      SELF\Passage_technology.as_finished_deposition_thickness : Tolerance_characteristic;
      SELF\Passage_technology.as_finished_passage_extent       : Tolerance_characteristic;
    INVERSE
      SELF\Passage_technology.deposition_material : SET [1:1] OF material_identification FOR items;
    WHERE
      WR1 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material);
  END_ENTITY;

  ENTITY Dependent_material_removal_feature_template
    SUBTYPE OF (Material_removal_feature_template);
      associated_template : Land_physical_template;
  END_ENTITY;

  ENTITY Design_layer_technology
    SUBTYPE OF (Stratum_technology);
      design_layer_purpose                                     : layer_purpose;
      SELF\Stratum_technology.minimum_finished_feature_size    : Length_data_element;
      SELF\Stratum_technology.minimum_finished_feature_spacing : Length_data_element;
   WHERE
	WR1 : (SIZEOF([SELF\Stratum_technology.stratum_material.electrical_conductivity_classification,
           SELF\Stratum_technology.stratum_material.thermal_conductivity_classification] *
           ['conductive']) >= 1) OR
       (SELF\Stratum_technology.stratum_material.magnetic_permeability_classification IN ['highly permeable']) OR
       (SELF\Stratum_technology.stratum_material.optical_insertion_loss_classification IN ['vacuum', 'very low loss', 'low loss']);
  END_ENTITY;

  ENTITY Design_stack_model -- choose some of the Stratum_technology_occurrence
    SUBTYPE OF(Stratum_stack_model);
      reference_model : OPTIONAL Library_stack_model; 
    INVERSE
      passage: SET [1:?] OF Passage_technology_allocation_to_stack_model for associated_stackup;
    WHERE
      WR1: NOT EXISTS(reference_model) OR 
          ((SELF\Stratum_stack_model.composing_occurrence * reference_model\Stratum_stack_model.composing_occurrence) = 
           SELF\Stratum_stack_model.composing_occurrence);
  END_ENTITY;

  ENTITY Documentation_layer_technology
    SUBTYPE OF (Stratum_technology);
      pre_defined_documentation_layer_purpose : OPTIONAL predefined_documentation_layer_purpose;
    INVERSE
	  externally_defined_documentation_layer_purpose : SET [0:1] OF External_source_identification FOR item;      
	WHERE
	  WR1: (EXISTS (pre_defined_documentation_layer_purpose)) XOR ((SIZEOF(externally_defined_documentation_layer_purpose)) = 1);
  END_ENTITY;

  ENTITY Inter_stratum_feature_template
    SUPERTYPE OF (ONEOF(Component_termination_passage_template,
      Unsupported_passage_template,
      Via_template))
    SUBTYPE OF (Template_definition);
      of_passage_technology : Passage_technology;
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
  END_ENTITY;

  ENTITY Land_physical_template
    SUPERTYPE OF (ONEOF (Default_passage_based_land_physical_template,
		 Default_attachment_size_based_land_physical_template))
    SUBTYPE OF (Stratum_feature_template);
      SELF\Stratum_feature_template.of_stratum_technology : OPTIONAL SET[1:?] OF Design_layer_technology;
    INVERSE
      access_mechanisms                                   : SET[1:?] OF land_template_terminal FOR containing_shape;
      pre_defined_classification_code                     : SET[0:1] OF External_source_identification FOR item;      
    UNIQUE
      UR1 : pre_defined_classification_code;
    WHERE
      WR1 : SIZEOF(QUERY(ltjt <* access_mechanisms | NOT ('FABRICATION_TECHNOLOGY_ARM.LAND_TEMPLATE_JOIN_TERMINAL' IN TYPEOF(ltjt)))) = 0;
  END_ENTITY;

  ENTITY Land_template_interface_terminal
    SUBTYPE OF (Land_template_terminal);
      SELF\Land_template_terminal.associated_definition : Default_attachment_size_based_land_physical_template;
  END_ENTITY;

  ENTITY Land_template_join_terminal
    SUBTYPE OF (Land_template_terminal);
  END_ENTITY;

  ENTITY Land_template_terminal
    ABSTRACT SUPERTYPE OF (ONEOF (Land_template_join_terminal,
 Land_template_interface_terminal))
    SUBTYPE OF (Placed_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition : Land_physical_template;
      terminal_connection_zone                                          : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;
      connection_zone_category                                          : OPTIONAL SET[1:?] OF land_template_terminal_class;
    INVERSE
      SELF\Placed_feature.feature_shape : SET[0:1] OF geometric_model_constituent_relationship FOR constituent_element;
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT (EXISTS(terminal_connection_zone)) OR EXISTS(connection_zone_category);
      WR2 : NOT (EXISTS(terminal_connection_zone)) OR (SIZEOF(terminal_connection_zone) = SIZEOF(connection_zone_category));
      WR3 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;

  ENTITY Layout_spacing_requirement_occurrence
    SUBTYPE OF (Requirement_definition_property);
      reference_design_object_category                                   : pca_product_design_object_category;
      dependent_design_object_category                                   : pca_product_design_object_category;
      SELF\Requirement_definition_property.required_characteristic       : Tolerance_characteristic;
      of_spacing_type                                                    : spacing_type;
    UNIQUE
      UR1 : reference_design_object_category,
 dependent_design_object_category;
    WHERE
      WR1 : 'VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(SELF\Requirement_definition_property.required_characteristic.items[1]);
  END_ENTITY;

-- has many Stratum_technology_occurrence, more than may be actually used
  ENTITY Library_stack_model 
    SUBTYPE OF(Stratum_stack_model);
  END_ENTITY;

  ENTITY Material_addition_feature_template
    SUBTYPE OF (Stratum_feature_template);
  END_ENTITY;

  ENTITY Material_removal_feature_template
    SUPERTYPE OF (Dependent_material_removal_feature_template)
    SUBTYPE OF (Template_definition);
      of_stratum_technology : OPTIONAL SET[1:?] OF Stratum_technology;
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
  END_ENTITY;

	ENTITY Passage_technology
		SUPERTYPE OF (ONEOF (Default_via_definition,
 			Default_component_termination_passage_definition,
 			Default_unsupported_passage_definition));
      name                              : STRING;
      as_finished_deposition_thickness  : OPTIONAL Tolerance_characteristic;
      as_finished_passage_extent        : OPTIONAL Tolerance_characteristic;      
      maximum_aspect_ratio              : OPTIONAL REAL;      
      plated_passage                    : BOOLEAN;
	 DERIVE
		specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'specification', 
  			'SPECIFICATION_DOCUMENT_ARM.PROCESS_SPECIFICATION');
     INVERSE
	  deposition_material : SET [0:1] OF material_identification FOR items;      
     UNIQUE
       UR1 : name;
	 WHERE
	  WR1 : NOT (SIZEOF(deposition_material) = 1) OR
            ('CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (deposition_material[1]));
      WR2: NOT (plated_passage) OR (SIZEOF(deposition_material) = 1);
      WR3: NOT EXISTS(as_finished_deposition_thickness) OR (SIZEOF(deposition_material) = 1);
      WR4: NOT EXISTS(as_finished_deposition_thickness) OR (SIZEOF(deposition_material) = 1);
      WR5: NOT (plated_passage) OR
           (SIZEOF([deposition_material[1].electrical_conductivity_classification,
                    deposition_material[1].thermal_conductivity_classification] *
                   ['conductive']) >= 1);
      WR6 : ('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_passage_extent)) OR
        ('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_passage_extent)) OR
        (SIZEOF(QUERY(it <* as_finished_passage_extent\Representation.items |
          NOT('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_passage_extent\Representation.items))
         )) = 0);
      WR7 : NOT('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_passage_extent)) OR
        (SIZEOF(QUERY(it <* as_finished_passage_extent\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_passage_extent\Representation.items))
           )) = 1);
      WR8 : ('CHARACTERISTIC_ARM.STATISTICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_deposition_thickness)) OR
        ('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_deposition_thickness)) OR
        (SIZEOF(QUERY(it <* as_finished_deposition_thickness\Representation.items |
          NOT('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_deposition_thickness\Representation.items))
         )) = 0);
      WR9 : NOT('CHARACTERISTIC_ARM.SYMMETRICAL_TOLERANCE_CHARACTERISTIC' IN TYPEOF(as_finished_deposition_thickness)) OR
        (SIZEOF(QUERY(it <* as_finished_deposition_thickness\Representation.items |
        ('VALUE_WITH_UNIT_EXTENSION_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(as_finished_deposition_thickness\Representation.items))
           )) = 1);
	END_ENTITY;

  ENTITY Passage_technology_allocation_to_stack_model;
      allocated_technology : Passage_technology;
      from_stratum_technology_occurrence : OPTIONAL Stratum_technology_occurrence;
      to_stratum_technology_occurrence : OPTIONAL Stratum_technology_occurrence;
      stratum_technology_sequence : OPTIONAL SET [1:?] OF Stratum_technology_occurrence_link;
      associated_stackup : SET [1:?] OF Design_stack_model;
   WHERE 
     WR1: (NOT EXISTS(from_stratum_technology_occurrence) OR
               (from_stratum_technology_occurrence IN associated_stackup.composing_occurrence)) AND
          (NOT EXISTS(to_stratum_technology_occurrence) OR
               (to_stratum_technology_occurrence IN associated_stackup.composing_occurrence));
     WR2: EXISTS(stratum_technology_sequence) OR
               (from_stratum_technology_occurrence = to_stratum_technology_occurrence);
     WR3: NOT (from_stratum_technology_occurrence XOR to_stratum_technology_occurrence);
     WR4: stratum_technology_sequence XOR from_stratum_technology_occurrence;
     WR5: SIZEOF(QUERY(ast <* associated_stackup | 
               (SIZEOF(QUERY(sts <* stratum_technology_sequence | NOT(ast IN sts.scope))) = 0)
               )) = 0;
     WR6: SIZEOF(get_stack(stratum_technology_sequence)) = (SIZEOF(stratum_technology_sequence) + 1);     
  END_ENTITY;

  ENTITY Stratum_feature_template
    SUPERTYPE OF (ONEOF (Land_physical_template,
 Material_addition_feature_template))
    SUBTYPE OF (Template_definition);
      of_stratum_technology : OPTIONAL SET[1:?] OF Stratum_technology;
    WHERE
      WR1 : NOT EXISTS(SELF\Product_view_definition.name);
  END_ENTITY;

  ENTITY Stratum_stack_model
    ABSTRACT SUPERTYPE OF(ONEOF(Library_stack_model,Design_stack_model))
    SUBTYPE OF(Template_definition);
    DERIVE
      composing_occurrence : SET [1:?] OF Stratum_technology_occurrence := get_stack(composing_link);
    INVERSE
      composing_link : SET[1:?] OF Stratum_technology_occurrence_link FOR scope;
  END_ENTITY;

  ENTITY Stratum_technology
    SUPERTYPE OF (ONEOF (Design_layer_technology,
 Documentation_layer_technology));
      name                             : STRING;  
      layer_position                   : layer_position_type;
      stratum_thickness                : Tolerance_characteristic;
      minimum_finished_feature_size    : OPTIONAL Length_data_element;
      laminate_stiffness_class         : OPTIONAL stiffness_class;
      minimum_finished_feature_spacing : OPTIONAL Length_data_element;
      maximum_feature_size_requirement : OPTIONAL Length_data_element;
	DERIVE
		specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'specification', 
  			'SPECIFICATION_DOCUMENT_ARM.PROCESS_SPECIFICATION');
		surface_specification: SET[0:1] OF Document_definition :=
  			get_document_definition(SELF, 'surface specification', 
  			'SPECIFICATION_DOCUMENT_ARM.SURFACE_FINISH_SPECIFICATION');
   INVERSE
	  stratum_material : material_identification FOR items;      
    UNIQUE
      UR1 : name;
    WHERE
      WR1 : NOT (layer_position = layer_position_type.primary) OR ('FABRICATION_TECHNOLOGY_ARM.DESIGN_LAYER_TECHNOLOGY' IN TYPEOF(SELF));
      WR2 : NOT (layer_position = layer_position_type.secondary) OR ('FABRICATION_TECHNOLOGY_ARM.DESIGN_LAYER_TECHNOLOGY' IN TYPEOF(SELF));
	  WR3 : 'CONDUCTIVITY_MATERIAL_ASPECTS.'+ 'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' IN TYPEOF (stratum_material);
  END_ENTITY;

  ENTITY Stratum_technology_occurrence;
    name       : STRING; 
    definition : Stratum_technology;
  UNIQUE
    UR1: name;  
   --also don't want to disallow multiple references to one stratum_technology!
  END_ENTITY;

  ENTITY Stratum_technology_occurrence_link;
    precedent_sto  : Stratum_technology_occurrence;
    subsequent_sto : Stratum_technology_occurrence;
    scope          : Stratum_stack_model;
  WHERE
   WR1 : precedent_sto <> subsequent_sto;
--  IPs
--  IP1: acyclic stos
  END_ENTITY;

  ENTITY Stratum_technology_swap_relationship;
    primary_stratum_technology   : Stratum_technology;
    secondary_stratum_technology : Stratum_technology;
   UNIQUE
    UR1: primary_stratum_technology;
    UR2: secondary_stratum_technology;
   WHERE 
    WR1 : NOT ('FABRICATION_TECHNOLOGY_ARM.DOCUMENTATION_LAYER_TECHNOLOGY' IN 
          TYPEOF(primary_stratum_technology)) OR
          (primary_stratum_technology\Documentation_layer_technology.pre_defined_documentation_layer_purpose =
           secondary_stratum_technology\Documentation_layer_technology.pre_defined_documentation_layer_purpose);
    WR2: TYPEOF(primary_stratum_technology) = TYPEOF(secondary_stratum_technology);
    WR3: primary_stratum_technology\Stratum_technology.layer_position = primary;
    WR4: secondary_stratum_technology\Stratum_technology.layer_position = secondary;
    WR5: primary_stratum_technology <> secondary_stratum_technology;
  END_ENTITY;

  ENTITY Unsupported_passage_template
    SUPERTYPE OF (ONEOF (Counterbore_passage_template,
      Countersunk_passage_template,
      Blind_passage_template))
    SUBTYPE OF (Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_unsupported_passage_definition;
  END_ENTITY;

  ENTITY Via_template
    SUBTYPE OF (Inter_stratum_feature_template);
      SELF\Inter_stratum_feature_template.of_passage_technology : Default_via_definition;
    INVERSE
      access_mechanisms : SET[2:?] OF via_template_terminal FOR containing_shape;
  END_ENTITY;

  ENTITY Via_template_terminal
    SUBTYPE OF (Placed_feature);
      SELF\Shape_element.containing_shape RENAMED associated_definition : Via_template;
      disallowed_inter_stratum_extent                                   : OPTIONAL SET [1:?] OF Stratum_technology_occurrence_link;
      terminal_connection_zone                                          : OPTIONAL SET[1:?] OF Connection_zone_in_layout_template;
    INVERSE
      SELF\Placed_feature.feature_shape : SET[0:1] OF geometric_model_constituent_relationship FOR constituent_element;
    UNIQUE
      UR1 : SELF\Shape_element.element_name,
 associated_definition;
    WHERE
      WR1 : NOT EXISTS(SELF\Shape_element.description);
  END_ENTITY;

  FUNCTION bag_to_set(
    the_bag : BAG OF GENERIC : intype
  ) : SET OF GENERIC : intype;

    LOCAL
      the_set : SET OF GENERIC : intype := [];
      i       : INTEGER;
    END_LOCAL;

    IF SIZEOF(the_bag) > 0 THEN
      REPEAT i := 1 TO HIINDEX(the_bag);
        the_set := the_set + the_bag[i];
      END_REPEAT;
    END_IF;
    RETURN(the_set);
  END_FUNCTION;

FUNCTION get_electrical_conductivity
  (mi : SET[0:?] OF Material_identification) : BOOLEAN;
	REPEAT i := 1 to SIZEOF(mi) by 1;
	  IF ('CONDUCTIVITY_MATERIAL_ASPECT.'+'MATERIAL_IDENTIFICATION_WITH_CONDUCTIVITY_CLASSIFICATION' 
	  	IN TYPEOF (mi[i])) THEN
		  IF((EXISTS(mi[i].electrical_conductivity_classification)) AND 
		  (mi[i].electrical_conductivity_classification IN ['conductive', 'semi conductive', 'super conductive'])) THEN
	  		RETURN (TRUE);
	  	END_IF;	
	  END_IF;
	END_REPEAT;
	RETURN (FALSE);
END_FUNCTION;

 FUNCTION get_stack(input : SET OF Stratum_technology_occurrence_link) : SET OF Stratum_technology_occurrence;
  LOCAL
   sto : SET OF Stratum_technology_occurrence := [];
    i : INTEGER := 0;
  END_LOCAL;
  REPEAT  i := 1 TO SIZEOF(input) BY 1;
   sto := sto + input[i].precedent_sto + input[i].subsequent_sto;
  END_REPEAT;
  RETURN(sto);
  END_FUNCTION;


  FUNCTION less(input1 : Tolerance_characteristic;
              input2 : Tolerance_characteristic) : BOOLEAN;
    RETURN(TRUE);
  END_FUNCTION;

END_SCHEMA;
