(*
   $Id: arm.exp,v 1.8 2006/01/20 08:43:42 liutkuviene Exp $
   ISO TC184/SC4/WG3 N2035 - ISO/CD-TS 10303-1621 AP210 interconnect requirement allocation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1662
*)

SCHEMA Ap210_interconnect_requirement_allocation_arm;
	USE FROM Ap210_interconnect_functional_requirements_arm;	-- ISO/TS 10303-1619
	USE FROM Ap210_interconnect_physical_requirements_arm;	-- ISO/TS 10303-1620
END_SCHEMA;

