(* 
 $Id: arm.exp,v 1.8 2002/07/09 10:20:44 goset1 Exp $
 N1204 - ISO/TS - 10303-1127 File identification - EXPRESS ARM 
*)

SCHEMA File_identification_arm;

ENTITY Digital_file
SUBTYPE OF (File);
END_ENTITY;

ENTITY File
ABSTRACT SUPERTYPE OF (ONEOF(Digital_file, Hardcopy));
  id : STRING;
  version : OPTIONAL STRING;
  contained_data_type : OPTIONAL STRING;
END_ENTITY;

ENTITY Hardcopy
SUBTYPE OF (File);
END_ENTITY;

END_SCHEMA;

