(*
   $Id: arm.exp,v 1.18 2005/04/04 09:13:39 liutkus Exp $
   ISO TC184/SC4/WG12 N3291 - ISO/CD-TS 10303-1634 Assembly component placement requirements - EXPRESS ARM
*)

SCHEMA Assembly_component_placement_requirements_arm;

	USE FROM Assembly_module_with_interconnect_component_arm;	-- ISO/TS 10303-1643
	
	REFERENCE FROM Requirement_decomposition_arm(get_rvd);	-- ISO/TS 10303-1740
		
	TYPE restriction_basis_item = EXTENSIBLE SELECT(
		Requirement_definition_property,
   		Part_feature);
	END_TYPE;

TYPE acpr_requirement_assignment_item = EXTENSIBLE SELECT BASED_ON requirement_assignment_item WITH 
    (restriction_basis_item,
  	Placement_group);
END_TYPE; 

TYPE assembly_product_design_object_category = ENUMERATION OF
    (assembly_component_category,
     assembly_module_component_category,
     assembly_module_component_terminal_category,
     assembly_module_macro_component_category,
     assembly_module_macro_component_join_terminal_category,
     bare_die_component_category,
     bare_die_component_terminal_category,
     buried_via_category,
     cable_component_category,
     component_feature_category,
     component_termination_passage_category,
     conductive_interconnect_element_with_pre_defined_transitions_category,
     cutout_category,
     cutout_edge_segment_category,
     dielectric_material_passage_category,
     embedded_component_terminal_category,
     fiducial_category,
     fill_area_category,
     inter_stratum_feature_category,
     interconnect_component_interface_terminal_category,
     interconnect_component_join_terminal_category,
     interconnect_module_component_category,
     interconnect_module_component_stratum_based_terminal_category,
     interconnect_module_component_surface_feature_category,
     interconnect_module_component_terminal_category,
     interconnect_module_edge_category,
     interconnect_module_edge_segment_category,
     interconnect_module_macro_component_category,
     interconnect_module_macro_component_join_terminal_category,
     interface_access_material_removal_laminate_component_category,
     interface_access_stratum_feature_template_component_category,
     interface_component_category,
     interfacial_connection_category,
     internal_probe_access_area_category,
     laminate_component_category,
     minimally_defined_component_terminal_category,
     packaged_component_category,
     packaged_component_join_terminal_category,
     packaged_connector_component_category,
     packaged_connector_component_interface_terminal_category,
     physical_component_category,
     plated_passage_or_unsupported_passage_category,
     routed_interconnect_component_category,
     routed_physical_component_category,
     stratum_feature_category,
     via_category);
END_TYPE;

TYPE assembly_spacing_type = ENUMERATION OF
    (nearest_boundary,
     centroid,
     furthest_boundary);
END_TYPE;

  ENTITY Assembly_spacing_requirement_occurrence
    SUBTYPE OF (Requirement_definition_property);
      reference_design_object_category                                   : assembly_product_design_object_category;
      dependent_design_object_category                                   : assembly_product_design_object_category;
      SELF\Requirement_definition_property.required_coordinated_characteristic : SET[1:1] OF Tolerance_characteristic;
      of_spacing_type                                                    : assembly_spacing_type;
    UNIQUE
      UR1 : reference_design_object_category,
 dependent_design_object_category;
    WHERE
      WR1 : 'ASSEMBLY_TECHNOLOGY_ARM.LENGTH_DATA_ELEMENT' IN TYPEOF(SELF\Requirement_definition_property.required_coordinated_characteristic[1].items[1]);
  END_ENTITY;

  ENTITY Component_group_assignment;
      associated_group   : Placement_group;
      assigned_component : Assembly_component;
  END_ENTITY;

  ENTITY Component_placement_restriction_assignment;
      maximum_negative_component_height : OPTIONAL Datum_based_length_measure;
      maximum_positive_component_height : OPTIONAL Datum_based_length_measure;
      area                              : OPTIONAL Mounting_restriction_area;
      volume                            : OPTIONAL Mounting_restriction_volume;
      requirement                       : Item_restricted_requirement_occurrence;
      components_permitted              : BOOLEAN;
      maximum_mounting_clearance        : OPTIONAL Datum_based_length_measure;
      minimum_mounting_clearance        : OPTIONAL Datum_based_length_measure;
    WHERE
      WR1 : EXISTS(area) OR EXISTS(volume);
  END_ENTITY;

  ENTITY Item_restricted_requirement_occurrence
    SUBTYPE OF (Requirement_definition_property);
      basis : restriction_basis_item;
  END_ENTITY;

  ENTITY Mounting_restriction_area
    SUBTYPE OF (Non_feature_shape_element);
      mounting_surface                     : Interconnect_module_component_surface_feature;
      SELF\Non_feature_shape_element.scope : Assembly_module;
    WHERE
      WR1 : 'ASSEMBLY_COMPONENT_PLACEMENT_REQUIREMENTS_ARM.CONSTRUCTIVE_GEOMETRY' IN TYPEOF(SELF\Non_feature_shape_element.element_shape);
  END_ENTITY;

  ENTITY Mounting_restriction_volume
    SUBTYPE OF (Non_feature_shape_element);
      mounting_surface                     : Interconnect_module_component_surface_feature;
      SELF\Non_feature_shape_element.scope : Assembly_module;
    INVERSE
      volume : non_feature_shape_definition FOR associated_element;
    WHERE
      WR1 : 'ASSEMBLY_COMPONENT_PLACEMENT_REQUIREMENTS_ARM.THREE_DIMENSIONAL_SHAPE' IN TYPEOF(volume);
  END_ENTITY;

  ENTITY Placement_group;
      design_specific_usage : STRING; --ee_name;
	DERIVE
  		requirement: SET[0:?] OF Requirement_view_definition :=
  		get_rvd(SELF, 'requirement');
	WHERE
   		WR1 : EXISTS (requirement) AND SIZEOF(requirement) >= 1;
  END_ENTITY;

  ENTITY Placement_group_area_assignment;
      placed_group : Placement_group;
      area         : Mounting_restriction_area;
  END_ENTITY;

  ENTITY Placement_group_volume_assignment;
      placed_group : Placement_group;
      volume       : Mounting_restriction_volume;
  END_ENTITY;

END_SCHEMA;

