(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Physical unit design view - EXPRESS MIM
*)


SCHEMA Physical_unit_design_view_mim;
	USE FROM Feature_and_connection_zone_mim;
	USE FROM Item_definition_structure_mim;
	USE FROM Part_view_definition_mim;
	USE FROM Physical_unit_usage_view_mim;
	USE FROM Product_occurrence_mim;
END_SCHEMA;

