(*
 $Id: arm.exp,v 1.19 2008/09/12 10:26:23 liutkuviene Exp $
 ISO TC184/SC4/WG12 N5278 - ISO/TS 10303-1109 Alternative solution - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N4928
*)

SCHEMA Alternative_solution_arm;

USE FROM Person_organization_assignment_arm;
USE FROM Product_occurrence_arm; -- ISO/TS 10303-1063
USE FROM Functional_breakdown_arm;  -- ISO/TS 10303-1216
USE FROM Physical_breakdown_arm;

  TYPE complex_product_select = SELECT
    (Alternative_solution, Functional_element_definition, Physical_element_definition);
  END_TYPE;


  ENTITY Alternative_solution;
    id : STRING;
    version_id : OPTIONAL STRING;
    base_element : complex_product_select;
  END_ENTITY;

  ENTITY Solution_element;
    resolved_requirement: complex_product_select;
    element: Product_occurrence;
    description : OPTIONAL STRING;
  END_ENTITY;

  ENTITY Supplier_solution
    SUBTYPE OF (Alternative_solution);
      supplier : Organization;
      probability_rate : OPTIONAL REAL;
    DERIVE
      actual_rate : REAL := NVL(probability_rate, 1.0);
    WHERE
      WR1: { 0.0 <= actual_rate <= 1.0 };
  END_ENTITY;

  ENTITY Technical_solution
    SUBTYPE OF (Alternative_solution);
      description : STRING;
  END_ENTITY;

END_SCHEMA;

