(*
   $Id: mim.exp,v 1.8 2005/11/08 11:03:00 thomasrthurman Exp $
   ISO TC184/SC4/WG3 N1633 - ISO/CD-TS 10303-1611 Ap210 connection zone based model extraction - EXPRESS MIM
*)


SCHEMA Ap210_connection_zone_based_model_extraction_mim;
	USE FROM Analytical_model_mim;	-- ISO/TS 10303-1603
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Characteristic_mim;	-- ISO/TS 10303-1654
    USE FROM Feature_and_connection_zone_mim; -- ISO/TS 10303-1671	
END_SCHEMA;

