(*
$Id: arm.exp,v 1.1 2005/02/11 21:05:46 thendrix Exp $
*) 


SCHEMA Ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_arm;

USE FROM Configuration_controlled_3d_parts_and_assemblies_arm;    -- ISO/TS 10303-1230

USE FROM External_model_arm;    -- ISO/TS 10303-1033

USE FROM Part_definition_relationship_arm;    -- ISO/TS 10303-1055

USE FROM Time_interval_assignment_arm;    -- ISO/TS 10303-1365


TYPE alias_identification_item_203e2 = SELECT BASED_ON alias_identification_item WITH 
   (Approval_status, 
    Document, 
    Document_definition, 
    Document_version, 
    Geometric_model, 
    Independent_property, 
    Organization, 
    Part, 
    Part_version, 
    Part_view_definition, 
    Security_classification);
END_TYPE; 

TYPE approval_item_203e2 = SELECT BASED_ON approval_item WITH 
   (Activity, 
    Alternate_part_relationship, 
    Assembly_relationship_substitution, 
    Document, 
    Document_definition, 
    Document_version, 
    File, 
    Part_version, 
    Part_view_definition);
END_TYPE; 

TYPE contract_item_203e2 = SELECT BASED_ON contract_item WITH 
   (Activity, 
    Part_version);
END_TYPE; 

TYPE documented_element_select_203e2 = SELECT BASED_ON documented_element_select WITH 
   (Part, 
    Part_version, 
    Part_view_definition, 
    View_definition_relationship);
END_TYPE; 

TYPE effectivity_item_203e2 = SELECT BASED_ON effectivity_item WITH 
   (Assembly_relationship_substitution, 
    Document, 
    Document_definition, 
    Document_definition_relationship, 
    Document_version, 
    Part, 
    Part_version, 
    Part_view_definition);
END_TYPE; 

TYPE identification_item_203e2 = SELECT BASED_ON identification_item WITH 
   (Approval_status, 
    Document, 
    Document_definition, 
    Document_version, 
    Geometric_model, 
    Independent_property, 
    Organization, 
    Part, 
    Part_version, 
    Part_view_definition, 
    Security_classification);
END_TYPE; 

TYPE organization_or_person_in_organization_item_203e2 = SELECT BASED_ON organization_or_person_in_organization_item WITH 
   (Alternate_part_relationship, 
    Applied_independent_property, 
    Assembly_relationship_substitution, 
    Certification, 
    Document, 
    Document_definition, 
    Document_version, 
    File, 
    Geometric_model, 
    Independent_property, 
    Part, 
    Part_version, 
    Part_view_definition, 
    Product_version_relationship, 
    Project);
END_TYPE; 

TYPE security_classification_item_203e2 = SELECT BASED_ON security_classification_item WITH 
   (Document_definition, 
    Document_version, 
    File, 
    Part_version, 
    Part_view_definition, 
    View_definition_usage);
END_TYPE; 

TYPE string_select_203e2 = SELECT BASED_ON string_select WITH 
   (Alias_identification, 
    Alternate_part_relationship, 
    Applied_independent_property, 
    Assembly_relationship_substitution, 
    Certification_assignment, 
    Detailed_geometric_model_element, 
    Effectivity, 
    Effectivity_relationship, 
    Event, 
    External_geometric_model, 
    Independent_property, 
    Independent_property_relationship, 
    Item_shape, 
    Make_from_relationship, 
    Product_version_relationship, 
    Representation, 
    Security_classification_assignment, 
    Shape_element, 
    Shape_element_relationship, 
    String_representation_item, 
    Uncertainty_with_unit, 
    View_definition_context);
END_TYPE; 

TYPE time_interval_item_203e2 = SELECT BASED_ON time_interval_item WITH 
   (Time_interval_effectivity);
END_TYPE; 

SUBTYPE_CONSTRAINT exclusive_product_versions_203e2 FOR Product_version;
  ONEOF (Document_version,
         Part_version);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;  -- Ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_arm