(*
$Id: mim.exp,v 1.24 2009/04/20 08:57:50 mikeward Exp $
ISO TC184/SC4/WG12 N6094 - ISO/TS 10303-1287 AP239 activity recording - EXPRESS MIM
Supersedes ISO TC184/SC4/WG12 N1562
*) 


SCHEMA Ap239_activity_recording_mim;

USE FROM Ap239_work_definition_mim;    -- ISO/TS 10303-1307

USE FROM Resource_as_realized_characterized_mim;    -- ISO/TS 10303-1283


TYPE ar_action_method_items = SELECT BASED_ON action_method_items WITH 
   (action_actual, 
    applied_action_assignment, 
    event_occurrence);
END_TYPE; 

TYPE ar_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH 
   (event_occurrence, 
    observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH 
   (observation_consequence);
END_TYPE; 

TYPE ar_condition_evaluation_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_evaluation_action_items WITH 
   (action, 
    action_method, 
    action_method_relationship, 
    action_property, 
    action_property_representation, 
    action_relationship, 
    action_resource, 
    action_resource_relationship, 
    action_resource_requirement, 
    applied_action_assignment, 
    applied_action_method_assignment, 
    group, 
    product_group, 
    product_group_membership, 
    product_group_relationship, 
    property_definition_representation, 
    resource_property, 
    resource_property_representation);
END_TYPE; 

TYPE ar_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
   (observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_identification_item = EXTENSIBLE SELECT BASED_ON identification_item WITH 
   (observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH 
   (observation);
END_TYPE; 

TYPE ar_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH 
   (event_occurrence, 
    observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_observed_context_item = SELECT BASED_ON observed_context_item WITH 
   (action, 
    action_directive, 
    action_method, 
    action_resource, 
    action_resource_requirement, 
    applied_action_assignment, 
    event_occurrence, 
    interface_connector_occurrence, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_group, 
    versioned_action_request);
END_TYPE; 

END_SCHEMA;  -- Ap239_activity_recording_mim

