(*
 $Id: mim.exp,v 1.14 2003/11/14 15:45:04 robbod Exp $
ISO TC184/SC4/WG3 N1394 - ISO/TS 10303-1287 AP239 activity recording - EXPRESS MIM
Supersedes ISO TC184/SC4/WG3 N1289
*) 


SCHEMA Ap239_activity_recording_mim; 

USE FROM action_schema;    -- ISO 10303-41

USE FROM Activity_as_realized_mim;    -- ISO/TS 10303-1259

USE FROM Activity_method_assignment_mim;    -- ISO/TS 10303-1249

USE FROM Activity_method_implementation_mim;    -- ISO/TS 10303-1261

USE FROM Activity_method_mim;    -- ISO/TS 10303-1049

USE FROM Activity_mim;    -- ISO/TS 10303-1047

USE FROM Ap239_work_definition_mim;    -- ISO/TS 10303-1307

USE FROM Condition_evaluation_mim;    -- ISO/TS 10303-1254

USE FROM date_time_schema   -- ISO 10303-41
  (event_occurrence); 

USE FROM Document_assignment_mim;    -- ISO/TS 10303-1122

USE FROM Event_mim;    -- ISO/TS 10303-1064

USE FROM group_schema   -- ISO 10303-41
  (group); 

USE FROM Justification_mim;    -- ISO/TS 10303-1263

USE FROM Multi_linguism_mim;    -- ISO/TS 10303-1105

USE FROM Observation_mim;    -- ISO/TS 10303-1258

USE FROM Process_property_assignment_mim;    -- ISO/TS 10303-1040

USE FROM process_property_schema   -- ISO 10303-49
  (action_property,
   action_resource_requirement,
   resource_property); 

USE FROM product_definition_schema   -- ISO 10303-41
  (product,
   product_definition,
   product_definition_formation); 

USE FROM Product_group_mim;    -- ISO/TS 10303-1278

USE FROM Product_identification_mim;    -- ISO/TS 10303-1017

USE FROM Product_version_mim;    -- ISO/TS 10303-1018

USE FROM Product_view_definition_mim;    -- ISO/TS 10303-1019

USE FROM Required_resource_mim;    -- ISO/TS 10303-1267

USE FROM Resource_as_realized_characterized_mim;    -- ISO/TS 10303-1283

USE FROM Resource_as_realized_mim;    -- ISO/TS 10303-1269

USE FROM Resource_item_mim;    -- ISO/TS 10303-1268

USE FROM Resource_management_mim;    -- ISO/TS 10303-1266

USE FROM Resource_property_assignment_mim;    -- ISO/TS 10303-1273

USE FROM Scheme_mim;    -- ISO/TS 10303-1260

USE FROM Task_specification_mim;    -- ISO/TS 10303-1262

USE FROM Work_order_mim;    -- ISO/TS 10303-1043

USE FROM Work_output_mim;    -- ISO/TS 10303-1300

USE FROM Work_request_mim;    -- ISO/TS 10303-1042


TYPE ar_action_method_items = SELECT BASED_ON action_method_items WITH 
   (action_actual, 
    applied_action_assignment, 
    event_occurrence);
END_TYPE; 

TYPE ar_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH 
   (event_occurrence, 
    observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_condition_evaluation_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_evaluation_action_items WITH 
   (action, 
    action_method, 
    action_method_relationship, 
    action_property, 
    action_relationship, 
    action_resource, 
    action_resource_relationship, 
    action_resource_requirement, 
    applied_action_assignment, 
    applied_action_method_assignment, 
    group, 
    product_group, 
    product_group_membership, 
    product_group_relationship, 
    resource_property);
END_TYPE; 

TYPE ar_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
   (observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH 
   (observation);
END_TYPE; 

TYPE ar_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH 
   (event_occurrence, 
    observation, 
    observation_consequence);
END_TYPE; 

TYPE ar_observed_context_item = SELECT BASED_ON observed_context_item WITH 
   (action, 
    action_directive, 
    action_method, 
    action_resource, 
    action_resource_requirement, 
    applied_action_assignment, 
    event_occurrence, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_group, 
    versioned_action_request);
END_TYPE; 

END_SCHEMA;  -- Ap239_activity_recording_mim


