(*
  $Id: mim.exp,v 1.3 2009/12/17 12:38:07 lothartklein Exp $
  ISO TC184/SC4/WG12 N7044 - ISO/TS 10303-1788 Explicit_constraints - EXPRESS MIM
*)

SCHEMA Explicit_constraints_mim;

USE FROM Expression_mim;  -- ISO 10303-1341

USE FROM Foundation_representation_mim;  -- ISO 10303-1006

USE FROM Parameterization_and_variational_representation_mim; -- ISO 10303-1790
   
USE FROM explicit_constraint_schema;  -- ISO 10303-108


END_SCHEMA;
