{ iso standard 10303 part (11) version (4) }
(*  $Id: $ *) 
SCHEMA Product_view_definition_properties_arm;

USE FROM Product_view_definition_arm;

USE FROM Product_view_definition_relationship_arm;

USE FROM Product_view_definition_relationship_arm;

USE FROM Property_assignment_arm;

TYPE product_view_definition_property_assignment = EXTENSIBLE SELECT BASED_ON property_assignment_select WITH
  (Product_view_definition,
   Product_view_definition_relationship);
END_TYPE;

END_SCHEMA;
