(*
   $Id: mim.exp,v 1.12 2006/01/05 11:50:47 liutkus Exp $
   ISO TC184/SC4/WG12 N3451 - ISO/CD-TS 10303-1687 Interconnect module with macros - EXPRESS MIM
*)


SCHEMA Interconnect_module_with_macros_mim;
	USE FROM Assembly_module_with_interconnect_component_mim;	-- ISO/TS 10303-1643
	USE FROM Layered_interconnect_module_design_mim;	-- ISO/TS 10303-1698

  ENTITY interconnect_module_macro_component
    SUBTYPE OF (physical_component);
  END_ENTITY;
	
ENTITY interconnect_module_macro_component_join_terminal
  SUBTYPE OF (physical_component_terminal);
END_ENTITY;
	
END_SCHEMA;

