(*
   $Id: arm.exp,v 1.2 2011/08/17 11:32:51 lothartklein Exp $
   ISO TC184/SC4/WG12 N7930 - ISO/CD-TS - 10303-1812 Product and manufacturing annotation presentation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N7367
*)
(* UNDER DEVELOPMENT *)
SCHEMA Product_and_manufacturing_annotation_presentation_arm;

USE FROM Product_and_manufacturing_information_with_nominal_3d_models_arm;

ENTITY Pmi_annotation_presentation_shape
  SUBTYPE OF (Nominal_3d_model_shape);
WHERE
  WR1: 'PRODUCT_AND_MANUFACTURING_INFORMATION_VIEW_CONTEXT_ARM.MODEL_BASED_3D_ANNOTATION_PRESENTATION_VIEW_CONTEXT' IN TYPEOF(described_element\Product_view_definition.additional_contexts); 
--  WR2: TRUE; -- must have at least one draughting_model of the ABREP
END_ENTITY;  
  

END_SCHEMA;
