(*
   $Id: arm.exp,v 1.3 2007/03/03 21:31:48 abhpf Exp $
   ISO TC184/SC4/WG12 N4568 - ISO/WD 10303-1491 Expression assignment - EXPRESS ARM
*)   
(* UNDER DEVELOPMENT *)

SCHEMA Expression_assignment_arm;

USE FROM Expression_arm;

TYPE expression_assignment_item = EXTENSIBLE GENERIC_ENTITY SELECT ;
END_TYPE;

ENTITY Expression_assignment;
  expression : Expression;
  item : expression_assignment_item;
END_ENTITY;

END_SCHEMA;