(*
   $Id: arm.exp,v 1.6 2004/12/08 13:41:25 budreckytej Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Component feature - EXPRESS ARM 
(* UNDER DEVELOPMENT *)

SCHEMA Component_feature_arm;

	USE FROM Physical_unit_design_view_arm;
	
	USE FROM Shape_property_assignment_arm;	

	TYPE part_feature_or_template_feature = EXTENSIBLE GENERIC_ENTITY SELECT
		(Part_feature);
	END_TYPE;

  ENTITY Component_feature
    ABSTRACT SUBTYPE OF (shape_element);
      definition           : OPTIONAL part_feature_or_template_feature;
      SELF\shape_element.containing_shape RENAMED associated_component : assembly_component;
    UNIQUE
      UR1 : definition,
 associated_component;
  END_ENTITY; -- component_feature

  ENTITY Component_feature_make_from_relationship
		SUBTYPE OF (Component_feature_relationship);
      SELF\Shape_element_relationship.relating RENAMED reusable_feature	: component_feature;
      SELF\Shape_element_relationship.related RENAMED resultant_feature	: component_feature;
  END_ENTITY; -- component_feature_make_from_relationship

  ENTITY Component_feature_relationship
  	SUBTYPE OF (Shape_element_relationship);
      SELF\Shape_element_relationship.related  : component_feature;
      SELF\Shape_element_relationship.relating : component_feature;
  END_ENTITY; -- component_feature_relationship

  ENTITY Component_feature_to_physical_usage_view_assignment;
      defined_part_feature   : part_feature;
      assigned_design_object : component_feature;
    UNIQUE 
    	UR1 : assigned_design_object;
    	UR2 : defined_part_feature;
  END_ENTITY; -- component_feature_to_physical_usage_view_assignment

  ENTITY Component_terminal
    SUBTYPE OF (Component_feature);
      local_swappable  : OPTIONAL BOOLEAN;
      global_swappable : OPTIONAL BOOLEAN;
      swap_code        : OPTIONAL STRING;
  END_ENTITY; -- component_terminal

END_SCHEMA;
