
(*
   $Id: arm.exp,v 1.4 2006/03/29 21:54:32 darla Exp $
   N - ISO/CD-TS - 10303-1232 design_material_aspects - EXPRESS ARM*)


SCHEMA design_material_aspects_arm;

USE FROM generic_material_aspects_arm;

USE FROM product_view_definition_arm;

USE FROM shape_property_assignment_arm;

TYPE dma_material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON material_item_select WITH
  (item_shape,
   product_view_definition,
   shape_element);
END_TYPE;

END_SCHEMA;

