
(*
 $Id: arm.exp,v 1.10 2015/03/14 14:34:49 lothartklein Exp $
 ISO TC184/SC4/WG12 N3799 - ISO/CD-TS 10303-1232 Design material aspects - EXPRESS ARM
*)

SCHEMA Design_material_aspects_arm;

USE FROM Generic_material_aspects_arm;

USE FROM Product_view_definition_arm;

USE FROM Shape_property_assignment_arm;

TYPE dma_material_item_select = SELECT BASED_ON material_item_select WITH
  (shapeable_item,
   Product_view_definition,
   Shape_element);
END_TYPE;

END_SCHEMA;

