(*
   $Id: arm.exp,v 1.7 2007/03/21 01:12:37 abhpf Exp $
   ISO TC184/SC4/WG12 N4577- ISO/WD 10303-1478 External functional model - EXPRESS ARM
*) 

SCHEMA External_functional_model_arm;

USE FROM File_identification_arm;

USE FROM Function_based_behaviour_representation_arm;

ENTITY External_functional_model
SUBTYPE OF (Function_based_behaviour_model);
  external_file : Digital_file;
END_ENTITY;

END_SCHEMA;

