/*
 * STEPModMkReleaseDialog.java
 *
 * Created on 07 July 2006, 15:05
 */

package org.stepmod.gui;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import org.stepmod.CmRecord;
import org.stepmod.CmRelease;
import org.stepmod.StepmodPart;
import org.stepmod.cvschk.StepmodCvs;

/**
 *
 * @author  Rob Bodington
 */
public class STEPModMkReleaseSetDialog extends javax.swing.JDialog {
    
    private StepmodPart part;
    private DefaultMutableTreeNode node;
    private CmRelease cmRelease;
    private ArrayList selectedParts;
    
    private STEPModFrame stepmodFrame;
    private boolean create;
    
  
    
    /**
     * Creates new form STEPModMkReleaseDialog for creating a new release that is applied to a set of parts
     */
    public STEPModMkReleaseSetDialog(STEPModFrame stepmodFrame, ArrayList selectedParts, boolean create) {
        super(stepmodFrame, true);
        this.stepmodFrame = stepmodFrame;
        initComponents();
        this.selectedParts = selectedParts;
        StepmodPart part = (StepmodPart) selectedParts.get(0);
        releaseDatejTextField.setText(part.getReleaseDate());
        releaseStatusjComboBox.setSelectedItem("Team review");
        releaseWhojTextField.setText(part.getStepMod().getStepmodProperty("SFORGE_USERNAME"));
        this.create = create;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        canceljButton = new javax.swing.JButton();
        okjButton = new javax.swing.JButton();
        releaseStatusjComboBox = new javax.swing.JComboBox();
        titleLabel = new javax.swing.JLabel();
        releaseDatejLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        releaseDescriptionjEditorPane = new javax.swing.JEditorPane();
        jLabel5 = new javax.swing.JLabel();
        releaseDatejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        releaseWhojTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        okjButton.setText("OK");
        okjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButtonActionPerformed(evt);
            }
        });

        releaseStatusjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Team review", "Convener review", "Secretariat review", "ISO review", "Ballot", "ISO publication" }));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        titleLabel.setText("Create a new release for selected parts");

        releaseDatejLabel.setText("Release date:");

        jLabel4.setText("Release status:");

        jScrollPane1.setViewportView(releaseDescriptionjEditorPane);

        jLabel5.setText("Description:");

        releaseDatejTextField.setEditable(false);
        releaseDatejTextField.setText("jTextField3");

        jLabel7.setText("Released by:");

        releaseWhojTextField.setText("jTextField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(titleLabel)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(okjButton)
                                .add(14, 14, 14)
                                .add(canceljButton))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel5)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(layout.createSequentialGroup()
                                                .add(releaseDatejLabel)
                                                .add(12, 12, 12)
                                                .add(releaseDatejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel4)
                                                    .add(jLabel7))
                                                .add(12, 12, 12)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(releaseWhojTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                    .add(releaseStatusjComboBox, 0, 250, Short.MAX_VALUE))))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                                .add(23, 23, 23))
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                .add(11, 11, 11)))
                        .add(32, 32, 32))))
        );

        layout.linkSize(new java.awt.Component[] {jLabel4, jLabel5, releaseDatejLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(releaseDatejLabel)
                    .add(releaseDatejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(releaseStatusjComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(releaseWhojTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okjButton)
                    .add(canceljButton))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed
    
    
    private void createReleaseOnSelectParts () {
       for (Iterator it = selectedParts.iterator(); it.hasNext();) {
            // tag each selected part
            StepmodPart part = (StepmodPart) it.next();
            CmRecord cmRecord = part.getCmRecord();
            String releaseId = part.getNextReleaseId();
            StepmodCvs stepmodCvs = part.cvsTag(releaseId);
            stepmodFrame.outputCvsResults(stepmodCvs);
            if (stepmodCvs.getCvsErrorVal() == 0) {
                // successfully tagged the part, so check out the tagged release
                stepmodCvs = part.cvsCoRelease(releaseId);
                stepmodFrame.outputCvsResults(stepmodCvs);
                if (stepmodCvs.getCvsErrorVal() != 0) {
                    // error
                    return;
                }
            } else {
                // error
                return;
            }
        }
        //  create a release for each part  - do this in separate loop
        // in case any parts dependend on any other parts in the set
        for (Iterator it = selectedParts.iterator(); it.hasNext();) {
            // tag each selected part
            StepmodPart part = (StepmodPart) it.next();
            String releaseId = part.getNextReleaseId();
            CmRelease cmRelease = new CmRelease(
                    releaseId, part,
                    releaseWhojTextField.getText(),
                    (String)releaseStatusjComboBox.getSelectedItem(),
                    releaseDescriptionjEditorPane.getText());
            node = stepmodFrame.getNodeForPart(part);
            stepmodFrame.addReleaseToTree(part, cmRelease, node, true);
            // Successfully tagged the part, so save the record
            part.getCmRecord().writeCmRecord();
        }
    }
    
    private void editReleaseOnSelectParts() {
        for (Iterator it = selectedParts.iterator(); it.hasNext();) {
            // tag each selected part
            StepmodPart part = (StepmodPart) it.next();      
            CmRelease cmRelease = part.getCmRecord().getCheckedOutRelease();            
            node = stepmodFrame.getNodeForPart(part);
            stepmodFrame.updateReleaseStatus(part, cmRelease, (String)releaseStatusjComboBox.getSelectedItem(), node, true);
            part.getCmRecord().writeCmRecord();
        }
    }
    
    
    private void okjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjButtonActionPerformed
        if (create) {
            createReleaseOnSelectParts();
        } else {
            editReleaseOnSelectParts();
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okjButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okjButton;
    private javax.swing.JLabel releaseDatejLabel;
    private javax.swing.JTextField releaseDatejTextField;
    private javax.swing.JEditorPane releaseDescriptionjEditorPane;
    private javax.swing.JComboBox releaseStatusjComboBox;
    private javax.swing.JTextField releaseWhojTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
