(*
   $Id: mkmodule.js,v 1.45 2006/05/18 17:01:14 dmprice Exp $
   N - ISO/CD-TS - 10303- qualified_measure - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Qualified_measure_mim;

USE FROM External_item_identification_assignment_mim;

USE FROM External_library_mim;

USE FROM Measure_representation_mim;

USE FROM qualified_measure_schema
  (type_qualifier);

TYPE qualified_measure_identification_item = SELECT BASED_ON external_identification_item WITH
  (type_qualifier);
END_TYPE; 

END_SCHEMA;
