(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Design specific assignment to assembly usage view - EXPRESS ARM
*)

SCHEMA Design_specific_assignment_to_assembly_usage_view_arm;

USE FROM Assembly_module_with_subassembly_arm;

USE FROM Assembly_module_with_interconnect_component_arm;

	SUBTYPE_CONSTRAINT component_feature_to_physical_usage_view_assignment_subtypes FOR component_feature_to_physical_usage_view_assignment;     
		ONEOF (component_terminal_to_assembly_module_interface_terminal_assignment,
		 component_terminal_to_pca_terminal_assignment);
	END_SUBTYPE_CONSTRAINT;

	TYPE pca_interface_select = SELECT
	    (interconnect_module_component_terminal,
	     component_interface_terminal,
	     assembly_module_component_terminal);
  	END_TYPE;
 
  ENTITY Component_terminal_to_assembly_module_interface_terminal_assignment
    SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
    SELF\component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal : assembly_module_interface_terminal;
    SELF\component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal : pca_interface_select;
    UNIQUE
      UR1 : usage_view_terminal;
  END_ENTITY; -- component_terminal_to_assembly_module_interface_terminal_assignment

  ENTITY Component_terminal_to_pca_terminal_assignment
    SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
    	SELF\component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal : pca_terminal;
    	SELF\component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal : pca_interface_select;
    UNIQUE
      UR1 : usage_view_terminal;
  END_ENTITY; -- component_terminal_to_pca_terminal_assignment

END_SCHEMA; -- Information_assignment_to_usage_view_arm
