#!/bin/bash
export ANT_HOME=/usr/share/ant
export SAXON_HOME=/Applications/saxon6-5-5
export JAVA_HOME=/Library/Java/Home
export PATH=${PATH}:${ANT_HOME}/bin
export ANT_OPTS=-Xmx1024m
export CLASSPATH=$ANT_HOME/lib:$SAXON_HOME/saxon.jar
ant wf 
