@echo off
REM $Id: make_html_all.bat,v 1.4 2002/02/24 23:18:09 robbod Exp $

REM Generate the html for all the modules.


REM +++++++++++++++++++++++++++++++++++++++
REM create the html for all the modules
REM ++ copy the next line for each new module
rem goto :BP1
rem goto :BP2
rem goto :BP3
rem goto :ALL
goto :IRS


rem Ballot Package 1
:BP1
call make_html alias_identification
call make_html approval
call make_html contract
call make_html date_time
call make_html date_time_assignment
call make_html identification_assignment
call make_html part_and_version_identification
call make_html part_view_definition
call make_html person_organisation
call make_html person_organisation_assignment
call make_html product_categorisation
call make_html product_identification
call make_html product_version
call make_html product_view_definition
call make_html project
call make_html security_classification
rem goto :END

rem Ballot packge 2
:BP2
call make_html certification
call make_html part_occurrence
call make_html part_structure
call make_html product_structure
call make_html product_version_structure
call make_html product_view_definition_structure
rem goto :END

rem Ballot packge 3
:BP3
call make_html work_order
call make_html work_request
rem goto :END


:ALL
call make_html advanced_boundary_representation
call make_html alias_identification
call make_html approval
call make_html boundary_representation_model
call make_html certification
call make_html configuration_effectivity
call make_html constructive_solid_geometry
call make_html constructive_solid_geometry_2d
call make_html constructive_solid_geometry_3d
call make_html contract
call make_html date_time
call make_html date_time_assignment
call make_html document_and_version_identification
call make_html document_assignment
call make_html document_definition
call make_html document_properties
call make_html document_structure
call make_html edge_based_wireframe
call make_html effectivity
call make_html effectivity_application
call make_html elemental_geometric_shape
call make_html elemental_topology
call make_html end_item_identification
call make_html event
call make_html external_item_identification_assignment
call make_html faceted_boundary_representation
call make_html faceted_boundary_representation_model
call make_html file_identification
call make_html file_properties
call make_html foundation_representation
call make_html geometric_shape_with_topology
call make_html geometric_validation_property_representation
call make_html geometrically_bounded_surface
call make_html geometrically_bounded_wireframe
call make_html identification_assignment
call make_html independent_property
call make_html independent_property_representation
call make_html independent_property_usage
call make_html manifold_surface
call make_html part_and_version_identification
call make_html part_occurrence
call make_html part_structure
call make_html part_view_definition
call make_html person_organisation
call make_html person_organisation_assignment
call make_html process_property_assignment
call make_html product_categorisation
call make_html product_concept_identification
call make_html product_identification
call make_html product_structure
call make_html product_version
call make_html product_version_structure
call make_html product_view_definition
call make_html product_view_definition_properties
call make_html product_view_definition_structure
call make_html product_view_definition_structure_properties
call make_html project
call make_html property_assignment
call make_html property_representation
call make_html security_classification
call make_html shape_property_assignment
call make_html shape_property_representation
call make_html shell_based_wireframe
call make_html solid_model
call make_html time_interval
call make_html topologically_bounded_surface
call make_html work_order
call make_html work_request

:IRS
call make_html_resource classification_schema
call make_html_resource set_theory_schema
call make_html_resource action_schema
call make_html_resource application_context_schema
call make_html_resource approval_schema
call make_html_resource basic_attribute_schema
call make_html_resource certification_schema
call make_html_resource configuration_management_schema
call make_html_resource contract_schema
call make_html_resource date_time_schema
call make_html_resource document_schema
call make_html_resource draughting_dimension_schema
call make_html_resource draughting_element_schema
call make_html_resource drawing_definition_schema
call make_html_resource effectivity_schema
call make_html_resource external_reference_schema
call make_html_resource fea_scalar_vector_tensor_schema
call make_html_resource finite_element_analysis_control_and_result_schema
call make_html_resource geometric_model_schema
call make_html_resource geometry_schema
call make_html_resource group_schema
call make_html_resource kinematic_analysis_control_and_result_schema
call make_html_resource kinematic_motion_representation_schema
call make_html_resource kinematic_structure_schema
call make_html_resource management_resources_schema
call make_html_resource material_property_definition_schema
call make_html_resource material_property_representation_schema
call make_html_resource mathematical_functions_schema
call make_html_resource measure_schema
call make_html_resource method_definition_schema
call make_html_resource person_organization_schema
call make_html_resource presentation_appearance_schema
call make_html_resource presentation_definition_schema
call make_html_resource presentation_organization_schema
call make_html_resource presentation_resource_schema
call make_html_resource process_property_representation_schema
call make_html_resource process_property_schema
call make_html_resource product_concept_schema
call make_html_resource product_definition_schema
call make_html_resource product_property_definition_schema
call make_html_resource product_property_representation_schema
call make_html_resource product_structure_schema
call make_html_resource qualified_measure_schema
call make_html_resource representation_schema
call make_html_resource security_classification_schema
call make_html_resource shape_aspect_definition_schema
call make_html_resource shape_dimension_schema
call make_html_resource shape_tolerance_schema
call make_html_resource structural_response_definition_schema
call make_html_resource structural_response_representation_schema
call make_html_resource support_resource_schema
call make_html_resource topology_schema

goto :END

:INDEX
SETLOCAL
set SAXON=e:\apps\instant-saxon\saxon
set MODULES_HOME=..
echo.
echo .... %MODULES_HOME%\repository_index.xml
%SAXON% -a -o "%MODULES_HOME%\repository_index.htm" "%MODULES_HOME%\repository_index.xml" output_type="HTM"
:END