(*
   $Id: arm.exp,v 1.5 2004/12/16 14:43:25 liutkus Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 interconnect functional requirements - EXPRESS ARM
*)

SCHEMA Ap210_interconnect_functional_requirements_arm;
   USE FROM AP210_product_data_management_arm;
   USE FROM Network_functional_design_view_arm;
   USE FROM Planned_characteristic_arm;   
   USE FROM Requirement_assignment_arm;
   USE FROM Requirement_decomposition_arm;   
   USE FROM Requirement_identification_and_version_arm;
   USE FROM Requirement_view_definition_arm;
   USE FROM Requirement_view_definition_relationship_arm;
   USE FROM Test_requirement_allocation_arm;
   USE FROM Assembly_module_usage_view_arm;
   -- ?? physical_network
   USE FROM Functional_assignment_to_part_arm; -- because of part_connected_terminals_definition
   USE FROM Characteristic_arm;
END_SCHEMA;
