(*
   $Id: mim.exp,v 1.6 2005/02/04 17:07:37 budreckytej Exp $
   ISO TC184/SC4/WG12 N1657 - ISO/CD-TS 10303-1619 Ap210 interconnect functional requirements - EXPRESS MIM
*)


SCHEMA Ap210_interconnect_functional_requirements_mim;
	USE FROM Ap210_functional_decomposition_mim;	-- ISO/TS 10303-1614
	USE FROM Ap210_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Functional_assignment_to_part_mim;	-- ISO/TS 10303-1674
	USE FROM Functional_decomposition_to_design_mim;	-- ISO/TS 10303-1676
	USE FROM Functional_decomposition_to_interconnect_design_mim;	-- ISO/TS 10303-1677
	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_mim;	-- ISO/TS 10303-1678
	USE FROM Interconnect_module_usage_view_mim;	-- ISO/TS 10303-1686
	USE FROM Planned_characteristic_mim;	-- ISO/TS 10303-1733
	USE FROM Requirement_assignment_mim;	-- ISO/TS 10303-1233
	USE FROM Requirement_decomposition_mim;	-- ISO/TS 10303-1740
	USE FROM Requirement_identification_and_version_mim;	-- ISO/TS 10303-1140
	USE FROM Requirement_view_definition_mim;	-- ISO/TS 10303-1141
	USE FROM Requirement_view_definition_relationship_mim;	-- ISO/TS 10303-1142
	USE FROM Test_requirement_allocation_mim;	-- ISO/TS 10303-1751
END_SCHEMA;

