/*
 * MakeCMRecordGui.java
 *
 * Created on February 18, 2008, 9:25 AM
 */

import java.io.*;
import java.util.Date;
import java.util.TreeMap;
import java.util.Vector;

/**
 *
 * @author  radack
 */
public class MakeCMRecordGui extends javax.swing.JFrame implements StatusPrinter {

    private File stepmodRootDir;
    private Config config;
    private static TreeMap<String, Integer> partTypeMap = new TreeMap<String, Integer>();

    /** Creates new form MakeCMRecordGui */
    public MakeCMRecordGui() {
        initComponents();
        initVars();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stepmodCmPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        partListFileField = new javax.swing.JTextField();
        partNameField = new javax.swing.JTextField();
        ptReleaseField = new javax.swing.JTextField();
        ptStepmodCommonReleaseField = new javax.swing.JTextField();
        ptReleaseSequenceField = new javax.swing.JTextField();
        editionField = new javax.swing.JTextField();
        partListFileLabel = new javax.swing.JLabel();
        partNameLabel = new javax.swing.JLabel();
        releaseLabel = new javax.swing.JLabel();
        stepmodCommonReleaseLabel = new javax.swing.JLabel();
        releaseSequenceLabel = new javax.swing.JLabel();
        editionLabel = new javax.swing.JLabel();
        ptWhoField = new javax.swing.JTextField();
        ptWhenField = new javax.swing.JTextField();
        ptDescriptionField = new javax.swing.JTextField();
        whoLabel = new javax.swing.JLabel();
        whenLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        partTypeComboBox = new javax.swing.JComboBox();
        partTypeLabel = new javax.swing.JLabel();
        createCmButton = new javax.swing.JButton();
        partListFileSelectButton = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox();
        ptStepmodFrameworkReleaseField = new javax.swing.JTextField();
        stepmodFrameworkReleaseLabel = new javax.swing.JLabel();
        ptReleaseStatusField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        smReleaseField = new javax.swing.JTextField();
        smTagField = new javax.swing.JTextField();
        smWhoField = new javax.swing.JTextField();
        smWhenField = new javax.swing.JTextField();
        smDescriptionField = new javax.swing.JTextField();
        smCreateCmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        partListFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partListFileFieldActionPerformed(evt);
            }
        });

        partNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partNameFieldActionPerformed(evt);
            }
        });

        ptReleaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptReleaseFieldActionPerformed(evt);
            }
        });

        ptStepmodCommonReleaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptStepmodCommonReleaseFieldActionPerformed(evt);
            }
        });

        ptReleaseSequenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptReleaseSequenceFieldActionPerformed(evt);
            }
        });

        editionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionFieldActionPerformed(evt);
            }
        });

        partListFileLabel.setText("Part list file");

        partNameLabel.setText("Part name");

        releaseLabel.setText("Release");

        stepmodCommonReleaseLabel.setText("STEPMod common release");

        releaseSequenceLabel.setText("Release sequence");

        editionLabel.setText("Edition");

        ptWhoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptWhoFieldActionPerformed(evt);
            }
        });

        ptWhenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptWhenFieldActionPerformed(evt);
            }
        });

        ptDescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptDescriptionFieldActionPerformed(evt);
            }
        });

        whoLabel.setText("Who");

        whenLabel.setText("When");

        descriptionLabel.setText("Description");

        statusLabel.setText("Status");

        partTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Module", "Resource" }));
        partTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTypeComboBoxActionPerformed(evt);
            }
        });

        partTypeLabel.setText("Part type");

        createCmButton.setText("Create CM");
        createCmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCmButtonActionPerformed(evt);
            }
        });

        partListFileSelectButton.setText("Select");
        partListFileSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partListFileSelectButtonActionPerformed(evt);
            }
        });

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Team review", "Convener review", "Secretariat review", "ISO review", "Ballot", "ISO publication" }));

        stepmodFrameworkReleaseLabel.setText("STEPMod framework release");

        jLabel6.setText("Release status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partTypeLabel)
                            .addComponent(partListFileLabel)
                            .addComponent(partNameLabel)
                            .addComponent(releaseLabel)
                            .addComponent(stepmodCommonReleaseLabel)
                            .addComponent(stepmodFrameworkReleaseLabel)
                            .addComponent(releaseSequenceLabel)
                            .addComponent(editionLabel)
                            .addComponent(whoLabel)
                            .addComponent(whenLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(statusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partTypeComboBox, 0, 197, Short.MAX_VALUE)
                            .addComponent(partListFileField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(partNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptReleaseField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptReleaseStatusField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptStepmodCommonReleaseField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptStepmodFrameworkReleaseField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptReleaseSequenceField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(editionField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptWhoField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptWhenField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(ptDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(statusComboBox, 0, 197, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partListFileSelectButton)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(383, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(createCmButton)
                        .addContainerGap(369, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTypeLabel)
                    .addComponent(partTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partListFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partListFileLabel)
                    .addComponent(partListFileSelectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(releaseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ptReleaseStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptStepmodCommonReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepmodCommonReleaseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptStepmodFrameworkReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepmodFrameworkReleaseLabel))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptReleaseSequenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(releaseSequenceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptWhoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptWhenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(createCmButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        stepmodCmPanel.addTab("Module CM", jPanel1);

        jLabel1.setText("Release");

        jLabel2.setText("Tag");

        jLabel3.setText("Who");

        jLabel4.setText("When");

        jLabel5.setText("Description");

        smReleaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smReleaseFieldActionPerformed(evt);
            }
        });

        smCreateCmButton.setText("Create CM");
        smCreateCmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smCreateCmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(smReleaseField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(smTagField)
                            .addComponent(smWhenField)
                            .addComponent(smWhoField)
                            .addComponent(smDescriptionField))
                        .addContainerGap(109, Short.MAX_VALUE))
                    .addComponent(smCreateCmButton)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(smReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(smTagField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smWhoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smWhenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(smDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smCreateCmButton)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        stepmodCmPanel.addTab("STEPMod CM", jPanel2);

        statusArea.setColumns(20);
        statusArea.setRows(5);
        jScrollPane1.setViewportView(statusArea);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stepmodCmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stepmodCmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void partListFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partListFileFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_partListFileFieldActionPerformed

    private void ptStepmodCommonReleaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptStepmodCommonReleaseFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptStepmodCommonReleaseFieldActionPerformed

    private void ptReleaseSequenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptReleaseSequenceFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptReleaseSequenceFieldActionPerformed

    private void editionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_editionFieldActionPerformed

    private void ptWhoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptWhoFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptWhoFieldActionPerformed

    private void ptWhenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptWhenFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptWhenFieldActionPerformed

    private void ptDescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptDescriptionFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptDescriptionFieldActionPerformed

    private void partTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTypeComboBoxActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_partTypeComboBoxActionPerformed

    private void partNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partNameFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_partNameFieldActionPerformed

    private void ptReleaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptReleaseFieldActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_ptReleaseFieldActionPerformed

    private void createCmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCmButtonActionPerformed
        String partName = partNameField.getText();
        String partListPath = partListFileField.getText();
        if ((partName.length() > 0) && (partListPath.length() > 0)) {
            printStatusMessage("Cannot specify both part name and part list file.");
            return;
        }
        if ((partName.length() == 0) && (partListPath.length() == 0)) {
            printStatusMessage("Must specify either part name or part list file.");
            return;
        }
        try {
            if (partName.length() > 0) {
                processModule(partName);
            } else {
                File partListFile = new File(partListPath);
                processModuleList(partListFile);
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_createCmButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void partListFileSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partListFileSelectButtonActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int returnVal = fileChooser.showOpenDialog(stepmodCmPanel);

        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            partListFileField.setText(file.getAbsolutePath());
        } else {
            System.err.println("Open command cancelled by user.");
        }
    // log.setCaretPosition(log.getDocument().getLength());
}//GEN-LAST:event_partListFileSelectButtonActionPerformed

    private void smCreateCmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smCreateCmButtonActionPerformed
        try {
            processStepmod();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_smCreateCmButtonActionPerformed

    private void smReleaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smReleaseFieldActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_smReleaseFieldActionPerformed

    /*
     * Custom methods.
     */
    public void initVars() {
        String dateStr = MakeCMRecord.isoDateFormat.format(new java.util.Date());
        ptWhenField.setText(dateStr);
        smWhenField.setText(dateStr);
        stepmodRootDir = FileUtil.getStepmodRoot();
        config = new Config();
    }

    public void processModuleList(File moduleListFile) throws
            java.io.IOException,
            java.io.FileNotFoundException, java.text.ParseException,
            javax.xml.transform.TransformerConfigurationException,
            javax.xml.transform.TransformerException,
            ConnectionException, InternalErrorException {
        BufferedReader rdr = new BufferedReader(new FileReader(moduleListFile));
        Vector<String> moduleVec = new Vector<String>();
        String moduleName;

        String line;

        printStatusMessage("Processing module list.");
        while ((line = rdr.readLine()) != null) {
            moduleName = line.replace("_ARM", "");
            moduleName = moduleName.toLowerCase().trim();
            moduleName = moduleName.replace(" ", "_");
            moduleName = moduleName.replace("-", "_");
            moduleVec.add(moduleName);
        }

        for (int i = 0; i < moduleVec.size(); i++) {
            moduleName = moduleVec.get(i);
            try {

                processModule(moduleName);
            } catch (InvalidPartDirException e) {
                printStatusMessage("Directory not found for part " + moduleName + ". Processing aborted.");
            }
        }
        printStatusMessage("Module list processing complete.");
    }

    public void processModule(String moduleName)
            throws java.io.FileNotFoundException, java.text.ParseException,
            javax.xml.transform.TransformerConfigurationException,
            javax.xml.transform.TransformerException, InvalidPartDirException,
            ConnectionException, InternalErrorException {

        String partTypeStr = (String) partTypeComboBox.getSelectedItem();
        String dateStr = ptWhenField.getText();
        java.util.Date date = MakeCMRecord.isoDateFormat.parse(dateStr);
        printStatusMessage("Processing module " + moduleName + ".");
        String description = ptDescriptionField.getText();
        String release = ptReleaseField.getText();
        String releaseStatus = ptReleaseStatusField.getText();
        String stepmodCommonRelease = ptStepmodCommonReleaseField.getText();
        String stepmodFrameworkRelease = ptStepmodFrameworkReleaseField.getText();
        String status = (String) statusComboBox.getSelectedItem();
        String releaseSequence = ptReleaseSequenceField.getText();
        Date when = new Date();
        String who = ptWhoField.getText();

        String edition = editionField.getText();
        int partType = partTypeMap.get(partTypeStr).intValue();

        MakeCMRecord makeCMRecord = new MakeCMRecord(partType, config,
                stepmodRootDir, moduleName, description, release, releaseStatus,
                stepmodCommonRelease, stepmodFrameworkRelease,
                status, releaseSequence, edition, who, when, this);
        makeCMRecord.generateCM();
        printStatusMessage("Finished module " + moduleName + ".");
    }

    public void processStepmod()
            throws java.io.FileNotFoundException, java.text.ParseException,
            javax.xml.transform.TransformerConfigurationException,
            javax.xml.transform.TransformerException, InvalidModuleDirException,
            ConnectionException, InternalErrorException {

        String dateStr = smWhenField.getText();
        java.util.Date date = MakeCMRecord.isoDateFormat.parse(dateStr);
        String description = smDescriptionField.getText();
        String release = smReleaseField.getText();
        String tag = smTagField.getText();
        Date when = new Date();
        String who = smWhoField.getText();

        System.err.println("Generating STEPMod CM record");
    /*
    MakeCMRecord makeCMRecord = new MakeCMRecord(config,
    stepmodRootDir, description, release, tag, who, when);
    try {
    makeCMRecord.generateCM();
    } catch (java.io.IOException e) {
    throw new InternalErrorException(e);
    }
     */

    }

    public void printStatusMessage(String msg) {
        statusArea.append(msg + "\n");
        statusArea.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MakeCMRecordGui().setVisible(true);
            }
        });
    }

    static {
        partTypeMap.put("Module", MakeCMRecord.PT_MODULE);
        partTypeMap.put("Resource", MakeCMRecord.PT_RESOURCE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCmButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField editionField;
    private javax.swing.JLabel editionLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField partListFileField;
    private javax.swing.JLabel partListFileLabel;
    private javax.swing.JButton partListFileSelectButton;
    private javax.swing.JTextField partNameField;
    private javax.swing.JLabel partNameLabel;
    private javax.swing.JComboBox partTypeComboBox;
    private javax.swing.JLabel partTypeLabel;
    private javax.swing.JTextField ptDescriptionField;
    private javax.swing.JTextField ptReleaseField;
    private javax.swing.JTextField ptReleaseSequenceField;
    private javax.swing.JTextField ptReleaseStatusField;
    private javax.swing.JTextField ptStepmodCommonReleaseField;
    private javax.swing.JTextField ptStepmodFrameworkReleaseField;
    private javax.swing.JTextField ptWhenField;
    private javax.swing.JTextField ptWhoField;
    private javax.swing.JLabel releaseLabel;
    private javax.swing.JLabel releaseSequenceLabel;
    private javax.swing.JButton smCreateCmButton;
    private javax.swing.JTextField smDescriptionField;
    private javax.swing.JTextField smReleaseField;
    private javax.swing.JTextField smTagField;
    private javax.swing.JTextField smWhenField;
    private javax.swing.JTextField smWhoField;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTabbedPane stepmodCmPanel;
    private javax.swing.JLabel stepmodCommonReleaseLabel;
    private javax.swing.JLabel stepmodFrameworkReleaseLabel;
    private javax.swing.JLabel whenLabel;
    private javax.swing.JLabel whoLabel;
    // End of variables declaration//GEN-END:variables
}
