(*
   $Id: mim.exp,v 1.4 2009/05/22 09:12:19 liutkuviene Exp $
   ISO TC184/SC4/WG12 N6614 - ISO/TS 10303-1403 Geometric model relationship - EXPRESS MIM
*)   
SCHEMA Geometric_model_relationship_mim;

USE FROM Elemental_geometric_shape_mim;    -- ISO/TS 10303-1004

USE FROM representation_schema(
  definitional_representation_relationship
);

USE FROM product_property_representation_schema -- ISO 10303-41
  (shape_representation_relationship);


END_SCHEMA;
