(*  ISO/TC184/SC4 WG12N2046 - ISO/CD-TS - 10303-1098 property_and_property_assignment - EXPRESS MIM*)

SCHEMA property_and_property_assignment_mim;

USE FROM independent_property_definition_mim;    --  ISO/CD-TS 10303-1099
USE FROM property_space_mim;    --  ISO/CD-TS 10303-1080
USE FROM property_identification_mim;    --  ISO/CD-TS 10303-1085
USE FROM possession_of_property_mim;    --  ISO/CD-TS 10303-1199
USE FROM property_condition_mim;    --  ISO/CD-TS 10303-1074

END_SCHEMA;
