(* N - ISO/TS - 10303-1041 Part definition relationship - EXPRESS ARM *)
   
SCHEMA Part_definition_relationship_arm;

   
USE FROM Product_view_definition__relationship_arm; -- ISO/TS 10303-1019
USE FROM Value_with_unit_arm; -- ISO/TS 10303-1054
      
ENTITY Make_from
  SUBTYPE OF (View_definition_usage);
  SELF\Product_view_definition_relationship.view1: Part_view_definition;
  SELF\Product_view_definition_relationship.view2: Part_view_definition;
  quantity  : OPTIONAL Value_with_unit;
  priority  : OPTIONAL STRING;
WHERE
  WR1: SELF\Product_view_definition_relationship.view1 :<>: SELF\Product_view_definition_relationship.view2;
END_ENTITY;

   
END_SCHEMA;
