(*
   $Id: arm.exp,v 1.5 2007/11/06 19:41:09 abhpf Exp $
   ISO TC184/SC4/WG12 N5866 - ISO/CD-TS 10303-1468 External state based behaviour model - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4580
*)

SCHEMA External_state_based_behaviour_model_arm;

USE FROM File_identification_arm;

USE FROM State_based_behaviour_representation_arm;

ENTITY External_state_based_behaviour_model
SUBTYPE OF (State_based_behaviour_model);
  external_file : Digital_file;
END_ENTITY;

END_SCHEMA;