(*
   $Id: mim.exp,v 1.19 2008/11/22 20:32:27 abhpf Exp $
   ISO TC184/SC4/WG12 N5912 - ISO/TS 10303-1437 Schedule - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4614
*)

SCHEMA Schedule_mim;
  USE FROM Activity_mim;
  USE FROM Activity_method_assignment_mim;
  USE FROM Activity_method_implementation_mim;
  USE FROM Attribute_classification_mim;
  USE FROM Condition_evaluation_mim;
  USE FROM Document_assignment_mim;
  USE FROM Effectivity_application_mim;
  USE FROM Information_rights_mim;
  USE FROM Justification_mim;
  USE FROM Observation_mim;
  USE FROM Process_property_assignment_mim;
  USE FROM Property_assignment_mim;
  USE FROM Resource_as_realized_mim;
  USE FROM Resource_property_assignment_mim;
  USE FROM Scheme_mim;
  USE FROM Task_specification_mim;
  USE FROM Time_interval_assignment_mim;
  USE FROM Work_output_mim;
  USE FROM product_property_definition_schema   -- ISO 10303-41
  (characterized_object); 

TYPE ss_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(action,
	action_method,
	action_method_assignment,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_relationship,
	action_request_solution,
	action_request_status,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	action_status,
	address,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_action_request_assignment,
	applied_approval_assignment,
	applied_attribute_classification_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_document_reference,
	applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	applied_location_assignment,
	applied_location_representation_assignment,
	applied_name_assignment,
	applied_organization_assignment,
	applied_organizational_project_assignment,
	applied_person_and_organization_assignment,
	applied_security_classification_assignment,
	applied_time_interval_assignment,
	applied_usage_right,
	approval,
	approval_person_organization,
	approval_relationship,
	approval_status,
	ascribable_state,
	ascribable_state_relationship,
	attribute_language_assignment,
	breakdown_context,
	breakdown_element_group_assignment,
	breakdown_of,
	calendar_date,
	certification,
	class,
	condition,
	contract,
	contract_relationship,
	coordinated_universal_time_offset,
	date_and_time,
	date_and_time_assignment,
	date_assignment,
	derived_unit,
	document_file,
	effectivity,
	effectivity_relationship,
	event_occurrence,
	event_occurrence_relationship,
	executed_action,
	general_property,
	general_property_relationship,
	group,
	information_right,
	information_usage_right,
	justification_assignment,
	justification_group_assignment,
	justification_item_group_assignment,
	justification_support_assignment,
	justification_support_item_group_assignment,
	language,
	location,
	location_relationship,
	measure_representation_item,
	measure_with_unit,
	multi_language_attribute_assignment,
	named_unit,
	observation,
	observation_consequence,
	observation_relationship,
	organization,
	organization_relationship,
	organizational_address,
	organizational_project,
	organizational_project_relationship,
	person,
	person_and_organization,
	person_and_organization_address,
	product,
	product_definition,
	product_definition_context,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_group_assignment,
	product_definition_relationship,
	product_design_to_individual,
	product_design_version_to_individual,
	product_planned_to_realized,
	product_relationship,
	property_definition,
	property_definition_representation,
	representation,
	representation_context,
	representation_item,
	resource_property,
	resource_property_representation,
	security_classification,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_observed_role,
	state_type,
	state_type_assignment,
	state_type_relationship,
	task_element,
	task_method,
	task_objective,
	time_interval,
	time_interval_relationship,
	time_interval_role,
	usage_association,
	versioned_action_request);
END_TYPE;

TYPE ss_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	ascribable_state,
	effectivity,
	event_occurrence,
	executed_action,
	group,
	property_definition,
	property_definition_representation,
	resource_property,
	resource_property_representation,
	state_observed,
	state_observed_relationship,
	state_type,
	state_type_relationship,
	task_element,
	task_method,
	task_method_relationship,
	task_method_version_relationship);
END_TYPE;


TYPE ss_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(action_method,
	action_property,
	action_resource,
	property_definition,
	resource_property);
END_TYPE;

TYPE ss_aliasable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON aliasable_item WITH
	(event_occurrence,
	justification_assignment,
	justification_group_assignment,
	justification_item_group_assignment,
	justification_support_assignment,
	justification_support_item_group_assignment,
	product,
	product_relationship);
END_TYPE;

TYPE ss_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_assignment,
	applied_action_method_assignment,
	event_occurrence,
	group,
	justification_assignment,
	justification_group_assignment,
	justification_item_group_assignment,
	justification_support_assignment,
	justification_support_item_group_assignment,
	product,
	product_definition,
	product_relationship,
	property_definition,
	resource_property,
	state_observed_assignment,
	state_type_assignment,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(action_resource,
	applied_action_method_assignment,
	task_element,
	task_method,
	task_objective);
END_TYPE;

TYPE ss_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(action,
	action_method,
	action_property,
	action_property_representation,
	action_relationship,
	action_request_solution,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_assignment,
	applied_event_occurrence_assignment,
	event_occurrence_relationship,
	executed_action,
	group,
	property_definition,
	property_definition_representation,
	resource_property,
	resource_property_representation);
END_TYPE;

TYPE ss_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(action,
	action_method_relationship,
	action_resource,
	applied_action_method_assignment,
	group,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	group,
	resource_property,
	resource_property_representation,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	group,
	resource_property,
	resource_property_representation,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	ascribable_state,
	group,
	resource_property,
	resource_property_representation,
	state_observed,
	state_type,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(action_method,
	action_property,
	action_resource_relationship,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	resource_property,
	state_type_assignment,
	state_type_relationship);
END_TYPE;

TYPE ss_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_resource,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	group,
	resource_property,
	state_type,
	state_type_relationship,
	task_element,
	task_element_relationship,
	task_method,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(task_element,
	task_method,
	task_objective);
END_TYPE;

TYPE ss_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	ascribable_state,
	group,
	resource_property,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(action_property,
	applied_action_method_assignment,
	resource_property,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment);
END_TYPE;

TYPE ss_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(action_method,
	action_resource,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	executed_action,
	task_element,
	task_method);
END_TYPE;

TYPE ss_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	group,
	resource_property,
	resource_property_representation,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	applied_action_assignment,
	applied_action_method_assignment,
	group,
	resource_property,
	resource_property_representation,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(action_method,
	action_method_relationship,
	applied_action_assignment,
	applied_action_method_assignment,
	group,
	task_element,
	task_method,
	task_objective);
END_TYPE;

		
	ENTITY ss_characterizable_applied_action_assignment
	  SUBTYPE OF (applied_action_assignment, characterized_object);
	END_ENTITY;
	
	ENTITY ss_characterizable_applied_action_method_assignment
	  SUBTYPE OF (applied_action_method_assignment, characterized_object);
	END_ENTITY;

TYPE ss_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(action_method_relationship,
	action_resource,
	applied_action_method_assignment,
	group,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(action,
	action_method,
	action_property,
	action_relationship,
	action_resource,
	action_resource_relationship,
	applied_action_assignment,
	applied_action_method_assignment,
	executed_action);
END_TYPE;

TYPE ss_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(action,
	action_method,
	action_property,
	action_relationship,
	action_resource,
	action_resource_relationship,
	applied_action_assignment,
	executed_action,
	task_method,
	task_objective);
END_TYPE;

TYPE ss_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	group,
	resource_property,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE ss_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(action,
	action_method,
	action_method_relationship,
	action_property,
	action_relationship,
	action_resource,
	action_resource_relationship,
	action_resource_requirement,
	action_resource_requirement_relationship,
	applied_action_method_assignment,
	group,
	resource_property,
	task_element,
	task_element_relationship,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

END_SCHEMA;


