(* 
 $Id: mim.exp,v 1.5 2002/06/27 16:04:03 robbod Exp $
 N1196 - ISO/TS - 10303-1124 Document structure - EXPRESS MIM 
*)


SCHEMA Document_structure_mim;
USE FROM Document_definition_mim; -- ISO/CD TS 10303-1123
USE FROM File_identification_mim; -- ISO/CD TS 10303-1127
USE FROM document_schema (document_relationship); -- ISO 10303-41
USE FROM product_definition_schema -- ISO 10303-41
	(product_definition_relationship,
	 product_definition_formation_relationship);
END_SCHEMA;

