(*
  $Id: mim.exp,v 1.2 2009 LMR $
  ISO TC184/SC4/WG12 N4xxx - ISO/CD-TS 10303-1pc4 Sketch - EXPRESS MIM
*)

SCHEMA Sketch_mim;

-- USE FROM Elementatary_geometry_mim;  -- ISO 10303-1pc3

USE FROM Foundation_representation_mim;  -- ISO 10303-1006

USE FROM Parameterization_and_variational_representation_mim; -- ISO 10303-1pc1
 
USE FROM Topologically_bounded_surface_mim;  -- ISO 10303-1511


USE FROM sketch_schema;  -- ISO 10303-108


END_SCHEMA;
