(*
 $Id: mim.exp,v 1.2 2009/12/11 20:05:04 lothartklein Exp $
 ISO TC184/SC4/WG12 N6876 - ISO/TS 10303-1bsg Bspline_geometry - EXPRESS MIM
*)

SCHEMA Bspline_geometry_mim;

USE FROM Basic_geometry_mim; -- ISO 10303-1652


USE FROM geometry_schema    -- ISO 10303-42
(b_spline_curve,
 b_spline_surface,
 bezier_curve,
 bezier_surface,
 quasi_uniform_curve,
 quasi_uniform_surface,
 rational_b_spline_curve,
 rational_b_spline_surface, 
 uniform_curve,
 uniform_surface);

END_SCHEMA;
