(*
   $Id: arm.exp,v 1.2 2003/01/14 22:27:12 darla Exp $
   N - ISO/CD-TS - 10303- ap203e2_configuration_management - EXPRESS ARM*)
SCHEMA AP203e2_configuration_management_arm;
USE FROM Assembly_structure_arm;
USE FROM Configuration_effectivity_arm;
USE FROM Effectivity_application_arm;
USE FROM Time_interval_arm;
USE FROM Project_arm;
USE FROM Date_time_assignment_arm;
END_SCHEMA; -- Configuration_management_arm;
