(*
   $Id: mim.exp,v 1.5 2009/07/22 20:21:58 darla Exp $
   ISO/CD-TS WG12 N6714 - 10303-1377 cfd_model - EXPRESS MIM*)

SCHEMA Cfd_model_mim;

USE FROM Analysis_mim;

USE FROM Cfd_conditions_mim;

USE FROM Cfd_equations_mim;

USE FROM Cfd_results_mim;

USE FROM Cfd_specified_general_property_mim;
 
USE FROM Mesh_connectivity_mim;

USE FROM Mesh_topology_mim;

USE FROM hierarchy_schema;

USE FROM domain_schema;

END_SCHEMA;

