(*
   $Id: mim.exp,v 1.3 2008/06/11 20:24:35 darla Exp $
   N - ISO/CD-TS - 10303- cfd_model - EXPRESS MIM*)

SCHEMA Cfd_model_mim;

USE FROM Analysis_mim;

USE FROM Cfd_conditions_mim;

USE FROM Cfd_equations_mim;

USE FROM Cfd_results_mim;

USE FROM Cfd_specified_general_property_mim;
 
USE FROM Mesh_connectivity_mim;

USE FROM Mesh_topology_mim;

USE FROM hierarchy_schema;

USE FROM domain_schema;

END_SCHEMA;

