(*
   $Id: mim.exp,v 1.1 2009/10/14 09:37:39 lothartklein Exp $
   WG12N7176 - ISO/TS 10303-1520 product_data_quality_definition - EXPRESS MIM
*)

SCHEMA Product_data_quality_definition_mim;

  USE FROM Product_data_quality_criteria_mim;

  USE FROM Product_data_quality_inspection_result_mim;

  USE FROM Product_view_definition_mim;

  USE FROM Date_time_assignment_mim;

  USE FROM Person_organization_assignment_mim;

  USE FROM Product_data_quality_definition_schema;

  TYPE pdq_date_or_date_time_item = SELECT BASED_ON date_and_time_item WITH
    (Data_quality_definition);
  END_TYPE;

  TYPE pqd_organization_or_person_in_organization_item = SELECT BASED_ON person_and_organization_item WITH
    (Data_quality_definition);
  END_TYPE;


END_SCHEMA;
