(*

	WG12 N525 								2000-05-30

	EXPRESS Declarations for ISO 10303-41: 3rd Edition
*)

SCHEMA security_classification_schema; 

REFERENCE FROM support_resource_schema   -- ISO 10303-41
  (label,
   text); 


ENTITY security_classification;
  name : label;
  purpose : text;
  security_level : security_classification_level;
END_ENTITY;

ENTITY security_classification_level;
  name : label;
END_ENTITY;

END_SCHEMA;  -- security_classification_schema
