(*
   $Id: mim.exp,v 1.6 2005/02/10 12:37:58 liutkus Exp $
   ISO TC184/SC4/WG12 N1615 - ISO/CD-TS 10303-1605 Ap210 assembly functional requirements - EXPRESS MIM
*)


SCHEMA Ap210_assembly_functional_requirements_mim;
	USE FROM Ap210_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Functional_decomposition_to_assembly_design_mim;	-- ISO/TS 10303-1675
	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_mim;	-- ISO/TS 10303-1678
	USE FROM Physical_node_requirement_to_implementing_component_allocation_mim;	-- ISO/TS 10303-1723
	USE FROM Planned_characteristic_mim;	-- ISO/TS 10303-1733
	USE FROM Test_requirement_allocation_mim;	-- ISO/TS 10303-1751
END_SCHEMA;

