(*
   $Id: arm.exp,v 1.1 2016/11/21 17:00:36 kevletu Exp $
   N - ISO/CD-TS - 10303- surface_visual_texture - EXPRESS ARM*)
(* UNDER DEVELOPMENT *)
SCHEMA Surface_visual_texture_arm;

USE FROM Tessellated_geometry_arm;
USE FROM Support_resource_arm; -- to get label

TYPE tessellated_face_or_tessellated_surface_set = SELECT
    (Tessellated_face,
     Tessellated_surface_set);
END_TYPE; 

TYPE texture_file_type = ENUMERATION OF
    (JPEG, 
    PNG,
    GIF,
    TIFF,
    BMP,
    DDS,
    TGA,
    other);
END_TYPE;

TYPE zero_to_one_bounded_non_negative_real = REAL;
  WHERE
      WR1: { 0. <= SELF <= 1. };
END_TYPE;

(*ENTITY texture_style_specification
    SUBTYPE OF (founded_item)
    ABSTRACT SUPERTYPE;
END_ENTITY; *)

ENTITY Texture_style_tessellation_specification
   ABSTRACT SUPERTYPE
   SUBTYPE OF (); -- Founded_item in ARM ? 
END_ENTITY;

ENTITY Single_texture_style_tessellation_specification
   SUBTYPE OF (Texture_style_tessellation_specification);
   texture_image: label;
   texture_coordinates: LIST [1:?] OF LIST [2:2] OF zero_to_one_bounded_non_negative_real;
   texture_format: texture_file_type;
   repeating_pattern: BOOLEAN;
END_ENTITY;


END_SCHEMA;
