(*
   $Id: arm.exp,v 1.2 2004/11/19 09:59:42 budreckytej Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Electrical network definition - EXPRESS ARM
(* UNDER DEVELOPMENT *)

SCHEMA Electrical_network_definition_arm;

USE FROM Network_functional_design_view_arm;

  ENTITY Electrical_network_definition
    SUBTYPE OF (Functional_unit_network_definition);
  END_ENTITY; -- electrical_network_definition
  
END_SCHEMA;  
