(*
   $Id: arm.exp,v 1.26 2006/04/14 07:11:34 liutkus Exp $
   ISO TC184/SC4/WG3 N2015 - ISO/TS 10303-1617 AP210 interconnect design - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1650
*)

SCHEMA Ap210_interconnect_design_arm;
	USE FROM Ap210_interconnect_design_for_microwave_arm;	-- ISO/TS 10303-1618
(* add constraints prohibiting edge curve for printed component *)
(**   (- spline curves ...)
   - edge terminal, cross-section_terminals !!
   - guided_wave_terminal
*)   
END_SCHEMA;
