(*
   $Id: arm.exp,v 1.7 2005/01/04 07:10:54 kovaliovas Exp $
   ISO TC184/SC4/WG12 N1650 - ISO/CD-TS 10303-1617 Ap210 interconnect design - EXPRESS ARM
*)

SCHEMA Ap210_interconnect_design_arm;
	USE FROM Ap210_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Area_2d_arm;	-- ISO/TS 10303-1631
	USE FROM Characteristic_arm;	-- ISO/TS 10303-1654
	USE FROM Chemical_substance_arm;	-- ISO/TS 10303-1655
	USE FROM Connectivity_allocation_to_physical_network_arm;	-- ISO/TS 10303-1658
	USE FROM Design_specific_assignment_to_interconnect_usage_view_arm;	-- ISO/TS 10303-1663
	USE FROM Device_marking_arm;	-- ISO/TS 10303-1664
	USE FROM Fill_area_arm;	-- ISO/TS 10303-1672
	USE FROM Interconnect_2d_shape_arm;	-- ISO/TS 10303-1682
	USE FROM Interconnect_3d_shape_arm;	-- ISO/TS 10303-1683
	USE FROM Interconnect_module_to_assembly_module_relationship_arm;	-- ISO/TS 10303-1685
	USE FROM Interconnect_non_planar_shape_arm;	-- ISO/TS 10303-1688
	USE FROM Land_arm;	-- ISO/TS 10303-1692
	USE FROM Layered_interconnect_module_2d_design_arm;	-- ISO/TS 10303-1695
	USE FROM Layered_interconnect_module_3d_design_arm;	-- ISO/TS 10303-1696
	USE FROM Layered_interconnect_module_3d_shape_arm;	-- ISO/TS 10303-1697
	USE FROM Layout_macro_definition_arm;	-- ISO/TS 10303-1701
	USE FROM Pre_defined_datum_symbol_arm;	-- ISO/TS 10303-1734
	USE FROM Via_component_arm;	-- ISO/TS 10303-1754

(** Most likely it is in CC Interconnect_module *)    
	SUBTYPE_CONSTRAINT laminate_component_interface_terminal_subtypes FOR Laminate_component_interface_terminal; 
		 (ONEOF (Non_functional_land_interface_terminal,
		 Printed_connector_component_interface_terminal,
		 Component_termination_passage_interface_terminal,
		 Land_interface_terminal));
	END_SUBTYPE_CONSTRAINT;

(** Most likely it is in CC Interconnect_module *)    
	SUBTYPE_CONSTRAINT laminate_component_join_terminal_subtypes FOR Laminate_component_join_terminal; 
		 (ONEOF (Component_termination_passage_join_terminal,
		 Land_join_terminal,
		 Non_functional_land_join_terminal,
		 Embedded_component_terminal,
		 Printed_component_join_terminal));
	END_SUBTYPE_CONSTRAINT;
   
(** It most likely should be in Interconnect_module CC *)
SUBTYPE_CONSTRAINT planar_projected_shape_subtypes FOR Planar_projected_shape;  
	(ONEOF ((Assembly_component_2d_shape ANDOR
	 (ONEOF (Part_template_planar_shape,
	 Footprint_definition_shape,
	 Padstack_definition_shape,
	 Physical_unit_planar_shape))),
	 Design_intent_modification_planar_shape,
	 Stratum_feature_planar_shape,
	 Stratum_planar_shape));
END_SUBTYPE_CONSTRAINT; 

(** Pre_defined_datum_symbol_arm and Layered_interconnect_module_3d_shape_arm are not linked in any way.
Most likely it should be defined in Interconnect_module CC *)
 SUBTYPE_CONSTRAINT shape_definition_3d_intersection_subtypes FOR Shape_definition_3d_intersection;  
	 (ONEOF (Edge_segment_cross_section,
	 Pre_defined_perpendicular_datum_plane_symbol_3d_2d_relationship,
	 Pre_defined_perpendicular_datum_axis_symbol_3d_2d_relationship,
	 Pre_defined_parallel_datum_axis_symbol_3d_2d_relationship));
 END_SUBTYPE_CONSTRAINT;  
   
   
END_SCHEMA;
