(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 interconnect design - EXPRESS ARM
*)

SCHEMA Ap210_interconnect_design_arm;
   USE FROM AP210_product_data_management_arm;
   USE FROM Characteristic_arm;
   USE FROM Connectivity_allocation_to_physical_network_arm;
   USE FROM Design_specific_assignment_to_interconnect_usage_view_arm;   
   USE FROM Device_marking_arm;   
   USE FROM Fill_area_arm;   
   USE FROM Interconnect_module_to_assembly_module_relationship_arm;
   USE FROM Interconnect_non_planar_shape_arm;
   USE FROM Interconnect_2d_shape_arm;
   USE FROM Interconnect_3d_shape_arm;
   USE FROM Land_arm;
   USE FROM Layered_interconnect_module_2d_design_arm;
   USE FROM Layered_interconnect_module_3d_design_arm;   
   USE FROM Layered_interconnect_module_3d_shape_arm;      
   USE FROM Pre_defined_datum_symbol_arm;

(** Most likely it is in CC Interconnect_module *)    
	SUBTYPE_CONSTRAINT laminate_component_interface_terminal_subtypes FOR Laminate_component_interface_terminal; 
		 (ONEOF (Non_functional_land_interface_terminal,
		 Printed_connector_component_interface_terminal,
		 Component_termination_passage_interface_terminal,
		 Land_interface_terminal));
	END_SUBTYPE_CONSTRAINT;

(** Most likely it is in CC Interconnect_module *)    
	SUBTYPE_CONSTRAINT laminate_component_join_terminal_subtypes FOR Laminate_component_join_terminal; 
		 (ONEOF (Component_termination_passage_join_terminal,
		 Land_join_terminal,
		 Non_functional_land_join_terminal,
		 Embedded_component_terminal,
		 Printed_component_join_terminal));
	END_SUBTYPE_CONSTRAINT;
   
(** It most likely should be in Interconnect_module CC *)
SUBTYPE_CONSTRAINT planar_projected_shape_subtypes FOR planar_projected_shape;  
	(ONEOF ((Assembly_component_2d_shape ANDOR
	 (ONEOF (Part_template_planar_shape,
	 Footprint_definition_shape,
	 Padstack_definition_shape,
	 Physical_unit_planar_shape))),
	 Design_intent_modification_planar_shape,
	 Stratum_feature_planar_shape,
	 Stratum_planar_shape));
END_SUBTYPE_CONSTRAINT; 

(** Pre_defined_datum_symbol_arm and Layered_interconnect_module_3d_shape_arm are not linked in any way.
Most likely it should be defined in Interconnect_module CC *)
 SUBTYPE_CONSTRAINT shape_definition_3d_intersection_subtypes FOR shape_definition_3d_intersection;  
	 (ONEOF (Edge_segment_cross_section,
	 Pre_defined_perpendicular_datum_plane_symbol_3d_2d_relationship,
	 Pre_defined_perpendicular_datum_axis_symbol_3d_2d_relationship,
	 Pre_defined_parallel_datum_axis_symbol_3d_2d_relationship));
 END_SUBTYPE_CONSTRAINT;  
   
   
END_SCHEMA;
