(*
 $Id: checkModuleMain.js,v 1.11 2004/10/20 08:33:34 robbod Exp $
 ISO TC184/SC4/WG12 N1226 - ISO/TS 10303-1032 Shape property assignment - EXPRESS MIM
*)

SCHEMA Shape_property_assignment_mim;

USE FROM Elemental_geometric_shape_mim;

USE FROM Elemental_geometric_shape_mim;

USE FROM External_model_mim;

USE FROM Foundation_representation_mim;

USE FROM product_property_definition_schema
(characterized_object,
 product_definition_shape,
 shape_aspect,
 shape_aspect_relationship);

USE FROM product_property_representation_schema
(shape_definition_representation);

USE FROM Product_view_definition_mim;

USE FROM Product_view_definition_relationship_mim;

END_SCHEMA;
