(*
$Id: $
ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Textual expression representation - EXPRESS ARM
*) 

SCHEMA Textual_expression_representation_arm; 

USE FROM Foundation_representation_arm;    -- ISO/TS 10303-1006


ENTITY Parameter_representation_item
  SUBTYPE OF (Textual_expression_representation_item);
END_ENTITY;

ENTITY Textual_expression_representation_item
  ABSTRACT SUPERTYPE 
  SUBTYPE OF (Representation_item);
  description : STRING;
  encoding : STRING;
  my_value : OPTIONAL Representation_item;
END_ENTITY;

ENTITY Textual_function_representation_item
  SUBTYPE OF (Textual_expression_representation_item);
  function_text : STRING;
  parameters : SET[1:?] OF Textual_expression_representation_item;
END_ENTITY;

END_SCHEMA;  -- Textual_expression_representation_arm

