(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Interconnect physical requirement allocation - EXPRESS ARM
*)

 SCHEMA Interconnect_physical_requirement_allocation_arm;

USE FROM Requirement_decomposition_arm;
USE FROM Manufacturing_technology_arm;

	SUBTYPE_CONSTRAINT material_removal_feature_template_subtypes FOR material_removal_feature_template; 
	    (ONEOF (electrical_isolation_removal_template,
	 	thermal_isolation_removal_template));
	END_SUBTYPE_CONSTRAINT;

 	TYPE thermal_isolation_removal_structure_or_template = EXTENSIBLE GENERIC_ENTITY SELECT
 		(thermal_isolation_removal_template);
	END_TYPE;
		
  ENTITY Thermal_isolation_removal_template
    SUBTYPE OF (Material_removal_feature_template);
  END_ENTITY; -- thermal_isolation_removal_template

  ENTITY Thermal_isolation_requirement
  	SUBTYPE OF (Requirement_view_definition);
  	INVERSE
			thermal_isolation_spacing_requirement		: Layout_spacing_requirement_occurrence FOR associated_definition;  	
      effective_current_capacity_requirement 	: Requirement_definition_property FOR associated_definition;
      angular_orientation_requirement        	: Requirement_definition_property FOR associated_definition;
  END_ENTITY; -- thermal_isolation_requirement
  
 END_SCHEMA; -- Interconnect_physical_requirement_allocation_arm
