(*
   $Id: mim.exp,v 1.15 2005/12/28 22:19:30 liutkus Exp $
   ISO TC184/SC4/WG12 N3457 - ISO/CD-TS 10303-1689 Interconnect physical requirement allocation - EXPRESS MIM
*)


SCHEMA Interconnect_physical_requirement_allocation_mim;
	USE FROM Fabrication_technology_mim;	-- ISO/TS 10303-1670
	
	USE FROM Requirement_view_definition_relationship_mim; -- ISO/TS 10303-1142	
	
	USE FROM Integral_shield_mim; -- ISO/TS 10303-xxxx	

	SUBTYPE_CONSTRAINT ipra_material_removal_feature_template_subtypes FOR material_removal_feature_template; 
	    (ONEOF (electrical_isolation_removal_template,
	 	thermal_isolation_removal_template));
	END_SUBTYPE_CONSTRAINT;

TYPE ipra_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH 
     (thermal_isolation_removal_template);
END_TYPE; 

ENTITY dependent_electrical_isolation_removal_template
  SUBTYPE OF (dependent_template, electrical_isolation_removal_template);
END_ENTITY;

ENTITY dependent_thermal_isolation_removal_template
  SUBTYPE OF (dependent_template, thermal_isolation_removal_template);
END_ENTITY;
  
ENTITY electrical_isolation_removal_template
  SUBTYPE OF (material_removal_feature_template);
END_ENTITY;

ENTITY interconnect_shield_allocation
  SUBTYPE OF (requirement_assignment);
END_ENTITY;

ENTITY thermal_isolation_removal_template
  SUBTYPE OF (material_removal_structured_template);
END_ENTITY;
	
END_SCHEMA;


