(* N727 - ISO/TS - 10303-1017 Product identification - EXPRESS ARM *)
   
SCHEMA Product_identification_arm;

   
USE FROM Product_categorisation_arm; -- Product categorisation

ENTITY Product;
  id         : STRING;
  name       : STRING;
  description: OPTIONAL STRING;
END_ENTITY;

END_ENTITY;

ENTITY Product_category_assignment; 
  category : Product_category;
  products : SET[1:?] OF Product;
END_ENTITY;
  
END_SCHEMA;

