(*
  $Id$
ISO TC184/SC4/WG12 N7946 - ISO/TS 10303-1311 Associative draughting elements - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N9664
*)

SCHEMA Associative_draughting_elements_mim;

USE FROM Shape_property_assignment_mim; -- ISO/TS 10303-1032

USE FROM Draughting_element_mim; -- ISO/TS 10303-1310

USE FROM aic_associative_draughting_elements; --  ISO 10303-520

USE FROM draughting_dimension_schema(dimension_callout); --  ISO 10303-101

USE FROM geometric_model_schema (geometric_set); -- ISO 10303-42

USE FROM draughting_element_schema(
         annotation_plane,
         draughting_model_item_definition,
         des_annotation_representation_select,
         draughting_model_item_association,
         tessellated_annotation_occurrence); --ISO 10303-46

USE FROM presentation_definition_schema (
         annotation_curve_occurrence,
         annotation_fill_area_occurrence,
         annotation_point_occurrence,
         annotation_symbol_occurrence,
         annotation_text_occurrence
         ); --ISO 10303-46

USE FROM product_property_definition_schema(
        product_definition_shape,
        property_definition,
        shape_aspect, 
        shape_aspect_relationship,
        shape_definition); -- ISO 10303-41

END_SCHEMA;  
