(* N - ISO/TS - 10303-1026 Assembly structure - EXPRESS MIM *)
{iso standard 10303 part (11) version (4)}      

SCHEMA Part_structure_mim;

USE FROM Product_view_definition_relationship_mim; -- ISO/TS 10303-1019
USE FROM Value_with_unit_mim; -- ISO/TS 10303-1054

USE FROM product_structure_schema -- ISO 10303-44
  (assembly_component_usage,
   next_assembly_usage_occurrence,
   promissory_usage_occurrence,
   quantified_assembly_component_usage);

END_SCHEMA;




