(*
  $Id: arm.exp,v 1.4 2002/09/06 18:16:44 ckreiler Exp $
  ISO/TC184/SC4 WG12N1352 - ISO/CD-TS - 10303-1275 External class - EXPRESS ARM
*)

SCHEMA External_class_arm; 

USE FROM Class_arm;    -- ISO/CD-TS 10303-1070


ENTITY External_class
  SUBTYPE OF (Class);
  external_source : External_class_library;
END_ENTITY;

ENTITY External_class_library;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

END_SCHEMA;  -- External_class_arm
