(*
  $Id: arm.exp,v 1.1 2002/07/12 12:17:33 robbod Exp $
*)


SCHEMA External_class_arm;

USE FROM Class_arm;

TYPE class_source_select = EXTENSIBLE SELECT 
  (External_class_library);
END_TYPE;

ENTITY External_class
SUBTYPE OF (Class);
  external_source : class_source_select;
END_ENTITY;

ENTITY External_class_library;
  id : STRING;
  name : STRING;
  description : OPTIONAL STRING;
END_ENTITY;

END_SCHEMA;
