(*
   $Id: mkmodule.js,v 1.41 2004/10/11 20:17:49 thendrix Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Design specific assignment to interconnect usage view - EXPRESS ARM
*)

SCHEMA Design_specific_assignment_to_interconnect_usage_view_arm;

USE FROM Layered_interconnect_module_with_printed_component_design_arm;

USE FROM Interconnect_module_usage_view_arm;

USE FROM Fabrication_joint_arm (fabricated_feature_select);

 	TYPE interconnect_or_assembly_module_select = EXTENSIBLE GENERIC_ENTITY SELECT
 		(component_termination_passage_interface_terminal,
     printed_connector_component_interface_terminal);
	END_TYPE;

  ENTITY Component_terminal_to_interconnect_module_interface_terminal_assignment
    SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
      SELF\component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal	: interconnect_module_interface_terminal;
      SELF\component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal	: interconnect_or_assembly_module_select;
    UNIQUE
      UR1 : usage_view_terminal;
  END_ENTITY; -- component_terminal_to_interconnect_module_interface_terminal_assignment

  ENTITY Component_terminal_to_interconnect_module_join_terminal_assignment
    SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
      SELF\component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal : interconnect_module_join_terminal;
      SELF\component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal	: fabricated_feature_select;
    UNIQUE
      UR1 : usage_view_terminal;
  END_ENTITY; -- component_terminal_to_interconnect_module_join_terminal_assignment

  ENTITY Stratum_concept_to_physical_usage_view_assignment;
      assigned_design_object : stratum_concept;
      defined_part_feature   : part_feature;
      purpose                : OPTIONAL STRING; --ee_name;
    UNIQUE
    	UR1 : defined_part_feature;
    WHERE
      WR1 : NOT ('AP210_ARM.INTERCONNECT_MODULE_TERMINAL' IN TYPEOF(defined_part_feature));
  END_ENTITY; -- stratum_concept_to_physical_usage_view_assignment

END_SCHEMA;
