(*
   $Id: MimGenerator.java,v 1.6 2004/11/22 16:26:37 raimundas Exp $
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Design specific assignment to interconnect usage view - EXPRESS MIM
*)


SCHEMA Design_specific_assignment_to_interconnect_usage_view_mim;
	USE FROM Fabrication_joint_mim;
	USE FROM Interconnect_module_usage_view_mim;
	USE FROM Layered_interconnect_module_with_printed_component_design_mim;
END_SCHEMA;

