(*
   $Id: arm.exp,v 1.22 2005/11/24 11:55:19 liutkus Exp $
   ISO TC184/SC4/WG12 N3624 - ISO/CD-TS 10303-1751 Test requirement allocation - EXPRESS ARM
*)

SCHEMA Test_requirement_allocation_arm;

	USE FROM Functional_assignment_to_part_arm;	-- ISO/TS 10303-1674
	USE FROM Requirement_decomposition_arm;	-- ISO/TS 10303-1740
	USE FROM Functional_usage_view_arm;	-- ISO/TS 10303-1705

   TYPE tra_requirement_assignment_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assignment_item WITH 
      (Product_version);
   END_TYPE; 

  ENTITY Test_requirement_allocation
    SUBTYPE OF (Requirement_assignment);
      SELF\Requirement_assignment.assigned_to : Product_version;
      analytical_model_based_test_access                : OPTIONAL SET[1:?] OF Analytical_model_port_assignment; --part_feature_model_port_assignment;
      functional_specification_based_test_access        : OPTIONAL SET[1:?] OF Functional_usage_view_to_part_terminal_assignment;
    WHERE
      WR1 : EXISTS(analytical_model_based_test_access) XOR EXISTS(functional_specification_based_test_access);
      WR2 : NOT (EXISTS(functional_specification_based_test_access)) OR 
      (SIZEOF(QUERY(fa <* functional_specification_based_test_access | NOT 
      (fa.physical_usage_view_terminal\Shape_element.containing_shape.defined_version = SELF\Requirement_assignment.assigned_to))) = 0);
      WR3 : SIZEOF(QUERY( rdp <* USEDIN(SELF\Requirement_assignment.assigned_requirement,
      'REQUIREMENT_DECOMPOSITION_ARM.PREDEFINED_REQUIREMENT_VIEW_DEFINITION.ASSOCIATED_DEFINITION') |
       NOT(rdp\Product_view_definition.initial_context.life_cycle_stage = 'test')
       )) = 0;      
  END_ENTITY;

END_SCHEMA;  

